Batch Matmul Op
flexflow/FlexFlow pull request #1023
Opened 2023-08-22 21:12 UTC by KateUnger

**Description of changes:**
- Updates Batch Matmul Operation

**TODO**: Change `batch_matmul_kernels.cpp` and `batch_matmul_kernels.cu`

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #1048

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1023)

2023-08-23 11:41 UTC, lockshaw approved these changes

2023-08-29 15:36 UTC, lockshaw requested changes
> Reviewed 6 of 6 files at r1, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 25 unresolved discussions (waiting on @KateUnger)

___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 23 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0ow-gD-7ulJJcmp6w:-Nd0ow-gD-7ulJJcmp6x:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L23)):*
> ```objc
> 
> BMMPerDeviceState init_kernel(PerDeviceFFHandle handle,
>                   Allocator allocator,
> ```





_Suggestion:_
```objc
BMMPerDeviceState init_kernel(PerDeviceFFHandle const &handle,
                  Allocator const &allocator,
```
___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0p6mS-RM6WID9CHua:-Nd0p6mS-RM6WID9CHub:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L29)):*
> ```objc
> void forward_kernel(ffStream_t stream,
>                     BMMPerDeviceState const *meta,
>                     float *o_ptr,
> ```





_Suggestion:_
```objc
void forward_kernel(ffStream_t stream,
                    BMMPerDeviceState const &meta,
                    float *output_ptr,
```
___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 30 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0pS81B02q1cQme10K:-Nd0pS81B02q1cQme10L:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L30)):*
> ```objc
>                     BMMPerDeviceState const *meta,
>                     float *o_ptr,
>                     float const *a_ptr,
> ```





_Suggestion:_
```objc
                    float const *lhs_input_ptr,
```
___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 31 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0pUKi2Ir8mjSW2ikD:-Nd0pUKi2Ir8mjSW2ikE:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L31)):*
> ```objc
>                     float *o_ptr,
>                     float const *a_ptr,
>                     float const *b_ptr,
> ```





_Suggestion:_
```objc
                    float const *rhs_input_ptr,
```
___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 32 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0sSwQ7mzZHb5GPQyD:-Nd0sSwQ7mzZHb5GPQyE:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L32)):*
> ```objc
>                     float const *a_ptr,
>                     float const *b_ptr,
>                     float const *c_ptr,
> ```


___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 41 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0p9Pl9f7qdcdvM5QO:-Nd0p9Pl9f7qdcdvM5QP:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L41)):*
> ```objc
> void backward_kernel(ffStream_t stream,
>                     BMMPerDeviceState const *meta,
>                      float const *o_ptr,
> ```





_Suggestion:_
```objc
                    BMMPerDeviceState const &meta,
                     float const *o_ptr,
```
___
*[`lib/kernels/src/hip/batch_matmul_kernels.cpp` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0pwsj8rM__GPn6fze:-Nd0pwsj8rM__GPn6fzf:bbtfig6) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/src/hip/batch_matmul_kernels.cpp#L0)):*
If you have to modify the `.cpp` file (i.e., AMD) you probably also have to modify the `.cu` file (i.e., CUDA)
___
*[`lib/kernels/src/hip/batch_matmul_kernels.cpp` line 33 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0pLL18Ca5xwLc9ddZ:-Nd0pLL18Ca5xwLc9dd_:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/src/hip/batch_matmul_kernels.cpp#L33)):*
> ```cpp
> void forward_kernel(hipStream_t stream,
>                     BatchMatmulPerDeviceState const *meta,
>                     float *o_ptr,
> ```





_Suggestion:_
```cpp
void forward_kernel(hipStream_t stream,
                    BatchMatmulPerDeviceState const &meta,
                    float *o_ptr,
```
___
*[`lib/op-attrs/include/op-attrs/ops/batch_matmul.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0qJo24TdNp4NTrQlX:-Nd0qJo24TdNp4NTrQlY:b-tlclzb) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/op-attrs/include/op-attrs/ops/batch_matmul.h#L15)):*
> ```objc
> FF_VISITABLE_STRUCT(BatchMatmulAttrs, a_seq_length_dim, b_seq_length_dim);
> 
> int get_aSeqLengthDim(BatchMatmulAttrs const &attrs);
> ```

Probably not necessary--the additional functions were present for attention because iirc they involved some computation
___
*[`lib/runtime/include/runtime/config.h` line 110 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0qaOD32DsUfYEBnK4:-Nd0qaOD32DsUfYEBnK5:b-7crtzv) ([raw file](https://github.com/flexflow/FlexFlow/blob/5458923bc344d2cefbd6bc18b7c3719e73291ba8/lib/runtime/include/runtime/config.h#L110)):*
> ```objc
>   FFIterationConfig();
>   void reset();
>   req<int> seq_length;
> ```

`req` shouldn't be necessary here since it's using nonstandard construction (so it's allowed to be default constructible)



_Suggestion:_
```objc
  int seq_length;
```
___
*[`lib/runtime/src/ops/batch_matmul.h` line 86 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0r1g--OmKFFJEEMwZ:-Nd0r1g--OmKFFJEEMw_:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.h#L86)):*
> ```objc
> /* public: */
> /*   int a_seq_length_dim, b_seq_length_dim; */
> /* }; */
> ```


___
*[`lib/runtime/src/ops/batch_matmul.h` line 91 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0qvvm8u2D1g6Ltf1m:-Nd0qvvm8u2D1g6Ltf1n:bamuiv9) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.h#L91)):*
> ```objc
> 
> #endif
> ```

Why is there this giant commented-out block after the `#endif`?
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 20 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0rBga1fNMsgBAgsXC:-Nd0rBga1fNMsgBAgsXD:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.cc#L20)):*
> ```cpp
> // #include "kernels/profiling.h"
> // #include "legion/legion_utilities.h"
> // #include "tasks.h"
> ```


___
*[`lib/runtime/src/ops/batch_matmul.cc` line 77 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0rW1tE7mxYIipWg_t:-Nd0rW1tE7mxYIipWg_u:b-61dxrc) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.cc#L77)):*
> ```cpp
> 
> static DeviceSpecificArg<BMMPerDeviceState> init_task_impl(TaskArgumentAccessor const &acc) {
>   auto const a_seq_length_dim = acc.get_argument<int>(A_SEQ_LENGTH_DIM);
> ```

As long as the type is short you can skip `auto`--in general `auto` harms readability unless the type name is long (here it's a bit weird because the type is repeated twice, but if the type name is super short I'd lean toward using the type name)



_Suggestion:_
```cpp
  int const a_seq_length_dim = acc.get_argument<int>(A_SEQ_LENGTH_DIM);
```
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 89 at r1](https [...]

2023-08-29 18:37 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 25 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 23 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0ow-gD-7ulJJcmp6w:-Nd1KOqb-tibyuIJoOEo:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L23)):*
> ```objc
> 
> BMMPerDeviceState init_kernel(PerDeviceFFHandle handle,
>                   Allocator allocator,
> ```

Done.
___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0p6mS-RM6WID9CHua:-Nd1KnaiCtXp34jgHVsY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L29)):*
> ```objc
> void forward_kernel(ffStream_t stream,
>                     BMMPerDeviceState const *meta,
>                     float *o_ptr,
> ```

Done.
___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 30 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0pS81B02q1cQme10K:-Nd1Ks0k6l1Hrz2L3-t5:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L30)):*
> ```objc
>                     BMMPerDeviceState const *meta,
>                     float *o_ptr,
>                     float const *a_ptr,
> ```

Done.
___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 31 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0pUKi2Ir8mjSW2ikD:-Nd1KyPV9LCCJ9KtfE2R:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L31)):*
> ```objc
>                     float *o_ptr,
>                     float const *a_ptr,
>                     float const *b_ptr,
> ```

Done.
___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 32 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0sSwQ7mzZHb5GPQyD:-Nd1Ky6b4Vp6QL4hj2xE:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L32)):*
> ```objc
>                     float const *a_ptr,
>                     float const *b_ptr,
>                     float const *c_ptr,
> ```

Done.
___
*[`lib/kernels/include/kernels/batch_matmul_kernels.h` line 41 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0p9Pl9f7qdcdvM5QO:-Nd1Lpzj5jv7OT17p-BA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/include/kernels/batch_matmul_kernels.h#L41)):*
> ```objc
> void backward_kernel(ffStream_t stream,
>                     BMMPerDeviceState const *meta,
>                      float const *o_ptr,
> ```

Done.
___
*[`lib/kernels/src/hip/batch_matmul_kernels.cpp` line 33 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0pLL18Ca5xwLc9ddZ:-Nd1OkGcCYqN8GsPHy60:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/src/hip/batch_matmul_kernels.cpp#L33)):*
> ```cpp
> void forward_kernel(hipStream_t stream,
>                     BatchMatmulPerDeviceState const *meta,
>                     float *o_ptr,
> ```

Done.
___
*[`lib/kernels/src/hip/batch_matmul_kernels.cpp` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0pwsj8rM__GPn6fze:-Nd1Okn28uyyZL3fAk4V:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/kernels/src/hip/batch_matmul_kernels.cpp#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If you have to modify the `.cpp` file (i.e., AMD) you probably also have to modify the `.cu` file (i.e., CUDA)
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/batch_matmul.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0qJo24TdNp4NTrQlX:-Nd1PU5sEC4WZ3Vdbk-a:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/op-attrs/include/op-attrs/ops/batch_matmul.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably not necessary--the additional functions were present for attention because iirc they involved some computation
</blockquote></details>

Done.
___
*[`lib/runtime/include/runtime/config.h` line 110 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0qaOD32DsUfYEBnK4:-Nd1S5L4-AbYKZ5gl-Vc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5458923bc344d2cefbd6bc18b7c3719e73291ba8/lib/runtime/include/runtime/config.h#L110)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`req` shouldn't be necessary here since it's using nonstandard construction (so it's allowed to be default constructible)
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/batch_matmul.h` line 86 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0r1g--OmKFFJEEMwZ:-Nd1SN8eCXevtoGxD7LG:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.h#L86)):*
> ```objc
> /* public: */
> /*   int a_seq_length_dim, b_seq_length_dim; */
> /* }; */
> ```

Done.
___
*[`lib/runtime/src/ops/batch_matmul.h` line 91 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0qvvm8u2D1g6Ltf1m:-Nd1SOesCFRcRkXLSVVp:b-ifswsg) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.h#L91)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is there this giant commented-out block after the `#endif`?
</blockquote></details>

Thats all the old code from the .cc file
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 20 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0rBga1fNMsgBAgsXC:-Nd1Slwg-wMe-oHYFSnt:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.cc#L20)):*
> ```cpp
> // #include "kernels/profiling.h"
> // #include "legion/legion_utilities.h"
> // #include "tasks.h"
> ```

Done.
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 77 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0rW1tE7mxYIipWg_t:-Nd1T60a3kGD64HcBrBp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.cc#L77)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

As long as the type is short you can skip `auto`--in general `auto` harms readability unless the type name is long (here it's a bit weird because the type is repeated twice, but if the type name is super short I'd lean toward using the type name)
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 89 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0roj88O18lIzC4qWj:-Nd1TEcKCQrDXOGmRWjT:bv4f7v5) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.cc#L89)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this be commented out? Or should it be removed entirely?
</blockquote></details>

I think I deleted it in the final version
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 105 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0s32gALEArnUnGiI8:-Nd1Tm3QA22j94_Su_rt:bmg6nzc) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src [...]

2023-09-11 09:52 UTC, lockshaw reviewed
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 6 unresolved discussions (waiting on @KateUnger)

___
*[`lib/op-attrs/include/op-attrs/ops/batch_matmul.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0qJo24TdNp4NTrQlX:-Ne2c_byChc5_8UWxIl_:behrz0a) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/op-attrs/include/op-attrs/ops/batch_matmul.h#L15)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No that one was fine, I meant `get_aSeqLengthDim` and `get_bSeqLengthDim`, as all they do is return public fields
___
*[`lib/runtime/src/ops/batch_matmul.h` line 91 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0qvvm8u2D1g6Ltf1m:-Ne2conh9aAyZmorm08i:bbhb3eo) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.h#L91)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Thats all the old code from the .cc file
</blockquote></details>

It should be removed
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 105 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0s32gALEArnUnGiI8:-Ne2d26M2Yxopqx6raRw:btqgaln) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.cc#L105)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

I think the asserts don't stop compilation if they don't work. I'll delete these for now
</blockquote></details>

Yeah probably have them getting compiled out--https://en.cppreference.com/w/cpp/error/assert
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 196 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0t7-v4frKnEN35ddP:-Ne2dba78yjaPqm4Bs5J:b-c0r5fa) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.cc#L196)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why were the asserts deleted?
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 156 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ne2dOk05lAKxxBtIdsT:-Ne2dOk05lAKxxBtIdsU:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/09acbe545ad4d6d1cab1e14e55bf1d7e9a638954/lib/runtime/src/ops/batch_matmul.cc#L156)):*
> ```cpp
>   auto output = acc.get_tensor<Permissions::RO>(OUTPUT);
>   auto output_grad = acc.get_tensor_grad<Permissions::RW>(OUTPUT);
>   // is this equivalent to checking `Domain` equality?
> ```


___
*[`lib/runtime/src/task_spec/runtime_arg_ref.h` line 10 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ne2dpa89wihFHZD2Chz:-Ne2dpa89wihFHZD2Ci-:b-vcki81) ([raw file](https://github.com/flexflow/FlexFlow/blob/09acbe545ad4d6d1cab1e14e55bf1d7e9a638954/lib/runtime/src/task_spec/runtime_arg_ref.h#L10)):*
> ```objc
> namespace FlexFlow {
> 
> enum class RuntimeArgRefType { FF_HANDLE, PROFILING_SETTINGS };
> ```

You'll need a `RuntimeArgRefType` value for the iteration config


<!-- Sent from Reviewable.io -->

2023-09-30 03:13 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: 6 of 15 files reviewed, 6 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/op-attrs/include/op-attrs/ops/batch_matmul.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0qJo24TdNp4NTrQlX:-NfYwNlfDumHLNu2UJUX:b7yu5e8) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/op-attrs/include/op-attrs/ops/batch_matmul.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

No that one was fine, I meant `get_aSeqLengthDim` and `get_bSeqLengthDim`, as all they do is return public fields
</blockquote></details>

Weight isn't used anywhere so I deleted it. I'll delete get_xSeqLengthDim, too—they aren't used anywhere either
___
*[`lib/runtime/src/ops/batch_matmul.h` line 91 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0qvvm8u2D1g6Ltf1m:-NfZ0hkJAnJTsrlUaYM8:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.h#L91)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It should be removed
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 105 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0s32gALEArnUnGiI8:-NfZ0lxe9M6P4T5ZwSHv:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.cc#L105)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yeah probably have them getting compiled out--https://en.cppreference.com/w/cpp/error/assert
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 196 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Nd0t7-v4frKnEN35ddP:-NfZ1eLn2-4lExScNXST:bcpxa4g) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b248cf20e560dbc2ff57d0db2bf463775177620/lib/runtime/src/ops/batch_matmul.cc#L196)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why were the asserts deleted?
</blockquote></details>

a_len and b_len don't exist and seq_lengths aren't used in backward
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 156 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ne2dOk05lAKxxBtIdsT:-NfZ1BRj7q-V6Wc1x64p:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/09acbe545ad4d6d1cab1e14e55bf1d7e9a638954/lib/runtime/src/ops/batch_matmul.cc#L156)):*
> ```cpp
>   auto output = acc.get_tensor<Permissions::RO>(OUTPUT);
>   auto output_grad = acc.get_tensor_grad<Permissions::RW>(OUTPUT);
>   // is this equivalent to checking `Domain` equality?
> ```

Done.
___
*[`lib/runtime/src/task_spec/runtime_arg_ref.h` line 10 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ne2dpa89wihFHZD2Chz:-NfZ2cZ83CXgAjGH_2xf:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/09acbe545ad4d6d1cab1e14e55bf1d7e9a638954/lib/runtime/src/task_spec/runtime_arg_ref.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You'll need a `RuntimeArgRefType` value for the iteration config
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-02 18:56 UTC, reyna-abhyankar requested changes

2023-10-02 18:56 UTC, reyna-abhyankar commented on lib/runtime/src/ops/batch_matmul.h
> +OpTaskSignature bwd_signature();
```suggestion
template <task_id_t>
OpTaskSignature init_signature();
template <>
void register_task<BATCHMATMUL_INIT_TASK_ID>();

template <task_id_t>
OpTaskSignature fwd_signature();
template <>
void register_task<BATCHMATMUL_FWD_TASK_ID>();

template <task_id_t>
OpTaskSignature bwd_signature();
```

2023-10-02 18:56 UTC, reyna-abhyankar commented on lib/runtime/src/ops/batch_matmul.cc
> +                init_signature(),
```suggestion
                init_signature<BATCHMATMUL_INIT_TASK_ID>(),
```

2023-10-02 18:56 UTC, reyna-abhyankar commented on lib/runtime/src/ops/batch_matmul.cc
> +OpTaskSignature init_signature() {
```suggestion
template <>
OpTaskSignature init_signature<BATCHMATMUL_INIT_TASK_ID>() {
```
same for fwd and bwd

2023-10-04 02:03 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: 4 of 15 files reviewed, 9 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/runtime/src/ops/batch_matmul.h` line 19 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1023#gh-1343027198:-NfsQBOX-jo7K3mSSOVP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/03b291cf37d91bb08a18af1540b03ba4f2f3f1d8/lib/runtime/src/ops/batch_matmul.h#L19)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
template <task_id_t>
OpTaskSignature init_signature();
template <>
void register_task<BATCHMATMUL_INIT_TASK_ID>();

template <task_id_t>
OpTaskSignature fwd_signature();
template <>
void register_task<BATCHMATMUL_FWD_TASK_ID>();

template <task_id_t>
OpTaskSignature bwd_signature();
```
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 247 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1023#gh-1343044336:-NfsQC1r78ErE7qjGsL5:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/03b291cf37d91bb08a18af1540b03ba4f2f3f1d8/lib/runtime/src/ops/batch_matmul.cc#L247)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
template <>
OpTaskSignature init_signature<BATCHMATMUL_INIT_TASK_ID>() {
```
same for fwd and bwd
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/batch_matmul.cc` line 260 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1023#gh-1343044006:-NfsQCeX3T7jsjBXSl1t:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/03b291cf37d91bb08a18af1540b03ba4f2f3f1d8/lib/runtime/src/ops/batch_matmul.cc#L260)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
                init_signature<BATCHMATMUL_INIT_TASK_ID>(),
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-07 07:14 UTC, reyna-abhyankar approved these changes

2023-10-09 23:05 UTC, lockshaw requested changes
> Reviewed 5 of 9 files at r6, 2 of 4 files at r7, 3 of 5 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 7 unresolved discussions (waiting on @KateUnger and @reyna-abhyankar)

___
*[`lib/kernels/src/cuda/attention_kernels.cu` line 195 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-NgLfHES1_puuNy4crCO:-NgLfHET11iZrH5PxyAg:bmk5pg8) ([raw file](https://github.com/flexflow/FlexFlow/blob/3fb5f6f43a517289eaada692be7222f36666e9dd/lib/kernels/src/cuda/attention_kernels.cu#L195)):*
> ```Cuda
>   }
> 
>   MHAPerDeviceState per_device_state = {handle,
> ```

Shouldn't this be returned?
___
*[`lib/kernels/src/cuda/attention_kernels.cu` line 209 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-NgLfJig-tVtc6Lgb6qx:-NgLfJig-tVtc6Lgb6qy:b-11604c) ([raw file](https://github.com/flexflow/FlexFlow/blob/3fb5f6f43a517289eaada692be7222f36666e9dd/lib/kernels/src/cuda/attention_kernels.cu#L209)):*
> ```Cuda
>                                         reserveSpace,
>                                         allocator};
>   free(qoSeqArray);
> ```

`allocator.deallocate`
___
*[`lib/kernels/src/cuda/batch_matmul_kernels.cu` line 35 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-NgLfZd-1XiPISbNZYEN:-NgLfZd-1XiPISbNZYEO:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/3fb5f6f43a517289eaada692be7222f36666e9dd/lib/kernels/src/cuda/batch_matmul_kernels.cu#L35)):*
> ```Cuda
>                     int a_seq_length_dim,
>                     int b_seq_length_dim,
>                     int seq_length = -1) {
> ```

Why?
___
*[`lib/op-attrs/include/op-attrs/ops/attention.h` line 15 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-NgLfrKHEUZackwU9M4h:-NgLfrKHEUZackwU9M4i:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/3fb5f6f43a517289eaada692be7222f36666e9dd/lib/op-attrs/include/op-attrs/ops/attention.h#L15)):*
> ```objc
>   req<bool> bias, add_bias_kv, add_zero_attn;
> };
> FF_VISITABLE_STRUCT_NONSTANDARD_CONSTRUCTION(MultiHeadAttentionAttrs,
> ```

Why?


<!-- Sent from Reviewable.io -->

2023-10-12 21:21 UTC, lockshaw requested changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 5 unresolved discussions (waiting on @KateUnger and @reyna-abhyankar)

___
*[`lib/kernels/src/cuda/attention_kernels.cu` line 210 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ng_jLJuArnuoJV54az2:-Ng_jLJuArnuoJV54az3:b-rvu5kt) ([raw file](https://github.com/flexflow/FlexFlow/blob/3f6b8b093167193a5b2c091420f3b26068cf6286/lib/kernels/src/cuda/attention_kernels.cu#L210)):*
> ```Cuda
>                                         allocator};
>   allocator.deallocate(qoSeqArray);
>   allocator.deallocate(kvSeqArray);
> ```

Correct me if this is wrong



_Suggestion:_
```Cuda
  allocator.deallocate(devQoSeqArray);
  allocator.deallocate(devKvSeqArray);
```
___
*[`lib/kernels/src/cuda/attention_kernels.cu` line 212 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ng_kSLH8E0NnxIODueI:-Ng_kSLIEd37yNuamBlZ:bfb5jtc) ([raw file](https://github.com/flexflow/FlexFlow/blob/3f6b8b093167193a5b2c091420f3b26068cf6286/lib/kernels/src/cuda/attention_kernels.cu#L212)):*
> ```Cuda
>   allocator.deallocate(kvSeqArray);
> 
>   return per_device_state;
> ```

Should this return a `MHAPerDeviceState` or a `DeviceSpecific<MHAPerDeviceState>`?


<!-- Sent from Reviewable.io -->

2023-10-17 15:55 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 5 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/src/cuda/attention_kernels.cu` line 210 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ng_jLJuArnuoJV54az2:-NgyK1T9EEts7gpCDEq7:b7y4t5k) ([raw file](https://github.com/flexflow/FlexFlow/blob/3f6b8b093167193a5b2c091420f3b26068cf6286/lib/kernels/src/cuda/attention_kernels.cu#L210)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Correct me if this is wrong
</blockquote></details>

It should be `qoSeqArray` and` kvSeqArray` because the `dev___` arrays are pointers to GPU memory that we don't want to deallocate. That being said, I am unclear on the allocator interface. Is it able to (de)allocate host and device memory. If it's only supposed to be used for device memory, then these lines should just be `free(qoSeqArray); free(kvSeqArray);` 
___
*[`lib/kernels/src/cuda/attention_kernels.cu` line 212 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ng_kSLH8E0NnxIODueI:-NgyJp6c6Nbbo6kPnrCj:b-n8u0vb) ([raw file](https://github.com/flexflow/FlexFlow/blob/3f6b8b093167193a5b2c091420f3b26068cf6286/lib/kernels/src/cuda/attention_kernels.cu#L212)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this return a `MHAPerDeviceState` or a `DeviceSpecific<MHAPerDeviceState>`?
</blockquote></details>

This should be a `MHAPerDeviceState` because in `init_task_impl` we call `acc.create_device_specific<>(init_kernel(...))`


<!-- Sent from Reviewable.io -->

2023-10-19 00:58 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 4 unresolved discussions (waiting on @KateUnger and @reyna-abhyankar)

___
*[`lib/kernels/src/cuda/attention_kernels.cu` line 210 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ng_jLJuArnuoJV54az2:-Nh4QgWK4BLnfm0idsUk:b-7u3lst) ([raw file](https://github.com/flexflow/FlexFlow/blob/3f6b8b093167193a5b2c091420f3b26068cf6286/lib/kernels/src/cuda/attention_kernels.cu#L210)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

It should be `qoSeqArray` and` kvSeqArray` because the `dev___` arrays are pointers to GPU memory that we don't want to deallocate. That being said, I am unclear on the allocator interface. Is it able to (de)allocate host and device memory. If it's only supposed to be used for device memory, then these lines should just be `free(qoSeqArray); free(kvSeqArray);`
</blockquote></details>

Correct me if I'm wrong here, but `devQoSeqArray` and `devKvSeqArray` were created by `allocator.allocate`, and so should be cleaned up by `allocator.deallocate`? `qoSeqArray` was created by `malloc`, so should be cleaned up by `free` (or probably better would be to use a smart ptr/container so manual cleanup isn't necessary)


<!-- Sent from Reviewable.io -->

2023-10-19 20:31 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/src/cuda/attention_kernels.cu` line 210 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ng_jLJuArnuoJV54az2:-Nh8cJ2q5HwMiSXXz30b:bjwtb69) ([raw file](https://github.com/flexflow/FlexFlow/blob/3f6b8b093167193a5b2c091420f3b26068cf6286/lib/kernels/src/cuda/attention_kernels.cu#L210)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Correct me if I'm wrong here, but `devQoSeqArray` and `devKvSeqArray` were created by `allocator.allocate`, and so should be cleaned up by `allocator.deallocate`? `qoSeqArray` was created by `malloc`, so should be cleaned up by `free` (or probably better would be to use a smart ptr/container so manual cleanup isn't necessary)
</blockquote></details>

Ok, yes it should still be `qoSeqArray` and `kvSeqArray` that need to be deallocated, so we should change to `unique_ptr<int>` 


<!-- Sent from Reviewable.io -->

2023-11-06 20:42 UTC, lockshaw requested changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 4 unresolved discussions (waiting on @KateUnger and @reyna-abhyankar)

___
*[`lib/kernels/src/cuda/attention_kernels.cu` line 210 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ng_jLJuArnuoJV54az2:-NiaMlF03LOkSS-Nk17y:b-tmw8yq) ([raw file](https://github.com/flexflow/FlexFlow/blob/3f6b8b093167193a5b2c091420f3b26068cf6286/lib/kernels/src/cuda/attention_kernels.cu#L210)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Ok, yes it should still be `qoSeqArray` and `kvSeqArray` that need to be deallocated, so we should change to `unique_ptr<int>`
</blockquote></details>

Why does `devQoSeqArray` not get cleaned up?


<!-- Sent from Reviewable.io -->

2023-11-13 16:41 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/src/cuda/attention_kernels.cu` line 210 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1023#-Ng_jLJuArnuoJV54az2:-Nj8Ylms7vPSoJtcEzGp:b-pw29n0) ([raw file](https://github.com/flexflow/FlexFlow/blob/3f6b8b093167193a5b2c091420f3b26068cf6286/lib/kernels/src/cuda/attention_kernels.cu#L210)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does `devQoSeqArray` not get cleaned up?
</blockquote></details>

It is still needed for the device state.


<!-- Sent from Reviewable.io -->

2023-12-31 04:41 UTC, lockshaw approved these changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 3 unresolved discussions (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2023-12-31 04:42 UTC, lockshaw approved these changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1023)* status: all files reviewed, 3 unresolved discussions (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2023-12-31 04:43 UTC, merged