Implement `infer_bwd_binding`
flexflow/FlexFlow pull request #1097
Opened 2023-09-05 04:59 UTC by reyna-abhyankar

**Description of changes:**

Implement `infer_bwd_binding` 

**Related Issues:**

Issues closed by this PR:
- Closes #1043

2023-09-08 18:37 UTC, lockshaw requested changes
Test cases for `infer_bwd_binding` should be added

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-:-Ndq4QQN0AkG9GL-p5fg:b7slhm7)* status: all files reviewed, 3 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/runtime/src/task_spec/op_task_invocation.h` line 87 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ndq4DwlEe-mgrV3Hocz:-Ndq4DwlEe-mgrV3Hod-:bm6cqob) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/op_task_invocation.h#L87)):*
> ```objc
> 
>   void bind_args_from_fwd(OpTaskBinding const &fwd) {
>     this->arg_bindings = fwd.get_arg_bindings();
> ```

Can you make sure these are either implemented or marked as `NOT_IMPLEMENTED`?
___
*[`lib/runtime/src/task_spec/op_task_invocation.cc` line 51 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ndq3fgC1WB44NsaL1E3:-Ndq3fgC1WB44NsaL1E4:b-2sm66k) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/op_task_invocation.cc#L51)):*
> ```cpp
>   bwd.bind_args_from_fwd(fwd);
>   bwd.bind_tensors_from_fwd(fwd);
>   for (auto const &[key, spec] : fwd.get_tensor_bindings()) {
> ```

We probably need to handle untrainable parameters here. 
___
*[`lib/runtime/src/task_spec/task_signature.h` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ndq3wAE8qYIgXA9B6Cq:-Ndq3wAE8qYIgXA9B6Cr:b-mnxay6) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/task_signature.h#L45)):*
> ```objc
>   void add_variadic_arg_slot(slot_id name);
> 
>   static std::unordered_map<task_id_t, TaskSignature> task_sig_map;
> ```

Do you think it's better having these maps per type or would it be better to have a `SignatureStore` class (or something like it) that stores them--I'd lean toward the second just so that all of the signature storing and retrieval behavior is closeby


<!-- Sent from Reviewable.io -->

2023-09-09 01:15 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1097)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw)

___
*[`lib/runtime/src/task_spec/op_task_invocation.h` line 87 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ndq4DwlEe-mgrV3Hocz:-NdrTDEpBY--nPEUoiyv:b-9o60fb) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/op_task_invocation.h#L87)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you make sure these are either implemented or marked as `NOT_IMPLEMENTED`?
</blockquote></details>

Yes, `get_arg_bindings()` and `get_tensor_bindings()` are already implemented. See `op_task_invocation.cc`
___
*[`lib/runtime/src/task_spec/op_task_invocation.cc` line 51 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ndq3fgC1WB44NsaL1E3:-NdrTWa9D0ekJblbUMkL:bcyy5tq) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/op_task_invocation.cc#L51)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

We probably need to handle untrainable parameters here.
</blockquote></details>

The signature has `OpTensorSlotSpec` and the binding uses `OpTensorSpec`. The slot spec is more descriptive and has `OpSlotOptions`, which is where untrainable is handled. The binding is only aware of the `TensorRole` (input, weight, or output). Is there a reason that untrainable also needs to be specified in the binding? I think the signature should suffice.
___
*[`lib/runtime/src/task_spec/task_signature.h` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ndq3wAE8qYIgXA9B6Cq:-NdrUCZTE_e9Q0gXQYhm:b-lz3yla) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/task_signature.h#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Do you think it's better having these maps per type or would it be better to have a `SignatureStore` class (or something like it) that stores them--I'd lean toward the second just so that all of the signature storing and retrieval behavior is closeby
</blockquote></details>

At the moment, we only have two: one for task and one for operator task. If `SignatureStore` is just going to be a wrapper then I don't think it would be more useful. 


<!-- Sent from Reviewable.io -->

2023-09-11 09:44 UTC, lockshaw requested changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/runtime/src/task_spec/op_task_invocation.h` line 136 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2cDPZ5T7N5OWbXZ-v:-Ne2cDPZ5T7N5OWbXZ-w:b-kxtsxq) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/op_task_invocation.h#L136)):*
> ```objc
> OpTaskSignature infer_bwd_signature(OpTaskSignature const &fwd);
> OpTaskBinding infer_bwd_binding(OpTaskBinding const &fwd);
> OpTaskSignature get_op_signature(task_id_t const &);
> ```

Why remove this?
___
*[`lib/runtime/src/task_spec/op_task_invocation.h` line 43 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2c-ODDRIwIRJx8LXu:-Ne2c-ODDRIwIRJx8LXv:b-z16yh3) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_invocation.h#L43)):*
> ```objc
>                           TaskInvocationSpec>;
> 
> struct OpArgSpecTypeAccessor {
> ```

Can we just move all of these over to having a type tag?
___
*[`lib/runtime/src/task_spec/op_task_invocation.h` line 118 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2bS2Z3NkhPuq7OlpS:-Ne2bS2Z3NkhPuq7OlpT:b-kugefb) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_invocation.h#L118)):*
> ```objc
>   }
> 
>   bool operator==(const OpTaskBinding& rhs) {
> ```

Probably should use visitable instead
___
*[`lib/runtime/src/task_spec/op_task_invocation.cc` line 51 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ndq3fgC1WB44NsaL1E3:-Ne2_QOGDMpHNPolmQD1:bkxkm2k) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/op_task_invocation.cc#L51)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

The signature has `OpTensorSlotSpec` and the binding uses `OpTensorSpec`. The slot spec is more descriptive and has `OpSlotOptions`, which is where untrainable is handled. The binding is only aware of the `TensorRole` (input, weight, or output). Is there a reason that untrainable also needs to be specified in the binding? I think the signature should suffice.
</blockquote></details>

My point is that if a tensor if marked untrainable in the signature, it probably shouldn't have its gradient bound (as it has no gradient)
___
*[`lib/runtime/src/task_spec/op_task_signature.h` line 74 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2b10k8xSshpMO3tku:-Ne2b10lCbcy_B6t2k46:b-bop4eu) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_signature.h#L74)):*
> ```objc
>   }
> 
>   // TODO: what is this function's purpose? OpTaskSignature doesn't need a return value
> ```

Why does it not need a return value? For example, `init_task` for some operators returns a `DeviceSpecific<xxxxxPerDeviceState>`
___
*[`lib/runtime/src/task_spec/op_task_signature.h` line 92 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2aynG0qU9WdKG8G0R:-Ne2aynG0qU9WdKG8G0S:bgo5tou) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_signature.h#L92)):*
> ```objc
> 
> private:
>   OpTaskType type;
> ```

What is the purpose of this field?
___
*[`lib/runtime/src/task_spec/op_task_signature.cc` line 77 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2_pjlD6FYGwehLCJD:-Ne2_pjlD6FYGwehLCJE:b-zfo2s0) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_signature.cc#L77)):*
> ```cpp
> }
> 
> bool OpTaskSignature::operator==(OpTaskSignature const & rhs) const {
> ```

Make `OpTaskSignature` a `FF_VISITABLE_STRUCT_NONSTANDARD_CONSTRUCTION` so you get these automatically
___
*[`lib/runtime/src/task_spec/task_signature.h` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ndq3wAE8qYIgXA9B6Cq:-Ne2_5hlBBqV95pRIrtR:bvmtucm) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/task_signature.h#L45)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

At the moment, we only have two: one for task and one for operator task. If `SignatureStore` is just going to be a wrapper then I don't think it would be more useful.
</blockquote></details>

It would just be nice to have all of the signature storage in one place in the code rather than in two, but I'll go with your preference 
___
*[`lib/runtime/test/src/test_op_task_invocation.cc` line 13 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2aFnp2cSxlDGKZJv3:-Ne2aFnp2cSxlDGKZJv4:b8hzpal) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/test/src/test_op_task_invocation.cc#L13)):*
> ```cpp
>   // get binding from operator forward
>   OpTaskSignature signature = fwd_signature<AGGREGATE_FWD_TASK_ID>();
>   AggregateAttrs attrs {n: 12, lambda_bal: 1.0};
> ```

I don't think this is valid C++ syntax?
___
*[`lib/runtime/test/src/test_op_task_invocation.cc` line 37 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2aVhY6zMhyEYNlJ2b:-Ne2aVhY6zMhyEYNlJ2c:btjtcei) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/test/src/test_op_task_invocation.cc#L37)):*
> ```cpp
>     assert (arg_types.count(slot_id));
>     assert (arg_types.at(slot_id) == op_arg_spec_type);
>   }
> ```

This should probably be pulled out into a separate function as every function's operator tests will be using it?

Also, tests should use `CHECK`, not `assert`



_Code quote:_
```cpp
  // check tensors
  auto const& tensor_slots = signature.get_tensor_slots();
  auto const& tensor_bindings = binding.get_tensor_bindings();
  assert (tensor_slots.size() == tensor_bindings.size());
  for (OpTensorSlotSpec const& tensor_slot_spec: tensor_slots) {
    slot_id name = tensor_slot_spec.name;
    assert (tensor_bindings.count({name, IsGrad::NO}));
    assert (!tensor_bindings.count({name, IsGrad::YES}));
    OpTensorSpec const tensor_spec = tensor_bindings.at({name, IsGrad::NO});
    assert (tensor_spec.role == tensor_slot_spec.tensor_role);
  }

  // check arg types
  auto const& arg_types = signature.get_arg_types();
  auto const& arg_bindings = binding.get_arg_bindings();
  assert (arg_types.size() == arg_bindings.size());
  for (auto const &[slot_id, op_arg_spec] : arg_bindings) {
    std::type_index op_arg_spec_type = std::visit(OpArgSpecTypeAccessor(), op_arg_spec);
    assert (arg_types.count(slot_id));
    assert (arg_types.at(slot_id) == op_arg_spec_type);
  }
```


<!-- Sent from Reviewable.io -->

2023-09-28 00:50 UTC, wmdi requested changes
> Reviewed 16 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1097)* status: 19 of 27 files reviewed, 11 unresolved discussions (waiting on @lambda7xx, @lockshaw, and @reyna-abhyankar)

___
*[`lib/op-attrs/include/op-attrs/tensor_shape.h` line 19 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfOCIxl91XI-EbcKCr0:-NfOCIxl91XI-EbcKCr1:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/op-attrs/include/op-attrs/tensor_shape.h#L19)):*
> ```objc
>   template <typename Dims>
>   TensorShape(Dims const &dims, DataType data_type)
>       : dims(this->dims), data_type(this->data_type) {}
> ```

Why?


<!-- Sent from Reviewable.io -->

2023-09-28 06:50 UTC, lockshaw requested changes
> Reviewed 8 of 24 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1097)* status: all files reviewed, 28 unresolved discussions (waiting on @lambda7xx, @reyna-abhyankar, and @wmdi)

___
*[`lib/op-attrs/include/op-attrs/tensor_shape.h` line 19 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfOCIxl91XI-EbcKCr0:-NfPSZJN41uhPEgkkbez:b5anvjv) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/op-attrs/include/op-attrs/tensor_shape.h#L19)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

I think this is a bug and should be reverted: `this->dims` and `this->data_type` aren't initialized yet
___
*[`lib/runtime/src/task_spec/op_task_invocation.cc` line 6 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPTAwM5vSNl9J27Szc:-NfPTAwM5vSNl9J27Szd:b-i9cfx8) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/op_task_invocation.cc#L6)):*
> ```cpp
> namespace FlexFlow {
> 
> OpTensorSpec input_tensor(int idx, OpSlotOptions option = OpSlotOptions::NECESSARY) {
> ```

Shouldn't the slot options be on the slot (i.e., as part of the signature) and not part of the binding?
___
*[`lib/runtime/src/task_spec/op_task_signature.h` line 66 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPTiXY0kFWArKkvaxA:-NfPTiXZCGrLcnjCOaZV:bw1jcms) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/op_task_signature.h#L66)):*
> ```objc
> 
>   bool operator==(OpTaskSignature const &) const;
>   bool operator!=(OpTaskSignature const &) const;
> ```

Provided by visitable
___
*[`lib/runtime/src/task_spec/op_task_signature.h` line 98 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPTq9j8xCLj_Ux4aTX:-NfPTq9j8xCLj_Ux4aTY:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/op_task_signature.h#L98)):*
> ```objc
> 
> OpTaskSignature get_op_signature(task_id_t const &);
> FF_VISITABLE_STRUCT_NONSTANDARD_CONSTRUCTION(OpTaskSignature, get_tensor_slots, set_arg_types, get_arg_types);
> ```





_Suggestion:_
```objc
FF_VISITABLE_STRUCT_NONSTANDARD_CONSTRUCTION(OpTaskSignature, op_tensor_slots, set_arg_types, task_arg_types);
```
___
*[`lib/runtime/src/task_spec/op_task_signature.cc` line 5 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPU00x3sRMiulYA_kh:-NfPU00x3sRMiulYA_ki:b-jnvliw) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_signature.cc#L5)):*
> ```cpp
> namespace FlexFlow {
> 
> OpTaskSignature::OpTaskSignature(OpTaskType t) {
> ```

Why was this deleted? I think it's necessary?
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 86 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPVdGQ7HArozfo-JNO:-NfPVdGQ7HArozfo-JNP:bjlrj0s) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L86)):*
> ```objc
>                                     std::vector<privilege_mode_to_accessor<Permissions::WO>>>;
> 
> struct ITaskArgumentAccessor {
> ```

Move into its own header/source files
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 89 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPUsXQ4N3YD74SxH0c:-NfPUsXQ4N3YD74SxH0d:buqqktz) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L89)):*
> ```objc
>   virtual PrivilegeType get_tensor(slot_id slot, Permissions priv) const = 0;
> 
>   virtual PrivilegeVariadicType get_variadic_tensor(slot_id slot, Permissions priv) const = 0;
> ```

Why was the template parameter removed from these? By requiring it to be static we were able to infer the return type and didn't have to return a variant
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 98 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPV1Dg6zDAmjNeDdbV:-NfPV1Dg6zDAmjNeDdbW:brojeiy) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L98)):*
> ```objc
> 
>   virtual size_t get_device_idx() const = 0;
> };
> ```

Should be used on anything that declares a virtual method (checks https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c67-a-polymorphic-class-should-suppress-public-copymove) 



_Suggestion:_
```objc
  virtual size_t get_device_idx() const = 0;
};
CHECK_RC_COPY_VIRTUAL_COMPLIANT(ITaskArgumentAccessor);
```
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 132 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPX6am4zqPO-ZFMicU:-NfPX6am4zqPO-ZFMicV:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L132)):*
> ```objc
>     return acc.get_variadic_argument<T>(slot);
>   }
> };
> ```


___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 134 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPVfB51dmfxTl3fuwV:-NfPVfB51dmfxTl3fuwW:bjlrj0s) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L134)):*
> ```objc
> };
> 
> struct LegionTaskArgumentAccessor : public ITaskArgumentAccessor {
> ```

Move into its own header/source files
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 169 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPVj4g7C9wio3zrBio:-NfPVj4g7C9wio3zrBip:bjlrj0s) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L169)):*
> ```objc
> };
> 
> struct LocalTaskArgumentAccessor : public ITaskArgumentAccessor {
> ```

Move into its own header/source files
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 201 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPVzMt-KK9V6tdxhNU:-NfPVzMt-KK9V6tdxhNV:b1g0byq) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L201)):*
> ```objc
> 
>   void *allocate(size_t size);
>   void deallocate(void *ptr);
> ```

The operators expect to be able to get an `Allocator`. Memory usage tracking should instead be moved to a wrapper around `Allocator` (e.g., `TrackedAllocator(Allocator const &)`) (which is also an `Allocator` of course)



_Suggestion:_
```objc
  Allocator get_allocator() const;
```
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 204 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPWZEe3YP9NbmRad6-:-NfPWZEe3YP9NbmRad60:bmm8z7s) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L204)):*
> ```objc
> 
> private:
>   std::shared_ptr<SimTaskBinding const> sim_task_binding;
> ```

Is there a reason we have this as a shared ptr rather than a value?
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 210 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPWfiF5oQ7ylQ1hcTj:-NfPWfiF5oQ7ylQ1hcTk:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L210)):*
> ```objc
> 
> using TaskArgumentAccessorBackend = variant<LegionTaskArgumentAccessor,
>                                         LocalTaskArgumentAccessor>;
> ```


___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 221 at r4](https://reviewable.io/revi [...]

2023-10-04 17:33 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1097)* status: all files reviewed, 27 unresolved discussions (waiting on @lambda7xx, @lockshaw, and @wmdi)

___
*[`lib/op-attrs/include/op-attrs/tensor_shape.h` line 19 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfOCIxl91XI-EbcKCr0:-NfvXq806PtdIrBajunW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/op-attrs/include/op-attrs/tensor_shape.h#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think this is a bug and should be reverted: `this->dims` and `this->data_type` aren't initialized yet
</blockquote></details>

Done.
___
*[`lib/runtime/src/task_spec/op_task_invocation.h` line 136 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2cDPZ5T7N5OWbXZ-v:-NfvYtJ_-MrWXLlHUqY_:b96rwff) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/op_task_invocation.h#L136)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why remove this?
</blockquote></details>

This is moved to `op_task_signature.h`
___
*[`lib/runtime/src/task_spec/op_task_invocation.h` line 118 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2bS2Z3NkhPuq7OlpS:-NfvYZkPAPky9SISRDLG:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_invocation.h#L118)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably should use visitable instead
</blockquote></details>

Done.
___
*[`lib/runtime/src/task_spec/op_task_invocation.cc` line 51 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ndq3fgC1WB44NsaL1E3:-NfvZVzG-F2Ig33ZLJLL:b-4tx8ka) ([raw file](https://github.com/flexflow/FlexFlow/blob/373b3144ccb6c5aa1ff24b03f26f710452e98365/lib/runtime/src/task_spec/op_task_invocation.cc#L51)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

My point is that if a tensor if marked untrainable in the signature, it probably shouldn't have its gradient bound (as it has no gradient)
</blockquote></details>

See response to your other comment on `OpSlotOptions` for binding. 
___
*[`lib/runtime/src/task_spec/op_task_invocation.cc` line 6 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPTAwM5vSNl9J27Szc:-NfvZ67D3Rt5uOcXvqx4:b8eve8u) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/op_task_invocation.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Shouldn't the slot options be on the slot (i.e., as part of the signature) and not part of the binding?
</blockquote></details>

I added it to the binding so we can check untrainable in `infer_bwd_binding()` but the other option is have `infer_bwd_binding()` also take the signature as an argument.
___
*[`lib/runtime/src/task_spec/op_task_signature.h` line 74 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2b10k8xSshpMO3tku:-NfvaORv3UG0NvV57q8y:bpgh3kq) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_signature.h#L74)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does it not need a return value? For example, `init_task` for some operators returns a `DeviceSpecific<xxxxxPerDeviceState>`
</blockquote></details>

Done. Should it be a vector of return values or is there only one return value?
___
*[`lib/runtime/src/task_spec/op_task_signature.h` line 92 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2aynG0qU9WdKG8G0R:-Nfvaf7a0yzT7nigB1Rq:bujp82m) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_signature.h#L92)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is the purpose of this field?
</blockquote></details>

There is a `get_task_type()` function that is called in `task_spec.cc`. I've implemented it as follows:



_Code snippet:_
```objc
OpTaskType get_task_type() const {
  return this->type;
}
```
___
*[`lib/runtime/src/task_spec/op_task_signature.h` line 66 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPTiXY0kFWArKkvaxA:-NfvZfpu-skZNsndOsFX:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/op_task_signature.h#L66)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Provided by visitable
</blockquote></details>

Done.
___
*[`lib/runtime/src/task_spec/op_task_signature.h` line 98 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPTq9j8xCLj_Ux4aTX:-NfvcDNl6ZiREcsmCigH:bos2ohs) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/op_task_signature.h#L98)):*
> ```objc
> 
> OpTaskSignature get_op_signature(task_id_t const &);
> FF_VISITABLE_STRUCT_NONSTANDARD_CONSTRUCTION(OpTaskSignature, get_tensor_slots, set_arg_types, get_arg_types);
> ```

Done. But also getting `member is inaccessible` because they're private. Should we make them public? 
___
*[`lib/runtime/src/task_spec/op_task_signature.cc` line 5 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPU00x3sRMiulYA_kh:-NfvdIM89RwAbxvRXQ_A:biq60bf) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_signature.cc#L5)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was this deleted? I think it's necessary?
</blockquote></details>

Added this as



_Code snippet:_
```cpp
OpTaskSignature::OpTaskSignature(OpTaskType t) {
  this->type = t;
}
```
___
*[`lib/runtime/src/task_spec/op_task_signature.cc` line 77 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-Ne2_pjlD6FYGwehLCJD:-NfvdWJF6xk5hxJyof4z:b-sbr9kx) ([raw file](https://github.com/flexflow/FlexFlow/blob/766e980253f15bbd252095c7c6802fd40c0ea67c/lib/runtime/src/task_spec/op_task_signature.cc#L77)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Make `OpTaskSignature` a `FF_VISITABLE_STRUCT_NONSTANDARD_CONSTRUCTION` so you get these automatically
</blockquote></details>

Done. See above comment about member accessible
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 86 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPVdGQ7HArozfo-JNO:-NfvfpJW8DhMC09te-fT:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L86)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move into its own header/source files
</blockquote></details>

Done.
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 89 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPUsXQ4N3YD74SxH0c:-Nfvg-3X1j8Fiycdskj2:b-ot793s) ([raw file](https://github.com/flexflow/FlexFlow/blob/6f2b51b83ed57ee00046cac6b0e57d593b7677e3/lib/runtime/src/task_spec/task_argument_accessor.h#L89)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was the template parameter removed from these? By requiring it to be static we were able to infer the return type and didn't have to return a variant
</blockquote></details>

AFAIK C++ does not allow virtual template functions. I was getting errors 
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 98 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NfPV1Dg6zDAmjNeDdbV:-NfvgHIHDUwAwja4LIAt:b-d4lcd1) ([raw file](h [...]

2023-10-13 00:26 UTC, lockshaw requested changes
> Reviewed 7 of 9 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1097)* status: all files reviewed, 33 unresolved discussions (waiting on @lambda7xx, @reyna-abhyankar, and @wmdi)

___
*[`lib/kernels/include/kernels/allocation.h` line 34 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaIhF5B2fH2mhiZI9W:-NgaIhF5B2fH2mhiZI9X:b-oc2eh1) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/kernels/include/kernels/allocation.h#L34)):*
> ```objc
> };
> 
> struct TrackedAllocator: public Allocator {
> ```

Is this better as a subclass of `Allocator` or of `IAllocator`?
___
*[`lib/runtime/src/task_spec/itask_argument_accessor.h` line 52 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaKjjd0bxaJy8oZrmZ:-NgaKjjd0bxaJy8oZrm_:b2wkyog) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/itask_argument_accessor.h#L52)):*
> ```objc
> FF_VISITABLE_STRUCT(FutureArgumentFormat, type, future_idx);
> 
> struct TaskArgumentsFormat {
> ```

`TaskArgumentsFormat` should be in a different file than `ITaskArgumentAccessor`, as `TaskArgumentsFormat` is part of compilation to legion tasks and `ITaskArgumentAccessor` is shared across all backends
___
*[`lib/runtime/src/task_spec/itask_argument_accessor.h` line 92 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaLE8qEw6HEtpNUNW2:-NgaLE8qEw6HEtpNUNW3:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/itask_argument_accessor.h#L92)):*
> ```objc
> struct ITaskArgumentAccessor {
>   ITaskArgumentAccessor& operator=(const ITaskArgumentAccessor&) = delete;
>   virtual ~ITaskArgumentAccessor() {};
> ```





_Suggestion:_
```objc
  virtual ~ITaskArgumentAccessor() = default;
```
___
*[`lib/runtime/src/task_spec/legion_task_argument_accessor.h` line 20 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaMHYi4FCZADQ-rEiy:-NgaMHYi4FCZADQ-rEiz:b-bi8amr) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/legion_task_argument_accessor.h#L20)):*
> ```objc
> namespace FlexFlow {
> 
> struct LegionTaskArgumentAccessor : public ITaskArgumentAccessor {
> ```

You're missing some `override`s
___
*[`lib/runtime/src/task_spec/legion_task_argument_accessor.cc` line 0 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaMO-S4Ku55pAHvTq8:-NgaMO-S4Ku55pAHvTq9:b3a692x) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/legion_task_argument_accessor.cc#L0)):*
`#include "runtime/task_spec/legion_task_argument_accessor.h"`
___
*[`lib/runtime/src/task_spec/local_task_argument_accessor.h` line 29 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaMc7J6h3TkRwUGTpX:-NgaMc7J6h3TkRwUGTpY:b-bi8amr) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/local_task_argument_accessor.h#L29)):*
> ```objc
>   PrivilegeType get_tensor(slot_id slot, Permissions priv) const override;
> 
>   PrivilegeVariadicType get_variadic_tensor(slot_id slot, Permissions priv) const override;
> ```

You're missing some `override`s
___
*[`lib/runtime/src/task_spec/local_task_argument_accessor.h` line 53 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaMgeV-2KeyaAT6Ui6:-NgaMgeV-2KeyaAT6Ui7:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/local_task_argument_accessor.h#L53)):*
> ```objc
> 
>   void *allocate(size_t size);
>   void deallocate(void *ptr);
> ```

Delete



_Code quote:_
```objc
  size_t get_memory_usage() const {
    return memory_usage;
  }

  void *allocate(size_t size);
  void deallocate(void *ptr);
```
___
*[`lib/runtime/src/task_spec/local_task_argument_accessor.h` line 59 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaMipaCsMs9gyO0orh:-NgaMipaCsMs9gyO0ori:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/local_task_argument_accessor.h#L59)):*
> ```objc
>   SimTaskBinding sim_task_binding;
>   Allocator local_allocator;
>   size_t memory_usage;
> ```

Delete
___
*[`lib/runtime/src/task_spec/local_task_argument_accessor.cc` line 7 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaMt3c7ynjsVkxEhPZ:-NgaMt3c7ynjsVkxEhP_:b-5bedpa) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/local_task_argument_accessor.cc#L7)):*
> ```cpp
> template <typename T>
> T const &LocalTaskArgumentAccessor::get_argument(slot_id slot) const {
>   assert(contains_key(this->sim_task_binding.arg_bindings.at(slot)));
> ```

`contains_key` takes multiple arguments. You should be able to compile these files to catch errors like this, even if you're not able to build+link the full `runtime`
___
*[`lib/runtime/src/task_spec/local_task_argument_accessor.cc` line 12 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaN32789KH_o66i_nx:-NgaN32789KH_o66i_ny:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/local_task_argument_accessor.cc#L12)):*
> ```cpp
> 
> template <typename T>
> optional<T> LocalTaskArgumentAccessor::get_optional_argument(slot_id slot) const {
> ```





_Suggestion:_
```cpp
std::optional<T>
```
___
*[`lib/runtime/src/task_spec/local_task_argument_accessor.cc` line 24 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaN51Q2ErK-WLLtWXJ:-NgaN51Q2ErK-WLLtWXK:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/local_task_argument_accessor.cc#L24)):*
> ```cpp
> }
> 
> void *LocalTaskArgumentAccessor::allocate(size_t size) {
> ```

Delete
___
*[`lib/runtime/src/task_spec/local_task_argument_accessor.cc` line 42 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaNJSy40JZ4AwZ4Gp0:-NgaNJSy40JZ4AwZ4Gp1:b-exjhf1) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/local_task_argument_accessor.cc#L42)):*
> ```cpp
> 
> 
>   if (slot == GATE_PREDS || slot == GATE_ASSIGN) {
> ```

Why is there special handling needed for some slots?
___
*[`lib/runtime/src/task_spec/local_task_argument_accessor.cc` line 47 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaNMXU0sAAzLwvi1kP:-NgaNMXU0sAAzLwvi1kQ:b-ey9pxx) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/local_task_argument_accessor.cc#L47)):*
> ```cpp
>     DataType data_type = gate_preds.shape.data_type;
>     ArrayShape array_shape = {
>         gate_preds.shape.dims.get_dims()}; // gate_preds.shape.dims.get_dims()
> ```

remove comments
___
*[`lib/runtime/src/task_spec/local_task_argument_accessor.cc` line 57 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaNNLd2XQv0PCoEeIH:-NgaNNLd2XQv0PCoEeII:b-ey9pxx) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/local_task_argument_accessor.cc#L57)):*
> ```cpp
>     Datatype data_type = output_shape.data_type;
>     ArrayShape array_shape = {
>         output_shape.dims.get_dims()}; // output_shape.dims.get_dims() return
> ```

remove comments
___
*[`lib/runtime/src/task_spec/local_task_argument_accessor.cc` line 64 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1097#-NgaNBupCNaE5q7fxe1I:-NgaNBupCNaE5q7fxe1J:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/25364c5a37fdeccee1579402a230cad4d3034f2f/lib/runtime/src/task_spec/local_task_argument_ [...]

2024-03-28 07:31 UTC, closed without merging