Reshape OP
flexflow/FlexFlow pull request #1100
Opened 2023-09-06 08:08 UTC by lambda7xx

**Description of changes:**
- update the `Reshape Operator`

**Related Issues:**

Linked Issues:
- Issue #1077 

Issues closed by this PR:
- Closes #

2023-09-08 17:49 UTC, lockshaw submitted a review, later dismissed
Move 1077 to the closed session, not the linked section (you can just delete the linked section if it doesn't have anything in it)

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-:-NdpuBqi2QmxayS8wWxJ:by0aa85)* status: all files reviewed, 19 unresolved discussions (waiting on @KateUnger and @lambda7xx)

___
*[`deps/fmt` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpu-TDBJF-EVud5MX5:-Ndpu-TDBJF-EVud5MX6:b-dkp59x) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/deps/fmt#L0)):*
Why was this change made as part of this PR? (and at all?)
___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 7 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdprQrWDMQD8BChVmtw:-NdprQrWDMQD8BChVmtx:b447crj) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/kernels/include/kernels/reshape_kernels.h#L7)):*
> ```objc
> #include "datatype_dispatch.h"
> #include "kernels/accessor.h"
> #include "kernels/device.h"
> ```

Neither of the added includes here should be needed in the header file



_Suggestion:_
```objc
#include "kernels/accessor.h"
#include "kernels/device.h"
```
___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpr0_i1Su7wCSvVvqO:-Ndpr0_i1Su7wCSvVvqP:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/kernels/include/kernels/reshape_kernels.h#L16)):*
> ```objc
> };
> 
> FF_VISITABLE_STRUCT_NO_EQ(ReshapePerDeviceState, data_type);
> ```





_Suggestion:_
```objc
FF_VISITABLE_STRUCT(ReshapePerDeviceState, data_type);
```
___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpr68X0heSZJ0on7pB:-Ndpr68X0heSZJ0on7pC:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/kernels/include/kernels/reshape_kernels.h#L21)):*
> ```objc
> 
> namespace Kernels {
> namespace Reshape {
> ```





_Suggestion:_
```objc
namespace Kernels {
namespace Reshape {
  
ReshapePerDeviceState init_kernel(DataType data_type);
```
___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdpragEBGJJhk56NVCo:-NdpragEBGJJhk56NVCp:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/kernels/include/kernels/reshape_kernels.h#L24)):*
> ```objc
> 
> void forward_kernel(ffStream_t stream,
>                     ReshapePerDeviceState const &meta,
> ```





_Suggestion:_
```objc
                    ReshapePerDeviceState const &per_device_state,
```
___
*[`lib/runtime/src/tasks.h` line 76 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdprBagBe-BYMm-ayOZ:-NdprBagBe-BYMm-ayO_:b-idy2ti) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/tasks.h#L76)):*
> ```objc
>   REDUCE_FWD_TASK_ID,
>   REDUCE_BWD_TASK_ID,
>   _INIT_TASK_IDRESHAPE,
> ```

Something looks wrong here
___
*[`lib/runtime/src/ops/replicate.h` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndps-9_62A10ydKo6ta:-Ndps-9_62A10ydKo6tb:bnvzizj) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/replicate.h#L0)):*
Should not be part of this PR?
___
*[`lib/runtime/src/ops/reshape.cc` line 20 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndps6wn1z4Si2vAp4m1:-Ndps6wn1z4Si2vAp4m2:bb6qxws) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L20)):*
> ```cpp
> #include "legion/legion_utilities.h"
> #include "utils/exception.decl.h"
> #include "utils/hash-utils.h"
> ```

Things outside of `utils` should not access `.decl.h` files (also FYI they'll be going away soon with the `req-fix` PR)



_Suggestion:_
```cpp
#include "kernels/reshape_kernels.h"
#include "legion/legion_utilities.h"
#include "utils/exception.h"
#include "utils/hash-utils.h"
```
___
*[`lib/runtime/src/ops/reshape.cc` line 56 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdpsgFw0vi7_eIH5rNn:-NdpsgFx3TMmJF9R7998:b8ex7uo) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L56)):*
> ```cpp
> 
>   binding.bind(INPUT, input_tensor(0));
>   binding.bind(OUTPUT, output_tensor(0));
> ```

Just a guess as `init_task_impl` is currently not defined



_Suggestion:_
```cpp
  binding.bind(INPUT, input_parallel_tensor_shape(0));
```
___
*[`lib/runtime/src/ops/reshape.cc` line 64 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdpsNtXDijoqNJNPK4_:-NdpsNtXDijoqNJNPK4a:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L64)):*
> ```cpp
>   OpTaskBinding binding;
> 
>   binding.bind(PER_DEVICE_STATE, per_device_op_state<ReshapeMeta>());
> ```





_Suggestion:_
```cpp
  binding.bind_arg(PER_DEVICE_STATE, per_device_op_state<ReshapePerDeviceState>());
```
___
*[`lib/runtime/src/ops/reshape.cc` line 65 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdpsTRv-FqJEdgEtOej:-NdpsTRv-FqJEdgEtOek:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L65)):*
> ```cpp
> 
>   binding.bind(PER_DEVICE_STATE, per_device_op_state<ReshapeMeta>());
>   binding.bind(PROFILING, profiling_settings());
> ```





_Suggestion:_
```cpp
  binding.bind_arg(PROFILING, profiling_settings());
```
___
*[`lib/runtime/src/ops/reshape.cc` line 80 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpsady9Bi5HxI65KnS:-Ndpsady9Bi5HxI65KnT:biasoqt) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L80)):*
> ```cpp
> static DeviceSpecific<ReshapePerDeviceState>
>     init_task_impl(TaskArgumentAccessor const &acc) {
>   NOT_IMPLEMENTED();
> ```

This should be implemented as part of this PR



_Code quote:_
```cpp
  NOT_IMPLEMENTED();
```
___
*[`lib/runtime/src/ops/reshape.cc` line 94 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpstk_2QeOs-ZoYLbp:-Ndpstka4h2Du0pmaPSi:b-7ohf31) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L94)):*
> ```cpp
> static optional<float> forward_task_impl(TaskArgumentAccessor const &acc) {
>   auto per_device_state =
>       acc.get_argument<DeviceSpecific<ReshapePerDeviceState>>(PER_DEVICE_STATE);
> ```

tasks should not care whether their arguments were passed device-specific or not--this is handled by `TaskArgumentAccessor`



_Suggestion:_
```cpp
  auto per_device_state =
      acc.get_argument<ReshapePerDeviceState>(PER_DEVICE_STATE);
```
___
*[`lib/runtime/src/ops/reshape.cc` line 105 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpt5ZPBWVs59UzVY-9:-Ndpt5ZPBWVs59UzVY-A:bdo2ul) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L105)):*
> ```cpp
>                  &per_device_state,
>                  input,
>                  output);
> ```

Change to take by `const &`



_Suggestion:_
```cpp
  return profile(forward_kernel,
                 profiling,
                 "[Reshape] forward time = %.2lfms\n",
                 per_device_state,
                 input,
                 output);
```
___
*[`lib/runtime/src/ops/reshape.cc` line 127 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdptCSN6nBnstQqJxsc:-NdptCSN6nBnstQqJxsd:bdo2ul) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1 [...]

2023-09-24 14:58 UTC, lambda7xx commented
*[`deps/fmt` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpu-TDBJF-EVud5MX5:-Nf6glpCEH5GuvSxe41m:b-zfxkyw) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/deps/fmt#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was this change made as part of this PR? (and at all?)
</blockquote></details>

which change


<!-- Sent from Reviewable.io -->

2023-09-24 15:03 UTC, lambda7xx commented
*[`lib/runtime/src/ops/reshape.cc` line 56 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdpsgFw0vi7_eIH5rNn:-Nf6hdn95-lkSl2pP2sI:b-j5qlp9) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L56)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just a guess as `init_task_impl` is currently not defined
</blockquote></details>

Done. how to bind output? output_tensor(0) or  output_parallel_tensor_shape(0)?


<!-- Sent from Reviewable.io -->

2023-09-24 15:06 UTC, lambda7xx commented
*[`lib/runtime/src/ops/reshape.cc` line 146 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdptK9f4DHQxRL1NX-6:-Nf6idXP-FzP6-07PgcQ:b-svvf45) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L146)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does `reshape` have no cost? It does a data copy in the forward pass and tensor addition in the backward pass
</blockquote></details>

i will update


<!-- Sent from Reviewable.io -->

2023-09-24 15:09 UTC, lambda7xx commented
*[`lib/runtime/src/ops/reshape.cc` line 80 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpsady9Bi5HxI65KnS:-Nf6jKZR9Z2VFESInudS:b32wtd) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L80)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This should be implemented as part of this PR
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2023-09-24 19:21 UTC, lambda7xx commented
*[`lib/kernels/include/kernels/reshape_kernels.h` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpr68X0heSZJ0on7pB:-Nf6gpHyEtyvwwb7q2jS:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/kernels/include/kernels/reshape_kernels.h#L21)):*
> ```objc
> 
> namespace Kernels {
> namespace Reshape {
> ```

Done.



_Code snippet (i):_
```objc
it seems the  shoud just be in namespace flexflow
```



_Code snippet (ii):_
```objc
ReshapePerDeviceState init_kernel(DataType data_type);
```


<!-- Sent from Reviewable.io -->

2023-09-24 19:57 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: 2 of 6 files reviewed, 19 unresolved discussions (waiting on @KateUnger and @lockshaw)

___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 7 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdprQrWDMQD8BChVmtw:-Nf6gnrmBwExfUkKGjl6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/kernels/include/kernels/reshape_kernels.h#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Neither of the added includes here should be needed in the header file
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpr0_i1Su7wCSvVvqO:-Nf6gobR3O83bQqgmQEW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/kernels/include/kernels/reshape_kernels.h#L16)):*
> ```objc
> };
> 
> FF_VISITABLE_STRUCT_NO_EQ(ReshapePerDeviceState, data_type);
> ```

Done.
___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdpragEBGJJhk56NVCo:-Nf6guD35cbB4NxdfQQm:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/kernels/include/kernels/reshape_kernels.h#L24)):*
> ```objc
> 
> void forward_kernel(ffStream_t stream,
>                     ReshapePerDeviceState const &meta,
> ```

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 20 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndps6wn1z4Si2vAp4m1:-Nf6hU_o9lwkLMs0uItV:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Things outside of `utils` should not access `.decl.h` files (also FYI they'll be going away soon with the `req-fix` PR)
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 64 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdpsNtXDijoqNJNPK4_:-Nf6i8zx-VjsDW7-vzkQ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L64)):*
> ```cpp
>   OpTaskBinding binding;
> 
>   binding.bind(PER_DEVICE_STATE, per_device_op_state<ReshapeMeta>());
> ```

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 65 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdpsTRv-FqJEdgEtOej:-Nf6jJMh2OUWXGczwoPa:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L65)):*
> ```cpp
> 
>   binding.bind(PER_DEVICE_STATE, per_device_op_state<ReshapeMeta>());
>   binding.bind(PROFILING, profiling_settings());
> ```

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 94 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpstk_2QeOs-ZoYLbp:-Nf6iPsnBdXTBLLhCHUX:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L94)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

tasks should not care whether their arguments were passed device-specific or not--this is handled by `TaskArgumentAccessor`
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 105 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpt5ZPBWVs59UzVY-9:-Nf6jMbgACzk7hEu4XxN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L105)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Change to take by `const &`
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 127 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdptCSN6nBnstQqJxsc:-Nf6iXRqDowQx9LznSyE:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L127)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Change to take by `const &`
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 160 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdptfBC0FMWrGGpwIuw:-Nf6jNMS4QLtL8jxqVUI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L160)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Also this is missing the task's return type
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 170 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdptpJ-ADRujI5xaAXq:-Nf6jO3j4ydNtBHoKlLA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L170)):*
> ```cpp
> 
>   fwd.add_arg_slot<bool>(PROFILING);
>   fwd.add_unchecked_arg_slot<ReshapePerDeviceState>(PER_DEVICE_STATE);
> ```

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 186 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndptsdn7fPboHDFU0uo:-Nf6j7GU4yl-jUO8nr0Q:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/reshape.cc#L186)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete this whole commented part (we have `master` and git history)
</blockquote></details>

Done.
___
*[`lib/runtime/src/tasks.h` line 76 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NdprBagBe-BYMm-ayOZ:-Nf6h8O22cxBns5Jis4u:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/tasks.h#L76)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Something looks wrong here
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/replicate.h` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndps-9_62A10ydKo6ta:-Nf6hJco4FiqE6CbZbqt:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/runtime/src/ops/replicate.h#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should not be part of this PR?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-25 21:53 UTC, wmdi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: 2 of 6 files reviewed, 20 unresolved discussions (waiting on @KateUnger, @lambda7xx, @lockshaw, and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 27 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NfDJQ6w4OMYagOiyuL8:-NfDJQ6w4OMYagOiyuL9:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/ea161cd63f41761e262ba1a294b7a58b1e2a53dc/lib/kernels/include/kernels/reshape_kernels.h#L27)):*
> ```objc
> 
> void backward_kernel(ffStream_t stream,
>                      ReshapePerDeviceState const $per_device_state,
> ```





_Suggestion:_
```objc
                     ReshapePerDeviceState const &per_device_state,
```


<!-- Sent from Reviewable.io -->

2023-09-26 13:47 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: 2 of 6 files reviewed, 20 unresolved discussions (waiting on @KateUnger, @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 27 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NfDJQ6w4OMYagOiyuL8:-NfGjVCb8YjP8HHr06wJ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ea161cd63f41761e262ba1a294b7a58b1e2a53dc/lib/kernels/include/kernels/reshape_kernels.h#L27)):*
> ```objc
> 
> void backward_kernel(ffStream_t stream,
>                      ReshapePerDeviceState const $per_device_state,
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-09-26 17:48 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: 2 of 6 files reviewed, 19 unresolved discussions (waiting on @KateUnger, @lockshaw, and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpr0_i1Su7wCSvVvqO:-NfHZssEARHm6nFkv36U:buwrwjt) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/kernels/include/kernels/reshape_kernels.h#L16)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why do we have `ReshapePerDeviceState`?


<!-- Sent from Reviewable.io -->

2023-09-26 22:16 UTC, lambda7xx commented
*[`lib/kernels/include/kernels/reshape_kernels.h` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-Ndpr0_i1Su7wCSvVvqO:-NfIY4hV2z-XCOqNM9cH:b-u70jov) ([raw file](https://github.com/flexflow/FlexFlow/blob/15ed89cccb5d0ad9aea4bc87eff5a14c6b1d4ef1/lib/kernels/include/kernels/reshape_kernels.h#L16)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Why do we have `ReshapePerDeviceState`?
</blockquote></details>

the cuda kernel needs  the `ReshapPerdeviceState`


<!-- Sent from Reviewable.io -->

2023-09-27 19:02 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: 2 of 6 files reviewed, 20 unresolved discussions (waiting on @KateUnger, @lambda7xx, @lockshaw, and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 19 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NfN0BIfBkXQ9dce6THK:-NfN0BIfBkXQ9dce6THL:b-x7tm71) ([raw file](https://github.com/flexflow/FlexFlow/blob/63cc83dd409ef929010c2161dacf29071c5d72d7/lib/kernels/include/kernels/reshape_kernels.h#L19)):*
> ```objc
> namespace Reshape {
> 
> ReshapePerDeviceState init_kernel(DataType data_type);
> ```

Where do we implement `init_kernel`?


<!-- Sent from Reviewable.io -->

2023-09-27 20:04 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: 2 of 6 files reviewed, 20 unresolved discussions (waiting on @KateUnger, @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 19 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NfN0BIfBkXQ9dce6THK:-NfNEYNxDzVtG8n09gAw:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/63cc83dd409ef929010c2161dacf29071c5d72d7/lib/kernels/include/kernels/reshape_kernels.h#L19)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Where do we implement `init_kernel`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-27 20:50 UTC, wmdi requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: 2 of 7 files reviewed, 21 unresolved discussions (waiting on @KateUnger, @lambda7xx, @lockshaw, and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/reshape_kernels.h` line 21 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NfNOtMeEkU_D2OT64JN:-NfNOtMeEkU_D2OT64JO:bij9mtc) ([raw file](https://github.com/flexflow/FlexFlow/blob/59166071d31707e62664af61d6bca1a588c168f3/lib/kernels/include/kernels/reshape_kernels.h#L21)):*
> ```objc
> ReshapePerDeviceState init_kernel(DataType data_type);
> 
> void forward_kernel(ffStream_t stream,
> ```

Where do we implement `forward_kernel` and `backward_kernel`?


<!-- Sent from Reviewable.io -->

2023-09-27 21:14 UTC, lambda7xx commented
*[`lib/kernels/include/kernels/reshape_kernels.h` line 21 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1100#-NfNOtMeEkU_D2OT64JN:-NfNUSX1B_5ZnAUq_8hJ:bnd548n) ([raw file](https://github.com/flexflow/FlexFlow/blob/59166071d31707e62664af61d6bca1a588c168f3/lib/kernels/include/kernels/reshape_kernels.h#L21)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Where do we implement `forward_kernel` and `backward_kernel`?
</blockquote></details>

I think Colin implement this. For example, the link is the kernel for reshape [FlexFlow/lib/kernels/src/cuda/reshape\_kernels.cu at repo-refactor-lambda-reshape-OP · lambda7xx/FlexFlow (github.com)](https://github.com/lambda7xx/FlexFlow/blob/repo-refactor-lambda-reshape-OP/lib/kernels/src/cuda/reshape_kernels.cu)


<!-- Sent from Reviewable.io -->

2023-09-27 21:23 UTC, lambda7xx reviewed
> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: all files reviewed, 20 unresolved discussions (waiting on @KateUnger, @lockshaw, @reyna-abhyankar, and @wmdi)



<!-- Sent from Reviewable.io -->

2023-10-02 20:06 UTC, reyna-abhyankar requested changes

2023-10-02 20:06 UTC, reyna-abhyankar commented on lib/runtime/src/ops/reshape.cc
> +  auto bwd_accessor = env.get_bwd_accessor(TOPK_BWD_TASK_ID, bwd_binding);
```suggestion
  auto fwd_accessor = env.get_fwd_accessor(RESHAPE_FWD_TASK_ID, fwd_binding);
  auto bwd_accessor = env.get_bwd_accessor(RESHAPE_BWD_TASK_ID, bwd_binding);
```

2023-10-17 17:09 UTC, reyna-abhyankar requested changes

2023-10-17 17:09 UTC, reyna-abhyankar commented on lib/kernels/src/cuda/reshape_kernels.cu
Update kernels for `ReshapePerDeviceState const & per_device_state`

2023-10-17 17:09 UTC, reyna-abhyankar commented on lib/runtime/src/ops/reshape.cc
> +  auto output_grad = acc.get_tensor<Permissions::WO>(OUTPUT);
```suggestion
  auto input_grad = acc.get_tensor_grad<Permissions::RW>(INPUT);
  auto output_grad = acc.get_tensor_grad<Permissions::RO>(OUTPUT);
```

2023-10-17 17:09 UTC, reyna-abhyankar commented on lib/runtime/src/ops/reshape.cc
> +#include "utils/exception.h"
Why?

2023-10-17 21:12 UTC, lambda7xx commented
*[`lib/runtime/src/ops/reshape.cc` line 19 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1100#gh-1362492111:-NgzTp2e8gep4dCJGYim:b60qj9) ([raw file](https://github.com/flexflow/FlexFlow/blob/bdf4d5e96d1c128b14b424e679df84b8e388f101/lib/runtime/src/ops/reshape.cc#L19)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

maybe it's added by the vscode automatically.


<!-- Sent from Reviewable.io -->

2023-10-18 18:58 UTC, reyna-abhyankar requested changes

2023-10-18 18:58 UTC, reyna-abhyankar commented on lib/kernels/src/cuda/reshape_kernels.cu
Remove the `ReshapePerDeviceState` from `BackwardKernel` struct

2023-10-18 18:58 UTC, reyna-abhyankar commented on lib/kernels/src/cuda/reshape_kernels.cu
>    DataTypeDispatch1<ForwardKernel>{}(m->data_type, stream, m, input, output);
```suggestion
  DataTypeDispatch1<ForwardKernel>{}(m.data_type, stream, input, output);
```

2023-10-18 18:58 UTC, reyna-abhyankar commented on lib/kernels/src/cuda/reshape_kernels.cu
>    DataTypeDispatch1<BackwardKernel>{}(m->data_type, stream, m, input, output);
```suggestion
  DataTypeDispatch1<BackwardKernel>{}(m.data_type, stream, input, output);
```

2023-10-19 00:00 UTC, wmdi submitted a review, later dismissed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: all files reviewed, 27 unresolved discussions (waiting on @lambda7xx, @lockshaw, and @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2023-10-19 00:32 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: all files reviewed, 27 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/src/cuda/reshape_kernels.cu` line 0 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1100#gh-1362490507:-NgzTjnV1h8UpcN21Oj-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/bdf4d5e96d1c128b14b424e679df84b8e388f101/lib/kernels/src/cuda/reshape_kernels.cu#L0)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Update kernels for `ReshapePerDeviceState const & per_device_state`
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/reshape_kernels.cu` line 0 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1100#gh-1364373453:-Nh46YzHEVTHaR5I46wx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/803f0c041581696be35154a39d62b5e7cd19580b/lib/kernels/src/cuda/reshape_kernels.cu#L0)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Remove the `ReshapePerDeviceState` from `BackwardKernel` struct
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/reshape_kernels.cu` line 61 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1100#gh-1364373614:-Nh461299-ThFWHJHla7:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/803f0c041581696be35154a39d62b5e7cd19580b/lib/kernels/src/cuda/reshape_kernels.cu#L61)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
  DataTypeDispatch1<ForwardKernel>{}(m.data_type, stream, input, output);
```
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/reshape_kernels.cu` line 68 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1100#gh-1364373777:-Nh46_MoBX4zSceyVOEA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/803f0c041581696be35154a39d62b5e7cd19580b/lib/kernels/src/cuda/reshape_kernels.cu#L68)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
  DataTypeDispatch1<BackwardKernel>{}(m.data_type, stream, input, output);
```
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 170 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1100#gh-1343099965:-Nfq4WyP-cW13UC0oMQq:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/59166071d31707e62664af61d6bca1a588c168f3/lib/runtime/src/ops/reshape.cc#L170)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
  auto fwd_accessor = env.get_fwd_accessor(RESHAPE_FWD_TASK_ID, fwd_binding);
  auto bwd_accessor = env.get_bwd_accessor(RESHAPE_BWD_TASK_ID, bwd_binding);
```
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/reshape.cc` line 118 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1100#gh-1362491672:-Nh46HnhDZsc5VC4zJ79:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/bdf4d5e96d1c128b14b424e679df84b8e388f101/lib/runtime/src/ops/reshape.cc#L118)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
  auto input_grad = acc.get_tensor_grad<Permissions::RW>(INPUT);
  auto output_grad = acc.get_tensor_grad<Permissions::RO>(OUTPUT);
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-19 18:54 UTC, reyna-abhyankar commented on lib/kernels/src/cuda/reshape_kernels.cu
>    DataTypeDispatch1<ForwardKernel>{}(m->data_type, stream, m, input, output);
You can remove `m` from the kernel calls. It's not used in the actual kernels

2023-10-19 19:40 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1100)* status: 6 of 7 files reviewed, 27 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/kernels/src/cuda/reshape_kernels.cu` line 61 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1100#gh-1364373614:-Nh8K9MJ0BsPW92OVrTv:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/803f0c041581696be35154a39d62b5e7cd19580b/lib/kernels/src/cuda/reshape_kernels.cu#L61)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-24 20:57 UTC, lambda7xx commented on lib/runtime/src/ops/reshape.cc
> +  auto bwd_accessor = env.get_bwd_accessor(TOPK_BWD_TASK_ID, bwd_binding);
ok

2023-11-01 17:43 UTC, merged