SoftMax OP
flexflow/FlexFlow pull request #1106
Opened 2023-09-07 03:36 UTC by lambda7xx

**Description of changes:**
- SoftMax OP 

**Related Issues:**

Linked Issues:
- Issue #1079 

Issues closed by this PR:
- Closes #

2023-10-02 19:46 UTC, reyna-abhyankar requested changes

2023-10-02 19:46 UTC, reyna-abhyankar commented on lib/kernels/include/kernels/softmax_kernels.h
> -  int dim;
I think `dim` is still needed.

2023-10-02 19:46 UTC, reyna-abhyankar commented on lib/runtime/src/ops/softmax.cc
> +  init_binding.bind_arg(HANDLE, ff_handle());
I think `init_binding` only needs this

2023-10-02 19:46 UTC, reyna-abhyankar commented on lib/runtime/src/ops/softmax.cc
> +  binding.bind_arg(HANDLE, ff_handle());
```suggestion
  binding.bind_arg(HANDLE, ff_handle());
  binding.bind_arg(ATTRS, attrs);
```

2023-10-17 16:48 UTC, reyna-abhyankar submitted a review, later dismissed

2023-10-17 16:48 UTC, reyna-abhyankar commented on lib/runtime/src/ops/softmax.cc
> +  auto input = acc.get_tensor<Permissions::RO>(A_INPUT);
```suggestion
  auto input = acc.get_tensor<Permissions::RO>(INPUT);
```

2023-10-17 16:48 UTC, reyna-abhyankar commented on lib/runtime/src/ops/softmax.cc
> +  auto output_grad = acc.get_tensor<Permissions::RO>(OUTPUT);
```suggestion
  auto output_grad = acc.get_tensor_grad<Permissions::RO>(OUTPUT);
```

2023-10-17 16:48 UTC, reyna-abhyankar commented on lib/runtime/src/ops/softmax.cc
> +  fwd.add_arg_slot<bool>(PROFILING);
```suggestion
  fwd.add_arg_slot<ProfilingSettings>(PROFILING);
```

2023-10-18 20:10 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/flexflow/1106)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/softmax_kernels.h` line 0 at r1](https://reviewable.io/reviews/flexflow/flexflow/1106#gh-1343085227:-NgzRMaF4PSKWGRweEeA:b-896fix) ([raw file](https://github.com/flexflow/flexflow/blob/675a22b33920974b0b5feaae2ae78f3364088a54/lib/kernels/include/kernels/softmax_kernels.h#L0)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/flexflow/FlexFlow/pull/1106#discussion_r1343085227) to the right spot — sorry!)*

I think `dim` is still needed. 
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/softmax.cc` line 60 at r1](https://reviewable.io/reviews/flexflow/flexflow/1106#gh-1343088111:-NgzRO_W5eD7xlwJGdue:b-896fix) ([raw file](https://github.com/flexflow/flexflow/blob/675a22b33920974b0b5feaae2ae78f3364088a54/lib/runtime/src/ops/softmax.cc#L60)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
  binding.bind_arg(HANDLE, ff_handle());
  binding.bind_arg(ATTRS, attrs);
```
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/softmax.cc` line 168 at r1](https://reviewable.io/reviews/flexflow/flexflow/1106#gh-1343087453:-NgzRjgrC_-FXXpR9qmB:b-896fix) ([raw file](https://github.com/flexflow/flexflow/blob/675a22b33920974b0b5feaae2ae78f3364088a54/lib/runtime/src/ops/softmax.cc#L168)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I think `init_binding` only needs this
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/softmax.cc` line 93 at r3](https://reviewable.io/reviews/flexflow/flexflow/1106#gh-1362461955:-NgzRUFQCRdIj-2C0Djs:b-896fix) ([raw file](https://github.com/flexflow/flexflow/blob/8c424a967f1ddefc552b134eb31937c348c7195f/lib/runtime/src/ops/softmax.cc#L93)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
  auto input = acc.get_tensor<Permissions::RO>(INPUT);
```
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/softmax.cc` line 122 at r3](https://reviewable.io/reviews/flexflow/flexflow/1106#gh-1362462568:-NgzRc45EORg99wsV_O9:b-896fix) ([raw file](https://github.com/flexflow/flexflow/blob/8c424a967f1ddefc552b134eb31937c348c7195f/lib/runtime/src/ops/softmax.cc#L122)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
  auto output_grad = acc.get_tensor_grad<Permissions::RO>(OUTPUT);
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-19 18:51 UTC, reyna-abhyankar approved these changes

2023-10-19 18:51 UTC, merged