Conv 2D Op
flexflow/FlexFlow pull request #1112
Opened 2023-09-07 21:12 UTC by KateUnger

**Description of changes:**

- Update Conv_2d operator

**TODO**: Change `conv2d_kernels.cpp` and `conv2d_kernels.cu`

**Related Issues:**

Linked Issues:
- Issue #1053

Issues closed by this PR:
- Closes #1053

2023-09-08 00:17 UTC, lockshaw reviewed
This is mostly correct except for the interaction with `kernels` (in particular, `init_kernel`). Any `ff<Thing>_t` (like `ffTensorDescriptor_t` is a cuda/hip thing and should be initialized in `init_kernel` based on the operator attributes and potentially the tensor shapes, not passed in--initializing these cuda/hip objects from the non-cuda/hip operator description is the essentially the whole point of `init_kernel`

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-:-Ndm8Dc_8l36qF4CR8Gn:b-tme2g4)* status: all files reviewed, 9 unresolved discussions (waiting on @KateUnger)

___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 19 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm6xyF2sGF7CxEr7bx:-Ndm6xyF2sGF7CxEr7by:bm7dxrh) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/kernels/include/kernels/conv_2d_kernels.h#L19)):*
> ```objc
>   ffConvolutionBwdFilterAlgo_t bwdFilterAlgo;
>   ffConvolutionBwdDataAlgo_t bwdDataAlgo;
>   req<optional<Activation>> activation;
> ```

Only the last field needs `req`



_Suggestion:_
```objc
optional<Activation> activation;
```
___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 50 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm74g41L09HcjGVYcf:-Ndm74g41L09HcjGVYcg:b-be3i1a) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/kernels/include/kernels/conv_2d_kernels.h#L50)):*
> ```objc
>                                  ffConvolutionBwdFilterAlgo_t bwdFilterAlgo,
>                                  ffConvolutionBwdDataAlgo_t bwdDataAlgo,
>                                  req<optional<Activation>> relu,
> ```

`req` should only be a struct field and should not be passed around



_Suggestion:_
```objc
Conv2DPerDeviceState init_kernel(PerDeviceFFHandle handle,
                                 ffTensorDescriptor_t inputTensor,
                                 ffTensorDescriptor_t biasTensor,
                                 ffTensorDescriptor_t outputTensor,
                                 ffFilterDescriptor_t filterDesc,
                                 ffActivationDescriptor_t actiDesc,
                                 ffConvolutionDescriptor_t convDesc,
                                 ffConvolutionFwdAlgo_t fwdAlgo,
                                 ffConvolutionBwdFilterAlgo_t bwdFilterAlgo,
                                 ffConvolutionBwdDataAlgo_t bwdDataAlgo,
                                 optional<Activation> relu,
```
___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 50 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7DV16XwH3MHsIiD1:-Ndm7DV16XwH3MHsIiD2:b-g4kbaq) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/kernels/include/kernels/conv_2d_kernels.h#L50)):*
> ```objc
>                                  ffConvolutionBwdFilterAlgo_t bwdFilterAlgo,
>                                  ffConvolutionBwdDataAlgo_t bwdDataAlgo,
>                                  req<optional<Activation>> relu,
> ```

No cuda objects can be passed in--they should be created in `init_kernel`



_Suggestion:_
```objc
Conv2DPerDeviceState init_kernel(PerDeviceFFHandle handle,
                                 req<optional<Activation>> relu)
```
___
*[`lib/runtime/src/ops/conv_2d.h` line 137 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7NKz0Go52-ZY_I2S:-Ndm7NKz0Go52-ZY_I2T:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.h#L137)):*
> ```objc
> 
> #endif
> ```

Delete
___
*[`lib/runtime/src/ops/conv_2d.cc` line 62 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7YohDjfp-kmaxiPt:-Ndm7YohDjfp-kmaxiPu:biwrhsm) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.cc#L62)):*
> ```cpp
> 
>   PerDeviceFFHandle handle = acc.get_argument<PerDeviceFFHandle>(HANDLE);
>   auto const &attrs = acc.get_argument<Conv2DAttrs>(ATTRS);
> ```

Honestly just copy, the ref isn't worth it



_Suggestion:_
```cpp
  auto attrs = acc.get_argument<Conv2DAttrs>(ATTRS);
```
___
*[`lib/runtime/src/ops/conv_2d.cc` line 72 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7cliCZ64O7Z2U0P0:-Ndm7cliCZ64O7Z2U0P1:b-tsaf93) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.cc#L72)):*
> ```cpp
>   ffConvolutionFwdAlgo_t fwdAlgo;
>   ffConvolutionBwdFilterAlgo_t bwdFilterAlgo;
>   ffConvolutionBwdDataAlgo_t bwdDataAlgo;
> ```

All of these should be create in `init_kernel`, not passed in



_Code quote:_
```cpp
  ffTensorDescriptor_t inputTensor;
  ffTensorDescriptor_t biasTensor;
  ffTensorDescriptor_t outputTensor;
  ffFilterDescriptor_t filterDesc;
  ffActivationDescriptor_t actiDesc;
  ffConvolutionDescriptor_t convDesc;
  ffConvolutionFwdAlgo_t fwdAlgo;
  ffConvolutionBwdFilterAlgo_t bwdFilterAlgo;
  ffConvolutionBwdDataAlgo_t bwdDataAlgo;
```
___
*[`lib/runtime/src/ops/conv_2d.cc` line 87 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7gYPAidrJ3J7ARnD:-Ndm7gYPAidrJ3J7ARnE:b-qrderu) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.cc#L87)):*
> ```cpp
>                       bwdDataAlgo,
>                       attrs.activation,
>                       attrs.use_bias));
> ```

`init_kernel` should just be a function of the handle and the attrs (and any shape info from `parallel_tensor_shape` etc)



_Code quote:_
```cpp
          init_kernel(handle,
                      inputTensor,
                      biasTensor,
                      outputTensor,
                      filterDesc,
                      actiDesc,
                      convDesc,
                      fwdAlgo,
                      bwdFilterAlgo,
                      bwdDataAlgo,
                      attrs.activation,
                      attrs.use_bias));
```
___
*[`lib/runtime/src/ops/conv_2d.cc` line 114 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7sBK-7qdvk76JZO8:-Ndm7sBK-7qdvk76JZO9:bvebc73) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.cc#L114)):*
> ```cpp
>                  profiling,
>                  "[Conv2d] forward_time = %.2lfms\n",
>                  &per_device_state,
> ```

Change `forward_kernel` to take the state by reference instead of by pointer
___
*[`lib/runtime/src/ops/conv_2d.cc` line 146 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7ySD-P72JBW8Z6am:-Ndm7ySD-P72JBW8Z6an:b4kwbih) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.cc#L146)):*
> ```cpp
>                  profiling,
>                  "[Conv2d] backward_time = %.2lfms\n",
>                  &per_device_state,
> ```

Change `backward_kernel` to take the per device state as `const &`, not as a pointer


<!-- Sent from Reviewable.io -->

2023-09-10 18:52 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1112)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @KateUnger and @lockshaw)

___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 19 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm6xyF2sGF7CxEr7bx:-Ne-PRjo50CVUl8f62wc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/kernels/include/kernels/conv_2d_kernels.h#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Only the last field needs `req`
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 50 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm74g41L09HcjGVYcf:-Ne-PTLLCHcV4npTt8ye:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/kernels/include/kernels/conv_2d_kernels.h#L50)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`req` should only be a struct field and should not be passed around
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 50 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7DV16XwH3MHsIiD1:-Ne-P_7zC07YpvVW3vZA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/kernels/include/kernels/conv_2d_kernels.h#L50)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

No cuda objects can be passed in--they should be created in `init_kernel`
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/conv_2d.h` line 137 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7NKz0Go52-ZY_I2S:-Ne-Pe7n6rw3GlaR8Q7p:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.h#L137)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/conv_2d.cc` line 62 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7YohDjfp-kmaxiPt:-Ne-PlRn5M8-PfvSHwxw:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.cc#L62)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Honestly just copy, the ref isn't worth it
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/conv_2d.cc` line 72 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7cliCZ64O7Z2U0P0:-Ne-PnOQAc-kuLluSi5w:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.cc#L72)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

All of these should be create in `init_kernel`, not passed in
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/conv_2d.cc` line 87 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7gYPAidrJ3J7ARnD:-Ne-PqI24WWQgCqxPU9o:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.cc#L87)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`init_kernel` should just be a function of the handle and the attrs (and any shape info from `parallel_tensor_shape` etc)
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/conv_2d.cc` line 114 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7sBK-7qdvk76JZO8:-Ne-R-A-42ijcNg06Cqp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.cc#L114)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Change `forward_kernel` to take the state by reference instead of by pointer
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/conv_2d.cc` line 146 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ndm7ySD-P72JBW8Z6am:-Ne-R-aw8t6XXKgmSQg1:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/30959792bd0b82e49a5feb53ffd918e214149fed/lib/runtime/src/ops/conv_2d.cc#L146)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Change `backward_kernel` to take the per device state as `const &`, not as a pointer
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-12 00:12 UTC, lockshaw requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1112)* status: all files reviewed, 20 unresolved discussions (waiting on @KateUnger)

___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 14 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5fEn42UwAmkQu3DpJ:-Ne5fEn42UwAmkQu3DpK:b9g2a6y) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/include/kernels/conv_2d_kernels.h#L14)):*
> ```objc
> struct Conv2DPerDeviceState {
>   PerDeviceFFHandle handle;
>   optional<Activation> activation;
> ```

Why does this even have an `activation` field? It should probably be removed, along with `Conv2DPerDeviceState::use_bias` as both of them are available from the `Conv2DAttrs`
___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 25 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5fVB44DT_sxG3Jdh6:-Ne5fVB44DT_sxG3Jdh7:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/include/kernels/conv_2d_kernels.h#L25)):*
> ```objc
>   ffConvolutionFwdAlgo_t fwdAlgo;
>   ffConvolutionBwdFilterAlgo_t bwdFilterAlgo;
>   ffConvolutionBwdDataAlgo_t bwdDataAlgo;
> ```





_Suggestion:_
```objc
  req<ffConvolutionBwdDataAlgo_t> bwdDataAlgo;
```
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 46 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5hEUP8fQqmj5fEEl4:-Ne5hEUP8fQqmj5fEEl5:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L46)):*
> ```Cuda
>   }
>   return perfResults[0].algo;
> }
> ```





_Suggestion:_
```Cuda
cudnnConvolutionBwdDataAlgo_t selectConvolutionBackwardDataAlgorithm(
    cudnnHandle_t handle,
    const cudnnFilterDescriptor_t wDesc,
    void const *w,
    const cudnnTensorDescriptor_t dyDesc,
    void const *dy,
    const cudnnConvolutionDescriptor_t convDesc,
    void *workSpace,
    size_t workSpaceSize,
    const cudnnTensorDescriptor_t dxDesc,
    void *dx,
    float *time) {
  int const reqAlgCnt = 8;
  int cnt = 0;
  cudnnConvolutionBwdDataAlgoPerf_t perfResults[reqAlgCnt];
  checkCUDNN(cudnnFindConvolutionBackwardDataAlgorithmEx(handle,
                                                         wDesc,
                                                         w,
                                                         dyDesc,
                                                         dy,
                                                         convDesc,
                                                         dxDesc,
                                                         dx,
                                                         reqAlgCnt,
                                                         &cnt,
                                                         perfResults,
                                                         workSpace,
                                                         workSpaceSize));
  assert(cnt > 0);
  checkCUDNN(perfResults[0].status);
  if (time != nullptr) {
    *time = perfResults[0].time;
  }
  return perfResults[0].algo;
}
```
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 85 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5hABx6N3VxsZkPOtz:-Ne5hABx6N3VxsZkPOu-:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L85)):*
> ```Cuda
>   }
>   return perfResults[0].algo;
> }
> ```





_Suggestion:_
```Cuda
  assert(cnt > 0);
  checkCUDNN(perfResults[0].status);
  if (time != nullptr) {
    *time = perfResults[0].time;
  }
  return perfResults[0].algo;
}
```
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 124 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5hM-N8DtDaewdYTLC:-Ne5hM-N8DtDaewdYTLD:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L124)):*
> ```Cuda
>   }
>   return perfResults[0].algo;
> }
> ```





_Suggestion:_
```Cuda
cudnnConvolutionBwdFilterAlgo_t selectConvolutionBackwardFilterAlgorithm(
    cudnnHandle_t handle,
    const cudnnTensorDescriptor_t xDesc,
    void const *x,
    const cudnnTensorDescriptor_t dyDesc,
    void const *dy,
    const cudnnConvolutionDescriptor_t convDesc,
    void *workSpace,
    size_t workSpaceSize,
    const cudnnFilterDescriptor_t dwDesc,
    void *dw,
    float *time) {
  int const reqAlgCnt = 8;
  int cnt = 0;
  cudnnConvolutionBwdFilterAlgoPerf_t perfResults[reqAlgCnt];
  checkCUDNN(cudnnFindConvolutionBackwardFilterAlgorithmEx(handle,
                                                           xDesc,
                                                           x,
                                                           dyDesc,
                                                           dy,
                                                           convDesc,
                                                           dwDesc,
                                                           dw,
                                                           reqAlgCnt,
                                                           &cnt,
                                                           perfResults,
                                                           workSpace,
                                                           workSpaceSize));
  assert(cnt > 0);
  checkCUDNN(perfResults[0].status);
  if (time != nullptr) {
    *time = perfResults[0].time;
  }
  return perfResults[0].algo;
}
```
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 185 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5h_9i7VTxzqBBc87Q:-Ne5h_9i7VTxzqBBc87R:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L185)):*
> ```Cuda
>          kernel_w,
>          input_c / groups,
>          output_c);
> ```


___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 202 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5heD138fmwWxjbEQy:-Ne5heD138fmwWxjbEQz:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L202)):*
> ```Cuda
>                                              1 /*upscale_y*/,
>                                              CUDNN_CROSS_CORRELATION,
>                                              CUDNN_DATA_FLOAT));
> ```





_Suggestion:_
```Cuda
  checkCUDNN(cudnnSetConvolution2dDescriptor(convDesc,
                                             pad_h,
                                             pad_w,
                                             stride_h,
                                             stride_w,
                                             1 /*upscale_x*/,
                                             1 /*upscale_y*/,
                                             CUDNN_CROSS_CORRELATION,
                                             CUDNN_DATA_FLOAT));
```
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 238 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5hpJBC39016ZhNRt4:-Ne5hpJBC39016ZhNRt5:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L238)):*
> ```Cuda
>                                               outputTensor,
>                                               output.get_float_ptr(),
>                                               &time);
> ```





_Suggestion:_
```Cuda
  // select forward algorithm
  fwdAlgo = selectConvolutionForwardAlgorithm(handle.dnn,
                                              inputTensor,
                                              input.get_float_ptr(),
          [...]

2023-09-12 20:42 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1112)* status: all files reviewed, 20 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 14 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5fEn42UwAmkQu3DpJ:-NeA40sA0IOvXvfr_EyH:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/include/kernels/conv_2d_kernels.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does this even have an `activation` field? It should probably be removed, along with `Conv2DPerDeviceState::use_bias` as both of them are available from the `Conv2DAttrs`
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 25 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5fVB44DT_sxG3Jdh6:-NeA4QXX0UEwoZf_oatO:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/include/kernels/conv_2d_kernels.h#L25)):*
> ```objc
>   ffConvolutionFwdAlgo_t fwdAlgo;
>   ffConvolutionBwdFilterAlgo_t bwdFilterAlgo;
>   ffConvolutionBwdDataAlgo_t bwdDataAlgo;
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 46 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5hEUP8fQqmj5fEEl4:-NeA4btI7odhSxAMsNTs:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L46)):*
> ```Cuda
>   }
>   return perfResults[0].algo;
> }
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 85 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5hABx6N3VxsZkPOtz:-NeA4cZ-6ghiQ3FZpDGT:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L85)):*
> ```Cuda
>   }
>   return perfResults[0].algo;
> }
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 124 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5hM-N8DtDaewdYTLC:-NeA4dWO6WwiLPdNCuHe:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L124)):*
> ```Cuda
>   }
>   return perfResults[0].algo;
> }
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 185 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5h_9i7VTxzqBBc87Q:-NeA4ehe0iAajnoUJ6SW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L185)):*
> ```Cuda
>          kernel_w,
>          input_c / groups,
>          output_c);
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 202 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5heD138fmwWxjbEQy:-NeA4khuEoTQXodpbHm6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L202)):*
> ```Cuda
>                                              1 /*upscale_y*/,
>                                              CUDNN_CROSS_CORRELATION,
>                                              CUDNN_DATA_FLOAT));
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 238 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5hpJBC39016ZhNRt4:-NeA4qInECPiPsi8Aq-t:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L238)):*
> ```Cuda
>                                               outputTensor,
>                                               output.get_float_ptr(),
>                                               &time);
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 252 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5htMW815e2nsH2DFo:-NeA4vKe41G8pD-1qd71:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L252)):*
> ```Cuda
>                                                filterDesc,
>                                                filter_grad_ptr,
>                                                &time);
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 265 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5hw7E6jm40NP1P9Y4:-NeA4yQ-EWpzw01VZoB7:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L265)):*
> ```Cuda
>                                                        inputTensor,
>                                                        input.get_float_ptr(),
>                                                        &time);
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 282 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5i0S493flowzJHoUi:-NeA50wR789d_JhZIQW6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L282)):*
> ```Cuda
>                                            fwdAlgo,
>                                            bwdFilterAlgo,
>                                            bwdDataAlgo};
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 291 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5iP5j8T95rUDIr4vH:-NeA5Rhn-RFmzlM6GmHX:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L291)):*
> ```Cuda
>                     float *output_ptr,
>                     float const *filter_ptr,
>                     float const *bias_ptr) {
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 292 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5iAcf6ktAU8IUJjMP:-NeA61LY5xGroiLLa9t4:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L292)):*
> ```Cuda
>                     float const *filter_ptr,
>                     float const *bias_ptr) {
>   checkCUDNN(cudnnSetStream(m->handle.dnn, stream));
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 307 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5iDORBTKn6DfiCzd8:-NeA62cu3noYFZMUjXy7:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L307)):*
> ```Cuda
>                                      &beta,
>                                      m->outputTensor,
>                                      output_ptr));
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 317 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5iIge2-hbZCaMzcN2:-NeA63Lu5tmZPiiH6rMf:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L317)):*
> ```Cuda
>                               &alpha,
>                               m->outputTensor,
>                               output_ptr));
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 322 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5iXXy-YSA4aJQpSIK:-NeA64EeEISvsy5peMZ2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3aad5eb5802ba65173e5b6826c6089e629475f41/lib/kernels/src/cuda/conv_2d_kernels.cu#L322)):*
> ```Cuda
>     checkCUDNN(cudnnActivationForward(m->handle.dnn,
>                                       m->actiDesc,
>                                       &alpha,
> ```

Done.
___
*[`lib/kernels/src/cuda/conv_2d_kernels.cu` line 344 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1112#-Ne5ibYy6-FGmG-gSTZR:-NeA65FH6_mQSQFfut9H:b-896f [...]

2023-09-13 00:29 UTC, lockshaw approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KateUnger)



<!-- Sent from Reviewable.io -->

2023-09-13 00:29 UTC, merged