Repartition OP
flexflow/FlexFlow pull request #1119
Opened 2023-09-08 07:17 UTC by lambda7xx

**Description of changes:**
- update the Repartition OP

**Related Issues:**

Linked Issues:
- Issue #1074 

Issues closed by this PR:
- Closes #1074

2023-09-27 21:36 UTC, wmdi requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1119)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @lambda7xx, @lockshaw, and @reyna-abhyankar)

___
*[`lib/runtime/src/ops/partition.cc` line 72 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1119#-NfNSw9uCevi_clHxqOe:-NfNSw9uCevi_clHxqOf:b-9wroup) ([raw file](https://github.com/flexflow/FlexFlow/blob/06c96ad8d75ab27e529c332898232191083ad4cd/lib/runtime/src/ops/partition.cc#L72)):*
> ```cpp
>   OpTaskBinding binding;
> 
>   binding.bind_arg(HANDLE, ff_handle());
> ```

Where is `HANDLE`?
___
*[`lib/runtime/src/ops/partition.cc` line 89 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1119#-NfNUAuh-PKCz1JeXTRt:-NfNUAuh-PKCz1JeXTRu:b45h) ([raw file](https://github.com/flexflow/FlexFlow/blob/06c96ad8d75ab27e529c332898232191083ad4cd/lib/runtime/src/ops/partition.cc#L89)):*
> ```cpp
> }
> 
> OpTaskInvocation backward(CastAttrs const &attrs) {
> ```





_Suggestion:_
```cpp
OpTaskInvocation backward(RepartitionAttrs const &attrs) {
```
___
*[`lib/runtime/src/ops/partition.cc` line 92 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1119#-NfNXjvVCuP1Ax1F_7Af:-NfNXjvW6vJtojGUyG3V:b-koewhj) ([raw file](https://github.com/flexflow/FlexFlow/blob/06c96ad8d75ab27e529c332898232191083ad4cd/lib/runtime/src/ops/partition.cc#L92)):*
> ```cpp
>   OpTaskBinding binding = infer_bwd_binding(forward(attrs).binding);
> 
>   PerDeviceFFHandle handle = acc.get_argument<PerDeviceFFHandle>(HANDLE);
> ```

`handle` is unused


<!-- Sent from Reviewable.io -->

2023-09-30 05:22 UTC, reyna-abhyankar requested changes

2023-09-30 05:22 UTC, reyna-abhyankar commented on lib/runtime/src/ops/partition.cc
> +  PerDeviceFFHandle handle = acc.get_argument<PerDeviceFFHandle>(HANDLE);
```suggestion

```

2023-09-30 05:22 UTC, reyna-abhyankar commented on lib/runtime/src/ops/partition.cc
> +enum Slots { INPUT, OUTPUT, ATTRS, PROFILING };
```suggestion
enum Slots { INPUT, OUTPUT, ATTRS, PROFILING, HANDLE };
```

2023-09-30 05:22 UTC, reyna-abhyankar commented on lib/runtime/src/ops/partition.cc
> +  registar_task(REPARTITION_BWD_TASK_ID, "Repartition Bwd", bwd, backward_task);
```suggestion
  register_task(REPARTITION_BWD_TASK_ID, "Repartition Bwd", bwd, backward_task);
```

2023-09-30 13:13 UTC, lambda7xx commented on lib/runtime/src/ops/partition.cc
> +  registar_task(REPARTITION_BWD_TASK_ID, "Repartition Bwd", bwd, backward_task);
pushed

2023-10-17 16:08 UTC, reyna-abhyankar approved these changes

2023-10-17 20:38 UTC, lambda7xx commented
*[`lib/runtime/src/ops/partition.cc` line 45 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1119#gh-1341912783:-NgzLuI-DDUmNdl471xw:baptkx5) ([raw file](https://github.com/flexflow/FlexFlow/blob/986af8faa8549de36e2e5da7937771447d2f7bc9/lib/runtime/src/ops/partition.cc#L45)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
enum Slots { INPUT, OUTPUT, ATTRS, PROFILING, HANDLE };
```
</blockquote></details>

we should add `PER_DEVICE_STATE` for forward and backward


<!-- Sent from Reviewable.io -->

2023-10-17 20:38 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1119)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @reyna-abhyankar and @wmdi)

___
*[`lib/runtime/src/ops/partition.cc` line 72 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1119#-NfNSw9uCevi_clHxqOe:-NgzLQTs31b2tcGU4VsT:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/06c96ad8d75ab27e529c332898232191083ad4cd/lib/runtime/src/ops/partition.cc#L72)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Where is `HANDLE`?
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/partition.cc` line 89 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1119#-NfNUAuh-PKCz1JeXTRt:-NgzLSIcDMCEQrSLAMvc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/06c96ad8d75ab27e529c332898232191083ad4cd/lib/runtime/src/ops/partition.cc#L89)):*
> ```cpp
> }
> 
> OpTaskInvocation backward(CastAttrs const &attrs) {
> ```

Done.
___
*[`lib/runtime/src/ops/partition.cc` line 92 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1119#-NfNXjvVCuP1Ax1F_7Af:-NgzLeMwEl90w2f3_X8g:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/06c96ad8d75ab27e529c332898232191083ad4cd/lib/runtime/src/ops/partition.cc#L92)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

`handle` is unused
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/partition.cc` line 92 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1119#gh-1341912722:-NgzLtZG3upDhP3YGxFX:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/986af8faa8549de36e2e5da7937771447d2f7bc9/lib/runtime/src/ops/partition.cc#L92)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion

```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-18 01:02 UTC, wmdi approved these changes
> Reviewed 2 of 5 files at r1, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1119)* status: all files reviewed, 3 unresolved discussions (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2023-11-01 18:20 UTC, merged