Gather Op
flexflow/FlexFlow pull request #1165
Opened 2023-10-01 21:23 UTC by KateUnger

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #1068 

Issues closed by this PR:
- Closes #1068

2024-02-07 22:47 UTC, reyna-abhyankar requested changes

2024-02-07 22:47 UTC, reyna-abhyankar commented on lib/kernels/src/cuda/gather_kernels.cu
Based on the old kernel code, we should still template the gather index datatype.

2024-02-07 22:47 UTC, reyna-abhyankar commented on lib/runtime/src/ops/gather.cc
> +      infer_bwd_signature(get_op_signature(GATHER_BWD_TASK_ID));
```suggestion
      infer_bwd_signature(get_fwd_signature(GATHER_BWD_TASK_ID));
```
And I think fix the `register_fwd_task`

2024-05-31 05:42 UTC, lockshaw commented
@reyna-abhyankar Can this be closed now as it's superseded by #1389?

2024-05-31 17:52 UTC, lockshaw commented
Superseded by #1389.

2024-05-31 17:52 UTC, closed without merging