linear operator
flexflow/FlexFlow pull request #1180
Opened 2023-10-07 22:47 UTC by lambda7xx

**Description of changes:**
- [x] update the linear operator
- [ ] `init_kernel` has some problem, we need to fix it. 

**Related Issues:**

Linked Issues:
- Issue #1071

Issues closed by this PR:
- Closes #

2023-11-01 23:32 UTC, reyna-abhyankar requested changes

2023-11-01 23:32 UTC, reyna-abhyankar commented on lib/kernels/src/cuda/linear_kernels.cu
> +                Activation activation,
What is `Activation` I think this should be `ActiMode`

2023-11-01 23:32 UTC, reyna-abhyankar commented on lib/kernels/src/cuda/linear_kernels.cu
> +  // bytes to allocate?
Use the same allocation method that is in the original constructor for `LinearPerDeviceState`

2023-11-01 23:32 UTC, reyna-abhyankar commented on lib/runtime/src/ops/element_binary.cc
> +  return init; // todo:this may be wrong, because the headfile retrun void
Don't worry about it in this PR. If it's a problem, you can open an issue

2023-11-01 23:32 UTC, reyna-abhyankar commented on lib/runtime/src/ops/linear.cc
> +  ATTR,
```suggestion
  ATTRS,
```

2023-11-01 23:32 UTC, reyna-abhyankar commented on lib/runtime/src/ops/linear.cc
> +}; // Note: this needs add more
Why?

2023-11-01 23:32 UTC, reyna-abhyankar commented on lib/runtime/src/ops/linear.cc
> +  bind.bind_arg(ATTR, attrs);
```suggestion
  bind.bind_arg(ATTRS, attrs);
```

2023-11-01 23:32 UTC, reyna-abhyankar commented on lib/runtime/src/ops/linear.cc
> +          init_kernel(handle,
I don't think this function call matches what you have in the kernel.

2023-11-01 23:32 UTC, reyna-abhyankar commented on lib/runtime/src/ops/linear.cc
> +  int batch_size = output.shape.get_volume() / out_dim;
We had agreed previously that `ff_dim_t{1}` is batch size. Is this equivalent?

2023-11-01 23:32 UTC, reyna-abhyankar commented on lib/runtime/src/ops/linear.cc
> +  int out_dim = output.shape.at(ff_dim_t{0}) + 1;
Why the `+ 1`?

2023-11-01 23:32 UTC, reyna-abhyankar commented on lib/runtime/src/ops/linear.cc
> +                                  ParallelTensorShape const &input_shape,
I think these should always be `InputParallelTensorDesc` instead of `ParallelTensorShape`

2024-01-17 21:30 UTC, reyna-abhyankar commented on deps/fmt
Use most updated submodules

2024-02-06 11:09 UTC, lambda7xx commented
*[`lib/runtime/src/ops/linear.cc` line 86 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1379424984:-Npy5p8w5GMOgZ0LptEc:b2b56kx) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/lib/runtime/src/ops/linear.cc#L86)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

We had agreed previously that `ff_dim_t{1}` is batch size. Is this equivalent?
</blockquote></details>

ok, make sense


<!-- Sent from Reviewable.io -->

2024-02-06 11:12 UTC, lambda7xx commented
*[`lib/runtime/src/ops/linear.cc` line 92 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1379424690:-Npy6CkmBEUXtUrRknpg:bz68zmd) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/lib/runtime/src/ops/linear.cc#L92)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I don't think this function call matches what you have in the kernel.
</blockquote></details>

where?  maybe this. should be 



_Code snippet:_
```cpp


  DeviceSpecific<LinearPerDeviceState> state =
      acc.create_device_specific<LinearPerDeviceState>(
          init_kernel(handle,
                      allocator,
                      one_ptr,
                      attrs.regularizer,
                      attrs.use_bias,
                      input.data_type,
                      weight.data_type,
                      output.data_type,
                      batch_size,
                      attrs.out_channels));
  return state;
}
```


<!-- Sent from Reviewable.io -->

2024-02-07 21:34 UTC, reyna-abhyankar commented on lib/kernels/src/cuda/linear_kernels.cu
> +  checkCUDA(cudaMalloc(one_ptr, sizeof(float) * batch_size));
```suggestion
  checkCUDA(cudaMalloc(&one_ptr, sizeof(float) * batch_size));
```

2024-02-07 23:31 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1180)* status: 0 of 6 files reviewed, 12 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/src/cuda/linear_kernels.cu` line 28 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1379422817:-Npy4I3n6ozFLoXDRffL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/lib/kernels/src/cuda/linear_kernels.cu#L28)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

What is `Activation` I think this should be `ActiMode`
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/linear_kernels.cu` line 71 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1379422965:-Npy5ByfAmVPedhcNQt0:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/lib/kernels/src/cuda/linear_kernels.cu#L71)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Use the same allocation method that is in the original constructor for `LinearPerDeviceState`
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/element_binary.cc` line 216 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1379423637:-Npy5Dp1-8AOz0MZCutt:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/lib/runtime/src/ops/element_binary.cc#L216)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Don't worry about it in this PR. If it's a problem, you can open an issue
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/linear.cc` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1379423976:-Npy5ZC71LwOhDlVO1R2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/lib/runtime/src/ops/linear.cc#L37)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
  ATTRS,
```
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/linear.cc` line 40 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1379424007:-Npy5bBJEaTkVwGA1OS3:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/lib/runtime/src/ops/linear.cc#L40)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/linear.cc` line 46 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1379424134:-Npy5dtc-qybWiEi1DoI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/lib/runtime/src/ops/linear.cc#L46)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

```suggestion
  bind.bind_arg(ATTRS, attrs);
```
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/linear.cc` line 85 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1379425105:-Npy5hVj93xNk76oAM91:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/lib/runtime/src/ops/linear.cc#L85)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why the `+ 1`? 
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/linear.cc` line 202 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1379427492:-Nq4sxCaCXxZPRxZ1W4x:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/lib/runtime/src/ops/linear.cc#L202)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I think these should always be `InputParallelTensorDesc` instead of `ParallelTensorShape`
</blockquote></details>

Done.
___
*[`deps/fmt` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1180#gh-1456506559:-Nq4sy-eEBOzqGrluW2u:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2f5908c89f260ad8ed6de8d024cbd318727167c8/deps/fmt#L0)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Use most updated submodules
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-07 23:57 UTC, reyna-abhyankar approved these changes

2024-02-07 23:57 UTC, merged