Pool2D OP
flexflow/FlexFlow pull request #1182
Opened 2023-10-08 14:03 UTC by lambda7xx

**Description of changes:**
- Pool2D OP

**Related Issues:**

Linked Issues:
- Issue #1072

Issues closed by this PR:
- Closes #

2023-10-10 18:21 UTC, reyna-abhyankar requested changes

2023-10-10 18:21 UTC, reyna-abhyankar commented on lib/kernels/src/cuda/pool_2d_kernels.cu
Also do hip kernel?

2023-10-10 18:21 UTC, reyna-abhyankar commented on lib/runtime/src/ops/pool_2d.cc
Split signature from register task

2023-10-23 18:25 UTC, reyna-abhyankar commented on lib/runtime/src/ops/pool_2d.cc
> +  NOT_IMPLEMENTED();
@lambda7xx is this still not implemented?

2023-10-25 22:50 UTC, lambda7xx commented
*[`lib/runtime/src/ops/pool_2d.cc` line 28 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1182#gh-1369088886:-Nhd0wjo7P_7Y9T9aUn6:b4wfniu) ([raw file](https://github.com/flexflow/FlexFlow/blob/2928870914f07658e47ec7045b94c566888641ea/lib/runtime/src/ops/pool_2d.cc#L28)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

@lambda7xx is this still not implemented?
</blockquote></details>

remove the ` NOT_IMPLEMENTED();`


<!-- Sent from Reviewable.io -->

2023-11-01 23:34 UTC, reyna-abhyankar approved these changes

2023-11-01 23:47 UTC, merged