get_output_shape draft
flexflow/FlexFlow pull request #1183
Opened 2023-10-08 22:07 UTC by lambda7xx

**Description of changes:**
- [ ] `get_output_shape ` for each OP
- [ ] AggregateSpecAttrs 
- [x] AggregateAttrs 
- [x] MultiHeadAttentionAttrs
- [x] BatchMatmulAttr
- [x] BatchNormAttrs
- [ ] BroadcastAttrs
- [x] CastAttrs
- [x] CombineAttrs
- [x] ConcatAttrs
- [x]  Conv2DAttrs
- [x] DropoutAttrs
- [x] ElementBinaryAttr
- [x] ElementUnaryAttrs
- [x] EmbeddingAttrs
- [x] FlatAttrs
- [ ] GatherAttrs
- [ ] Group_byAttrs
- [ ] InputAttrs
- [ ] LayerNormAttrs
- [ ] LinearAttrs
- [ ] NoopAttrs
- [ ] Pool2DAttrs
- [ ] ReduceAttrs
- [ ] ReductionAttrs
- [ ] RepartitionAttrs
- [ ] ReplicateAttrs
- [ ] ReshapeAttrs
- [ ] ReverseAttrs 
- [ ] SoftmaxAttrs
- [ ] SplitAttrs
- [ ] TopKAttrs
- [ ] TransposeAttrs

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2023-10-12 23:12 UTC, lockshaw requested changes
Note: I changed my mind during this PR and instead of moving `is_valid` from a method to a function, it should just be deleted altogether--treat any "Function not method" comments as "Delete"

> Reviewed 39 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-:-Nga79-b3HSsD9mWibwW:b-avt8w0)* status: 39 of 55 files reviewed, 52 unresolved discussions (waiting on @lambda7xx)

___
*[`lib/kernels/src/cuda/aggregate_spec_kernels.cu` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0PTkDogn9SWmy4d6:-Nga0PTl4jrkIoqTn9ah:b4zu305) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/kernels/src/cuda/aggregate_spec_kernels.cu#L0)):*
Why was this file modified in this PR?
___
*[`lib/op-attrs/include/op-attrs/ops/attention.h` line 31 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0Yxh9Ys6cNkhS_qo:-Nga0Yxh9Ys6cNkhS_qp:bp0hc35) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/attention.h#L31)):*
> ```objc
> };
> 
> struct MultiHeadAttentionAttrs {
> ```

Why did you move this?
___
*[`lib/op-attrs/include/op-attrs/ops/attention.h` line 35 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0ZvB5hDW3TO-A275:-Nga0ZvB5hDW3TO-A276:b-8zn2gm) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/attention.h#L35)):*
> ```objc
>   req<float> dropout;
>   req<bool> bias, add_bias_kv, add_zero_attn;
>   bool is_valid(MultiHeadAttentionInputs<ParallelTensorShape> const &) const;
> ```

`is_valid` should be a function, not a method
___
*[`lib/op-attrs/include/op-attrs/ops/batch_matmul.h` line 12 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0edD4hFyvuJRpU7D:-Nga0edD4hFyvuJRpU7E:b-7qjsch) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/batch_matmul.h#L12)):*
> ```objc
> struct BatchMatmulAttrs {
>   req<int> a_seq_length_dim, b_seq_length_dim;
>   bool is_valid(ParallelTensorShape const &, ParallelTensorShape const &);
> ```

Function, not method
___
*[`lib/op-attrs/include/op-attrs/ops/batch_norm.h` line 12 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0iFi4ytfARDCgQm9:-Nga0iFi4ytfARDCgQmA:b-7qjsch) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/batch_norm.h#L12)):*
> ```objc
> struct BatchNormAttrs {
>   req<bool> relu;
>   bool is_valid(ParallelTensorShape const &);
> ```

Function, not method
___
*[`lib/op-attrs/include/op-attrs/ops/cast.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0ljkEsMMqA4XNVPZ:-Nga0ljkEsMMqA4XNVP_:bad015d) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/cast.h#L13)):*
> ```objc
> struct CastAttrs {
>   req<DataType> dtype;
>   bool is_valid(ParallelTensorShape const &input) const;
> ```

Function not method
___
*[`lib/op-attrs/include/op-attrs/ops/combine.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0nj08fFP2lqhsMcg:-Nga0nj08fFP2lqhsMch:bad015d) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/combine.h#L14)):*
> ```objc
>   ff_dim_t combine_dim;
>   req<int> combine_degree;
>   bool is_valid(ParallelTensorShape const &) const;
> ```

Function not method
___
*[`lib/op-attrs/include/op-attrs/ops/concat.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0qQsAw_Qs5N9lmVl:-Nga0qQu6pfhzVHqjyoo:bad015d) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/concat.h#L13)):*
> ```objc
> struct ConcatAttrs {
>   ff_dim_t axis;
>   bool is_valid(std::vector<ParallelTensorShape> const &input) const;
> ```

Function not method
___
*[`lib/op-attrs/include/op-attrs/ops/conv_2d.h` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0sLuC_1Oe9tPrYuB:-Nga0sLuC_1Oe9tPrYuC:bad015d) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/conv_2d.h#L17)):*
> ```objc
>   req<optional<Activation>> activation;
>   req<bool> use_bias;
>   bool is_valid(ParallelTensorShape const &input) const;
> ```

Function not method
___
*[`lib/op-attrs/include/op-attrs/ops/dropout.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1JYoARVrbPfMousf:-Nga1JYoARVrbPfMousg:bad015d) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/dropout.h#L13)):*
> ```objc
>   req<float> rate;
>   req<unsigned long long> seed;
>   bool is_valid(ParallelTensorShape const &) const;
> ```

Function not method
___
*[`lib/op-attrs/include/op-attrs/ops/element_binary.h` line 7 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1Mrl14Fjs7Vqvi0b:-Nga1Mrl14Fjs7Vqvi0c:b-eqguqs) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/element_binary.h#L7)):*
> ```objc
> #include "op-attrs/op.h"
> #include "op-attrs/parallel_tensor_shape.h"
> #include "op-attrs/©"
> ```

I don't think this is correct
___
*[`lib/op-attrs/include/op-attrs/ops/element_binary.h` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1LBh8IteQCqf3fyZ:-Nga1LBh8IteQCqf3fy_:bad015d) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/element_binary.h#L17)):*
> ```objc
>   req<bool> should_broadcast_lhs;
>   req<bool> should_broadcast_rhs;
>   bool is_valid(ParallelTensorShape const &lhs,
> ```

Function not method
___
*[`lib/op-attrs/include/op-attrs/ops/element_unary.h` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1UJU3gsv5wX2c6iQ:-Nga1UJU3gsv5wX2c6iR:bad015d) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/element_unary.h#L21)):*
> ```objc
> struct ElementUnaryAttrs {
>   req<Op> op;
>   bool is_valid(ParallelTensorShape const &) const;
> ```

Function not method
___
*[`lib/op-attrs/include/op-attrs/ops/embedding.h` line 22 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1YaR2h7yO61B16-f:-Nga1YaR2h7yO61B16-g:bad015d) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/embedding.h#L22)):*
> ```objc
>   req<AggregateOp> aggr;
>   req<DataType> data_type;
>   bool is_valid(ParallelTensorShape const &input) const;
> ```

Function not method
___
*[`lib/op-attrs/include/op-attrs/ops/gather.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1a8w4Ej2dkbX1dgN:-Nga1a8w4Ej2dkbX1dgO:bad015d) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/gather.h#L13)):*
> ```objc
> struct GatherAttrs {
>   ff_dim_t dim;
>   bool is_valid(ParallelTensorShape const &, ParallelTensorShape const &) const;
> ```

Function not method
___
*[`lib/op-attrs/include/op-attrs/ops/groupby.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1bdf97zXuXS_oqPu:-Nga1bdf97zXuXS_oqPv:bad015d) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/groupby.h#L13)):*
> ```objc
>   req<int> n;
>   req<float> alpha;
>   bool is_valid(ParallelTensorShape const &, ParallelTensorShape const &) const;
> ```

Function not method
___
*[`lib/op-attrs/include/op-attrs/ops/layer_norm.h` line 15 at r1](https://reviewable.io/revi [...]

2023-10-16 20:21 UTC, lambda7xx commented
*[`lib/op-attrs/src/attention.cc` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga2K7pCSkQRi9F7oaP:-Ngu8YTyA-UymWAGcO5q:bla8vo0) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/src/attention.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`is_valid` should assume that all input tensors have already been `is_valid`-checked
</blockquote></details>

you mean we don't need to check if the input_tensor is valid in `is_valid` function.


<!-- Sent from Reviewable.io -->

2023-10-18 20:40 UTC, lambda7xx commented
*[`lib/op-attrs/include/op-attrs/ops/topk.h` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga23cX1i2dBlvJohTS:-Nh3WF2AAGsS2FPirlIQ:b-7gdmng) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/topk.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think this op is removed in #1177 anyway
</blockquote></details>

you mean topk?


<!-- Sent from Reviewable.io -->

2023-10-18 20:43 UTC, lambda7xx commented
*[`lib/op-attrs/src/batch_matmul.cc` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga3Ekg1B4B4XmAL-Ef:-Nh3Wk7aDQ4WOO-ZsuKp:b-9c6lng) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/src/batch_matmul.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

remove what?


<!-- Sent from Reviewable.io -->

2023-10-18 20:43 UTC, lambda7xx commented
*[`lib/op-attrs/src/batch_matmul.cc` line 20 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga3jdMEj6Bz2UfW7B7:-Nh3WmKW5RWJM-L5lWYW:b-fjbmdo) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/src/batch_matmul.cc#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is this actually the case? If so, we should remove `a_seq_length_dim` and `b_seq_length_dim` from the `BatchMatmulAttrs` as the information is already present in the inputs. I'd recommend checking with Zhihao on this one, as I think this may be were `FFIterationConfig::seq_length` is used (but I'm not sure)
</blockquote></details>

I am not sure.


<!-- Sent from Reviewable.io -->

2023-10-18 20:43 UTC, lambda7xx commented
*[`lib/op-attrs/src/batch_matmul.cc` line 33 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga4oUjDPpYxSmVMGKo:-Nh3Ws241J700GRLqwKb:b-tbvk0e) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/src/batch_matmul.cc#L33)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yes, you need to take parallelism into account for all of the operators. For example, for this one you're not doing any checking on the parallelism degrees of the inputs, but that is necessary: if m has parallelism dimension k for example, we need to move k into the reduction dimension
</blockquote></details>

implement one version.


<!-- Sent from Reviewable.io -->

2023-10-18 20:43 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1183)* status: 5 of 55 files reviewed, 52 unresolved discussions (waiting on @lockshaw)

___
*[`lib/op-attrs/include/op-attrs/ops/attention.h` line 35 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0ZvB5hDW3TO-A275:-Nh3UddT1vZAkzENNjkx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/attention.h#L35)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`is_valid` should be a function, not a method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/batch_matmul.h` line 12 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0edD4hFyvuJRpU7D:-Nh3UxffCWkuUU1vFKrn:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/batch_matmul.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function, not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/batch_norm.h` line 12 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0iFi4ytfARDCgQm9:-Nh3UyIz23a_-isqRM5D:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/batch_norm.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function, not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/cast.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0ljkEsMMqA4XNVPZ:-Nh3UyqQ5Zzbu7CQs5iz:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/cast.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/combine.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0nj08fFP2lqhsMcg:-Nh3UzNS0QiWhAX0TEOJ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/combine.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/concat.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0qQsAw_Qs5N9lmVl:-Nh3Uzrh06bGCoFT7PrY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/concat.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/conv_2d.h` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga0sLuC_1Oe9tPrYuB:-Nh3V-O63gUZV0hivMYS:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/conv_2d.h#L17)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/dropout.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1JYoARVrbPfMousf:-Nh3V-vACpZUUoWtZS5N:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/dropout.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/element_binary.h` line 7 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1Mrl14Fjs7Vqvi0b:-Nh3V0R42Lcq71wgObW8:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/element_binary.h#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think this is correct
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/element_binary.h` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1LBh8IteQCqf3fyZ:-Nh3W27QA9dsJwnU2Nkr:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/element_binary.h#L17)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/element_unary.h` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1UJU3gsv5wX2c6iQ:-Nh3W2h70gfedbSGqQVb:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/element_unary.h#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/embedding.h` line 22 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1YaR2h7yO61B16-f:-Nh3W3EUC3oGiHRIeJx-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/embedding.h#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/gather.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1a8w4Ej2dkbX1dgN:-Nh3W3js2ON0BP-6SrCl:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/gather.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/groupby.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1bdf97zXuXS_oqPu:-Nh3W4Al8ZFplvt7a6Ip:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/groupby.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/layer_norm.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1dRa9fS5UmTZ5QHD:-Nh3W4szAbXMT60tqxdV:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/layer_norm.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/linear.h` line 32 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1jg-AuuGmYKRGkuv:-Nh3W5PdEpAC4-JUt9-C:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/linear.h#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Function not method
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/pool_2d.h` line 20 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga1l0C1PzjeWGBqni-:-Nh3W5vS4P6HLC2nlCkl:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/include/op-attrs/ops/pool_2d.h#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summar [...]

2023-10-18 20:58 UTC, lambda7xx commented
*[`lib/op-attrs/src/concat.cc` line 20 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga6E3w5R2CgcxjD20_:-Nh3_3a2472oFFGQzHkd:b1mragv) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/src/concat.cc#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use `sum` from `containers.h`
</blockquote></details>

it seems we can't  directly use `sum` because we need `i.at(attrs.axis).size`


<!-- Sent from Reviewable.io -->

2023-10-18 21:01 UTC, lambda7xx commented
*[`lib/op-attrs/src/element_binary.cc` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga8Ke93qIC4ukL92qQ:-Nh3_rZW1fHAxsO6OSj9:b-xhlsbp) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/src/element_binary.cc#L16)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

we use this `compare` to decide `output` should be `lhs` or `rhs`. so we can use max
</blockquote></details>

we can't use max


<!-- Sent from Reviewable.io -->

2023-10-18 21:02 UTC, lambda7xx commented
*[`lib/op-attrs/src/element_binary.cc` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga8U8n0_SseR55w4a_:-Nh3_tzaCnos88_n6a8N:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/src/element_binary.cc#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

How is parallelism handled here? If you're only handling non-parallel cases, (1) you probably should handle them, and (2) if you don't you should at least check each dimension of each tensor and through a `mk_runtime_error` if any of them have `degree > 1`
</blockquote></details>

Done.



_Code snippet:_
```cpp
i think heare the output degree is same as input degree. 
```


<!-- Sent from Reviewable.io -->

2023-10-18 21:02 UTC, lambda7xx commented
*[`lib/op-attrs/src/element_binary.cc` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga8U8n0_SseR55w4a_:-Nh3a97j4qqm34aMDApA:b-o1mac4) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/src/element_binary.cc#L21)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think here the output degree is same as input degree.


<!-- Sent from Reviewable.io -->

2023-10-18 21:03 UTC, lambda7xx commented
*[`lib/op-attrs/src/embedding.cc` line 20 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga9CZs9blpMhpPNhub:-Nh3aXvC5-XIL1dm9gIp:bxkpemq) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/src/embedding.cc#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What about any parallelism handling here?
</blockquote></details>

output degree is same as input degree


<!-- Sent from Reviewable.io -->

2023-10-18 21:04 UTC, lambda7xx commented
*[`lib/op-attrs/src/flat.cc` line 28 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-Nga9Kfi4NG3xxftR5NW:-Nh3agmt8LgJJ11QzNCI:bxyu5mb) ([raw file](https://github.com/flexflow/FlexFlow/blob/b56d9c0c49a4daaafb0be09f7329ea56a7082a2f/lib/op-attrs/src/flat.cc#L28)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Do you need to check that all of the rest of the channels have degree 1?
</blockquote></details>

flat operator return a one dimension tensor. how to decide its degree.


<!-- Sent from Reviewable.io -->

2023-11-26 17:21 UTC, wmdi requested changes
> Reviewed 19 of 48 files at r3, 30 of 39 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1183)* status: 50 of 59 files reviewed, 55 unresolved discussions (waiting on @jiazhihao, @lambda7xx, and @lockshaw)

___
*[`lib/op-attrs/src/replicate.cc` line 24 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-NkBbwPS7BGtorJRyFIj:-NkBbwPT9-_3mTbmi45X:b-pnyz8p) ([raw file](https://github.com/flexflow/FlexFlow/blob/fec4928ea094b327724b0ac7b2ace4f9450cd704/lib/op-attrs/src/replicate.cc#L24)):*
> ```cpp
>   ParallelTensorShape output = input;
>   output.at(ff_dim_t(0)).is_replica_dim = true;
>   output.at(ff_dim_t(0)).size *= attrs.replicate_degree;
> ```

I think you also have to update the degree
___
*[`lib/op-attrs/src/reshape.cc` line 43 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-NkBce8CDrAL9NBk5LpE:-NkBce8CDrAL9NBk5LpF:b-uk63id) ([raw file](https://github.com/flexflow/FlexFlow/blob/fec4928ea094b327724b0ac7b2ace4f9450cd704/lib/op-attrs/src/reshape.cc#L43)):*
> ```cpp
>       data[1].size = attrs.shape.at(ff_dim_t(0));
>       data[2].size = input_volume / attrs.shape.at(ff_dim_t(0));
>       for (int i = 1; i < 3; i++) {
> ```

I am a little confused of this piece of codes. What does 3 standard for?
___
*[`lib/op-attrs/src/split.cc` line 30 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-NkBdRpk3_ng9mkhm5CQ:-NkBdRpk3_ng9mkhm5CR:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/fec4928ea094b327724b0ac7b2ace4f9450cd704/lib/op-attrs/src/split.cc#L30)):*
> ```cpp
> 
> std::vector<ParallelTensorShape>
>     get_output_shape(SplitAttrs const &attrs,
> ```

Why?


<!-- Sent from Reviewable.io -->

2023-12-03 01:26 UTC, lambda7xx commented
*[`lib/op-attrs/src/reshape.cc` line 43 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-NkBce8CDrAL9NBk5LpE:-NkhG8uAAypv8b-LL8dt:b45h) ([raw file](https://github.com/flexflow/FlexFlow/blob/fec4928ea094b327724b0ac7b2ace4f9450cd704/lib/op-attrs/src/reshape.cc#L43)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I am a little confused of this piece of codes. What does 3 standard for?
</blockquote></details>





_Code snippet:_
```cpp
if the `attrs.shape.dims.num_dims() == 1` and `attrs.shape.at(ff_dim_t(0)) != -1` , i think it will be a tensor with 2 dimensison. And its ParallelTensorShape will be 3 dimension. 0-dimension represents the replicate num, the 1-dimention will be the attrs.shape.at(ff_dim_t(0)), and we know its input_volume,
ffor example, the pytorch tensor x = torch.randn((3,4)), its input_volume its 12, and the attrs.shape.at(ff_dim_t(0)) =2, so the new tensor will be the (2,6)
```


<!-- Sent from Reviewable.io -->

2023-12-03 01:27 UTC, lambda7xx commented
*[`lib/op-attrs/src/replicate.cc` line 24 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1183#-NkBbwPS7BGtorJRyFIj:-NkhHHfG0n4-xNbTZTkO:b-6g5eqa) ([raw file](https://github.com/flexflow/FlexFlow/blob/fec4928ea094b327724b0ac7b2ace4f9450cd704/lib/op-attrs/src/replicate.cc#L24)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I think you also have to update the degree
</blockquote></details>

yeah, you are right. because it's replicate operator, so the degree of output is same as input.


<!-- Sent from Reviewable.io -->

2024-01-25 07:33 UTC, lockshaw commented
FYI @lambda7xx: @wmdi will be handling finishing off and merging this PR to free you up to start to work on more runtime-related things





<!-- Sent from Reviewable.io -->

2024-05-30 21:36 UTC, lockshaw commented
Superseded by #1394.

2024-05-30 21:36 UTC, closed without merging