Substitutions build
flexflow/FlexFlow pull request #1189
Opened 2023-10-12 01:22 UTC by wmdi

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2023-10-12 22:16 UTC, lockshaw requested changes
> Reviewed 76 of 76 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 55 unresolved discussions (waiting on @wmdi)

___
*[`deps/fmt` line 1 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_lDuKD9mt9EOuWmR3:-Ng_lDuM63yXw9xg5NM-:blookbn) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/deps/fmt#L1)):*
> ```
> Subproject commit a33701196adfad74917046096bf5a2aa0ab0bb50
> ```

This change should be removed (everything should be using the `f5e5` commit as it's newer and has features we rely on)
___
*[`lib/substitutions/include/substitutions/attribute_expr.h` line 34 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_lo8D9Itr1IicRdF_:-Ng_lo8E6N_Mv2QGqhPr:b63ze3v) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/include/substitutions/attribute_expr.h#L34)):*
> ```objc
> struct AttributePattern {
>   std::vector<AttributeConstraint<K, V>> attribute_constraints;
>   // TODO: Revert to unordered_set once we have visitable for templates
> ```

Why is this necessary? Also, can you create an issue for this and link to it on the req-fix PR (otherwise it'll just get lost/forgotten) 
___
*[`lib/substitutions/include/substitutions/operator_pattern.h` line 70 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_m0n8ANyRBrMsxYPt:-Ng_m0n93-USaLBOPJtF:b-fyi3mm) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/include/substitutions/operator_pattern.h#L70)):*
> ```objc
>   COMBINE_DIM,
>   COMBINE_DEGREE,
>   NUM_INPUTS
> ```

Why is this necessary? `OperatorAttributeKey`s are for node-local properties (i.e., things on `op-attrs`) but the number of inputs is a graph-level property
___
*[`lib/substitutions/src/graph_pattern.cc` line 237 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_mPit5deehC6Q5RBc:-Ng_mPit5deehC6Q5RBd:ba5ok4b) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern.cc#L237)):*
> ```cpp
>     auto pcgEdge = kv.second;
>     optional<bool> constraintResult =
>         satisfies(at(pcg, pcgEdge), at(pattern.value(), patternEdge));
> ```

What is this `at` function, as opposed to the `at` method on `pattern`? (and same for the other `at` call here)
___
*[`lib/substitutions/src/graph_pattern_match.cc` line 20 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_md4MBMhFeRNnswpT:-Ng_md4MBMhFeRNnswpU:bbff0rc) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern_match.cc#L20)):*
> ```cpp
> std::pair<OpenMultiDiGraphView, OpenMultiDiGraphView>
>     apply_split(OpenMultiDiGraphView const &pattern, GraphSplit const &split) {
>   return {get_subgraph<OpenMultiDiSubgraphView>(pattern, split.first),
> ```

Why is a template parameter necessary here? Shouldn't this be inferable from the input graph type, as there generally should only be one subgraph view for each graph type?
___
*[`lib/substitutions/src/substitution.cc` line 135 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_n7g-6bZtLQSV-c8J:-Ng_n7g-6bZtLQSV-c8K:b-giit2) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/substitution.cc#L135)):*
> ```cpp
>     case Op::CONCAT:
>       return Operator(ConcatAttrs{get<ff_dim_t>(
>                           assignments.at(OperatorAttributeKey::AXIS)), get<int>(assignments.at(OperatorAttributeKey::NUM_INPUTS))},
> ```

I don't think `ConcatAttrs` should have a `num_inputs` field
___
*[`lib/substitutions/src/substitution.cc` line 399 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_nI1E5pcJinRy9Dw5:-Ng_nI1E5pcJinRy9Dw6:bqnjom8) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/substitution.cc#L399)):*
> ```cpp
> };
> 
>   SubParallelComputationGraph
> ```

Why was this all indented? Also, I think you forgot to run the formatting script
___
*[`lib/utils/include/utils/graph/adjacency_multidigraph.h` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_nkwz6wAgPOViDTM5:-Ng_nkwz6wAgPOViDTM6:b-n1b2iu) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/adjacency_multidigraph.h#L25)):*
> ```objc
>   std::unordered_set<Edge> query_edges(EdgeQuery const &) const override;
>   std::unordered_set<Node> query_nodes(NodeQuery const &) const override;
>   // std::unordered_set<DirectedEdge> query_edges(DirectedEdgeQuery const &q)
> ```

Remove instead of commenting out?
___
*[`lib/utils/include/utils/graph/adjacency_openmultidigraph.h` line 9 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_nwWIEdLOsd2ucMcV:-Ng_nwWIEdLOsd2ucMcW:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/adjacency_openmultidigraph.h#L9)):*
> ```objc
> namespace FlexFlow {
> 
> class AdjacencyInputs {
> ```





_Suggestion:_
```objc
AdjacencyInputEdges
```
___
*[`lib/utils/include/utils/graph/adjacency_openmultidigraph.h` line 23 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_nuOm1dbYxjLSx2Yq:-Ng_nuOm1dbYxjLSx2Yr:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/adjacency_openmultidigraph.h#L23)):*
> ```objc
> };
> 
> class AdjacencyOutputs {
> ```





_Suggestion:_
```objc
AdjacencyOutputEdges
```
___
*[`lib/utils/include/utils/graph/digraph.h` line 19 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_oHKN9CwJ5eaEIcpS:-Ng_oHKN9CwJ5eaEIcpT:b-n1b2iu) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph.h#L19)):*
> ```objc
>   using EdgeQuery = DirectedEdgeQuery;
> 
>   // DiGraphView() = delete;
> ```

Remove instead of commenting out?
___
*[`lib/utils/include/utils/graph/digraph.h` line 35 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_oJ8e9QwfikQoynNn:-Ng_oJ8e9QwfikQoynNo:b-n1b2iu) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph.h#L35)):*
> ```objc
> 
> protected:
>   // DiGraphView(cow_ptr_t<IDiGraphView> ptr);
> ```

Remove instead of commenting out?
___
*[`lib/utils/include/utils/graph/digraph.h` line 50 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pEbr-pGMyryDQO1y:-Ng_pEbr-pGMyryDQO1z:b-n1b2iu) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph.h#L50)):*
> ```objc
>   using EdgeQuery = DirectedEdgeQuery;
> 
>   // DiGraph() = delete;
> ```

Remove instead of commenting out?
___
*[`lib/utils/include/utils/graph/digraph.h` line 72 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pLnKEnZMXUxuZScW:-Ng_pLnKEnZMXUxuZScX:b-n1b2iu) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph.h#L72)):*
> ```objc
> 
> protected:
>   // DiGraph(cow_ptr_t<IDiGraph>);
> ```

Remove instead of commenting out?
___
*[`lib/utils/include/utils/graph/digraph_interfaces.h` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pTdD-fuphlUtDXem:-Ng_pTdD-fuphlUtDXen:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph_interfaces.h#L25)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(IDiGraphView);
> 
> struct IDiGraph : virtual public IDiGraphView {
> ```





_Suggestion:_
```objc
struct IDiGraph : virtual public IDiGraphView [...]

2023-10-13 19:34 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 55 unresolved discussions (waiting on @lockshaw)

___
*[`lib/substitutions/include/substitutions/attribute_expr.h` line 34 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_lo8D9Itr1IicRdF_:-NgeTTi46yPPeAg_wXhK:b-h8e8vj) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/include/substitutions/attribute_expr.h#L34)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is this necessary? Also, can you create an issue for this and link to it on the req-fix PR (otherwise it'll just get lost/forgotten)
</blockquote></details>

Using vectors also work. Using sets just makes more sense. Will do.
___
*[`lib/substitutions/include/substitutions/operator_pattern.h` line 70 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_m0n8ANyRBrMsxYPt:-NgeTpA50Kne-s_E0IIY:b-w7hm4k) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/include/substitutions/operator_pattern.h#L70)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is this necessary? `OperatorAttributeKey`s are for node-local properties (i.e., things on `op-attrs`) but the number of inputs is a graph-level property
</blockquote></details>

`ConcatAttrs` has a field named `num_inputs`, so I just created a corresponding one.
___
*[`lib/substitutions/src/graph_pattern.cc` line 237 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_mPit5deehC6Q5RBc:-NgeU7DU9N-CDwjFVDhs:b-rj94sy) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern.cc#L237)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is this `at` function, as opposed to the `at` method on `pattern`? (and same for the other `at` call here)
</blockquote></details>

For `OutputLabelledOpenMultiDiGraph`, we have `at(InputMultiDiEdge)` and `at(MultiDiOutput)`, but we cannot directly call `at(OpenMultiDiEdge)`, which is why `at(OutputLabelledOpenMultiDiGraph, OpenMultiDiEdge)` is here.
___
*[`lib/substitutions/src/graph_pattern_match.cc` line 20 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_md4MBMhFeRNnswpT:-NgeUhBi9vku1okXwltS:b-pf5806) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern_match.cc#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is a template parameter necessary here? Shouldn't this be inferable from the input graph type, as there generally should only be one subgraph view for each graph type?
</blockquote></details>

Because we have four semantics of subgraphs for an open graph, depending on whether we want to include the input/output edges.
___
*[`lib/substitutions/src/substitution.cc` line 135 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_n7g-6bZtLQSV-c8J:-NgeUx_CBvnYnEkq8Kmf:b-8u49zi) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/substitution.cc#L135)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think `ConcatAttrs` should have a `num_inputs` field
</blockquote></details>

I think it should be fixed in the op PR, and I will make the corresponding fix to substitutions after that is merges. In this way we can ensure that substitutions build at each time.
___
*[`lib/utils/include/utils/graph/digraph_interfaces.h` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pTdD-fuphlUtDXem:-NgeVkBG2BZTDelB9qlf:bkbrdry) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph_interfaces.h#L25)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(IDiGraphView);
> 
> struct IDiGraph : virtual public IDiGraphView {
> ```

Currently the graph library works, so I will do graph improvements after functioning substitutions and compiler. 
___
*[`lib/utils/include/utils/graph/internal.h` line 16 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pa_uEnF0-ag0Xxhr:-NgeVzcoBAK7v8vJVsvq:bdrh2hi) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/internal.h#L16)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was all of this commented out?
</blockquote></details>

I plan to remove this, because with virtual inheritance, we don't need them any more.
___
*[`lib/utils/include/utils/graph/multidiedge.h` line 92 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pnrmBUeMbvyEZQbz:-NgeWHeO4okG59EVQn5_:bvkpfve) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/multidiedge.h#L92)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not just use `FF_VISIT_FMTABLE`?
</blockquote></details>

I think these are some old codes... I will check it.
___
*[`lib/utils/include/utils/graph/multidigraph.h` line 39 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_puW00V7Ij2liKKIA:-NgeWWNx08G5QJbY0-RP:bld4gg2) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/multidigraph.h#L39)):*
> ```objc
> CHECK_WELL_BEHAVED_VALUE_TYPE_NO_EQ(MultiDiGraphView);
> 
> struct MultiDiGraph : virtual MultiDiGraphView {
> ```

I will do all the graph improvements after functioning substitutions and compiler, as long as the graph library still works.
___
*[`lib/utils/include/utils/graph/multidigraph_interfaces.h` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_qBCF9dcEDCssbxBY:-NgeWg9W0U0vuXpeT1Dl:bld4gg2) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/multidigraph_interfaces.h#L25)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(IMultiDiGraphView);
> 
> struct IMultiDiGraph : virtual public IMultiDiGraphView {
> ```

I will do all the graph improvements after functioning substitutions and compiler, as long as the graph library still works.
___
*[`lib/utils/include/utils/graph/open_edge.h` line 38 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_qhC2AMExMt5KMP6d:-NgeWjofEzA0aY23uF4B:b-sl5klt) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_edge.h#L38)):*
> ```objc
>                                              output_edge_query);
> 
> struct DownwardOpenMultiDiEdgeQuery {
> ```

I haven't thought carefully whether this would cause any issues... Again, will do it after substitutions and compiler work.


<!-- Sent from Reviewable.io -->

2023-10-17 19:38 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 55 unresolved discussions (waiting on @lockshaw)

___
*[`lib/substitutions/src/substitution.cc` line 399 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_nI1E5pcJinRy9Dw5:-Ngu_xHo2J5PNSPO3qb-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/substitution.cc#L399)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was this all indented? Also, I think you forgot to run the formatting script
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/adjacency_multidigraph.h` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_nkwz6wAgPOViDTM5:-Ngua5Ce1cQE1Mv33Q_r:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/adjacency_multidigraph.h#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove instead of commenting out?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/adjacency_openmultidigraph.h` line 9 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_nwWIEdLOsd2ucMcV:-NguaFpa-8OCp3OywhE8:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/adjacency_openmultidigraph.h#L9)):*
> ```objc
> namespace FlexFlow {
> 
> class AdjacencyInputs {
> ```

Done.
___
*[`lib/utils/include/utils/graph/adjacency_openmultidigraph.h` line 23 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_nuOm1dbYxjLSx2Yq:-NguaG7a5hO_ERdC_sn9:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/adjacency_openmultidigraph.h#L23)):*
> ```objc
> };
> 
> class AdjacencyOutputs {
> ```

Done.
___
*[`lib/utils/include/utils/graph/digraph.h` line 19 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_oHKN9CwJ5eaEIcpS:-NguaTkC8fnNOXgao8Kk:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph.h#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove instead of commenting out?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/digraph.h` line 35 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_oJ8e9QwfikQoynNn:-NguaUBq9F7RFsmxiDsI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph.h#L35)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove instead of commenting out?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/digraph.h` line 50 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pEbr-pGMyryDQO1y:-NguaXgbDyOUuDQcF1sC:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph.h#L50)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove instead of commenting out?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/digraph.h` line 72 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pLnKEnZMXUxuZScW:-NguaY8SEWDPuC3mfrH_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph.h#L72)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove instead of commenting out?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/node.h` line 82 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_qLTL5gxGu6EBpbcf:-Ngz2ehh24t1lxG7h6df:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/node.h#L82)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete instead of commenting out?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 19 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_s2Bc2OdFQtOxuWBT:-NgubX4O87YJB42Q55M5:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete instead of commenting?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 81 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_sDxUCO1w3cAmZHeo:-NgubXb8DBRvQ6TQBNJM:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L81)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete instead of commenting?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 144 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_sP497OzHolIqdWrE:-Ngub_jQ2HfqNEQs4-nY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L144)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete instead of commenting?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/views.h` line 277 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_tTbtA9nYqhfOd5F5:-NgubiOn2i2rE57qUS8H:b-3mv416) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/views.h#L277)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are all these new subgraph classes necessary?
</blockquote></details>

Basically, I want to refactor `get_subgraph` for labelled open graphs, because it can be decoupled as `get_subgraph` for open graphs and restriction on labels.
___
*[`lib/utils/include/utils/graph/labelled/label_interfaces.h` line 9 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_tcVhCuxy_SFVk4Ea:-NgymoXY0XUTwqvO7KZp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/labelled/label_interfaces.h#L9)):*
> ```objc
> 
> template <typename Elem, typename Label>
> struct ILabel {
> ```

Done.
___
*[`lib/utils/include/utils/graph/labelled/node_labelled.h` line 27 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_tidk0IDFZShuVnuC:-Ngz2iUGCW3TrXdBeq3d:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/labelled/node_labelled.h#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete instead of commenting?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/labelled/output_labelled.h` line 28 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_tuOv99PgrKtJB64j:-Ngz2nbk-mx_ydvsaqXL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/labelled/output_labelled.h#L28)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete instead of commenting?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/labelled/output_labelled.h` line 65 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_uACa0xegMs-7CGOy:-Ngz2nsT9TrRKCVKvq2B:bps5tz) ([raw file](https://github.com/flexflow/Fl [...]

2023-10-19 00:51 UTC, lockshaw requested changes
> Reviewed 29 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 21 unresolved discussions (waiting on @wmdi)

___
*[`lib/substitutions/src/graph_pattern.cc` line 237 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_mPit5deehC6Q5RBc:-Nh4NrECB8VHC8DHMRG5:b-hxdakf) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern.cc#L237)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

For `OutputLabelledOpenMultiDiGraph`, we have `at(InputMultiDiEdge)` and `at(MultiDiOutput)`, but we cannot directly call `at(OpenMultiDiEdge)`, which is why `at(OutputLabelledOpenMultiDiGraph, OpenMultiDiEdge)` is here.
</blockquote></details>

In that case this should probably be done as a variant `get`? Where is the guarantee here that the `OpenMultiDiEdge` is in fact an input edge and not some other edge?
___
*[`lib/substitutions/src/graph_pattern_match.cc` line 20 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_md4MBMhFeRNnswpT:-Nh4OSBnCPOArZznowIV:b-g82ec4) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern_match.cc#L20)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Because we have four semantics of subgraphs for an open graph, depending on whether we want to include the input/output edges.
</blockquote></details>

Why not always include them, since `OpenMultiDiGraphView` coerces to `MultiDiGraphView` by dropping the open edges anyway? I think removing the input/output edges should be a separate function/thing, not part of subgraph retrieval
___
*[`lib/substitutions/src/substitution.cc` line 135 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_n7g-6bZtLQSV-c8J:-Nh4NJ0e6Td4wXH1BXEp:b-p72vek) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/substitution.cc#L135)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I think it should be fixed in the op PR, and I will make the corresponding fix to substitutions after that is merges. In this way we can ensure that substitutions build at each time.
</blockquote></details>

Makes sense. Can you create an issue (or comment on the corresponding PR if it's still open)? 
___
*[`lib/utils/include/utils/graph/digraph_interfaces.h` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pTdD-fuphlUtDXem:-Nh4P-yE1P0jON_WGl-j:b-wkqbpl) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph_interfaces.h#L25)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Currently the graph library works, so I will do graph improvements after functioning substitutions and compiler.
</blockquote></details>

Makes sense. Can you create an issue to track the additional changes we want to make and note the changes from the comments on this PR so they don't get lost? 
___
*[`lib/utils/include/utils/graph/views.h` line 277 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_tTbtA9nYqhfOd5F5:-Nh4PY2YEZtH7Z0V7UBs:b-nm60p0) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/views.h#L277)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Basically, I want to refactor `get_subgraph` for labelled open graphs, because it can be decoupled as `get_subgraph` for open graphs and restriction on labels.
</blockquote></details>

Sounds good. Might be worth thinking if we can template out some of this repeated code, but for now this makes sense
___
*[`lib/utils/include/utils/graph/labelled/output_labelled.h` line 65 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_uACa0xegMs-7CGOy:-Nh4LSoL08Kz5mJH3M7k:b-e27pbn) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/labelled/output_labelled.h#L65)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Downward casting requires a dynamic cast. We are using the standard `dynamic_point_cast` which only takes standard pointers as arguments. I think we can fix it when we have pointer casts for `cow_ptr_t`
</blockquote></details>

`dynamic_cast` though does runtime checks, which are unnecessary here because we are certain that the type is always correct (unless those additional checks are intentional). If static_cast doesn't work, then probably reinterpret_cast?
___
*[`lib/utils/src/graph/algorithms.cc` line 256 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_vaHv4BdED2ptm55F:-Nh4M1Nt6xyhwbCfDzgA:b-fzh3g2) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/src/graph/algorithms.cc#L256)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Doesn't seem to work.
</blockquote></details>

Got it. In that case it would probably be more clear if written as 



_Suggestion:_
```cpp
  return transform(get_edges(g), [&](MultiDiEdge const &e) {
    return static_cast<MultiDiInput>(e);
  });
```
___
*[`lib/utils/src/graph/diedge.cc` line 33 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Nh4M_jA0DbGfUfMEWh8:-Nh4M_jA0DbGfUfMEWh9:bcltkhg) ([raw file](https://github.com/flexflow/FlexFlow/blob/e31a41dfc98e16458e82e17758a7dca320415881/lib/utils/src/graph/diedge.cc#L33)):*
> ```cpp
>   }
> 
>   return {result_srcs, result_srcs};
> ```

`result_dsts`?
___
*[`lib/utils/test/src/test_algorithms.cc` line 20 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Nh4Ms5nCfm8PLzk8V4f:-Nh4Ms5nCfm8PLzk8V4g:bcgjvre) ([raw file](https://github.com/flexflow/FlexFlow/blob/e31a41dfc98e16458e82e17758a7dca320415881/lib/utils/test/src/test_algorithms.cc#L20)):*
> ```cpp
>   std::vector<NodePort> p = add_node_ports(g, 4);
> 
>   MultiDiEdge e0{n[3], p[3], n[0], p[0]};
> ```

Why this change?


<!-- Sent from Reviewable.io -->

2023-10-19 01:37 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 21 unresolved discussions (waiting on @lockshaw)

___
*[`lib/substitutions/src/graph_pattern.cc` line 237 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_mPit5deehC6Q5RBc:-Nh4QFY77MzNyV0k9-xL:bneimfj) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern.cc#L237)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In that case this should probably be done as a variant `get`? Where is the guarantee here that the `OpenMultiDiEdge` is in fact an input edge and not some other edge?
</blockquote></details>

It should be an `at`. I mean, we have three types of edges, `InputMultiDiEdge`, `MultiDiEdge` and `OutputMultiDiEdge`, among which the labels of `MultiDiEdge` and `OutputMultiDiEdge` can be obtained from `OutputLabelledOpenMultiDiGraph::at(MultiDiOutput)` while those of `InputMultiDiEdge` cannot and thus have to be obtained from `OutputLabelledOpenMultiDiGraph::at(InputMultiDiEdge)`.

Then we cannot add another function called `OutputLabelledOpenMultiDiGraph::at(OpenMultiDiEdge)` because it will cause ambiguity when we  call `g.at(e)` where `e` is one of `InputMultiDiEdge`, `MultiDiEdge` or `OutputMultiDiEdge`. Therefore, I implement an `at` outside `OutputLabelledOpenMultiDiGraph` scope to handle this type of reference.
___
*[`lib/utils/include/utils/graph/digraph_interfaces.h` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pTdD-fuphlUtDXem:-Nh4XfpJCDvIbgmRLdcy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph_interfaces.h#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Makes sense. Can you create an issue to track the additional changes we want to make and note the changes from the comments on this PR so they don't get lost?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/graph/open_graph_interfaces.h` line 15 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_qx750yLopAQOmIFU:-Nh4XgJVC6N59NgWvqXN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graph_interfaces.h#L15)):*
> ```objc
> namespace FlexFlow {
> 
> struct IOpenMultiDiGraphView : virtual public IMultiDiGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/open_graph_interfaces.h` line 48 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_rOYS0vYdwuOqxjD2:-Nh4Xg_82o1Mg3kTZuAI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graph_interfaces.h#L48)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(IUpwardOpenMultiDiGraphView);
> 
> struct IOpenMultiDiGraph : virtual public IOpenMultiDiGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/open_graph_interfaces.h` line 59 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_rchBDOySVat2ix0i:-Nh4XgySA5mhn_iq3iCE:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graph_interfaces.h#L59)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(IOpenMultiDiGraph);
> 
> struct IUpwardOpenMultiDiGraph : virtual public IUpwardOpenMultiDiGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/open_graph_interfaces.h` line 70 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_rk7lBDYL3KFKHWNm:-Nh4XhSrB1xScUHEXY9u:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graph_interfaces.h#L70)):*
> ```objc
> 
> struct IDownwardOpenMultiDiGraph
>     : virtual public IDownwardOpenMultiDiGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 14 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_rsyG4RkHAhJnoUFU:-Nh4Xi3n7u5DdelBN0Xq:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L14)):*
> ```objc
> namespace FlexFlow {
> 
> struct OpenMultiDiGraphView : virtual MultiDiGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 43 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_s7wzC7lv-jGPj2xe:-Nh4XiW8BkTHpmPFIomj:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L43)):*
> ```objc
> };
> 
> struct OpenMultiDiGraph : virtual OpenMultiDiGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 105 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_sI5q7uRODT6hVj_D:-Nh4Xisp3AEx3HSjcloE:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L105)):*
> ```objc
> CHECK_WELL_BEHAVED_VALUE_TYPE_NO_EQ(UpwardOpenMultiDiGraphView);
> 
> struct UpwardOpenMultiDiGraph : virtual UpwardOpenMultiDiGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 168 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_sV_85vOkoNDiqzTl:-Nh4XjFG-_FBc-gqN4ih:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L168)):*
> ```objc
> CHECK_WELL_BEHAVED_VALUE_TYPE_NO_EQ(DownwardOpenMultiDiGraphView);
> 
> struct DownwardOpenMultiDiGraph : virtual DownwardOpenMultiDiGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/undirected.h` line 62 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_sm1D0e_jVRRcqw_2:-Nh4Xjej-dcWrMCs1waE:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/undirected.h#L62)):*
> ```objc
> CHECK_WELL_BEHAVED_VALUE_TYPE_NO_EQ(UndirectedGraphView);
> 
> struct IUndirectedGraph : public IUndirectedGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/undirected.h` line 75 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_sthhC7mu65x-Y4p_:-Nh4Xk0wE0C-wP8cCYc7:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/undirected.h#L75)):*
> ```objc
> };
> 
> struct UndirectedGraph : virtual UndirectedGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/views.h` line 263 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_tItNELKGXLb6h6VD:-Nh4XkY-BERpok9RUgoQ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/views.h#L263)):*
> ```objc
> };
> 
> struct UpwardOpenMultiDiSubgraphView : public IOpenMultiDiGraphView {
> ```

Done.
___
*[`lib/utils/include/utils/graph/views.h` line 277 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_tTbtA9nYqhfOd5F5:-Nh4YQXcAH2JimW4NDqs:b-1v44aw) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/views.h#L277)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Sounds good. Might be worth thinking if we can template out some of this repeated code, but for now this makes sense
</blockquote></details>

I have tracked it in the graph improvement issue.
___
*[`lib/utils/src/graph/digraph.cc` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_weJ5CodutQLxMGoW:-Nh4ZnNgApnE7_9Up9-E:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/src/graph/digraph.cc#L25)):*
<details><summary><i>Previously, l [...]

2023-10-23 18:29 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: 55 of 82 files reviewed, 21 unresolved discussions (waiting on @lockshaw)

___
*[`lib/substitutions/src/graph_pattern_match.cc` line 20 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_md4MBMhFeRNnswpT:-Nh4bh8I17e0sl3FhYMC:b-1v44aw) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern_match.cc#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not always include them, since `OpenMultiDiGraphView` coerces to `MultiDiGraphView` by dropping the open edges anyway? I think removing the input/output edges should be a separate function/thing, not part of subgraph retrieval
</blockquote></details>

I have tracked it in the graph improvement issue.
___
*[`lib/utils/include/utils/graph/labelled/output_labelled.h` line 65 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_uACa0xegMs-7CGOy:-NhSn6eB6iq6KtgIbSZC:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/labelled/output_labelled.h#L65)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`dynamic_cast` though does runtime checks, which are unnecessary here because we are certain that the type is always correct (unless those additional checks are intentional). If static_cast doesn't work, then probably reinterpret_cast?
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/diedge.cc` line 33 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Nh4M_jA0DbGfUfMEWh8:-NhSnC9p82VlhHYduxBr:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e31a41dfc98e16458e82e17758a7dca320415881/lib/utils/src/graph/diedge.cc#L33)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`result_dsts`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-05 19:59 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: 42 of 106 files reviewed, 21 unresolved discussions (waiting on @lockshaw)

___
*[`lib/substitutions/src/substitution.cc` line 135 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_n7g-6bZtLQSV-c8J:-NiW2oYU83n9llnsLdbE:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/substitution.cc#L135)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Makes sense. Can you create an issue (or comment on the corresponding PR if it's still open)?
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/algorithms.cc` line 256 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_vaHv4BdED2ptm55F:-NiW3J0bEOKTXvfAv6WW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/src/graph/algorithms.cc#L256)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Got it. In that case it would probably be more clear if written as
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-05 19:59 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: 42 of 106 files reviewed, 21 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`deps/fmt` line 1 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_lDuKD9mt9EOuWmR3:-NiW3LoY-8CGvyXms73h:b-uo8e6w) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/deps/fmt#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This change should be removed (everything should be using the `f5e5` commit as it's newer and has features we rely on)
</blockquote></details>

Should I make any change?


<!-- Sent from Reviewable.io -->

2023-11-05 20:01 UTC, wmdi reviewed
This pr makes `substitutions` function.

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-:-NiW3VAe5uKz4naH2jtK:bqutsdg)* status: 42 of 106 files reviewed, 21 unresolved discussions (waiting on @lockshaw and @wmdi)



<!-- Sent from Reviewable.io -->

2023-11-08 21:00 UTC, wmdi reviewed
> Reviewed 35 of 76 files at r3, 7 of 29 files at r4, 9 of 27 files at r5, 55 of 55 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 21 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2023-12-29 22:17 UTC, lockshaw requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 7 unresolved discussions (waiting on @wmdi)

___
*[`deps/fmt` line 1 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_lDuKD9mt9EOuWmR3:-NiaNb6_A6VXHVPzP-wm:bc5osg4) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/deps/fmt#L1)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Should I make any change?
</blockquote></details>

Move it to `f5e5`?
___
*[`lib/substitutions/src/graph_pattern.cc` line 237 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_mPit5deehC6Q5RBc:-NmrTI7-EQfqYnP0Tn-X:bcom1ka) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern.cc#L237)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

It should be an `at`. I mean, we have three types of edges, `InputMultiDiEdge`, `MultiDiEdge` and `OutputMultiDiEdge`, among which the labels of `MultiDiEdge` and `OutputMultiDiEdge` can be obtained from `OutputLabelledOpenMultiDiGraph::at(MultiDiOutput)` while those of `InputMultiDiEdge` cannot and thus have to be obtained from `OutputLabelledOpenMultiDiGraph::at(InputMultiDiEdge)`.

Then we cannot add another function called `OutputLabelledOpenMultiDiGraph::at(OpenMultiDiEdge)` because it will cause ambiguity when we  call `g.at(e)` where `e` is one of `InputMultiDiEdge`, `MultiDiEdge` or `OutputMultiDiEdge`. Therefore, I implement an `at` outside `OutputLabelledOpenMultiDiGraph` scope to handle this type of reference.
</blockquote></details>

I guess my confusion is what an `OutputLabelledOpenMultiDiGraphView` should conceptually do--I would expect `InputMultiDiEdge`s in an `OutputLabelledOpenMultiDiGraphView` to not be labelled, but it seems that's not the case. Thinking briefly it seems like the best solution here would be to add an `::at(variant<Ts...> const &)` that then forwards each `T` to `::at(T const &)`--thoughts? 

Side note: the number of `auto`s here should be reduced--this code is rather difficult to read at the moment due to the ambiguity about what the types of everything are
___
*[`lib/substitutions/src/graph_pattern_match.cc` line 20 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_md4MBMhFeRNnswpT:-NmrKXU90VO8UXaayK9T:b-32wlyu) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern_match.cc#L20)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I have tracked it in the graph improvement issue.
</blockquote></details>

Sounds good, linking the issue here: #1198 
___
*[`lib/utils/include/utils/graph/digraph_interfaces.h` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_pTdD-fuphlUtDXem:-NmrLakJ8X-ZthReZ273:b92qjbb) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/digraph_interfaces.h#L25)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM, linking here: #1198  
___
*[`lib/utils/include/utils/graph/open_graph_interfaces.h` line 15 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_qx750yLopAQOmIFU:-NmrM7OpC8BIEOoOcVfU:b-v906uw) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graph_interfaces.h#L15)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not seeing this change here. Is this an accident, or is this going to be handled as part of #1198?
___
*[`lib/utils/include/utils/graph/open_graph_interfaces.h` line 48 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_rOYS0vYdwuOqxjD2:-NmrMHKd59tjuARSfz6h:bw6oorw) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graph_interfaces.h#L48)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM, moving to #1198.
___
*[`lib/utils/include/utils/graph/open_graph_interfaces.h` line 59 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_rchBDOySVat2ix0i:-NmrMeClCwgKh7Ko75_m:b-v1g4qm) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graph_interfaces.h#L59)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM, moving to #1198
___
*[`lib/utils/include/utils/graph/open_graph_interfaces.h` line 70 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_rk7lBDYL3KFKHWNm:-NmrMhcFENDJ6jtP7stH:b3bokdw) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graph_interfaces.h#L70)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM, moving to #1198. 
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 14 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_rsyG4RkHAhJnoUFU:-NmrMk69EwqnrMs4TY43:b-6zlsl) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L14)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not seeing this change here. Is this accidental, or are you planning on doing it as part of #1198?
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 43 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_s7wzC7lv-jGPj2xe:-NmrMsHO11rHI77ulN7G:bw6oorw) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L43)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM, moving to #1198.
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 105 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_sI5q7uRODT6hVj_D:-NmrNVlf6mKMPAp0BRi4:bw6oori) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L105)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM, moving to #1198 
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 168 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_sV_85vOkoNDiqzTl:-NmrNYH4Cl2dUoZ0Cd8d:bw6oori) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L168)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM, moving to #1198 
___
*[`lib/utils/include/utils/graph/undirected.h` line 62 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_sm1D0e_jVRRcqw_2:-NmrNaP45sZx62AL-hNu:bw6oori) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/undirected.h#L62)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM, moving to #1198 
___
*[`lib/utils/include/utils/graph/undirected.h` line 75 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_sthhC7mu65x-Y4p_:-NmrNc_O5YZgFmLfc9ZD:bw6oori) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/undirected.h#L75)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) w [...]

2024-01-02 05:43 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 7 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/graph/open_graph_interfaces.h` line 15 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_qx750yLopAQOmIFU:-Nn5iHQ1DJNXx6mcYdQz:bveeqm5) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graph_interfaces.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm not seeing this change here. Is this an accident, or is this going to be handled as part of #1198?
</blockquote></details>

It is part of graph improvements.
___
*[`lib/utils/include/utils/graph/open_graphs.h` line 14 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_rsyG4RkHAhJnoUFU:-Nn5iU5N1N_IrNyVsThj:bveeqm5) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/open_graphs.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm not seeing this change here. Is this accidental, or are you planning on doing it as part of #1198?
</blockquote></details>

It is part of graph improvements.
___
*[`lib/utils/include/utils/graph/views.h` line 263 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_tItNELKGXLb6h6VD:-Nn5iW1u8bQwffEP2lvw:bveeqm5) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/include/utils/graph/views.h#L263)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not seeing this change--is this an accident, or are you planning on doing it as part of #1198?
</blockquote></details>

It is part of graph improvements.
___
*[`lib/utils/test/src/test_algorithms.cc` line 20 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Nh4Ms5nCfm8PLzk8V4f:-Nn7gXNR5SMZd-fvJCtj:b-4l14st) ([raw file](https://github.com/flexflow/FlexFlow/blob/e31a41dfc98e16458e82e17758a7dca320415881/lib/utils/test/src/test_algorithms.cc#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yes, but why remove the declaration from the `std::vector`? Just seems a bit redundant
</blockquote></details>

Just thought it clearer.


<!-- Sent from Reviewable.io -->

2024-01-04 00:18 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 7 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/graph/digraph.cc` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_weJ5CodutQLxMGoW:-NnGp6Q02-vo2LGZqL_4:b-5g0318) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/src/graph/digraph.cc#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Does this really require a `get_mutable` call (which performs a copy)? Would it be better to have to overloads, one `const` which returns a `IDiGraphView const &` and does not use `get_mutable` and one which returns a `IDiGraphView &` and does use `get_mutable`?
</blockquote></details>

I remember I encountered some issues when trying to do that. Currently I use const pointers in graph views and non-const pointers in graphs.


<!-- Sent from Reviewable.io -->

2024-01-05 03:22 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 3 unresolved discussions (waiting on @wmdi)

___
*[`lib/utils/src/graph/digraph.cc` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_weJ5CodutQLxMGoW:-NnMcWNM6eAwYrQF6fEm:br3ukf4) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/src/graph/digraph.cc#L25)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I remember I encountered some issues when trying to do that. Currently I use const pointers in graph views and non-const pointers in graphs.
</blockquote></details>

Can you take another look into what issues you ran into and either resolve them here or create a github issue with a specific writeup? Adding a potential copy on every pointer access seems like a rather significant problem
___
*[`lib/utils/test/src/test_algorithms.cc` line 20 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Nh4Ms5nCfm8PLzk8V4f:-NnMc3fiCq7Etr_Vg1BQ:b-9gz8b2) ([raw file](https://github.com/flexflow/FlexFlow/blob/e31a41dfc98e16458e82e17758a7dca320415881/lib/utils/test/src/test_algorithms.cc#L20)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Just thought it clearer.
</blockquote></details>

Makes sense, though it has the disadvantage of being more verbose. Not a huge deal so I'll resolve this


<!-- Sent from Reviewable.io -->

2024-01-06 03:48 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: 104 of 106 files reviewed, 3 unresolved discussions (waiting on @lockshaw)

___
*[`deps/fmt` line 1 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_lDuKD9mt9EOuWmR3:-NnQ9YF0AGmz13a_5fb2:b-9z0sg8) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/deps/fmt#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move it to `f5e5`?
</blockquote></details>

Where is f5e5? Which branch is it in?
___
*[`lib/substitutions/src/graph_pattern.cc` line 237 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_mPit5deehC6Q5RBc:-NnRsekz9i1M8R6n-VOh:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/substitutions/src/graph_pattern.cc#L237)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I guess my confusion is what an `OutputLabelledOpenMultiDiGraphView` should conceptually do--I would expect `InputMultiDiEdge`s in an `OutputLabelledOpenMultiDiGraphView` to not be labelled, but it seems that's not the case. Thinking briefly it seems like the best solution here would be to add an `::at(variant<Ts...> const &)` that then forwards each `T` to `::at(T const &)`--thoughts? 

Side note: the number of `auto`s here should be reduced--this code is rather difficult to read at the moment due to the ambiguity about what the types of everything are
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-06 04:18 UTC, wmdi reviewed
> Reviewed 1 of 2 files at r7, 15 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/graph/digraph.cc` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_weJ5CodutQLxMGoW:-NnRyKFtALt1gXRBYZNs:b-uvvbt3) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/src/graph/digraph.cc#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you take another look into what issues you ran into and either resolve them here or create a github issue with a specific writeup? Adding a potential copy on every pointer access seems like a rather significant problem
</blockquote></details>

The issue is that `Interface &get_ptr()` should be const since it does not make any change the the graph, but if we make it const, it is not distinguished from `Interface const &get_ptr()`, which would cause a compile error. I make it non-const for now. Do you have any better solutions?


<!-- Sent from Reviewable.io -->

2024-01-07 06:33 UTC, lockshaw requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 3 unresolved discussions (waiting on @wmdi)

___
*[`deps/fmt` line 1 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_lDuKD9mt9EOuWmR3:-NnXaSW1Bl5m4sCALEPr:b-hb7w9y) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/deps/fmt#L1)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Where is f5e5? Which branch is it in?
</blockquote></details>

It's a commit on `fmt`--this PR currently changes the commit of `deps/fmt` from `f5e5` (what it should be) to `a337` (an older commit that we aren't using anymore)
___
*[`lib/utils/include/utils/graph/labelled/output_labelled_open.h` line 30 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-NnXb05A8BtpVnwfYU3j:-NnXb05A8BtpVnwfYU3k:b-roemp2) ([raw file](https://github.com/flexflow/FlexFlow/blob/68a1bf16a05cffeed9cf939ffa12a7322861f832/lib/utils/include/utils/graph/labelled/output_labelled_open.h#L30)):*
> ```objc
>       operator=(OutputLabelledOpenMultiDiGraphView const &) = default;
> 
>   virtual NodeLabel const &at(Node const &n) const {
> ```

Why are these virtual?
___
*[`lib/utils/src/graph/digraph.cc` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_weJ5CodutQLxMGoW:-NnXbUJY36ARWLTfWO31:b-5zt9sz) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/src/graph/digraph.cc#L25)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

The issue is that `Interface &get_ptr()` should be const since it does not make any change the the graph, but if we make it const, it is not distinguished from `Interface const &get_ptr()`, which would cause a compile error. I make it non-const for now. Do you have any better solutions?
</blockquote></details>

Why should `Interface &get_ptr()` be `const`--accessors which return non-const references are frequently not marked `const` (e.g., indexing into a vector: https://en.cppreference.com/w/cpp/container/vector/operator_at)


<!-- Sent from Reviewable.io -->

2024-01-08 20:02 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: 105 of 106 files reviewed, 3 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/graph/labelled/output_labelled_open.h` line 30 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-NnXb05A8BtpVnwfYU3j:-Nnee_zm28QVRTTgXE8f:b-5s5kua) ([raw file](https://github.com/flexflow/FlexFlow/blob/68a1bf16a05cffeed9cf939ffa12a7322861f832/lib/utils/include/utils/graph/labelled/output_labelled_open.h#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are these virtual?
</blockquote></details>

`OutputLabelledOpenMultiDiGraph` inherits them and may use a different implementation
___
*[`lib/utils/src/graph/digraph.cc` line 25 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_weJ5CodutQLxMGoW:-Nneer9lAGgyArkYRGKk:bxxx4gf) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/lib/utils/src/graph/digraph.cc#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why should `Interface &get_ptr()` be `const`--accessors which return non-const references are frequently not marked `const` (e.g., indexing into a vector: https://en.cppreference.com/w/cpp/container/vector/operator_at)
</blockquote></details>

That makes sense.
___
*[`deps/fmt` line 1 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-Ng_lDuKD9mt9EOuWmR3:-NneetXkBusHQn9hwTTa:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9ef1113dbb63a5467a2c80a58404e1cbb3c48081/deps/fmt#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It's a commit on `fmt`--this PR currently changes the commit of `deps/fmt` from `f5e5` (what it should be) to `a337` (an older commit that we aren't using anymore)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-10 19:00 UTC, wmdi reviewed
> Reviewed 3 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-01-17 22:35 UTC, lockshaw requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 1 unresolved discussion (waiting on @wmdi)

___
*[`lib/utils/include/utils/graph/labelled/output_labelled_open.h` line 30 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-NnXb05A8BtpVnwfYU3j:-NoOYeur7xOkJQVFsFR0:bxmpxyx) ([raw file](https://github.com/flexflow/FlexFlow/blob/68a1bf16a05cffeed9cf939ffa12a7322861f832/lib/utils/include/utils/graph/labelled/output_labelled_open.h#L30)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

`OutputLabelledOpenMultiDiGraph` inherits them and may use a different implementation
</blockquote></details>

The non-interface graphs shouldn't have any non-virtual methods--can you give me an example that would necessitate them being virtual?


<!-- Sent from Reviewable.io -->

2024-01-17 22:42 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/utils/include/utils/graph/labelled/output_labelled_open.h` line 30 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-NnXb05A8BtpVnwfYU3j:-NoO_VTEATMQtDaQt3PS:ba2cjp3) ([raw file](https://github.com/flexflow/FlexFlow/blob/68a1bf16a05cffeed9cf939ffa12a7322861f832/lib/utils/include/utils/graph/labelled/output_labelled_open.h#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The non-interface graphs shouldn't have any non-virtual methods--can you give me an example that would necessitate them being virtual?
</blockquote></details>

For example, `GraphView::at()` should use `GraphView::get_ptr()` which returns a `IGraphView` pointer, while `Graph()::at()` should use `Graph::get_ptr()` which returns a `IGraph` pointer.


<!-- Sent from Reviewable.io -->

2024-01-18 01:51 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 1 unresolved discussion (waiting on @wmdi)

___
*[`lib/utils/include/utils/graph/labelled/output_labelled_open.h` line 30 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-NnXb05A8BtpVnwfYU3j:-NoPFstg2j57ojMJaubM:buplz5e) ([raw file](https://github.com/flexflow/FlexFlow/blob/68a1bf16a05cffeed9cf939ffa12a7322861f832/lib/utils/include/utils/graph/labelled/output_labelled_open.h#L30)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

For example, `GraphView::at()` should use `GraphView::get_ptr()` which returns a `IGraphView` pointer, while `Graph()::at()` should use `Graph::get_ptr()` which returns a `IGraph` pointer.
</blockquote></details>

But the pointer type doesn't matter because the `get_ptr()::at` is virtual anyway, right?


<!-- Sent from Reviewable.io -->

2024-01-19 17:39 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: 100 of 107 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/utils/include/utils/graph/labelled/output_labelled_open.h` line 30 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1189#-NnXb05A8BtpVnwfYU3j:-NoXnbGEBoQoatpsHuoz:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/68a1bf16a05cffeed9cf939ffa12a7322861f832/lib/utils/include/utils/graph/labelled/output_labelled_open.h#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

But the pointer type doesn't matter because the `get_ptr()::at` is virtual anyway, right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-19 17:51 UTC, wmdi reviewed
> Reviewed 7 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1189)* status: all files reviewed, 1 unresolved discussion (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-01-19 18:14 UTC, merged