Finish implementing `compiler`
flexflow/FlexFlow pull request #1229
Opened 2023-11-15 22:17 UTC by wmdi

**Description of changes:**

- [ ] finish machine mapping (dp algorithm)
- [ ] finish cost estimator
- [ ] finish unity search

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2023-11-29 19:36 UTC, wmdi reviewed
> Reviewed 26 of 76 files at r3, 123 of 123 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lambda7xx and @lockshaw)



<!-- Sent from Reviewable.io -->

2024-01-24 03:46 UTC, wmdi reviewed
> Reviewed 86 of 86 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lambda7xx and @lockshaw)



<!-- Sent from Reviewable.io -->

2024-01-24 21:33 UTC, wmdi reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lambda7xx and @lockshaw)



<!-- Sent from Reviewable.io -->

2024-01-25 21:22 UTC, wmdi reviewed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lambda7xx and @lockshaw)



<!-- Sent from Reviewable.io -->

2024-02-01 01:40 UTC, lockshaw requested changes
> Reviewed 5 of 76 files at r3, 57 of 123 files at r4, 85 of 86 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 80 unresolved discussions (waiting on @lambda7xx and @wmdi)

___
*[`lib/compiler/include/compiler/machine_mapping.h` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX51N604K_nzulA_-0:-NpX51N604K_nzulA_-1:b-7f14bh) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/machine_mapping.h#L27)):*
> ```objc
>   SerialParallelDecomposition subgraph;
>   req<MachineSpecification> resource;
>   // req<std::unordered_map<Node, MachineView>> given_machine_views;
> ```

What are these for? Why are they commented out? 
___
*[`lib/compiler/include/compiler/unity_algorithm.h` line 39 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX5DHJDKul42gzJrcx:-NpX5DHJDKul42gzJrcy:b-cxeztr) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/unity_algorithm.h#L39)):*
> ```objc
> } // namespace FlexFlow
> 
> VISITABLE_STRUCT(FlexFlow::Strategy, pcg, machine_mapping, runtime);
> ```

Why here instead of using `FF_VISITABLE_STRUCT`?
___
*[`lib/compiler/src/graph_utils.cc` line 15 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX9nQmAsR22ZFk2PaA:-NpX9nQmAsR22ZFk2PaB:bx68o5s) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/graph_utils.cc#L15)):*
> ```cpp
> 
> SubParallelComputationGraph pcg_to_subpcg(ParallelComputationGraph const &pcg) {
>   return materialize_output_labelled_open_multidigraph_view<
> ```

I don't think doing this should be this complicated. If it is we probably need to make some changes to the graph library. Also, why is explicit materialization required here? Viewing sub-PCGs is the whole point of the view abstraction
___
*[`lib/compiler/src/machine_mapping.cc` line 0 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX8zrl0oBy5ZO3T--s:-NpX8zrl0oBy5ZO3T--t:b-r2il9d) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L0)):*
Overall the readability of the algorithm here (while much better than the old version) still needs a bit of work. The key thing is all the argument passing obscures what's actually going on
___
*[`lib/compiler/src/machine_mapping.cc` line 48 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX5V8qAWtKZcOXXCjX:-NpX5V8qAWtKZcOXXCjY:bedx8cr) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L48)):*
> ```cpp
> optional<OptimalCostResult>
>     OptimalCostCache::load(OptimalCostState const &state) const {
>   auto it = cache.find(state);
> ```

This looks unfinished?
___
*[`lib/compiler/src/machine_mapping.cc` line 99 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX5cj70M8XO9mlrax5:-NpX5cj70M8XO9mlrax6:bw9pcnb) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L99)):*
> ```cpp
>                     std::unordered_map<OpenMultiDiEdge, MachineView> const
>                         &frontier_machine_views) {
>   return 0.1;
> ```

This hardcoding the cost should probably be moved to the specific  implementation of `ICostEstimator` that backs `estimator`, instead of here
___
*[`lib/compiler/src/machine_mapping.cc` line 137 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX6hqO0ruGWj4be2aR:-NpX6hqO0ruGWj4be2aS:buylpj5) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L137)):*
> ```cpp
>   OptimalCostResult operator()(T const &t) const {
>     OptimalCostState state{
>         t, resource /*, given_machine_views, frontier_machine_views*/};
> ```

Remove commented-out arguments?
___
*[`lib/compiler/src/machine_mapping.cc` line 157 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX7ANo4RDJuxFstBIh:-NpX7ANo4RDJuxFstBIi:b-6cqxit) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L157)):*
> ```cpp
>     GraphSplit graph_split = get_graph_split(pre_decompn, post_decompn);
>     SubParallelComputationGraphView pre_graph =
>         get_subgraph<OpenMultiDiSubgraphView>(g, graph_split.first);
> ```

Why are explicit template parameters necessary here?
___
*[`lib/compiler/src/machine_mapping.cc` line 193 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX7LBrDDSzRFwo2vYX:-NpX7LBrDDSzRFwo2vYY:bdnie66) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L193)):*
> ```cpp
>                                              resource,
>                                              new_given_machine_views,
>                                              frontier_machine_views,
> ```

Instead of using a single implementation to do both unity and the newer-memory-optimization algorithms, I'd rather have two different algorithm implementations and factor out the parts in common where necessary/useful. Otherwise this is quickly going to grow unmaintainably large
___
*[`lib/compiler/src/machine_mapping.cc` line 215 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX7lwd2q96mcORyrmL:-NpX7lwd2q96mcORyrmM:b-u4d5gx) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L215)):*
> ```cpp
>     OptimalCostResult optimal_result = OptimalCostResult::sequential_combine(
>         visit(OptimalCost(g1,
>                           cost_estimator,
> ```

I appreciate the stateless design here (i.e., passing all of the algorithm state in the form of `resource`, `allowed_machine_views`, `cached_subgraph_costs`, etc. but here I think it's making things hard to read/understand. Can we separate the implementation here into a stateless layer (where most of the individual code is) and then add a stateful layer on top for readability? 

Also, since this is all stateless I'm a little confused why there is a class here (i.e., `OptimalCost`)--if this is just to handle `visit` let's move the `visit` invocation into a separate function so the details of how all variant dispatch are separate from the actual algorithm.
___
*[`lib/compiler/src/unity_algorithm.cc` line 13 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXA8r0841AHwk_xmDU:-NpXA8r0841AHwk_xmDV:bn57q32) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L13)):*
> ```cpp
> 
> std::unordered_set<Substitution>
>     get_all_substitutions(ParallelComputationGraph const &pcg) {
> ```

What is this function intended to do? Is it to get all *applicable* substitutions? Or if not why does it require a `ParallelComputationGraph` as input?

Especially for these `NOT_IMPLEMENTED` functions a quick docstring would be quite helpful--we have doxygen support :slightly_smiling_face: 
___
*[`lib/compiler/src/unity_algorithm.cc` line 46 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXAVjl93l3Empuvhfk:-NpXAVjl93l3Empuvhfl:b1qbq83) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L46)):*
> ```cpp
>                                                       cached_subgraph_costs);
>   Strategy initial_result{
>       pcg, initial_pcg_result.machine_mapping, initial_pcg_result.runtime};
> ```

Why does `optimal_cost` not just return a `Strategy` directly, or why does an API that just does that translation not exist?
___
*[`lib/compiler/src/unity_algor [...]

2024-02-15 19:17 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 80 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/machine_mapping.h` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX51N604K_nzulA_-0:-NqOmdED3v8Dhvx5Whmd:bx2yp4q) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/machine_mapping.h#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What are these for? Why are they commented out?
</blockquote></details>

This is related to an issue I forgot to report. We need these attributes, but `FF_VISITABLE_STRUCT` would fail with them.
___
*[`lib/compiler/include/compiler/unity_algorithm.h` line 39 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX5DHJDKul42gzJrcx:-NqOnKv1-VuliR07fL-z:b-hbvs6v) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/unity_algorithm.h#L39)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why here instead of using `FF_VISITABLE_STRUCT`?
</blockquote></details>

I don't want automatically generated `operator==` for them.
___
*[`lib/compiler/src/graph_utils.cc` line 15 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX9nQmAsR22ZFk2PaA:-NqOnR0-2C_iALwX4BpP:blp4i9d) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/graph_utils.cc#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think doing this should be this complicated. If it is we probably need to make some changes to the graph library. Also, why is explicit materialization required here? Viewing sub-PCGs is the whole point of the view abstraction
</blockquote></details>

The template arguments make it look so but I don't think it too complicated. An explicit materialization is required here because we need a graph instead of a graph view, which is because we need to change the graph in the algorithm.
___
*[`lib/compiler/src/machine_mapping.cc` line 48 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX5V8qAWtKZcOXXCjX:-NqOpypHDFbeb3o8Uft8:bav7gv9) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L48)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This looks unfinished?
</blockquote></details>

Yes, due to the `visitable` issue of `OptimalCostState`.
___
*[`lib/compiler/src/machine_mapping.cc` line 99 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX5cj70M8XO9mlrax5:-Nqe17Wm4jgI0am3tuc0:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L99)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This hardcoding the cost should probably be moved to the specific  implementation of `ICostEstimator` that backs `estimator`, instead of here
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 137 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX6hqO0ruGWj4be2aR:-NqQG9U0Bw652qUHskcd:b-no3u3o) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L137)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove commented-out arguments?
</blockquote></details>

This should be fixed with the `visitable` issue related to `OptimalCostState`.
___
*[`lib/compiler/src/machine_mapping.cc` line 157 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX7ANo4RDJuxFstBIh:-NqQGILY8GvN_8KsgIMU:bng6qvu) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L157)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are explicit template parameters necessary here?
</blockquote></details>

We use template parameters to specify the open type of the subgraph now. It should be unnecessary after we change the open subgraph algorithm.
___
*[`lib/compiler/src/machine_mapping.cc` line 193 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX7LBrDDSzRFwo2vYX:-NqQGbNnE2CaOAQh_m37:b69nlfm) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L193)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Instead of using a single implementation to do both unity and the newer-memory-optimization algorithms, I'd rather have two different algorithm implementations and factor out the parts in common where necessary/useful. Otherwise this is quickly going to grow unmaintainably large
</blockquote></details>

I agree. Will keep it in mind when implementing the new algorithm.
___
*[`lib/compiler/src/unity_algorithm.cc` line 13 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXA8r0841AHwk_xmDU:-Nqe1wpCA4esINEGlJFN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is this function intended to do? Is it to get all *applicable* substitutions? Or if not why does it require a `ParallelComputationGraph` as input?

Especially for these `NOT_IMPLEMENTED` functions a quick docstring would be quite helpful--we have doxygen support :slightly_smiling_face:
</blockquote></details>

Done.
___
*[`lib/compiler/src/unity_algorithm.cc` line 46 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXAVjl93l3Empuvhfk:-Nqe2B19A89rbi2sZ5Dr:b-hacjsd) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does `optimal_cost` not just return a `Strategy` directly, or why does an API that just does that translation not exist?
</blockquote></details>

I treat the PCG as the input of `optimal_cost`, which means `optimal_cost` searches for the best device mapping for a fixed PCG. On the other hand, the upper-level search `graph_optimize` searches for a PCG. Thus it makes more sense that PCG is not part of the output of `optimal_cost`.
___
*[`lib/compiler/src/unity_algorithm.cc` line 56 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXBFa4DEI_Q7BVQBap:-Nqe3K63APPx_UcXoS2P:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L56)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just compare on runtime directly unless there's some abstraction that's being enabled here
</blockquote></details>

Done.
___
*[`lib/compiler/src/unity_algorithm.cc` line 86 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXBg095C6L-xF1EIVB:-Nqe3TJm0O0RJiKKYk_z:bnrur9c) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L86)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not use `visitable` for the hash function?
</blockquote></details>

The hash function for MachineMapping does not work and I use manual hash function to get around temporarily. Will get back to `visitable` after the `visitable` issues are solved. 
___
*[`lib/compiler/src/old/basic_graph.h` line  at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXBnD5BRz0sgZMXCA3:- [...]

2024-02-16 02:25 UTC, lockshaw requested changes
> Reviewed 22 of 23 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: 152 of 153 files reviewed, 60 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/machine_mapping.h` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX51N604K_nzulA_-0:-NqjYwvu7Qn14XXKpyQB:b94ju50) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/machine_mapping.h#L27)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

This is related to an issue I forgot to report. We need these attributes, but `FF_VISITABLE_STRUCT` would fail with them.
</blockquote></details>

What is the issue?
___
*[`lib/compiler/include/compiler/unity_algorithm.h` line 39 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX5DHJDKul42gzJrcx:-NqjZYB_DACubrIJe_7R:b-www5v0) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/unity_algorithm.h#L39)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I don't want automatically generated `operator==` for them.
</blockquote></details>

Why not? Usually that's an indicator that you shouldn't actually be using `visitable`
___
*[`lib/compiler/include/compiler/unity_algorithm.h` line 14 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NqjZrSI1kvljyil2LkV:-NqjZrSI1kvljyil2LkW:bif0cnn) ([raw file](https://github.com/flexflow/FlexFlow/blob/95fa427b8680e68acf33cccf96bbc66bb37cd1fa/lib/compiler/include/compiler/unity_algorithm.h#L14)):*
> ```objc
>   ParallelComputationGraph pcg;
>   MachineMapping machine_mapping;
>   req<float> runtime;
> ```

Why put `runtime` as an object on `Strategy` rather than having an `unordered_map` somewhere from pairs of `ParallelComputationGraph` and `MachineMapping` to `runtime`?
___
*[`lib/compiler/src/graph_utils.cc` line 15 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX9nQmAsR22ZFk2PaA:-Nqj_ERG0NshiTlk5whZ:b-emx7y6) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/graph_utils.cc#L15)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

The template arguments make it look so but I don't think it too complicated. An explicit materialization is required here because we need a graph instead of a graph view, which is because we need to change the graph in the algorithm.
</blockquote></details>

Why are we changing the graph in the algorithm? If you're referring to applying substitutions, then it seems like materializing the graph should instead be handled there and not here?

Also, the need to pass all those template arguments to me suggests that the interface actually is to complex, as there generally should not be like 5 different template parameters that all have effects that don't have reasonable defaults that can be inferred
___
*[`lib/compiler/src/machine_mapping.cc` line 48 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX5V8qAWtKZcOXXCjX:-Nqja1g_5_hT9AExp0pa:b-c7ctnb) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L48)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Yes, due to the `visitable` issue of `OptimalCostState`.
</blockquote></details>

What is this issue?
___
*[`lib/compiler/src/machine_mapping.cc` line 157 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX7ANo4RDJuxFstBIh:-NqjawVG5q6m8QWdXxD3:b-sosesk) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L157)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

We use template parameters to specify the open type of the subgraph now. It should be unnecessary after we change the open subgraph algorithm.
</blockquote></details>

Why can't this just be inferred from the type of `g`?
___
*[`lib/compiler/src/machine_mapping.cc` line 100 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NqjadNd2RcWtwUNidqF:-NqjadNd2RcWtwUNidqG:bgxfd1z) ([raw file](https://github.com/flexflow/FlexFlow/blob/95fa427b8680e68acf33cccf96bbc66bb37cd1fa/lib/compiler/src/machine_mapping.cc#L100)):*
> ```cpp
>                         &frontier_machine_views) {
>   float cost = 0;
>   for (Node const &node : get_nodes(g)) {
> ```

It's not entirely clear to me what this function is doing. Why is the cost just the sum of the cost of the pieces? Where is parallelism taken into account?
___
*[`lib/compiler/src/unity_algorithm.cc` line 13 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXA8r0841AHwk_xmDU:-NqjbOyeERNjQQefHUaM:b-atscbs) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L13)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In that case, maybe rename to `get_all_applicable_substitutions`? I think the clarity is worth the extra typing
___
*[`lib/compiler/src/unity_algorithm.cc` line 46 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXAVjl93l3Empuvhfk:-NqjbsFSAkkv0n5rsgzt:b3b6giy) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L46)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I treat the PCG as the input of `optimal_cost`, which means `optimal_cost` searches for the best device mapping for a fixed PCG. On the other hand, the upper-level search `graph_optimize` searches for a PCG. Thus it makes more sense that PCG is not part of the output of `optimal_cost`.
</blockquote></details>

In that case why is the PCG part of `Strategy`?
___
*[`lib/compiler/test/src/test_labelled_open_graph.cc` line 59 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXCPQE9KCHCXa2DLPb:-NqjcBEA-CE6p-IG7kHw:bnpwnk) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/test/src/test_labelled_open_graph.cc#L59)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

To get around the fmt issue.
</blockquote></details>

What fmt issue?
___
*[`lib/compiler/test/src/test_labelled_open_graph.cc` line 10 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NqjcFeLEwUdLq7qK7Ch:-NqjcFeLEwUdLq7qK7Ci:b-ub342f) ([raw file](https://github.com/flexflow/FlexFlow/blob/95fa427b8680e68acf33cccf96bbc66bb37cd1fa/lib/compiler/test/src/test_labelled_open_graph.cc#L10)):*
> ```cpp
>   auto g = OpenMultiDiGraph::create<AdjacencyOpenMultiDiGraph>();
> 
>   int t0 = 100000;
> ```

What is `t0` here for?
___
*[`lib/compiler/test/src/test_optimal_cost.cc` line 11 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXDTofC7_zHN4I0i8B:-NqjcRUv9587ZyAUMOIl:b8xbyia) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/test/src/test_optimal_cost.cc#L11)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

They use rapidcheck which does not work for now.
</blockquote></details>

In that case an issue should be created and a link should be placed in the code so people reading this know why it's commented out and we don't lose track of the fact that it needs to be fixed.
___
*[`lib/pcg/include/pcg/operator.h` line 23 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-Nqjco152oGkHOfT3ISA:-Nqjco152oGkHOfT3ISB:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/95fa427b8680e68acf33cccf96bbc66bb37cd1fa/lib/pcg/include/pcg/operator.h#L23)):*
> ```objc
> FF_VISITABLE_STRUCT(Operator, attrs, name);
> 
> static_asse [...]

2024-02-18 21:26 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: 152 of 153 files reviewed, 60 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/machine_mapping.h` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX51N604K_nzulA_-0:-Nqy5VTM4L_V8ORHC1xd:bkqjp8r) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/machine_mapping.h#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is the issue?
</blockquote></details>

```
In file included from /home/mengdiwu/wmdi/FlexFlow/lib/op-attrs/include/op-attrs/tensor_shape.h:8,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/op-attrs/include/op-attrs/parallel_tensor_shape.h:5,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/op-attrs/include/op-attrs/ops/attention.h:5,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/op-attrs/include/op-attrs/operator_attrs.h:5,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/compiler/include/compiler/cost_estimate.h:5,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/compiler/include/compiler/unity_algorithm.h:4,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/compiler/src/graph_utils.h:4,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/compiler/src/graph_utils.cc:1:
/home/mengdiwu/wmdi/FlexFlow/lib/utils/include/utils/visitable.h:320:56: error: static assertion failed: OptimalCostState should be fully visitable
  320 |   static_assert(sizeof(visit_as_tuple_raw_t<TYPENAME>) == sizeof(TYPENAME),    \
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/home/mengdiwu/wmdi/FlexFlow/lib/utils/include/utils/visitable.h:313:3: note: in expansion of macro ‘CHECK_WELL_BEHAVED_VISIT_TYPE_NONSTANDARD_CONSTRUCTION_NO_EQ’
  313 |   CHECK_WELL_BEHAVED_VISIT_TYPE_NONSTANDARD_CONSTRUCTION_NO_EQ(TYPENAME);      \
```
Is it because `std::unordered_map` is not visitable?


<!-- Sent from Reviewable.io -->

2024-02-18 21:33 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: 152 of 153 files reviewed, 60 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/machine_mapping.h` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX51N604K_nzulA_-0:-Nqy7OTn8ZcwSw2cYYpJ:bx27i7a) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/machine_mapping.h#L27)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

```
In file included from /home/mengdiwu/wmdi/FlexFlow/lib/op-attrs/include/op-attrs/tensor_shape.h:8,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/op-attrs/include/op-attrs/parallel_tensor_shape.h:5,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/op-attrs/include/op-attrs/ops/attention.h:5,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/op-attrs/include/op-attrs/operator_attrs.h:5,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/compiler/include/compiler/cost_estimate.h:5,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/compiler/include/compiler/unity_algorithm.h:4,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/compiler/src/graph_utils.h:4,
                 from /home/mengdiwu/wmdi/FlexFlow/lib/compiler/src/graph_utils.cc:1:
/home/mengdiwu/wmdi/FlexFlow/lib/utils/include/utils/visitable.h:320:56: error: static assertion failed: OptimalCostState should be fully visitable
  320 |   static_assert(sizeof(visit_as_tuple_raw_t<TYPENAME>) == sizeof(TYPENAME),    \
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/home/mengdiwu/wmdi/FlexFlow/lib/utils/include/utils/visitable.h:313:3: note: in expansion of macro ‘CHECK_WELL_BEHAVED_VISIT_TYPE_NONSTANDARD_CONSTRUCTION_NO_EQ’
  313 |   CHECK_WELL_BEHAVED_VISIT_TYPE_NONSTANDARD_CONSTRUCTION_NO_EQ(TYPENAME);      \
```
Is it because `std::unordered_map` is not visitable?
</blockquote></details>

It's complaining that not all of the fields of `OptimalCostState` are listed under the `FF_VISITABLE_STRUCT` declaration. I'm not entirely sure what code you tried to compile, but the following should be correct:



_Suggestion:_
```objc
struct OptimalCostState {
  SerialParallelDecomposition subgraph;
  MachineSpecification resource;
  std::unordered_map<Node, MachineView> given_machine_views;
  req<std::unordered_map<OpenMultiDiEdge, MachineView>> frontier_machine_views;
};
FF_VISITABLE_STRUCT(OptimalCostState, subgraph, resource, given_machine_views, frontier_machine_views);
```


<!-- Sent from Reviewable.io -->

2024-02-18 21:37 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: 152 of 153 files reviewed, 60 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/machine_mapping.h` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX51N604K_nzulA_-0:-Nqy8eR_-m5cLkoNs0FD:b-gu0bdb) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/machine_mapping.h#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It's complaining that not all of the fields of `OptimalCostState` are listed under the `FF_VISITABLE_STRUCT` declaration. I'm not entirely sure what code you tried to compile, but the following should be correct:
</blockquote></details>

I changed to this version and got a long error information which starts with
```
/home/mengdiwu/wmdi/FlexFlow/lib/compiler/src/machine_mapping.cc:168:22: error: use of deleted function ‘FlexFlow::required<std::unordered_map<mpark::variant<FlexFlow::InputMultiDiEdge, FlexFlow::OutputMultiDiEdge, FlexFlow::MultiDiEdge>, FlexFlow::MachineView>, void>::required()’
```


<!-- Sent from Reviewable.io -->

2024-02-18 21:51 UTC, lockshaw commented
*[`lib/compiler/include/compiler/machine_mapping.h` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX51N604K_nzulA_-0:-NqyBv_20FXU85k0GaUQ:b-yvg6sm) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/machine_mapping.h#L27)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I changed to this version and got a long error information which starts with
```
/home/mengdiwu/wmdi/FlexFlow/lib/compiler/src/machine_mapping.cc:168:22: error: use of deleted function ‘FlexFlow::required<std::unordered_map<mpark::variant<FlexFlow::InputMultiDiEdge, FlexFlow::OutputMultiDiEdge, FlexFlow::MultiDiEdge>, FlexFlow::MachineView>, void>::required()’
```
</blockquote></details>

That's because you're not passing in sufficient arguments at that line: https://github.com/flexflow/FlexFlow/blob/95fa427b8680e68acf33cccf96bbc66bb37cd1fa/lib/compiler/src/machine_mapping.cc#L168-L169


<!-- Sent from Reviewable.io -->

2024-02-18 21:52 UTC, lockshaw requested changes
> Reviewed 1 of 23 files at r8.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 60 unresolved discussions (waiting on @lockshaw and @wmdi)



<!-- Sent from Reviewable.io -->

2024-02-18 21:56 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 60 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/src/machine_mapping.cc` line 137 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX6hqO0ruGWj4be2aR:-NqyCHZv3JAbSw8WhG89:boa73ag) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L137)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

This should be fixed with the `visitable` issue related to `OptimalCostState`.
</blockquote></details>

Can you put this comment into the "Working" state on your side? That keeps it from going away but makes it not blocked on me. In general when the response is "will do, but am waiting on some other issue", put the discussion in the "Working" state. If you're not sure how to do this, see https://docs.reviewable.io/discussions.html#checking-and-changing-dispositions
___
*[`lib/compiler/src/unity_algorithm.cc` line 86 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXBg095C6L-xF1EIVB:-NqyD1p24f-DhA3ZEnPS:bf2m25u) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L86)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

The hash function for MachineMapping does not work and I use manual hash function to get around temporarily. Will get back to `visitable` after the `visitable` issues are solved.
</blockquote></details>

https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX6hqO0ruGWj4be2aR


<!-- Sent from Reviewable.io -->

2024-02-18 22:00 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 60 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/machine_mapping.h` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX51N604K_nzulA_-0:-NqyDeJ51Gvjqnx-eff5:b1i9dg3) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/machine_mapping.h#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

That's because you're not passing in sufficient arguments at that line: https://github.com/flexflow/FlexFlow/blob/95fa427b8680e68acf33cccf96bbc66bb37cd1fa/lib/compiler/src/machine_mapping.cc#L168-L169
</blockquote></details>

It becomes
```
/home/mengdiwu/wmdi/FlexFlow/lib/compiler/src/machine_mapping.cc:48:29:   required from here
/usr/include/c++/9/bits/hashtable.h:1026:4: error: no matching function for call to ‘std::_Hashtable<std::pair<FlexFlow::Node, std::pair<const FlexFlow::Node, FlexFlow::MachineView> >, std::pair<FlexFlow::Node, std::pair<const FlexFlow::Node, FlexFlow::MachineView> >, std::allocator<std::pair<FlexFlow::Node, std::pair<const FlexFlow::Node, FlexFlow::MachineView> > >, std::__detail::_Identity, std::equal_to<std::pair<FlexFlow::Node, std::pair<const FlexFlow::Node, FlexFlow::MachineView> > >, std::hash<std::pair<FlexFlow::Node, std::pair<const FlexFlow::Node, FlexFlow::MachineView> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::insert(const std::pair<const FlexFlow::Node, FlexFlow::MachineView>&)’
 1026 |    this->insert(*__f);
      |    ^~~~

```
this time. And line `machine_mapping.cc:48:29` is
```
  auto it = cache.find(state);
```


<!-- Sent from Reviewable.io -->

2024-02-18 22:10 UTC, lockshaw commented
*[`lib/compiler/include/compiler/machine_mapping.h` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX51N604K_nzulA_-0:-NqyGF2z40qfpUmAZfHI:bz9581) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/machine_mapping.h#L27)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

It becomes
```
/home/mengdiwu/wmdi/FlexFlow/lib/compiler/src/machine_mapping.cc:48:29:   required from here
/usr/include/c++/9/bits/hashtable.h:1026:4: error: no matching function for call to ‘std::_Hashtable<std::pair<FlexFlow::Node, std::pair<const FlexFlow::Node, FlexFlow::MachineView> >, std::pair<FlexFlow::Node, std::pair<const FlexFlow::Node, FlexFlow::MachineView> >, std::allocator<std::pair<FlexFlow::Node, std::pair<const FlexFlow::Node, FlexFlow::MachineView> > >, std::__detail::_Identity, std::equal_to<std::pair<FlexFlow::Node, std::pair<const FlexFlow::Node, FlexFlow::MachineView> > >, std::hash<std::pair<FlexFlow::Node, std::pair<const FlexFlow::Node, FlexFlow::MachineView> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::insert(const std::pair<const FlexFlow::Node, FlexFlow::MachineView>&)’
 1026 |    this->insert(*__f);
      |    ^~~~

```
this time. And line `machine_mapping.cc:48:29` is
```
  auto it = cache.find(state);
```
</blockquote></details>

Hmm, not sure what's going on there. Can you push your current code and I'll take a look?


<!-- Sent from Reviewable.io -->

2024-02-18 22:28 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: 151 of 153 files reviewed, 60 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/machine_mapping.h` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX51N604K_nzulA_-0:-NqyKJaODrA-2K-hXJ3y:b-lvtrwi) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/machine_mapping.h#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Hmm, not sure what's going on there. Can you push your current code and I'll take a look?
</blockquote></details>

pushed


<!-- Sent from Reviewable.io -->

2024-02-20 23:17 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: 151 of 153 files reviewed, 60 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/src/machine_mapping.cc` line 157 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX7ANo4RDJuxFstBIh:-Nr7mv2G68063NUOa3s2:b-9j15x1) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L157)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why can't this just be inferred from the type of `g`?
</blockquote></details>

It can, but not for now. Currently whether the subgraph is closed, upward open, downward open or open is determined by the template argument. It is planned to be changed in #1284 . 


<!-- Sent from Reviewable.io -->

2024-02-27 21:34 UTC, wmdi reviewed
> Reviewed 21 of 23 files at r8, 10 of 10 files at r10.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: 141 of 157 files reviewed, 59 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/unity_algorithm.h` line 39 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX5DHJDKul42gzJrcx:-NrgKu705zDVO86Qe4hT:bwjttkq) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/include/compiler/unity_algorithm.h#L39)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not? Usually that's an indicator that you shouldn't actually be using `visitable`
</blockquote></details>

Tracked in a new issue
___
*[`lib/compiler/include/compiler/unity_algorithm.h` line 14 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NqjZrSI1kvljyil2LkV:-NrgKIRgBI3_Ahme0Z9f:bwjttkq) ([raw file](https://github.com/flexflow/FlexFlow/blob/95fa427b8680e68acf33cccf96bbc66bb37cd1fa/lib/compiler/include/compiler/unity_algorithm.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why put `runtime` as an object on `Strategy` rather than having an `unordered_map` somewhere from pairs of `ParallelComputationGraph` and `MachineMapping` to `runtime`?
</blockquote></details>

Tracked in a new issue
___
*[`lib/compiler/src/graph_utils.cc` line 15 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX9nQmAsR22ZFk2PaA:-NrgKvV7DYEFgqmCVsJQ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/graph_utils.cc#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are we changing the graph in the algorithm? If you're referring to applying substitutions, then it seems like materializing the graph should instead be handled there and not here?

Also, the need to pass all those template arguments to me suggests that the interface actually is to complex, as there generally should not be like 5 different template parameters that all have effects that don't have reasonable defaults that can be inferred
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 48 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX5V8qAWtKZcOXXCjX:-NrgL4vd4gW8KxPI2YY6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L48)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is this issue?
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 137 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX6hqO0ruGWj4be2aR:-NrAwCnA9MuYQNnWTLa2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L137)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you put this comment into the "Working" state on your side? That keeps it from going away but makes it not blocked on me. In general when the response is "will do, but am waiting on some other issue", put the discussion in the "Working" state. If you're not sure how to do this, see https://docs.reviewable.io/discussions.html#checking-and-changing-dispositions
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 215 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX7lwd2q96mcORyrmL:-NrgLNYo-b_0ADLlX8zQ:b-k36kma) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L215)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I appreciate the stateless design here (i.e., passing all of the algorithm state in the form of `resource`, `allowed_machine_views`, `cached_subgraph_costs`, etc. but here I think it's making things hard to read/understand. Can we separate the implementation here into a stateless layer (where most of the individual code is) and then add a stateful layer on top for readability? 

Also, since this is all stateless I'm a little confused why there is a class here (i.e., `OptimalCost`)--if this is just to handle `visit` let's move the `visit` invocation into a separate function so the details of how all variant dispatch are separate from the actual algorithm.
</blockquote></details>

How about the new version?
___
*[`lib/compiler/src/machine_mapping.cc` line  at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX8zrl0oBy5ZO3T--s:-NrgKxRn53pTN2mJhCuC:b-vdp0ik) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Overall the readability of the algorithm here (while much better than the old version) still needs a bit of work. The key thing is all the argument passing obscures what's actually going on
</blockquote></details>

I have refined it a little bit. How about the current version?
___
*[`lib/compiler/src/machine_mapping.cc` line 100 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NqjadNd2RcWtwUNidqF:-NrgLA7LDgcV7Ny76nzc:bwjttkq) ([raw file](https://github.com/flexflow/FlexFlow/blob/95fa427b8680e68acf33cccf96bbc66bb37cd1fa/lib/compiler/src/machine_mapping.cc#L100)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It's not entirely clear to me what this function is doing. Why is the cost just the sum of the cost of the pieces? Where is parallelism taken into account?
</blockquote></details>

Tracked in a new issue
___
*[`lib/compiler/src/unity_algorithm.cc` line 13 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXA8r0841AHwk_xmDU:-NrCavbXBlnr1VompFqh:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In that case, maybe rename to `get_all_applicable_substitutions`? I think the clarity is worth the extra typing
</blockquote></details>

Done.
___
*[`lib/compiler/src/unity_algorithm.cc` line 46 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXAVjl93l3Empuvhfk:-NrgLQuJANUp86Z9K5SG:bwjttkq) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In that case why is the PCG part of `Strategy`?
</blockquote></details>

Tracked in a new issue
___
*[`lib/compiler/src/unity_algorithm.cc` line 51 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXAjkl6emRLKpubBVG:-NrCb6286RwFYLgC1t6E:b-iwgzc3) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L51)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Refactoring needs to be done here to reduce the amount of nesting--if we're hitting tripluy-nested for loops something has gone wrong. Overall the functions in this PR could do with some dividing-up.
</blockquote></details>

I agree that this piece of codes needs more clarification, but I don't think nested loops are a problem, since it can explicitly show the complexity of the algorithm.
___
*[`lib/compiler/src/unity_algorithm.cc` line 59 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXBXXY1mQjG45rwRjr:-NrgMML7E8hJklPXK2DN:bwjttkq) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/unity_algorithm.cc#L59)):*
<details><summary><i>Pr [...]

2024-02-28 00:42 UTC, wmdi reviewed
> Reviewed 16 of 16 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 59 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-02-28 01:15 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 59 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/graph/algorithms.cc` line 167 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXItoU-QaY9nt13tIl:-Nrh9UnRB2OBXJPZm8ut:bpdwklw) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/algorithms.cc#L167)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In that case let's write that function now
</blockquote></details>

I don't see where we need such a check...
___
*[`lib/utils/src/graph/open_graphs.cc` line 25 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHhF5C3MhAd5xT5ET:-NrhGTiy9VqR20iVcL-e:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/open_graphs.cc#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/open_graphs.cc` line 59 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHhmh9Ye27g9dXogm:-NrhGU5cECWbGTnkrCDB:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/open_graphs.cc#L59)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/open_graphs.cc` line 80 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHiEHCtcI9cUEAQji:-NrhGUSZAGref60B0FJl:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/open_graphs.cc#L80)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/open_graphs.cc` line 110 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHihbAldaknd3bDpj:-NrhGUoCDXccdSfNzMzS:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/open_graphs.cc#L110)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/open_graphs.cc` line 115 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHj2A1jywtQ_qqPvl:-NrhGV9sCKeBCeqdb88D:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/open_graphs.cc#L115)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/open_graphs.cc` line 132 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHn_M1qO5fGshe5zP:-NrhGVXI2syoPSpjd8wr:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/open_graphs.cc#L132)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/open_graphs.cc` line 168 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHo2T-RBY_XPYwOzz:-NrhGVnzD2hN-jqYkyKJ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/open_graphs.cc#L168)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/views.cc` line 473 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NqjeYtr1EM2avEtGycu:-NrhGjat2RelBz99bYUF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/95fa427b8680e68acf33cccf96bbc66bb37cd1fa/lib/utils/src/graph/views.cc#L473)):*
> ```cpp
>     OpenMultiDiGraphView const &g, std::unordered_set<Node> const &nodes)
>     : g(g), nodes(nodes) {
>   inputs = transform(get_cut_set(g, nodes), to_inputmultidiedge);
> ```

Done.
___
*[`lib/utils/src/graph/digraph.cc` line 17 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHb6r1bwgm4ud_naB:-NrhGuLAA17XmARm4fBi:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/digraph.cc#L17)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpret`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/digraph.cc` line 50 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHc7j3W5hZWEsYio5:-NrhGufhEyQoEBsMkyYF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/digraph.cc#L50)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/digraph.cc` line 54 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHeED7aMAykkm4eSR:-NrhGv1u-f1GgS-hmDvu:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/digraph.cc#L54)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/multidigraph.cc` line 27 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHf5dCj5N32InwuRW:-NrhGvXR1UMJs2Uzb4Tn:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/multidigraph.cc#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/multidigraph.cc` line 69 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHfRv4p2VCu01JaB4:-NrhGvqk4AKKQxhBB_B6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/multidigraph.cc#L69)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/multidigraph.cc` line 73 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHfm_0Uh2dKhWK59L:-NrhGw6wELRd8EKzN0Qr:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/multidigraph.cc#L73)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/node.cc` line 56 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHgOwEHCrawCJmmuM:-NrhGwTZ1X5soH3QdUGh:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/node.cc#L56)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/node.cc` line 60 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHgeqBucgzy0A1aHy:-NrhGwjTCaUcYkV3vZHn:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/node.cc#L60)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`reinterpet`
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/undirected.cc` line 29 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHqcH6tHwVc3EkQvy:-NrhGxIdARMg4h6ipPTu:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/undirected.cc#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><b [...]

2024-02-28 04:58 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 59 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/graph/views.cc` line 486 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXID6K2w4xFifqTCIK:-Nri3y7p8TQNPPBZsY6r:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/views.cc#L486)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

See https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXIBGU11sbI_OAUfTb
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/views.cc` line 508 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXIBGU11sbI_OAUfTb:-Nri2_oi87xxWl926rpy:bfogak1) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/views.cc#L508)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Makes sense. In that case let's instead do an explicit cast on the right-hand side or modify `set_union` to allow it to take arguments of different types that can be made the same via a static cast
</blockquote></details>

I am just wondering why not just use `extend`. I think it is straightforward and performant. Especially in algorithm implementation, it explicitly shows the execution time linear to the edge size.
___
*[`lib/utils/src/graph/views.cc` line 499 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-Nqjefey9ZAhlu0sWjBv:-Nri1tQ34tQIPAmvKSeB:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/95fa427b8680e68acf33cccf96bbc66bb37cd1fa/lib/utils/src/graph/views.cc#L499)):*
> ```cpp
>     OpenMultiDiGraphView const &g, std::unordered_set<Node> const &nodes)
>     : g(g), nodes(nodes) {
>   outputs = transform(get_cut_set(g, nodes), to_outputmultidiedge);
> ```

Done.
___
*[`deps/fmt` line 1 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NmreZoB4GMLLfwGWNf0:-Nri3sVB0Uyuj9JuIU8h:b-fddfb6) ([raw file](https://github.com/flexflow/FlexFlow/blob/6211b84e84a8ba471783d7b7c4f6854b4d59c884/deps/fmt#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Revert this change?
</blockquote></details>

Which commit should we use?


<!-- Sent from Reviewable.io -->

2024-02-28 20:10 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: 151 of 157 files reviewed, 59 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/graph/algorithms.cc` line 354 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXJ0N80zRUtmX50p5E:-NrlKiqfDlzOhby--bsj:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/algorithms.cc#L354)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

And then refactor these cases to use the new function
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-28 20:10 UTC, wmdi reviewed
> Reviewed 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 59 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-02-29 01:57 UTC, wmdi reviewed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 59 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-03-12 17:00 UTC, wmdi reviewed
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 59 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-03-12 17:02 UTC, wmdi reviewed
The new issue to track the improvements to do is #1315 . It currently tracks all the remaining todos, and is planed to be further split into separate issues.

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-:-NsnaxnLAM43EZkuA191:b-yerkt0)* status: all files reviewed, 59 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-03-14 00:59 UTC, wmdi reviewed
> Reviewed 11 of 11 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 59 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-03-15 00:00 UTC, lockshaw requested changes
> Reviewed 5 of 10 files at r10, 14 of 16 files at r11, 3 of 6 files at r12, 2 of 2 files at r13, 3 of 3 files at r14, 11 of 11 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 4 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/src/machine_mapping.cc` line  at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpX8zrl0oBy5ZO3T--s:-NszNvbcEMhceIRBh9YP:bxf1y3o) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/src/machine_mapping.cc#L)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I have refined it a little bit. How about the current version?
</blockquote></details>

I think it's a step in the right direction. There's probably more that can be done, but rather than programming-by-proxy through you I think it makes sense to merge this and iterate from there :slightly_smiling_face: 
___
*[`lib/compiler/test/src/test_labelled_open_graph.cc` line 59 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXCPQE9KCHCXa2DLPb:-Nsz3-Kx7GFCmb-5S5Xj:b-xyailv) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/compiler/test/src/test_labelled_open_graph.cc#L59)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Graphs are not formatable
</blockquote></details>

We'll keep this for now, tracking in #1322 
___
*[`lib/pcg/include/pcg/parallel_computation_graph.h` line 18 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXEBF10ro1Ooo4N9Kp:-NszONBa2WJMU9FGqjlu:bb875u3) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/pcg/include/pcg/parallel_computation_graph.h#L18)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

We may want different types of hash functions for graphs in different applications. For example, we may or may not want two graphs to be the same after relabelling. In this case, I think it is better to leave the hash functions customized.
</blockquote></details>

But the equality operation here is just falling back to the hash function, so clearly there's an implicit usage here. I think we should define the strictest hash function by default here, and then other hash functions can be used as desired but are not the default.
___
*[`lib/utils/include/utils/graph/labelled/views.h` line 99 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXIUFF161EZ4SUsKim:-NszOhsR8NjTq931z6_V:b-10rxkb) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/include/utils/graph/labelled/views.h#L99)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I think the implementation is different
</blockquote></details>

Yes, but that isn't that the whole point of overloading? If you don't think it makes sense to address this in this PR that's fine with me, but in that case can you create a detailed issue with why you think this can't be done as well as a link to this discussion?
___
*[`lib/utils/src/graph/open_graphs.cc` line 25 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHhF5C3MhAd5xT5ET:-Nsz5AzQ25wSiPzxBbsn:b-8duy1w) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/open_graphs.cc#L25)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still seems to be dynamic?
___
*[`lib/utils/src/graph/views.cc` line 508 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXIBGU11sbI_OAUfTb:-Nsz6AT8-ZZzNfmt3vEn:by27fw5) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/views.cc#L508)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I am just wondering why not just use `extend`. I think it is straightforward and performant. Especially in algorithm implementation, it explicitly shows the execution time linear to the edge size.
</blockquote></details>

Mainly to avoid mutability (and `set_union` here seems to better match what you're trying to do rather than extending some existing data structure), but clearly this is a minor case so it's not a big deal.


<!-- Sent from Reviewable.io -->

2024-03-15 00:19 UTC, wmdi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 3 unresolved discussions (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2024-03-15 05:29 UTC, wmdi reviewed
> Reviewed 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 3 unresolved discussions (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2024-03-21 01:16 UTC, wmdi reviewed
> Reviewed 22 of 22 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 3 unresolved discussions (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2024-03-21 01:17 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/graph/labelled/views.h` line 99 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXIUFF161EZ4SUsKim:-NtT_L5U9sX0u3W7Q-Te:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/include/utils/graph/labelled/views.h#L99)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yes, but that isn't that the whole point of overloading? If you don't think it makes sense to address this in this PR that's fine with me, but in that case can you create a detailed issue with why you think this can't be done as well as a link to this discussion?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-23 19:51 UTC, wmdi reviewed
> Reviewed 68 of 68 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-03-23 19:52 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw)

___
*[`lib/pcg/include/pcg/parallel_computation_graph.h` line 18 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXEBF10ro1Ooo4N9Kp:-NtgrhQQ0dofdd4FVGjf:bf9l2cs) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/pcg/include/pcg/parallel_computation_graph.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

But the equality operation here is just falling back to the hash function, so clearly there's an implicit usage here. I think we should define the strictest hash function by default here, and then other hash functions can be used as desired but are not the default.
</blockquote></details>

Tracked in #1329  


<!-- Sent from Reviewable.io -->

2024-03-23 19:52 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/src/graph/open_graphs.cc` line 25 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1229#-NpXHhF5C3MhAd5xT5ET:-NtgroJs6ukPE9sNtaJS:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/0c45f61f114414215c5eff7d39006f07735e2fe7/lib/utils/src/graph/open_graphs.cc#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Still seems to be dynamic?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-24 20:15 UTC, wmdi reviewed
> Reviewed 10 of 10 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-03-25 01:16 UTC, wmdi reviewed
> Reviewed 23 of 23 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-03-26 23:40 UTC, lockshaw approved these changes
> Reviewed 10 of 22 files at r17, 38 of 68 files at r18, 10 of 10 files at r19, 20 of 23 files at r20, 27 of 27 files at r21, 4 of 4 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2024-03-26 23:54 UTC, lockshaw approved these changes
> Reviewed 12 of 12 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1229)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2024-03-26 23:54 UTC, merged