Local Execution
flexflow/FlexFlow pull request #1305
Opened 2024-02-20 16:53 UTC by reyna-abhyankar

**Description of changes:**

Implement local execution 

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

TODO
- [ ] synchronize graph and signature representation 
- [ ] local task argument accessor
- [ ] port over/fix task spec code from #1097 
- [ ] reorganize repo to be able to build operators, kernels, and local execution without legion
- [ ] new plantuml diagram that matches the interface

2024-02-27 11:37 UTC, lockshaw requested changes
I'm guessing this currently does not build. Now that's it's pulled out into a separate library it would be nice to prioritize that as well as add the build into CI to help push the code towards being mergeable.

Also, it would be nice to start adding some tests not aiming at full coverage, but just as documentation of how you're envisioning some of the APIs here being used (essentially as machine-checkable documentation)

> Reviewed 137 of 137 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-:-NreLK0s9i0DJHWntZVP:bsh62t5)* status: all files reviewed, 67 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/CMakeLists.txt` line 3 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre4KKU1oZR-cOc_xPb:-Nre4KKV-4hnTKUGpFIm:b8lflzf) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/CMakeLists.txt#L3)):*
> ```CMake
> add_subdirectory(pcg)
> add_subdirectory(compiler)
> add_subdirectory(execution)
> ```

Might be better renamed "local-execution"--"execution" by itself is a bit vague



_Code quote:_
```CMake
execution
```
___
*[`lib/README.md` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre4Xbk1ZlV8XaM7LZD:-Nre4Xbk1ZlV8XaM7LZE:b-vktlh3) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/README.md#L8)):*
> ```Markdown
> - `kernels`:
> - `op-attrs`:
> - `execution`:
> ```

Might be worth adding a quick summary of what the library does, especially as this one is a bit less trivial than some of the others



_Code quote:_
```Markdown
- `execution`:
```
___
*[`lib/execution/CMakeLists.txt` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre4hcJBJ_HQnDJx7qU:-Nre4hcJBJ_HQnDJx7qV:b-7fh320) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/CMakeLists.txt#L13)):*
> ```CMake
>     op-attrs
>     utils
>     optional
> ```

Use `std::optional` instead and remove the `optional` dependency
___
*[`lib/execution/CMakeLists.txt` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre4eFJBCZbRaByOJf2:-Nre4eFJBCZbRaByOJf3:buqdwcu) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/CMakeLists.txt#L14)):*
> ```CMake
>     utils
>     optional
>     compiler
> ```

Why does this need compiler?
___
*[`lib/execution/include/local_execution/local_allocator.h` line 11 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre5uyf9_jZPqmngXhO:-Nre5uyf9_jZPqmngXhP:bqfq8pi) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_allocator.h#L11)):*
> ```objc
> 
> struct LocalAllocator : public IAllocator {
>   LocalAllocator(size_t);
> ```

Worth including a parameter name here since it's not clear what this actually does.



_Suggestion:_
```objc
 LocalAllocator(size_t ?????);
```
___
*[`lib/execution/include/local_execution/local_allocator.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre5jx54shlzziTzMkX:-Nre5jx54shlzziTzMkY:brnf4i3) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_allocator.h#L14)):*
> ```objc
>   ~LocalAllocator() override;
> 
>   void *allocate(Tensor) override;
> ```

The code to calculate the memory size needed for a tensor is shared between allocators, so it seems worth making this the interface rather than forcing each allocator to compute the size itself



_Suggestion:_
```objc
  void *allocate(size_t) override;
```
___
*[`lib/execution/include/local_execution/local_allocator.h` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre61pt88Sp_P3nnHf9:-Nre61pt88Sp_P3nnHfA:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_allocator.h#L16)):*
> ```objc
>   void *allocate(Tensor) override;
>   void deallocate(void *) override;
>   size_t get_ptr_memory_size(void *);
> ```

Why?
___
*[`lib/execution/include/local_execution/local_allocator.h` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre65mP6jWCe8tJ52Tm:-Nre65mP6jWCe8tJ52Tn:b1ow0y0) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_allocator.h#L21)):*
> ```objc
>   size_t total_memory_size;
>   size_t allocated_memory_size;
>   std::unordered_map<void *, size_t> ptr_memory_size_mapping;
> ```

Why? Isn't this already handled by `cudaMalloc`?
___
*[`lib/execution/include/local_execution/local_allocator.h` line 22 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre4qoV3ythzGZ0gZeb:-Nre4qoV3ythzGZ0gZec:bghbyb1) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_allocator.h#L22)):*
> ```objc
>   size_t allocated_memory_size;
>   std::unordered_map<void *, size_t> ptr_memory_size_mapping;
> };
> ```

Add `CHECK_RC_COPY_VIRTUAL_COMPLIANT(LocalAllocator);`. This checks the conditions in https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-copy-virtual
___
*[`lib/execution/include/local_execution/local_model_training_instance.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre6dEQ5s4IWx6rYnYR:-Nre6dEQ5s4IWx6rYnYS:b7jdjbj) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_model_training_instance.h#L14)):*
> ```objc
> namespace FlexFlow {
> 
> struct LocalModelTrainingInstance {
> ```

Maybe worth splitting out a `TrainingInstance` to remove duplication between `LocalModelTrainingInstance` and `ModelTrainingInstance` (or whatever it is called now if you changed its name)
___
*[`lib/execution/include/local_execution/local_model_training_instance.h` line 34 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre6LeR4js_RqBvXcOF:-Nre6LeR4js_RqBvXcOG:b15la02) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_model_training_instance.h#L34)):*
> ```objc
>                     local_training_backing);
> 
> void initialize_backing(LocalModelTrainingInstance &);
> ```

See https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/



_Suggestion:_
```objc
LocalModelTrainingInstance initialize_backing(ComputationGraph const &, Optimizer const &, etc.);
```
___
*[`lib/execution/include/local_execution/local_task_argument_accessor.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre7BKWBiIoW4Lbp64v:-Nre7BKWBiIoW4Lbp64w:b39crxg) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_task_argument_accessor.h#L15)):*
> ```objc
> 
>   template <typename T>
>   T const &get_argument(slot_id) const;
> ```

Same for all methods here I think



_Suggestion:_
```objc
  template <typename T>
  T const &get_argument(slot_id) const override;
```
___
*[`lib/execution/include/local_execution/local_task_argument_accessor.h` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre71cu39K0tEZRtQC8:-Nre71cu39K0tEZRtQC9:by8rmrm) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_task_argument_accessor.h#L37)):*
> ```objc
> private:
>   Allocator allocator;
>   std::unordered_map<std::pair<slot_id, IsGrad>, GenericTensorAccessorW> tensor_backing_map;
> ```

Pull out into a separate struct that has a name. Raw `pair`s, `variant`s, etc. tend to be confusing as it's not clear what they do.



_Code quote:_
```objc
std::pair<slot_id, IsGrad>
```
___
*[`l [...]

2024-02-27 23:16 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1305)* status: 112 of 144 files reviewed, 67 unresolved discussions (waiting on @lockshaw)

___
*[`lib/README.md` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre4Xbk1ZlV8XaM7LZD:-NrgSWs00EwMdIJRzyQu:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/README.md#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be worth adding a quick summary of what the library does, especially as this one is a bit less trivial than some of the others
</blockquote></details>

Done.
___
*[`lib/execution/CMakeLists.txt` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre4hcJBJ_HQnDJx7qU:-NrgShS750lREmsDieJp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/CMakeLists.txt#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use `std::optional` instead and remove the `optional` dependency
</blockquote></details>

Done.
___
*[`lib/execution/CMakeLists.txt` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre4eFJBCZbRaByOJf2:-NrgSsLB6wZP63mq6xPQ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/CMakeLists.txt#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does this need compiler?
</blockquote></details>

Done.
___
*[`lib/execution/include/local_execution/local_allocator.h` line 22 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre4qoV3ythzGZ0gZeb:-NrgTRyJ-7uB34fe54fC:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_allocator.h#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add `CHECK_RC_COPY_VIRTUAL_COMPLIANT(LocalAllocator);`. This checks the conditions in https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-copy-virtual
</blockquote></details>

Done.
___
*[`lib/execution/include/local_execution/local_task_argument_accessor.h` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre71cu39K0tEZRtQC8:-NrgZKZd7Bns6zy1Nhre:b-ckmihu) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_task_argument_accessor.h#L37)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull out into a separate struct that has a name. Raw `pair`s, `variant`s, etc. tend to be confusing as it's not clear what they do.
</blockquote></details>

Why not just `using SlotGradId = std::pair<slot_id, IsGrad>`?
___
*[`lib/execution/include/local_execution/local_task_argument_accessor.h` line 44 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre6rzi9rMTNpCD_31O:-NrgZSfy4DGpWDVnfsxi:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_task_argument_accessor.h#L44)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

CHECK_RC_COPY_VIRTUAL_COMPLIANT
</blockquote></details>

Done.
___
*[`lib/execution/include/local_execution/local_training_backing.h` line 28 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre7XvoEUPxb7GOBtCv:-Nrg_QvA1SMix5H8MXt-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_training_backing.h#L28)):*
> ```objc
> 
> struct LocalTrainingBacking {
>   LocalTrainingBacking(ComputationGraph, Allocator, std::unordered_map<OperatorSlotBackingId, GenericTensorAccessorW>);
> ```

Done.
___
*[`lib/execution/include/local_execution/local_training_backing.h` line 35 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre8Ye_Bop9v-AST_by:-Nrg_faL4tEH9bqUd-Gg:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_training_backing.h#L35)):*
> ```objc
>   void execute_update();
> 
>   LocalTaskArgumentAccessor get_fwd_accessor(OpTaskInvocation);
> ```

Done.
___
*[`lib/execution/include/local_execution/local_training_backing.h` line 36 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre8a3f1hcEDDmpkXX9:-Nrg_gFDDs1D6WUeFkzt:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_training_backing.h#L36)):*
> ```objc
> 
>   LocalTaskArgumentAccessor get_fwd_accessor(OpTaskInvocation);
>   LocalTaskArgumentAccessor get_bwd_accessor(OpTaskInvocation);
> ```

Done.
___
*[`lib/execution/include/local_execution/local_training_backing.h` line 43 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre8Lqm932riKoYeCpB:-Nrg_kyV5BxpFmOaNV-n:b-pt1vlv) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_training_backing.h#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What's happening with args (i.e., not tensors)?
</blockquote></details>

Yeah, have to add that based on our discussion yesterday.
___
*[`lib/execution/include/local_execution/task_argument_accessor.h` line 12 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreIQsrCijEV-1BvRN1:-Nrga5ZQAQ1eA_zW4C8D:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/task_argument_accessor.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

We have `std::variant` now that we're on C++17
</blockquote></details>

Done.
___
*[`lib/execution/src/task_spec/op_task_signature.cc` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreJpT98IJSa81YjReo:-NrgbAJx-Z-_6N_X3h7G:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/src/task_spec/op_task_signature.cc#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I like to do this to signify that this is just a composite of these values, rather than some object that might be doing nontrivial things in a constructor.
</blockquote></details>

Done.
___
*[`lib/execution/src/task_spec/local_backing/local_task_argument_accessor.cc` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreF3EVD1zltwjGIwPi:-NrgcceCB25zBG8Wn5S5:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/src/task_spec/local_backing/local_task_argument_accessor.cc#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Semicolons?
</blockquote></details>

Done.
___
*[`lib/execution/src/task_spec/local_backing/local_task_argument_accessor.cc` line 38 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreFGsa2-QNCXRgy3vs:-Nrgcu8h81_mvFZgZAW3:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/src/task_spec/local_backing/local_task_argument_accessor.cc#L38)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is this syntax?
</blockquote></details>

Done.
___
*[`lib/execution/src/task_spec/local_backing/local_training_backing.cc` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreFPzZBvqmnNvqX-JE:-NrgcyvXA85DEPPd-WOV:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/src/task_spec/local_b [...]

2024-02-27 23:23 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1305)* status: 112 of 144 files reviewed, 67 unresolved discussions (waiting on @lockshaw)

___
*[`lib/execution/include/local_execution/local_allocator.h` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre61pt88Sp_P3nnHf9:-Nrgs4st8nc8QxjOPO-b:bujgq2k) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_allocator.h#L16)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Yeah, I don't think this is needed. I wrote the allocator first and just added that as an API in case but didn't end up using it.
___
*[`lib/execution/include/local_execution/local_allocator.h` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre65mP6jWCe8tJ52Tm:-NrgsC1k3nzZC0LEZSl_:b-cv46f8) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_allocator.h#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why? Isn't this already handled by `cudaMalloc`?
</blockquote></details>

Yeah, I don't think this is needed. 


<!-- Sent from Reviewable.io -->

2024-02-28 16:56 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1305)* status: 112 of 144 files reviewed, 67 unresolved discussions (waiting on @lockshaw)

___
*[`lib/execution/include/local_execution/local_model_training_instance.h` line 34 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre6LeR4js_RqBvXcOF:-Nrkcbh4AZV-8p3bqLJG:b-7m53ie) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_model_training_instance.h#L34)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

See https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/
</blockquote></details>

This is a good paradigm. But I'm not connecting the dots for this example. Wouldn't we have already initialized `LocalModelTrainingInstance` before calling this function? That's what is expected for `forward`, `backward`, and `update`. 

Actually, in that case shouldn't we do `LocalModelTrainingInstance::forward()` instead of `forward(LocalModelTrainingInstance)`?


<!-- Sent from Reviewable.io -->

2024-03-01 20:58 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1305)* status: 112 of 145 files reviewed, 67 unresolved discussions (waiting on @lockshaw)

___
*[`lib/CMakeLists.txt` line 3 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre4KKU1oZR-cOc_xPb:-NrvTXUgDZBdUbycVnwo:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/CMakeLists.txt#L3)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be better renamed "local-execution"--"execution" by itself is a bit vague
</blockquote></details>

Done.
___
*[`lib/execution/include/local_execution/local_allocator.h` line 11 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre5uyf9_jZPqmngXhO:-NrvTiOc1Ja1YzImsHIK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_allocator.h#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Worth including a parameter name here since it's not clear what this actually does.
</blockquote></details>

Done.
___
*[`lib/execution/include/local_execution/local_allocator.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre5jx54shlzziTzMkX:-NrvTrB09x5nJx9I925b:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_allocator.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The code to calculate the memory size needed for a tensor is shared between allocators, so it seems worth making this the interface rather than forcing each allocator to compute the size itself
</blockquote></details>

Done.
___
*[`lib/execution/include/local_execution/local_model_training_instance.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre6dEQ5s4IWx6rYnYR:-NrvVHgE1CDqKfTDrV0J:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_model_training_instance.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Maybe worth splitting out a `TrainingInstance` to remove duplication between `LocalModelTrainingInstance` and `ModelTrainingInstance` (or whatever it is called now if you changed its name)
</blockquote></details>

Done.
___
*[`lib/execution/include/local_execution/local_task_argument_accessor.h` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre7BKWBiIoW4Lbp64v:-NrvYVqv1aZVP88VxzZT:by7gb79) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_task_argument_accessor.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Same for all methods here I think
</blockquote></details>

I think to have this kind of polymorphism we need to have a variant that holds all argument types. 2 reasons: 
1. C++ doesn't allow virtual template functions
2. Having a map like below doesn't make sense because we'd need to then have `LocalTaskArgumentAccessor<T>` for a particular argument type which doesn't work. 
The variant solution (while it kind of seems like hard-coding) will fix this, and I think since arguments broadly fall into 2-3 categories, this is fine. (I think `RuntimeArgRefSpec` or `OpArgRefSpec` already  does some of this)



_Code snippet:_
```objc
template <typename T>
std::unordered_map<slot_id, T> argument_map;
```
___
*[`lib/execution/include/local_execution/local_training_backing.h` line 40 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre7gi34ZG5WbSf8vOw:-Nrv_tKyAQOOiTxD-ZjR:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_training_backing.h#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just use the `ComputationGraph` you already have until we actually learn the performance is that important.
</blockquote></details>

Done.
___
*[`lib/execution/include/local_execution/local_training_backing.h` line 50 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre7yUz3ESrvnx3JQnp:-NrvbA1tA121sBlzoPuo:bxpvq8j) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_training_backing.h#L50)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably worth pulling out into a separate struct that's responsible for the internals of task registration to avoid `LocalTrainingBacking` from becoming monolithic and unwieldy
</blockquote></details>

I've simplified these maps down, may pull more out.
___
*[`lib/execution/src/task_spec/local_backing/local_allocator.cc` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreEQmM6_1pLx_6KbbT:-Nrvj7629TpVZZaiRMJQ:b-k07qje) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/src/task_spec/local_backing/local_allocator.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why track allocated memory in `LocalAllocator`? Might be worth instead having a separate `IAllocator` implementation that wraps an `IAllocator` with this functionality instead
</blockquote></details>

Sure, i've lined down `LocalAllocator` accordingly to not need memory tracking and purely allocate/deallocate.
___
*[`lib/execution/src/task_spec/local_backing/local_allocator.cc` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreEB9z92y4u1BkWN1f:-NrvhfLTEN2-1k4vrGDO:b-uckexj) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/src/task_spec/local_backing/local_allocator.cc#L37)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was this chosen over not owning all of the memory regions (i.e., whoever uses them is responsible for deleting them)? No strong opinion, just curious
</blockquote></details>

What would the alternative be? My take is that once `LocalAllocator` goes out of scope, it should de-allocate all the memory it allocated, but perhaps `deallocate` can be private. What do you think?
___
*[`lib/execution/src/task_spec/local_backing/local_model_training_instance.cc` line 16 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreEjp_CBCC_nsGRZC7:-NrvjqbdAgoRnnRZ7G_j:bv03izj) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/src/task_spec/local_backing/local_model_training_instance.cc#L16)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why return this over having the `LocalModelTrainingInstance` just write out to an externally-provided tensor that's encoded when the instance is created?
</blockquote></details>

Yeah, I'm changing this to what you said. 
___
*[`lib/execution/src/task_spec/local_backing/local_training_backing.cc` line 55 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreI9dy8rVOZHftsJk2:-NrvkUCD82khH3zFSBCH:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/src/task_spec/local_backing/local_training_backing.cc#L55)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

move toinitialization list?
</blockquote></details>

Done.
___
*[`lib/execution/src/task_spec/local_backing/local_training_backing.cc` line 64 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreGl1703dwapmT9QSW:-NrvkjtS2AieoCkxqCIF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8a [...]

2024-04-11 01:41 UTC, lockshaw reviewed
There seem to be a lot of stray commented-out code throughout this PR--it would be nice to try to clean up some of that before this is merged.

Also, try to use more specific and clear names--a lot of the names (e.g., `tensor_mapping`) provide essentially no information, making the code way more challenging to read than it needs to be. Decomposing functions, even in instances where the functions are only called from that one location, can also be helpful for this reason--it bundles up pieces of functionality into nice named pieces that I can understand without having to wade through their implementation details

Also, let's try to aim for slightly smaller PRs in the future slightly_smiling_face:--I know a lot of the changes were relatively simple, but it's still a lot of code to go through

> Reviewed 5 of 32 files at r2, 109 of 235 files at r4, 125 of 125 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-:-Nv9XJUf4oXhyfeaBpI5:b-cnwibn)* status: all files reviewed, 126 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/allocation.h` line 28 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nv9oDFx3hlY5fVw-7AT:-Nv9oDFx3hlY5fVw-7AU:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/kernels/include/kernels/allocation.h#L28)):*
> ```objc
>   }
> 
>   void deallocate(GenericTensorAccessorW tensor_backing) {
> ```





_Suggestion:_
```objc
  void deallocate(GenericTensorAccessorW const &tensor_backing)
```
___
*[`lib/kernels/include/kernels/flat_kernels.h` line 4 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NuvK6QK1u1W5h9JipBV:-NuvK6QLACMdapPpzYOj:bcgjvre) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/kernels/include/kernels/flat_kernels.h#L4)):*
> ```objc
> #define _FLEXFLOW_OPS_KERNELS_FLAT_KERNELS_H
> 
> #include "device.h"
> ```

Why this change?
___
*[`lib/kernels/include/kernels/layer_norm_kernels.h` line 10 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NuvKBcz4pQ6lkZ1VGFm:-NuvKBcz4pQ6lkZ1VGFn:bhofei7) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/kernels/include/kernels/layer_norm_kernels.h#L10)):*
> ```objc
> namespace FlexFlow {
> 
> // class LayerNormPerDeviceState : public PerDeviceOpState {
> ```

Delete?
___
*[`lib/kernels/include/kernels/reduce_kernels.h` line 37 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NuvKO7F5TZjjt2GfYb4:-NuvKO7F5TZjjt2GfYb5:bhofei7) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/kernels/include/kernels/reduce_kernels.h#L37)):*
> ```objc
>                                  ArrayShape output_shape);
> 
> // void forward_kernel_wrapper(ReducePerDeviceState const &m,
> ```

Delete?
___
*[`lib/kernels/include/kernels/reverse_kernels.h` line 8 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NuvKZZx6w6K9QYtGEVk:-NuvKZZx6w6K9QYtGEVl:bfm5lvi) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/kernels/include/kernels/reverse_kernels.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> using legion_coord_t = long long;
> ```

Just use the type directly--having a type named `legion_coord_t` in a part of the codebase without legion is just confusing
___
*[`lib/kernels/include/kernels/split_kernels.h` line 8 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NuvKk9xAUGV_ZTe4kei:-NuvKk9xAUGV_ZTe4kej:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/kernels/include/kernels/split_kernels.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> using legion_coord_t = long long;
> ```

Delete
___
*[`lib/kernels/include/kernels/transpose_kernels.h` line 11 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NuvKoSoEF8Nx5c6Qx-I:-NuvKoSoEF8Nx5c6Qx-J:b-bs8uxv) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/kernels/include/kernels/transpose_kernels.h#L11)):*
> ```objc
> struct TransposePerDeviceState {
>   int num_dim;
>   req<int> perm[MAX_TENSOR_DIM];
> ```

`vector`?
___
*[`lib/kernels/include/kernels/transpose_kernels.h` line 36 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NuvKwRT6HtSmbNdLboL:-NuvKwRT6HtSmbNdLboM:bhofei7) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/kernels/include/kernels/transpose_kernels.h#L36)):*
> ```objc
> // namespace Internal {
> 
> // void forward_kernel_wrapper(TransposePerDeviceState const &m,
> ```

Delete?
___
*[`lib/kernels/src/cuda/reverse_kernels.cu` line 20 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NuvP5d17nOsNsSx5v_V:-NuvP5d17nOsNsSx5v_W:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/kernels/src/cuda/reverse_kernels.cu#L20)):*
> ```Cuda
> namespace FlexFlow {
> // declare Legion names
> using legion_coord_t = long long;
> ```

Delete
___
*[`lib/local-execution/include/arg_backing.h` line 19 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NuvPcL-4834g2nTXxjc:-NuvPcL-4834g2nTXxjd:bgybbsv) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/local-execution/include/arg_backing.h#L19)):*
> ```objc
> using DeviceStates = std::variant<LinearPerDeviceState>;
> 
> struct OpArgBacking {
> ```

visitable?
___
*[`lib/local-execution/include/arg_backing.h` line 28 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NuvPYB4B3-U1AIcPMK4:-NuvPYB4B3-U1AIcPMK5:bu98v5l) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/local-execution/include/arg_backing.h#L28)):*
> ```objc
> };
> 
> using ArgBackingMapping = std::unordered_map<operator_guid_t, OpArgBacking>;
> ```

What's the purpose of `ArgBackingMapping` here?
___
*[`lib/local-execution/include/local_allocator.h` line 19 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nv9Tg-f-afAK84QDeUT:-Nv9Tg-f-afAK84QDeUU:ba0pgk8) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/local-execution/include/local_allocator.h#L19)):*
> ```objc
> 
> private:
>   std::unordered_set<void *> ptrs;
> ```

Why have a set of pointers?
___
*[`lib/local-execution/include/local_model_training_instance.h` line 14 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nv9TsGk429TJqctGh5P:-Nv9TsGk429TJqctGh5Q:b-5oqd9w) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/local-execution/include/local_model_training_instance.h#L14)):*
> ```objc
> namespace FlexFlow {
> 
> struct LocalModelTrainingInstance {
> ```

Turn into a visitable-style type without methods
___
*[`lib/local-execution/include/local_task_argument_accessor.h` line 14 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nv9UadVAts--7YPbt1i:-Nv9UadVAts--7YPbt1j:b-wie3pd) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/local-execution/include/local_task_argument_accessor.h#L14)):*
> ```objc
> 
> using SlotGradId = std::pair<slot_id, IsGrad>;
> using TensorBackingOption = std::variant<
> ```

Why a variant of maps instead of a map of variants?
___
*[`lib/local-execution/include/local_task_argument_accessor.h` line 14 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nv9UkoJ-5clv_3Q-SMe:-Nv9UkoJ-5clv_3Q-SMf:b88z62) ([raw file](https://github.com/flexflow/FlexFlow/blob/367fd6079280c18970d1e43647394cce5b7d0125/lib/local-execution/include/local_task_argument_accessor.h#L14)):*
> ```objc
> 
> using SlotGradId = std::pair<slot_id, IsGrad>;
> using TensorBackingOption = std::variant<
> ```

Also I think it's generally better to wrap `std::variant`s rather than just usi [...]

2024-04-11 02:05 UTC, lockshaw reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1305)* status: all files reviewed, 95 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/runtime/src/task_invocation_compilation.cc` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-NreCbwsABm-5BIVI193:-Nv9orzh0gNCAa9QA7PF:b-slvvs7) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/runtime/src/task_invocation_compilation.cc#L)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

So there were actually 2 files with the same name in different subfolders. This deleted one looks like a precursor to the newer file which is in `lib/execution/src/task_spec/task_invocation_compilation.cc` and has a bunch of Legion stuff. Let me know if that's correct (I haven't verified which one is actually older via commit history, so I'll do that if you can't immediately tell).
</blockquote></details>

I think they both need to exist--this is the one for the actual compilation to legion objects, which shouldn't be part of `local-execution` but is critical for `runtime`
___
*[`lib/execution/include/local_execution/local_model_training_instance.h` line 34 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre6LeR4js_RqBvXcOF:-Nv9pQhP2JmHMbQekw2c:b-imiw9r) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_model_training_instance.h#L34)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

This is a good paradigm. But I'm not connecting the dots for this example. Wouldn't we have already initialized `LocalModelTrainingInstance` before calling this function? That's what is expected for `forward`, `backward`, and `update`. 

Actually, in that case shouldn't we do `LocalModelTrainingInstance::forward()` instead of `forward(LocalModelTrainingInstance)`?
</blockquote></details>

I guess the question to answer is: if the lifetime of `LocalTrainingBacking` is different than the lifetime of `LocalModelTrainingInstance` (i.e., we create a `LocalModelTrainingInstance` and then only later do we actually initialize the backing), then should they be part of the same object? We generally try to avoid objects/structs having a whole bunch of state changes as that can't be tracked by the type system, and instead represent those state changes with different types so it can be checked by the type system (e.g., rather than having a `FFModel` which has to have a computation graph constructed, then legion initialized, then run, etc. we have a `ComputationGraph` object and a `LegionBacking` object that get created as you go along, so that if you have a `LegionBacking` you know for sure that legion has already been initialized) 
___
*[`lib/execution/include/local_execution/local_task_argument_accessor.h` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1305#-Nre71cu39K0tEZRtQC8:-Nv9qKyk47LP_kEADADl:b-lo2am8) ([raw file](https://github.com/flexflow/FlexFlow/blob/6fb8aa7ee3d10d4d75141e2468178b43e62fd808/lib/execution/include/local_execution/local_task_argument_accessor.h#L37)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why not just `using SlotGradId = std::pair<slot_id, IsGrad>`?
</blockquote></details>

Because that's just an alias--anywhere I am using `SlotGradId` I can instead use a `std::pair` directly (as is being done here) which means the types only make sense if I know what type a `SlotGradId` actually is (so the alias doesn't really have much of a point), and it leads to code that looks like `std::get<IsGrad>(my_slot_id)` rather than `my_slot_id.is_grad` which is often easier to read. It's less of an issue here because `pair`s are pretty small and you benefit from the fact that both of the elements have wrapper types that make their purpose quite clear, but this would definitely improve some other parts of the code where you don't have this advantage (I care about this occurence here a bit less for that reason)

It's a similar answer to "why provide `Node` when you could just return `int`?"--while `int` is sufficiently expressive, this expressiveness actually makes the code harder to read (it's why we don't just pass around everything as a `void *` :level_slider:) 


<!-- Sent from Reviewable.io -->

2024-05-23 01:07 UTC, closed without merging