pr for debugging kernel driver issues
flexflow/FlexFlow pull request #1384
Opened 2024-05-06 22:27 UTC by oOTigger

PR for debugging kernel-test driver issues. Currently running into a CUDA error 35 ([cudaErrorInsufficientDriver](https://docs.nvidia.com/cuda/archive/10.2/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038)) when trying to compile the following test in kernels/test. 

Running the code on Sapling cluster on GPU 4, and seeing issue after running proj cmake, proj build, and on proj test. 

The changes made to initializer_kernels, array_shape, and fmt.h were needed in order for other tests to compile.

2024-05-31 05:33 UTC, lockshaw requested changes
Can you update the PR description and title?

Overall the tests look okay, but they need two things: (1) use some of the higher level interfaces (I think `Allocator` already has a way of producing a `GenericTensorAccessor` for a given `ArrayShape`, though if not it should be added), and (2) pull out duplicate testing code--currently it's nearly impossible to read what the test functions are doing, because 90% of the code is the same "generate a random tensor" code over and over again, which should be pulled out into separate functions (`kernels-tests` can have helper functions and header files in it)

> Reviewed 8 of 13 files at r1, 23 of 31 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-:-NzC7Qqs7MoF2-CuJXAQ:bxpin6m)* status: 31 of 39 files reviewed, 28 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`.proj.toml` line 16 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC241e56M65NDghDkW:-NzC210RAKgHUY3ER8Xf:bdlmbdz) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/.proj.toml#L16)):*
> ```TOML
> 
> test_targets = [
>   "kernel-tests",
> ```

Make sure these changes don't get merged--the only change here should be _adding_ `kernel-tests` to the list of tests to run, not removing anything
___
*[`lib/CMakeLists.txt` line 9 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC2FnZ2WtwZ21N8dUs:-NzC2FnZ2WtwZ21N8dUt:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/CMakeLists.txt#L9)):*
> ```CMake
> add_subdirectory(ffi)
> add_subdirectory(substitutions)
> # add_subdirectory(local-execution)
> ```

Why?
___
*[`lib/kernels/CMakeLists.txt` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC2JcB1SiQXZkKSgOv:-NzC2JcB1SiQXZkKSgOw:b-73ow16) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/CMakeLists.txt#L11)):*
> ```CMake
>      src/*.cc
>      src/cuda/cuda_helper.cu
>      src/cuda/ops/cast_kernels.cu
> ```

I assume eventually this will get changed back to `src/cuda/ops/*.cu` once everything builds successfully?
___
*[`lib/kernels/include/kernels/concat_kernels.h` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC2TPL4FsyF0qCMGfk:-NzC2TPL4FsyF0qCMGfl:b-1fr2os) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/include/kernels/concat_kernels.h#L6)):*
> ```objc
> #include "device.h"
> #include "kernels/accessor.h"
> #include "kernels/concat_kernels.h"
> ```

Why does this file include itself?
___
*[`lib/kernels/include/kernels/cuda_helper.h` line 21 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC2aCe-j3Y_0fetuwZ:-NzC2aCe-j3Y_0fetuw_:bf8q7hs) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/include/kernels/cuda_helper.h#L21)):*
> ```objc
> 
> template <typename T>
> __global__ void apply_add_with_scale(T *data_ptr, T const *grad_ptr, size_t size, T scale);
> ```

This shouldn't be exposed by kernels, only the wrapped kernel functions for each operator should be exposed through the public headers
___
*[`lib/kernels/include/kernels/device.h` line 31 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC2misDt8Ezz4hgjK-:-NzC2misDt8Ezz4hgjK0:bcgjvre) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/include/kernels/device.h#L31)):*
> ```objc
> #if defined(FF_USE_CUDA) || defined(FF_USE_HIP_CUDA)
> typedef cudaStream_t ffStream_t;
> // cudaError_t get_legion_stream(cudaStream_t *stream);
> ```

Why this change?
___
*[`lib/kernels/include/kernels/softmax_kernels.h` line 22 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC2v1UBW20vjRjlO3D:-NzC2v1UBW20vjRjlO3E:b3j0okp) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/include/kernels/softmax_kernels.h#L22)):*
> ```objc
> 
> SoftmaxPerDeviceState init_kernel(PerDeviceFFHandle const &, int, 
>                                   int, int, int, int);
> ```

Add argument names
___
*[`lib/kernels/src/accessor.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3-UqAQqTE5_EaQKK:-NzC3-UqAQqTE5_EaQKL:b-xwghe0) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/accessor.cc#L6)):*
> ```cpp
> 
> int32_t *GenericTensorAccessorW::get_int32_ptr() const {
>   return get<DataType::INT32>();
> ```

Generally we prefer explicitly using `this` as it makes it clearer what is a method and what is a function



_Suggestion:_
```cpp
  return this->get<DataType::INT32>();
```
___
*[`lib/kernels/src/device.h` line 96 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3B_x-MtHs8eWIWXM:-NzC3B_x-MtHs8eWIWXN:b-vp64c0) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/device.h#L96)):*
> ```objc
> 
> // template <typename DT>
> // __global__ void apply_add_with_scale(DT *data_ptr,
> ```

Why commented out?
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 274 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3THM-IFOMx3dcQea:-NzC3THM-IFOMx3dcQeb:bxngf21) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/cuda_helper.cu#L274)):*
> ```Cuda
> }
> 
> template __global__ void
> ```

Can/should we move these manual instantiations over to use the stuff in `datatype_dispatch.h`?
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 294 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3egoEssVaDWrUuFK:-NzC3egoEssVaDWrUuFL:b-ar8rk1) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/cuda_helper.cu#L294)):*
> ```Cuda
>     add_kernel<int64_t>(int64_t *dst, int64_t const *src, size_t size);
> template __global__ void
>     add_kernel<bool>(bool *dst, bool const *src, unsigned long size);
> ```

Why do we need to add `bool`s? Is it just because `DatatypeDispatch` forces all of the instantiations?
___
*[`lib/kernels/src/cuda/ops/attention_kernels.cu` line 47 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3qETBRvGyv52t-WL:-NzC3qETBRvGyv52t-WM:bfzd5o6) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/ops/attention_kernels.cu#L47)):*
> ```Cuda
>   ffSeqDataDescriptor_t oDesc;
>   void *reserveSpace;
>   // void *dropoutStates; // NOT USED
> ```

Not even on `inference`/`master`? In that case they should be removed
___
*[`lib/kernels/src/cuda/ops/attention_kernels.cu` line 307 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC47rZBmKty-GDQ_OD:-NzC47rZBmKty-GDQ_OE:b6b0wmk) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/ops/attention_kernels.cu#L307)):*
> ```Cuda
> void cleanup_kernel(Allocator &allocator,
>                     MHAPerDeviceState const &device_state) {
>   /* Noticed that loWinIdx and hiWinIdx are not allocated on GPU? Should 
> ```

Where are they used? 
___
*[`lib/kernels/src/cuda/ops/cast_kernels.cu` line 61 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC4XpkB7xtjIckJCMF:-NzC4XpkB7xtjIckJCMG:bj5qys0) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/ops/cast_kernels.cu#L61)):*
> ```Cuda
> };
> 
> // void forward_kernel(PerDeviceFFHandle handle,
> ```

If these shouldn't be here, delete don't just comment out
___
*[`lib/kernels/test/CMakeLists.txt` line 3 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC4sdl89lJB5EAgIAo:-NzC4sdl89lJB5EAgIAp:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b6 [...]

2024-06-02 15:28 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 13 of 63 files reviewed, 28 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/CMakeLists.txt` line 9 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC2FnZ2WtwZ21N8dUs:-NzK_BOW4yDq47Z1vVQ3:b29r6cc) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/CMakeLists.txt#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

I think I copied over this CMakeList from a different branch before I actually had local-execution so I commented out in order to compile
___
*[`lib/kernels/CMakeLists.txt` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC2JcB1SiQXZkKSgOv:-NzOX51T-kp0LEGMX-Xv:b-wowo8n) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/CMakeLists.txt#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I assume eventually this will get changed back to `src/cuda/ops/*.cu` once everything builds successfully?
</blockquote></details>

Yeah, it's just `src/cuda/ops/*.cu` now 
___
*[`lib/kernels/include/kernels/device.h` line 31 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC2misDt8Ezz4hgjK-:-NzOX8qT1Us6UcVBIM9b:b-l3391y) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/include/kernels/device.h#L31)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

Was running into dependency issues, but forgot to uncomment => Fixed 
___
*[`lib/kernels/include/kernels/softmax_kernels.h` line 22 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC2v1UBW20vjRjlO3D:-NzKcEoX0UjR3jIsRV7v:b-8b11j9) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/include/kernels/softmax_kernels.h#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add argument names
</blockquote></details>

Added
___
*[`lib/kernels/src/accessor.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3-UqAQqTE5_EaQKK:-NzKcMb_Bqx00KlPgEGo:b-8b11j9) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/accessor.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Generally we prefer explicitly using `this` as it makes it clearer what is a method and what is a function
</blockquote></details>

Added
___
*[`lib/kernels/src/device.h` line 96 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3B_x-MtHs8eWIWXM:-NzKcfzVDJOeLSRV_Cj6:b-eh2tuj) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/device.h#L96)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why commented out?
</blockquote></details>

Fixed, forgot to uncomment 
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 294 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3egoEssVaDWrUuFK:-NzKctQDCr3kos_V2zmi:bqr7zr) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/cuda_helper.cu#L294)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why do we need to add `bool`s? Is it just because `DatatypeDispatch` forces all of the instantiations?
</blockquote></details>

Yeah, ran into compile issues without the bool
___
*[`lib/kernels/src/cuda/ops/attention_kernels.cu` line 47 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3qETBRvGyv52t-WL:-NzKeRkEAAYgqalz4Igt:b-czxprx) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/ops/attention_kernels.cu#L47)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not even on `inference`/`master`? In that case they should be removed
</blockquote></details>

I just don't see the dropOutState fields being used anywhere in the init kernel
___
*[`lib/kernels/src/cuda/ops/attention_kernels.cu` line 307 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC47rZBmKty-GDQ_OD:-NzOXJuyDZpPdYnklNKN:bd9vscs) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/ops/attention_kernels.cu#L307)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Where are they used?
</blockquote></details>

In init_kernel: 

// allocate memory for loWinIdx/hiWinIdx
  int *loWinIdx = (int *)malloc(sizeof(int) * qoSeqLength);
  int *hiWinIdx = (int *)malloc(sizeof(int) * qoSeqLength);
___
*[`lib/kernels/src/cuda/ops/cast_kernels.cu` line 61 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC4XpkB7xtjIckJCMF:-NzOX_UHD80L2ccEzEzf:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/ops/cast_kernels.cu#L61)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If these shouldn't be here, delete don't just comment out
</blockquote></details>

Done.
___
*[`lib/kernels/test/CMakeLists.txt` line 3 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC4sdl89lJB5EAgIAo:-NzOY4bn0F9cfpu9fvGX:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/test/CMakeLists.txt#L3)):*
> ```CMake
> ff_add_test_executable(
>   NAME
>     kernel-tests
> ```

Done.
___
*[`lib/kernels/test/CMakeLists.txt` line 21 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC4ySz0Lim-inypwq3:-NzOY5AT0S44Jwj_ovvf:ba3dfob) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/test/CMakeLists.txt#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Definitely don't need `compiler` or `pcg`, I also don't think you need `nccl`
</blockquote></details>

Removed
___
*[`lib/kernels/test/CMakeLists.txt` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC4m8pE3Q1xlJWlCgt:-NzOY6ueBAwZWyaplH5T:ba3dfob) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/test/CMakeLists.txt#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Fix up commented-out stuff before merging
</blockquote></details>

Removed
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC5Gvi3uNLYHpsX8bh:-NzOY9x0C5aeAYJA1W26:b91p3c3) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/test/src/test_attention_kernel.cc#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably best to pull this out into a helper function
</blockquote></details>

Created
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 51 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC5TrLARV9xAVaS3IC:-NzOYBgS9H15VjJvl0_f:bb6un1j) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/test/src/test_attention_kernel.cc#L51)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull generating a random `GenericTensorAccessor` out into a separate function
</blockquote></details>

Done
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 86 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC5bL0-Wfo-SIXX3wz:-NzOYCu3A8emgy1FyXC3:bb6un1j) ([raw file](https://git [...]

2024-06-10 17:02 UTC, reyna-abhyankar requested changes
Agree with this and I'd add to separate the kernel tests by forward and backward (and then pull out the duplicated code). Currently it's a giant end to end test for each operator, which if it fails we don't actually know what part went wrong. 

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-:-O-25F0B--hvBrQ5Me_c:b-qqvrnl)* status: 10 of 63 files reviewed, 37 unresolved discussions (waiting on @lockshaw and @oOTigger)

___
*[`lib/kernels/include/kernels/device.h` line 31 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-22Bmp8veh3SnW9yx-:-O-22Bmp8veh3SnW9yx0:b-ptajf2) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/kernels/include/kernels/device.h#L31)):*
> ```objc
> #if defined(FF_USE_CUDA) || defined(FF_USE_HIP_CUDA)
> typedef cudaStream_t ffStream_t;
> cudaError_t get_legion_stream(cudaStream_t *stream);
> ```

Why deleted? iirc this is called in a couple of places
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 36 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC5O9MDYeDIU_peGHj:-O-24ztr09hNQTyPFwN6:bvaxsep) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/test/src/test_attention_kernel.cc#L36)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

@reyna-abhyankar Isn't there a way to directly allocate a `GenericTensorAccessor` using an `Allocator`?
</blockquote></details>

Yes, this is in the latest repo-refactor from 1400.
___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 8 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-22eG-6qDZ6nYK5Ap4:-O-22eG08UdsOni4bpYA:b9tmszt) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_cast_kernel.cc#L8)):*
> ```cpp
> 
> template <typename T>
> void allocate_ptrs(std::vector<T **> &gpu_data_ptrs,
> ```

This code can be moved out since it's replicated a bunch
___
*[`lib/kernels/test/src/test_concat_kernel.cc` line 27 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-23JvP3VYr7AcDA6Cu:-O-23JvP3VYr7AcDA6Cv:bw1msze) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_concat_kernel.cc#L27)):*
> ```cpp
> 
>     for (int i = 0; i < num_inputs; i++) {
>       void *input_data_ptr = allocator.allocate(size_per_input * sizeof(float));
> ```

Merge latest repo-refactor, I think the allocator interface now allows you to pass in a tensor shape and get back a GTAW
___
*[`lib/kernels/test/src/test_layer_norm_kernels.cc` line 21 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-23gkQ2Ejj6RJ9fG3G:-O-23gkQ2Ejj6RJ9fG3H:b14fan8) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_layer_norm_kernels.cc#L21)):*
> ```cpp
> 
> TEST_SUITE("kernel-tests") {
>   TEST_CASE("Test LayerNorm Forward and Backward Kernel") {
> ```

In general, I think we should have separate test cases for the 3 kernels since we aren't actually testing for correctness in this. Then, later we can add correctness tests that do it end to end
___
*[`lib/kernels/test/src/test_partition_kernel.cc` line 19 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-241Mj4luqNLDNlh4s:-O-241Mj4luqNLDNlh4t:bt87j6x) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_partition_kernel.cc#L19)):*
> ```cpp
> }
> 
> using namespace ::FlexFlow;
> ```

Suggestion



_Code snippet:_
```cpp
using namespace FlexFlow;
```
___
*[`lib/kernels/test/src/test_partition_kernel.cc` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-244tL1hEt54X-TwRt:-O-244tL1hEt54X-TwRu:bt87j6x) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_partition_kernel.cc#L25)):*
> ```cpp
>     std::size_t dims[] = {num_elements};
>     std::size_t num_dims = 1;
>     FlexFlow::ArrayShape shape(dims, num_dims);
> ```

Suggestion



_Code snippet:_
```cpp
ArrayShape shape(...);
```
___
*[`lib/kernels/test/src/test_partition_kernel.cc` line 44 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-24EG57m0NVR5em_Hv:-O-24EG57m0NVR5em_Hw:b5uynkm) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_partition_kernel.cc#L44)):*
> ```cpp
>         Kernels::Repartition::init_kernel(handle, DataType::FLOAT);
> 
>     
> ```

What's this?
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 22 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-24TLEEAfgxBUsN1Eo:-O-24TLEEAfgxBUsN1Ep:b2oao3e) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_softmax_kernel.cc#L22)):*
> ```cpp
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("Test Softmax Forward") {
>     std::size_t num_elements = 100;
> ```

This is good, splitting up the kernels. But then you can also just refactor any shared code between the test cases (can call it like `softmax_test_setup()` that does any other work for you)
___
*[`lib/kernels/test/src/test_utils.h` line 10 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-24jJDEYror6O3Nnel:-O-24jJDEYror6O3Nnem:blv2su3) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_utils.h#L10)):*
> ```objc
> #include <vector>
> #include <algorithm>
> ```

move that pointers allocation to here. we can maybe push it to allocator too but for now, the utils file should be fine


<!-- Sent from Reviewable.io -->

2024-06-10 17:03 UTC, reyna-abhyankar requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 10 of 63 files reviewed, 38 unresolved discussions (waiting on @lockshaw and @oOTigger)

___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 54 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-25jUr5nd5Vwzjjs1-:-O-25jUr5nd5Vwzjjs10:b36jz02) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/include/kernels/conv_2d_kernels.h#L54)):*
> ```objc
>                                  float *filter_grad_ptr);
> 
> void forward_kernel(cudaStream_t stream,
> ```

Also, why? this is the header file for both the cuda and hip kernels so it should be generic, right?


<!-- Sent from Reviewable.io -->

2024-06-12 01:47 UTC, lockshaw requested changes
Reyna's comment is a great use case for doctest's `SUBCASE` (see https://github.com/doctest/doctest/blob/master/doc/markdown/tutorial.md#test-cases-and-subcases)--you can have a subcase for `forward` and a subcase for `backward` without duplicating all of the setup code

> Reviewed 1 of 13 files at r3, 13 of 44 files at r4, 1 of 8 files at r5, 12 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-:-O-7wWQy4WcAKKpQ53zK:b-1me126)* status: 37 of 63 files reviewed, 40 unresolved discussions (waiting on @oOTigger)

___
*[`flake.nix` line 32 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-92uwN06x1nkjCg-qS:-O-92uwN06x1nkjCg-qT:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/flake.nix#L32)):*
> ```Nix
>       stdenv = pkgs.cudaPackages.backendStdenv;
>       mkShell = pkgs.mkShell.override {
>         # stdenv = pkgs.cudaPackages.backendStdenv;
> ```

Delete
___
*[`lib/kernels/include/kernels/element_unary_kernels.h` line 8 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-93CWE5AO7FzRg-ADK:-O-93CWE5AO7FzRg-ADL:b-edbvir) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/include/kernels/element_unary_kernels.h#L8)):*
> ```objc
> #include "kernels/ff_handle.h"
> #include "op-attrs/ops/element_unary.h"
> #include "op-attrs/operator_type.h"
> ```

Why was this added?
___
*[`lib/kernels/include/kernels/gather_kernels.h` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-93UFD0Z3R8i-aImpf:-O-93UFD0Z3R8i-aImpg:bt9h7j2) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/include/kernels/gather_kernels.h#L25)):*
> ```objc
>                     GenericTensorAccessorR const &index,
>                     GenericTensorAccessorW const &output,
>                     size_t stride,
> ```

Why were these added?
___
*[`lib/kernels/include/kernels/layer_norm_kernels.h` line 39 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-93gmv-s7qq8uG5Zxu:-O-93gmv-s7qq8uG5Zxv:bff3x09) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/include/kernels/layer_norm_kernels.h#L39)):*
> ```objc
> LayerNormPerDeviceState init_kernel(PerDeviceFFHandle const &handle,
>                                     Allocator &allocator,
>                                     bool elementwise_affine_,
> ```

Why change all the argument names?
___
*[`lib/kernels/src/array_shape.cc` line 18 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7tWdb6y984IC5kqky:-O-7tWdb6y984IC5kqkz:b70rm0r) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/array_shape.cc#L18)):*
> ```cpp
> 
> std::size_t ArrayShape::num_dims() const {
>   return this->dims.size();
> ```

Why this change? I don't think we really do one-line functions formatted like this all that often (I'm actually surprised the formatter didn't complain--did it make this change?)
___
*[`lib/kernels/src/array_shape.cc` line 23 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7tmbs5jCY-GRx1Ltf:-O-7tmbt4FVaKP9tEdZr:b-jzfveh) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/array_shape.cc#L23)):*
> ```cpp
>     return 0;
>   return std::accumulate(dims.begin(), dims.end(), 1,
>                          std::multiplies<std::size_t>());
> ```

From `utils/containers.h`



_Suggestion:_
```cpp
  return product(this->dims);
```
___
*[`lib/kernels/src/array_shape.cc` line 39 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7tz6YCfbBqLmajV2h:-O-7tz6YCfbBqLmajV2i:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/array_shape.cc#L39)):*
> ```cpp
> std::optional<std::size_t> ArrayShape::at_maybe(std::size_t index) const {
>   if (index < dims.size()) {
>     return dims[legion_dim_t(index)];
> ```





_Suggestion:_
```cpp
   return dims.at(legion_dim_t(index));
```
___
*[`lib/kernels/src/array_shape.cc` line 49 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7u6Ib1k5nNTWqeL1G:-O-7u6Ib1k5nNTWqeL1H:b-gncmvx) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/array_shape.cc#L49)):*
> ```cpp
>   std::reverse(reversed_dims.begin(), reversed_dims.end());
>   return ArrayShape(reversed_dims);
> }
> ```

This method should probably just be deleted

Also, `reversed` from `utils/containers.h`



_Code quote:_
```cpp
ArrayShape ArrayShape::reversed_dim_order() const {
  std::vector<std::size_t> reversed_dims(dims.begin(), dims.end());
  std::reverse(reversed_dims.begin(), reversed_dims.end());
  return ArrayShape(reversed_dims);
}
```
___
*[`lib/kernels/src/device.h` line 139 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-94UqW1pn51x-lQELB:-O-94UqW1pn51x-lQELC:bcgjvre) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/device.h#L139)):*
> ```objc
> void print_tensor(T const *ptr, size_t num_elements, char const *prefix);
> 
> cudnnStatus_t
> ```

Why this change?
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 1 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-94jvR1YPW9Uha1Ocw:-O-94jvR1YPW9Uha1Ocx:bocdtod) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/cuda_helper.cu#L1)):*
> ```Cuda
> // #include "flexflow/model.h"
> ```

Delete if not used
___
*[`lib/kernels/src/cuda/ops/attention_kernels.cu` line 307 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC47rZBmKty-GDQ_OD:-O-951iyDtQxnbwWi4AY:bw78u6y) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/ops/attention_kernels.cu#L307)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

In init_kernel: 

// allocate memory for loWinIdx/hiWinIdx
  int *loWinIdx = (int *)malloc(sizeof(int) * qoSeqLength);
  int *hiWinIdx = (int *)malloc(sizeof(int) * qoSeqLength);
</blockquote></details>

They're allocated there, but where are they used?
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 134 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95GVi-QexYSjWgFBJ:-O-95GVi-QexYSjWgFBK:b-hnxnyt) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L134)):*
> ```Cuda
>   float *saveVar = (float *)saveMean + output_c;
>   cudaStream_t stream;
>   checkCUDA(get_legion_stream(&stream));
> ```

Should a stream just get passed in as an argument? Isn't that how most of the other operators work?
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 137 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95MLd1GLAx-3xkFuU:-O-95MLd1GLAx-3xkFuV:blpv8ba) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L137)):*
> ```Cuda
> 
>   assign_kernel<<<GET_BLOCKS(output_c), CUDA_NUM_THREADS, 0, stream>>>(
>       runningMean, (size_t)output_c, 0.0f);
> ```

From `utils/conversions.h`



_Suggestion:_
```Cuda
size_t_from_int(output_c)
```
___
*[`lib/kernels/src/cuda/ops/conv_2d_kernels.cu` line 247 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95XvGEHXwK0w5MdNz:-O-95XvH9WKr9K28bVKJ:b-5e49nj) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/conv_2d_kernels.cu#L247)):*
> ```Cuda
>                                                        handle.workSpaceSize,
>                                                        inputTensor,
>                                [...]

2024-06-13 13:57 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 15 of 66 files reviewed, 40 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`flake.nix` line 32 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-92uwN06x1nkjCg-qS:-O-Fu-e67g5NRaUkSaFf:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/flake.nix#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/conv_2d_kernels.h` line 54 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-25jUr5nd5Vwzjjs1-:-O-FvQFP1at0PgkJzgLD:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/include/kernels/conv_2d_kernels.h#L54)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Also, why? this is the header file for both the cuda and hip kernels so it should be generic, right?
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/device.h` line 31 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-22Bmp8veh3SnW9yx-:-O-FwIGs4ktYz5aasi5N:btl7nqp) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/kernels/include/kernels/device.h#L31)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why deleted? iirc this is called in a couple of places
</blockquote></details>



I was running into compile issues regarding the get_legion_stream declarations and use in cuda_helper.cu. This new changes allows things to compile fine as well, but not sure if this is allowed either? 
___
*[`lib/kernels/include/kernels/element_unary_kernels.h` line 8 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-93CWE5AO7FzRg-ADK:-O-G0UXt9YGms7haNrQd:ba3dfob) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/include/kernels/element_unary_kernels.h#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was this added?
</blockquote></details>

Removed
___
*[`lib/kernels/include/kernels/gather_kernels.h` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-93UFD0Z3R8i-aImpf:-O-G0p6D69wiMkdjQBI5:bswobp7) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/include/kernels/gather_kernels.h#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why were these added?
</blockquote></details>

I was matching the declaration of gather_kernels.cu originally as the two did not match. It looks like these parameters were removed from gather_kernels.cu in the latest merge so this should be resolved now. 
___
*[`lib/kernels/include/kernels/layer_norm_kernels.h` line 39 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-93gmv-s7qq8uG5Zxu:-O-G19t1BcxXaNZkn6Ip:b-p3psec) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/include/kernels/layer_norm_kernels.h#L39)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why change all the argument names?
</blockquote></details>

Originally there were no names, in an earlier review you asked me to "Add argument names" for the SoftmaxPerDeviceState, so I figured I should do the same for LayerNormPerDeviceState as well. 
___
*[`lib/kernels/src/array_shape.cc` line 18 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7tWdb6y984IC5kqky:-O-G1gvnA43vGVnPFTHB:b-o02k3z) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/array_shape.cc#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why this change? I don't think we really do one-line functions formatted like this all that often (I'm actually surprised the formatter didn't complain--did it make this change?)
</blockquote></details>

I was talking to Reyna and realized I was using the wrong formatting script. I was using clang-format -i, as I was unaware of ./scripts/format.sh  
___
*[`lib/kernels/src/array_shape.cc` line 23 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7tmbs5jCY-GRx1Ltf:-O-G2CEr1AfWQ0aL7OTZ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/array_shape.cc#L23)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

From `utils/containers.h`
</blockquote></details>

Done.
___
*[`lib/kernels/src/array_shape.cc` line 39 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7tz6YCfbBqLmajV2h:-O-G2C000SLWdSOEm5Wf:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/array_shape.cc#L39)):*
> ```cpp
> std::optional<std::size_t> ArrayShape::at_maybe(std::size_t index) const {
>   if (index < dims.size()) {
>     return dims[legion_dim_t(index)];
> ```

Done.
___
*[`lib/kernels/src/array_shape.cc` line 49 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7u6Ib1k5nNTWqeL1G:-O-G2zRyAicBAJN0L5XF:bg3yhnu) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/array_shape.cc#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This method should probably just be deleted

Also, `reversed` from `utils/containers.h`
</blockquote></details>

Deleted get_volume() and fixed relevant function calls. 

What are you suggesting with the second part relating to reversed_dim_order? 
___
*[`lib/kernels/src/device.h` line 139 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-94UqW1pn51x-lQELB:-O-G3NIeC0EdRggTUC6G:b-f1rbsf) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/device.h#L139)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

Was debugging and forgot to restore to original. Fixed.
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 1 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-94jvR1YPW9Uha1Ocw:-O-G3WP0-uUtSR3G_iw_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/cuda_helper.cu#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete if not used
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/ops/attention_kernels.cu` line 307 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC47rZBmKty-GDQ_OD:-O-G4_pd7j1S73lIcctC:bh9d8uh) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/ops/attention_kernels.cu#L307)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

They're allocated there, but where are they used?
</blockquote></details>

They're used as parameters that are fields in MHAPerDeviceState which are then later fed into cudnnMultiHeadAttnForward 
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 134 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95GVi-QexYSjWgFBJ:-O-G6GEm-7Ixd9Tg84kf:b-3t4ujm) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L134)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should a stream just get passed in as an argument? Isn't that how most of the other operators work?
</blockquote></details>

Yeah, most other functions get a stream passed in but  [...]

2024-06-14 21:00 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 13 of 68 files reviewed, 40 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 36 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC5O9MDYeDIU_peGHj:-O-NSiGpEafkQQ3p4akK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/test/src/test_attention_kernel.cc#L36)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Yes, this is in the latest repo-refactor from 1400.
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_batch_matmul_kernel.cc` line 29 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7vx7U6COmFARdRbti:-O-NXGvP6lrU-uTiGo6c:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_batch_matmul_kernel.cc#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This should be using `TensorShape`s and the corresponding ability to use `Allocator` to allocate tensors using `TensorShapes` rather than raw sizes
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_concat_kernel.cc` line 27 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-23JvP3VYr7AcDA6Cu:-O-NSrq1-3uX9pV3snzp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_concat_kernel.cc#L27)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Merge latest repo-refactor, I think the allocator interface now allows you to pass in a tensor shape and get back a GTAW
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-16 01:43 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 13 of 69 files reviewed, 40 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/test/src/test_batch_matmul_kernel.cc` line 44 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7vQDlEz7rDQFKaT7T:-O-TgnJ35zTfOw_s-Nq2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_batch_matmul_kernel.cc#L44)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull out into a separate function which just gives you a bunch of filled tensors ready to go. Also, more functions here should have return values rather then returning void and using pointers/references to return values
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_batch_matmul_kernel.cc` line 56 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-7vccfERC_P0Ob6X02:-O-TgnkSENNz4tqkAQi7:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_batch_matmul_kernel.cc#L56)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

All of this raw pointer manipulation should be moved out into separate helper functions
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-16 17:35 UTC, reyna-abhyankar requested changes
> Reviewed 3 of 13 files at r3, 2 of 14 files at r6, 12 of 46 files at r7, 16 of 36 files at r8, 2 of 6 files at r9, 21 of 21 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: all files reviewed, 38 unresolved discussions (waiting on @lockshaw and @oOTigger)

___
*[`lib/kernels/include/kernels/device.h` line 31 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-22Bmp8veh3SnW9yx-:-O-X1bIa4szeA4xMcJX7:bnmru31) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/kernels/include/kernels/device.h#L31)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

I was running into compile issues regarding the get_legion_stream declarations and use in cuda_helper.cu. This new changes allows things to compile fine as well, but not sure if this is allowed either?
</blockquote></details>

This seems fine to me if the tests that call `get_legion_stream` work. But if they don't, then we can leave them out of this PR and create an issue for it. Which operators call this function?
___
*[`lib/kernels/include/kernels/local_allocator.h` line 4 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X4XhF6f8_MZ9OAY10:-O-X4XhF6f8_MZ9OAY11:bx1yxiw) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/include/kernels/local_allocator.h#L4)):*
> ```objc
> #include <unordered_set>
> 
> namespace FlexFlow {
> ```

@lockshaw Should we just move `LocalAllocator` into kernels? Otherwise `kernels` needs to link local-execution`
___
*[`lib/kernels/include/kernels/softmax_kernels.h` line 22 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X53EY0ylKn7jYrils:-O-X53EY0ylKn7jYrilt:bau554e) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/include/kernels/softmax_kernels.h#L22)):*
> ```objc
> 
> SoftmaxPerDeviceState init_kernel(PerDeviceFFHandle const &handle,
>                                   int dim,
> ```

can you create an issue for fixing the calling code? I can handle it in a local-execution related PR
___
*[`lib/kernels/src/cuda/ops/conv_2d_kernels.cu` line 247 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95XvGEHXwK0w5MdNz:-O-X5fVL9DzXWYDnNJj5:b-gny9lb) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/conv_2d_kernels.cu#L247)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

I get a error: invalid type conversion static_cast<void *>(input.get_float_ptr()) when trying to cast input.get_float_ptr() normally for bwdDataAlgo, I think as get_float_ptr() returns a const float *
</blockquote></details>

We can use `GenericTensorAccessorW` instead of `R` then? 
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 59 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X1wJg8PBAhIuHx77V:-O-X1wJg8PBAhIuHx77W:b-8rid2d) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_attention_kernel.cc#L59)):*
> ```cpp
>           getRandomFilledAccessorW(weight_shape, allocator);
>       GenericTensorAccessorW output_accessor =
>           allocator.allocate_tensor(output_shape);
> ```

Why is output tensor not using the `getRandomFilledAccessorW`?
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 63 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X5yav2WIj2SufACaj:-O-X5yav2WIj2SufACak:b-xixp2c) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_attention_kernel.cc#L63)):*
> ```cpp
>       Kernels::MultiHeadAttention::forward_kernel(stream,
>                                                   state,
>                                                   (float *)query_accessor.ptr,
> ```

why not just `query_accessor.get_float_ptr()`? Goes for everywhere else where you're doing `(float *)`
___
*[`lib/kernels/test/src/test_layer_norm_kernels.cc` line 21 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-23gkQ2Ejj6RJ9fG3G:-O-X2U4eAHWq5kSmCarQ:b-5g4k9n) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_layer_norm_kernels.cc#L21)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Does this mean I need to create a new "TEST_SUITE"? How do I do that?
</blockquote></details>

What you have here (the nested subcase, as discussed in our Friday meeting) is fine. Just do it for all the operators
___
*[`lib/kernels/test/src/test_partition_kernel.cc` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-244tL1hEt54X-TwRt:-O-NXk2b0vsRTM0HwqVl:b4kp4rq) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_partition_kernel.cc#L25)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

What does this mean?
</blockquote></details>

Your change is fine.
___
*[`lib/kernels/test/src/test_partition_kernel.cc` line 44 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-24EG57m0NVR5em_Hv:-O-NYkv9ED67-yx3-G01:b-11ktv3) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_partition_kernel.cc#L44)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

This is just setting up my accessors like the other kernels, or is there special behavior for partition kernels?
</blockquote></details>

I think I was just wondering what the ellipses were for but you removed them.
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 22 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-24TLEEAfgxBUsN1Eo:-O-X2cWj1f2YECAEZkT0:bfgq1bg) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_softmax_kernel.cc#L22)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Got it. Will utilize the SUBCASE functionality Colin brought up
</blockquote></details>

Nest the backward subcase in the forward subcase (goes for all operators)
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 60 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X6IcdB6PQS6LX8LJm:-O-X6IcdB6PQS6LX8LJn:b-2ff8ab) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_split_kernel.cc#L60)):*
> ```cpp
>     }
> 
>     SUBCASE("Test Split Backward Kernel") {
> ```

Nest subcase
___
*[`lib/kernels/test/src/test_utils.h` line 13 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X3n9f-uxM_UpmEbZ3:-O-X3n9f-uxM_UpmEbZ4:bq7c5x2) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_utils.h#L13)):*
> ```objc
> 
> template <typename T>
> void allocate_ptrs(std::vector<T **> &gpu_data_ptrs,
> ```

Can you just pass `std::vector<T*>` instead of double pointer? It's being dereferenced anyway


<!-- Sent from Reviewable.io -->

2024-06-17 06:14 UTC, lockshaw commented
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 52 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-Zp9jg2zzEg2BLOoMi:-O-Zp9jg2zzEg2BLOoMj:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_batch_norm_kernel.cc#L52)):*
> ```cpp
>       std::vector<float> host_output_data =
>           fill_host_data<float>(output_accessor.ptr, num_elements);
>       REQUIRE(contains_non_zero(host_output_data));
> ```





_Suggestion:_
```cpp
CHECK
```


<!-- Sent from Reviewable.io -->

2024-06-18 16:16 UTC, reyna-abhyankar requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 39 of 70 files reviewed, 35 unresolved discussions (waiting on @lockshaw and @oOTigger)

___
*[`lib/kernels/include/kernels/local_allocator.h` line 4 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X4XhF6f8_MZ9OAY10:-O-g7US2E1ryDCGm-7_t:b-681ovp) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/include/kernels/local_allocator.h#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think `kernels-tests` needs to link to local-execution, but I don't think `kernels` does? Either way yes it's probably a good idea to move it into `kernels`
</blockquote></details>

@oOTigger can you make this change?
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 59 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X1wJg8PBAhIuHx77V:-O-g7Fln2Dg4SW-ONKxg:bikfhgf) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_attention_kernel.cc#L59)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Isn't the output accessor just where things will get stored so no need to initialize it with data?
</blockquote></details>

Yeah you're right
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 22 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-24TLEEAfgxBUsN1Eo:-O-g7ITgDelxcSAcrSJ2:bnagh84) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_softmax_kernel.cc#L22)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

See my slack msg: 
actually instead of nesting the subcases, maybe just keep separate subcases and pull out the relevant tensor accessor code to before the forward kernel
because nesting means the backward will only be tested if the forward passes
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 60 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X6IcdB6PQS6LX8LJm:-O-g7O-78EQn-TVCoEoY:byr4ffv) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_split_kernel.cc#L60)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

see above


<!-- Sent from Reviewable.io -->

2024-06-18 22:30 UTC, lockshaw requested changes
> Reviewed 2 of 13 files at r3, 3 of 46 files at r7, 5 of 36 files at r8, 20 of 31 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 59 of 70 files reviewed, 33 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/array_shape.h` line 55 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hQIgV9UZY8zntirl-:-O-hQIgV9UZY8zntirl0:b-hyoy0j) ([raw file](https://github.com/flexflow/FlexFlow/blob/86339457770e6405745df7a1605a4bff86726e68/lib/kernels/include/kernels/array_shape.h#L55)):*
> ```objc
> FF_VISITABLE_STRUCT_NONSTANDARD_CONSTRUCTION(ArrayShape, dims);
> 
> size_t get_volume(ArrayShape const &);
> ```

Why was this removed?
___
*[`lib/kernels/include/kernels/layer_norm_kernels.h` line 39 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-93gmv-s7qq8uG5Zxu:-O-hHP9fAHtWRn9Z3o1h:bwg3juk) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/include/kernels/layer_norm_kernels.h#L39)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Oh, I guess it's because I just copied the signature over from layer_norm_kernels.cu, which has the names defined with the underscores. I can ever if that's preferable.
</blockquote></details>

The underscores are an older style, avoid them in new code
___
*[`lib/kernels/include/kernels/transpose_kernels.h` line 5 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZOv-R-y7kqRvAMQNr:-O-hKq135hbP9loH_ut3:b9trijc) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/include/kernels/transpose_kernels.h#L5)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Otherwise you get errors regarding "GenericTensorAccessor's" being declared
</blockquote></details>

Then shouldn't `kernels/accessor.h` be included instead? 
___
*[`lib/kernels/src/array_shape.cc` line 7 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hIS_W6mgmgCC3rG8Q:-O-hIS_W6mgmgCC3rG8R:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L7)):*
> ```cpp
> 
> static LegionTensorDims
>     create_reversed_dims(FFOrdered<size_t> const &ff_ordered) {
> ```





_Suggestion:_
```cpp
static LegionTensorDims
    legion_dims_from_ff_dims(FFOrdered<size_t> const &ff_ordered) {
```
___
*[`lib/kernels/src/array_shape.cc` line 15 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hILtfCEydMtGt6t3s:-O-hILtfCEydMtGt6t3t:bb77ufx) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L15)):*
> ```cpp
> ArrayShape::ArrayShape(size_t *_dims, size_t num_dims)
>     : dims(_dims, _dims + num_dims) {
> } // This assumes dims can be constructed from iterators.
> ```

Yes?
___
*[`lib/kernels/src/array_shape.cc` line 64 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hJ5PPE3JBMHm78gd5:-O-hJ5PPE3JBMHm78gd6:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L64)):*
> ```cpp
>   reversed(reversed_dims);
>   return ArrayShape(reversed_dims);
> }
> ```

Delete



_Code quote:_
```cpp
ArrayShape ArrayShape::reversed_dim_order() const {
  std::vector<std::size_t> reversed_dims(dims.begin(), dims.end());
  reversed(reversed_dims);
  return ArrayShape(reversed_dims);
}
```
___
*[`lib/kernels/src/cuda/ops/attention_kernels.cu` line 47 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3qETBRvGyv52t-WL:-O-hLg9W2n1DZui2EQEr:b-t65fzp) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/ops/attention_kernels.cu#L47)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

How can I be sure that it's not used on master/inference? I searched on Git and I don't see that state being used anywhere. Is that good enough of a check?
</blockquote></details>

Yeah that works, it can be removed.
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 137 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95MLd1GLAx-3xkFuU:-O-hK0wbDYSWp1lklJGT:b19fbnu) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L137)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

I should be up to date with the latest repo-refactor? I'm looking directly at the latest version of utils in repo-refactor on the Git as well and can't seem to find a conversions.h file either
</blockquote></details>

https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/utils/include/utils/integer_conversions.h
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 101 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZkDU1BU897IXeyCKd:-O-hKS7H6MXiFL4kurYT:bqqnbtx) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_attention_kernel.cc#L101)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see `REQUIRE`?
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 10 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZpJCuBz9QWyyqzNhq:-O-hLvRm9OuSI-pQ-A-9:b-xt52hg) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_batch_norm_kernel.cc#L10)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

It's because num_elements is needed later for things like the backward kernel and fill_host_data
</blockquote></details>

Best to replace those uses with a `num_elements` call on the `TensorShape`
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 51 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZoaM62xmDZyJnNHj2:-O-hM5jD9JNFZjm33r3B:ba291za) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_batch_norm_kernel.cc#L51)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Changed name to load_data_to_host_from_device and it now takes in just the tensor accessor directly. 

Regarding the last point, I didn't handle the logic in an explicit check as the contains_non_zero checks rn are honestly just filler checks for now. When we begin implementing the more complicated CPU checks though later I imagine just getting the vector and writing the check in the kernel is what we want?
</blockquote></details>

That makes sense, sounds good
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 52 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-Zp9jg2zzEg2BLOoMi:-O-hMTLPEqfiGrcdExcy:b4lj5vf) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_batch_norm_kernel.cc#L52)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still see REQUIRE
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 53 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hMAjX-Vf1rmqJwMii:-O-hMAjX-Vf1rmqJwMij:bilmn0y) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_batch_norm_kernel.cc#L53)):*
> ```cpp
>                                          bias_accessor.get_float_ptr());
> 
>       std::vector<float> host_output_data =
> ```

In the long term this shouldn't be a `std::vector` as `std::vector` loses all of the shape data that, e.g., `GenericTensorAccessor` has. We may need to add a h [...]

2024-06-18 23:19 UTC, reyna-abhyankar requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 59 of 70 files reviewed, 42 unresolved discussions (waiting on @oOTigger)

___
*[`lib/kernels/test/src/test_batch_matmul_kernel.cc` line 71 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-g94GL54xKbzw9_014:-O-g94GL54xKbzw9_015:b207mxc) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_batch_matmul_kernel.cc#L71)):*
> ```cpp
>                                             n,
>                                             k,
>                                             batch);
> ```

Is there a check that needs to happen?
___
*[`lib/kernels/test/src/test_combine_kernel.cc` line 37 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-g91qREgPmSoxvhnft:-O-g91qREgPmSoxvhnfu:b207mxc) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_combine_kernel.cc#L37)):*
> ```cpp
>         std::vector<float> host_input_grad =
>             load_data_to_host_from_device<float>(
>                 read_only_accessor_from_write_accessor(accessorWGrad));
> ```

Is there a check that needs to happen?
___
*[`lib/kernels/test/src/test_layer_norm_kernels.cc` line 74 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-g8p6lEhQ059vkKU6M:-O-g8p6lEhQ059vkKU6N:b207mxc) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_layer_norm_kernels.cc#L74)):*
> ```cpp
>             read_only_accessor_from_write_accessor(gamma_accessor),
>             gamma_grad_accessor,
>             beta_grad_accessor);
> ```

Is there a check that needs to happen?
___
*[`lib/kernels/test/src/test_pool_2d_kernels.cc` line 71 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-g8lmG43mvq1Pu-Iq9:-O-g8lmG43mvq1Pu-IqA:b207mxc) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_pool_2d_kernels.cc#L71)):*
> ```cpp
>                                          input_grad.ptr,
>                                          output_data.ptr,
>                                          output_grad.ptr);
> ```

Is there a check that needs to happen?
___
*[`lib/kernels/test/src/test_reduction_kernel.cc` line 46 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-g8iGuB6Fnj7wVgF3j:-O-g8iGuB6Fnj7wVgF3k:b207mxc) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_reduction_kernel.cc#L46)):*
> ```cpp
>         std::vector<float> host_grad_data =
>             load_data_to_host_from_device<float>(
>                 read_only_accessor_from_write_accessor(output_accessor));
> ```

Is there a check that needs to happen?
___
*[`lib/kernels/test/src/test_reverse_kernels.cc` line 48 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-g8ZAi9eNSn5SI8J10:-O-g8ZAi9eNSn5SI8J11:b-wkr6vs) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_reverse_kernels.cc#L48)):*
> ```cpp
>             load_data_to_host_from_device<float>(
>                 read_only_accessor_from_write_accessor(grad_input_accessor));
>       }
> ```

Is there a check here that needs to happen?
___
*[`lib/kernels/test/src/test_transpose_kernel.cc` line 48 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-g8SjLDPTfUFGfYSiw:-O-g8SjLDPTfUFGfYSix:b-5ksw6b) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_transpose_kernel.cc#L48)):*
> ```cpp
> 
>         std::vector<float> host_grad_input_data =
>             load_data_to_host_from_device<float>(
> ```

Why is this happening? Are there some conditions that need to be checked?
___
*[`lib/kernels/test/src/test_utils.h` line 32 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hdVWy2kTtzrpLDE-X:-O-hdVWy2kTtzrpLDE-Y:b-wmzdy8) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_utils.h#L32)):*
> ```objc
> 
> template <typename T>
> std::vector<T> load_data_to_host_from_device(GenericTensorAccessorR accessor) {
> ```

why does this need to return a vector?
___
*[`lib/kernels/test/src/test_utils.h` line 36 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-g7sjp7DZrhM7NCU5h:-O-g7sjp7DZrhM7NCU5i:bs0xj1t) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_utils.h#L36)):*
> ```objc
> 
>   int volume =
>       std::accumulate(dims.begin(), dims.end(), 1, std::multiplies<int>());
> ```

`product(...)`


<!-- Sent from Reviewable.io -->

2024-06-19 10:48 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 40 of 70 files reviewed, 42 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/layer_norm_kernels.h` line 39 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-93gmv-s7qq8uG5Zxu:-O-izRbT34nKGgoyDMEK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/include/kernels/layer_norm_kernels.h#L39)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The underscores are an older style, avoid them in new code
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/local_allocator.h` line 4 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X4XhF6f8_MZ9OAY10:-O-jkX2Z5OqWsksAKmns:b-vrq47s) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/include/kernels/local_allocator.h#L4)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

@oOTigger can you make this change?
</blockquote></details>

Isn't LocalAllocator already a part of kernels? 
___
*[`lib/kernels/include/kernels/transpose_kernels.h` line 5 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZOv-R-y7kqRvAMQNr:-O-izrTF4Ro_Of_hJE5Q:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/include/kernels/transpose_kernels.h#L5)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Then shouldn't `kernels/accessor.h` be included instead?
</blockquote></details>

Done.
___
*[`lib/kernels/src/array_shape.cc` line 7 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hIS_W6mgmgCC3rG8Q:-O-jyXTI0mOjEa50ABvk:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L7)):*
> ```cpp
> 
> static LegionTensorDims
>     create_reversed_dims(FFOrdered<size_t> const &ff_ordered) {
> ```

Done.
___
*[`lib/kernels/src/array_shape.cc` line 15 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hILtfCEydMtGt6t3s:-O-jhFr78XZu9JkvnXnu:ba3dfob) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yes?
</blockquote></details>

Removed
___
*[`lib/kernels/src/array_shape.cc` line 64 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hJ5PPE3JBMHm78gd5:-O-jp0YkB6aHMlv4_DI5:bbage1g) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L64)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

What about the call to reversed_dim_order in cuda_helper.cu? 



_Code snippet:_
```cpp
ffStatus_t
    cudnnSetTensorDescriptorFromArrayShape(cudnnTensorDescriptor_t tensor,
                                           ArrayShape const &shape) {
  ArrayShape flipped = shape.reversed_dim_order();

  if (flipped.get_dim() == 5) {
    assert(flipped[legion_dim_t(0)] == 1);
    flipped = flipped.sub_shape(legion_dim_t(1), std::nullopt);
  }

  assert(flipped.get_dim() > 0);
  assert(flipped.get_dim() < 4);

  return cudnnSetTensor4dDescriptor(tensor,
                                    CUDNN_TENSOR_NCHW,
                                    CUDNN_DATA_FLOAT,
                                    flipped.at_maybe(0).value_or(1),
                                    flipped.at_maybe(1).value_or(2),
                                    flipped.at_maybe(2).value_or(3),
                                    flipped.at_maybe(3).value_or(3));
}
```
___
*[`lib/kernels/src/cuda/ops/attention_kernels.cu` line 47 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3qETBRvGyv52t-WL:-O-j1b756EYLPACmeHW4:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/ops/attention_kernels.cu#L47)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yeah that works, it can be removed.
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 137 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95MLd1GLAx-3xkFuU:-O-j1eio0rjw3aEHhrbB:b-7ql1td) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L137)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/utils/include/utils/integer_conversions.h
</blockquote></details>

fixed
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 101 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZkDU1BU897IXeyCKd:-O-j3IAlCshcXAQOGtQi:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_attention_kernel.cc#L101)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I still see `REQUIRE`?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_batch_matmul_kernel.cc` line 71 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-g94GL54xKbzw9_014:-O-jpdZz7asnOf1FknNh:b-mmq79t) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_batch_matmul_kernel.cc#L71)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Is there a check that needs to happen?
</blockquote></details>

I think for now we're just calling ~ more concrete tests will really be added when the CPU kernels are done 
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 10 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZpJCuBz9QWyyqzNhq:-O-jNk6N5_IXVMfy5y48:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_batch_norm_kernel.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Best to replace those uses with a `num_elements` call on the `TensorShape`
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 52 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-Zp9jg2zzEg2BLOoMi:-O-j5PT95Gu0gaXbOC6L:b90tt6x) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_batch_norm_kernel.cc#L52)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Still see REQUIRE
</blockquote></details>

I think I ran into issues with having multiple copies of the same file open on my VS code and the old one overwrote the changes ~ I don't know why else the changes rolled back. Should have double checked again though my bad. 

Should be fixed now though. 
___
*[`lib/kernels/test/src/test_batch_norm_kernel.cc` line 53 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hMAjX-Vf1rmqJwMii:-O-jNr2mEM3MtMeIaMjQ:b-4hvi10) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_batch_norm_kernel.cc#L53)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In the long term this shouldn't be a `std::vector` as `std::vector` loses all of the shape data that, e.g., `GenericTensorAccessor` has. We may need to add a host accessor that has the shape info? This doesn't need to get fixed this PR but should probably get addressed eventually
</blockquote></details>

Got it 
___
*[`lib/kernels/te [...]

2024-06-19 19:18 UTC, reyna-abhyankar requested changes
> Reviewed 30 of 30 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: all files reviewed, 32 unresolved discussions (waiting on @lockshaw and @oOTigger)

___
*[`lib/kernels/include/kernels/local_allocator.h` line 4 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X4XhF6f8_MZ9OAY10:-O-lvlzVCv_zDlHoF6Rd:baldpe6) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/include/kernels/local_allocator.h#L4)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Isn't LocalAllocator already a part of kernels?
</blockquote></details>

Well, it is because we moved it here for the purpose of this PR. But it also exists in `local-execution`. You can just remove it from there and replace all `#include "local-execution/local_allocator.h` with its kernels version instead
___
*[`lib/kernels/test/src/test_dropout.cc` line 54 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hPECCDUX4f6NNGMQd:-O-lvPWq0BA6S4AJn-86:bpmbyqs) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_dropout.cc#L54)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

I think so, as it's using the output_data accessor for backward pass
</blockquote></details>

You don't need to nest since the actual data for the output accessor doesn't matter, just that the tensor was created, and then you can pass the tensor in


<!-- Sent from Reviewable.io -->

2024-06-20 04:19 UTC, lockshaw requested changes
> Reviewed 1 of 13 files at r3, 1 of 14 files at r6, 30 of 30 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: all files reviewed, 20 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`lib/kernels/src/array_shape.cc` line 64 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hJ5PPE3JBMHm78gd5:-O-nqaxy6b0ORpYd8Ttd:b-z0y5bp) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L64)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

What about the call to reversed_dim_order in cuda_helper.cu?
</blockquote></details>

It seems like it's just used in this one place so maybe just reverse the dims here? If it's used more broadly then we can keep it, but it doesn't seem like an operation that's really all that generally useful

Also, I think this code snippet (i.e., `cudnnSetTensorDescriptorFromArrayShape`) is checking for parallel dims in that if statement, which shouldn't show up in an `ArrayShape` (not your fault, this is probably code that hasn't been updated with changes in `repo-refactor`). @reyna-abhyankar do you agree?
___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 54 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZpmVi5HVkp2_Kb9jJ:-O-nnMMWCdMk2gAjzWep:b-6sb8jd) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_cast_kernel.cc#L54)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Should this just be added into test_utils or should I add this somewhere more global in scope?
</blockquote></details>

Hmm, good question. I think they would be good to use in the rest of the runtime, so let's add them to the public interface of `kernels`
___
*[`lib/kernels/test/src/test_dropout.cc` line 48 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hP5wR3UfcnSZa6kyS:-O-noFADA2cKGJ-e6Xj-:b-jqrfbw) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_dropout.cc#L48)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think `count` just takes a container, not an iterator pair, right?
___
*[`lib/kernels/test/src/test_dropout.cc` line 61 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-nnwO66ayhxJN7g-ft:-O-nnwO66ayhxJN7g-fu:b9jd3od) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_dropout.cc#L61)):*
> ```cpp
>                 read_only_accessor_from_write_accessor(grad_input_data));
> 
>         int zero_count = [&]() {
> ```

Pull this (or more precisely, a `get_zero_count` lambda) out of the subcases so you don't have to duplicate it
___
*[`lib/kernels/test/src/test_pool_2d_kernels.cc` line 56 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-np6Ks4zsAHIk3g2PV:-O-np6Ks4zsAHIk3g2PW:bjdk8ku) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_pool_2d_kernels.cc#L56)):*
> ```cpp
>               read_only_accessor_from_write_accessor(output_data));
> 
>       SUBCASE("backward_kernel") {
> ```

Is a nested subcase necessary/useful here?
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 40 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-nrCOSAG6ZJLzW4Y0t:-O-nrCOSAG6ZJLzW4Y0u:b-3bczq1) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_softmax_kernel.cc#L40)):*
> ```cpp
> 
>       float max_input =
>           *std::max_element(host_input_data.begin(), host_input_data.end());
> ```

`maximum` from `utils/containers.h`
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 46 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-nrM16CR_VOGXQPWsM:-O-nrM16CR_VOGXQPWsN:b-uvs46e) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_softmax_kernel.cc#L46)):*
> ```cpp
>                                       [max_input](float acc, float val) {
>                                         return acc + std::exp(val - max_input);
>                                       });
> ```

Can this just be replaced by a `transform` into a `sum`? If so I'd probably prefer that--the functions in `utils/containers.h` generally make code more readable 



_Code quote:_
```cpp
      float sum_exp = std::accumulate(host_input_data.begin(),
                                      host_input_data.end(),
                                      0.0f,
                                      [max_input](float acc, float val) {
                                        return acc + std::exp(val - max_input);
                                      });
```
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 48 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-nrXPiDOd7ZRO6C1Fq:-O-nrXPiDOd7ZRO6C1Fr:b1vir9s) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_softmax_kernel.cc#L48)):*
> ```cpp
>                                       });
> 
>       for (std::size_t i = 0; i < input_accessor.shape.num_elements(); ++i) {
> ```

Remove for now and replace with cpu check later?
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 20 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-npqrMCEjc5DM-cOQL:-O-npqrMCEjc5DM-cOQM:bqwdeq0) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_split_kernel.cc#L20)):*
> ```cpp
> 
>     TensorShape input_shape = make_float_tensor_shape_from_legion_dims({100});
>     GenericTensorAccessorW input_accessor =
> ```

Does anything ever actually clean up the allocated memory? (Also a question for @reyna-abhyankar) 
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 43 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-npPk_Cyo4fLksJi8q:-O-npPka5QcnqD1k3BhL:bj356i9) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_split_kernel.cc#L43)):*
> ```cpp
>           num_outputs, std::vector<float>(50, 0));
>       for (int i = 0; i < num_outputs; i++) {
>         cudaMemcpy(host_output_data[i].data(),
> ```

Why are raw cuda memcpy's necessary here?
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 52 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-npSlV60P2Lcj59GhG:-O-npSlV60P2Lcj59GhH:b7nuiaj) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_split_kernel.cc#L52)):*
> ```cpp
>         int offset = std::accumulate(out_blk_sizes, out_blk_sizes + i, 0);
>         for (int j = 0; j < out_blk_sizes[i]; j++) {
>           CHECK(host_output_data[i][j] == host_input_data[offset + j]);
> ```

Leave out check and instead compare with the cpu implementation as otherwise the test code gets pretty complicated (same for the backward kernel below)
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 66 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-npdYV8AAieJoHO8H4:-O-npdYV8AAieJoHO8H5:bbj0ihi) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_split_kernel.cc#L66)):*
> ```cpp
>             stream,
>             grad_input_data,
>             const_cast<float const **>(output_ptrs.data()),
> ```

No const cast
___
*[`lib/kernels/test/src/test_utils.h` line 48 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-nq0NYBc5kxpwQ6e_0:-O-nq0NYBc5kxpwQ6e_1:b5xde7d) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45b [...]

2024-06-20 08:04 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: all files reviewed, 20 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/local_allocator.h` line 4 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-X4XhF6f8_MZ9OAY10:-O-oDT8-APhLRd8vO0wD:b1dd0hq) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/include/kernels/local_allocator.h#L4)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Well, it is because we moved it here for the purpose of this PR. But it also exists in `local-execution`. You can just remove it from there and replace all `#include "local-execution/local_allocator.h` with its kernels version instead
</blockquote></details>

Removed and replaced
___
*[`lib/kernels/src/array_shape.cc` line 64 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hJ5PPE3JBMHm78gd5:-O-oESx--0a0SWMVgavL:b-ogx7a5) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L64)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It seems like it's just used in this one place so maybe just reverse the dims here? If it's used more broadly then we can keep it, but it doesn't seem like an operation that's really all that generally useful

Also, I think this code snippet (i.e., `cudnnSetTensorDescriptorFromArrayShape`) is checking for parallel dims in that if statement, which shouldn't show up in an `ArrayShape` (not your fault, this is probably code that hasn't been updated with changes in `repo-refactor`). @reyna-abhyankar do you agree?
</blockquote></details>

Removed reversed_dim_order and just wrote out the function in cudnnSetTensorDescriptorFromArrayShape
___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 54 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZpmVi5HVkp2_Kb9jJ:-O-oeixxE7ZNaqxNpL0V:bs6z0qv) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_cast_kernel.cc#L54)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Hmm, good question. I think they would be good to use in the rest of the runtime, so let's add them to the public interface of `kernels`
</blockquote></details>

Is public interface of "kernels" the device.h file? And if so, is it the one in include or src?
___
*[`lib/kernels/test/src/test_dropout.cc` line 48 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hP5wR3UfcnSZa6kyS:-O-oFMbMB5a-LrdB0MH-:b-886gsx) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_dropout.cc#L48)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think `count` just takes a container, not an iterator pair, right?
</blockquote></details>

Fixed
___
*[`lib/kernels/test/src/test_dropout.cc` line 54 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hPECCDUX4f6NNGMQd:-O-oS_mA4yw35X23qalm:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_dropout.cc#L54)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

You don't need to nest since the actual data for the output accessor doesn't matter, just that the tensor was created, and then you can pass the tensor in
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_dropout.cc` line 61 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-nnwO66ayhxJN7g-ft:-O-oHcoE4pS0mUjDr2Cr:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_dropout.cc#L61)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull this (or more precisely, a `get_zero_count` lambda) out of the subcases so you don't have to duplicate it
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_pool_2d_kernels.cc` line 56 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-np6Ks4zsAHIk3g2PV:-O-oSblB8rFFxDIUlDzs:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_pool_2d_kernels.cc#L56)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is a nested subcase necessary/useful here?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 22 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-24TLEEAfgxBUsN1Eo:-O-oS6Rj1CBM7H84b7q3:bh53zpt) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_softmax_kernel.cc#L22)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

See my slack msg: 
actually instead of nesting the subcases, maybe just keep separate subcases and pull out the relevant tensor accessor code to before the forward kernel
because nesting means the backward will only be tested if the forward passes
</blockquote></details>

Okay, unnested all tests. In order to keep the kinda filler "contains_non_zero" check, I'm just passing in a random filled accessor as the output_accessor for most tests, otherwise none of the checks would pass as it's just being given empty data not updated after the forward kernel 
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 40 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-nrCOSAG6ZJLzW4Y0t:-O-oHuSx8SnIKr_OBrAI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_softmax_kernel.cc#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`maximum` from `utils/containers.h`
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 46 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-nrM16CR_VOGXQPWsM:-O-oKIAiDEE5beFvuWGL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_softmax_kernel.cc#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can this just be replaced by a `transform` into a `sum`? If so I'd probably prefer that--the functions in `utils/containers.h` generally make code more readable
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 48 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-nrXPiDOd7ZRO6C1Fq:-O-oKPz603vQC7qtFP9x:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_softmax_kernel.cc#L48)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove for now and replace with cpu check later?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 20 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-npqrMCEjc5DM-cOQL:-O-oKYVM-cf1Ak13xQsL:b-mxrcjh) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_split_kernel.cc#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Does anything ever actually clean up the allocated memory? (Also a question for @reyna-abhyankar)
</blockquote></details>

I saw that the old version of local-allocator that Reyna gave me a while ago made use of a field called ptrs and had a deallocator that cleaned everything up. Noticed that the most recent version of local-allocator though in local-execution had this rem [...]

2024-06-21 00:47 UTC, reyna-abhyankar submitted a review, later dismissed
> Reviewed 25 of 26 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 73 of 74 files reviewed, 20 unresolved discussions (waiting on @lockshaw and @oOTigger)

___
*[`lib/kernels/src/array_shape.cc` line 64 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hJ5PPE3JBMHm78gd5:-O-sDr4t2AbfVFG2Riy3:b-cel1iq) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L64)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Removed reversed_dim_order and just wrote out the function in cudnnSetTensorDescriptorFromArrayShape
</blockquote></details>

`ArrayShape` is a drop in replacement for `Legion::Domain`, so I think you're right. There shouldn't be a parallel dim. 
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 99 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-sFOWb3LEytUyEnsq_:-O-sFOWb3LEytUyEnsqa:b-v9fyan) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_attention_kernel.cc#L99)):*
> ```cpp
> 
>       /* I don't get why this only passes when it contains the value from the
>          forward passses output accessor? Shouldn't a randomly filled accessor
> ```

Is the accessor filled with zeros by any chance? Also I'm not sure if `contains_non_zero` is really the right check here since we don't have the true values for what the kernel should return (the CPU kernel test would validate this for us).  Honestly, you can just pass it as long as the kernel doesn't crash.
___
*[`lib/kernels/test/src/test_dropout.cc` line 54 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hPECCDUX4f6NNGMQd:-O-sBtsg50ZL_U96O2sZ:b-3tbeda) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_dropout.cc#L54)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But those tensors still have to be created before the forward subcase, right? `grad_input_data` and` output_data` can be initialized before the forward subcase.
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 22 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-24TLEEAfgxBUsN1Eo:-O-sC2bE06e2Ccwce5kv:bozlid5) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_softmax_kernel.cc#L22)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Okay, unnested all tests. In order to keep the kinda filler "contains_non_zero" check, I'm just passing in a random filled accessor as the output_accessor for most tests, otherwise none of the checks would pass as it's just being given empty data not updated after the forward kernel
</blockquote></details>

I think that's sufficient. As for nesting, see the other comment I had (i.e., any tensor accessor that's also needed by the backward pass can be initialized before the forward kernel subcase.
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 20 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-npqrMCEjc5DM-cOQL:-O-sCXNm6ck3Hk6SrRus:b-ypam4c) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_split_kernel.cc#L20)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

I saw that the old version of local-allocator that Reyna gave me a while ago made use of a field called ptrs and had a deallocator that cleaned everything up. Noticed that the most recent version of local-allocator though in local-execution had this removed? 

For now, the old local allocator with the deallocator is still there and being used to clean things up
</blockquote></details>

Allocator doesn't automatically clean anything up, @lockshaw we decided to leave this to the calling code. But if it's too much of a headache for the caller, then we can just add it into the destructor. Otherwise, we can just stick with what we have now: any allocation done by one of the kernels has to be cleaned up in the kernel code, and the caller can just free the pointers itself.


<!-- Sent from Reviewable.io -->

2024-06-21 21:25 UTC, lockshaw requested changes
> Reviewed 10 of 26 files at r13.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: all files reviewed, 21 unresolved discussions (waiting on @oOTigger)

___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 54 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZpmVi5HVkp2_Kb9jJ:-O-qqShU4Nu-T5jOrjFo:b-24h63d) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_cast_kernel.cc#L54)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Is public interface of "kernels" the device.h file? And if so, is it the one in include or src?
</blockquote></details>

It's just anything in `lib/kernels/include/kernels`
___
*[`lib/kernels/test/src/test_dropout.cc` line 54 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hPECCDUX4f6NNGMQd:-O-qqfMs0l2XDNMF1kNK:b-smmu0c) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_dropout.cc#L54)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It looks like it's still nested?
___
*[`lib/kernels/test/src/test_gather_kernels.cc` line 41 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-qqwVHEUlpzwOynmRg:-O-qqwVHEUlpzwOynmRh:bni4kqi) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_gather_kernels.cc#L41)):*
> ```cpp
> 
>     SUBCASE("backward_kernel") {
>       GenericTensorAccessorR device_output_accessor =
> ```

Pull the common accessors out of the subcases?
___
*[`lib/kernels/test/src/test_layer_norm_kernels.cc` line 56 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-qr56m6MFx0tP_tb2Z:-O-qr56nBKsQIfrAKWpc:bni4kqi) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_layer_norm_kernels.cc#L56)):*
> ```cpp
> 
>     SUBCASE("backward_kernel") {
>       GenericTensorAccessorR output_accessor =
> ```

Pull the common accessors out of the subcases?
___
*[`lib/kernels/test/src/test_partition_kernel.cc` line 55 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-qrBjv9mkD8TWLh3tf:-O-qrBjv9mkD8TWLh3tg:bcgjvre) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_partition_kernel.cc#L55)):*
> ```cpp
> 
>       std::vector<float> expected_grad_input_data(
>           output_accessor.shape.num_elements(), 2.0f);
> ```

Why this change?
___
*[`lib/kernels/test/src/test_pool_2d_kernels.cc` line 61 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-qrQcpCltjAYeOLlIT:-O-qrQcpCltjAYeOLlIU:b-h2u346) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_pool_2d_kernels.cc#L61)):*
> ```cpp
>     SUBCASE("backward_kernel") {
>       GenericTensorAccessorW output_data =
>           create_random_filled_accessor_w(output_shape, allocator);
> ```

Pull out the common accessor?


<!-- Sent from Reviewable.io -->

2024-06-23 09:35 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 48 of 85 files reviewed, 21 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 274 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-NzC3THM-IFOMx3dcQea:-O03QC2735ywE2r68UJL:b-79kr73) ([raw file](https://github.com/flexflow/FlexFlow/blob/eec114eaac45b603ca4a12f1233bafe6f6eef580/lib/kernels/src/cuda/cuda_helper.cu#L274)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can/should we move these manual instantiations over to use the stuff in `datatype_dispatch.h`?
</blockquote></details>

no clue if I did this right lol
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 134 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95GVi-QexYSjWgFBJ:-O02QXAY2zwjx71Ubzxq:bvnc6n8) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L134)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I ended up bringing back in order for things to properly build, but am not sure if this is allowed. 

The issue is that in batch_norm.cc in local-execution, the call to init_kernel does not pass in a stream as an argument in init_kernel. I was unsure if we're allowed to create in local-execution which we could pass into the call as I didn't see streams called / used anywhere in local-execution.

I also didn't realize this earlier, but no other kernels have a stream passed into their init_kernel. Batch norm's init_kernel is special as it includes two calls to assign_kernel, both of which require a stream. 

I thus ended up reverting things, to having a stream created in the init_kernel as well as destroying the stream at the end of the function. I wasn't sure if it would be better to return the stream that's created in init_kernel back, but that lead to other issues in local-execution as well, which I was too scared to really touch / modify. 
___
*[`lib/kernels/test/src/test_attention_kernel.cc` line 99 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-sFOWb3LEytUyEnsq_:-O02kYhG-jW0ggJDTlNK:bxnr39w) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_attention_kernel.cc#L99)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Is the accessor filled with zeros by any chance? Also I'm not sure if `contains_non_zero` is really the right check here since we don't have the true values for what the kernel should return (the CPU kernel test would validate this for us).  Honestly, you can just pass it as long as the kernel doesn't crash.
</blockquote></details>

Idk why, but moving the output_accessor creation outside of both fixed the issue. 
___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 54 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-ZpmVi5HVkp2_Kb9jJ:-O03LSvw9xGKzdlgGkeF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/9e4bda2896cb6eddb92338f0d8ecb21a21b616d3/lib/kernels/test/src/test_cast_kernel.cc#L54)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It's just anything in `lib/kernels/include/kernels`
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_dropout.cc` line 54 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hPECCDUX4f6NNGMQd:-O02lKAXAp0HI9s1mcmZ:b2k8og3) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_dropout.cc#L54)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It looks like it's still nested?
</blockquote></details>

Originally wanted to keep this unnested but fixed after our discussion on Friday
___
*[`lib/kernels/test/src/test_gather_kernels.cc` line 41 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-qqwVHEUlpzwOynmRg:-O02m5H9BYGB6gSfC_gF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_gather_kernels.cc#L41)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull the common accessors out of the subcases?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_layer_norm_kernels.cc` line 56 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-qr56m6MFx0tP_tb2Z:-O02mJ7YE9Cw8hU4x7mq:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_layer_norm_kernels.cc#L56)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull the common accessors out of the subcases?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_partition_kernel.cc` line 55 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-qrBjv9mkD8TWLh3tf:-O02mPhyCjZ4KwIN_XHw:b-covybx) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_partition_kernel.cc#L55)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

It's because input_accessor is no longer in same scope 
___
*[`lib/kernels/test/src/test_pool_2d_kernels.cc` line 61 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-qrQcpCltjAYeOLlIT:-O02mtIKCnnYnmDNVS9O:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_pool_2d_kernels.cc#L61)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull out the common accessor?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_softmax_kernel.cc` line 22 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-24TLEEAfgxBUsN1Eo:-O02muXzDknW5l2-Bvwz:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/test/src/test_softmax_kernel.cc#L22)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I think that's sufficient. As for nesting, see the other comment I had (i.e., any tensor accessor that's also needed by the backward pass can be initialized before the forward kernel subcase.
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 20 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-npqrMCEjc5DM-cOQL:-O03QOvUDUu4ZJjX66Oo:b-zdog3d) ([raw file](https://github.com/flexflow/FlexFlow/blob/d0a3ea92cec95bf6052f71c005d45bb5ed2a5d4f/lib/kernels/test/src/test_split_kernel.cc#L20)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Allocator doesn't automatically clean anything up, @lockshaw we decided to leave this to the calling code. But if it's too much of a headache for the caller, then we can just add it into the destructor. Otherwise, we can just stick with what we have now: any allocation done by one of the kernels has to be cleaned up in the kernel code, and the caller can just free the pointers itself.
</blockquote></details>

Just using the old local_allocator's deallocator for now 


<!-- Sent from Reviewable.io -->

2024-06-23 16:00 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 48 of 85 files reviewed, 19 unresolved discussions (waiting on @lockshaw and @oOTigger)

___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 14 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hQhXQ-Rw076TCqlPM:-O04ofWTDKtPymIfz4Vl:bbptdoj) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_cast_kernel.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`from_legion_dims` is probably clearer, but not critical
</blockquote></details>

@oOTigger 


<!-- Sent from Reviewable.io -->

2024-06-23 21:25 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 48 of 85 files reviewed, 19 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 14 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hQhXQ-Rw076TCqlPM:-O05z5w88hS9IUHHAIOU:bqgchr7) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_cast_kernel.cc#L14)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

@oOTigger
</blockquote></details>

I think you were looking at an old version? Everything should be denoted with make_float_tensor_shape_from_legion_dims? 


<!-- Sent from Reviewable.io -->

2024-06-24 01:54 UTC, lockshaw requested changes
> Reviewed 6 of 26 files at r13, 37 of 37 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: all files reviewed, 25 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/local_allocator.h` line 6 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06nJcc-CTw-TDP_fF7:-O06nJcc-CTw-TDP_fF8:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/include/kernels/local_allocator.h#L6)):*
> ```objc
> namespace FlexFlow {
> 
> struct LocalAllocator : public IAllocator {
> ```





_Suggestion:_
```objc
LocalCudaAllocator
```
___
*[`lib/kernels/include/kernels/local_allocator.h` line 22 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06n8NN5alMtQebm99y:-O06n8NN5alMtQebm99z:b-hb060c) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/include/kernels/local_allocator.h#L22)):*
> ```objc
> Allocator get_local_memory_allocator();
> 
> struct LocalCPUAllocator : public IAllocator {
> ```

Why is this part of this PR? I guess there's not an issue with it being included, but I don't think it should be used here?
___
*[`lib/kernels/include/kernels/managed_handle.h` line 14 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06oJgt4qU1Aeve-n1h:-O06oJgt4qU1Aeve-n1i:b-26qyvj) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/include/kernels/managed_handle.h#L14)):*
> ```objc
> 
>   ManagedHandle(ManagedHandle const &) = delete;
>   ManagedHandle(ManagedHandle &&) = delete;
> ```

Why is move construction disabled? Should copy-assignment be deleted?
___
*[`lib/kernels/include/kernels/managed_handle.h` line 19 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06nYNLBb-51bWDR0AK:-O06nYNLBb-51bWDR0AL:bg4qk1u) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/include/kernels/managed_handle.h#L19)):*
> ```objc
> };
> 
> ManagedHandle get_managed_handle();
> ```

Not really necessary here? `ManagedHandle` already has a default constructor



_Code quote:_
```objc
ManagedHandle get_managed_handle();
```
___
*[`lib/kernels/include/kernels/managed_stream.h` line 14 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06oBnW4thzqbYGvnOa:-O06oBnW4thzqbYGvnOb:b-26qyvj) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/include/kernels/managed_stream.h#L14)):*
> ```objc
> 
>   ManagedStream(ManagedStream const &) = delete;
>   ManagedStream(ManagedStream &&) = delete;
> ```

Why is move construction disabled? Should copy-assignment be deleted?
___
*[`lib/kernels/include/kernels/managed_stream.h` line 19 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06ndVU5y3cMDxNnwfn:-O06ndVU5y3cMDxNnwfo:b35bwru) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/include/kernels/managed_stream.h#L19)):*
> ```objc
> };
> 
> ManagedStream get_managed_stream();
> ```

Not really necessary here? `ManagedStream` already has a default constructor
___
*[`lib/kernels/src/array_shape.cc` line 64 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hJ5PPE3JBMHm78gd5:-O06njijDzm6mbELIx_M:b6pz43u) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L64)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

`ArrayShape` is a drop in replacement for `Legion::Domain`, so I think you're right. There shouldn't be a parallel dim.
</blockquote></details>

@reyna-abhyankar Can we get either a fix or an issue created for this?
___
*[`lib/kernels/src/local_allocator.cc` line 31 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06p60F6E6SwDmnIqh7:-O06p60F6E6SwDmnIqh8:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/local_allocator.cc#L31)):*
> ```cpp
> void *LocalCPUAllocator::allocate(size_t requested_memory_size) {
>   void *ptr = malloc(requested_memory_size);
>   if (ptr) {
> ```





_Suggestion:_
```cpp
  if (ptr != nullptr) {
```
___
*[`lib/kernels/src/local_allocator.cc` line 46 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06ow-4BF6GBJ9zn9qf:-O06ow-4BF6GBJ9zn9qg:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/local_allocator.cc#L46)):*
> ```cpp
>   } else {
>     throw std::runtime_error(
>         "Deallocating a pointer that was not allocated by this allocator");
> ```





_Suggestion:_
```cpp
       "Deallocating a pointer that was not allocated by this Allocator");
```
___
*[`lib/kernels/src/local_allocator.cc` line 54 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06omdt9QeLLD8Bw88n:-O06omdt9QeLLD8Bw88o:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/local_allocator.cc#L54)):*
> ```cpp
>     void *ptr = *it;
>     it++;
>     this->deallocate(ptr);
> ```





_Suggestion:_
```cpp
  for (void *ptr : this->ptrs) {
    this->deallocate(ptr);
```
___
*[`lib/kernels/src/managed_handle.cc` line 9 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06nxxB9xcJPD6KGdvs:-O06nxxB9xcJPD6KGdvt:b4zv9rv) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/managed_handle.cc#L9)):*
> ```cpp
> 
>   cudnnCreate(&handle.dnn);
>   cublasCreate(&handle.blas);
> ```

Do these functions also need to be checked, e.g., by `checkCUDA`?



_Code quote:_
```cpp
  cudnnCreate(&handle.dnn);
  cublasCreate(&handle.blas);
```
___
*[`lib/kernels/src/managed_handle.cc` line 15 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06o2ePD1eQxaZ5jwLf:-O06o2ePD1eQxaZ5jwLg:b4zv9rv) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/managed_handle.cc#L15)):*
> ```cpp
> ManagedHandle::~ManagedHandle() {
>   cudnnDestroy(handle.dnn);
>   cublasDestroy(handle.blas);
> ```

Do these functions also need to be checked, e.g., by `checkCUDA`?



_Code quote:_
```cpp
  cudnnDestroy(handle.dnn);
  cublasDestroy(handle.blas);
```
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 283 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06v0jG-iOlBNMBMLC3:-O06v0jG-iOlBNMBMLC4:b8tyf3v) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/cuda/cuda_helper.cu#L283)):*
> ```Cuda
>         static_cast<ValueType *>(ptr), size, val);
>   }
> };
> ```

As a side note, `real_type` should really be renamed to `real_type_t` to follow naming conventions, @oOTigger can you create a separate PR to do that renaming?

The code below I think should work, if it does it should get propagated to the other kernel structs below in this file



_Suggestion:_
```Cuda
template <DataType DT, typename T = real_type<DT>>
struct AssignKernel {
  void operator()(T *ptr, size_t size, T value) const {
    assign_kernel<ValueType><<<GET_BLOCKS(size), CUDA_NUM_THREADS>>>(
        ptr, size, value);
  }
};
```
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 285 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06wTJ_BWoG0u304PDb:-O06wTJ_BWoG0u304PDc:bjwdvwb) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/cuda/cuda_helper.cu#L285)):*
> ```Cuda
> };
> 
> void dispatch_assign(DataType type, void *ptr, size_t size, void *value) {
> ```

Make sure these get exposed through the header files.
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 134 at r6](https://reviewable.io/reviews/flexflow/Flex [...]

2024-06-24 02:20 UTC, lockshaw commented
*[`flake.lock` line 84 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O071mKeEzPK-WD6hDNj:-O071mKeEzPK-WD6hDNk:bgs8bb7) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/flake.lock#L84)):*
> ```JSON
>   "root": "root",
>   "version": 7
> }
> ```

Btw can you tell your editor to stop messing with whitespace in files, or alternatively don't push those changes? It unnecessarily clutters up the diff


<!-- Sent from Reviewable.io -->

2024-06-24 02:27 UTC, lockshaw commented
*[`flake.lock` line 84 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O071mKeEzPK-WD6hDNj:-O073Gzq6z3x9adAK9o6:bnvlu5u) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/flake.lock#L84)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Btw can you tell your editor to stop messing with whitespace in files, or alternatively don't push those changes? It unnecessarily clutters up the diff
</blockquote></details>

You should be able to set up whatever editorconfig integration your editor uses: https://editorconfig.org/


<!-- Sent from Reviewable.io -->

2024-06-25 01:20 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 45 of 89 files reviewed, 26 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`flake.lock` line 84 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O071mKeEzPK-WD6hDNj:-O0BtA_qEAdDTOCLKj3t:b-z77b3z) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/flake.lock#L84)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You should be able to set up whatever editorconfig integration your editor uses: https://editorconfig.org/
</blockquote></details>

Is there a .editorconfig file that I'm supposed to be matching somewhere? 

It looks like the default one is below. Is this fine? 

root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

[{CMakeLists.txt,*.cmake}]
indent_style = space
indent_size = 2

[*.{cc,h,cu,cpp}]
indent_style = space
indent_size = 2

[*.py]
indent_style = space
indent_size = 4

[*.toml]
indent_style = space
indent_size = 2
___
*[`lib/kernels/include/kernels/managed_handle.h` line 14 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06oJgt4qU1Aeve-n1h:-O0BVNsFDtwjG_j4d9hf:b-lc7h5b) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/include/kernels/managed_handle.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is move construction disabled? Should copy-assignment be deleted?
</blockquote></details>

I thought it's considered safer to disable these when dealing with memory, to avoid things like multiple deletions. 

I noticed that's what the Allocator's had so thought it would be safe to transfer over. 
___
*[`lib/kernels/include/kernels/managed_handle.h` line 19 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06nYNLBb-51bWDR0AK:-O080yex-5sLLPBaGtG_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/include/kernels/managed_handle.h#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not really necessary here? `ManagedHandle` already has a default constructor
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 283 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06v0jG-iOlBNMBMLC3:-O0BOiRu3qkPUNXCOgRM:bwelhha) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/cuda/cuda_helper.cu#L283)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

As a side note, `real_type` should really be renamed to `real_type_t` to follow naming conventions, @oOTigger can you create a separate PR to do that renaming?

The code below I think should work, if it does it should get propagated to the other kernel structs below in this file
</blockquote></details>

This code gave issues regarding dispatch. I ended up just sticking with original code but changing to make use of real_type 
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 285 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06wTJ_BWoG0u304PDb:-O0BOubt6406j11yVBrc:b-x10y5r) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/cuda/cuda_helper.cu#L285)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Make sure these get exposed through the header files.
</blockquote></details>

Done. 

I exposed everything except dispatch_print_tensor_kernel and ended up reverting that function back to it's old template format. 

For some reason, the compiler didn't like me exposing the print_tensor kernel and got a long list of cascading errors. It says it has something to do with ff_handle and nccl.h but I wasn't really able to figure out how to fix. 
___
*[`lib/kernels/test/src/test_cast_kernel.cc` line 10 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06jH5Z7Md5bVOxYAPg:-O0B9E-96y2ABAXDW27e:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/test/src/test_cast_kernel.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`m` have a bit of an overloaded meaning, and `managed_stream` is substantially clearer. Also, `ManagedFFStream` makes it much clearer what stream you're talking about
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_dropout.cc` line 20 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06jzX83oIEYqcRU39T:-O0BAPZL4KDCVEnmSzEn:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/test/src/test_dropout.cc#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Clearer names are really preferred: the codebase is going to have many "handle objects", so naming something `ManagedHandle` makes the code really difficult to read
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_partition_kernel.cc` line 52 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06ks7FD-WvYtiIHS48:-O0B_9wa2PYdQJa9d_kv:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_partition_kernel.cc#L52)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is the `host_grad_input_data` being read from the `output_accessor`? Either the names here are incredibly confusing or something weird is going on: the output of the backward kernel should generally be referred to as `input_grad`, not as `output`, as that would confuse things with the `output` tensor generated in the forward pass
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_partition_kernel.cc` line 55 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-qrBjv9mkD8TWLh3tf:-O0B_AESEp-H7Jokvxj4:b-r0xdv5) ([raw file](https://github.com/flexflow/FlexFlow/blob/35071af86bf715a5a10a855cb7aed9b659a3660e/lib/kernels/test/src/test_partition_kernel.cc#L55)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

See above comment, something weird seems to be going on with the names here
</blockquote></details>

Done.

Namings should be correct. Added back in some accessors in the backward_kernels to be explicit on grad accessors 
___
*[`lib/kernels/test/src/test_replicate_kernel.cc` line 10 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06lVEjDJn-Fxyypr49:-O0B_CE57hbGgzwvstVk:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/test/src/test_replicate_kernel.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

"shape" by itself is a bit unclear, also wouldn't hurt to use this in the other tests where you just have "shape"--even if you don't want the second `output_shape`, replacing `shape` with `input_shape` should already help quite a bit
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_utils.h` line 53 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06qC1-0YoCoV_zabsk:-O0BURGK2rxhnrpMzWow:b-s2x5d) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/test/src/test_utils.h#L53)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are we using `memcpy`? Can't you just use `vector`'s constructor?
</blockquote></details>

Done. => also removed as will add back in when adding cpu kernels 
___
*[`lib/kernels/test/src/test_utils.h` line 58 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06sk8x-sNJm4DwpyJt:-O0BUf_Z5IQXw2 [...]

2024-06-25 02:13 UTC, lockshaw commented
*[`flake.lock` line 84 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O071mKeEzPK-WD6hDNj:-O0C9p1p0q0l6RQDT7xs:b-theapn) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/flake.lock#L84)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Is there a .editorconfig file that I'm supposed to be matching somewhere? 

It looks like the default one is below. Is this fine? 

root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

[{CMakeLists.txt,*.cmake}]
indent_style = space
indent_size = 2

[*.{cc,h,cu,cpp}]
indent_style = space
indent_size = 2

[*.py]
indent_style = space
indent_size = 4

[*.toml]
indent_style = space
indent_size = 2
</blockquote></details>

Yes, just the one in the root of the repository: https://github.com/flexflow/FlexFlow/blob/repo-refactor/.editorconfig. If you enable whatever editorconfig support your editor has it should automatically find it and apply those settings


<!-- Sent from Reviewable.io -->

2024-06-25 02:39 UTC, lockshaw requested changes
> Reviewed 44 of 44 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: all files reviewed, 20 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`.proj.toml` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CF1iI5DXp5odjrCKQ:-O0CF1iI5DXp5odjrCKR:b6l580y) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/.proj.toml#L18)):*
> ```TOML
> 
> test_targets = [
>   "kernels-tests",
> ```

What does this do on machines without GPUs? (also, what does this do on machines with GPUs, doesn't it need nixGL?)
___
*[`lib/kernels/include/kernels/managed_handle.h` line 14 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06oJgt4qU1Aeve-n1h:-O0CAKiB4KfSfhRVxEXN:b8ut8m2) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/include/kernels/managed_handle.h#L14)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

I thought it's considered safer to disable these when dealing with memory, to avoid things like multiple deletions. 

I noticed that's what the Allocator's had so thought it would be safe to transfer over.
</blockquote></details>

But move-construction is exactly the operation that should be allowed if you don't want multiple deletions, right? And copy-assignment is something you wouldn't want allowed, but I'm not seeing deleted. I think you'd want move construction and move assignment enabled, and copy construction and copy assignment disabled, just like unique_ptr
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 8 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CAghj5AyFT7G6AmkW:-O0CAghj5AyFT7G6AmkX:br2uews) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> struct ManagedPerDeviceFFHandle {
> ```

This appears duplicated with the file `managed_handle.h` which seems to still exist?
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 14 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CDqAw4gtx_OdHBm_K:-O0CDqAx1tVanWweAFgd:b-vfp860) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/src/local_cuda_allocator.cc#L14)):*
> ```cpp
> void LocalCudaAllocator::deallocate(void *ptr) {
>   checkCUDA(cudaFree(ptr));
>   this->ptrs.erase(ptr);
> ```

Add a check if the pointer is not in ptrs?
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CDnNE29Puo5RsZxGX:-O0CDnNE29Puo5RsZxGY:b-xtzlqu) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/src/local_cuda_allocator.cc#L18)):*
> ```cpp
> 
> LocalCudaAllocator::~LocalCudaAllocator() {
>   for (auto it = this->ptrs.begin(); it != this->ptrs.end();) {
> ```

Replace with range-based loop
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 25 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CE-2YEqyYhYBKR4hf:-O0CE-2YEqyYhYBKR4hg:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/src/local_cuda_allocator.cc#L25)):*
> ```cpp
> }
> 
> Allocator get_local_cuda_memory_allocator() {
> ```





_Suggestion:_
```cpp
Allocator create_local_cuda_memory_allocator() {
```
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 283 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06v0jG-iOlBNMBMLC3:-O0CFBde-Hxs6wtPKicv:bj9a7wt) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/cuda/cuda_helper.cu#L283)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

This code gave issues regarding dispatch. I ended up just sticking with original code but changing to make use of real_type
</blockquote></details>

The `static_cast`ing in your version is very messy, so I'd prefer to adapt the version above. If you want help resolving the errors let me know, but just dumping everything to a void pointer and then doing a convoluted set of casts may pass the compiler but often doesn't actually result in the behavior you want
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 285 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06wTJ_BWoG0u304PDb:-O0CFbE49n3aHC3WCIoB:bzfsmsq) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/cuda/cuda_helper.cu#L285)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done. 

I exposed everything except dispatch_print_tensor_kernel and ended up reverting that function back to it's old template format. 

For some reason, the compiler didn't like me exposing the print_tensor kernel and got a long list of cascading errors. It says it has something to do with ff_handle and nccl.h but I wasn't really able to figure out how to fix.
</blockquote></details>

What's the error message?
___
*[`lib/kernels/test/src/test_cuda.cc` line 1 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CFm7z4T_QvOQSneOt:-O0CFm7z4T_QvOQSneOu:b-q5xmmk) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_cuda.cc#L1)):*
> ```cpp
> #include "test_utils.h"
> ```

Why remove doctest?
___
*[`lib/kernels/test/src/test_pool_2d_kernels.cc` line 54 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CCGZg8sN3aoziU5Wq:-O0CCGZg8sN3aoziU5Wr:b-whmxjj) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_pool_2d_kernels.cc#L54)):*
> ```cpp
>                                       output_accessor.ptr);
> 
>       std::vector<float> host_output_accessor =
> ```

This isn't an accessor?
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 26 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CCq4A9BWx2YBLvamZ:-O0CCq4A9BWx2YBLvam_:b-9m3n91) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_split_kernel.cc#L26)):*
> ```cpp
> 
>       std::vector<float *> output_ptrs(num_outputs);
>       for (int i = 0; i < num_outputs; i++) {
> ```

Replace loop with `repeat`?
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 43 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CCtBk8Stem2hr9Wg_:-O0CCtBk8Stem2hr9Wga:b-9m3n91) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_split_kernel.cc#L43)):*
> ```cpp
>     SUBCASE("backward_kernel") {
>       std::vector<float *> output_grad_ptrs(num_outputs);
>       for (int i = 0; i < num_outputs; i++) {
> ```

Replace loop with `repeat`?
___
*[`lib/kernels/test/src/test_utils.h` line 4 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CD60776JRqlanfxP0:-O0CD60776JRqlanfxP1:b6cmlt4) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_utils.h#L4)):*
> ```objc
> #define _FLEXFLOW_KERNELS_TEST_UTILS
> 
> #include "doctest/doctest.h"
> ```

Why? I don't see doctest being used in this file?
___
*[`lib/kernels/test/src/test_utils.cc` line 90 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06suc-BL3cmPhmJmGO:-O0CE7U2C28gLKt7agtM:bwy61tf) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/test/src/test_utils.cc#L90)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still seeing it here as of the latest revision?
___
*[`lib/kernels/src/local_allocator. [...]

2024-06-25 23:42 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 59 of 90 files reviewed, 19 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`.proj.toml` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CF1iI5DXp5odjrCKQ:-O0Cfn5W6dlNFEQga2Uu:b7e201x) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/.proj.toml#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What does this do on machines without GPUs? (also, what does this do on machines with GPUs, doesn't it need nixGL?)
</blockquote></details>

If you're asking if things build fine when on a machine with GPU's => proj test builds fine but runs into an error of: 

CUDA failure: CUDA driver version is insufficient for CUDA runtime version (35)

when actually trying to test things. 

Everything is fine though when using: 
NIXPKGS_ALLOW_UNFREE=1 nix run --impure github:nix-community/nixGL -- build/lib/kernels/test/kernels-tests
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 8 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CAghj5AyFT7G6AmkW:-O0CPE8XBx2s-o3ZfGu5:bhg34lq) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This appears duplicated with the file `managed_handle.h` which seems to still exist?
</blockquote></details>

Deleted managed_handle.h
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 14 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CDqAw4gtx_OdHBm_K:-O0CgRSfCow1oF8Uzo5A:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/src/local_cuda_allocator.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add a check if the pointer is not in ptrs?
</blockquote></details>

Done.
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CDnNE29Puo5RsZxGX:-O0CdxQu2K1Dq5MSEsve:bpyry2c) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/src/local_cuda_allocator.cc#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Replace with range-based loop
</blockquote></details>

Same issue as mentioned on local_allocator.cc ~ When I change this to use a range-based loop I get the following issue: 

kernels-tests: /home/dylanlim/ff/pr/622/lib/kernels/src/local_cuda_allocator.cc:13: virtual void FlexFlow::LocalCudaAllocator::deallocate(void*): Assertion `false' failed.

/home/dylanlim/ff/pr/622/lib/kernels/test/src/test_attention_kernel.cc:8: FATAL ERROR: test case CRASHED: SIGABRT - Abort (abnormal termination) signal

and then a bunch of out of bounds memory accesses are printed. ie: 

фY�LCvalid argument (1)
  �Y�
  �
  ��
  
  PZ�
  p_�
  
  �Y�
  �gXb�
  Ћ
  �^�
  ��
  �`�
  
  �`�
  p��
  
  b�
  �
  A
  ��
  
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 25 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CE-2YEqyYhYBKR4hf:-O0Cevnh0e-7DuYgrZ-K:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/src/local_cuda_allocator.cc#L25)):*
> ```cpp
> }
> 
> Allocator get_local_cuda_memory_allocator() {
> ```

Done.
___
*[`lib/kernels/src/cuda/cuda_helper.cu` line 283 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06v0jG-iOlBNMBMLC3:-O0GlbVRDCBP899kH0-i:bg0eo6w) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/cuda/cuda_helper.cu#L283)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The `static_cast`ing in your version is very messy, so I'd prefer to adapt the version above. If you want help resolving the errors let me know, but just dumping everything to a void pointer and then doing a convoluted set of casts may pass the compiler but often doesn't actually result in the behavior you want
</blockquote></details>

Ended up just getting rid of this for a later PR, feel like I'm spending too much time and no progress and still not fully sure why not working 
___
*[`lib/kernels/test/src/test_cuda.cc` line 1 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CFm7z4T_QvOQSneOt:-O0CQ9IeAgPYB6ZfwJ0R:b-adfxgb) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_cuda.cc#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why remove doctest?
</blockquote></details>

Since all test files include "doctest" I thought it'd maybe be cleaner to just include doctest in "test_utils"?
___
*[`lib/kernels/test/src/test_pool_2d_kernels.cc` line 54 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CCGZg8sN3aoziU5Wq:-O0CQWM7EMh_qoadzZgg:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_pool_2d_kernels.cc#L54)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This isn't an accessor?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 26 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CCq4A9BWx2YBLvamZ:-O0CfK6K1hcm8bJK9M8z:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_split_kernel.cc#L26)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Replace loop with `repeat`?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_split_kernel.cc` line 43 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CCtBk8Stem2hr9Wg_:-O0CfKLC6-RFQUc7icHJ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_split_kernel.cc#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Replace loop with `repeat`?
</blockquote></details>

Done.
___
*[`lib/kernels/test/src/test_utils.h` line 4 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CD60776JRqlanfxP0:-O0CfLJz5xG0-jDqOS40:bjt49l3) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_utils.h#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why? I don't see doctest being used in this file?
</blockquote></details>

Thought since all tests use doctest I could clean things by putting it in test_utils, but I guess that's bad practice. I reverted. 
___
*[`lib/kernels/test/src/test_utils.cc` line 90 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06suc-BL3cmPhmJmGO:-O0CfkhZ8FC3tJ32rP5q:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/test/src/test_utils.cc#L90)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm still seeing it here as of the latest revision?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/local_allocator.h` line 8 at r15](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CEyb50JAAGF1WBIuX:-O0CRE9yC-IwhW3IMufK:b-5voycr) ([raw file](https://github.com/flexflow/FlexFlow/blob/66b0736f038528c9dddacaa13cfe84d3190bcf53/lib/local-execution/include/local-execution/local_allocator.h#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why do we have both `LocalAllocator` and `LocalCudaAllocator`?
</blockquote></de [...]

2024-06-26 04:36 UTC, lockshaw requested changes
> Reviewed 31 of 31 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: all files reviewed, 16 unresolved discussions (waiting on @oOTigger and @reyna-abhyankar)

___
*[`.proj.toml` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CF1iI5DXp5odjrCKQ:-O0HgZQ62pYzr7bH3cyj:beglfud) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/.proj.toml#L18)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

If you're asking if things build fine when on a machine with GPU's => proj test builds fine but runs into an error of: 

CUDA failure: CUDA driver version is insufficient for CUDA runtime version (35)

when actually trying to test things. 

Everything is fine though when using: 
NIXPKGS_ALLOW_UNFREE=1 nix run --impure github:nix-community/nixGL -- build/lib/kernels/test/kernels-tests
</blockquote></details>

Let's leave this out of `test_targets` then for now until we have a fix so `proj` doesn't crash on machines without a GPU
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 15 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HoRyS0aEd2Ow0YUaI:-O0HoRyS0aEd2Ow0YUaJ:brclkz) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L15)):*
> ```objc
>   ~ManagedPerDeviceFFHandle();
> 
>   ManagedPerDeviceFFHandle(ManagedPerDeviceFFHandle &&other) noexcept
> ```

These implementations should be in the `.cc` file
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 16 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0Ho1YG1nHMlenktWuC:-O0Ho1YG1nHMlenktWuD:b-2o2i24) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L16)):*
> ```objc
> 
>   ManagedPerDeviceFFHandle(ManagedPerDeviceFFHandle &&other) noexcept
>       : handle(std::move(other.handle)) {}
> ```

Right now you're going to run into issues with the value being moved from double-freeing your objects I think. Making this a pointer (1) makes it easy to fix your double-free problem, and (2) as a nice side effect probably makes copying cheaper

Note that you'll need to modify your deconstructor accordingly, mostly along the lines of the implementation in `ManagedFFStream` but with slightly different behavior in terms of the actual `checkCUDA(freething(...))` calls



_Suggestion:_
```objc
  PerDeviceFFHandle *handle;

  ManagedPerDeviceFFHandle();

  ~ManagedPerDeviceFFHandle();

  ManagedPerDeviceFFHandle(ManagedPerDeviceFFHandle &&other) noexcept
      : handle(std::exchange(other.handle, nullptr)) {}
```
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 18 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HoaMp89oSsjNKi6Oz:-O0HoaMp89oSsjNKi6P-:b-cgey13) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L18)):*
> ```objc
>       : handle(std::move(other.handle)) {}
> 
>   ManagedPerDeviceFFHandle &
> ```

Probably a good idea to test the move behaviors of both this and `ManagedFFStream` just to make sure you actually got the implementations correct. I think you should just be able to (in your tests), declare an object, move from it, and then check the state of both the moved-from object and the moved to object
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 23 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0Hms1o3ksO8t8A8SlH:-O0Hms1pDTrlEjX-KbH2:bisyf0c) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L23)):*
> ```objc
>       handle = std::move(other.handle);
>     }
>     return *this;
> ```

Otherwise you'll double free your handle things



_Suggestion:_
```objc
    using std::swap;
    
    swap(this->handle, other.handle);
    
    return *this;
```
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 30 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HnAq64JBdKIEQvXNz:-O0HnAq64JBdKIEQvXO-:b-h28mjs) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L30)):*
> ```objc
>   ManagedPerDeviceFFHandle &
>       operator=(ManagedPerDeviceFFHandle const &) = delete;
> };
> ```

Just for consistency we tend to layout struct definitions like this--obviously there's some variation, but trying to follow the convention makes the codebase a bit more approachable



_Suggestion:_
```objc
struct ManagedPerDeviceFFHandle {
public:
  ManagedPerDeviceFFHandle();

  ManagedPerDeviceFFHandle(ManagedPerDeviceFFHandle const &) = delete;
  ManagedPerDeviceFFHandle &
      operator=(ManagedPerDeviceFFHandle const &) = delete;
      
  ManagedPerDeviceFFHandle(ManagedPerDeviceFFHandle &&other);
  ManagedPerDeviceFFHandle &
      operator=(ManagedPerDeviceFFHandle &&other) noexcept;
      
  ~ManagedPerDeviceFFHandle();
  
  PerDeviceFFHandle const &raw_handle() const;
private:
    PerDeviceFFHandle *handle;
};
```
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CDnNE29Puo5RsZxGX:-O0HilDg5GtxDZeA3FiE:b-s5ga62) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/src/local_cuda_allocator.cc#L18)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Same issue as mentioned on local_allocator.cc ~ When I change this to use a range-based loop I get the following issue: 

kernels-tests: /home/dylanlim/ff/pr/622/lib/kernels/src/local_cuda_allocator.cc:13: virtual void FlexFlow::LocalCudaAllocator::deallocate(void*): Assertion `false' failed.

/home/dylanlim/ff/pr/622/lib/kernels/test/src/test_attention_kernel.cc:8: FATAL ERROR: test case CRASHED: SIGABRT - Abort (abnormal termination) signal

and then a bunch of out of bounds memory accesses are printed. ie: 

фY�LCvalid argument (1)
  �Y�
  �
  ��
  
  PZ�
  p_�
  
  �Y�
  �gXb�
  Ћ
  �^�
  ��
  �`�
  
  �`�
  p��
  
  b�
  �
  A
  ��
</blockquote></details>

Without seeing what code you tried I can't really help. In general try to post not just the output but also the code you tried out unless it's included in the PR
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 14 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HhUj34ez-x3ZhpTfk:-O0HhUj34ez-x3ZhpTfl:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/src/local_cuda_allocator.cc#L14)):*
> ```cpp
> void LocalCudaAllocator::deallocate(void *ptr) {
>   auto it = this->ptrs.find(ptr);
>   if (it != this->ptrs.end()) {
> ```





_Suggestion:_
```cpp
  if (contains(this->ptrs, ptr)) {
```
___
*[`lib/kernels/test/src/test_cuda.cc` line 1 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CFm7z4T_QvOQSneOt:-O0HhylFDlXti4V6Fraw:b-nr5sm2) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_cuda.cc#L1)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Since all test files include "doctest" I thought it'd maybe be cleaner to just include doctest in "test_utils"?
</blockquote></details>

Just include it in the tests directly, in my experience trying tricks like this to avoid repeating headers just makes everything more confusing and harms build times.
___
*[`lib/kernels/test/src/test_utils.h` line 4 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CD60776JRqlanfxP0:-O0HiMQ60O4GGqdX_FtW:b-g5vyjy) ([raw file](https:/ [...]

2024-06-26 13:45 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: all files reviewed, 15 unresolved discussions (waiting on @lockshaw and @oOTigger)

___
*[`lib/kernels/src/array_shape.cc` line 64 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hJ5PPE3JBMHm78gd5:-O0FBxWK6GH8IyOrQIrt:b-93tgjb) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/src/array_shape.cc#L64)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

@reyna-abhyankar Can we get either a fix or an issue created for this?
</blockquote></details>

Yeah, I can fix this in #1418  (issue created is #1421)
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 134 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95GVi-QexYSjWgFBJ:-O0FA7Kp8vFf3IJruzK8:biyjonz) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L134)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't see any issue in passing in a stream in `local-execution` (I assume there's an `ArgRef` of some kind for that)? @reyna-abhyankar
</blockquote></details>

`init_kernel` should be wrapped in a `profile(...)` like the other kernel calls. if you look at `kernels/profiling.h`, you'll see the profiling wrapper passes in the stream, so local execution doesn't handle it.


<!-- Sent from Reviewable.io -->

2024-06-27 02:04 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 66 of 90 files reviewed, 14 unresolved discussions (waiting on @lockshaw)

___
*[`.proj.toml` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CF1iI5DXp5odjrCKQ:-O0Lq4OA2VQ6_YByKTSs:bqzl8c0) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/.proj.toml#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Let's leave this out of `test_targets` then for now until we have a fix so `proj` doesn't crash on machines without a GPU
</blockquote></details>

idk why I didn't understand your question initially. things still build fine even on machines without GPU 
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 15 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HoRyS0aEd2Ow0YUaI:-O0LrH6gCveXv73N95kh:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

These implementations should be in the `.cc` file
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 16 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0Ho1YG1nHMlenktWuC:-O0MPqqsA3ffPU6Gafor:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L16)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Right now you're going to run into issues with the value being moved from double-freeing your objects I think. Making this a pointer (1) makes it easy to fix your double-free problem, and (2) as a nice side effect probably makes copying cheaper

Note that you'll need to modify your deconstructor accordingly, mostly along the lines of the implementation in `ManagedFFStream` but with slightly different behavior in terms of the actual `checkCUDA(freething(...))` calls
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 18 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HoaMp89oSsjNKi6Oz:-O0MPq_Q1PBdE_Sx0lZQ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably a good idea to test the move behaviors of both this and `ManagedFFStream` just to make sure you actually got the implementations correct. I think you should just be able to (in your tests), declare an object, move from it, and then check the state of both the moved-from object and the moved to object
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 23 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0Hms1o3ksO8t8A8SlH:-O0LyLQk8JZL06TL8jqH:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L23)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Otherwise you'll double free your handle things
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 30 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HnAq64JBdKIEQvXNz:-O0Lz-BS8rVUjPeciUoH:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just for consistency we tend to layout struct definitions like this--obviously there's some variation, but trying to follow the convention makes the codebase a bit more approachable
</blockquote></details>

Done.
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CDnNE29Puo5RsZxGX:-O0Lrlyt3fYin6GEYj63:b-4x509p) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/src/local_cuda_allocator.cc#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Without seeing what code you tried I can't really help. In general try to post not just the output but also the code you tried out unless it's included in the PR
</blockquote></details>

Oh I was just trying to show that it lead to printing out random memory.

But yeah I've been testing it for a while and a range based loop always seems to lead to problems with all tests not passing as it's deallocating a pointer that wasn't allocated by it. I tried verifying the tests as well, and they all look like they shouldn't be calling deallocate on an invalid pointer, and it looks like only when it's in a non range based loops, all allocations and deallocations work as expected. 

I rewrote it to use a while loop so potentially that looks a little cleaner? 
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 14 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HhUj34ez-x3ZhpTfk:-O0M3AYs3qmwOkGQ1P1h:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/src/local_cuda_allocator.cc#L14)):*
> ```cpp
> void LocalCudaAllocator::deallocate(void *ptr) {
>   auto it = this->ptrs.find(ptr);
>   if (it != this->ptrs.end()) {
> ```

Done.
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 134 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95GVi-QexYSjWgFBJ:-O0LtApb-NSXSRGh1fAk:bmvswvu) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L134)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

`init_kernel` should be wrapped in a `profile(...)` like the other kernel calls. if you look at `kernels/profiling.h`, you'll see the profiling wrapper passes in the stream, so local execution doesn't handle it.
</blockquote></details>

In that case I'll just keep things as is? 
___
*[`lib/kernels/test/src/test_cuda.cc` line 1 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CFm7z4T_QvOQSneOt:-O0LtDd7CsHE5Cg7jhiy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/test/src/test_cuda.cc#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just include it in the tests directly, in my experience trying tricks like this to avoid repeating headers just makes everything more confusing and harms build times.
</blockquote></details>

Done.
___
*[`lib/kernels/src/local_allocator.cc` line 54 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O06omdt9QeLLD8Bw88n:-O0MPruGD5sHLYkfI6Bv:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f92d046daeac857e18730d8ccef2484d60fc1cde/lib/kernels/src/local_allocator.cc#L54)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

See other comment about posting the code you tried
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/managed_ff_stream.h` line 18 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HjBIQ36UxxtTX2ss0:-O0Lnc945ANz8JJHnonr:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_ff_stream.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

These should be in the `.cc` fil [...]

2024-07-02 21:23 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 64 of 90 files reviewed, 14 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/test/src/test_dropout.cc` line 54 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hPECCDUX4f6NNGMQd:-O0pK1vJDjpLzIe88cMY:bfdaqr8) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_dropout.cc#L54)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Originally wanted to keep this unnested but fixed after our discussion on Friday
</blockquote></details>

I believe this is still nested?


<!-- Sent from Reviewable.io -->

2024-07-04 03:51 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 64 of 90 files reviewed, 14 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/test/src/test_dropout.cc` line 54 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-hPECCDUX4f6NNGMQd:-O0vqsI4DKN6V9fIvDhO:b-lejlli) ([raw file](https://github.com/flexflow/FlexFlow/blob/e7dad32c61c40d14b1903a5ff58eafae918cfea3/lib/kernels/test/src/test_dropout.cc#L54)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I believe this is still nested?
</blockquote></details>

It doesn't look like it is? 


<!-- Sent from Reviewable.io -->

2024-07-05 20:04 UTC, lockshaw requested changes
> Reviewed 24 of 24 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: all files reviewed, 5 unresolved discussions (waiting on @oOTigger)

___
*[`.proj.toml` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CF1iI5DXp5odjrCKQ:-O13QS4i9aM5L3CKmPu-:b-83guog) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/.proj.toml#L18)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

idk why I didn't understand your question initially. things still build fine even on machines without GPU
</blockquote></details>

Yes, but `proj test` runs the tests, at which point you'll get an error on non-GPU machines
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 18 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HoaMp89oSsjNKi6Oz:-O13S3i_-D3IxgG4_75J:bcvbsrn) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L18)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Where? Unless I missed something I'm not seeing any new tests added
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 22 at r19](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O13Soq4Am3N39lV-Zhw:-O13Soq4Am3N39lV-Zhx:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/dcd9f9bc968218bd8f58d94abdd6e9feceb8a145/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L22)):*
> ```objc
>   ~ManagedPerDeviceFFHandle();
> 
>   PerDeviceFFHandle const &raw_handle();
> ```





_Suggestion:_
```objc
  PerDeviceFFHandle const &raw_handle() const;
```
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CDnNE29Puo5RsZxGX:-O13R97X1t8dYPqBP29U:b-fuy0mc) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/src/local_cuda_allocator.cc#L18)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

Oh I was just trying to show that it lead to printing out random memory.

But yeah I've been testing it for a while and a range based loop always seems to lead to problems with all tests not passing as it's deallocating a pointer that wasn't allocated by it. I tried verifying the tests as well, and they all look like they shouldn't be calling deallocate on an invalid pointer, and it looks like only when it's in a non range based loops, all allocations and deallocations work as expected. 

I rewrote it to use a while loop so potentially that looks a little cleaner?
</blockquote></details>

I still don't see a reason that the range-based for loop wouldn't work. Can you show me the code you're trying that isn't working properly?
___
*[`lib/kernels/src/cuda/ops/batch_norm_kernels.cu` line 134 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O-95GVi-QexYSjWgFBJ:-O13UZns-H8gM04x41c-:b-1u10ml) ([raw file](https://github.com/flexflow/FlexFlow/blob/2e9b4cacd82a82fff1f21c8824cb7c6b835ab31b/lib/kernels/src/cuda/ops/batch_norm_kernels.cu#L134)):*
<details><summary><i>Previously, oOTigger (Dylan Lim) wrote…</i></summary><blockquote>

In that case I'll just keep things as is?
</blockquote></details>

Sure, this is fine for now.
___
*[`lib/kernels/include/kernels/managed_ff_stream.h` line 20 at r19](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O13Ug0R9WWL_PrfCez1:-O13Ug0R9WWL_PrfCez2:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/dcd9f9bc968218bd8f58d94abdd6e9feceb8a145/lib/kernels/include/kernels/managed_ff_stream.h#L20)):*
> ```objc
>   ~ManagedFFStream();
> 
>   ffStream_t const &raw_stream();
> ```





_Suggestion:_
```objc
  ffStream_t const &raw_stream() const;
```


<!-- Sent from Reviewable.io -->

2024-07-09 22:29 UTC, oOTigger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: 84 of 90 files reviewed, 5 unresolved discussions (waiting on @lockshaw)

___
*[`.proj.toml` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CF1iI5DXp5odjrCKQ:-O1ObN48DWL8SfJ3H9D1:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/.proj.toml#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yes, but `proj test` runs the tests, at which point you'll get an error on non-GPU machines
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 18 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0HoaMp89oSsjNKi6Oz:-O1OLyllCq5iRg2xm_2E:b-j5bqe1) ([raw file](https://github.com/flexflow/FlexFlow/blob/f75b22e2e0228371ac8f6fc49a6f5885972d748b/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Where? Unless I missed something I'm not seeing any new tests added
</blockquote></details>

Created issue for this 
___
*[`lib/kernels/include/kernels/managed_per_device_ff_handle.h` line 22 at r19](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O13Soq4Am3N39lV-Zhw:-O1OLmeL1SfZBFXfJLc2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dcd9f9bc968218bd8f58d94abdd6e9feceb8a145/lib/kernels/include/kernels/managed_per_device_ff_handle.h#L22)):*
> ```objc
>   ~ManagedPerDeviceFFHandle();
> 
>   PerDeviceFFHandle const &raw_handle();
> ```

Done.
___
*[`lib/kernels/src/local_cuda_allocator.cc` line 18 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O0CDnNE29Puo5RsZxGX:-O1OaNHF4mSKgdBdHA9J:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/32762520086b6d1ff7922a8054a543e9713bb4cf/lib/kernels/src/local_cuda_allocator.cc#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I still don't see a reason that the range-based for loop wouldn't work. Can you show me the code you're trying that isn't working properly?
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/managed_ff_stream.h` line 20 at r19](https://reviewable.io/reviews/flexflow/FlexFlow/1384#-O13Ug0R9WWL_PrfCez1:-O1OLhxt3K7o-AgiaQe6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/dcd9f9bc968218bd8f58d94abdd6e9feceb8a145/lib/kernels/include/kernels/managed_ff_stream.h#L20)):*
> ```objc
>   ~ManagedFFStream();
> 
>   ffStream_t const &raw_stream();
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-10 00:05 UTC, lockshaw approved these changes
> Reviewed 6 of 6 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1384)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oOTigger)



<!-- Sent from Reviewable.io -->

2024-07-10 00:07 UTC, merged