Local Execution: Op refactor
flexflow/FlexFlow pull request #1389
Opened 2024-05-14 14:06 UTC by reyna-abhyankar

**Description of changes:**

Small fixes to operators to local execution and remove legion names

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-05-25 03:46 UTC, lockshaw requested changes
> Reviewed 34 of 60 files at r1, 68 of 68 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: all files reviewed, 10 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/serialization.h` line 1 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpuTp1FSnsw9JlY9s:-NyhpuTp1FSnsw9JlY9t:b-7dgst0) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/include/serialization.h#L1)):*
> ```objc
> #ifndef _FLEXFLOW_LOCAL_EXECUTION_SERIALIZATION_H
> ```

Does serialization need to be in local execution or should it be in runtime? We don't need to copy anything between machines so I'm not sure functionality-wise it needs to be in local execution, though if it makes things easier I don't mind
___
*[`lib/local-execution/include/task_argument_accessor.h` line 1 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhqEEnAlvLDGAnu-zz:-NyhqEEo9XDqrMiH03io:b-ubf2cr) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/include/task_argument_accessor.h#L1)):*
> ```objc
> #ifndef _FLEXFLOW_LOCAL_EXECUTION_TASK_ARGUMENT_ACCESSOR_H
> ```

Might be nice to split up this file a bit eventually
___
*[`lib/utils/include/utils/type_index.h` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nyhox_78JyCWWBSDriC:-Nyhox_78JyCWWBSDriD:b-cuhlhw) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/utils/include/utils/type_index.h#L11)):*
> ```objc
> 
> template <typename T>
> std::type_index init_type_index() {
> ```

`get_type_index` might be better?
___
*[`lib/local-execution/include/op_task_invocation.h` line 62 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpDS02lWNS4SIP_Y-:-NyhpDS02lWNS4SIP_Y0:b-ogidtw) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/include/op_task_invocation.h#L62)):*
> ```objc
>   }
> 
>   void bind_args_from_fwd(OpTaskBinding const &fwd) {
> ```

What is this (and the next method) intended to do?
___
*[`lib/local-execution/include/op_task_invocation.h` line 101 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpJwz4cvB3tQxqGNJ:-NyhpJwz4cvB3tQxqGNK:bq26tog) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/include/op_task_invocation.h#L101)):*
> ```objc
> OpTaskBinding infer_bwd_binding(OpTaskBinding const &fwd);
> 
> bool is_invocation_valid(OpTaskSignature sig, OpTaskInvocation inv);
> ```

Probably want to take args as `const &`
___
*[`lib/local-execution/include/op_task_signature.h` line 41 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpQd6BqFmef21UTh9:-NyhpQd6BqFmef21UThA:b-awluma) ([raw file](https://github.com/flexflow/FlexFlow/blob/6a3abdf44072c3059470f0421b30b05e68fff737/lib/local-execution/include/op_task_signature.h#L41)):*
> ```objc
> 
> struct OpTaskSignature {
>   OpTaskSignature() = delete;
> ```

Why not delete the default constructor?
___
*[`lib/local-execution/include/op_task_signature.h` line 65 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpU41ExVTVULlUD9Z:-NyhpU41ExVTVULlUD9_:b-dactzl) ([raw file](https://github.com/flexflow/FlexFlow/blob/6a3abdf44072c3059470f0421b30b05e68fff737/lib/local-execution/include/op_task_signature.h#L65)):*
> ```objc
>   /* void add_input_slot(slot_id, SlotType, Legion::PrivilegeMode); */
> 
>   bool operator==(OpTaskSignature const &) const;
> ```

Why remove equality comparison?
___
*[`lib/local-execution/include/profiling.h` line 18 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nyhpihf6VUaPKCVMA0q:-Nyhpihf6VUaPKCVMA0r:b-8a0yua) ([raw file](https://github.com/flexflow/FlexFlow/blob/6a3abdf44072c3059470f0421b30b05e68fff737/lib/local-execution/include/profiling.h#L18)):*
> ```objc
>       profiling_wrapper<F, Ts...>(f, profiling, std::forward<Ts>(ts)...);
>   if (elapsed.has_value()) {
>     log_profile.debug(s, elapsed.value());
> ```

Why remove?
___
*[`lib/local-execution/src/ops/layer_norm.cc` line 32 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhnX29DOkQgXGo6gqn:-NyhnX29DOkQgXGo6gqo:bqgchcx) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/src/ops/layer_norm.cc#L32)):*
> ```cpp
>   PROFILING,
>   INPUT,
>   INPUT_GRAD,
> ```

Don't we have the `get_tensor_grad` (or something similar) or am I misremembering?
___
*[`lib/local-execution/src/ops/linear.cc` line 149 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhnzTj5rKHjc_p7e5E:-NyhnzTj5rKHjc_p7e5F:b-b671rs) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/src/ops/linear.cc#L149)):*
> ```cpp
>                  "[Linear] backward_time = %.2lfms\n",
>                  per_device_state,
>                  (void *)input.get_float_ptr(),
> ```

Why does this need a cast to `void *`?


<!-- Sent from Reviewable.io -->

2024-05-28 05:08 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: 89 of 101 files reviewed, 10 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/include/serialization.h` line 1 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpuTp1FSnsw9JlY9s:-NyxYMoNDMH1JUgalv1Q:b-6m5jfy) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/include/serialization.h#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Does serialization need to be in local execution or should it be in runtime? We don't need to copy anything between machines so I'm not sure functionality-wise it needs to be in local execution, though if it makes things easier I don't mind
</blockquote></details>

That's true, but it does make things easier since`ArgRefSpec`, `ConcreteArgSpec`, and `OpTaskSignature` all check for serialization so it'll just make things easier.
___
*[`lib/local-execution/include/task_argument_accessor.h` line 1 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhqEEnAlvLDGAnu-zz:-Nyxa-k_6Jt-Ri7DddLX:b-83od3n) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/include/task_argument_accessor.h#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be nice to split up this file a bit eventually
</blockquote></details>

Noted
___
*[`lib/utils/include/utils/type_index.h` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nyhox_78JyCWWBSDriC:-Nyx_nBz3OcvKPzHWkjP:b2ylgr1) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/utils/include/utils/type_index.h#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`get_type_index` might be better?
</blockquote></details>

We're already using `get_type_index()`. How about "construct"?
___
*[`lib/local-execution/include/op_task_invocation.h` line 62 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpDS02lWNS4SIP_Y-:-NyxVKpAD5OsaJOkDn_G:b-pfn6kq) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/include/op_task_invocation.h#L62)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is this (and the next method) intended to do?
</blockquote></details>

This is called for `infer_bwd_binding`, but I guess we don't need a method for this and it can be replaced directly the other function. I've changed this.
___
*[`lib/local-execution/include/op_task_invocation.h` line 101 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpJwz4cvB3tQxqGNJ:-NyxWWOX8i85kmzZavbP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/include/op_task_invocation.h#L101)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably want to take args as `const &`
</blockquote></details>

Done.
___
*[`lib/local-execution/include/op_task_signature.h` line 41 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpQd6BqFmef21UTh9:-NyxW_JH73Ry2VCk3b4v:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6a3abdf44072c3059470f0421b30b05e68fff737/lib/local-execution/include/op_task_signature.h#L41)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not delete the default constructor?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/op_task_signature.h` line 65 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpU41ExVTVULlUD9Z:-NyxXTOO9gtmomz4HivK:bbaewet) ([raw file](https://github.com/flexflow/FlexFlow/blob/6a3abdf44072c3059470f0421b30b05e68fff737/lib/local-execution/include/op_task_signature.h#L65)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why remove equality comparison?
</blockquote></details>

Don't we get this from visitable?
___
*[`lib/local-execution/include/profiling.h` line 18 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nyhpihf6VUaPKCVMA0q:-NyxXl5W0RhSyTrapcXR:b-wnw6di) ([raw file](https://github.com/flexflow/FlexFlow/blob/6a3abdf44072c3059470f0421b30b05e68fff737/lib/local-execution/include/profiling.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why remove?
</blockquote></details>

It's the legion logger. What should we use instead for logging?
___
*[`lib/local-execution/src/ops/layer_norm.cc` line 32 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhnX29DOkQgXGo6gqn:-NyxZRWb277fOS4bG66H:b-yei9t4) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/src/ops/layer_norm.cc#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Don't we have the `get_tensor_grad` (or something similar) or am I misremembering?
</blockquote></details>

You're correct. Fixed
___
*[`lib/local-execution/src/ops/linear.cc` line 149 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhnzTj5rKHjc_p7e5E:-NyxZsFW-cFYng0xPJO8:b-vv7su3) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/src/ops/linear.cc#L149)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does this need a cast to `void *`?
</blockquote></details>

I think this is because [cublasGemmEx](https://docs.nvidia.com/cuda/cublas/#cublasgemmex) takes `void*` and then also the datatype for that tensor


<!-- Sent from Reviewable.io -->

2024-05-29 23:31 UTC, lockshaw requested changes
> Reviewed 7 of 8 files at r3, 4 of 4 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: all files reviewed, 6 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local_allocator.h` line 1 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nz5eP2jBo7TKTOMu39Q:-Nz5eP2jBo7TKTOMu39R:b-y1dp2l) ([raw file](https://github.com/flexflow/FlexFlow/blob/be791ad58d5957fd1299bfd600e3495eb550eafc/lib/local-execution/include/local_allocator.h#L1)):*
> ```objc
> <<<<<<< op-refactor
> ```

Resolve merge conflict
___
*[`lib/local-execution/src/op_task_invocation.cc` line 100 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nz5en0o9RPdzYb9ll1W:-Nz5en0o9RPdzYb9ll1X:b-f5q3lx) ([raw file](https://github.com/flexflow/FlexFlow/blob/be791ad58d5957fd1299bfd600e3495eb550eafc/lib/local-execution/src/op_task_invocation.cc#L100)):*
> ```cpp
> }
> 
> bool are_sigs_eq(OpTaskSignature const &sig1, OpTaskSignature const &sig2) {
> ```

Any reason for this function over just using `==`?
___
*[`lib/local-execution/src/tracked_allocator.cc` line 6 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nz5ew-I0x_kEx2K0ewi:-Nz5ew-I0x_kEx2K0ewj:b-y1dp2l) ([raw file](https://github.com/flexflow/FlexFlow/blob/be791ad58d5957fd1299bfd600e3495eb550eafc/lib/local-execution/src/tracked_allocator.cc#L6)):*
> ```cpp
> namespace FlexFlow {
> 
> <<<<<<< op-refactor
> ```

Resolve merge conflict
___
*[`lib/utils/include/utils/type_index.h` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nyhox_78JyCWWBSDriC:-Nz5fS3MA1OgNCHpWsQR:b-7hrc72) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/utils/include/utils/type_index.h#L11)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

We're already using `get_type_index()`. How about "construct"?
</blockquote></details>

What is using `get_type_index()`? I'm not seeing anything in the codebase. If the change is necessary, maybe `get_type_index_for_type`? `construct` and `init` just make it sound like it does something much more complicated than it does.
___
*[`lib/local-execution/include/op_task_invocation.h` line 101 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpJwz4cvB3tQxqGNJ:-NyxalNX1vS2x-ZrUK9d:b-n7p2d1) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/include/op_task_invocation.h#L101)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still appears the same?
___
*[`lib/local-execution/include/op_task_signature.h` line 65 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpU41ExVTVULlUD9Z:-NyxavKH922fHjzCEHZ4:b4nhikx) ([raw file](https://github.com/flexflow/FlexFlow/blob/6a3abdf44072c3059470f0421b30b05e68fff737/lib/local-execution/include/op_task_signature.h#L65)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Don't we get this from visitable?
</blockquote></details>

Ah, didn't see this was visitable.
___
*[`lib/local-execution/include/profiling.h` line 18 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nyhpihf6VUaPKCVMA0q:-Nz5g02A2XdR6Mwlj0K8:by8w0ug) ([raw file](https://github.com/flexflow/FlexFlow/blob/6a3abdf44072c3059470f0421b30b05e68fff737/lib/local-execution/include/profiling.h#L18)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

It's the legion logger. What should we use instead for logging?
</blockquote></details>

`spdlog`, or wrap in an `ILogger` interface. The first is probably the simpler one for now. As we implement more of the runtime we should think about which approach we want to take
___
*[`lib/local-execution/src/ops/linear.cc` line 149 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhnzTj5rKHjc_p7e5E:-Nz5f1Wn-BGCm2Vgi4ST:b-yt9yzu) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/src/ops/linear.cc#L149)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I think this is because [cublasGemmEx](https://docs.nvidia.com/cuda/cublas/#cublasgemmex) takes `void*` and then also the datatype for that tensor
</blockquote></details>

Probably better to pass in `float *`s here and handle the cast in the kernel code itself. Not a bit issue though, can always get handled later (maybe a good small task for @oOTigger when he has time)


<!-- Sent from Reviewable.io -->

2024-05-30 05:24 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: all files reviewed, 6 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/include/local_allocator.h` line 1 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nz5eP2jBo7TKTOMu39Q:-Nz6tzpx4zRvu9rp-gL6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/be791ad58d5957fd1299bfd600e3495eb550eafc/lib/local-execution/include/local_allocator.h#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Resolve merge conflict
</blockquote></details>

Done.
___
*[`lib/local-execution/src/op_task_invocation.cc` line 100 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nz5en0o9RPdzYb9ll1W:-Nz6uB3FBbpycEDsWMQh:b-yh6f8m) ([raw file](https://github.com/flexflow/FlexFlow/blob/be791ad58d5957fd1299bfd600e3495eb550eafc/lib/local-execution/src/op_task_invocation.cc#L100)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Any reason for this function over just using `==`?
</blockquote></details>

Removed. I was just confirming that equality worked because of visitable.
___
*[`lib/local-execution/src/tracked_allocator.cc` line 6 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nz5ew-I0x_kEx2K0ewi:-Nz6uQc--YCLCTlA7D3a:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/be791ad58d5957fd1299bfd600e3495eb550eafc/lib/local-execution/src/tracked_allocator.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Resolve merge conflict
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/type_index.h` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nyhox_78JyCWWBSDriC:-Nz6ukY54hIuTh-_q0qA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/utils/include/utils/type_index.h#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is using `get_type_index()`? I'm not seeing anything in the codebase. If the change is necessary, maybe `get_type_index_for_type`? `construct` and `init` just make it sound like it does something much more complicated than it does.
</blockquote></details>

Done.
___
*[`lib/local-execution/include/op_task_invocation.h` line 101 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhpJwz4cvB3tQxqGNJ:-Nz6u5GR0JxTrMiZ-G6o:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/include/op_task_invocation.h#L101)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Still appears the same?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/profiling.h` line 18 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nyhpihf6VUaPKCVMA0q:-Nz6un-A7Ih7aXi9ms51:b-8r37ma) ([raw file](https://github.com/flexflow/FlexFlow/blob/6a3abdf44072c3059470f0421b30b05e68fff737/lib/local-execution/include/profiling.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`spdlog`, or wrap in an `ILogger` interface. The first is probably the simpler one for now. As we implement more of the runtime we should think about which approach we want to take
</blockquote></details>

Done. Just `spdlog::debug` for now
___
*[`lib/local-execution/src/ops/linear.cc` line 149 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NyhnzTj5rKHjc_p7e5E:-Nz6wf04BT9PzVyc4Vg4:b9ncdsz) ([raw file](https://github.com/flexflow/FlexFlow/blob/583b2d30ca780c9ac2e6fbcc391869f33b2ab2b9/lib/local-execution/src/ops/linear.cc#L149)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably better to pass in `float *`s here and handle the cast in the kernel code itself. Not a bit issue though, can always get handled later (maybe a good small task for @oOTigger when he has time)
</blockquote></details>

Created an issue for this: https://github.com/flexflow/FlexFlow/issues/1397


<!-- Sent from Reviewable.io -->

2024-05-30 05:26 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: 91 of 101 files reviewed, 6 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/include/profiling.h` line 18 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-Nyhpihf6VUaPKCVMA0q:-Nz6xZ452XFlu_gxj2fo:b-gpnfd7) ([raw file](https://github.com/flexflow/FlexFlow/blob/6a3abdf44072c3059470f0421b30b05e68fff737/lib/local-execution/include/profiling.h#L18)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done. Just `spdlog::debug` for now
</blockquote></details>

Created an issue to track: https://github.com/flexflow/FlexFlow/issues/1398


<!-- Sent from Reviewable.io -->

2024-05-30 21:03 UTC, lockshaw requested changes
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/profiling.h` line 17 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzAJ91J3Qdq9Cj4qCzA:-NzAJ91J3Qdq9Cj4qCzB:bg69drq) ([raw file](https://github.com/flexflow/FlexFlow/blob/5093acb42aee5dcbe4aec16401363c8e95902c9b/lib/local-execution/include/profiling.h#L17)):*
> ```objc
>       profiling_wrapper<F, Ts...>(f, profiling, std::forward<Ts>(ts)...);
>   if (elapsed.has_value()) {
>     spdlog::debug(elapsed.value());
> ```

Can we get an actual message here rather than just a float?


<!-- Sent from Reviewable.io -->

2024-05-31 03:21 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: 100 of 109 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/local-execution/include/profiling.h` line 17 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzAJ91J3Qdq9Cj4qCzA:-NzBeGs29u0PfSKQLxTM:b-8q0js0) ([raw file](https://github.com/flexflow/FlexFlow/blob/5093acb42aee5dcbe4aec16401363c8e95902c9b/lib/local-execution/include/profiling.h#L17)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can we get an actual message here rather than just a float?
</blockquote></details>

Done? So `s` is something like `"[MultiHeadAttention] backward_time = %.2lfms\n"` which we can format with `elapsed.value()`
I think this is syntactically correct, but I could be wrong.


<!-- Sent from Reviewable.io -->

2024-05-31 05:00 UTC, lockshaw requested changes
> Reviewed 1 of 3 files at r7, 7 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: all files reviewed, 10 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/gather_kernels.h` line 12 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBxyUI8ugPxO5N-kBi:-NzBxyUI8ugPxO5N-kBj:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/include/kernels/gather_kernels.h#L12)):*
> ```objc
>   PerDeviceFFHandle handle;
>   int legion_dim;
> };
> ```





_Suggestion:_
```objc
struct GatherPerDeviceState {
  PerDeviceFFHandle handle;
  legion_dim_t legion_dim;
};
```
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 42 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBwKE30KDwb93KtCN0:-NzBwKE30KDwb93KtCN1:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L42)):*
> ```Cuda
>     // Therefore, input_index = outter_index * (stride * input_dim_size)
>     //                        + index[0] * stride + left_over;
>     coord_t outter_index = o / (stride * output_dim_size);
> ```





_Suggestion:_
```Cuda
    coord_t outer_index = o / (stride * output_dim_size);
```
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 46 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBwMmJ48KgDH3o2JQD:-NzBwMmJ48KgDH3o2JQE:b-pkyy1j) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L46)):*
> ```Cuda
>     coord_t left_over = o % stride;
>     coord_t input_idx = outter_index * (stride * input_dim_size) +
>                         index[o] * stride + left_over;
> ```

I assume this was just a typo?



_Suggestion:_
```Cuda
    coord_t input_idx = outer_index * (stride * input_dim_size) +
                        index[o] * stride + left_over;
```
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 142 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBwuKbA_BmCpsyOjC9:-NzBwuKbA_BmCpsyOjCA:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L142)):*
> ```Cuda
>   for (int i = 0; i < m.legion_dim; i++) {
>     stride *= output.shape[legion_dim_t(i)] + 1;
>   }
> ```





_Suggestion:_
```Cuda
  coord_t stride = output.shape.sub_shape(std::nullopt, m.legion_dim + 1).get_volume();
```
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 144 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBxrvYEs4jYpAEwTbY:-NzBxrvYEs4jYpAEwTbZ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L144)):*
> ```Cuda
>   }
> 
>   coord_t output_dim_size = output.shape[legion_dim_t(m.legion_dim)] + 1;
> ```





_Suggestion:_
```Cuda
  coord_t output_dim_size = output.shape[legion_dim_t(m.legion_dim)];
```
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 145 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBxtpI-AvfRCETdPgm:-NzBxtpI-AvfRCETdPgn:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L145)):*
> ```Cuda
> 
>   coord_t output_dim_size = output.shape[legion_dim_t(m.legion_dim)] + 1;
>   coord_t input_dim_size = input.shape[legion_dim_t(m.legion_dim)] + 1;
> ```





_Suggestion:_
```Cuda
  coord_t input_dim_size = input.shape[legion_dim_t(m.legion_dim)];
```
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 178 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBy4QREHAcwaftvuh4:-NzBy4QSCRU30Xeg_oFs:b-t0e2fu) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L178)):*
> ```Cuda
> 
>   coord_t stride = 1;
>   for (int i = 0; i < m.legion_dim; i++) {
> ```

Same fixes as in forward kernel are needed here
___
*[`lib/op-attrs/include/op-attrs/ops/gather.h` line 12 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzC01aT7s-rw6oxvMmI:-NzC01aT7s-rw6oxvMmJ:bdp5b54) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/op-attrs/include/op-attrs/ops/gather.h#L12)):*
> ```objc
> 
> struct GatherAttrs {
>   req<int> legion_dim;
> ```

And make sure everything flips the dim. Definitely don't use raw (i.e., `int`) dims anywhere as it is unclear if they are in legion ordering or ff ordering. I'd lean toward `ff_dim_t` at this level as `legion_dim_t` is only really necessary when dealing with the concrete data layouts



_Suggestion:_
```objc
  ff_dim_t dim;
```
___
*[`lib/substitutions/src/operator_attributes.cc` line 132 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzC0N-w-FryPxxLYKX2:-NzC0N-w-FryPxxLYKX3:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/substitutions/src/operator_attributes.cc#L132)):*
> ```cpp
>   switch (key) {
>     case OperatorAttributeKey::AXIS:
>       return p.legion_dim;
> ```





_Suggestion:_
```cpp
      return p.dim;
```
___
*[`lib/local-execution/include/profiling.h` line 17 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzAJ91J3Qdq9Cj4qCzA:-NzByQlbBlXVyh8yUPa_:b-5u1bbv) ([raw file](https://github.com/flexflow/FlexFlow/blob/5093acb42aee5dcbe4aec16401363c8e95902c9b/lib/local-execution/include/profiling.h#L17)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done? So `s` is something like `"[MultiHeadAttention] backward_time = %.2lfms\n"` which we can format with `elapsed.value()`
I think this is syntactically correct, but I could be wrong.
</blockquote></details>

I don't think `spdlog` and Legion's logger use the same syntax (`spdlog` uses `fmt`, Legion uses printf-style), so we'll need to choose one--considering that we already use fmt all over the place (and it has support for non-primitive data structures), probably that, in which case here I think you'd do `spdlog::debug(s, elapsed.value());`, and then we'd have to update the strings that get passed in to be `"[MultiHeadAttention] backward_time = {:.2lf}ms\n"` I think. You should look into `vformat` in https://fmt.dev/latest/api.html and at https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/utils/include/utils/exception.h#L10-L15, though it may be best done slightly different than there. Another option is to, instead of taking in an arbitrary format string, take in an operator name and a pass, and just use `"[{}] {}_time = {:.2lf}ms\n"`, which is probably best as we really don't need the complexity of passing in arbitrary format strings. 


<!-- Sent from Reviewable.io -->

2024-06-01 21:40 UTC, lockshaw requested changes
> Reviewed 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/profiling.h` line 17 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzAJ91J3Qdq9Cj4qCzA:-NzKjgHz0BRTeD22M0Gt:bndq2dh) ([raw file](https://github.com/flexflow/FlexFlow/blob/5093acb42aee5dcbe4aec16401363c8e95902c9b/lib/local-execution/include/profiling.h#L17)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think `spdlog` and Legion's logger use the same syntax (`spdlog` uses `fmt`, Legion uses printf-style), so we'll need to choose one--considering that we already use fmt all over the place (and it has support for non-primitive data structures), probably that, in which case here I think you'd do `spdlog::debug(s, elapsed.value());`, and then we'd have to update the strings that get passed in to be `"[MultiHeadAttention] backward_time = {:.2lf}ms\n"` I think. You should look into `vformat` in https://fmt.dev/latest/api.html and at https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/utils/include/utils/exception.h#L10-L15, though it may be best done slightly different than there. Another option is to, instead of taking in an arbitrary format string, take in an operator name and a pass, and just use `"[{}] {}_time = {:.2lf}ms\n"`, which is probably best as we really don't need the complexity of passing in arbitrary format strings.
</blockquote></details>

You need to update the format strings in all of the operators due to the change in syntax


<!-- Sent from Reviewable.io -->

2024-06-01 22:58 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: all files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/kernels/include/kernels/gather_kernels.h` line 12 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBxyUI8ugPxO5N-kBi:-NzGSB04-dXz8iQpqpyz:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/include/kernels/gather_kernels.h#L12)):*
> ```objc
>   PerDeviceFFHandle handle;
>   int legion_dim;
> };
> ```

Done.
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 42 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBwKE30KDwb93KtCN0:-NzFV6fdDS3ljfwgvtD_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L42)):*
> ```Cuda
>     // Therefore, input_index = outter_index * (stride * input_dim_size)
>     //                        + index[0] * stride + left_over;
>     coord_t outter_index = o / (stride * output_dim_size);
> ```

Done.
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 46 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBwMmJ48KgDH3o2JQD:-NzFV6ybBnSdGfKAzxvA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I assume this was just a typo?
</blockquote></details>

Done.
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 142 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBwuKbA_BmCpsyOjC9:-NzFVdDoCGMGst1_ruv1:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L142)):*
> ```Cuda
>   for (int i = 0; i < m.legion_dim; i++) {
>     stride *= output.shape[legion_dim_t(i)] + 1;
>   }
> ```

Done.
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 144 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBxrvYEs4jYpAEwTbY:-NzFVdT19ClcjHXowzmc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L144)):*
> ```Cuda
>   }
> 
>   coord_t output_dim_size = output.shape[legion_dim_t(m.legion_dim)] + 1;
> ```

Done.
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 145 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBxtpI-AvfRCETdPgm:-NzFVdqPDzWS1ew6EhXZ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L145)):*
> ```Cuda
> 
>   coord_t output_dim_size = output.shape[legion_dim_t(m.legion_dim)] + 1;
>   coord_t input_dim_size = input.shape[legion_dim_t(m.legion_dim)] + 1;
> ```

Done.
___
*[`lib/kernels/src/cuda/ops/gather_kernels.cu` line 178 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzBy4QREHAcwaftvuh4:-NzFVkFE6pdcibm0JcQH:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/kernels/src/cuda/ops/gather_kernels.cu#L178)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Same fixes as in forward kernel are needed here
</blockquote></details>

Done.
___
*[`lib/op-attrs/include/op-attrs/ops/gather.h` line 12 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzC01aT7s-rw6oxvMmI:-NzL0aHP2D-pa1Xm6P9v:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/op-attrs/include/op-attrs/ops/gather.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

And make sure everything flips the dim. Definitely don't use raw (i.e., `int`) dims anywhere as it is unclear if they are in legion ordering or ff ordering. I'd lean toward `ff_dim_t` at this level as `legion_dim_t` is only really necessary when dealing with the concrete data layouts
</blockquote></details>

Done.
___
*[`lib/substitutions/src/operator_attributes.cc` line 132 at r9](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzC0N-w-FryPxxLYKX2:-NzL0cYH0M7FaO7VHdiv:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/89afe2cf0a9e9d6f76a81a561b2efb8dc0b6dc0a/lib/substitutions/src/operator_attributes.cc#L132)):*
> ```cpp
>   switch (key) {
>     case OperatorAttributeKey::AXIS:
>       return p.legion_dim;
> ```

Done.
___
*[`lib/local-execution/include/profiling.h` line 17 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzAJ91J3Qdq9Cj4qCzA:-NzFgcZB5kUHAP4WOgPF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5093acb42aee5dcbe4aec16401363c8e95902c9b/lib/local-execution/include/profiling.h#L17)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think `spdlog` and Legion's logger use the same syntax (`spdlog` uses `fmt`, Legion uses printf-style), so we'll need to choose one--considering that we already use fmt all over the place (and it has support for non-primitive data structures), probably that, in which case here I think you'd do `spdlog::debug(s, elapsed.value());`, and then we'd have to update the strings that get passed in to be `"[MultiHeadAttention] backward_time = {:.2lf}ms\n"` I think. You should look into `vformat` in https://fmt.dev/latest/api.html and at https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/utils/include/utils/exception.h#L10-L15, though it may be best done slightly different than there. Another option is to, instead of taking in an arbitrary format string, take in an operator name and a pass, and just use `"[{}] {}_time = {:.2lf}ms\n"`, which is probably best as we really don't need the complexity of passing in arbitrary format strings.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-01 23:06 UTC, lockshaw requested changes
> Reviewed 28 of 28 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/src/ops/gather.cc` line 112 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzL24UcDrJsfEyjSU73:-NzL24UcDrJsfEyjSU74:bl4afxa) ([raw file](https://github.com/flexflow/FlexFlow/blob/5f539a3a1edcf72bdb1ec58b099fd0053f0789a0/lib/local-execution/src/ops/gather.cc#L112)):*
> ```cpp
>   auto input_grad = acc.get_tensor_grad<Permissions::WO>(INPUT);
> 
>   return profile(forward_kernel,
> ```

Really should not be calling `foward_kernel` in the backward task impl I assume?
___
*[`lib/local-execution/src/ops/combine.cc` line 67 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzL1oQ57TwEZXPEUzbR:-NzL1oQ57TwEZXPEUzbS:bbki261) ([raw file](https://github.com/flexflow/FlexFlow/blob/5f539a3a1edcf72bdb1ec58b099fd0053f0789a0/lib/local-execution/src/ops/combine.cc#L67)):*
> ```cpp
>   return profile(backward_kernel,
>                  profiling,
>                  "[Combine] forward_time = {:.2lf}ms\n",
> ```

Someone should probably fix this to be backward time eventually...
___
*[`lib/local-execution/src/ops/embedding.cc` line 79 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzL1vLx7IuOg5FzdSZ4:-NzL1vLx7IuOg5FzdSZ5:b6pzdgu) ([raw file](https://github.com/flexflow/FlexFlow/blob/5f539a3a1edcf72bdb1ec58b099fd0053f0789a0/lib/local-execution/src/ops/embedding.cc#L79)):*
> ```cpp
>   return profile(backward_kernel,
>                  profiling,
>                  "[Embedding] forward_time = {:.2lf}ms\n",
> ```

Should eventually be fixed to be backward time
___
*[`lib/local-execution/src/ops/flat.cc` line 51 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzL2-ItC3UtUYlgjBrJ:-NzL2-ItC3UtUYlgjBrK:b6pzdgu) ([raw file](https://github.com/flexflow/FlexFlow/blob/5f539a3a1edcf72bdb1ec58b099fd0053f0789a0/lib/local-execution/src/ops/flat.cc#L51)):*
> ```cpp
>   return profile(backward_kernel,
>                  profiling,
>                  "[Flat] forward_time = {:.2lf}ms\n",
> ```

Should eventually be fixed to be backward time


<!-- Sent from Reviewable.io -->

2024-06-01 23:26 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: 43 of 111 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/local-execution/src/ops/gather.cc` line 112 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzL24UcDrJsfEyjSU73:-NzL6ZVK8bFiyx14N7lV:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5f539a3a1edcf72bdb1ec58b099fd0053f0789a0/lib/local-execution/src/ops/gather.cc#L112)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Really should not be calling `foward_kernel` in the backward task impl I assume?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/combine.cc` line 67 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzL1oQ57TwEZXPEUzbR:-NzL5hj52mLoU5jtJT3o:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5f539a3a1edcf72bdb1ec58b099fd0053f0789a0/lib/local-execution/src/ops/combine.cc#L67)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Someone should probably fix this to be backward time eventually...
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/embedding.cc` line 79 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzL1vLx7IuOg5FzdSZ4:-NzL5iuqAfZ4gcCYudRY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5f539a3a1edcf72bdb1ec58b099fd0053f0789a0/lib/local-execution/src/ops/embedding.cc#L79)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should eventually be fixed to be backward time
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/flat.cc` line 51 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1389#-NzL2-ItC3UtUYlgjBrJ:-NzL5jppDLLfmWK2O--0:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5f539a3a1edcf72bdb1ec58b099fd0053f0789a0/lib/local-execution/src/ops/flat.cc#L51)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should eventually be fixed to be backward time
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-01 23:33 UTC, lockshaw approved these changes
> Reviewed 68 of 68 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1389)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2024-06-02 00:35 UTC, merged