Local backing
flexflow/FlexFlow pull request #1400
Opened 2024-05-30 23:27 UTC by reyna-abhyankar

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-06-01 23:51 UTC, lockshaw requested changes
Everything in `lib/local-execution/include` should be moved to `lib/local-execution/include/local-execution` so the include paths work out properly

> Reviewed 35 of 110 files at r1.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-:-NzKxi247SOUtBNg6aae:bafbc9p)* status: 35 of 110 files reviewed, 36 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local_task_argument_accessor.h` line 43 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKw0hs4IRBmu1d77c5:-NzKw0hs4IRBmu1d77c6:b-p3jwxx) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_task_argument_accessor.h#L43)):*
> ```objc
>   Allocator allocator;
>   SlotTensorBackingMapping slot_tensor_backing_mapping;
>   SlotArgBackingMap slot_argument_map;
> ```

`map` vs `mapping` is a bit weird naming wise, but this is a pretty minor issue



_Code quote:_
```objc
  SlotTensorBackingMapping slot_tensor_backing_mapping;
  SlotArgBackingMap slot_argument_map;
```
___
*[`lib/local-execution/include/local_training_backing.h` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKwXxS-RBtvAXNiXZ9:-NzKwXxS-RBtvAXNiXZA:bv91ukq) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_training_backing.h#L9)):*
> ```objc
> 
> struct LocalTrainingBacking {
>   LocalTrainingBacking(
> ```

Won't you need something more than just a `ComputationGraph` for the model to actually be trainable? `ComputationGraph` doesn't include a loss function, optimizers, etc.--it's just the computation graph
___
*[`lib/local-execution/include/local_training_backing.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKwINy--no-PQdDpfA:-NzKwINzAKe-2f5lk5pM:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_training_backing.h#L13)):*
> ```objc
>       ComputationGraph const &,
>       TensorBackingMapping,
>       RuntimeArgConfig);
> ```





_Suggestion:_
```objc
  LocalTrainingBacking(
      Allocator const &,
      ComputationGraph const &,
      TensorBackingMapping const &,
      RuntimeArgConfig const &);
```
___
*[`lib/local-execution/include/local_training_backing.h` line 22 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKwM8oAtngwOlXE2iR:-NzKwM8oAtngwOlXE2iS:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_training_backing.h#L22)):*
> ```objc
> 
>   DeviceSpecific<DeviceStates> call_init_task_impl(task_id_t,
>                                                    TaskArgumentAccessor);
> ```





_Suggestion:_
```objc
  DeviceSpecific<DeviceStates> call_init_task_impl(task_id_t,
                                                   TaskArgumentAccessor const &);
```
___
*[`lib/local-execution/include/local_training_backing.h` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKwOQQ86A-bgDLhhfX:-NzKwOQQ86A-bgDLhhfY:b-5lkt3) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_training_backing.h#L29)):*
> ```objc
> private:
>   Allocator allocator;
>   ComputationGraph const & computation_graph;
> ```

Pass args by `const &`, but don't store them by `const &`



_Suggestion:_
```objc
  ComputationGraph computation_graph;
```
___
*[`lib/local-execution/include/local_training_backing.h` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKwy4HBAU_pmpj08AI:-NzKwy4HBAU_pmpj08AJ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_training_backing.h#L37)):*
> ```objc
> OpTaskInvocation init(CompGraphOperatorAttrs);
> OpTaskInvocation forward(CompGraphOperatorAttrs);
> OpTaskInvocation backward(CompGraphOperatorAttrs);
> ```





_Suggestion:_
```objc
OpTaskInvocation init(CompGraphOperatorAttrs const &);
OpTaskInvocation forward(CompGraphOperatorAttrs const &);
OpTaskInvocation backward(CompGraphOperatorAttrs const &);
```
___
*[`lib/local-execution/include/op_task_invocation.h` line 30 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKy1YvANFP4WdLHxdL:-NzKy1YvANFP4WdLHxdM:br2aqc1) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/op_task_invocation.h#L30)):*
> ```objc
>   OpTaskBinding() = default;
> 
>   void bind(slot_id, VariadicTensorRef<OpTensorSpec> const &) {
> ```

Any non-template functions can be moved into the `.cc` file
___
*[`lib/local-execution/include/op_task_invocation.h` line 65 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKyGOa9HJCOwaqSEF2:-NzKyGOa9HJCOwaqSEF3:b-pbs718) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/op_task_invocation.h#L65)):*
> ```objc
>   std::unordered_map<slot_id, OpArgSpec> const &get_arg_bindings() const;
> 
>   void insert_arg_spec(slot_id name, OpArgSpec const &arg_spec) {
> ```

Non-template implementations should be in the `.cc` file
___
*[`lib/local-execution/include/op_task_invocation.h` line 65 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKyLo_888q7SzAyHOL:-NzKyLoa6M6h34nn1z0f:b-d3p9nl) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/op_task_invocation.h#L65)):*
> ```objc
>   std::unordered_map<slot_id, OpArgSpec> const &get_arg_bindings() const;
> 
>   void insert_arg_spec(slot_id name, OpArgSpec const &arg_spec) {
> ```

Should this be private?
___
*[`lib/local-execution/include/op_task_invocation.h` line 70 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKyR2WBVaEf8fE9S1p:-NzKyR2WBVaEf8fE9S1q:b-6c3i6k) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/op_task_invocation.h#L70)):*
> ```objc
>   }
> 
>   std::unordered_map<slot_id, OpArgSpec> arg_bindings;
> ```

Should these be private?
___
*[`lib/local-execution/include/task_argument_accessor.h` line 71 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL3ZMJ41Q6zuzDdqdw:-NzL3ZMJ41Q6zuzDdqdx:b-w08m40) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_argument_accessor.h#L71)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(ITaskArgumentAccessor);
> 
> struct TaskArgumentAccessor {
> ```

These large header files should be split up into multiple files for readability and improved build times. In general probably lean toward one struct per header file (not a hard and fast rule, but a good heuristic). You can always group files into sub directories, so for example this file could be broken up into three separate header files located in `lib/local-execution/include/local-execution/task_argument_accessor/` 
___
*[`lib/local-execution/include/task_registry.h` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL1-zt-LWmP5QPef3G:-NzL1-zt-LWmP5QPef3H:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L29)):*
> ```objc
> 
> struct TaskRegistry {
>   TaskRegistry(TensorBackingMapping, RuntimeArgConfig);
> ```





_Suggestion:_
```objc
  TaskRegistry(TensorBackingMapping const &, RuntimeArgConfig const &);
```
___
*[`lib/local-execution/include/task_registry.h` line 35 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL0Llx5VdFs_tYH8CE:-NzL0Llx5VdFs_tYH8CF:b96kn6v) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L35)):*
> ```objc
>   std::unor [...]

2024-06-02 17:16 UTC, reyna-abhyankar reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-:-NzOhocI6XYUJBTCoZr5:b-896fix)* status: 9 of 114 files reviewed, 36 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/local-execution/include/local_task_argument_accessor.h` line 43 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKw0hs4IRBmu1d77c5:-NzOhztkAZyYpMKu4gD0:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_task_argument_accessor.h#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`map` vs `mapping` is a bit weird naming wise, but this is a pretty minor issue
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local_training_backing.h` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKwXxS-RBtvAXNiXZ9:-NzOi76G3JMDlmUqIbue:b-dc8hcv) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_training_backing.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Won't you need something more than just a `ComputationGraph` for the model to actually be trainable? `ComputationGraph` doesn't include a loss function, optimizers, etc.--it's just the computation graph
</blockquote></details>

Yup, I'm going to add that when we actually implement `update`. That's the PR we talked about that will actually get us to trainable.
___
*[`lib/local-execution/include/local_training_backing.h` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKwINy--no-PQdDpfA:-NzOiN2W5wz_t4euGdwl:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_training_backing.h#L13)):*
> ```objc
>       ComputationGraph const &,
>       TensorBackingMapping,
>       RuntimeArgConfig);
> ```

Done.
___
*[`lib/local-execution/include/local_training_backing.h` line 22 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKwM8oAtngwOlXE2iR:-NzOiaqLCrG-fJC9FtaD:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_training_backing.h#L22)):*
> ```objc
> 
>   DeviceSpecific<DeviceStates> call_init_task_impl(task_id_t,
>                                                    TaskArgumentAccessor);
> ```

Done.
___
*[`lib/local-execution/include/local_training_backing.h` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKwOQQ86A-bgDLhhfX:-NzOideN7vVK_F_QtEnK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_training_backing.h#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pass args by `const &`, but don't store them by `const &`
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local_training_backing.h` line 37 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzKwy4HBAU_pmpj08AI:-NzOikb7DF4j4AwQVPXJ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/local_training_backing.h#L37)):*
> ```objc
> OpTaskInvocation init(CompGraphOperatorAttrs);
> OpTaskInvocation forward(CompGraphOperatorAttrs);
> OpTaskInvocation backward(CompGraphOperatorAttrs);
> ```

Done.
___
*[`lib/local-execution/include/task_registry.h` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL1-zt-LWmP5QPef3G:-NzOroUh3JeupRQZEcpY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L29)):*
> ```objc
> 
> struct TaskRegistry {
>   TaskRegistry(TensorBackingMapping, RuntimeArgConfig);
> ```

Done.
___
*[`lib/local-execution/include/task_registry.h` line 35 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL0Llx5VdFs_tYH8CE:-NzOrwLY0dXJSPyrgOh_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L35)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You should essentially never store references
</blockquote></details>

Done.
___
*[`lib/local-execution/include/task_registry.h` line 38 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL0RXS9oiTffCypmbK:-NzOs1hvEGg6ZREShzNm:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L38)):*
> ```objc
> 
>   // tensors
>   std::unordered_map<tensor_guid_t, GenericTensorAccessorW const &> tensor_mapping;
> ```

Done.
___
*[`lib/local-execution/include/task_registry.h` line 46 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL5d3C0f_pepJeDNMB:-NzOuEFyA-McGr4XbaQb:by5rjgw) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are slots and arguments tracked under `TaskRegistry`? Should this class be split up a bit?
</blockquote></details>

Yes, I'll split it up.
___
*[`lib/local-execution/include/task_registry.h` line 61 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL0Y8M-KT4TlMNd48i:-NzOsL4P-VSoljLXMtcg:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L61)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Considering the name of the function, why not the signature below?

If there is a reason, the function probably needs to be renamed
</blockquote></details>

Done.
___
*[`lib/local-execution/include/task_registry.h` line 62 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL0h2dDqhm4v40JqEN:-NzOsLdcAQ9APF3tPVRF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L62)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Considering the name of the function, why not the signature below?

If there is a reason, the function probably needs to be renamed
</blockquote></details>

Done.
___
*[`lib/local-execution/include/task_registry.h` line 63 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL0v0s1CKkSc0P2aBV:-NzOsQkt0qHCpOo5cZBO:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L63)):*
> ```objc
>   void construct_slot_tensor_backing_map(SlotTensorBackingMapping &, OpTaskBinding const &, operator_guid_t const &);
>   void construct_slot_argument_map(SlotArgBackingMap &, OpTaskBinding const &, operator_guid_t const &);
>   ConcreteArgSpec compile_op_arg_ref_spec(OpArgRefSpec, operator_guid_t const &);
> ```

Done.
___
*[`lib/local-execution/include/task_registry.h` line 64 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL0wYv08YsEfbZ8UTF:-NzOsQzm7RQfirHM5bi4:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L64)):*
> ```objc
>   void construct_slot_argument_map(SlotArgBackingMap &, OpTaskBinding const &, operator_guid_t const &);
>   ConcreteArgSpec compile_op_arg_ref_spec(OpArgRefSpec, operator_guid_t const &);
>   ConcreteArgSpec compile_runtime_arg_ref_spec(RuntimeArgRefSpec);
> ```

Done.
___
*[`lib/local-execution/include/tensor_allocator_utils.h` line 10 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL6MZv-ds8nClS6Fd0:-NzOl1 [...]

2024-06-02 20:06 UTC, lockshaw requested changes
> Reviewed 131 of 131 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: all files reviewed, 18 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/allocation.h` line 20 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzOySJj7JfIL4nxbp_r:-NzOySJj7JfIL4nxbp_s:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/kernels/include/kernels/allocation.h#L20)):*
> ```objc
>   Allocator() = delete;
> 
>   GenericTensorAccessorW allocate(TensorShape const &tensor_shape);
> ```





_Suggestion:_
```objc
GenericTensorAccessorW allocate_tensor(TensorShape const &tensor_shape)
```
___
*[`lib/kernels/src/allocation.cc` line 14 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzOyZ9aCIBFTrXlOoMY:-NzOyZ9aCIBFTrXlOoMZ:b-gnfgz6) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/kernels/src/allocation.cc#L14)):*
> ```cpp
> 
> GenericTensorAccessorW Allocator::allocate(TensorShape const &tensor_shape) {
>   void *ptr = this->allocate(tensor_shape.get_volume());
> ```

Need to include the size of the datatype, as `get_volume` is just the number of elements iirc



_Code quote:_
```cpp
 *ptr = this->allocate(tensor_shape.get_volume());
```
___
*[`lib/local-execution/include/local-execution/privilege_tensor_accessor.h` line 31 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzOzZ8d4pDEhqS8G46p:-NzOzZ8d4pDEhqS8G46q:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/include/local-execution/privilege_tensor_accessor.h#L31)):*
> ```objc
>     typename privilege_mode_to_accessor_t<PRIV>::type;
> 
> using PrivilegeTensorAccessor =
> ```





_Suggestion:_
```objc
using GenericTensorAccessor =
```
___
*[`lib/local-execution/include/local-execution/privilege_tensor_accessor.h` line 33 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzOz_y3C4JxwLoknlhY:-NzOz_y3C4JxwLoknlhZ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/include/local-execution/privilege_tensor_accessor.h#L33)):*
> ```objc
> using PrivilegeTensorAccessor =
>     std::variant<GenericTensorAccessorR, GenericTensorAccessorW>;
> using PrivilegeVariadicTensorAccessor =
> ```





_Suggestion:_
```objc
using VariadicGenericTensorAccessor =
```
___
*[`lib/local-execution/include/local-execution/task_registry.h` line 32 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzPYXiC1J-8XAKec2RA:-NzPYXiC1J-8XAKec2RB:b-kka6tz) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/include/local-execution/task_registry.h#L32)):*
> ```objc
>   TaskRegistry(TensorBackingMapping const &, RuntimeArgConfig const &);
> 
>   // tasks
> ```

Generally we layout code where the fields are after the methods, e.g., 

```
struct MyStruct {
public:
  void do_thing();
public:
  int my_field;
};
```

Unless there's a strong reason to not do this here I'd probably lean toward this for consistency
___
*[`lib/local-execution/src/local_training_backing.cc` line 80 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzLAWoJ3Ph04GFrdX7t:-NzOzwDV6OlC-CVR-ub7:bcfmkvs) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/src/local_training_backing.cc#L80)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

My idea was that at initialization we don't deal with any invocations since nothing is actually "invoked" yet. We just register tasks and allocate tensors.
</blockquote></details>

Well, but the invocations are all static so there's nothing stopping you from checking them ahead of time--invocations are just a lowering of operators to a description of actual tasks to be performed, they don't actually run any of those tasks
___
*[`lib/local-execution/src/task_registry.cc` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP-aFOB8bIRILV-Pk2:-NzP-aFOB8bIRILV-Pk3:b-ce8mp4) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L11)):*
> ```cpp
> 
> void TaskRegistry::register_task(task_id_t const & task_id, operator_guid_t const & op_id) {
>   // -- err: not a compile-time constant so I can't call the function template
> ```

Yeah if you want to do this you'll need a function to handle dispatching to the right template instantiation, i.e., 

```
TaskImplFunction get_task_impl(task_id_t const &task_id) {
  switch (task_id) {
    case CONV2D_INIT_TASK_ID:
      return get_task_id<CONV2D_INIT_TASK_ID>();
    ...
  }
}
```

Thinking about it, you could have `register_task` take in a `TaskSignatureImpl`, and have a function somewhere that loops through all of the task ids and registers them, which while initially a bit weird is actually not the worst idea since we'll need this code for legion too. In hindsight I'd also probably lean away from `get_task_impl` being a template function that is specialized for each op, and instead just use normal functions since you'll have to have a wrapper that aggregates them all eventually, and dealing with templates for this feels unlikely to be particularly enjoyable (you could have a compile-time loop that generates the dispatcher, similar to how `DataTypeDispatch` works, but considering that it's a one-time implementation I'm not convinced that this additional complexity would be worth it).
___
*[`lib/local-execution/src/task_registry.cc` line 30 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzPXIHsBmWHgK4NR8np:-NzPXIHt5e7gaVVg1dyk:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L30)):*
> ```cpp
> }
> 
> void TaskRegistry::insert_per_device_op_state(
> ```





_Suggestion:_
```cpp
void TaskRegistry::add_per_device_op_state(
```
___
*[`lib/local-execution/src/task_registry.cc` line 37 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP1jlqCfiFRtYv84CQ:-NzP1jlqCfiFRtYv84CR:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L37)):*
> ```cpp
> 
> bool TaskRegistry::is_tensor_allocated(tensor_guid_t const &tensor_id) const {
>   return this->tensor_mapping.find(tensor_id) != this->tensor_mapping.end();
> ```





_Suggestion:_
```cpp
 return contains(this->tensor_mapping, tensor_id) ;
```
___
*[`lib/local-execution/src/task_registry.cc` line 48 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP1pej7Q1sPUhlQJ17:-NzP1pej7Q1sPUhlQJ18:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L48)):*
> ```cpp
>     OpTaskBinding const &binding, operator_guid_t const &op_guid) const {
>   SlotTensorBackingMapping mapping;
>   for (auto tensor_binding : binding.get_tensor_bindings()) {
> ```





_Suggestion:_
```cpp
  for (auto const &tensor_binding : binding.get_tensor_bindings()) {
```
___
*[`lib/local-execution/src/task_registry.cc` line 63 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP1x3-EpjjaGkl-_N-:-NzP1x3-EpjjaGkl-_N0:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L63)):*
> ```cpp
>         break;
>       default:
>         throw mk_runtime_error("Invalid TensorRole");
> ```





_Suggestion:_
```cpp
        throw mk_runtime_error(fmt::format("Invalid TensorRole {}", tensor_spec.role));
```
___
*[`lib/local-execution/src/task_registry.cc` line 66 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/ [...]

2024-06-02 23:32 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: 116 of 132 files reviewed, 18 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/include/kernels/allocation.h` line 20 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzOySJj7JfIL4nxbp_r:-NzQAdQi8pAeNFWY9tC2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/kernels/include/kernels/allocation.h#L20)):*
> ```objc
>   Allocator() = delete;
> 
>   GenericTensorAccessorW allocate(TensorShape const &tensor_shape);
> ```

Done.
___
*[`lib/kernels/src/allocation.cc` line 14 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzOyZ9aCIBFTrXlOoMY:-NzQApN30k2QINRUdf4G:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/kernels/src/allocation.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Need to include the size of the datatype, as `get_volume` is just the number of elements iirc
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/privilege_tensor_accessor.h` line 31 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzOzZ8d4pDEhqS8G46p:-NzQAygPELndS0qvvVfH:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/include/local-execution/privilege_tensor_accessor.h#L31)):*
> ```objc
>     typename privilege_mode_to_accessor_t<PRIV>::type;
> 
> using PrivilegeTensorAccessor =
> ```

Done.
___
*[`lib/local-execution/include/local-execution/privilege_tensor_accessor.h` line 33 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzOz_y3C4JxwLoknlhY:-NzQAz-38mvbHsOZszaA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/include/local-execution/privilege_tensor_accessor.h#L33)):*
> ```objc
> using PrivilegeTensorAccessor =
>     std::variant<GenericTensorAccessorR, GenericTensorAccessorW>;
> using PrivilegeVariadicTensorAccessor =
> ```

Done.
___
*[`lib/local-execution/include/local-execution/task_registry.h` line 32 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzPYXiC1J-8XAKec2RA:-NzQC647C5Oxzm54HQ9K:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/include/local-execution/task_registry.h#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Generally we layout code where the fields are after the methods, e.g., 

```
struct MyStruct {
public:
  void do_thing();
public:
  int my_field;
};
```

Unless there's a strong reason to not do this here I'd probably lean toward this for consistency
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_training_backing.cc` line 80 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzLAWoJ3Ph04GFrdX7t:-NzQCaikBna2al6e6HZ7:b-x87cxs) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/src/local_training_backing.cc#L80)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Well, but the invocations are all static so there's nothing stopping you from checking them ahead of time--invocations are just a lowering of operators to a description of actual tasks to be performed, they don't actually run any of those tasks
</blockquote></details>

Yeah, I still think conceptually it should be separated. 
___
*[`lib/local-execution/src/task_registry.cc` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP-aFOB8bIRILV-Pk2:-NzQCybp4rWF8ciyPeVr:b8rufmc) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yeah if you want to do this you'll need a function to handle dispatching to the right template instantiation, i.e., 

```
TaskImplFunction get_task_impl(task_id_t const &task_id) {
  switch (task_id) {
    case CONV2D_INIT_TASK_ID:
      return get_task_id<CONV2D_INIT_TASK_ID>();
    ...
  }
}
```

Thinking about it, you could have `register_task` take in a `TaskSignatureImpl`, and have a function somewhere that loops through all of the task ids and registers them, which while initially a bit weird is actually not the worst idea since we'll need this code for legion too. In hindsight I'd also probably lean away from `get_task_impl` being a template function that is specialized for each op, and instead just use normal functions since you'll have to have a wrapper that aggregates them all eventually, and dealing with templates for this feels unlikely to be particularly enjoyable (you could have a compile-time loop that generates the dispatcher, similar to how `DataTypeDispatch` works, but considering that it's a one-time implementation I'm not convinced that this additional complexity would be worth it).
</blockquote></details>

Yeah, I agree. I'll set up the switch case for task impl and signatures since that has the same issue.
___
*[`lib/local-execution/src/task_registry.cc` line 30 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzPXIHsBmWHgK4NR8np:-NzQDAbl2OgvhW2ouutS:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L30)):*
> ```cpp
> }
> 
> void TaskRegistry::insert_per_device_op_state(
> ```

Done.
___
*[`lib/local-execution/src/task_registry.cc` line 37 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP1jlqCfiFRtYv84CQ:-NzQDp8E5A3a89AfvrAM:b-lifrs7) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L37)):*
> ```cpp
> 
> bool TaskRegistry::is_tensor_allocated(tensor_guid_t const &tensor_id) const {
>   return this->tensor_mapping.find(tensor_id) != this->tensor_mapping.end();
> ```

Done. (`contains_key`)
___
*[`lib/local-execution/src/task_registry.cc` line 48 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP1pej7Q1sPUhlQJ17:-NzQDyZYBVeGh88gTMnQ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L48)):*
> ```cpp
>     OpTaskBinding const &binding, operator_guid_t const &op_guid) const {
>   SlotTensorBackingMapping mapping;
>   for (auto tensor_binding : binding.get_tensor_bindings()) {
> ```

Done.
___
*[`lib/local-execution/src/task_registry.cc` line 63 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP1x3-EpjjaGkl-_N-:-NzQEScjBfu3QO01yKhi:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L63)):*
> ```cpp
>         break;
>       default:
>         throw mk_runtime_error("Invalid TensorRole");
> ```

Done.
___
*[`lib/local-execution/src/task_registry.cc` line 66 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP21bd-trg7f97PAYc:-NzQEVi46wvnGghOlLkV:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L66)):*
> ```cpp
>     }
>     GenericTensorAccessorW tensor_backing =
>         this->get_tensor_backing(tensor_guids[tensor_spec.idx]);
> ```

Done.
___
*[`lib/local-execution/src/task_registry.cc` line 75 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP24yR2JKyJW2Pqf3u:-NzQEWT62M02codlF8ib:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L75)):*
> ```cpp
>     OpTaskBinding const &binding, operator_guid_t const &op_guid) const {
>   SlotArgBackingMapping mapping;
>   for (auto  [...]

2024-06-03 01:04 UTC, lockshaw requested changes
> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: all files reviewed, 4 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/src/local_training_backing.cc` line 80 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzLAWoJ3Ph04GFrdX7t:-NzQb9Bk4wJBPX5bzomK:b-vumb0e) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/src/local_training_backing.cc#L80)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Yeah, I still think conceptually it should be separated.
</blockquote></details>

As a counterargument, moving errors earlier is pretty much always a good idea--in this implementation, if the user never calls `execute_backward` they don't know that the invocations were invalid (or even if they do call it they don't get the errors until then), whereas if it's done in initialization they get informed that their code is incorrect sooner. Since nothing changes (i.e., if they are incorrect here they are incorrect at initialization too) I'd lean toward checking earlier


<!-- Sent from Reviewable.io -->

2024-06-03 01:54 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: all files reviewed, 4 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/src/local_training_backing.cc` line 80 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzLAWoJ3Ph04GFrdX7t:-NzQnDd_C5kRoXqKv81G:bwrpa1n) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/src/local_training_backing.cc#L80)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

As a counterargument, moving errors earlier is pretty much always a good idea--in this implementation, if the user never calls `execute_backward` they don't know that the invocations were invalid (or even if they do call it they don't get the errors until then), whereas if it's done in initialization they get informed that their code is incorrect sooner. Since nothing changes (i.e., if they are incorrect here they are incorrect at initialization too) I'd lean toward checking earlier
</blockquote></details>

Yeah that's fair. I'll move it.


<!-- Sent from Reviewable.io -->

2024-06-03 15:02 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: 120 of 137 files reviewed, 4 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/local-execution/src/local_training_backing.cc` line 80 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzLAWoJ3Ph04GFrdX7t:-NzTDgPLEHPi_2CJ_u9v:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/src/local_training_backing.cc#L80)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Yeah that's fair. I'll move it.
</blockquote></details>

Done.
___
*[`lib/local-execution/src/task_registry.cc` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP-aFOB8bIRILV-Pk2:-NzTKTYQ27bCb0F1OhNr:b-4pijbp) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L11)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Yeah, I agree. I'll set up the switch case for task impl and signatures since that has the same issue.
</blockquote></details>

Done. Added an example for element binary, if that looks good, I can create an issue and then we can go in and add that for all operators.
___
*[`lib/local-execution/src/task_registry.cc` line 103 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP2K0H7Y-7dRGfDCg8:-NzTbiqj2ZGhIjaddCyH:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L103)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Yup.
</blockquote></details>

Done.
___
*[`lib/local-execution/include/task_registry.h` line 46 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzL5d3C0f_pepJeDNMB:-NzTSODl8bD98pwFfa6z:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/include/task_registry.h#L46)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Yes, I'll split it up.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-03 19:00 UTC, lockshaw requested changes
> Reviewed 32 of 32 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: all files reviewed, 12 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 12 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUSI6x9BHKx_Z4ff2W:-NzUSI6x9BHKx_Z4ff2X:b-roxei) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/op_arg_ref.h#L12)):*
> ```objc
> enum class OpArgRefLabel { PER_DEVICE_OP_STATE, PARALLEL_TENSOR_SHAPE };
> 
> struct IndexOpArgRefType {
> ```

Probably more clearly done as a variant, one with the index and one without?
___
*[`lib/local-execution/include/local-execution/op_task_invocation.h` line 69 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUPn15DrLKZ1V5TY6S:-NzUPn15DrLKZ1V5TY6T:bnauthf) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/op_task_invocation.h#L69)):*
> ```objc
>   std::unordered_map<std::pair<slot_id, IsGrad>, OpTensorSpec> tensor_bindings;
>   std::unordered_map<slot_id, OpArgSpec> arg_bindings;
>   std::unordered_map<slot_id, std::pair<slot_id, IsGrad>> shape_bindings;
> ```

Why reference a slot (which could also potentially not be a tensor) when you can reference a tensor directly?



_Suggestion:_
```objc
  std::unordered_map<slot_id, std::tuple<int, TensorRole, IsGrad>> shape_bindings;
```
___
*[`lib/local-execution/include/local-execution/slot_registry.h` line 14 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUMAgj6DPS5t-FlQv8:-NzUMAgkE1WRGw9_Kij-:bg72x9y) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/slot_registry.h#L14)):*
> ```objc
> namespace FlexFlow {
> 
> using TensorBackingMapping =
> ```

Is the additional type alias here useful?
___
*[`lib/local-execution/include/local-execution/slot_registry.h` line 17 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUNcKTAUvAexHoalr9:-NzUNcKTAUvAexHoalrA:bgy0un0) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/slot_registry.h#L17)):*
> ```objc
>     std::unordered_map<tensor_guid_t, GenericTensorAccessorW>;
> 
> struct SlotRegistry {
> ```

Thoughts on `ConcreteSlotBindings` or `LocalSlotsBacking`?



_Code quote:_
```objc
struct SlotRegistry {
```
___
*[`lib/local-execution/include/local-execution/slot_registry.h` line 32 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUM0lrC4OuR-vU9rz9:-NzUM0lrC4OuR-vU9rzA:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/slot_registry.h#L32)):*
> ```objc
>                                       operator_guid_t const &) const;
>   ConcreteArgSpec compile_op_arg_ref_spec(OpArgRefSpec const &,
>                                           operator_guid_t const &) const;
> ```





_Suggestion:_
```objc
  ConcreteArgSpec resolve_op_arg_ref_spec(OpArgRefSpec const &,
                                          operator_guid_t const &) const;
```
___
*[`lib/local-execution/include/local-execution/task_registry.h` line 25 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUMTWo-aATGbBfMwDJ:-NzUMTWo-aATGbBfMwDK:bv8zvee) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/task_registry.h#L25)):*
> ```objc
> };
> 
> OpTaskInvocation init(CompGraphOperatorAttrs const &);
> ```

Seems like a bit of an odd place for these?
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 16 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUMrJT7sbR88SKWroT:-NzUMrJT7sbR88SKWroU:b9gwdet) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/task_signature_impl.h#L16)):*
> ```objc
>     std::function<std::optional<float>(TaskArgumentAccessor const &)>>;
> 
> struct TaskSignatureImpl {
> ```

Bit of an odd name, maybe `FullySpecifiedTask` or `TaskSignatureAndImpl`? (I actually kind of like this second one, what it lacks in elegance it more than makes up for in unambiguity)



_Code quote:_
```objc
struct TaskSignatureImpl {
```
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 23 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUMcTD6cWXGGWJSu4b:-NzUMcTD6cWXGGWJSu4c:bb22bch) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/task_signature_impl.h#L23)):*
> ```objc
> TaskSignatureImpl get_task_sig_impl(task_id_t const &);
> 
> TaskImplFunction get_elementbinary_init_task_impl();
> ```

Why are these declared here instead of being declared in their corresponding operator headers?
___
*[`lib/local-execution/src/local_training_backing.cc` line 80 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzLAWoJ3Ph04GFrdX7t:-NzUO_7dE4KQPUPamFXO:bvctd3t) ([raw file](https://github.com/flexflow/FlexFlow/blob/624b3d7a5a27720192e25e1cc28674f3436f428d/lib/local-execution/src/local_training_backing.cc#L80)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Where did it get moved to? Also to be clear I have no objection to checking it twice (duplicate assertions are hardly the end of the world, and are honestly part of the point of assertions), I just also want it checked earlier
___
*[`lib/local-execution/src/local_training_backing.cc` line 105 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUQEGq9GNy0IKCiDkb:-NzUQEGq9GNy0IKCiDkc:b-pwofl6) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/src/local_training_backing.cc#L105)):*
> ```cpp
> TaskArgumentAccessor LocalTrainingBacking::get_task_arg_accessor(
>     OpTaskInvocation const &invocation, operator_guid_t const &op_guid) const {
>   SlotTensorBackingMapping slot_tensor_backing_map =
> ```

Thoughts on `TensorSlotsBacking` and `ArgSlotsBacking`? `Mapping` feels like it's not contributing a whole lot (except number of characters) to this name, and it's a bit unclear what's being mapped



_Code quote:_
```cpp
  SlotTensorBackingMapping slot_tensor_backing_map =
```
___
*[`lib/local-execution/src/task_registry.cc` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzP-aFOB8bIRILV-Pk2:-NzUSbs04qALtM0yJXBm:b-tl0kqm) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/local-execution/src/task_registry.cc#L11)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done. Added an example for element binary, if that looks good, I can create an issue and then we can go in and add that for all operators.
</blockquote></details>

Looks good, we may still want to move over to the "one giant register function" eventually since we'll need it for legion, but I think we're better off waiting until we actually need it than trying to predict it now, so this all looks good to me (minus my comment that the signature-getting should also be de-templatized)
___
*[`lib/pcg/include/pcg/computation_graph.h` line 8 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUR1unChfHqVXAiuUC:-NzUR1unChfHqVXAiuUD:b-6watfo) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/pcg/include/pcg/computation_graph.h#L8)):*
> ```objc
> #include "tensor.h"
> #include "tensor_guid_t.h"
> #include "utils/containers.h"
> ```

Move to `.cc` file if n [...]

2024-06-03 21:41 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: 120 of 137 files reviewed, 11 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 23 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUMcTD6cWXGGWJSu4b:-NzV2BaxBCr4tlKEKX5R:bekchiz) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/task_signature_impl.h#L23)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Ok, I'll move it over.
</blockquote></details>

Then the `task_signature_impl.cc` will have to include all the operator header files. That ok?


<!-- Sent from Reviewable.io -->

2024-06-03 22:38 UTC, lockshaw requested changes
> Reviewed 14 of 17 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: all files reviewed, 5 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 12 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUSI6x9BHKx_Z4ff2W:-NzVDazU-3kVnkNXRA4j:b-jsejqe) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/op_arg_ref.h#L12)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In theory you could also split up `OpArgRefLabel` based on this, but this is also fine for now
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 23 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUMcTD6cWXGGWJSu4b:-NzVDooU34ad3ibawUh_:b9xxlqx) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/task_signature_impl.h#L23)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Then the `task_signature_impl.cc` will have to include all the operator header files. That ok?
</blockquote></details>

Yeah I think that should be fine. If we end up having build time issues we can fix it later, but for now I think it's the most straightforward solution
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 19 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzVEunq2rdKBbnMD8jV:-NzVEunq2rdKBbnMD8jW:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3c7ad98f66e4cd21d3070eb20ca18188b7f0c0a/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L19)):*
> ```objc
>   LocalTaskArgumentAccessor(Allocator allocator,
>                             TensorSlotsBacking tensor_slots_backingping,
>                             ArgSlotsBacking arg_slots_backing)
> ```





_Suggestion:_
```objc
  LocalTaskArgumentAccessor(Allocator const &allocator,
                            TensorSlotsBacking const &tensor_slots_backingping,
                            ArgSlotsBacking const &arg_slots_backing)
```
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 41 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzVF27L9qoFrWlTRgEt:-NzVF27L9qoFrWlTRgEu:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3c7ad98f66e4cd21d3070eb20ca18188b7f0c0a/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L41)):*
> ```objc
> private:
>   Allocator allocator;
>   TensorSlotsBacking tensor_slots_backingping;
> ```





_Suggestion:_
```objc
  TensorSlotsBacking tensor_slots_backing;
```
___
*[`lib/local-execution/include/local-execution/slot_registry.h` line 14 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUMAgj6DPS5t-FlQv8:-NzVEk5R8I4mW3UGI3Ee:byntzap) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/slot_registry.h#L14)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I use that type alias a lot, I think it's helpful.
</blockquote></details>

Can we change it to `Map` instead of `Mapping`? Seems like a more straightforward name
___
*[`lib/local-execution/src/ops/element_binary.cc` line 133 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzURnEPBBJsEqtjPBJJ:-NzVEXsh9qvA0yCtiY5c:b-4dpsbr) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/src/ops/element_binary.cc#L133)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Yeah ok, I'll do that too.
</blockquote></details>

And probably for `register_task`


<!-- Sent from Reviewable.io -->

2024-06-04 00:16 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: all files reviewed, 5 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 23 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUMcTD6cWXGGWJSu4b:-NzVPyQA-I09kN2knXNi:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/task_signature_impl.h#L23)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Yeah I think that should be fine. If we end up having build time issues we can fix it later, but for now I think it's the most straightforward solution
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 19 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzVEunq2rdKBbnMD8jV:-NzVIrDC8lgcidVEbiMc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3c7ad98f66e4cd21d3070eb20ca18188b7f0c0a/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L19)):*
> ```objc
>   LocalTaskArgumentAccessor(Allocator allocator,
>                             TensorSlotsBacking tensor_slots_backingping,
>                             ArgSlotsBacking arg_slots_backing)
> ```

Done.
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 41 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzVF27L9qoFrWlTRgEt:-NzVIwzp6JmW8GCct5OQ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3c7ad98f66e4cd21d3070eb20ca18188b7f0c0a/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L41)):*
> ```objc
> private:
>   Allocator allocator;
>   TensorSlotsBacking tensor_slots_backingping;
> ```

Done.
___
*[`lib/local-execution/include/local-execution/slot_registry.h` line 14 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzUMAgj6DPS5t-FlQv8:-NzVIhebCYNnaAOFgzi8:brgq1k0) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/include/local-execution/slot_registry.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can we change it to `Map` instead of `Mapping`? Seems like a more straightforward name
</blockquote></details>

Sure. Done.
___
*[`lib/local-execution/src/ops/element_binary.cc` line 133 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzURnEPBBJsEqtjPBJJ:-NzVI5rw5ep-k6NWdSxE:b-abtuaw) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/src/ops/element_binary.cc#L133)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

And probably for `register_task`
</blockquote></details>

Actually, I'm never invoking the individual `register_task` function for the operator. We can delete this? Or just handle it in runtime for the legion specific task registration. 


<!-- Sent from Reviewable.io -->

2024-06-04 03:39 UTC, lockshaw requested changes
> Reviewed 59 of 59 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: all files reviewed, 13 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/src/ops/split.cc` line 167 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJlnV0_5L5-SrcQSv:-NzWJlnV0_5L5-SrcQSw:ba3dfna) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/split.cc#L167)):*
> ```cpp
> 
> // template <>
> // void register_task<SPLIT_FWD_TASK_ID>() {
> ```

Remove?
___
*[`lib/local-execution/src/ops/cast.cc` line 135 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJ3UEATDd_mHJO4Yv:-NzWJ3UEATDd_mHJO4Yw:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/cast.cc#L135)):*
> ```cpp
> }
> 
> OpTaskSignature get_cast_Bwd_signature() {
> ```





_Suggestion:_
```cpp
OpTaskSignature get_cast_bwd_signature() {
```
___
*[`lib/local-execution/src/ops/element_binary.cc` line 133 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzURnEPBBJsEqtjPBJJ:-NzWK2ebBoxYUv2GqZ72:bb74ce2) ([raw file](https://github.com/flexflow/FlexFlow/blob/611701c5fba0a5566ac27eca19f6fd04f18483fc/lib/local-execution/src/ops/element_binary.cc#L133)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Actually, I'm never invoking the individual `register_task` function for the operator. We can delete this? Or just handle it in runtime for the legion specific task registration.
</blockquote></details>

Sure
___
*[`lib/local-execution/src/ops/pool_2d.cc` line 219 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJPYfAi67LxeUrqbm:-NzWJPYfAi67LxeUrqbn:b-wdlbq4) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/pool_2d.cc#L219)):*
> ```cpp
> }
> 
> // template <>
> ```

Should this still be here?
___
*[`lib/local-execution/src/ops/reduce.cc` line 50 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJSXU2JL9U3RrxJRl:-NzWJSXU2JL9U3RrxJRm:b-wdlbq4) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/reduce.cc#L50)):*
> ```cpp
> }
> 
> // template <>
> ```

Should this still be here?
___
*[`lib/local-execution/src/ops/reduce.cc` line 92 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJV5s9aVtW2aUyQRN:-NzWJV5s9aVtW2aUyQRO:b-wdlbq4) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/reduce.cc#L92)):*
> ```cpp
> }
> 
> // template <>
> ```

Should this still be here?
___
*[`lib/local-execution/src/ops/reduction.cc` line 126 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJXe84E-3DL2uBQj9:-NzWJXe84E-3DL2uBQjA:b-wdlbq4) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/reduction.cc#L126)):*
> ```cpp
> }
> 
> // template <>
> ```

Should this still be here?
___
*[`lib/local-execution/src/ops/repartition.cc` line 166 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJZzQ5WsRE-L6rp6G:-NzWJZzQ5WsRE-L6rp6H:b-wdlbq4) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/repartition.cc#L166)):*
> ```cpp
> }
> 
> // template <>
> ```

Should this still be here?
___
*[`lib/local-execution/src/ops/replicate.cc` line 119 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJbq4D5cOUDxKh19D:-NzWJbq4D5cOUDxKh19E:b-wdlbq4) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/replicate.cc#L119)):*
> ```cpp
> }
> 
> // template <>
> ```

Should this still be here?
___
*[`lib/local-execution/src/ops/reshape.cc` line 159 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJdv11VYNP3BZ5f79:-NzWJdv11VYNP3BZ5f7A:b-wdlbq4) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/reshape.cc#L159)):*
> ```cpp
> 
> // template <>
> // void register_task<RESHAPE_INIT_TASK_ID>() {
> ```

Should this still be here?
___
*[`lib/local-execution/src/ops/reverse.cc` line 165 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJhJqB1WKZhKqL6-r:-NzWJhJqB1WKZhKqL6-s:ba3dfna) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/reverse.cc#L165)):*
> ```cpp
> }
> 
> // template <>
> ```

Remove?
___
*[`lib/local-execution/src/ops/softmax.cc` line 172 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJjT58agFpRf6lqOc:-NzWJjT58agFpRf6lqOd:ba3dfna) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/softmax.cc#L172)):*
> ```cpp
> 
> // template <>
> // void register_task<SOFTMAX_INIT_TASK_ID>() {
> ```

Remove?
___
*[`lib/local-execution/src/ops/topk.cc` line 192 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJoZBCGxQ5-1-TXiI:-NzWJoZBCGxQ5-1-TXiJ:ba3dfna) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/topk.cc#L192)):*
> ```cpp
> 
> // template <>
> // void register_task<TOPK_INIT_TASK_ID>() {
> ```

Remove?


<!-- Sent from Reviewable.io -->

2024-06-05 01:45 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: 60 of 147 files reviewed, 12 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/local-execution/src/ops/split.cc` line 167 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJlnV0_5L5-SrcQSv:-NzWjJdC8-Rai6pHw1Sl:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/split.cc#L167)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/cast.cc` line 135 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJ3UEATDd_mHJO4Yv:-NzWXKaq0H37wN8fYImb:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/cast.cc#L135)):*
> ```cpp
> }
> 
> OpTaskSignature get_cast_Bwd_signature() {
> ```

Done.
___
*[`lib/local-execution/src/ops/pool_2d.cc` line 219 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJPYfAi67LxeUrqbm:-NzWjEZH-pdrebHensWR:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/pool_2d.cc#L219)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this still be here?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/reduce.cc` line 50 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJSXU2JL9U3RrxJRl:-NzWjF8l0vRKKjO3N8ZU:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/reduce.cc#L50)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this still be here?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/reduce.cc` line 92 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJV5s9aVtW2aUyQRN:-NzWjFOK4DTiMLPdsjnW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/reduce.cc#L92)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this still be here?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/reduction.cc` line 126 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJXe84E-3DL2uBQj9:-NzWjGRl1mGCLlOonevw:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/reduction.cc#L126)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this still be here?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/repartition.cc` line 166 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJZzQ5WsRE-L6rp6G:-NzWjH7iAvNNIJfz6U2-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/repartition.cc#L166)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this still be here?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/replicate.cc` line 119 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJbq4D5cOUDxKh19D:-NzWjHb94S5xW3zGATYo:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/replicate.cc#L119)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this still be here?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/reshape.cc` line 159 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJdv11VYNP3BZ5f79:-NzWjI3vDR8dcrcKjOoV:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/reshape.cc#L159)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this still be here?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/reverse.cc` line 165 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJhJqB1WKZhKqL6-r:-NzWjIhM8pDEQEHlH3wY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/reverse.cc#L165)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/softmax.cc` line 172 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJjT58agFpRf6lqOc:-NzWjJAmCpeCvqGBrvAd:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/softmax.cc#L172)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/topk.cc` line 192 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzWJoZBCGxQ5-1-TXiI:-NzWjK8Z1ZfGrf1rtXuF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/71ea2e131ca8bfc43cc0435bfd8b607b52172526/lib/local-execution/src/ops/topk.cc#L192)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-05 03:14 UTC, lockshaw requested changes
> Reviewed 3 of 57 files at r8, 1 of 4 files at r9, 82 of 82 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: all files reviewed, 9 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/src/cuda/ops/element_unary_kernels.cu` line 79 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaO25k2HtGeuF1ze9R:-NzaO25k2HtGeuF1ze9S:bwur9cz) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/kernels/src/cuda/ops/element_unary_kernels.cu#L79)):*
> ```Cuda
> }
> 
> OperatorType get_variant_op_type(ElementUnaryUnifiedAttrs const &attrs) {
> ```

Make this static
___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 18 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaJ0vx8EF7HXfpgDfF:-NzaJ0vx8EF7HXfpgDfG:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/local-execution/include/local-execution/op_arg_ref.h#L18)):*
> ```objc
> };
> 
> using OpArgRefType = std::variant<IndexlessOpArgRefType, IndexOpArgRefType>;
> ```





_Suggestion:_
```objc
struct PerDeviceOpStateRefType {};

struct ParallelTensorShapeRefType {
  int idx;
};

using OpArgRefType = std::variant<PerDeviceOpStateRefType, ParallelTensorShapeRefType>;
```
___
*[`lib/local-execution/include/local-execution/serialization.h` line 8 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaJSrz0-xbOcTp6_ef:-NzaJSrz0-xbOcTp6_eg:b8atmij) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/local-execution/include/local-execution/serialization.h#L8)):*
> ```objc
> #include "op-attrs/dim_ordered.h"
> #include "utils/required.h"
> #include "utils/strong_typedef.h"
> ```

Why add?
___
*[`lib/op-attrs/include/op-attrs/param_sync.h` line 1 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaL2stCz-U2r7Msz0n:-NzaL2stCz-U2r7Msz0o:b-r77eag) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/op-attrs/include/op-attrs/param_sync.h#L1)):*
> ```objc
> #ifndef _FLEXFLOW_OPATTRS_INCLUDE_OPATTRS_PARAM_SYNC_H
> ```

Just delete this file? It's not doing anything
___
*[`lib/op-attrs/include/op-attrs/ops/element_unary.h` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaNmNG63rN77RkA_lH:-NzaNmNG63rN77RkA_lI:b-l5plth) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/op-attrs/include/op-attrs/ops/element_unary.h#L11)):*
> ```objc
> namespace FlexFlow {
> 
> struct ElementUnaryAttrs {
> ```

Just convert back to `ElementUnaryAttrs` which has an op_type and an optional float, I don't think the two-types (and especially the nested variant of two types) is really worth it
___
*[`lib/op-attrs/src/op-attrs/ops/element_unary.cc` line 6 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaNzbD0eHTIg5CXQFS:-NzaNzbEC4qGFsrVsFmf:bhlrlz8) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/op-attrs/src/op-attrs/ops/element_unary.cc#L6)):*
> ```cpp
> namespace FlexFlow {
> 
> // tl::expected<TensorShape, std::string>
> ```

Delete comments
___
*[`lib/pcg/include/pcg/computation_graph.h` line 34 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaMB2O6b73L-DwdqZH:-NzaMB2O6b73L-DwdqZI:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/pcg/include/pcg/computation_graph.h#L34)):*
> ```objc
> 
> ComputationGraphOpAttrs get_layer_attrs(ComputationGraph const &cg,
>                                         layer_guid_t const &n);
> ```





_Suggestion:_
```objc
LayerAttrs get_layer_attrs(ComputationGraph const &cg,
                                        layer_guid_t const &n);
```
___
*[`lib/pcg/src/pcg/computation_graph.cc` line 36 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaLOnz039S1y0Wqs_c:-NzaLOnz039S1y0Wqs_d:bofilw) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/pcg/src/pcg/computation_graph.cc#L36)):*
> ```cpp
> 
> std::vector<tensor_guid_t>
>     sort_edge_set(std::unordered_set<MultiDiEdge> edges) {
> ```

Also, any functions that are purely helpers (not exposed through the `.h`) should be `static`



_Suggestion:_
```cpp
    sort_edge_set(std::unordered_set<MultiDiEdge> const &edges) {
```
___
*[`lib/local-execution/src/ops/layer_norm.cc` line 126 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaKOVwDvjg_kEXI86E:-NzaKOVwDvjg_kEXI86F:b-91vndl) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/local-execution/src/ops/layer_norm.cc#L126)):*
> ```cpp
>   int M = 1;
>   for (int i = 0; i < attrs.axes.size(); i++) {
>     legion_dim_t legion_dim = to_legion(
> ```

Rename to `legion_dim_from_ff_dim` for consistency



_Code quote:_
```cpp
to_legion(
```


<!-- Sent from Reviewable.io -->

2024-06-05 17:05 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: all files reviewed, 9 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/src/cuda/ops/element_unary_kernels.cu` line 79 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaO25k2HtGeuF1ze9R:-NzdJfn2CoeK3T0c48iW:b7vfpeb) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/kernels/src/cuda/ops/element_unary_kernels.cu#L79)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Make this static
</blockquote></details>

Superseded by removing the variant.
___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 18 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaJ0vx8EF7HXfpgDfF:-Nzd8FlT9JrQ6nNzGm_q:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/local-execution/include/local-execution/op_arg_ref.h#L18)):*
> ```objc
> };
> 
> using OpArgRefType = std::variant<IndexlessOpArgRefType, IndexOpArgRefType>;
> ```

Done.
___
*[`lib/local-execution/include/local-execution/serialization.h` line 8 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaJSrz0-xbOcTp6_ef:-Nzd8pvT6SybZJH1jkJ4:b-pc588l) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/local-execution/include/local-execution/serialization.h#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why add?
</blockquote></details>

I was getting a build error from `underlying_type_t` being undefined, and it is defined in `utils/strong_typedef.h`
___
*[`lib/op-attrs/include/op-attrs/param_sync.h` line 1 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaL2stCz-U2r7Msz0n:-Nzd9pjHDDZVKR3cOPMJ:b-ppi03y) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/op-attrs/include/op-attrs/param_sync.h#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just delete this file? It's not doing anything
</blockquote></details>

It's technically included in `config.h` so we can do this:
```
#ifdef FF_USE_NCCL
constexpr ParamSync CHOSEN_SYNC_TYPE = ParamSync::NCCL;
#else
constexpr ParamSync CHOSEN_SYNC_TYPE = ParamSync::PS;
#endif
```

But this code is never used, and I don't know if we need it.
___
*[`lib/op-attrs/include/op-attrs/ops/element_unary.h` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaNmNG63rN77RkA_lH:-NzdJibq7KnpG92uBKXm:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2a69843922efbb5cda27ca8339f677c516e4604b/lib/op-attrs/include/op-attrs/ops/element_unary.h#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just convert back to `ElementUnaryAttrs` which has an op_type and an optional float, I don't think the two-types (and especially the nested variant of two types) is really worth it
</blockquote></details>

Done.
___
*[`lib/op-attrs/src/op-attrs/ops/element_unary.cc` line 6 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaNzbD0eHTIg5CXQFS:-NzdJCwA4reNHSdhI3lW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/op-attrs/src/op-attrs/ops/element_unary.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete comments
</blockquote></details>

Done.
___
*[`lib/pcg/include/pcg/computation_graph.h` line 34 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaMB2O6b73L-DwdqZH:-NzdJJ0mDocSGEoKRF2m:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/pcg/include/pcg/computation_graph.h#L34)):*
> ```objc
> 
> ComputationGraphOpAttrs get_layer_attrs(ComputationGraph const &cg,
>                                         layer_guid_t const &n);
> ```

Done.
___
*[`lib/pcg/src/pcg/computation_graph.cc` line 36 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaLOnz039S1y0Wqs_c:-NzdJefmCum08IR4S_yq:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/pcg/src/pcg/computation_graph.cc#L36)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Also, any functions that are purely helpers (not exposed through the `.h`) should be `static`
</blockquote></details>

Done.
___
*[`lib/local-execution/src/ops/layer_norm.cc` line 126 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaKOVwDvjg_kEXI86E:-Nzd9N_r9TBzb6zGz7CW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/local-execution/src/ops/layer_norm.cc#L126)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Rename to `legion_dim_from_ff_dim` for consistency
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-06 00:45 UTC, lockshaw approved these changes
> Reviewed 36 of 36 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @reyna-abhyankar)

___
*[`lib/kernels/src/hip/element_unary_kernels.cpp` line 41 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-Nzezgpm12o1izIk313c:-Nzezgpm12o1izIk313d:b-8zu7kj) ([raw file](https://github.com/flexflow/FlexFlow/blob/738c1edb6edfd2a9ea2a54471dd58753deca1a86/lib/kernels/src/hip/element_unary_kernels.cpp#L41)):*
> ```cpp
> }
> 
> template <typename T>
> ```

No longer necessary?
___
*[`lib/kernels/src/hip/element_unary_kernels.cpp` line 145 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-Nzf-8NE1npfasB9R7l_:-Nzf-8NE1npfasB9R7la:b-sn9g2q) ([raw file](https://github.com/flexflow/FlexFlow/blob/738c1edb6edfd2a9ea2a54471dd58753deca1a86/lib/kernels/src/hip/element_unary_kernels.cpp#L145)):*
> ```cpp
> 
> template <typename T>
> __global__ void elewise_unary_backward_kernel(coord_t volume,
> ```

Changes needed to this file I assume?
___
*[`lib/op-attrs/include/op-attrs/param_sync.h` line 1 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaL2stCz-U2r7Msz0n:-Nzeyrxl7fa0h3Z4tvy3:b5xy7nd) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/op-attrs/include/op-attrs/param_sync.h#L1)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

It's technically included in `config.h` so we can do this:
```
#ifdef FF_USE_NCCL
constexpr ParamSync CHOSEN_SYNC_TYPE = ParamSync::NCCL;
#else
constexpr ParamSync CHOSEN_SYNC_TYPE = ParamSync::PS;
#endif
```

But this code is never used, and I don't know if we need it.
</blockquote></details>

Well either way this file isn't needed, you can just replace the include in `config.h` with `#include "param_sync.dtg.h"`


<!-- Sent from Reviewable.io -->

2024-06-06 01:14 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: 164 of 168 files reviewed, all discussions resolved (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/op-attrs/include/op-attrs/param_sync.h` line 1 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-NzaL2stCz-U2r7Msz0n:-Nzf5qroACzuYoG-s5PY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/cf428b038871335e6adef6763683e08704ec00c8/lib/op-attrs/include/op-attrs/param_sync.h#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Well either way this file isn't needed, you can just replace the include in `config.h` with `#include "param_sync.dtg.h"`
</blockquote></details>

Done.
___
*[`lib/kernels/src/hip/element_unary_kernels.cpp` line 41 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-Nzezgpm12o1izIk313c:-Nzf62bLBAbUWDfu-Sag:b-ua6u6r) ([raw file](https://github.com/flexflow/FlexFlow/blob/738c1edb6edfd2a9ea2a54471dd58753deca1a86/lib/kernels/src/hip/element_unary_kernels.cpp#L41)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

No longer necessary?
</blockquote></details>

Tracking in https://github.com/flexflow/FlexFlow/issues/1408
___
*[`lib/kernels/src/hip/element_unary_kernels.cpp` line 145 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1400#-Nzf-8NE1npfasB9R7l_:-Nzf6CMHBjXG22mirK0d:b-ua6u6r) ([raw file](https://github.com/flexflow/FlexFlow/blob/738c1edb6edfd2a9ea2a54471dd58753deca1a86/lib/kernels/src/hip/element_unary_kernels.cpp#L145)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Changes needed to this file I assume?
</blockquote></details>

Tracking in https://github.com/flexflow/FlexFlow/issues/1408


<!-- Sent from Reviewable.io -->

2024-06-06 04:32 UTC, lockshaw approved these changes
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1400)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2024-06-06 04:32 UTC, merged