Local Cost Estimator
flexflow/FlexFlow pull request #1410
Opened 2024-06-09 14:59 UTC by reyna-abhyankar

**Description of changes:**

Add a local cost estimator that runs an operator's forward and backward pass on a single device and returns the elapsed time.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #1415

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1410)

2024-06-11 19:33 UTC, lockshaw requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1410)* status: all files reviewed, 16 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7eiwd94Ez_NHMr3Vk:-O-7eiwd94Ez_NHMr3Vl:b-ewtake) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/include/local-execution/local_training_backing.h#L9)):*
> ```objc
> namespace FlexFlow {
> 
> enum class KernelType { FWD, BWD };
> ```

Move to `.enum.toml`



_Code quote:_
```objc
num class KernelType { FWD, BWD };
```
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7jFDJ6DkDJddKan2F:-O-7jFDJ6DkDJddKan2G:b-kfjk44) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L8)):*
> ```cpp
> #include "pcg/computation_graph_builder.h"
> 
> // from #1384
> ```

Remove these comments before merging
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7fVIr2vqmnzT_Jl9u:-O-7fVIr2vqmnzT_Jl9v:b-fu87rv) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L15)):*
> ```cpp
> 
> // from #1384
> inline void setPerDeviceFFHandle(PerDeviceFFHandle *handle) {
> ```

Should be in `kernels`, not `local-execution`
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 25 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7j95c9OECEZTZPxfo:-O-7j95c9OECEZTZPxfp:b-oc1kiu) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L25)):*
> ```cpp
> static std::vector<TensorAttrs>
>     get_piece_attrs(std::vector<ParallelTensorAttrs> const &parallel_attrs) {
>   return transform(parallel_attrs, [](ParallelTensorAttrs const &p) {
> ```

Maybe better to just make this a lambda in the actual function? Seems like it's only used in one place, and it's static anyway
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 30 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7fdKQBFhZXEmeonpC:-O-7fdKQBFhZXEmeonpD:bvz2fx4) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L30)):*
> ```cpp
> }
> 
> static TensorAttrs get_piece_attrs(ParallelTensorAttrs const &parallel_attrs) {
> ```

This should probably just be a public function for `ParallelTensorAttrs const &`
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 38 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7g0qv8GnX92CoEpMP:-O-7g0qv8GnX92CoEpMQ:b3tygy) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L38)):*
> ```cpp
> 
> static LayerAttrs
>     get_layer_attrs_from_pcg_op_attrs(PCGOperatorAttrs const &op) {
> ```

I don't think this should be possible? The analog of `PCGOperatorAttrs` is `ComputationGraphOpAttrs`, not `LayerAttrs`. Technically at the moment `LayerAttrs` just has an extra "name" field over `ComputationGraphOpAttrs`, but it doesn't really feel like the right conversion to be doing and I'm not sure why you need a `LayerAttrs` over a `ComputationGraphOpAttrs` anyway
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 39 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7fmCAA9DYtj-i8yjD:-O-7fmCAA9DYtj-i8yjE:b7qtz4x) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L39)):*
> ```cpp
> static LayerAttrs
>     get_layer_attrs_from_pcg_op_attrs(PCGOperatorAttrs const &op) {
>   assert(!is_parallel_op(op));
> ```

Throwing an exception is probably better so we actually get error messages
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7h1z66McwsCIpsEsr:-O-7h1z66McwsCIpsEss:b8edfc2) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L45)):*
> ```cpp
>             ComputationGraphOpAttrs{std::forward<decltype(arg)>(arg)}};
>       },
>       op);
> ```

Isn't this just going to throw an build error on the parallel op types? Also, this function should get moved to `op-attrs` and tests should be added



_Code quote:_
```cpp
  return std::visit(
      [](auto &&arg) -> LayerAttrs {
        return LayerAttrs{
            ComputationGraphOpAttrs{std::forward<decltype(arg)>(arg)}};
      },
      op);
```
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 59 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7iRnv5Suv7w_RIky9:-O-7iRnv5Suv7w_RIkyA:b-6oq5p3) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L59)):*
> ```cpp
>   Allocator allocator = get_local_memory_allocator();
>   TensorBackingMap tensor_backing_map;
>   std::vector<tensor_guid_t> input_tensor_ids;
> ```

Why not just have a single `TensorBackingMap` instead of duplicating the information



_Code quote:_
```cpp
  TensorBackingMap tensor_backing_map;
  std::vector<tensor_guid_t> input_tensor_ids;
```
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 66 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7hWwEBkcuyFtT1rT0:-O-7hWwEBkcuyFtT1rT1:b-dexgmo) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L66)):*
> ```cpp
>     tensor_guid_t tensor_id = cg_builder.create_tensor(tensor_shape);
>     GenericTensorAccessorW const tensor_backing =
>         allocator.allocate_tensor(tensor_shape);
> ```

Currently we don't really use local "const" declarations without a particular reason



_Suggestion:_
```cpp
    TensorShape tensor_shape = get_piece_shape(input);
    tensor_guid_t tensor_id = cg_builder.create_tensor(tensor_shape);
    GenericTensorAccessorW tensor_backing =
        allocator.allocate_tensor(tensor_shape);
```
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 82 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7hyonAxliud6XFY6d:-O-7hyonAxliud6XFY6e:bivekr8) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L82)):*
> ```cpp
>   int measure_iters = 1;
>   PerDeviceFFHandle handle;
>   setPerDeviceFFHandle(&handle);
> ```

I don't think you just get to keep reinitializing CUDA? The handle should probably be passed in when constructing the `LocalCostEstimator` instead of being created by it
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 87 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7ioG4BnH-zfTvl7Rb:-O-7ioG4BnH-zfTvl7Rc:b7e6g15) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L87)):*
> ```cpp
>       DeviceSpecific<PerDeviceFFHandle>::create(handle),
>       EnableProfiling::YES,
>       ProfilingSettings{warmup_iters, measure_iters}};
> ```

Maybe better to have `ProfilingSettings` passed in when creating the `LocalCostEstimator` rather than being hardocded?
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 98 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7iDAx84TsuXaRo8EQ:-O-7iDAx84TsuXaRo8ER:b2nhswy) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-executi [...]

2024-06-14 17:32 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1410)* status: all files reviewed, 16 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7eiwd94Ez_NHMr3Vk:-O-MaHNn7Y02PRqT9DuX:b-ae2ht8) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/include/local-execution/local_training_backing.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `.enum.toml`
</blockquote></details>

Unnecessary because reverting back to `execute_forward / execute_backward`
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 8 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7jFDJ6DkDJddKan2F:-O-MVYSM-K3mD7r4x0eZ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove these comments before merging
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7fVIr2vqmnzT_Jl9u:-O-MVNSl-gt6Qw57U9pg:b-8ehupo) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should be in `kernels`, not `local-execution`
</blockquote></details>

Deleted. Don't need this anymore. Logically, we will merge #1384 first too 
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 25 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7j95c9OECEZTZPxfo:-O-MUMcl54JyzwHRmXsn:b-sypavc) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Maybe better to just make this a lambda in the actual function? Seems like it's only used in one place, and it's static anyway
</blockquote></details>

Actually, I think we can just move this as a public function to `ParallelTensorAttrs` too? It could be useful to do this for a vector
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 30 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7fdKQBFhZXEmeonpC:-O-MURtd7eSqcheVARwg:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This should probably just be a public function for `ParallelTensorAttrs const &`
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 38 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7g0qv8GnX92CoEpMP:-O-MWNXFBiSeO2spU6Bw:b-6ancxs) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L38)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think this should be possible? The analog of `PCGOperatorAttrs` is `ComputationGraphOpAttrs`, not `LayerAttrs`. Technically at the moment `LayerAttrs` just has an extra "name" field over `ComputationGraphOpAttrs`, but it doesn't really feel like the right conversion to be doing and I'm not sure why you need a `LayerAttrs` over a `ComputationGraphOpAttrs` anyway
</blockquote></details>

Done. Also moved to public fn in `pcg_operator_attrs.h`
Also I think this forwarding code is still wrong, but I'm not sure how to do this without just enumerating every possibility (although again, this is a one time thing so we could just do that)
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 39 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7fmCAA9DYtj-i8yjD:-O-MaO8U1ePgGIHoXW1-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L39)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Throwing an exception is probably better so we actually get error messages
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7h1z66McwsCIpsEsr:-O-MWVlnCLlNdpd0ewWv:b-fqr531) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Isn't this just going to throw an build error on the parallel op types? Also, this function should get moved to `op-attrs` and tests should be added
</blockquote></details>

Moved. Working on tests. And what should be the behavior for local cost estimator on parallel op types?
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 59 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7iRnv5Suv7w_RIky9:-O-MXORd9uuVAHcHgyYA:bj4a7w3) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L59)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not just have a single `TensorBackingMap` instead of duplicating the information
</blockquote></details>

A vector of tensor ids is needed to actually construct the layer in the computation graph builder. 
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 66 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7hWwEBkcuyFtT1rT0:-O-MX7lt3AT1QfNvfqbx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L66)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Currently we don't really use local "const" declarations without a particular reason
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 82 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7hyonAxliud6XFY6d:-O-Mj1Qv8YxrbkjKUG1v:bakk2ed) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L82)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think you just get to keep reinitializing CUDA? The handle should probably be passed in when constructing the `LocalCostEstimator` instead of being created by it
</blockquote></details>

Done. now, I initialize a `LocalCostEstimator` with a `RuntimeArgConfig` that contains both the handle and the `ProfilingSettings`
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 87 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7ioG4BnH-zfTvl7Rb:-O-Mj23l-uTMUDp37Px8:bakk2ed) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L87)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Maybe better to have `ProfilingSettings` passed in when creating the `LocalCostEstimator` rather than being hardocded?
</blockquote></details>

Done. now, I initialize a `LocalCostEstimator` with a `RuntimeArgConfig` that contains both the handle and the `ProfilingSettings`
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 98 at r1](https://reviewable.io/reviews [...]

2024-06-17 05:39 UTC, lockshaw requested changes
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1410)* status: all files reviewed, 12 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZeOky3NoE4PJ2pg2N:-O-ZeOky3NoE4PJ2pg2O:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/include/local-execution/local_slots_backing.h#L24)):*
> ```objc
>   bool is_tensor_allocated(tensor_guid_t const &) const;
>   GenericTensorAccessorW const &get_tensor_backing(tensor_guid_t const &,
>                                                    IsGrad const) const;
> ```





_Suggestion:_
```objc
  GenericTensorAccessorW const &get_tensor_backing(tensor_guid_t const &,
                                                   IsGrad) const;
```
___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 20 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZeWSj6CvZLPKR3ECD:-O-ZeWSj6CvZLPKR3ECE:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/include/local-execution/local_training_backing.h#L20)):*
> ```objc
> 
>   void execute_init();
>   PerLayerElapsedTime const &execute_forward();
> ```





_Suggestion:_
```objc
  PerLayerElapsedTime execute_forward();
```
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 25 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7j95c9OECEZTZPxfo:-O-ZehcGB3rSSyVMvFD7:blib77t) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L25)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Actually, I think we can just move this as a public function to `ParallelTensorAttrs` too? It could be useful to do this for a vector
</blockquote></details>

I'd rather not have separate functions for the `vector` version of everything, it massively increases the number of functions, and with `transform` everything is pretty short anyway. If you need to do a similar thing a bunch of times in a function you can use a lambda, or a function with `static` linkage if you need to do it a bunch of times in a single file
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 38 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7g0qv8GnX92CoEpMP:-O-Zf2cI1_Kw5CL65hkR:b-jkkknt) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L38)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done. Also moved to public fn in `pcg_operator_attrs.h`
Also I think this forwarding code is still wrong, but I'm not sure how to do this without just enumerating every possibility (although again, this is a one time thing so we could just do that)
</blockquote></details>

Enumerating every possibility is fine. If you're worried about the list getting out of date, add rapidcheck tests
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7h1z66McwsCIpsEsr:-O-ZfBQF4Xh-e8-4I_5R:beuc1xc) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L45)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Moved. Working on tests. And what should be the behavior for local cost estimator on parallel op types?
</blockquote></details>

Zero cost
___
*[`lib/local-execution/src/local_slots_backing.cc` line 26 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7esc94KiB5uMv4ElR:-O-Zg5Vr6Wb1MvX5fhmj:b-470v0g) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_slots_backing.cc#L26)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

#1415
</blockquote></details>

Is this resolved now?
___
*[`lib/local-execution/src/local_slots_backing.cc` line 30 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-Zh-eV20jR015LPPYl:-O-Zh-eV20jR015LPPYm:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/src/local_slots_backing.cc#L30)):*
> ```cpp
>       return this->gradient_tensor_mapping.at(tensor_id);
>     default:
>       throw mk_runtime_error(fmt::format("IsGrad should only have YES or NO"));
> ```





_Suggestion:_
```cpp
      throw mk_runtime_error(fmt::format("IsGrad should only have YES or NO, received {}", is_grad));
```
___
*[`lib/local-execution/src/local_training_backing.cc` line 86 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgA7B5Xn7SjvUA7x4:-O-ZgA7B5Xn7SjvUA7x5:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/src/local_training_backing.cc#L86)):*
> ```cpp
> }
> 
> PerLayerElapsedTime const &LocalTrainingBacking::execute_forward() {
> ```





_Suggestion:_
```cpp
PerLayerElapsedTime LocalTrainingBacking::execute_forward() {
```
___
*[`lib/local-execution/src/local_training_backing.cc` line 102 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgD-h7J_FeTdkpZoE:-O-ZgD-h7J_FeTdkpZoF:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/src/local_training_backing.cc#L102)):*
> ```cpp
> }
> 
> PerLayerElapsedTime const &LocalTrainingBacking::execute_backward() {
> ```





_Suggestion:_
```cpp
PerLayerElapsedTime LocalTrainingBacking::execute_backward() {
```
___
*[`lib/op-attrs/include/op-attrs/pcg_operator_attrs.h` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgI3q2VaxqhNmkP1M:-O-ZgI3q2VaxqhNmkP1N:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/op-attrs/include/op-attrs/pcg_operator_attrs.h#L11)):*
> ```objc
> bool is_parallel_op(PCGOperatorAttrs const &);
> OperatorType get_op_type(PCGOperatorAttrs const &);
> ComputationGraphOpAttrs get_cg_attrs(PCGOperatorAttrs const &);
> ```





_Suggestion:_
```objc
ComputationGraphOpAttrs compgraph_op_attrs_from_pcg_op_attrs(PCGOperatorAttrs const &);
```
___
*[`lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc` line 19 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgRZ685I2iiEtoi8f:-O-ZgRZ685I2iiEtoi8g:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc#L19)):*
> ```cpp
>   if (is_parallel_op(op)) {
>     throw mk_runtime_error(
>         fmt::format("Cannot convert parallel op to non-parallel"));
> ```





_Suggestion:_
```cpp
fmt::format("Cannot convert parallel op to ComputationGraphOpAttrs: {}", op));
```
___
*[`lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc` line 22 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgXGU-HEd0RUAPP28:-O-ZgXGU-HEd0RUAPP29:b-3y4t9a) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc#L22)):*
> ```cpp
>   }
> 
>   return std::visit(
> ```

Just enumerating is fine
___
*[`lib/pcg/include/pcg/parallel_tensor_attrs.h` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgcGF-D3hOtbFDLG5:-O-ZgcGF-D3hOtbFDLG6:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/pcg/include/pcg/parallel_tensor_attrs.h#L11)):*
> ```objc
> 
> std::vector<TensorAttrs>
>     get_piece_attrs(std::vector<Parall [...]

2024-06-17 17:37 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1410)* status: 10 of 22 files reviewed, 12 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZeOky3NoE4PJ2pg2N:-O-b8dHB9FC-i9ivzGGe:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/include/local-execution/local_slots_backing.h#L24)):*
> ```objc
>   bool is_tensor_allocated(tensor_guid_t const &) const;
>   GenericTensorAccessorW const &get_tensor_backing(tensor_guid_t const &,
>                                                    IsGrad const) const;
> ```

Done.
___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 20 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZeWSj6CvZLPKR3ECD:-O-b8jCN6ov0SuTU05MG:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/include/local-execution/local_training_backing.h#L20)):*
> ```objc
> 
>   void execute_init();
>   PerLayerElapsedTime const &execute_forward();
> ```

Done.
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 25 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7j95c9OECEZTZPxfo:-O-bAL9U48SIJNct2XdO:b-s27rb5) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'd rather not have separate functions for the `vector` version of everything, it massively increases the number of functions, and with `transform` everything is pretty short anyway. If you need to do a similar thing a bunch of times in a function you can use a lambda, or a function with `static` linkage if you need to do it a bunch of times in a single file
</blockquote></details>

Ok, just made it a lambda.
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 38 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7g0qv8GnX92CoEpMP:-O-bDZ6z3nXq8VL2sxyn:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L38)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Enumerating every possibility is fine. If you're worried about the list getting out of date, add rapidcheck tests
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_cost_estimator.cc` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7h1z66McwsCIpsEsr:-O-bBEfV78zqYm1LTvzI:b-gvqh22) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Zero cost
</blockquote></details>

Even for memory?
___
*[`lib/local-execution/src/local_slots_backing.cc` line 26 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7esc94KiB5uMv4ElR:-O-bBQZG2svXL_ome7sJ:b-e5fed2) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_slots_backing.cc#L26)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is this resolved now?
</blockquote></details>

Yup, this PR closes the issue.
___
*[`lib/local-execution/src/local_slots_backing.cc` line 30 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-Zh-eV20jR015LPPYl:-O-bG06F-F2b9LaAjzf0:bi3rk3z) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/src/local_slots_backing.cc#L30)):*
> ```cpp
>       return this->gradient_tensor_mapping.at(tensor_id);
>     default:
>       throw mk_runtime_error(fmt::format("IsGrad should only have YES or NO"));
> ```

How should I extract the string value of an unknown enum case? 
___
*[`lib/local-execution/src/local_training_backing.cc` line 86 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgA7B5Xn7SjvUA7x4:-O-bBXjx2FfTQuEOB7af:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/src/local_training_backing.cc#L86)):*
> ```cpp
> }
> 
> PerLayerElapsedTime const &LocalTrainingBacking::execute_forward() {
> ```

Done.
___
*[`lib/local-execution/src/local_training_backing.cc` line 102 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgD-h7J_FeTdkpZoE:-O-bBY0l7-x2YVB4pZCA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/src/local_training_backing.cc#L102)):*
> ```cpp
> }
> 
> PerLayerElapsedTime const &LocalTrainingBacking::execute_backward() {
> ```

Done.
___
*[`lib/op-attrs/include/op-attrs/pcg_operator_attrs.h` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgI3q2VaxqhNmkP1M:-O-bBdwo30ol8qF54Mvq:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/op-attrs/include/op-attrs/pcg_operator_attrs.h#L11)):*
> ```objc
> bool is_parallel_op(PCGOperatorAttrs const &);
> OperatorType get_op_type(PCGOperatorAttrs const &);
> ComputationGraphOpAttrs get_cg_attrs(PCGOperatorAttrs const &);
> ```

Done.
___
*[`lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc` line 19 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgRZ685I2iiEtoi8f:-O-bG7Tg-TqvuxFxvTCa:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc#L19)):*
> ```cpp
>   if (is_parallel_op(op)) {
>     throw mk_runtime_error(
>         fmt::format("Cannot convert parallel op to non-parallel"));
> ```

Done.
___
*[`lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc` line 22 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgXGU-HEd0RUAPP28:-O-bG82o6ilq2LZ6nQ7k:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just enumerating is fine
</blockquote></details>

Done.
___
*[`lib/pcg/include/pcg/parallel_tensor_attrs.h` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-ZgcGF-D3hOtbFDLG5:-O-bBoKm6TLmVT1peh2i:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/pcg/include/pcg/parallel_tensor_attrs.h#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-18 04:55 UTC, lockshaw requested changes
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1410)* status: all files reviewed, 2 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/src/local_cost_estimator.cc` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7h1z66McwsCIpsEsr:-O-dfqnKDIn4SGrTddGP:bm2ao2f) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L45)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Even for memory?
</blockquote></details>

For now let's go with that, we can always change it later if we need to factor it in
___
*[`lib/local-execution/src/local_slots_backing.cc` line 30 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-Zh-eV20jR015LPPYl:-O-dg2U98p1PomvCCU6-:b-m0bwl3) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/src/local_slots_backing.cc#L30)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

How should I extract the string value of an unknown enum case?
</blockquote></details>

You shouldn't need to? With dtgen, as long as you have the `fmt` feature enabled enums should automatically support stringification as above
___
*[`lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc` line 18 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-dgOKL1IHTMqNZJsja:-O-dgOKL1IHTMqNZJsjb:b-sp83iq) ([raw file](https://github.com/flexflow/FlexFlow/blob/10b1c5bf9bb6b88dde6f1397bdc192753c4a33f1/lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc#L18)):*
> ```cpp
> ComputationGraphOpAttrs
>     compgraph_op_attrs_from_pcg_op_attrs(PCGOperatorAttrs const &op) {
>   if (op.has<BatchMatmulAttrs>()) {
> ```

`.visit` using `utils/overload.h` might be cleaner? No strong feelings here


<!-- Sent from Reviewable.io -->

2024-06-18 15:49 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1410)* status: 18 of 29 files reviewed, 2 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/src/local_cost_estimator.cc` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-7h1z66McwsCIpsEsr:-O-fvlOQ23jnPML3O8rh:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d7be5a2b76257d8a20e8756d4d98a0e23454c6a3/lib/local-execution/src/local_cost_estimator.cc#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

For now let's go with that, we can always change it later if we need to factor it in
</blockquote></details>

Done.
___
*[`lib/local-execution/src/local_slots_backing.cc` line 30 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-Zh-eV20jR015LPPYl:-O-fx2C0DXHzdu6ZEO-A:bslndb5) ([raw file](https://github.com/flexflow/FlexFlow/blob/6b1a74fc4120654398ce209065525d46306c3fb1/lib/local-execution/src/local_slots_backing.cc#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You shouldn't need to? With dtgen, as long as you have the `fmt` feature enabled enums should automatically support stringification as above
</blockquote></details>

Ah, it's because `IsGrad` wasn't being generated. Fixed.
___
*[`lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc` line 18 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-dgOKL1IHTMqNZJsja:-O-fx-UM8UbbBcSQHn-9:b-b2i9qv) ([raw file](https://github.com/flexflow/FlexFlow/blob/10b1c5bf9bb6b88dde6f1397bdc192753c4a33f1/lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`.visit` using `utils/overload.h` might be cleaner? No strong feelings here
</blockquote></details>

How do I write this?


<!-- Sent from Reviewable.io -->

2024-06-18 16:24 UTC, lockshaw commented
*[`lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc` line 18 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-dgOKL1IHTMqNZJsja:-O-g9PyW0M8RDaDFtDrH:bntyhv3) ([raw file](https://github.com/flexflow/FlexFlow/blob/10b1c5bf9bb6b88dde6f1397bdc192753c4a33f1/lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc#L18)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

How do I write this?
</blockquote></details>

```.visit<ReturnType>(overload {
  [](BatchMatmulAttrs const &attrs) { ... },
  [](BatchNormAttrs const &attrs) { ... },
})```
```



<!-- Sent from Reviewable.io -->

2024-06-18 16:25 UTC, lockshaw commented
*[`lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc` line 18 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-dgOKL1IHTMqNZJsja:-O-g9f6H9jEViaUvNk0C:b-37emhd) ([raw file](https://github.com/flexflow/FlexFlow/blob/10b1c5bf9bb6b88dde6f1397bdc192753c4a33f1/lib/op-attrs/src/op-attrs/pcg_operator_attrs.cc#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

```.visit<ReturnType>(overload {
  [](BatchMatmulAttrs const &attrs) { ... },
  [](BatchNormAttrs const &attrs) { ... },
})```
```

</blockquote></details>

Missing first line: `.visit<ComputationGraphOpAttrs>(overload {`


<!-- Sent from Reviewable.io -->

2024-06-18 23:49 UTC, lockshaw requested changes
> Reviewed 7 of 11 files at r4, 8 of 9 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1410)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/cost_details.struct.toml` line 8 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-hjtYk4VXy1zKPHE_S:-O-hjtYk4VXy1zKPHE_T:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/2d09dfe64e651baa532348f87007c4b631f8af70/lib/local-execution/include/local-execution/cost_details.struct.toml#L8)):*
> ```TOML
>   "rapidcheck",
>   "fmt",
> ]
> ```





_Suggestion:_
```TOML
features = [
  "eq",
  "ord",
  "hash",
  "json",
  "rapidcheck",
  "fmt",
]
```


<!-- Sent from Reviewable.io -->

2024-06-18 23:54 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1410)* status: 31 of 34 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/local-execution/include/local-execution/cost_details.struct.toml` line 8 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1410#-O-hjtYk4VXy1zKPHE_S:-O-hl7d_-8z3BnZh7bxw:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/2d09dfe64e651baa532348f87007c4b631f8af70/lib/local-execution/include/local-execution/cost_details.struct.toml#L8)):*
> ```TOML
>   "rapidcheck",
>   "fmt",
> ]
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-19 00:05 UTC, lockshaw approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1410)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2024-06-20 03:53 UTC, lockshaw approved these changes
> Reviewed 3 of 6 files at r8, 208 of 209 files at r9, 210 of 210 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1410)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2024-06-20 03:55 UTC, merged