Local execution tests
flexflow/FlexFlow pull request #1418
Opened 2024-06-21 00:47 UTC by reyna-abhyankar

**Description of changes:**

Tests for task spec workflow, local backing, and local cost estimator 

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-06-24 02:19 UTC, lockshaw requested changes
Is `LocalCostEstimator` going to be tested in this PR or is that being moved to a separate PR?

> Reviewed 11 of 70 files at r1.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-:-O071MXM0pr7YljkH-pm:bkpn26r)* status: 11 of 70 files reviewed, 13 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 40 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06xobi8HpAeBUQZLDR:-O06xobi8HpAeBUQZLDS:b-oy5lz4) ([raw file](https://github.com/flexflow/FlexFlow/blob/d45673349801fec13e7d25c7d8319b9e689f0fef/lib/local-execution/include/local-execution/local_slots_backing.h#L40)):*
> ```objc
>       input_tensor_slots;
>   std::unordered_map<layer_guid_t, std::vector<tensor_guid_t>>
>       weight_tensor_slots;
> ```

Why remove `weigh_tensor_slots`? Are you just bundling them into `input_tensor_slots`? It looks like this is the case, does this have any forseeable downsides?
___
*[`lib/local-execution/include/local-execution/op_task_invocation.h` line 61 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06yb2EDcmzhmTJIXeX:-O06yb2EDcmzhmTJIXeY:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/include/local-execution/op_task_invocation.h#L61)):*
> ```objc
>   }
> 
>   bool operator==(OpTaskBinding const &other);
> ```





_Suggestion:_
```objc
  bool operator==(OpTaskBinding const &other) const;
  bool operator!=(OpTaskBinding const &other) const;
  
private:
  std::tuple<decltype(tensor_bindings) const &, decltype(arg_bindings) const &> tie() const;
```
___
*[`lib/local-execution/src/local_training_backing.cc` line 74 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06yO-L2WvqieUJfSJJ:-O06yO-L2WvqieUJfSJK:bt2fjef) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/src/local_training_backing.cc#L74)):*
> ```cpp
>   for (layer_guid_t const &operator_node :
>        topological_ordering(this->computation_graph)) {
>     if (contains_key(this->task_registry.init_task_ids, operator_node)) {
> ```

This feels like the kind of thing where if it doesn't have that key an error should be thrown, not that the program should just silently skip it
___
*[`lib/local-execution/src/local_training_backing.cc` line 124 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06y44T8VMPZEjNbxMG:-O06y44T8VMPZEjNbxMH:b-ch7571) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/src/local_training_backing.cc#L124)):*
> ```cpp
> }
> 
> TaskArgumentAccessor const &LocalTrainingBacking::get_task_arg_accessor(
> ```

Remove, never return a reference to a local variable/value (as that variable gets deallocated as soon as the function returns and you're left with a dangling pointer)
___
*[`lib/local-execution/src/op_task_invocation.cc` line 26 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06ywuJ7gAbo1HRPlo5:-O06ywuK0D8a1jxkulPY:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/src/op_task_invocation.cc#L26)):*
> ```cpp
>   return this->get_tensor_bindings() == other.get_tensor_bindings() &&
>          this->get_arg_bindings() == other.get_arg_bindings();
> }
> ```





_Suggestion:_
```cpp
bool OpTaskBinding::operator==(OpTaskBinding const &other) {
  return this->tie() == other.tie();
}

bool OpTaskBinding::operator!=(OpTaskBinding const &other) {
  return this->tie() != other.tie();
}

std::tuple<etc.> OpTaskBinding::tie() const {
  return std::tie(this->tensor_bindings, this->arg_bindings);
}
```
___
*[`lib/local-execution/test/src/test_local_backing_multi.cc` line 11 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O070SjDBXxJ-eQGdGmW:-O070SjDBXxJ-eQGdGmX:bsiwwtb) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_multi.cc#L11)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("Local Backing Multiple Operators -- Cast->Linear") {
> ```

How much of this is duplicated from the the single-operator check? If possible remove some of the duplication from this test as it's so big it's hard to tell what's going on. If you want an end-to-end test that runs a bunch of the system that's fine, but in that case maybe don't do intermediate checks on every value throughout the whole execution, just check the overall functionality you intend and leave the low-level detailed checks to smaller testcases
___
*[`lib/local-execution/test/src/test_local_backing_multi.cc` line 43 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06zpD84I3-NtWvhUVj:-O06zpD84I3-NtWvhUVk:b-x0zzjs) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_multi.cc#L43)):*
> ```cpp
>     // -- linear
>     int out_channels = 16;
>     TensorAttrs linear_output_shape =
> ```

Why not just use `get_output_shape`?
___
*[`lib/local-execution/test/src/test_local_backing_multi.cc` line 92 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O070eP4-qcZnTUB4hWg:-O070eP4-qcZnTUB4hWh:b-9ntvly) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_multi.cc#L92)):*
> ```cpp
>     GenericTensorAccessorW tensor_backing = allocator.allocate_tensor(input);
>     tensor_backing_map.insert({tensor_id, tensor_backing});
>     std::vector<tensor_guid_t> cast_result = cg_builder.add_layer(
> ```

Why not just use `cg_builder.cast`? It feels like this test is trying to test everything all at once, which makes it really hard to tell what's going on.
___
*[`lib/local-execution/test/src/test_local_backing_single.cc` line 60 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O07-77zBFUhECOx2ox1:-O07-77zBFUhECOx2ox2:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_single.cc#L60)):*
> ```cpp
> 
>     SUBCASE("Task Registration") {
>       TaskRegistry const task_registry = local_backing.get_task_registry();
> ```





_Suggestion:_
```cpp
     TaskRegistry task_registry = local_backing.get_task_registry();
```
___
*[`lib/local-execution/test/src/test_local_backing_single.cc` line 65 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O07-BI931fzQaLVKfxj:-O07-BI931fzQaLVKfxk:b-5mfxch) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_single.cc#L65)):*
> ```cpp
> 
>       correct_forward_task_ids.insert({layer_guid, CAST_FWD_TASK_ID});
>       correct_backward_task_ids.insert({layer_guid, CAST_BWD_TASK_ID});
> ```

Also break into two further subcases, one for "forward" and one for "backward" (for readability)



_Suggestion:_
```cpp
      std::unordered_map<layer_guid_t, task_id_t> correct_forward_task_ids = {{layer_guid, CAST_FWD_TASK_ID}};
      std::unordered_map<layer_guid_t, task_id_t> correct_backward_task_ids = {{layer_guid, CAST_BWD_TASK_ID}};
```
___
*[`lib/local-execution/test/src/test_local_backing_single.cc` line 170 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O07-sl91BhnBhwvQz_h:-O07-sl91BhnBhwvQz_i:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_single.cc#L170)):*
> ```cpp
>       binding.bind_grad(INPUT, input_tensor(0));
>       binding.bind(OUTPUT, output_tensor(0));
>       binding.bind_grad(OUTPUT, output_tensor(0));
> ```





_Suggestion:_
```cpp
      OpTaskBinding binding = [&] {
        OpTaskBinding b;
        b.bind_arg(PROFILING, profiling_settings());
        b.bind_arg [...]

2024-06-24 02:26 UTC, lockshaw commented
*[`lib/local-execution/test/src/test_local_backing_multi.cc` line 117 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O0732jU06fNGE4P3sPl:-O0732jU06fNGE4P3sPm:b-ea8b28) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_multi.cc#L117)):*
> ```cpp
>     std::vector<layer_guid_t> layer_guids =
>         topological_ordering(cg_builder.computation_graph);
>     layer_guid_t cast_layer_guid = layer_guids.at(0);
> ```

A better way is to probably add the ability to get a layer by name in `ComputationGraph`


<!-- Sent from Reviewable.io -->

2024-06-25 15:57 UTC, reyna-abhyankar reviewed
I'd say this does test the functionality of local cost estimator since it's basically just making calls to local backing

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-:-O0Eq4viAX5VPqFTXZL2:bq7uq1o)* status: 6 of 70 files reviewed, 14 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 40 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06xobi8HpAeBUQZLDR:-O0CrZkW2qcN26dwbdcL:b-ao3hvt) ([raw file](https://github.com/flexflow/FlexFlow/blob/d45673349801fec13e7d25c7d8319b9e689f0fef/lib/local-execution/include/local-execution/local_slots_backing.h#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why remove `weigh_tensor_slots`? Are you just bundling them into `input_tensor_slots`? It looks like this is the case, does this have any forseeable downsides?
</blockquote></details>

Yes, this is in accordance with what's in computation graph builder, as weights are concatenated to the inputs. AFAIK there's no way to differentiate whether a `tensor_guid_t` represents a weight tensor or not (if there is, I'm happy to switch back to having `weight_tensor_slots` instead)
___
*[`lib/local-execution/include/local-execution/op_task_invocation.h` line 61 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06yb2EDcmzhmTJIXeX:-O0EqShe9Oxzl8TxN_EZ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/include/local-execution/op_task_invocation.h#L61)):*
> ```objc
>   }
> 
>   bool operator==(OpTaskBinding const &other);
> ```

Done.
___
*[`lib/local-execution/src/local_training_backing.cc` line 74 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06yO-L2WvqieUJfSJJ:-O0Crrg7AoA0yVpqPWbD:b8s8yld) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/src/local_training_backing.cc#L74)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This feels like the kind of thing where if it doesn't have that key an error should be thrown, not that the program should just silently skip it
</blockquote></details>

I think here it's fine because some operators don't have an init task and others do. So only the ones with init task should be called since this is still iterating over all the operators in the graph.
___
*[`lib/local-execution/src/local_training_backing.cc` line 124 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06y44T8VMPZEjNbxMG:-O0Eqc_m07jnFYLxqE0Z:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/src/local_training_backing.cc#L124)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove, never return a reference to a local variable/value (as that variable gets deallocated as soon as the function returns and you're left with a dangling pointer)
</blockquote></details>

Done.
___
*[`lib/local-execution/src/op_task_invocation.cc` line 26 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06ywuJ7gAbo1HRPlo5:-O0ErO_ACbU_nxIEeLin:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/src/op_task_invocation.cc#L26)):*
> ```cpp
>   return this->get_tensor_bindings() == other.get_tensor_bindings() &&
>          this->get_arg_bindings() == other.get_arg_bindings();
> }
> ```

Done.
___
*[`lib/local-execution/test/src/test_local_backing_multi.cc` line 11 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O070SjDBXxJ-eQGdGmW:-O0F5U_N8FE6HltRMVNe:bsabg4l) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_multi.cc#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

How much of this is duplicated from the the single-operator check? If possible remove some of the duplication from this test as it's so big it's hard to tell what's going on. If you want an end-to-end test that runs a bunch of the system that's fine, but in that case maybe don't do intermediate checks on every value throughout the whole execution, just check the overall functionality you intend and leave the low-level detailed checks to smaller testcases
</blockquote></details>

Yeah, I agree. I'll make this change and only test things that aren't already tested by single operator 
___
*[`lib/local-execution/test/src/test_local_backing_multi.cc` line 43 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06zpD84I3-NtWvhUVj:-O0F5dCQCc7pqa3lD59v:b-3mjob8) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_multi.cc#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not just use `get_output_shape`?
</blockquote></details>

Similar to not using `ComputationGraphBuilder::cast`, I forgot that I could do this :smiling_face_with_tear: 
I will see if this intermediate step is necessary when I fix this case similar to the single op. otherwise, I can just chain `.cast()` and `.linear()` and not need to worry about these values.
___
*[`lib/local-execution/test/src/test_local_backing_multi.cc` line 92 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O070eP4-qcZnTUB4hWg:-O0Evaeo1JS1_gU_rotN:b-d8inis) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_multi.cc#L92)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not just use `cg_builder.cast`? It feels like this test is trying to test everything all at once, which makes it really hard to tell what's going on.
</blockquote></details>

I completely forgot I could do that...using that instead
___
*[`lib/local-execution/test/src/test_local_backing_multi.cc` line 117 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O0732jU06fNGE4P3sPl:-O0Ex-F44iXBnK_iOEbi:b-xllqz4) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_multi.cc#L117)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

A better way is to probably add the ability to get a layer by name in `ComputationGraph`
</blockquote></details>

`name` is currently optional in `LayerAttrs`, should we make it required? 
___
*[`lib/local-execution/test/src/test_local_backing_single.cc` line 60 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O07-77zBFUhECOx2ox1:-O0Erfjs9O3sCJFQpn4a:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_single.cc#L60)):*
> ```cpp
> 
>     SUBCASE("Task Registration") {
>       TaskRegistry const task_registry = local_backing.get_task_registry();
> ```

Done.
___
*[`lib/local-execution/test/src/test_local_backing_single.cc` line 65 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O07-BI931fzQaLVKfxj:-O0Es2WG3BE27U_WR1Rb:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_single.cc#L65)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Also break into two further subcases, one for "forward" and one for "backward" (for readability)
</blockquote></details>

Done.
___
*[`lib/local-execution/test/src/test_local_backing_single.cc` line 170 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O07-sl91BhnBhwvQz_h:-O0Es7dFArdwZnmSGYy7:bcgjvre) ([raw file](https://github.com/flexflow/FlexFl [...]

2024-06-26 04:50 UTC, lockshaw requested changes
As discussed at our meeting, add one end-to-end test for local cost estimator that just checks the interface

> Reviewed 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-:-O0HqBiQB73gQUc1Ty_v:bcl9w8t)* status: 9 of 70 files reviewed, 9 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/op_task_invocation.h` line 76 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O0HpOIa26FZ7OOwkhiO:-O0HpOIa26FZ7OOwkhiP:bq01qxu) ([raw file](https://github.com/flexflow/FlexFlow/blob/767ea1da35f23d8573829b60ae3ef05c91a2facf/lib/local-execution/include/local-execution/op_task_invocation.h#L76)):*
> ```objc
>   std::tuple<decltype(tensor_bindings) const &, decltype(arg_bindings) const &>
>       tie() const;
> };
> ```

Makes it a bit easier to tell at a glance what is a member and what is a method

If this is an issue due to the definition order, add another `private:` section after the member variables ones--the additional `private:` doesn't have a semantic effect but is nice for dividing things up for readability.



_Suggestion:_
```objc
private:
  void insert_arg_spec(slot_id name, OpArgSpec const &arg_spec);
  std::tuple<decltype(tensor_bindings) const &, decltype(arg_bindings) const &>
    tie() const;
    
private:
  std::unordered_map<std::pair<slot_id, IsGrad>, OpTensorSpec> tensor_bindings;
  std::unordered_map<slot_id, OpArgSpec> arg_bindings;
};
```
___
*[`lib/local-execution/src/local_training_backing.cc` line 74 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O06yO-L2WvqieUJfSJJ:-O0HpsMuEKj6eAsUAdFE:b-orumjy) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/src/local_training_backing.cc#L74)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I think here it's fine because some operators don't have an init task and others do. So only the ones with init task should be called since this is still iterating over all the operators in the graph.
</blockquote></details>

Good point
___
*[`lib/local-execution/src/local_training_backing.cc` line 124 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O0Hpyps0T9krlbVJhn-:-O0Hpyps0T9krlbVJhn0:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/767ea1da35f23d8573829b60ae3ef05c91a2facf/lib/local-execution/src/local_training_backing.cc#L124)):*
> ```cpp
> }
> 
> TaskArgumentAccessor const LocalTrainingBacking::get_task_arg_accessor(
> ```





_Suggestion:_
```cpp
TaskArgumentAccessor LocalTrainingBacking::get_task_arg_accessor(
```


<!-- Sent from Reviewable.io -->

2024-07-09 16:15 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: 1 of 113 files reviewed, 9 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/include/local-execution/op_task_invocation.h` line 76 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O0HpOIa26FZ7OOwkhiO:-O0Lp9OH24rZUFIYQRTc:bbyh9rd) ([raw file](https://github.com/flexflow/FlexFlow/blob/767ea1da35f23d8573829b60ae3ef05c91a2facf/lib/local-execution/include/local-execution/op_task_invocation.h#L76)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Makes it a bit easier to tell at a glance what is a member and what is a method

If this is an issue due to the definition order, add another `private:` section after the member variables ones--the additional `private:` doesn't have a semantic effect but is nice for dividing things up for readability.
</blockquote></details>

Added another private section, just with the member variables before (so I can still use the `decltype`)
___
*[`lib/local-execution/src/local_training_backing.cc` line 124 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O0Hpyps0T9krlbVJhn-:-O0LpNJmD_q_CmnigaJI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/767ea1da35f23d8573829b60ae3ef05c91a2facf/lib/local-execution/src/local_training_backing.cc#L124)):*
> ```cpp
> }
> 
> TaskArgumentAccessor const LocalTrainingBacking::get_task_arg_accessor(
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-09 20:43 UTC, lockshaw requested changes
Looks good to me, just waiting on 1384 to merge. I didn't go through everything with a fine-toothed comb, but at a high level things looked good (maybe more test code than I'd like, but sadly I think that's just C++ being C++)

> Reviewed 12 of 88 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-:-O1ODk5I6sGf7tB_s7zN:brkwwmq)* status: 13 of 113 files reviewed, 6 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/test/src/test_local_task_arg_accessor.cc` line 34 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1OBx1L1KLv57i9C3Gh:-O1OBx1L1KLv57i9C3Gi:bw9eag0) ([raw file](https://github.com/flexflow/FlexFlow/blob/987b9ce42ba49271159a20ec4e5077ce562720bc/lib/local-execution/test/src/test_local_task_arg_accessor.cc#L34)):*
> ```cpp
>         query_grad, query_grad};
> 
>     enum MockSlots {
> ```

I feel like the name "mock" in a bunch of this code is somewhat misleading (as you're not really mocking objects, you're just constructing example objects) so maybe just name this "Slots" or "ExampleSlots" or something? I'm not that convinced, just something I was thinking about as I was reading through this PR.



_Code quote:_
```cpp
Mock
```
___
*[`lib/local-execution/test/src/test_local_task_arg_accessor.cc` line 85 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1OCOV1DbDc1hGxM2he:-O1OCOV1DbDc1hGxM2hf:bximtlp) ([raw file](https://github.com/flexflow/FlexFlow/blob/987b9ce42ba49271159a20ec4e5077ce562720bc/lib/local-execution/test/src/test_local_task_arg_accessor.cc#L85)):*
> ```cpp
>     }
> 
>     SUBCASE("get_tensor") {
> ```

Why are there two subcases for `get_tensor`? Should this be `get_variadic_tensor`?
___
*[`lib/local-execution/test/src/test_utils.cc` line 3 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1OD5rDCCwlt6op6B3b:-O1OD5rDCCwlt6op6B3c:b-fw2ks0) ([raw file](https://github.com/flexflow/FlexFlow/blob/987b9ce42ba49271159a20ec4e5077ce562720bc/lib/local-execution/test/src/test_utils.cc#L3)):*
> ```cpp
> #include "test_utils.h"
> 
> PerDeviceFFHandle get_mock_per_device_ff_handle() {
> ```

I agree with the mock naming here though
___
*[`lib/local-execution/test/src/test_local_backing_multi.cc` line 117 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O0732jU06fNGE4P3sPl:-O1ODHMp8nLic4wXoZUq:b-7z6c0g) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_multi.cc#L117)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

`name` is currently optional in `LayerAttrs`, should we make it required?
</blockquote></details>

No, it should be optional, but that doesn't mean you can't get layers if they do have an assigned name


<!-- Sent from Reviewable.io -->

2024-07-10 00:47 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: 13 of 116 files reviewed, 4 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/test/src/test_local_task_arg_accessor.cc` line 34 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1OBx1L1KLv57i9C3Gh:-O1P5-iA9u7vOmgl4pC8:bj9b6uv) ([raw file](https://github.com/flexflow/FlexFlow/blob/987b9ce42ba49271159a20ec4e5077ce562720bc/lib/local-execution/test/src/test_local_task_arg_accessor.cc#L34)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I feel like the name "mock" in a bunch of this code is somewhat misleading (as you're not really mocking objects, you're just constructing example objects) so maybe just name this "Slots" or "ExampleSlots" or something? I'm not that convinced, just something I was thinking about as I was reading through this PR.
</blockquote></details>

Yeah, actually I'm not even sure that's necessary either. It seems perfectly fine without "example" or "mock" as a prefix.
___
*[`lib/local-execution/test/src/test_local_task_arg_accessor.cc` line 85 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1OCOV1DbDc1hGxM2he:-O1P4UKVEt_b338ATdgA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/987b9ce42ba49271159a20ec4e5077ce562720bc/lib/local-execution/test/src/test_local_task_arg_accessor.cc#L85)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are there two subcases for `get_tensor`? Should this be `get_variadic_tensor`?
</blockquote></details>

Done.
___
*[`lib/local-execution/test/src/test_utils.cc` line 3 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1OD5rDCCwlt6op6B3b:-O1P4VPv7QrMiSfICmtz:b-oofm7b) ([raw file](https://github.com/flexflow/FlexFlow/blob/987b9ce42ba49271159a20ec4e5077ce562720bc/lib/local-execution/test/src/test_utils.cc#L3)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I agree with the mock naming here though
</blockquote></details>

Ok, I'll change the others.
___
*[`lib/local-execution/test/src/test_local_backing_multi.cc` line 117 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O0732jU06fNGE4P3sPl:-O1P4aRjAn3M-KaJswKI:b2nhll9) ([raw file](https://github.com/flexflow/FlexFlow/blob/ef945e72c19ac2a1afedf9ad77ed956eed423b70/lib/local-execution/test/src/test_local_backing_multi.cc#L117)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

No, it should be optional, but that doesn't mean you can't get layers if they do have an assigned name
</blockquote></details>

Ok.


<!-- Sent from Reviewable.io -->

2024-07-10 01:36 UTC, lockshaw requested changes
> Reviewed 38 of 88 files at r3, 65 of 65 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 43 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`.proj.toml` line 18 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P7TLOD11S2NPzFQM5:-O1P7TLOD11S2NPzFQM6:b-zab1d8) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/.proj.toml#L18)):*
> ```TOML
> 
> test_targets = [
>   "kernels-tests",
> ```

Remove until this doesn't crash on GPU machines (if you've updated all the test suite markings so it doesn't crash, let me know and we can keep this in)
___
*[`lib/kernels/include/kernels/accessor.h` line 151 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P7fgy2DE6A1CIrs1L:-O1P7fgy2DE6A1CIrs1M:bbef68h) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/kernels/include/kernels/accessor.h#L151)):*
> ```objc
>                               GenericTensorAccessorW const &acc2);
> 
> bool is_shape_and_dtype_correct(GenericTensorAccessorW const &accessor,
> ```

What does this mean? Is "equal" or "matches" better? Maybe "has_shape_and_dtype" or "shape_and_dtype_matches"



_Code quote:_
```objc
is_shape_and_dtype_correct
```
___
*[`lib/kernels/src/array_shape.cc` line 50 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PGjbxE2C0hJp21PhU:-O1PGjbxE2C0hJp21PhV:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/kernels/src/array_shape.cc#L50)):*
> ```cpp
> 
> std::size_t ArrayShape::at(ff_dim_t idx) const {
>   return dims.at(legion_dim_from_ff_dim(idx, num_dims()));
> ```





_Suggestion:_
```cpp
  return dims.at(legion_dim_from_ff_dim(idx, this->num_dims()));
```
___
*[`lib/kernels/src/array_shape.cc` line 68 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PGlg6DNZE2KIK_4Nr:-O1PGlg6DNZE2KIK_4Ns:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/kernels/src/array_shape.cc#L68)):*
> ```cpp
> 
> std::optional<std::size_t> ArrayShape::at_maybe(ff_dim_t index) const {
>   return this->at_maybe(legion_dim_from_ff_dim(index, num_dims()));
> ```





_Suggestion:_
```cpp
  return this->at_maybe(legion_dim_from_ff_dim(index, this->num_dims()));
```
___
*[`lib/kernels/src/array_shape.cc` line 79 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PGt_91z7Dlw1N053V:-O1PGt_91z7Dlw1N053W:bkgpc5k) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/kernels/src/array_shape.cc#L79)):*
> ```cpp
>   std::reverse_copy(shape.dims.begin(), shape.dims.end(), sizes.begin());
>   return TensorShape{TensorDims{FFOrdered<size_t>(sizes.begin(), sizes.end())},
>                      dtype};
> ```

Use `reversed` from `utils/containers.h`



_Code quote:_
```cpp
  std::vector<size_t> sizes(shape.dims.size());
  std::reverse_copy(shape.dims.begin(), shape.dims.end(), sizes.begin());
  return TensorShape{TensorDims{FFOrdered<size_t>(sizes.begin(), sizes.end())},
                     dtype};
```
___
*[`lib/local-execution/include/local-execution/arg_ref.h` line 36 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PHDT94zH-RokN_Jst:-O1PHDT94zH-RokN_Jsu:br3oxtu) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/arg_ref.h#L36)):*
> ```objc
> 
>   bool operator==(ArgRefSpec const &other) const {
>     return this->get_ref_type() == other.get_ref_type() &&
> ```

Use `tie` pattern
___
*[`lib/local-execution/include/local-execution/concrete_arg.h` line 27 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8HniDCG9c6d0B_Ml:-O1P8HniDCG9c6d0B_Mm:b-4mz7wn) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/concrete_arg.h#L27)):*
> ```objc
>   // template <typename T>
>   bool operator==(ConcreteArgSpec const &other) const {
>     if (this->get_type_index() == other.get_type_index()) {
> ```

Move implementation to `.cc` file, update to use `tie()` pattern
___
*[`lib/local-execution/include/local-execution/device_specific.h` line 16 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8xXzDO9GjceejU7P:-O1P8xXzDO9GjceejU7Q:brb792i) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/device_specific.h#L16)):*
> ```objc
>   template <typename... Args>
>   static DeviceSpecific<T> create(T device_specific, Args &&...args) {
>     return DeviceSpecific<T>(&device_specific, std::forward<Args>(args)...);
> ```

This is a memory error, as you copy `device_specific` to this function's stack frame, take a pointer to it, and then leave the function. 

What's the ownership model for things wrapped in `DeviceSpecific`? Is there one?

Also, generally the semantics of these `create` functions is that they pass the `args` to `T`'s constructor, rather than taking in a `T` as an argument (which they can still do in the standard semantics using a copy constructor)
___
*[`lib/local-execution/include/local-execution/device_specific.h` line 20 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8U-n0ZqVF4arJzF4:-O1P8U-n0ZqVF4arJzF5:b-4mz7wn) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/device_specific.h#L20)):*
> ```objc
> 
>   bool operator==(DeviceSpecific const &other) const {
>     return this->ptr == other.ptr && this->device_idx == other.device_idx;
> ```

Move implementation to `.cc` file, update to use `tie()` pattern
___
*[`lib/local-execution/include/local-execution/device_specific.h` line 40 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8_Ty4TGQHjvdZiRU:-O1P8_Ty4TGQHjvdZiRV:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/device_specific.h#L40)):*
> ```objc
> 
> private:
>   DeviceSpecific(T *ptr, size_t device_idx = 0)
> ```

Why?



_Code quote:_
```objc
size_t device_idx = 0)
```
___
*[`lib/local-execution/include/local-execution/legion_tensor_shape.h` line 32 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P9Y-17CSdE5ttzweg:-O1P9Y-17CSdE5ttzweh:brhm8rg) ([raw file](https://github.com/flexflow/FlexFlow/blob/d30c8f0b74b83f3ecaec594d9e3efd19b26c212a/lib/local-execution/include/local-execution/legion_tensor_shape.h#L32)):*
> ```objc
> 
> ff_dim_t to_ff(legion_dim_t, size_t num_dims);
> legion_dim_t legion_dim_from_ff_dim(ff_dim_t, size_t num_dims);
> ```

Why removed?
___
*[`lib/local-execution/include/local-execution/local_cpu_allocator.h` line 9 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P9egEC1s0o7SCXqdd:-O1P9egEC1s0o7SCXqde:bski875) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/local_cpu_allocator.h#L9)):*
> ```objc
>   LocalCPUAllocator() = default;
>   LocalCPUAllocator(LocalCPUAllocator const &) = delete;
>   LocalCPUAllocator(LocalCPUAllocator &&) = delete;
> ```

I think you want move semantics and to have copy semantics disabled? 

Also, couldn't this be achieved by making `ptrs` instead a `std::unordered_set<std::unique_ptr<void>>`?



_Suggestion:_
```objc
  LocalCPUAllocator(LocalCPUAllocator const &) = delete;
  LocalCPUAllocator &operator=(LocalCPUAllocator const &) = delete;
  
  LocalCPUAllocator(LocalCPUAllocator &&);
  LocalCPUAllocator &operator=(LocalCPUAllocator &&);
```
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 22 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PBlYU15x-AtXqgsrK [...]

2024-07-16 15:11 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 43 unresolved discussions (waiting on @lockshaw)

___
*[`.proj.toml` line 18 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P7TLOD11S2NPzFQM5:-O1vSF3eAd7NR_pkx14f:bss4a2b) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/.proj.toml#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove until this doesn't crash on GPU machines (if you've updated all the test suite markings so it doesn't crash, let me know and we can keep this in)
</blockquote></details>

Removed.
___
*[`lib/kernels/include/kernels/accessor.h` line 151 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P7fgy2DE6A1CIrs1L:-O1v_AL52emhiA2SXGVo:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/kernels/include/kernels/accessor.h#L151)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What does this mean? Is "equal" or "matches" better? Maybe "has_shape_and_dtype" or "shape_and_dtype_matches"
</blockquote></details>

Done.
___
*[`lib/kernels/src/array_shape.cc` line 50 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PGjbxE2C0hJp21PhU:-O1v_FQq95bonbayEoLb:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/kernels/src/array_shape.cc#L50)):*
> ```cpp
> 
> std::size_t ArrayShape::at(ff_dim_t idx) const {
>   return dims.at(legion_dim_from_ff_dim(idx, num_dims()));
> ```

Done.
___
*[`lib/kernels/src/array_shape.cc` line 68 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PGlg6DNZE2KIK_4Nr:-O1v_HgT9yi_oThdyVb7:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/kernels/src/array_shape.cc#L68)):*
> ```cpp
> 
> std::optional<std::size_t> ArrayShape::at_maybe(ff_dim_t index) const {
>   return this->at_maybe(legion_dim_from_ff_dim(index, num_dims()));
> ```

Done.
___
*[`lib/kernels/src/array_shape.cc` line 79 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PGt_91z7Dlw1N053V:-O1vauy1BRMyjwlYj72R:bcsxjar) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/kernels/src/array_shape.cc#L79)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use `reversed` from `utils/containers.h`
</blockquote></details>

Just switched this to use the reverse iterator. That fine?
___
*[`lib/local-execution/include/local-execution/arg_ref.h` line 36 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PHDT94zH-RokN_Jst:-O1vcJLR5NtnHWpqCVaP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/arg_ref.h#L36)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use `tie` pattern
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/concrete_arg.h` line 27 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8HniDCG9c6d0B_Ml:-O1vdgZn6e-zngkDgMBj:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/concrete_arg.h#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move implementation to `.cc` file, update to use `tie()` pattern
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/device_specific.h` line 16 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8xXzDO9GjceejU7P:-O1veO9YBginOZs9Or53:b-ox7mo3) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/device_specific.h#L16)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This is a memory error, as you copy `device_specific` to this function's stack frame, take a pointer to it, and then leave the function. 

What's the ownership model for things wrapped in `DeviceSpecific`? Is there one?

Also, generally the semantics of these `create` functions is that they pass the `args` to `T`'s constructor, rather than taking in a `T` as an argument (which they can still do in the standard semantics using a copy constructor)
</blockquote></details>

I see. This is worth some discusion -- I removed the pointer temporarily just to get the build working / test passing (since there's only one device anyway), but this needs to be ironed out for distributed.
___
*[`lib/local-execution/include/local-execution/device_specific.h` line 20 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8U-n0ZqVF4arJzF4:-O1vryQQ1EcXHin1w0ys:b-mfbjym) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/device_specific.h#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move implementation to `.cc` file, update to use `tie()` pattern
</blockquote></details>

Shouldn't we keep the implementation in the `.h` file since `DeviceSpecific` is a template struct?
___
*[`lib/local-execution/include/local-execution/device_specific.h` line 40 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8_Ty4TGQHjvdZiRU:-O1vspwN9xqJ-5ESN0eY:b-awjkgo) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/device_specific.h#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Figured this was easier than refactoring all the operator code to pass in a device index for now since it's only using one device anyway.
___
*[`lib/local-execution/include/local-execution/legion_tensor_shape.h` line 32 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P9Y-17CSdE5ttzweg:-O1vtQLY4Fdig_OAOPgV:b-jw1g88) ([raw file](https://github.com/flexflow/FlexFlow/blob/d30c8f0b74b83f3ecaec594d9e3efd19b26c212a/lib/local-execution/include/local-execution/legion_tensor_shape.h#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why removed?
</blockquote></details>

Forgot why I removed this, just added it back and the corresponding implementation.
___
*[`lib/local-execution/include/local-execution/local_cpu_allocator.h` line 9 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P9egEC1s0o7SCXqdd:-O1vu2cxAjOWaUgKXzrb:bst7thg) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/local_cpu_allocator.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think you want move semantics and to have copy semantics disabled? 

Also, couldn't this be achieved by making `ptrs` instead a `std::unordered_set<std::unique_ptr<void>>`?
</blockquote></details>

In that case, won't it fail `CHECK_RC_COPY_VIRTUAL_COMPLIANT`?
___
*[`lib/local-execution/include/local-execution/local_slots_backing.h` line 22 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PBlYU15x-AtXqgsrK:-O1vuUhL8dgzp1Xs2uVp:b-76sj9j) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/local_slots_backing.h#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What tensors does this allocate? "new" is a bit vague
</blockquote></details>

It allocates any tensors that aren't already passed in to the backing. It also can just be `allocate_tensors` if that's clearer.
___
*[`lib/local-execution/include/local-exec [...]

2024-07-19 01:55 UTC, lockshaw requested changes
> Reviewed 40 of 40 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 33 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`.proj.toml` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27apIp983TTKhXXbE1:-O27apIp983TTKhXXbE2:b-wjqs53) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/.proj.toml#L25)):*
> ```TOML
>   # "compiler-tests",
>   "substitution-generator-tests",
>   # "local-execution-tests"
> ```

Is there a reason we can't enable this? Didn't we add an additional test suite for tests that require GPUs? As long as they don't also match the generated regex I don't see a reason why we wouldn't be able to enable the non-GPU-requiring local-execution tests (same for `kernel-tests` in the long-term, though I'm guessing the GPU tests in `kernels` haven't been moved over to use the new test suite)
___
*[`lib/kernels/include/kernels/profiling.h` line 9 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27RfMf9fYDHc1CkPdo:-O27RfMf9fYDHc1CkPdp:brp7znb) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/kernels/include/kernels/profiling.h#L9)):*
> ```objc
> namespace FlexFlow {
> 
> struct ProfilingSettings : public use_visitable_cmp<ProfilingSettings> {
> ```

Replace with `dtgen`
___
*[`lib/kernels/src/array_shape.cc` line 79 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PGt_91z7Dlw1N053V:-O27c-F52fkFPLfDkT4h:b8xhuww) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/kernels/src/array_shape.cc#L79)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Just switched this to use the reverse iterator. That fine?
</blockquote></details>

The better solution here is just to add a `template <typename T> FFOrdered<T> ff_ordered_from_legion_ordered(LegionOrdered<T> const &);` (probably in `kernels/legion_dim.h`) and use it here. If you'd like to use the reverse iterator in that function that's fine, but we should have a primitive for this as this is not an uncommon operation
___
*[`lib/local-execution/include/local-execution/device_specific.h` line 20 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8U-n0ZqVF4arJzF4:-O27SL1K8r-0X08gcQMk:b-1hq2ey) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/device_specific.h#L20)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Shouldn't we keep the implementation in the `.h` file since `DeviceSpecific` is a template struct?
</blockquote></details>

Good point, forgot about this.
___
*[`lib/local-execution/include/local-execution/device_specific.h` line 40 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8_Ty4TGQHjvdZiRU:-O27SZNc8HztuYeabnp5:bsrhq2u) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/device_specific.h#L40)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Figured this was easier than refactoring all the operator code to pass in a device index for now since it's only using one device anyway.
</blockquote></details>

None of the operator code should be using this as it's private I think?
___
*[`lib/local-execution/include/local-execution/local_cost_estimator.h` line 20 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27YqJg3nH1aB7ztFVE:-O27YqJg3nH1aB7ztFVF:b-gw0a46) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/local_cost_estimator.h#L20)):*
> ```objc
>                     std::vector<ParallelTensorAttrs> const &weights,
>                     std::vector<ParallelTensorAttrs> const &outputs,
>                     std::optional<MachineView> const &mv) const override;
> ```

Why did this become `optional`?
___
*[`lib/local-execution/include/local-execution/local_cpu_allocator.h` line 9 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P9egEC1s0o7SCXqdd:-O27YgmHES7SOnMYHgvz:bsspk71) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/local_cpu_allocator.h#L9)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

In that case, won't it fail `CHECK_RC_COPY_VIRTUAL_COMPLIANT`?
</blockquote></details>

Good point, in that case can you explicitly delete the `operator=`s too?
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 44 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27VyBiBfs51burz8dH:-O27VyBiBfs51burz8dI:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L44)):*
> ```objc
> };
> 
> bool are_slots_backings_equivalent_up_to_allocation_addresses(
> ```





_Suggestion:_
```objc
bool are_slots_backings_equivalent_up_to_tensor_allocation_addresses(
```
___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 43 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27_UIX6V_s55UxxGQH:-O27_UIX6V_s55UxxGQI:bcgjvre) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/op_arg_ref.h#L43)):*
> ```objc
> 
> template <typename T>
> OpArgRef<DeviceSpecific<DeviceStates>> per_device_op_state() {
> ```

Why this change?
___
*[`lib/local-execution/include/local-execution/runtime_arg_config.h` line 12 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27_c9O4Pg72anEQ7p9:-O27_c9O4Pg72anEQ7pA:b-8a0yua) ([raw file](https://github.com/flexflow/FlexFlow/blob/d30c8f0b74b83f3ecaec594d9e3efd19b26c212a/lib/local-execution/include/local-execution/runtime_arg_config.h#L12)):*
> ```objc
> struct RuntimeArgConfig {
> public:
>   DeviceSpecific<PerDeviceFFHandle> ff_handle;
> ```

Why remove?
___
*[`lib/local-execution/src/local_task_argument_accessor.cc` line 55 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27e4U6Ar7i4fYBVFx-:-O27e4U77PeuK0DtL_WQ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/src/local_task_argument_accessor.cc#L55)):*
> ```cpp
>   }
> 
>   auto check_tensors = [](auto acc1_variant, auto acc2_variant) {
> ```





_Suggestion:_
```cpp
  auto tensors_are_equivalent = [](auto acc1_variant, auto acc2_variant) {
```
___
*[`lib/local-execution/src/local_task_argument_accessor.cc` line 55 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27e6Dy3uf0YVC-CCoa:-O27e6Dy3uf0YVC-CCob:b-x0ty8g) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/src/local_task_argument_accessor.cc#L55)):*
> ```cpp
>   }
> 
>   auto check_tensors = [](auto acc1_variant, auto acc2_variant) {
> ```

Can the arguments have actual types rather than `auto`?
___
*[`lib/local-execution/src/local_task_argument_accessor.cc` line 63 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27eBtc6nTAEfLLB8hc:-O27eBtc6nTAEfLLB8hd:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/src/local_task_argument_accessor.cc#L63)):*
> ```cpp
>   };
> 
>   auto check_variadic_tensors = [](auto acc1_variant, auto acc2_variant) {
> ```





_Suggestion:_
```cpp
  auto variadic_tensor_are_equivalent = [](auto acc1_variant, auto acc2_variant) {
```
___
*[`lib/local-execution/src/local_task_argument_accessor.cc` line 63 at r6](https://reviewable.i [...]

2024-07-20 12:14 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 32 unresolved discussions (waiting on @lockshaw)

___
*[`.proj.toml` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27apIp983TTKhXXbE1:-O2BKx-uEpl8_-L_GZgF:b-in3two) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/.proj.toml#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is there a reason we can't enable this? Didn't we add an additional test suite for tests that require GPUs? As long as they don't also match the generated regex I don't see a reason why we wouldn't be able to enable the non-GPU-requiring local-execution tests (same for `kernel-tests` in the long-term, though I'm guessing the GPU tests in `kernels` haven't been moved over to use the new test suite)
</blockquote></details>

For some reason, the test suite differentiation still isn't preventing the gpu test from being executed (and hence failing) when I run `proj test`. I'm not sure why, but if you have any ideas then we can fix and enable this.
___
*[`lib/kernels/include/kernels/profiling.h` line 9 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27RfMf9fYDHc1CkPdo:-O2B_ZX76qhFd46yP1Oe:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/kernels/include/kernels/profiling.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Replace with `dtgen`
</blockquote></details>

Done.
___
*[`lib/kernels/src/array_shape.cc` line 79 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PGt_91z7Dlw1N053V:-O2BLeYFBjZgpEJdxGGn:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/kernels/src/array_shape.cc#L79)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The better solution here is just to add a `template <typename T> FFOrdered<T> ff_ordered_from_legion_ordered(LegionOrdered<T> const &);` (probably in `kernels/legion_dim.h`) and use it here. If you'd like to use the reverse iterator in that function that's fine, but we should have a primitive for this as this is not an uncommon operation
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/device_specific.h` line 40 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8_Ty4TGQHjvdZiRU:-O2BMJv7E7f8976u6pMv:b-juqdj0) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/device_specific.h#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

None of the operator code should be using this as it's private I think?
</blockquote></details>

Moved it to `DeviceSpecific<T> create`
___
*[`lib/local-execution/include/local-execution/local_cost_estimator.h` line 20 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27YqJg3nH1aB7ztFVE:-O2BMR4O-RV5aG92Cewo:bt6jkoh) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/local_cost_estimator.h#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why did this become `optional`?
</blockquote></details>

I wasn't using the `MachineView` previously. What information does the `MachineView` have that influences how we spin up local backing / ops?
___
*[`lib/local-execution/include/local-execution/local_cpu_allocator.h` line 9 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P9egEC1s0o7SCXqdd:-O2BN9lIELkgGbKyGhqS:b-8b11j9) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/local_cpu_allocator.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Good point, in that case can you explicitly delete the `operator=`s too?
</blockquote></details>

Added
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 44 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27VyBiBfs51burz8dH:-O2BPLGj8LTgAlzEXV7X:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L44)):*
> ```objc
> };
> 
> bool are_slots_backings_equivalent_up_to_allocation_addresses(
> ```

Done.
___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 12 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PD6buA9T3ynuc2pBJ:-O2BaOr6053RzUHOQgPf:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/op_arg_ref.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use `dtgen` for this type?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 14 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PCx7V8n2LhodHsbHf:-O2BaSqaAYXpW7mq69aT:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/op_arg_ref.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move implementations to `.cc`
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 26 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PCybxATPbqOG07HwP:-O2BadNe51wVJKCjvcvF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/op_arg_ref.h#L26)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move implementations to `.cc`
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 27 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PD-8455skjQZlMQjm:-O2BadcZ7rhZ_H2h2Olm:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/op_arg_ref.h#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use `dtgen` for this type?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 35 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PD998A9piQRVhpha_:-O2BbCrk1TxabP9uA2sP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/op_arg_ref.h#L35)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use `dtgen` for this variant type?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 43 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27_UIX6V_s55UxxGQH:-O2F2p1V5cJ8PGbOCb3R:b-gfpin5) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/op_arg_ref.h#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

Working on fixing device specific arg unwrapping, hoping to revert this
___
*[`lib/local-execution/include/local-execution/runtime_arg_config.h` line 12 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27_c9O4Pg72anEQ7p9:-O2F2rzBB_Kh7oiadUmX:b-gfpin5) ([raw file](https://github.com/flexflow/FlexFlow/blob/d30c8f0b74b83f3ecaec594d9e3efd19b26c212a/lib/local-execution/include/local-execution/runtime_arg_config.h#L12)) [...]

2024-07-27 05:18 UTC, lockshaw commented
*[`lib/local-execution/include/local-execution/local_cost_estimator.h` line 20 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27YqJg3nH1aB7ztFVE:-O2mbcypCxODa30dxxQl:b-m9ggcy) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/local_cost_estimator.h#L20)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I wasn't using the `MachineView` previously. What information does the `MachineView` have that influences how we spin up local backing / ops?
</blockquote></details>

I believe `estimate_cost` needs to include network cost of the parameter all-reduce (in the case of data parallelism, for example), which would need `MachineView` information I think? It's a bit of a question of how to define the interface rather than a question of implementation. @wmdi do you have any thoughts on this, as you're currently the primary consumer of this API?


<!-- Sent from Reviewable.io -->

2024-07-27 05:22 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: 95 of 152 files reviewed, 32 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/local_cost_estimator.h` line 20 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27YqJg3nH1aB7ztFVE:-O2mcq3b0fJVIWOVIq8H:bvjhv3u) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/local_cost_estimator.h#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I believe `estimate_cost` needs to include network cost of the parameter all-reduce (in the case of data parallelism, for example), which would need `MachineView` information I think? It's a bit of a question of how to define the interface rather than a question of implementation. @wmdi do you have any thoughts on this, as you're currently the primary consumer of this API?
</blockquote></details>

Yeah I think it is mostly required for parallel operators as Colin mentioned.


<!-- Sent from Reviewable.io -->

2024-07-27 05:47 UTC, lockshaw requested changes
> Reviewed 57 of 57 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 26 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`.proj.toml` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27apIp983TTKhXXbE1:-O2mbHTcCUBzuL40v16I:b-io8aur) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/.proj.toml#L25)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

For some reason, the test suite differentiation still isn't preventing the gpu test from being executed (and hence failing) when I run `proj test`. I'm not sure why, but if you have any ideas then we can fix and enable this.
</blockquote></details>

Interesting, I'll see if I can reproduce the issue locally
___
*[`lib/local-execution/include/local-execution/local_cost_estimator.h` line 20 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27YqJg3nH1aB7ztFVE:-O2mhH-V0lacl8aUUObK:bian26w) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/local_cost_estimator.h#L20)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Yeah I think it is mostly required for parallel operators as Colin mentioned.
</blockquote></details>

Oh yeah I guess weights are managed with explicit weight nodes now, so this wouldn't be necessary for non-parallel ops now since that's just done by having a `Weight->Replicate->TheOperator`, and so the cost is tracked in the backward pass of `Replicate` right? If that's really the case then I suppose the API could even be separated into one different subsets of `PCGOperatorAttrs` (i.e., some new variant types could be added in `op-attrs` for parallel ops and non-parallel ops)

I guess I'm fine either always passing in `MachineView` or defining one overload that always takes it and one overload that doesn't, but having an `optional` that's either (1) ignored or (2) only used based on some non-type-level property of `op` feels not great 
___
*[`lib/local-execution/include/local-execution/op_arg_ref_type.variant.toml` line 22 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2m_ByI8cQyHrVZPVr-:-O2m_BzF2YIq30tMSVVE:b-549yr6) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/op_arg_ref_type.variant.toml#L22)):*
> ```TOML
> [[values]]
> type = "::FlexFlow::ParallelTensorShapeRefType"
> key = "parallel_tensor_shape_ref_type"
> ```

Not sure why there's no trailing newline, can you make sure you've enabled editorconfig integration in vscode? (not a huge deal, but this should keep it consistent going forward)
___
*[`lib/local-execution/include/local-execution/op_task_signature.h` line 46 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2mb1PD7PtYiE2rPhMc:-O2mb1PEDAfouRzV7y9h:b6rinld) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/op_task_signature.h#L46)):*
> ```objc
>   OpTaskSignature() = delete;
>   explicit OpTaskSignature(OpTaskType);
>   OpTaskSignature(OpTaskSignature const &other);
> ```

Why do we need an explicit copy constructor now?
___
*[`lib/local-execution/include/local-execution/slot_id.h` line 8 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PDGV8AKifjMLMytLR:-O2mcd8y8KJ_9kAp_piJ:bbkbjv0) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/slot_id.h#L8)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not seeing this change?
___
*[`lib/local-execution/include/local-execution/task_argument_accessor.h` line 16 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2m_TeJBgHDNj8s2EHo:-O2m_TeJBgHDNj8s2EHp:b-fueqr2) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_argument_accessor.h#L16)):*
> ```objc
> 
>   template <typename T>
>   T const &get_argument_from_device_specific(slot_id slot) const {
> ```

Do we want a separate accessor or would it make more sense to have this be inferred by `TaskArgumentAccessor` by doing something to examine the arg?
___
*[`lib/local-execution/include/local-execution/task_impl_function.variant.toml` line 12 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2m_jsEEbWOCKXcaAAY:-O2m_jsEEbWOCKXcaAAZ:b-a3ae6m) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_impl_function.variant.toml#L12)):*
> ```TOML
> 
> [[values]]
> type = "std::function<::FlexFlow::DeviceSpecific<::FlexFlow::DeviceStates>(::FlexFlow::TaskArgumentAccessor const &)>"
> ```

If you want you could consider wrapping each of these `std::function`s in a trivial `dtgen` struct to give the type a shorter and more understandable name, but it's not a big deal--I could see arguments either way
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 4 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2ma1Xf6jTE2D0cu3qV:-O2ma1Xf6jTE2D0cu3qW:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_signature_impl.h#L4)):*
> ```objc
> #define _FLEXFLOW_LOCAL_EXECUTION_TASK_SIGNATURE_IMPL_H
> 
> // #include "local-execution/device_specific.h"
> ```

Delete
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 10 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2ma0hgAAZn0r9l3Uwe:-O2ma0hh95Zg_JbNJJ7T:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_signature_impl.h#L10)):*
> ```objc
> #include "local-execution/tasks.h"
> #include "op-attrs/computation_graph_op_attrs.h"
> // #include "task_argument_accessor.h"
> ```

Delete
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 15 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2ma0-w2wVuEX1HYiAX:-O2ma0-w2wVuEX1HYiAY:bs2dogg) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_signature_impl.h#L15)):*
> ```objc
> namespace FlexFlow {
> 
> // using TaskImplFunction = std::variant<
> ```

Delete
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 19 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2ma5l10HpvWCtbN5by:-O2ma5l10HpvWCtbN5bz:b-u0gvq6) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_signature_impl.h#L19)):*
> ```objc
> //     &)>, std::function<std::optional<float>(TaskArgumentAccessor const &)>>;
> 
> struct TaskSignatureAndImpl {
> ```

Move over to dtgen?
___
*[`lib/local-execution/src/local_cpu_allocator.cc` line 5 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PE-_s3tA11QR-r3Dd:-O2mdF018U0Md2Djr104:b-ccebo8) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/src/local_cpu_allocator.cc#L5)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I think it may complicate things, as we sometimes need to manually deallocate memory, which would require finding the correct unique ptr in our set.
</blockquote></details>

But doesn't that already need to be done in `LocalCPUAllocator::deallocate` with the whole `this->ptrs.erase(ptr)`? The poin [...]

2024-07-27 06:43 UTC, lockshaw commented
*[`.proj.toml` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27apIp983TTKhXXbE1:-O2mvNhEA394-apUHiNY:bpibtmm) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/.proj.toml#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Interesting, I'll see if I can reproduce the issue locally
</blockquote></details>

The test filtering seems to work okay on my side (though I did have to make some changes to get tests to build at all). Can you send me exactly what error message you were running into?


<!-- Sent from Reviewable.io -->

2024-08-01 01:06 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: 94 of 161 files reviewed, 26 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`.proj.toml` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27apIp983TTKhXXbE1:-O34b0GC0QMi36Mwzpf0:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/.proj.toml#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The test filtering seems to work okay on my side (though I did have to make some changes to get tests to build at all). Can you send me exactly what error message you were running into?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/device_specific.h` line 16 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1P8xXzDO9GjceejU7P:-O341j717ZOwGrgHzwIN:bt2vr1b) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/device_specific.h#L16)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I see. This is worth some discusion -- I removed the pointer temporarily just to get the build working / test passing (since there's only one device anyway), but this needs to be ironed out for distributed.
</blockquote></details>

Fixed.
___
*[`lib/local-execution/include/local-execution/local_cost_estimator.h` line 20 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27YqJg3nH1aB7ztFVE:-O33vwR3CIZqyWLvp5ID:b-dcvr9n) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/local_cost_estimator.h#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Oh yeah I guess weights are managed with explicit weight nodes now, so this wouldn't be necessary for non-parallel ops now since that's just done by having a `Weight->Replicate->TheOperator`, and so the cost is tracked in the backward pass of `Replicate` right? If that's really the case then I suppose the API could even be separated into one different subsets of `PCGOperatorAttrs` (i.e., some new variant types could be added in `op-attrs` for parallel ops and non-parallel ops)

I guess I'm fine either always passing in `MachineView` or defining one overload that always takes it and one overload that doesn't, but having an `optional` that's either (1) ignored or (2) only used based on some non-type-level property of `op` feels not great
</blockquote></details>

Yeah, makes sense. Fixed to have both.
___
*[`lib/local-execution/include/local-execution/op_arg_ref.h` line 43 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O27_UIX6V_s55UxxGQH:-O38wrfQA-VzAf7hGipV:bp3aow6) ([raw file](https://github.com/flexflow/FlexFlow/blob/47327b0b1b9ced7528d263c412ccdf530224a1ff/lib/local-execution/include/local-execution/op_arg_ref.h#L43)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Working on fixing device specific arg unwrapping, hoping to revert this
</blockquote></details>

Reverted.
___
*[`lib/local-execution/include/local-execution/op_arg_ref_type.variant.toml` line 22 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2m_ByI8cQyHrVZPVr-:-O33glSR0wbZ2Z-YLRn0:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/op_arg_ref_type.variant.toml#L22)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not sure why there's no trailing newline, can you make sure you've enabled editorconfig integration in vscode? (not a huge deal, but this should keep it consistent going forward)
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/op_task_signature.h` line 46 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2mb1PD7PtYiE2rPhMc:-O33w2lq7rxToqhBt0HD:bq4ibet) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/op_task_signature.h#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why do we need an explicit copy constructor now?
</blockquote></details>

Actually we don't, you're right.
___
*[`lib/local-execution/include/local-execution/slot_id.h` line 8 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O1PDGV8AKifjMLMytLR:-O38wknx616G83l0hEbX:b-9oo43o) ([raw file](https://github.com/flexflow/FlexFlow/blob/853ff624736dfe5be32d027dc8909c22062e0579/lib/local-execution/include/local-execution/slot_id.h#L8)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not seeing this change?
</blockquote></details>

Supersded by #1449    
___
*[`lib/local-execution/include/local-execution/task_argument_accessor.h` line 16 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2m_TeJBgHDNj8s2EHo:-O34aiKsEgljfvqFOnbz:b-s72cmj) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_argument_accessor.h#L16)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Do we want a separate accessor or would it make more sense to have this be inferred by `TaskArgumentAccessor` by doing something to examine the arg?
</blockquote></details>

Done. The arg constructor will unwrap device specific
___
*[`lib/local-execution/include/local-execution/task_impl_function.variant.toml` line 12 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2m_jsEEbWOCKXcaAAY:-O33slpe4_ukyQFosgLR:bfn6p5i) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_impl_function.variant.toml#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If you want you could consider wrapping each of these `std::function`s in a trivial `dtgen` struct to give the type a shorter and more understandable name, but it's not a big deal--I could see arguments either way
</blockquote></details>

I think here the `key` is expressive enough for the type anyway?
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 4 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2ma1Xf6jTE2D0cu3qV:-O33hJ-S7QmZ1RjdCD0x:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_signature_impl.h#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 10 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2ma0hgAAZn0r9l3Uwe:-O33hJW0Djy4h3FdW0wc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_signature_impl.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 15 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2ma0-w2wVuEX1HYiAX:-O33hJon0ONGGdO3RHu8:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_signature_impl.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 19 at r7] [...]

2024-08-07 02:56 UTC, lockshaw requested changes
Can you double check and make sure all of the `std::cout`s are removed? I left comments on all I found but it's not impossible that I missed one or two

> Reviewed 48 of 67 files at r8, 1 of 1 files at r10, 34 of 34 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-:-O3eieNW3LfLPmC-tnU1:b-1hz0tb)* status: all files reviewed, 51 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/accessor.h` line 172 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3LuRigCzPzUlfelZbr:-O3LuRipBFji2UbV1Obx:b1amjos) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/kernels/include/kernels/accessor.h#L172)):*
> ```objc
>               "");
> 
> std::string format_as(std::vector<GenericTensorAccessorR> const &x);
> ```

Why do we have this instead of just having `fmt` support for `GenericTensorAccessorR` and using the default `utils/fmt/vector.h` `fmt` support for `std::vector`?
___
*[`lib/kernels/include/kernels/device.h` line 102 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3LutHmC-QAlWZvweBN:-O3LutHmC-QAlWZvweBO:b-ik1b8t) ([raw file](https://github.com/flexflow/FlexFlow/blob/3b575d5222f8a90949bdd73ab97c63d572175e1f/lib/kernels/include/kernels/device.h#L102)):*
> ```objc
>     std::stringstream _error;                                                  \
>     if (status != 0) {                                                         \
>       _error << "CUDA failure: " << cudaGetErrorString(status) << " ("         \
> ```

This should be kept, why was this removed?
___
*[`lib/kernels/src/ff_handle.cc` line 6 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3Lv5gg7xVcV5IPamug:-O3Lv5gg7xVcV5IPamuh:b5bwwxv) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/kernels/src/ff_handle.cc#L6)):*
> ```cpp
> 
> std::string format_as(PerDeviceFFHandle const &x) {
>   return fmt::format("PerDeviceFFHandle");
> ```

Why not include some fields in the fmt description?
___
*[`lib/local-execution/include/local-execution/cost_estimate.h` line 21 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3LvrAD-boR0omhbRRk:-O3LvrAD-boR0omhbRRl:boyak19) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/cost_estimate.h#L21)):*
> ```objc
>                     std::vector<ParallelTensorAttrs> const &outputs,
>                     MachineView const &mv) const = 0;
>   virtual CostDetails
> ```

Remove this second overload and just ignore `MachineView` where it's not necessary. Overall `CostEstimator` should include network modelling, etc. rather than just being a thin interface onto kernel runtimes
___
*[`lib/local-execution/include/local-execution/device_specific_device_states.variant.toml` line 2 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3LwXEw-jSN5iBi7ceW:-O3LwXEw-jSN5iBi7ceX:b-7jenqw) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/device_specific_device_states.variant.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "DeviceSpecificDeviceStates"
> ```

What is the purpose of this variant? What's the reasoning for having a `variant<DeviceSpecific<T>, ...>` vs a `DeviceSpecific<variant<T, ...>>`?
___
*[`lib/local-execution/include/local-execution/device_states.variant.toml` line 2 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3Lwmrk1__9FnkdgjD3:-O3Lwmrk1__9FnkdgjD4:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/device_states.variant.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "DeviceStates"
> ```





_Suggestion:_
```TOML
name = "PerDeviceState"
```
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 47 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3eh1fC9BHYQpU5Cn_L:-O3eh1fC9BHYQpU5Cn_M:b4qdfio) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L47)):*
> ```objc
> CHECK_RC_COPY_VIRTUAL_COMPLIANT(LocalTaskArgumentAccessor);
> 
> std::string format_as(std::unordered_map<slot_id_t, ConcreteArgSpec> const &x);
> ```

`utils/fmt/unordered_map.h`
___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 17 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3ePkVr18BUd2WS7aR9:-O3ePkVr18BUd2WS7aRA:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/local_training_backing.h#L17)):*
> ```objc
>                        TensorBackingMap const &,
>                        RuntimeArgConfig const &);
>   ~LocalTrainingBacking() = default;
> ```


___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 38 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3ePo8u2u4z6d4RZmy-:-O3ePo8u2u4z6d4RZmy0:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/local_training_backing.h#L38)):*
> ```objc
>   ComputationGraph computation_graph;
>   TaskRegistry task_registry;
>   LocalSlotsBacking local_slots_backing;
> ```





_Suggestion:_
```objc
private:  
  Allocator allocator;
  ComputationGraph computation_graph;
  TaskRegistry task_registry;
  LocalSlotsBacking local_slots_backing;
```
___
*[`lib/local-execution/include/local-execution/op_task_invocation.h` line 102 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3QZHGmB4PTXeLwRsoE:-O3QZHGnBx04aoygzf_E:b-qbe6nt) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/op_task_invocation.h#L102)):*
> ```objc
>   std::unordered_map<slot_id_t, OpArgSpec> arg_bindings;
>   std::tuple<decltype(tensor_bindings) const &, decltype(arg_bindings) const &>
>       tie() const;
> ```

Having a separate section for member variables can improve readability



_Suggestion:_
```objc
private:
  std::unordered_map<SlotGradId, OpTensorSpec> tensor_bindings;
  std::unordered_map<slot_id_t, OpArgSpec> arg_bindings;

private:
  void insert_arg_spec(slot_id_t name, OpArgSpec const &arg_spec);
  std::tuple<decltype(tensor_bindings) const &, decltype(arg_bindings) const &>
      tie() const;
```
___
*[`lib/local-execution/include/local-execution/task_argument_accessor.h` line 13 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3QZcze7wWtAqH34yZm:-O3QZcze7wWtAqH34yZn:b-blr7bp) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/task_argument_accessor.h#L13)):*
> ```objc
>   template <typename T>
>   T const &get_argument(slot_id_t slot) const {
>     if constexpr (DeviceStates::IsPartOfDeviceStates_v<T>) {
> ```

Is doing this based on type the best way of doing this, or should this be done based on whether a value was passed as device-specific in the invocation?
___
*[`lib/local-execution/include/local-execution/task_impl_function.variant.toml` line 12 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2m_jsEEbWOCKXcaAAY:-O3QZv_B9bj09_pSa72E:b56oshi) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_impl_function.variant.toml#L12)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I think here the `key` is expressive enough for the type anyway?
</blockquote></details>

`key` isn't really used for much except for json serialization iirc
___
* [...]

2024-08-07 02:57 UTC, lockshaw reviewed
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 51 unresolved discussions (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2024-08-09 00:27 UTC, reyna-abhyankar reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-:-O3iCrnY1KT9zlO8ssN5:b-896fix)* status: 104 of 177 files reviewed, 51 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/accessor.h` line 172 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3LuRigCzPzUlfelZbr:-O3nuIa50uvZLhVdVq7k:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/kernels/include/kernels/accessor.h#L172)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why do we have this instead of just having `fmt` support for `GenericTensorAccessorR` and using the default `utils/fmt/vector.h` `fmt` support for `std::vector`?
</blockquote></details>

Done.
___
*[`lib/kernels/include/kernels/device.h` line 102 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3LutHmC-QAlWZvweBN:-O3hNwmD9PPczAJxtPf7:b-p0wkw7) ([raw file](https://github.com/flexflow/FlexFlow/blob/3b575d5222f8a90949bdd73ab97c63d572175e1f/lib/kernels/include/kernels/device.h#L102)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This should be kept, why was this removed?
</blockquote></details>

Temporarily removed it because I was getting a linker error when running `proj test` for `local-execution-tests`: `undefined reference to 'cudaGetErrorString'`
___
*[`lib/kernels/src/ff_handle.cc` line 6 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3Lv5gg7xVcV5IPamug:-O3nnWN37vrFOs68JcEC:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/kernels/src/ff_handle.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not include some fields in the fmt description?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/device_specific_device_states.variant.toml` line 2 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3LwXEw-jSN5iBi7ceW:-O3h_AnDACLFfpBQkygr:b-vdcncy) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/device_specific_device_states.variant.toml#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is the purpose of this variant? What's the reasoning for having a `variant<DeviceSpecific<T>, ...>` vs a `DeviceSpecific<variant<T, ...>>`?
</blockquote></details>

We want the device specific to hold the actual device state type, and then the init functions for all operators can return one of these device specifics. 
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 47 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3eh1fC9BHYQpU5Cn_L:-O3nsGPp9QDfhHN72qlv:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L47)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`utils/fmt/unordered_map.h`
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 17 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3ePkVr18BUd2WS7aR9:-O3hgxX45yxB0VxOt49f:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/local_training_backing.h#L17)):*
> ```objc
>                        TensorBackingMap const &,
>                        RuntimeArgConfig const &);
>   ~LocalTrainingBacking() = default;
> ```

Done.
___
*[`lib/local-execution/include/local-execution/local_training_backing.h` line 38 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3ePo8u2u4z6d4RZmy-:-O3hh6MQDPYZyVSATv9M:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/local_training_backing.h#L38)):*
> ```objc
>   ComputationGraph computation_graph;
>   TaskRegistry task_registry;
>   LocalSlotsBacking local_slots_backing;
> ```

Done.
___
*[`lib/local-execution/include/local-execution/op_task_invocation.h` line 102 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3QZHGmB4PTXeLwRsoE:-O3hhLHX6TfQgP6lVRTq:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/op_task_invocation.h#L102)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Having a separate section for member variables can improve readability
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_argument_accessor.h` line 13 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3QZcze7wWtAqH34yZm:-O3oWZgv87AEUdXWWhyh:b-8a1x3z) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/task_argument_accessor.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is doing this based on type the best way of doing this, or should this be done based on whether a value was passed as device-specific in the invocation?
</blockquote></details>

I'm going to make an issue for this because it's related to actually adding support for device specific bindings. #1462
___
*[`lib/local-execution/include/local-execution/task_registry.h` line 12 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3eP5Mb3fhxTX69QbAq:-O3oI82L41DpuTCxukCr:b-efpcjx) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/task_registry.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move `TaskRegistry` over to `dtgen`?
</blockquote></details>

We modify it on the fly while constructing the local backing, so I think we should keep as is.
___
*[`lib/local-execution/include/local-execution/task_registry.h` line 26 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3Q_JAuCPch-TtPdUT0:-O3hi8DDEUuYDNsRqfvg:btjezii) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/task_registry.h#L26)):*
> ```objc
>   bool operator!=(TaskRegistry const &other) const;
> 
> private:
> ```

Why private these? 
___
*[`lib/local-execution/include/local-execution/task_registry.h` line 35 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3Q_2hi4CP_P9b3e-GB:-O3nsemF1hUc3dGwYHGx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/task_registry.h#L35)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not use the default `utils/fmt/unordered_map.h` and `utils/fmt/optional.h`?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/task_signature_impl.h` line 19 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O2ma5l10HpvWCtbN5by:-O3o9V6b3XtFxkpE8_Cy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/72bf72ae286f1763011bb0aedce4144d36328a3c/lib/local-execution/include/local-execution/task_signature_impl.h#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In that case it would be better to have a separate function rather than an `operator==`--I'd recommend only having `operator==` if the type does actually support equality
</blockquote></details>

Done.
___
*[`lib/local-execution/src/concrete_arg.cc` line 19 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3ePzh03KTaIexM [...]

2024-08-10 02:21 UTC, lockshaw requested changes
> Reviewed 76 of 76 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 27 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/array_shape.h` line 58 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3tvrOV4z_EPRkmUJ1E:-O3tvrOV4z_EPRkmUJ1F:b-tiaeuq) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/kernels/include/kernels/array_shape.h#L58)):*
> ```objc
> TensorShape get_tensor_shape(ArrayShape const &, DataType);
> 
> std::string format_as(std::pair<ArrayShape, DataType> const &);
> ```

`utils/fmt/pair.h`?
___
*[`lib/kernels/include/kernels/device.h` line 102 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3LutHmC-QAlWZvweBN:-O3u4F6b4GQ10ZHQ-I1g:b8vbjo4) ([raw file](https://github.com/flexflow/FlexFlow/blob/3b575d5222f8a90949bdd73ab97c63d572175e1f/lib/kernels/include/kernels/device.h#L102)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Temporarily removed it because I was getting a linker error when running `proj test` for `local-execution-tests`: `undefined reference to 'cudaGetErrorString'`
</blockquote></details>

It should get added back in, the key is just only to call it from non-template code in `kernels` so the linker does the right thing. But we really do want the string version of those error messages. Of course if you wanted you could also pull parts of it out of macros and into constant functions to reduce the restrictions--for example if you just wrapped `cudaGetErrorString` in kernels this wouldn't be an issue
___
*[`lib/kernels/src/ff_handle.cc` line 9 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3twsS29LiG6_5HtLrF:-O3twsS29LiG6_5HtLrG:b-hz62w4) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/kernels/src/ff_handle.cc#L9)):*
> ```cpp
>   oss << "<PerDeviceFFHandle";
>   oss << " workSpaceSize=" << x.workSpaceSize;
>   oss << " allowTensorOpMathConversion=" << x.allowTensorOpMathConversion;
> ```

You're missing a closing `>`. You can also always use `fmt` syntax if you prefer, i.e., `return fmt::format("<PerDeviceFFHandle worksSpaceSize={} allowTensorOpMathConversion={}>", x.workSpaceSize, x.allowTensorOpMathConversion); 
___
*[`lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h` line 1 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txXacCg0_KkDkX0AH:-O3txXacCg0_KkDkX0AI:b-pd44pk) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h#L1)):*
> ```objc
> #include "local-execution/task_argument_accessor.h"
> ```

Header guard?
___
*[`lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h` line 7 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txh0v2zeI_zEW5Hta:-O3txh0v2zeI_zEW5Htb:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h#L7)):*
> ```objc
> struct FwdBwdTaskImplFunction {
> 
> std::optional<float> (*fwd_bwd_task_impl_function)(TaskArgumentAccessor const &);
> ```





_Suggestion:_
```objc
std::optional<float> (*function_ptr)(TaskArgumentAccessor const &);
```
___
*[`lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h` line 11 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txKxiEga5ouuIbrgb:-O3txKxiEga5ouuIbrgc:biel4mr) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h#L11)):*
> ```objc
> bool operator==(FwdBwdTaskImplFunction const &) const;
> bool operator!=(FwdBwdTaskImplFunction const &) const;
> ```

Ideally also add `operator<`
___
*[`lib/local-execution/include/local-execution/init_task_impl_function.h` line 1 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txTnR3CsUHo_qmIqS:-O3txTnR3CsUHo_qmIqT:b-pd44pk) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/init_task_impl_function.h#L1)):*
> ```objc
> #include "local-execution/device_specific_device_states.dtg.h"
> ```

Header guard?
___
*[`lib/local-execution/include/local-execution/init_task_impl_function.h` line 8 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txj5oBvVFtJ62wen0:-O3txj5oBvVFtJ62wen1:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/init_task_impl_function.h#L8)):*
> ```objc
> struct InitTaskImplFunction {
> 
> DeviceSpecificDeviceStates (*init_task_impl_function)(TaskArgumentAccessor const &);
> ```





_Suggestion:_
```objc
DeviceSpecificDeviceStates (*function_ptr)(TaskArgumentAccessor const &);
```
___
*[`lib/local-execution/include/local-execution/init_task_impl_function.h` line 12 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txPgP3FzDsQ3Pm7no:-O3txPgP3FzDsQ3Pm7np:biel4mr) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/init_task_impl_function.h#L12)):*
> ```objc
> bool operator==(InitTaskImplFunction const &) const;
> bool operator!=(InitTaskImplFunction const &) const;
> ```

Ideally also add `operator<`
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 42 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txoJM7o1hkaNd6ELQ:-O3txoJM7o1hkaNd6ELR:b-v35xpy) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L42)):*
> ```objc
> };
> 
> using TensorSlotsBackingWithoutAddresses = std::unordered_map<
> ```

`dtgen` wrapper would be preferable
___
*[`lib/local-execution/include/local-execution/op_task_signature.h` line 95 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3ty36W5ZJ9Ui09nCA6:-O3ty36W5ZJ9Ui09nCA7:b-9rnmrl) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/op_task_signature.h#L95)):*
> ```objc
>   std::unordered_set<OpTensorSlotSpec> op_tensor_slots;
> };
> FF_VISITABLE_STRUCT_NONSTANDARD_CONSTRUCTION(
> ```

Eventually this should be migrated on from `visitable`, but doesn't have to happen now
___
*[`lib/local-execution/include/local-execution/per_device_state.h` line 1 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3tyDfm6UfYTMWvGn91:-O3tyDfm6UfYTMWvGn92:b-pd44pk) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/per_device_state.h#L1)):*
> ```objc
> #include "local-execution/device_specific_device_states.dtg.h"
> ```

Header guard?
___
*[`lib/local-execution/include/local-execution/per_device_state.variant.toml` line 2 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3u3VxbC3LxAD4FxAyy:-O3u3VxbC3LxAD4FxAyz:b-ukbad4) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/per_device_state.variant.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "PerDeviceState"
> ```

These are all for operators, so `PerDeviceOpState` seems clearer--`PerDeviceState` makes it seem there is one per device and it has nothing to do with operators



_Code quote:_
```TOML
"PerDeviceState"
```
___
*[`lib/local-execution/include/local-execution/task_impl_function.variant.toml` line 4 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3tyb9oCkn1_SWRKTwK:-O3tyb9oCkn1_SWRKTwL:b-g78 [...]

2024-08-21 18:04 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: 155 of 186 files reviewed, 27 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/kernels/include/kernels/array_shape.h` line 58 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3tvrOV4z_EPRkmUJ1E:-O4piGeHEkNGztGiMpgH:b-bifixh) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/kernels/include/kernels/array_shape.h#L58)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`utils/fmt/pair.h`?
</blockquote></details>

Added a format fn for `ArrayShape` (then pair takes care of the rest)
___
*[`lib/kernels/include/kernels/device.h` line 102 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3LutHmC-QAlWZvweBN:-O4poK-XD2c0WGH5T3jC:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3b575d5222f8a90949bdd73ab97c63d572175e1f/lib/kernels/include/kernels/device.h#L102)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It should get added back in, the key is just only to call it from non-template code in `kernels` so the linker does the right thing. But we really do want the string version of those error messages. Of course if you wanted you could also pull parts of it out of macros and into constant functions to reduce the restrictions--for example if you just wrapped `cudaGetErrorString` in kernels this wouldn't be an issue
</blockquote></details>

Done.
___
*[`lib/kernels/src/ff_handle.cc` line 9 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3twsS29LiG6_5HtLrF:-O43XeiXEVRucYNnbVm6:bx5b3aq) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/kernels/src/ff_handle.cc#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You're missing a closing `>`. You can also always use `fmt` syntax if you prefer, i.e., `return fmt::format("<PerDeviceFFHandle worksSpaceSize={} allowTensorOpMathConversion={}>", x.workSpaceSize, x.allowTensorOpMathConversion);
</blockquote></details>

Just added the `>.
___
*[`lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h` line 1 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txXacCg0_KkDkX0AH:-O43XyaYCie-l0fj9Ern:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Header guard?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h` line 7 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txh0v2zeI_zEW5Hta:-O43YKJpCmA_vVZp7Uy5:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h#L7)):*
> ```objc
> struct FwdBwdTaskImplFunction {
> 
> std::optional<float> (*fwd_bwd_task_impl_function)(TaskArgumentAccessor const &);
> ```

Done.
___
*[`lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h` line 11 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txKxiEga5ouuIbrgb:-O43YMd67q11ig7bHZZc:b-mwvxds) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Ideally also add `operator<`
</blockquote></details>

Why do we need ordering? Even though we technically can order the function ptrs, there isn't a real order to the functions themselves (which is what we are actually comparing)
___
*[`lib/local-execution/include/local-execution/init_task_impl_function.h` line 1 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txTnR3CsUHo_qmIqS:-O43YzSI7HyiDIK25QWM:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/init_task_impl_function.h#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Header guard?
</blockquote></details>

Done.
___
*[`lib/local-execution/include/local-execution/init_task_impl_function.h` line 8 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txj5oBvVFtJ62wen0:-O43YzgQ1MmmZRBdoiHp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/init_task_impl_function.h#L8)):*
> ```objc
> struct InitTaskImplFunction {
> 
> DeviceSpecificDeviceStates (*init_task_impl_function)(TaskArgumentAccessor const &);
> ```

Done.
___
*[`lib/local-execution/include/local-execution/init_task_impl_function.h` line 12 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txPgP3FzDsQ3Pm7no:-O43Z0n4DBYFL_JqbSBo:b-x0xmxz) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/init_task_impl_function.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Ideally also add `operator<`
</blockquote></details>

See https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txKxiEga5ouuIbrgb
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 42 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txoJM7o1hkaNd6ELQ:-O4poqqFCxG7R57Al0AY:b-wn1lt5) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L42)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`dtgen` wrapper would be preferable
</blockquote></details>

It's only used in this one spot, I feel like dtgen for it is kind of overkill.
___
*[`lib/local-execution/include/local-execution/op_task_signature.h` line 95 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3ty36W5ZJ9Ui09nCA6:-O43_PkoDXAfemgkk-qG:b-gtktdf) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/op_task_signature.h#L95)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Eventually this should be migrated on from `visitable`, but doesn't have to happen now
</blockquote></details>

Created an issue for this: #1465  
___
*[`lib/local-execution/include/local-execution/task_impl_function.variant.toml` line 4 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3tyb9oCkn1_SWRKTwK:-O43djXK6rdPBLvisIux:biiw6qz) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/task_impl_function.variant.toml#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Would be good to have `hash`. `ord` too if it's possible (currently there's no `ord` for `unordered_set` and `unordered_map`, so it's not always possible)
</blockquote></details>

Added `hash`, for similar discussion of `ord` see https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txKxiEga5ouuIbrgb 
___
*[`lib/local-execution/include/local-execution/task_impl_function.variant.toml` line 13 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3tyu-LD4tTdxDsquxL:-O43eADe9KOOhN3Odu3J:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/task_impl_function.variant.toml#L13)):*
> ```TOML
>   "local-execution/init_task_impl_function.h",
>   "local-execution/fwd_bwd_task_impl [...]

2024-08-21 23:05 UTC, lockshaw requested changes
> Reviewed 30 of 30 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 13 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h` line 11 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txKxiEga5ouuIbrgb:-O4r6B3A-YYU0w8Ie-hJ:bmv7jd9) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/fwd_bwd_task_impl_function.h#L11)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why do we need ordering? Even though we technically can order the function ptrs, there isn't a real order to the functions themselves (which is what we are actually comparing)
</blockquote></details>

Usually to allow the thing to also be stored in a `std::map` or a `std::set` which require `operator<`
___
*[`lib/local-execution/include/local-execution/local_task_argument_accessor.h` line 42 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txoJM7o1hkaNd6ELQ:-O4r9mqa0JF0aUGlW3NY:b1r2c5p) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/local_task_argument_accessor.h#L42)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

It's only used in this one spot, I feel like dtgen for it is kind of overkill.
</blockquote></details>

The reason would be more to wrap the type so the additional `utils/fmt/variant.h`, `utils/fmt/vector.h`, etc. includes aren't necessary, and just to avoid the potential confusion/weirdness of a type alias. I'd lean toward `dtgen` here as the overhead is pretty small and it avoids these issues, but I don't think it's worth holding up the PR over
___
*[`lib/local-execution/include/local-execution/task_registry.h` line 12 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3eP5Mb3fhxTX69QbAq:-O4r6gqx2jioClYBICA9:b-vtjrqb) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/task_registry.h#L12)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Don't the `xxx_task_ids` maps have to be const? `register_tasks_for_layer` has to insert into them
</blockquote></details>

You'd take it as `TaskRegistry &` rather than `TaskRegistry const &` and then you'd be allowed to modify the `std::unordered_map`s
___
*[`lib/local-execution/src/fwd_bwd_task_impl_function.cc` line 18 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4r72igEzyz6-5OdpSc:-O4r72igEzyz6-5OdpSd:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/02cc5bf9049841fb2a617e36b7dc8cc2497d96ab/lib/local-execution/src/fwd_bwd_task_impl_function.cc#L18)):*
> ```cpp
>   std::ostringstream oss;
>   oss << "<FwdBwdTaskImplFunction";
>   oss << " function_ptr=" << (void *)x.function_ptr;
> ```





_Suggestion:_
```cpp
static_cast<void *>(x.function_ptr);
```
___
*[`lib/local-execution/src/init_task_impl_function.cc` line 16 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4r7E8qA22Cmrs8gZAr:-O4r7E8qA22Cmrs8gZAs:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/02cc5bf9049841fb2a617e36b7dc8cc2497d96ab/lib/local-execution/src/init_task_impl_function.cc#L16)):*
> ```cpp
>   std::ostringstream oss;
>   oss << "<InitTaskImplFunction";
>   oss << " function_ptr=" << (void *)x.function_ptr;
> ```





_Suggestion:_
```cpp
  oss << " function_ptr=" << static_cast<void *>(x.function_ptr);
```
___
*[`lib/local-execution/src/ops/input.cc` line 2 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4r7zBDDtraoE2NOREe:-O4r7zBDDtraoE2NOREf:b-u9fg8z) ([raw file](https://github.com/flexflow/FlexFlow/blob/02cc5bf9049841fb2a617e36b7dc8cc2497d96ab/lib/local-execution/src/ops/input.cc#L2)):*
> ```cpp
> #include "input.h"
> #include "local-execution/op_task_invocation.h"
> ```

Why is `op_task_invocation.h` needed?
___
*[`lib/local-execution/src/ops/input.cc` line 3 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4r7uukEnTm9jwGcsRh:-O4r7uukEnTm9jwGcsRi:bphqszb) ([raw file](https://github.com/flexflow/FlexFlow/blob/02cc5bf9049841fb2a617e36b7dc8cc2497d96ab/lib/local-execution/src/ops/input.cc#L3)):*
> ```cpp
> #include "input.h"
> #include "local-execution/op_task_invocation.h"
> #include "utils/hash-utils.h"
> ```

Why is `hash-utils.h` needed?
___
*[`lib/local-execution/src/ops/noop.cc` line 17 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4r84EaCUzdAg146-u3:-O4r84EaCUzdAg146-u4:bvmetur) ([raw file](https://github.com/flexflow/FlexFlow/blob/02cc5bf9049841fb2a617e36b7dc8cc2497d96ab/lib/local-execution/src/ops/noop.cc#L17)):*
> ```cpp
> 
> #include "noop.h"
> #include "utils/hash-utils.h"
> ```

Why is `hash-utils.h` necessary?
___
*[`lib/local-execution/src/ops/weight.cc` line 2 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4r8Aav1IgDluz_eKnp:-O4r8Aav1IgDluz_eKnq:bq9xvdp) ([raw file](https://github.com/flexflow/FlexFlow/blob/02cc5bf9049841fb2a617e36b7dc8cc2497d96ab/lib/local-execution/src/ops/weight.cc#L2)):*
> ```cpp
> #include "weight.h"
> #include "local-execution/op_task_invocation.h"
> ```

Why is `op_task_invocation.h` necessary?
___
*[`lib/local-execution/src/ops/weight.cc` line 3 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4r896G2-_1SG9AnhhJ:-O4r896G2-_1SG9AnhhK:bvmetur) ([raw file](https://github.com/flexflow/FlexFlow/blob/02cc5bf9049841fb2a617e36b7dc8cc2497d96ab/lib/local-execution/src/ops/weight.cc#L3)):*
> ```cpp
> #include "weight.h"
> #include "local-execution/op_task_invocation.h"
> #include "utils/hash-utils.h"
> ```

Why is `hash-utils.h` necessary?
___
*[`lib/local-execution/test/src/test_local_slots_backing.cc` line 77 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3eCi8X6cGHzWkpZx_D:-O4r8rBR2TIF5LWRNypP:b84ogyh) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/test/src/test_local_slots_backing.cc#L77)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Ah, actually here we are only checking for a single operator. It's just all incoming tensors for that node have to have been allocated first since we are checking both incoming and outgoing tensors exist for this operator.
</blockquote></details>

Sorry, I meant "bunch of tensors" instead of "bunch of operators"--this just seems to be checking much more than what `allocate_tensors` does? I'm not sure why we need to check that all incoming and outgoing tensors exist to confirm that `allocate_tensors` works?


<!-- Sent from Reviewable.io -->

2024-08-22 02:39 UTC, lockshaw requested changes
> Reviewed 6 of 6 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 3 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/task_impl_function.variant.toml` line 4 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3tyb9oCkn1_SWRKTwK:-O4rwomU8WujU6stB2vj:b-u0luy5) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/task_impl_function.variant.toml#L4)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Added `hash`, for similar discussion of `ord` see https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3txKxiEga5ouuIbrgb
</blockquote></details>

Can we also add `ord` here since `FwdBwdTaskImplFunction` now supports `ord`?
___
*[`lib/local-execution/include/local-execution/task_registry.h` line 12 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3eP5Mb3fhxTX69QbAq:-O4rwP-p9DFIuVf2RqPU:bcuf6u2) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/task_registry.h#L12)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

but when constructing `TaskRegistry` with dtgen, it requires const maps. Maybe I'm misunderstanding this part.
</blockquote></details>

I don't see why it requires `const` maps? It's totally fine to do `TaskRegistry r = TaskRegistry{{}, {}, {}, {}}; r.init_task_ids.insert({...});`. `dtgen` doesn't make the fields const (of course unless you declare a `TaskRegistry const r`, but then it's `const` because you explicitly told it to be)
___
*[`lib/local-execution/src/fwd_bwd_task_impl_function.cc` line 18 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4r72igEzyz6-5OdpSc:-O4rv4uZ-NJFYcAjMqxO:b-qdltf4) ([raw file](https://github.com/flexflow/FlexFlow/blob/02cc5bf9049841fb2a617e36b7dc8cc2497d96ab/lib/local-execution/src/fwd_bwd_task_impl_function.cc#L18)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done. Actually needed to be `reinterpret_cast`
</blockquote></details>

Yeah, that's because apparently this operation (and printing a function pointer in general), is really not a well-defined operation C++-wise. It's fine here because this is really just for debugging, but in general if something is requiring `reinterpret_cast` remember that's essentially just reinterpreting the bytes in memory and so you lose (at least a lot if not all) portability and correctness guarantees
___
*[`lib/local-execution/src/init_task_impl_function.cc` line 16 at r14](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4r7E8qA22Cmrs8gZAr:-O4rvWRf-qQhQqCpbaoS:bmny8j) ([raw file](https://github.com/flexflow/FlexFlow/blob/02cc5bf9049841fb2a617e36b7dc8cc2497d96ab/lib/local-execution/src/init_task_impl_function.cc#L16)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Done. Actually needed to be `reinterpret_cast`
</blockquote></details>

See https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4r72igEzyz6-5OdpSc
___
*[`lib/local-execution/test/src/test_local_slots_backing.cc` line 77 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3eCi8X6cGHzWkpZx_D:-O4rvxDz164aPALZoEP9:blizald) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/test/src/test_local_slots_backing.cc#L77)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

`allocate_tensors` will allocate all outgoing tensors for a given operator. You're right that we don't have to check all incoming tensors, but seeing as those should be allocated using `allocate_tensors` (or `allocator.allocate_tensor` if it's an input tensor) then I think it's ok? Again, the alternative would be to make `allocate_tensors` more granular OR we only check the output tensors are allocated.
</blockquote></details>

The second option is what I would recommend--I have no issue with some other test checking that all of the input tensors are allocated (this actually probably is something that should be tested), but I think that test is outside the scope of the semantics of `allocate_tensors`, which is only required to allocate the output tensors (also, in that case it should probably be renamed to `allocate_output_tensors`?)


<!-- Sent from Reviewable.io -->

2024-08-22 19:55 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 2 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/include/local-execution/task_impl_function.variant.toml` line 4 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3tyb9oCkn1_SWRKTwK:-O4vVyGu6AW3ETUEln-q:bb6un1j) ([raw file](https://github.com/flexflow/FlexFlow/blob/4705fe35c569d1329adff7ec6720a4b645572b39/lib/local-execution/include/local-execution/task_impl_function.variant.toml#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can we also add `ord` here since `FwdBwdTaskImplFunction` now supports `ord`?
</blockquote></details>

Done
___
*[`lib/local-execution/include/local-execution/task_registry.h` line 12 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3eP5Mb3fhxTX69QbAq:-O4ve4Up6dVcJzssRpU9:b-6ht1cu) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/include/local-execution/task_registry.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't see why it requires `const` maps? It's totally fine to do `TaskRegistry r = TaskRegistry{{}, {}, {}, {}}; r.init_task_ids.insert({...});`. `dtgen` doesn't make the fields const (of course unless you declare a `TaskRegistry const r`, but then it's `const` because you explicitly told it to be)
</blockquote></details>

That makes complete sense. Changed.
___
*[`lib/local-execution/test/src/test_local_slots_backing.cc` line 77 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O3eCi8X6cGHzWkpZx_D:-O4vYK50A16CFzLc-pqz:b-dp5ea) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1a8a01e9e4f782805aa62c163bf50799f0638b4/lib/local-execution/test/src/test_local_slots_backing.cc#L77)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The second option is what I would recommend--I have no issue with some other test checking that all of the input tensors are allocated (this actually probably is something that should be tested), but I think that test is outside the scope of the semantics of `allocate_tensors`, which is only required to allocate the output tensors (also, in that case it should probably be renamed to `allocate_output_tensors`?)
</blockquote></details>

Ok, I've fixed this and moved some of the allocation around in the test to reflect only allocating inputs and then separately only allocating outputs. 


<!-- Sent from Reviewable.io -->

2024-08-22 21:16 UTC, lockshaw requested changes
> Reviewed 14 of 14 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 2 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/task_registry.struct.toml` line 9 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4vux9zEJTBx_Y2IH-A:-O4vux9zEJTBx_Y2IH-B:b-b6uvnl) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d6f87e13b8405eabaa0224bd57acd85f91af625/lib/local-execution/include/local-execution/task_registry.struct.toml#L9)):*
> ```TOML
> 
> includes = [
>   "local-execution/task_signature_impl.h",
> ```

This file doesn't seem to have any datatype declarations? Should this be a different file? Did you mean `task_signature_impl.dtg.h`?
___
*[`lib/local-execution/include/local-execution/task_registry.struct.toml` line 12 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4vuZKY4V2xt-0dBxtv:-O4vuZKY4V2xt-0dBxtw:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d6f87e13b8405eabaa0224bd57acd85f91af625/lib/local-execution/include/local-execution/task_registry.struct.toml#L12)):*
> ```TOML
>   "local-execution/task_id_t.dtg.h",
>   "pcg/layer_guid_t.dtg.h",
> ]
> ```





_Suggestion:_
```TOML
features = [
  "eq",
  "hash",
  "fmt",
]

includes = [
  "local-execution/task_signature_impl.h",
  "local-execution/task_id_t.dtg.h",
  "pcg/layer_guid_t.dtg.h",
]

src_includes = [
  "utils/hash/unordered_map.h",
  "utils/fmt/unordered_map.h", 
]
```
___
*[`lib/local-execution/test/src/test_task_registry.cc` line 99 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4vwBwR2QnC9-jgj3Iu:-O4vwBwR2QnC9-jgj3Iv:b-hcxjnr) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d6f87e13b8405eabaa0224bd57acd85f91af625/lib/local-execution/test/src/test_task_registry.cc#L99)):*
> ```cpp
> 
>     SUBCASE("equality") {
>       TaskRegistry other_task_registry = TaskRegistry{{}, {}, {}, {}};
> ```

If you want you can also create a helper function like `TaskRegistry empty_task_registry()` in `task_registry.h` that just returns a `TaskRegistry{{}, {}, {}, {}}` to avoid duplicating that code everywhere, but not a big deal either way



_Code quote:_
```cpp
     TaskRegistry other_task_registry = TaskRegistry{{}, {}, {}, {}}
```


<!-- Sent from Reviewable.io -->

2024-08-22 21:34 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 2 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/include/local-execution/task_registry.struct.toml` line 9 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4vux9zEJTBx_Y2IH-A:-O4vzNhv1R3x0pwx1JAZ:blb56ds) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d6f87e13b8405eabaa0224bd57acd85f91af625/lib/local-execution/include/local-execution/task_registry.struct.toml#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This file doesn't seem to have any datatype declarations? Should this be a different file? Did you mean `task_signature_impl.dtg.h`?
</blockquote></details>

Yes, changed.
___
*[`lib/local-execution/include/local-execution/task_registry.struct.toml` line 12 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4vuZKY4V2xt-0dBxtv:-O4w-T4E9dWGyoiU7k5c:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d6f87e13b8405eabaa0224bd57acd85f91af625/lib/local-execution/include/local-execution/task_registry.struct.toml#L12)):*
> ```TOML
>   "local-execution/task_id_t.dtg.h",
>   "pcg/layer_guid_t.dtg.h",
> ]
> ```

Done.
___
*[`lib/local-execution/test/src/test_task_registry.cc` line 99 at r16](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4vwBwR2QnC9-jgj3Iu:-O4vzHlp-764iB556bA4:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/1d6f87e13b8405eabaa0224bd57acd85f91af625/lib/local-execution/test/src/test_task_registry.cc#L99)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If you want you can also create a helper function like `TaskRegistry empty_task_registry()` in `task_registry.h` that just returns a `TaskRegistry{{}, {}, {}, {}}` to avoid duplicating that code everywhere, but not a big deal either way
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-22 21:36 UTC, lockshaw requested changes
> Reviewed 6 of 6 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 2 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/task_registry.h` line 6 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4w09mR1gomPHlDmCS6:-O4w09mR1gomPHlDmCS7:b-edbvir) ([raw file](https://github.com/flexflow/FlexFlow/blob/5b2c4300487630363f391a257c8a1271c9f43bab/lib/local-execution/include/local-execution/task_registry.h#L6)):*
> ```objc
> 
> #include "local-execution/task_registry.dtg.h"
> #include "local-execution/task_signature_impl.h"
> ```

Why was this added?
___
*[`lib/local-execution/include/local-execution/task_signature_impl.struct.toml` line 15 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4w-zoJEfEduHoFHv4W:-O4w-zoJEfEduHoFHv4X:b-7b93df) ([raw file](https://github.com/flexflow/FlexFlow/blob/5b2c4300487630363f391a257c8a1271c9f43bab/lib/local-execution/include/local-execution/task_signature_impl.struct.toml#L15)):*
> ```TOML
> 
> src_includes = [
>   "utils/hash/unordered_map.h",
> ```

Why are these necessary? I don't see any `unordered_map`s or `unordered_set`s in the members?


<!-- Sent from Reviewable.io -->

2024-08-22 21:42 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 2 unresolved discussions (waiting on @lockshaw)

___
*[`lib/local-execution/include/local-execution/task_registry.h` line 6 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4w09mR1gomPHlDmCS6:-O4w1EOp2E3wwlTSs74V:bhvxfm0) ([raw file](https://github.com/flexflow/FlexFlow/blob/5b2c4300487630363f391a257c8a1271c9f43bab/lib/local-execution/include/local-execution/task_registry.h#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was this added?
</blockquote></details>

oops, added to the wrong file. changed (it's in `local_training_backing.cc` and `task_registry.cc` now)
___
*[`lib/local-execution/include/local-execution/task_signature_impl.struct.toml` line 15 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4w-zoJEfEduHoFHv4W:-O4w0fe84d1mpROxG_gg:b-goqkvu) ([raw file](https://github.com/flexflow/FlexFlow/blob/5b2c4300487630363f391a257c8a1271c9f43bab/lib/local-execution/include/local-execution/task_signature_impl.struct.toml#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are these necessary? I don't see any `unordered_map`s or `unordered_set`s in the members?
</blockquote></details>

It's needed to be able to hash `OpTaskSignature`. Removed the `fmt` includes though.


<!-- Sent from Reviewable.io -->

2024-08-22 21:45 UTC, lockshaw requested changes
> Reviewed 4 of 4 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/task_signature_impl.struct.toml` line 15 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4w-zoJEfEduHoFHv4W:-O4w2BgI8fowJepAL_kd:bdyhao7) ([raw file](https://github.com/flexflow/FlexFlow/blob/5b2c4300487630363f391a257c8a1271c9f43bab/lib/local-execution/include/local-execution/task_signature_impl.struct.toml#L15)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

It's needed to be able to hash `OpTaskSignature`. Removed the `fmt` includes though.
</blockquote></details>

Ah, because that's still using `visitable`. Let's put the includes in `op_task_signature.h` then rather than here


<!-- Sent from Reviewable.io -->

2024-08-22 21:51 UTC, lockshaw approved these changes
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2024-08-22 21:51 UTC, reyna-abhyankar reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1418)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @reyna-abhyankar)

___
*[`lib/local-execution/include/local-execution/task_signature_impl.struct.toml` line 15 at r17](https://reviewable.io/reviews/flexflow/FlexFlow/1418#-O4w-zoJEfEduHoFHv4W:-O4w3h3o-JCDKviefQ1k:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5b2c4300487630363f391a257c8a1271c9f43bab/lib/local-execution/include/local-execution/task_signature_impl.struct.toml#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Ah, because that's still using `visitable`. Let's put the includes in `op_task_signature.h` then rather than here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-22 21:59 UTC, merged