Attn qkv proj
flexflow/FlexFlow pull request #1436
Opened 2024-07-10 15:31 UTC by yingchen21

**Description of changes:**
This PR moves the qkv projection (and output projection) from the attention operator into a separate dense layer to support LORA on qkv projection (and output projection)

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-08-04 04:40 UTC, yingchen21 commented
This PR has been implemented for `IncMultiHeadSelfAttention`, `TreeIncMultiHeadSelfAttention` and `SpecIncMultiHeadSelfAttention`. Its cuda implementation is tested under TP=2, TP=4, both with fusion and w/o fusion.
The backward pass is tested for earlier commit. Due to some issue I had with script testing `peft` the latest commit's backward pass is not tested yet

2024-08-04 05:02 UTC, yingchen21 commented
Rebased onto `peft` branch and tested forward pass

2024-09-03 23:24 UTC, goliaro requested changes
great work! I left some comments. The code is working locally on my machine, so I think we only need to do a bit of cleanup, then we can merge. We also need to remove the unused functions from the attention files (.cu & .cpp) and the deprecated parameters (weight_ptr, bias_ptr). Once done, can you apply the disaggregation to the other models as well (opt, mpt, falcon, etc)?

2024-09-03 23:24 UTC, goliaro commented on inference/models/llama.cc
> +    att_norm->print("att_norm");
I think we can remove all tensor prints from this file

2024-09-03 23:24 UTC, goliaro commented on inference/models/llama.cc
> +            3, // q, k, v. need to change if want to remove replication.
thanks for adding this comment, it's super helpful for future reference!

2024-09-03 23:24 UTC, goliaro commented on inference/models/llama.cc
> +    Tensor mha_input = mha;
can we just reuse the same `mha` tensor for the input of the output projection?

2024-09-03 23:24 UTC, goliaro commented on src/ops/inc_multihead_self_attention.cc
> +  // launcher.add_region_requirement(
feel free to delete these commented out regions

2024-09-03 23:24 UTC, goliaro commented on src/ops/inc_multihead_self_attention.cc
> +  // GenericTensorAccessorR weight = helperGetGenericTensorAccessorRO(
we can also delete the commented out code here to access the weights/biases

2024-09-03 23:24 UTC, goliaro commented on src/ops/inc_multihead_self_attention.cu
> +                        // DT const *weight_ptr,
can you go ahead and delete the weight_ptr and bias_ptr from any function that still has still as a parameter, even if commented out? You might need to also update the headers

2024-09-03 23:24 UTC, goliaro commented on src/ops/inc_multihead_self_attention.cu
> +__global__ void transposeAdd_half_kernel(
can you use a template to avoid duplicating the code for this kernel?

2024-09-03 23:24 UTC, goliaro commented on src/ops/inc_multihead_self_attention.cu
> +        static_cast<half const *>(nullptr), // weight_ptr is no longer used
let's remove these null pointers and remove the weight/bias arguments to the inference_kernel

2024-09-03 23:24 UTC, goliaro commented on src/ops/inc_multihead_self_attention.cu
> +      // TODO: checkout if the input grad ptr has some relation with
can you replace these comments with an explanation of what this transposeAdd is doing and why it is needed?

2024-09-03 23:24 UTC, goliaro commented on src/ops/kernels/linear_kernels.cu
> +    // printf("%s: input_grad has shape %d, %d\n", m->op_name, in_dim,
can you remove this?

2024-09-03 23:24 UTC, goliaro commented on src/ops/linear.cc
> +           "num_peft_tokens = %d, volume = %d\n",
let's comment this out once done with debugging

2024-09-03 23:24 UTC, goliaro commented on src/runtime/request_manager.cc
> +      // assert(false && "terminate");
let's remove this

2024-09-03 23:24 UTC, goliaro commented on src/runtime/request_manager.cc
> +  // assert(false && "RM terminating bg server due to exit");
and this one

2024-10-09 22:27 UTC, merged