Unordered StridedRectangle, `get_allowed_machine_views`
flexflow/FlexFlow pull request #1458
Opened 2024-08-07 03:03 UTC by Marsella8

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-08-08 05:02 UTC, lockshaw requested changes
> Reviewed 35 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 35 of 41 files reviewed, 14 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/pcg/include/pcg/device_coordinates.struct.toml` line 1 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3kMJ2uCO_X_82Ef9fg:-O3kMJ2uCO_X_82Ef9fh:bkv20ih) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/include/pcg/device_coordinates.struct.toml#L1)):*
> ```TOML
> # DeviceCoordinates is exclusive to machine_view.cc, must not be used outside of it.
> ```

I don't think this requirement is necessary anymore with the new design?
___
*[`lib/pcg/include/pcg/strided_rectangle.struct.toml` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3eyV3J8vJoDBYVtIIJ:-O3eyV3J8vJoDBYVtIIK:b-9bahdc) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/include/pcg/strided_rectangle.struct.toml#L17)):*
> ```TOML
>   "utils/hash/unordered_multiset.h",
>   "utils/fmt/unordered_multiset.h",
> ]
> ```

`utils/hash` and `utils/fmt` are only needed for the implementation, not the declaration



_Suggestion:_
```TOML
includes = [
  "pcg/strided_rectangle_side.dtg.h",
  "<unordered_set>",
]

src_includes = [
  "utils/hash/unordered_multiset.h",
  "utils/fmt/unordered_multiset.h",
]
```
___
*[`lib/pcg/src/pcg/device_id.cc` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3ezGRKAv8Ri8ePheTY:-O3ezGRKAv8Ri8ePheTZ:bmexkjw) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/src/pcg/device_id.cc#L29)):*
> ```cpp
> 
> int get_raw_id(device_id_t device_id) {
>   if (get_device_type(device_id) == DeviceType::GPU) {
> ```

`switch` might be cleaner? You can also use `overload` if you'd prefer



_Code quote:_
```cpp
  if (get_device_type(device_id) == DeviceType::GPU) {
```
___
*[`lib/pcg/src/pcg/device_id.cc` line 35 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3eyvOp2lo4k6RLRSNH:-O3eyvOp2lo4k6RLRSNI:b1mkmv5) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/src/pcg/device_id.cc#L35)):*
> ```cpp
>   } else {
>     assert(false && "Unsupported DeviceType");
>     return -1;
> ```

`assert`s will get removed in non-debug builds



_Suggestion:_
```cpp
    throw mk_runtime_error(fmt::format("Unsupported DeviceType {} for device_id_t {}", get_device_type(device_id), device_id));
```
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 66 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3kLhGo-C7pDbGH4uUz:-O3kLhGo-C7pDbGH4uV-:bt41u19) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/test/src/pcg/machine_view.cc#L66)):*
> ```cpp
>         CHECK(expected == result);
>       }
>       SUBCASE("get_last_device_id") {
> ```

Test functions separately (i.e., group by `get_last_device_id` rather than by `MachineView` tested on) except for particularly trivial utility functions
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 70 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3kLaP39h7QZEtbX8PR:-O3kLaP39h7QZEtbX8PS:b-mnn8xg) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/test/src/pcg/machine_view.cc#L70)):*
> ```cpp
>       }
>     }
>     SUBCASE("MachineView #2") {
> ```

Use better test names
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 93 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3kLs6X3hVOzLIUDWa9:-O3kLs6X3hVOzLIUDWaA:b-uglc4u) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/test/src/pcg/machine_view.cc#L93)):*
> ```cpp
>   }
> 
>   TEST_CASE("MachineView make_1d_machine_view - GPU") {
> ```

The return type here isn't really necessary and is a bit confusing



_Suggestion:_
```cpp
  TEST_CASE("make_1d_machine_view - GPU") {
```
___
*[`lib/utils/include/utils/containers/foldl.h` line 27 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f3sGJBCFBlegjMBBi:-O3f3sGJBCFBlegjMBBj:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/include/utils/containers/foldl.h#L27)):*
> ```objc
>   C remaining(it, c.end());
>   return foldl(remaining, init, func);
> }
> ```





_Suggestion:_
```objc
template <typename C, typename F, typename E = typename C::value_type>
auto foldl1(C const &c, F func) -> typename C::value_type {
  if (c.empty()) {
     throw mk_runtime_error(fmt::format("foldl1 received empty container: {}", c)); 
  }
  
  std::optional<E> result;
  
  for (E const &e : c) { 
    if (!result.has_value()) {
      result = e; 
    } else {
      result = f(result.value(), e); 
    }
  }
  
  return result.value();
}
```
___
*[`lib/utils/include/utils/containers/range.h` line 11 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f4kzS1cvlhJvBgstY:-O3f4kzS1cvlhJvBgstZ:b-tcqt76) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/include/utils/containers/range.h#L11)):*
> ```objc
> 
> template <typename T>
> std::vector<T> range(T start, T end, T step = 1) {
> ```

C++ doesn't do generics super well so I'd lean toward concrete types unless there's a strong need for something more flexible



_Suggestion:_
```objc
std::vector<int> range(int start, int end, int step = 1) {
```
___
*[`lib/utils/include/utils/containers/replicate.h` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f50Ax3KwAQN1iLyWT:-O3f50Ax3KwAQN1iLyWU:b22pfvc) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/include/utils/containers/replicate.h#L9)):*
> ```objc
> 
> template <typename T>
> std::unordered_multiset<T> replicate(std::size_t n, T const &element) {
> ```

Prefer `int`--`size_t` intuitively seems like it should be good (it represents non-negative values!) but actually what it does is just remove the failure case by overflowing so you can't even assert that the value is okay. At some point we may add a non-negative integer type with the proper semantics, but we don't have one yet



_Code quote:_
```objc
std::size_t
```
___
*[`lib/utils/include/utils/containers/scanl.h` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f5kO_034t0RbELolF:-O3f5kO_034t0RbELolG:b5ri2c7) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/include/utils/containers/scanl.h#L9)):*
> ```objc
> 
> template <typename C, typename F, typename T>
> std::vector<T> scanl(C const &c, T init, F const &op) {
> ```

Can you add a docstring with a reference to https://hackage.haskell.org/package/base-4.20.0.1/docs/Prelude.html#v:scanl? Not everyone on the FlexFlow team does a bunch of Haskell :slightly_smiling_face: 
___
*[`lib/utils/include/utils/containers/scanl.h` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f5VaCBheWzd6XE0xy:-O3f5VaCBheWzd6XE0xz:b-hx0eqo) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/include/utils/containers/scanl.h#L24)):*
> ```objc
> template <typename C, typename F>
> auto scanl1(C const &c, F op) {
>   using T = typename C::value_type;
> ```

See implementation of `fold1` for a more readable version
___
*[`lib/utils/test/src/utils/containers/foldl.cc` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f2KAN2vtWdLtQdYYR:-O3f2KAN2vtWdLtQdYYS:b3o8t1r) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/test/src/utils/containers/foldl.cc#L9)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("foldl") {
> ```

I can see you're enjoying Haskell :stuck_out_tongue: 
___
*[`lib/utils/test/src [...]

2024-08-10 21:27 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 24 of 46 files reviewed, 14 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/pcg/include/pcg/device_coordinates.struct.toml` line 1 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3kMJ2uCO_X_82Ef9fg:-O3p3bLh81ZhpLnHpWO6:b4gzlhe) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/include/pcg/device_coordinates.struct.toml#L1)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think this requirement is necessary anymore with the new design?
</blockquote></details>

Not a requirement anymore, but I think the user will generally reason about the position of the devices using `device_id_t`, so it probably won't be used.
___
*[`lib/pcg/include/pcg/strided_rectangle.struct.toml` line 17 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3eyV3J8vJoDBYVtIIJ:-O3pEF9dCpHDUW3ua01I:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/include/pcg/strided_rectangle.struct.toml#L17)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`utils/hash` and `utils/fmt` are only needed for the implementation, not the declaration
</blockquote></details>

Done.
___
*[`lib/pcg/src/pcg/device_id.cc` line 29 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3ezGRKAv8Ri8ePheTY:-O3pEmw--avjUpRY5AI3:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/src/pcg/device_id.cc#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`switch` might be cleaner? You can also use `overload` if you'd prefer
</blockquote></details>

Done.
___
*[`lib/pcg/src/pcg/device_id.cc` line 35 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3eyvOp2lo4k6RLRSNH:-O3pEpbB128970pWRnBi:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/src/pcg/device_id.cc#L35)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`assert`s will get removed in non-debug builds
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 66 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3kLhGo-C7pDbGH4uUz:-O3pHjas6qBi1WayUsGF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/test/src/pcg/machine_view.cc#L66)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Test functions separately (i.e., group by `get_last_device_id` rather than by `MachineView` tested on) except for particularly trivial utility functions
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 70 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3kLaP39h7QZEtbX8PR:-O3pHkes4xG1bJTC2sMf:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/test/src/pcg/machine_view.cc#L70)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use better test names
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 93 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3kLs6X3hVOzLIUDWa9:-O3pHeoYCuh-ssqpsDP-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/pcg/test/src/pcg/machine_view.cc#L93)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The return type here isn't really necessary and is a bit confusing
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/containers/foldl.h` line 27 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f3sGJBCFBlegjMBBi:-O3pJm7J3tPdN5yRA9n9:be14fcv) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/include/utils/containers/foldl.h#L27)):*
> ```objc
>   C remaining(it, c.end());
>   return foldl(remaining, init, func);
> }
> ```

cool pattern !
___
*[`lib/utils/include/utils/containers/range.h` line 11 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f4kzS1cvlhJvBgstY:-O3pLbQK1apVHoWMW0-z:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/include/utils/containers/range.h#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

C++ doesn't do generics super well so I'd lean toward concrete types unless there's a strong need for something more flexible
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/containers/replicate.h` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f50Ax3KwAQN1iLyWT:-O3pMS4n4soeHVK71YgB:b21rho4) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/include/utils/containers/replicate.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `int`--`size_t` intuitively seems like it should be good (it represents non-negative values!) but actually what it does is just remove the failure case by overflowing so you can't even assert that the value is okay. At some point we may add a non-negative integer type with the proper semantics, but we don't have one yet
</blockquote></details>

Ahh makes sense thanks.
___
*[`lib/utils/include/utils/containers/scanl.h` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f5kO_034t0RbELolF:-O3pSnX15aKpNxxxds_p:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/include/utils/containers/scanl.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you add a docstring with a reference to https://hackage.haskell.org/package/base-4.20.0.1/docs/Prelude.html#v:scanl? Not everyone on the FlexFlow team does a bunch of Haskell :slightly_smiling_face:
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/containers/scanl.h` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f5VaCBheWzd6XE0xy:-O3pVQTF3mnhyxUHx3w6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/include/utils/containers/scanl.h#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

See implementation of `fold1` for a more readable version
</blockquote></details>

Done.
___
*[`lib/utils/test/src/utils/containers/foldl.cc` line 9 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f2KAN2vtWdLtQdYYR:-O3pVT313yTS2gjQbAbe:b-ld21h6) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/test/src/utils/containers/foldl.cc#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I can see you're enjoying Haskell :stuck_out_tongue:
</blockquote></details>

hahaha yes, I'm starting to see why you're so frustrated with C++. Functional code is so clean, wish the C++ syntax was a bit more accomodating...
___
*[`lib/utils/test/src/utils/containers/range.cc` line 45 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3f1YHS6ilQYF52qCVr:-O3pM5DNExt9XS0R-XWz:bnk6tcs) ([raw file](https://github.com/flexflow/FlexFlow/blob/d3f16577e7d05d95fe7ec49251ed1fb84c544cc3/lib/utils/test/src/utils/containers/range.cc#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What's the expected behavior of `range(0, 10, -1)`?
</blockquote></details>

empty range (this range is modelled after python's `range`s, so I'd like to keep it consistent, but we can also change it to throw  [...]

2024-08-11 02:00 UTC, lockshaw requested changes
> Reviewed 2 of 41 files at r1, 19 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 44 of 49 files reviewed, 32 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/compiler/include/compiler/machine_mapping.h` line 63 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z2XH85hZxtpAKQ1xC:-O3z2XH9E8IkIuBxPvV_:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/include/compiler/machine_mapping.h#L63)):*
> ```objc
> std::unordered_set<StartInvariantMachineView>
>     get_allowed_start_invariant_machine_views(
>         MachineSpecification const &machinespec,
> ```





_Suggestion:_
```objc
        MachineSpecification const &machine_spec,
```
___
*[`lib/compiler/src/machine_mapping.cc` line 378 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z2qqWBSJhGSm9y1At:-O3z2qqX3dTWfdBa-BZY:b-u6y99c) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L378)):*
> ```cpp
> }
> 
> std::vector<int> get_tensor_parallel_degrees(ParallelTensorShape const &shape) {
> ```

Should not return a `vector` as that imposes an order on `ParallelTensorShape`'s dims, should return either an `unordered_set` or a custom dtgen struct
___
*[`lib/compiler/src/machine_mapping.cc` line 385 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z8cOO1QFvNnavMg60:-O3z8cOPEtLGMbpdfLEX:b2cxs40) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L385)):*
> ```cpp
> }
> 
> bool is_valid_machine_view(MachineView const &mv,
> ```

A blank line here or there would also help readability--you can use them to break up flows of steps into logical pieces
___
*[`lib/compiler/src/machine_mapping.cc` line 393 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z36DuAOQMzNlQU1ov:-O3z36Dv78i09ZhvT8Lj:b8lua87) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L393)):*
> ```cpp
>   tensor_degrees =
>       filter(tensor_degrees, [](int degree) { return degree != 1; });
>   return without_order(mv_degrees) == without_order(tensor_degrees);
> ```

This returns a `multiset`, right?



_Code quote:_
```cpp
without_order(mv_degrees)
```
___
*[`lib/compiler/src/machine_mapping.cc` line 401 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z3Y7H-WpHq3T4zWji:-O3z3Y7H-WpHq3T4zWjj:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L401)):*
> ```cpp
>                                 ParallelTensorShape const &shape) {
> 
>   auto candidate_strides = [](std::vector<int> tensor_dims, int total_devices) {
> ```





_Suggestion:_
```cpp
std::vector<int> const &tensor_dims
```
___
*[`lib/compiler/src/machine_mapping.cc` line 401 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z4GweAmilqB4UZzHO:-O3z4GweAmilqB4UZzHP:b-r1dc2o) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L401)):*
> ```cpp
>                                 ParallelTensorShape const &shape) {
> 
>   auto candidate_strides = [](std::vector<int> tensor_dims, int total_devices) {
> ```

I think a return type annotation here would really improve readability



_Code quote:_
```cpp
[](std::vector<int> tensor_dims, int total_devices) {
```
___
*[`lib/compiler/src/machine_mapping.cc` line 404 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z4PHS4YR4YvRrckhF:-O3z4PHS4YR4YvRrckhG:bqk7m9d) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L404)):*
> ```cpp
>     int max_stride_upper_bound =
>         (total_devices + 1) /
>         product(transform(tensor_dims, [](int degree) { return degree - 1; }));
> ```

This is a bit complicated, I feel like a one-line comment would help me figure out what this dense piece of arithmetic is actually doing (or break up the nested expressions and give them each names. While composition of a bunch of functions can be concise, having intermediate variables can really help make code more readable as you can describe each intermediate value/step along the way. Conciseness is good when it benefits readability, but sometimes it gets in the way more than it helps)



_Code quote:_
```cpp
    int max_stride_upper_bound =
        (total_devices + 1) /
        product(transform(tensor_dims, [](int degree) { return degree - 1; }));
```
___
*[`lib/compiler/src/machine_mapping.cc` line 405 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z4DFQ07st_HOZNbDr:-O3z4DFQ07st_HOZNbDs:b-5wk1j7) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L405)):*
> ```cpp
>         (total_devices + 1) /
>         product(transform(tensor_dims, [](int degree) { return degree - 1; }));
>     std::unordered_multiset<std::vector<int>> strides = cartesian_product(
> ```

Should this be a `stride_size_t`?



_Code quote:_
```cpp
int
```
___
*[`lib/compiler/src/machine_mapping.cc` line 410 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z7AAlBgGQ3Hg9k9GO:-O3z7AAlBgGQ3Hg9k9GP:b-w6wnr2) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L410)):*
> ```cpp
>   };
> 
>   std::vector<int> tensor_dims = filter(get_tensor_parallel_degrees(shape),
> ```

Seems like a common pattern, probably good to pull out a separate function?
___
*[`lib/compiler/src/machine_mapping.cc` line 413 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z3MNR5oCZEJMFcszy:-O3z3MNR5oCZEJMFcszz:b30ku6v) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L413)):*
> ```cpp
>                                         [](int degree) { return degree != 1; });
>   std::unordered_set<MachineView> machine_views;
>   int total_devices = machinespec.num_nodes * machinespec.num_gpus_per_node;
> ```

Why not just have a `get_num_devices` or something function for `MachineSpecification`?



_Code quote:_
```cpp
  int total_devices = machinespec.num_nodes * machinespec.num_gpus_per_node;
```
___
*[`lib/compiler/src/machine_mapping.cc` line 414 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z3QFU9qzliwMouLEm:-O3z3QFU9qzliwMouLEn:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L414)):*
> ```cpp
>   std::unordered_set<MachineView> machine_views;
>   int total_devices = machinespec.num_nodes * machinespec.num_gpus_per_node;
>   for (std::vector<int> stride :
> ```





_Suggestion:_
```cpp
  for (std::vector<int> const &stride :
```
___
*[`lib/compiler/src/machine_mapping.cc` line 416 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z7z0r86Vs6fGKTEQu:-O3z7z0r86Vs6fGKTEQv:bs9aju2) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L416)):*
> ```cpp
>   for (std::vector<int> stride :
>        candidate_strides(tensor_dims, total_devices)) {
>     for (int start_id = 0; start_id < total_devices; start_id++) {
> ```

Seems like this loop is intuitively creating `StartInvariantMachineView`s and then looping over possible start degrees? If so, could this be written to do that? Using more descriptive data structures instead of things like `std::vector<int>` or `std::vector<std::unordered_set<int>>` is super helpful for readability. This would also let you break up this function into more intuitive pieces (generating all start-invar [...]

2024-08-13 18:50 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 30 of 63 files reviewed, 32 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/include/compiler/machine_mapping.h` line 63 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z2XH85hZxtpAKQ1xC:-O42KvNeDwY6Ds0P8wBx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/include/compiler/machine_mapping.h#L63)):*
> ```objc
> std::unordered_set<StartInvariantMachineView>
>     get_allowed_start_invariant_machine_views(
>         MachineSpecification const &machinespec,
> ```

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 378 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z2qqWBSJhGSm9y1At:-O47r3S26G5E2IYzx5uk:bwm8wm1) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L378)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should not return a `vector` as that imposes an order on `ParallelTensorShape`'s dims, should return either an `unordered_set` or a custom dtgen struct
</blockquote></details>

changed to `unordered_multiset` (but have to sort the multiset in `get_candidate_machine_views`, since I need the ordering to be coherent between stride and dimension). 
___
*[`lib/compiler/src/machine_mapping.cc` line 385 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z8cOO1QFvNnavMg60:-O48JoEt5ySGt1O51vjb:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L385)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

A blank line here or there would also help readability--you can use them to break up flows of steps into logical pieces
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 393 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z36DuAOQMzNlQU1ov:-O42LBOxC6SgDGhg7U_0:b-r6ccei) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L393)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This returns a `multiset`, right?
</blockquote></details>

yes, since different dimensions might have the same degree (we want to see if there exists a mapping between the 2 (multi)sets of dimensions, so order does not matter)
___
*[`lib/compiler/src/machine_mapping.cc` line 401 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z3Y7H-WpHq3T4zWji:-O42LVlN3SOLfFi7hYeD:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L401)):*
> ```cpp
>                                 ParallelTensorShape const &shape) {
> 
>   auto candidate_strides = [](std::vector<int> tensor_dims, int total_devices) {
> ```

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 401 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z4GweAmilqB4UZzHO:-O48HnHm4fP_VCIsGf9g:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L401)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think a return type annotation here would really improve readability
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 404 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z4PHS4YR4YvRrckhF:-O47y4VP6Ka3wj7eQR1C:bj59rb7) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L404)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This is a bit complicated, I feel like a one-line comment would help me figure out what this dense piece of arithmetic is actually doing (or break up the nested expressions and give them each names. While composition of a bunch of functions can be concise, having intermediate variables can really help make code more readable as you can describe each intermediate value/step along the way. Conciseness is good when it benefits readability, but sometimes it gets in the way more than it helps)
</blockquote></details>

I've simplified, but it's still a bit tricky to explain:
Naively, we could think that, given a (2,3) stride for example, it would result in 3*2=6 as many tiles occupied with respect to having all strides be 1, so we could say `max_stride_product = num_total_devices/num_devices_used_by_tensor` (where `num_devices_used_by_tensor` is the product of the parallel dims) and so we could simply say that the max stride across any dimension is `max_stride_product`, so we do the cartesian product and then filter downstream.
This however, doesn't quite work: consider, for example, a 2D MachineView with 2x2 points, and stride 2 across each dimension, and suppose there are 9 total devices. While the "volume" of the MachineView is technically 4x4, it can really fit into a 3x3 and thus we could fit it with the existing devices (since the outer volume can be cut without messing with any of the devices). To address this, I find not the number of total devices used by the tensor, but, the total number of "inner" devices, essentially the ones such that they have associated with them a full stride "volume". So I find the max stride for these using the naive procedure (which works since they all have full stride volume) and I know that if a given stride is too large for them then surely it's too large for the full set of devices, which essentially contains them. (Note that this solutions is incredibly underoptimized, if the generation turns out to be to slow I'll fix it).
___
*[`lib/compiler/src/machine_mapping.cc` line 405 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z4DFQ07st_HOZNbDr:-O48141H4mjMqB4C-Dio:b-huam9g) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L405)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this be a `stride_size_t`?
</blockquote></details>

fixed. is there a way to cast a container containing type X to the same container but with type Y (so not using transform and casting within the lambda)? 
___
*[`lib/compiler/src/machine_mapping.cc` line 410 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z7AAlBgGQ3Hg9k9GO:-O481xr-7LqCoZc4IXB-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L410)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Seems like a common pattern, probably good to pull out a separate function?
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 413 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z3MNR5oCZEJMFcszy:-O481ycB49wFleUz09Z5:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L413)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not just have a `get_num_devices` or something function for `MachineSpecification`?
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 414 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O3z3QFU9qzliwMouLEm:-O42Rrhg5Jl9sDMcAvpp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/878954fdb6535a5e07ca65086febb7a6f4a145b0/lib/compiler/src/machine_mapping.cc#L414)):*
> ```cpp
>   std::unordered_set<MachineView> machine_views;
>   int total_devices = machinespec.num_nodes * machinespec.num_gpus_pe [...]

2024-08-15 01:18 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 30 of 66 files reviewed, 33 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 124 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4Ib4G46zXhvw8O_ZtK:-O4Ib4G51Lf46hZkFoQr:b-ttzy3h) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/src/compiler/allowed_machine_views.cc#L124)):*
> ```cpp
>                    start_invariant_from_machine_view);
> }
> ```

Unsure where to put these functions, will we be using `parallel_tensor_dim_idx` as the main way of indexing the ParallelTensorShape going forwards or is it just for doing the machine view to tensor mapping? 


<!-- Sent from Reviewable.io -->

2024-08-21 23:34 UTC, wmdi submitted a review, later dismissed
> Reviewed 36 of 36 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: all files reviewed, 33 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2024-08-22 04:00 UTC, lockshaw requested changes
> Reviewed 36 of 36 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: all files reviewed, 50 unresolved discussions (waiting on @Marsella8)

___
*[`lib/compiler/include/compiler/tensor_to_machine_view_injection.struct.toml` line 2 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rLoRm7accT7vb45zz:-O4rLZ3x73YibSJFcCSz:bmc85ih) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/include/compiler/tensor_to_machine_view_injection.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "TensorToMachineViewInjection"
> ```

Why is this not a surjection? Seems like all of the `MachineView` dims need to be mapped to?
___
*[`lib/compiler/include/compiler/tensor_to_machine_view_injection.struct.toml` line 14 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rLVlC6LthSOYD80w0:-O4rLVlC6LthSOYD80w1:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/include/compiler/tensor_to_machine_view_injection.struct.toml#L14)):*
> ```TOML
>   "utils/bidict/bidict.h",
>   "utils/hash/unordered_map.h"
> ]
> ```





_Suggestion:_
```TOML
includes = [
  "pcg/machine_view_dim_idx.dtg.h",
  "op-attrs/parallel_tensor_dim_idx.dtg.h",
  "utils/bidict/bidict.h",
]
```
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 36 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rOMAl7K1LdZciFYbk:-O4rOMAnEy_5K2hyjbsR:b-wnhjif) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/src/compiler/allowed_machine_views.cc#L36)):*
> ```cpp
> }
> 
> bool is_valid_machine_view(MachineView const &mv,
> ```

I don't see this function declared in `allowed_machine_view.h`?
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 124 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4Ib4G46zXhvw8O_ZtK:-O4rNvJu1L0oOY6t1F9a:b-9sghma) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/src/compiler/allowed_machine_views.cc#L124)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Unsure where to put these functions, will we be using `parallel_tensor_dim_idx` as the main way of indexing the ParallelTensorShape going forwards or is it just for doing the machine view to tensor mapping?
</blockquote></details>

For now let's put `get_parallel_dim_at_idx` and `get_parallel_tensor_indices` into `parallel_tensor_dim_idx.h`
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 152 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rOCUfDM-61cWRWKFb:-O4rOCUfDM-61cWRWKFc:brm1z5p) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/src/compiler/allowed_machine_views.cc#L152)):*
> ```cpp
> 
> std::unordered_set<machine_view_dim_idx>
>     get_machine_view_indices(MachineView const &mv) {
> ```

Move to `machine_view_dim_idx.h`
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 157 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rXJTm948Hi7kcybCb:-O4rXJTm948Hi7kcybCc:bx94tvz) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/src/compiler/allowed_machine_views.cc#L157)):*
> ```cpp
> }
> 
> bool is_valid_injection(TensorToMachineViewInjection const &injection,
> ```

Probably better to move this and the functions below to an `tensor_to_machine_view_injection.h` file
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 175 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rXak28bfUxIhMXbAG:-O4rXak28bfUxIhMXbAH:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/src/compiler/allowed_machine_views.cc#L175)):*
> ```cpp
>   std::unordered_set<parallel_tensor_dim_idx> shape_indices =
>       get_parallel_tensor_indices(shape);
>   shape_indices = filter(shape_indices, [&](auto const idx) {
> ```





_Suggestion:_
```cpp
(parallel_tensor_dim_idx const &idx)
```
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 183 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rXwh7C7yPIPlMxr_l:-O4rXwh7C7yPIPlMxr_m:b45h) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/src/compiler/allowed_machine_views.cc#L183)):*
> ```cpp
>        permutations(shape_indices)) {
>     TensorToMachineViewInjection injection =
>         TensorToMachineViewInjection(bidict(zip(sorted(mv_indices), p)));
> ```





_Suggestion:_
```cpp
  std::vector<machine_view_dim_idx> machine_view_dim_ordering = sorted(mv_indices);
  std::unordered_set<TensorToMachineViewInjection> result;
  for (std::vector<parallel_tensor_dim_idx> const &tensor_dim_ordering :
       permutations(shape_indices)) {
    TensorToMachineViewInjection injection =
        TensorToMachineViewInjection(bidict(zip(machine_view_dim_ordering, tensor_dim_ordering)));
```
___
*[`lib/compiler/test/src/allowed_machine_ views.cc` line 62 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4sB6a8CK8fhPgP270I:-O4sB6a8CK8fhPgP270J:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/test/src/allowed_machine_%20views.cc#L62)):*
> ```cpp
>           views.insert(mv);
>         }
>         return views;
> ```





_Suggestion:_
```cpp
        return unordered_set_of(transform(count(num_starts), 
                                          [&](int start) {
                                             return MachineView{
                                               device_id_t{gpu_id_t{start}},
                                               StridedRectangle{{
                                                 StridedRectangleSide{num_points_t{2}, stride_t{stride1}},
                                                 StridedRectangleSide{num_points_t{3}, stride_t{stride2}}
                                               }},
                                             };
                                           }));
```
___
*[`lib/compiler/test/src/allowed_machine_ views.cc` line 64 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4sBfjGEabLtA46L3vM:-O4sBfjHE9eliI2O_cFh:b-ktwa6c) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/test/src/allowed_machine_%20views.cc#L64)):*
> ```cpp
>         return views;
>       };
>       std::unordered_set<MachineView> correct;
> ```

Is it possible to instead consider a smaller `MachineSpecification` where the set of `MachineView`s is small enough that you don't need all this infrastructure to generate it? This testcase is a bit complicated and might be rather annoying to debug
___
*[`lib/compiler/test/src/allowed_machine_ views.cc` line 136 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4sByynE9QBZCkMOwo6:-O4sByyo5t1RzzPIneKR:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/4b8600da25d64ae2c0bee61e5ab682f6b4c32fc4/lib/compiler/test/src/allowed_machine_%20views.cc#L136)):*
> ```cpp
>           make_2d_view(/*stride1*/ 3, /*stride2*/ 1),
>           make_2d_view(/*stride1*/ 1, /*stride2*/ 3),
>           make_2d_view(/*stride1*/ 1, /*stride2*/ 4)};
> ```





_Suggestion:_
```cpp
      std::unordered_set<StartInvariantMachineView> correct = {
          make_2d_view(/*stride1*/ 1, /*stride2*/ 1),
          make_2d_view(/*stride1*/ 2, /*stride2*/ 1),
          make_2d_view(/*stride1*/ 1, /*stride2*/ 2),
          make_2d_view(/*stride1*/ 3, /*stride2*/ 1),
          make_2d_view(/*stride1*/ 1, /*stride2*/ 3),
          make_2d_view(/*stride1*/ 1, /*stride2*/ 4),
      };
```
___
*[`lib/compiler/test/src/allowed_machine_ views.cc` line 140 at r3](https://reviewable.io/reviews/fle [...]

2024-08-28 00:57 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: all files reviewed, 49 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/tensor_to_machine_view_injection.struct.toml` line 2 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rLoRm7accT7vb45zz:-O504GQLBdcbrTf7zKNA:bjibt7m) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/include/compiler/tensor_to_machine_view_injection.struct.toml#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is this not a surjection? Seems like all of the `MachineView` dims need to be mapped to?
</blockquote></details>

Changed the name to `MachineViewToTensorMapping`
___
*[`lib/compiler/include/compiler/tensor_to_machine_view_injection.struct.toml` line 14 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rLVlC6LthSOYD80w0:-O504ACa4w7kmvpBUATH:b-57p6k2) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/include/compiler/tensor_to_machine_view_injection.struct.toml#L14)):*
> ```TOML
>   "utils/bidict/bidict.h",
>   "utils/hash/unordered_map.h"
> ]
> ```

placed in `bidict.h` (wouldn't compile otherwise)
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 36 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rOMAl7K1LdZciFYbk:-O506dp90w3yGM0Mo0Ey:bejxqv1) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/src/compiler/allowed_machine_views.cc#L36)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't see this function declared in `allowed_machine_view.h`?
</blockquote></details>

added (their primary use is within `get_allowed_machine_views` but is probably nice to have them available externally).
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 152 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rOCUfDM-61cWRWKFb:-O5K_APq9gA3ZWAT_ddB:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/src/compiler/allowed_machine_views.cc#L152)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `machine_view_dim_idx.h`
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 157 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rXJTm948Hi7kcybCb:-O5Kd_k54BOuJ9W-_Kyd:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/src/compiler/allowed_machine_views.cc#L157)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably better to move this and the functions below to an `tensor_to_machine_view_injection.h` file
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 175 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rXak28bfUxIhMXbAG:-O5KdsdT096zGg5_ptJI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/src/compiler/allowed_machine_views.cc#L175)):*
> ```cpp
>   std::unordered_set<parallel_tensor_dim_idx> shape_indices =
>       get_parallel_tensor_indices(shape);
>   shape_indices = filter(shape_indices, [&](auto const idx) {
> ```

Done.
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 183 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4rXwh7C7yPIPlMxr_l:-O5Kh8wwCkYlCgnHtkkh:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/src/compiler/allowed_machine_views.cc#L183)):*
> ```cpp
>        permutations(shape_indices)) {
>     TensorToMachineViewInjection injection =
>         TensorToMachineViewInjection(bidict(zip(sorted(mv_indices), p)));
> ```

Done.
___
*[`lib/compiler/test/src/allowed_machine_ views.cc` line 62 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4sB6a8CK8fhPgP270I:-O5LIDuL59mtrPwe_QlY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/test/src/allowed_machine_%20views.cc#L62)):*
> ```cpp
>           views.insert(mv);
>         }
>         return views;
> ```

Done.
___
*[`lib/compiler/test/src/allowed_machine_ views.cc` line 64 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4sBfjGEabLtA46L3vM:-O5LOEbr939_PiZ9aB_X:b-2n81ej) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/test/src/allowed_machine_%20views.cc#L64)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is it possible to instead consider a smaller `MachineSpecification` where the set of `MachineView`s is small enough that you don't need all this infrastructure to generate it? This testcase is a bit complicated and might be rather annoying to debug
</blockquote></details>

I've simplified it a bit (still want to leave enough devices so that a couple of different strides can get generated, and manual enumeration might be too much).
___
*[`lib/compiler/test/src/allowed_machine_ views.cc` line 136 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4sByynE9QBZCkMOwo6:-O5LMbTn2XIuGye7GurH:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/test/src/allowed_machine_%20views.cc#L136)):*
> ```cpp
>           make_2d_view(/*stride1*/ 3, /*stride2*/ 1),
>           make_2d_view(/*stride1*/ 1, /*stride2*/ 3),
>           make_2d_view(/*stride1*/ 1, /*stride2*/ 4)};
> ```

Done.
___
*[`lib/compiler/test/src/allowed_machine_ views.cc` line 140 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4sC1lX2yc7j3CFQEwG:-O5LNYtF3l0rHuazjHX_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/test/src/allowed_machine_%20views.cc#L140)):*
> ```cpp
>       std::unordered_set<StartInvariantMachineView> result =
>           get_allowed_start_invariant_machine_views(ms, shape);
>       CHECK(result == correct);
> ```

Done.
___
*[`lib/compiler/test/src/allowed_machine_ views.cc` line 163 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4sC7yG-xKuasn2eKrm:-O5LO8M18vyh972WZreF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/test/src/allowed_machine_%20views.cc#L163)):*
> ```cpp
>                          StridedRectangleSide{num_points_t(2), stride_t(4)},
>                          StridedRectangleSide{num_points_t(3), stride_t(1)}},
>                     }};
> ```

Done.
___
*[`lib/compiler/test/src/allowed_machine_ views.cc` line 178 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4sCSQOA-nMQ32L2sDh:-O5LO8oYAcdYseLmwRAh:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/test/src/allowed_machine_%20views.cc#L178)):*
> ```cpp
>     std::unordered_set<TensorToMachineViewInjection> result =
>         get_all_tensor_to_machine_view_injections(view, shape);
>     CHECK(correct == result);
> ```

Done.
___
*[`lib/compiler/test/src/machine_mapping.cc` line 7 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O4sCk_C0HP01AclmrDR:-O5KfPuo6IsWMDfHDb_J:btmpdfp) ([raw file](https://github.com/flexflow/FlexFlow/blob/94e2dc29975b7028022a9f0ea9414b127047bd4c/lib/compiler/test/src/machine_mapping.cc#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What's happening with this file?
</blockquote></details>

old test cases, i haven't touched them.
___
*[`lib/op-attrs/include/op-attrs/parallel_tensor_dim_idx.variant.toml` line 2 at r3](https://reviewable.io/revie [...]

2024-09-07 05:22 UTC, lockshaw reviewed
Deferring review until new device id calculation is added.

> Reviewed 19 of 41 files at r4.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-:-O69vhhA6q-NgC1qnBq4:b-oue28l)* status: 60 of 82 files reviewed, 20 unresolved discussions (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2024-09-10 00:15 UTC, lockshaw requested changes
> Reviewed 19 of 41 files at r4, 16 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 85 of 86 files reviewed, 31 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 44 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O7gAm2IZyo9wT0RWY:-O6O7gAm2IZyo9wT0RWZ:bw6er2r) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/src/compiler/allowed_machine_views.cc#L44)):*
> ```cpp
> bool is_valid_machine_view(MachineView const &mv,
>                            MachineSpecification const &machine_spec) {
>   return false; // TODO: fix
> ```

Implement or mark as `NOT_IMPLEMENTED()`



_Code quote:_
```cpp
  return false; // TODO: fix
```
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 67 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6OFa7r6jiQyu-oVCKg:-O6OFa7r6jiQyu-oVCKh:b53mxqw) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/src/compiler/allowed_machine_views.cc#L67)):*
> ```cpp
>  */
> static std::unordered_set<MachineView>
>     get_candidate_machine_views(MachineSpecification const &machine_spec,
> ```

Can any of this get pulled out into separate functions that make logical sense by themselves? Each statement is okay to read but the sheer number of statements is a bit intense and doesn't provide a lot of walking the reader through. If it really is this complicated that's fine (there are places where stuff just fundamentally needs a bunch of code that can't get decomposed), but I'd like to be convinced of that :slightly_smiling_face: 
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 0 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O7YaTBdYUswMCZ6fW:-O6O7YaTBdYUswMCZ6fX:b-t6ewa6) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/test/src/allowed_machine_views.cc#L0)):*
What's happening with this?
___
*[`lib/compiler/test/src/machine_view_to_tensor_mapping.cc` line 12 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O8PuR8sCdAOkUKmnH:-O6O8PuR8sCdAOkUKmnI:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/test/src/machine_view_to_tensor_mapping.cc#L12)):*
> ```cpp
>   TEST_CASE("get_all_machine_view_to_tensor_mappings") {
>     ParallelTensorShape shape = ParallelTensorShape{
>         ParallelTensorDims{
> ```





_Suggestion:_
```cpp
    SUBCASE("no possible mappings") {
      ...@pietro implement this ...
    }
    
    SUBCASE("multiple possible mappings") {
      ParallelTensorShape shape = ParallelTensorShape{
          ParallelTensorDims{
```
___
*[`lib/compiler/test/src/machine_view_to_tensor_mapping.cc` line 26 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O8DRdBCtnDOvcACyw:-O6O8DRdBCtnDOvcACyx:btdaxks) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/test/src/machine_view_to_tensor_mapping.cc#L26)):*
> ```cpp
>         MachineView{DeviceCoordinates{{0, 0, 0}},
>                     StridedRectangle{{
>                         StridedRectangleSide{num_points_t(2), stride_t(1)},
> ```

For consistency



_Suggestion:_
```cpp
num_points_t{2},
```
___
*[`lib/compiler/test/src/machine_view_to_tensor_mapping.cc` line 33 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O8A5308q2ma_8nDP_:-O6O8A5308q2ma_8nDPa:btdaxks) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/test/src/machine_view_to_tensor_mapping.cc#L33)):*
> ```cpp
> 
>     bidict<machine_view_dim_idx_t, parallel_tensor_dim_idx_t> b1 = {
>         {machine_view_dim_idx_t(2), parallel_tensor_dim_idx_t{ff_dim_t(0)}},
> ```

For consistency



_Suggestion:_
```cpp
        {machine_view_dim_idx_t{2}, parallel_tensor_dim_idx_t{ff_dim_t{0}}},
```
___
*[`lib/compiler/test/src/machine_view_to_tensor_mapping.cc` line 37 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O8hsD6WuF6XY5J8_q:-O6O8hsD6WuF6XY5J8_r:b-fz3o0t) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/test/src/machine_view_to_tensor_mapping.cc#L37)):*
> ```cpp
>          parallel_tensor_dim_idx_t{ReplicaType::SUM}},
>         {machine_view_dim_idx_t(0),
>          parallel_tensor_dim_idx_t{ReplicaType::DISCARD_COPY}}};
> ```

Might make this a bit more readable.



_Suggestion:_
```cpp
    machine_view_dim_idx_t mv_dim_0 = machine_view_dim_idx_t{0};
    machine_view_dim_idx_t mv_dim_1 = machine_view_dim_idx_t{1};
    machine_view_dim_idx_t mv_dim_2 = machine_view_dim_idx_t{2};
    parallel_tensor_dim_idx_t pt_dim_0 = parallel_tensor_dim_idx_t{ff_dim_t{0}};
    parallel_tensor_dim_idx_t pt_dim_sum = parallel_tensor_dim_idx_t{ReplicaType::SUM};
    parallel_tensor_dim_idx_t pt_dim_eq = parallel_tensor_dim_idx_t{ReplicaType::DISCARD_COPY};
    
    bidict<machine_view_dim_idx_t, parallel_tensor_dim_idx_t> b1 = {
        {mv_dim_2, pt_dim_0},
        {mv_dim_1, pt_dim_sum},
        {mv_dim_0, pt_dim_eq},
    };
```
___
*[`lib/local-execution/test/src/test_local_cost_estimator.cc` line 69 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O9cyS4Qci8wdZVCRn:-O6O9cyS4Qci8wdZVCRo:bfznc9z) ([raw file](https://github.com/flexflow/FlexFlow/blob/5e1f349215294ae312ccac9f2891aecacaf95e39/lib/local-execution/test/src/test_local_cost_estimator.cc#L69)):*
> ```cpp
>           std::vector<ParallelTensorAttrs>{weight_attrs},
>           std::vector<ParallelTensorAttrs>{output_attrs},
>           make_1d_machine_view(gpu_id_t{0}, gpu_id_t{1}));
> ```

I kinda like the clarify of having the GPU types in here--is there a reason this overload was removed? If you prefer to not wrap the argument types, it would be nice to force the `DeviceType` to be passed explicitly so there's no ambiguity (yes we're pretty much always going to be using GPU ids, but as long as CPU ids are an option I'd rather it be 100% clear which one is being constructed).

Another option would be to rename this to `make_1d_gpu_machine_view` if you like that better
___
*[`lib/op-attrs/include/op-attrs/parallel_tensor_dim_idx_t.h` line 13 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O5FFY2Ui0DsK-O4Ty:-O6O5FFY2Ui0DsK-O4Tz:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/op-attrs/include/op-attrs/parallel_tensor_dim_idx_t.h#L13)):*
> ```objc
> 
> std::unordered_set<parallel_tensor_dim_idx_t>
>     get_parallel_tensor_indices(ParallelTensorShape const &shape);
> ```





_Suggestion:_
```objc
    get_parallel_tensor_dim_indices(ParallelTensorShape const &shape);
```
___
*[`lib/op-attrs/src/op-attrs/parallel_tensor_dim_idx_t.cc` line 10 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6OA9Z28iVkJKyf8WRD:-O6OA9Z28iVkJKyf8WRE:b1zzvec) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/op-attrs/src/op-attrs/parallel_tensor_dim_idx_t.cc#L10)):*
> ```cpp
> namespace FlexFlow {
> 
> ParallelDim get_parallel_dim_at_idx(ParallelTensorShape const &shape,
> ```

Probably better to put these in `parallel_tensor_shape.h` instead (at least to me that's where I'd go look for them if I wanted to find them, lmk if you disagree)
___
*[`lib/pcg/include/pcg/device_coordinates.struct.toml` line 2 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O3ZBx3VTb8dVXrQ55:-O6O3ZBx3VTb8dVXrQ56:bfl3ctj) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/pcg/include/pcg/device_coordinates.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "DeviceCoordinates"
> ```

Makes reasoning about plurality in variable names easier :slightly_smi [...]

2024-09-11 18:53 UTC, wmdi submitted a review, later dismissed
> Reviewed 19 of 41 files at r1, 5 of 24 files at r2, 34 of 41 files at r4, 17 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: all files reviewed, 31 unresolved discussions (waiting on @Marsella8)



<!-- Sent from Reviewable.io -->

2024-09-13 21:37 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 43 of 89 files reviewed, 30 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 44 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O7gAm2IZyo9wT0RWY:-O6h8ADO6wcmgrsIEdDL:b8822u5) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/src/compiler/allowed_machine_views.cc#L44)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Implement or mark as `NOT_IMPLEMENTED()`
</blockquote></details>

implemented
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line  at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O7YaTBdYUswMCZ6fW:-O6h8Cig7yYYaADmqKR_:b-u2jg5m) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/test/src/allowed_machine_views.cc#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What's happening with this?
</blockquote></details>

now re-enabled
___
*[`lib/compiler/test/src/machine_view_to_tensor_mapping.cc` line 12 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O8PuR8sCdAOkUKmnH:-O6h8MWE1yzP50zy6pmb:blbprm9) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/test/src/machine_view_to_tensor_mapping.cc#L12)):*
> ```cpp
>   TEST_CASE("get_all_machine_view_to_tensor_mappings") {
>     ParallelTensorShape shape = ParallelTensorShape{
>         ParallelTensorDims{
> ```

added, throws an error  in this case (since it means that the machine view was generated for another tensor)
___
*[`lib/compiler/test/src/machine_view_to_tensor_mapping.cc` line 26 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O8DRdBCtnDOvcACyw:-O6h8u626Pg9P0gvoX-V:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/test/src/machine_view_to_tensor_mapping.cc#L26)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

For consistency
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/machine_view_to_tensor_mapping.cc` line 33 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O8A5308q2ma_8nDP_:-O6h8ulS296njPGiDMFo:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/test/src/machine_view_to_tensor_mapping.cc#L33)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

For consistency
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/machine_view_to_tensor_mapping.cc` line 37 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O8hsD6WuF6XY5J8_q:-O6h9OQF0yYg0xyNcUgw:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/test/src/machine_view_to_tensor_mapping.cc#L37)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might make this a bit more readable.
</blockquote></details>

Done.
___
*[`lib/local-execution/test/src/test_local_cost_estimator.cc` line 69 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O9cyS4Qci8wdZVCRn:-O6hA_Im752m0GZZ50Da:bxhrqll) ([raw file](https://github.com/flexflow/FlexFlow/blob/5e1f349215294ae312ccac9f2891aecacaf95e39/lib/local-execution/test/src/test_local_cost_estimator.cc#L69)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I kinda like the clarify of having the GPU types in here--is there a reason this overload was removed? If you prefer to not wrap the argument types, it would be nice to force the `DeviceType` to be passed explicitly so there's no ambiguity (yes we're pretty much always going to be using GPU ids, but as long as CPU ids are an option I'd rather it be 100% clear which one is being constructed).

Another option would be to rename this to `make_1d_gpu_machine_view` if you like that better
</blockquote></details>

Removed the default GPU type. Before the interface was different since the start of the `MachineView` was a `device_id_t`, which implictly stored the device type. Now the start is a devicetype-less n-dimensional point, and thus the device type is stored separately in machineview as a separate attribute (lucklily ends up being a lot cleaner than the previous implementation)
___
*[`lib/op-attrs/include/op-attrs/parallel_tensor_dim_idx_t.h` line 13 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O5FFY2Ui0DsK-O4Ty:-O6hBjhCEjbcwZ11P5cN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/op-attrs/include/op-attrs/parallel_tensor_dim_idx_t.h#L13)):*
> ```objc
> 
> std::unordered_set<parallel_tensor_dim_idx_t>
>     get_parallel_tensor_indices(ParallelTensorShape const &shape);
> ```

Done.
___
*[`lib/op-attrs/src/op-attrs/parallel_tensor_dim_idx_t.cc` line 10 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6OA9Z28iVkJKyf8WRD:-O6hBoNU0We96dkYpzzD:b-atlni1) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/op-attrs/src/op-attrs/parallel_tensor_dim_idx_t.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably better to put these in `parallel_tensor_shape.h` instead (at least to me that's where I'd go look for them if I wanted to find them, lmk if you disagree)
</blockquote></details>

I think the original rationale we agreed on is that we'd put them here since we weren't sure whether `parallel_tensor_dim_idx_t` would be used more widely. If you think that this will be used for indexing `ParallelTensorShape` throughout the codebase, I'll move it.
___
*[`lib/pcg/include/pcg/machine_specification_dimension.enum.toml` line 11 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O3Hbr2BF1a_XathaA:-O6hDWGY9g-MCOK8JSCl:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/pcg/include/pcg/machine_specification_dimension.enum.toml#L11)):*
> ```TOML
> 
> [[values]]
> name = "INTER"
> ```

Done.
___
*[`lib/pcg/include/pcg/machine_specification_dimension.enum.toml` line 14 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O3Jdm4FpIwfZmhZOr:-O6hDWV3DeqDopCt_zni:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/pcg/include/pcg/machine_specification_dimension.enum.toml#L14)):*
> ```TOML
> 
> [[values]]
> name = "INTRA"
> ```

Done.
___
*[`lib/pcg/include/pcg/machine_view_projection.struct.toml` line 7 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O4COU6CS0J5MGUDNN:-O6hDbu4DBzMjSBhAh_-:bf2ax25) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/pcg/include/pcg/machine_view_projection.struct.toml#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Any reason no json serialization? I'm not seeing anything here that's obviously not serializable, but I could totally be missing something
</blockquote></details>

added json serialization
___
*[`lib/pcg/include/pcg/machine_view_projection.struct.toml` line 18 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O44lNEb2DF6Hs9PIb:-O6hDz3r5VzOaivSdA63:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/pcg/include/pcg/machine_view_projection.struct.toml#L18)):*
> ```TOML
>   "utils/hash/unordered_map.h",
>   "utils/fmt/unordered_map.h",
> ]
> ```

Done.
___
*[`lib/pcg/include/pcg/machine_view_projection.struct.toml` line 21 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6O4QPSEaCvg4_B1FhI:-O6hE839EE4rROh1zwtv:b-896fix) ([raw file](https://gi [...]

2024-10-04 22:02 UTC, lockshaw requested changes
> Reviewed 27 of 46 files at r7, 29 of 34 files at r8, 1 of 21 files at r9.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 72 of 96 files reviewed, 30 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/compiler/include/compiler/allowed_machine_views.h` line 15 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OO7WD4bwVsE76qJap:-O8OO7WD4bwVsE76qJaq:b-drp1mk) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/compiler/include/compiler/allowed_machine_views.h#L15)):*
> ```objc
> 
> bool is_valid_machine_view(MachineView const &mv,
>                            TaskSpaceOperator const &task);
> ```

These two overloads seem nontrivially different(?), so giving them different (and clearer) names might help



_Code quote:_
```objc
bool is_valid_machine_view(MachineView const &mv,
                           TaskSpaceOperator const &task,
                           MachineSpecification const &ms);

bool is_valid_machine_view(MachineView const &mv,
                           TaskSpaceOperator const &task);
```
___
*[`lib/local-execution/test/src/test_local_cost_estimator.cc` line 11 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Nxy5D8fgbrrYdAKeR:-O8Nxy5D8fgbrrYdAKeS:b5ys57j) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/local-execution/test/src/test_local_cost_estimator.cc#L11)):*
> ```cpp
> 
> // TEST_SUITE(FF_CUDA_TEST_SUITE) {
> //   TEST_CASE("Local Cost Estimator") {
> ```

What's going on here?
___
*[`lib/op-attrs/src/op-attrs/parallel_tensor_dim_idx_t.cc` line 10 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6OA9Z28iVkJKyf8WRD:-O6hLXLn9-nqB7D3cdrP:b-ogkm58) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/op-attrs/src/op-attrs/parallel_tensor_dim_idx_t.cc#L10)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

I think the original rationale we agreed on is that we'd put them here since we weren't sure whether `parallel_tensor_dim_idx_t` would be used more widely. If you think that this will be used for indexing `ParallelTensorShape` throughout the codebase, I'll move it.
</blockquote></details>

I don't know how widely `parallel_tensor_dim_idx_t` will be used, but it's such an obvious thing to have conceptually that I think it makes sense to integrate into `parallel_tensor_shape.h`, etc.
___
*[`lib/pcg/include/pcg/machine_specification.h` line 19 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OLuNv2riNtFtrgZpU:-O8OLuNv2riNtFtrgZpV:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/machine_specification.h#L19)):*
> ```objc
> 
> bool is_valid_machine_space_coordinates(MachineSpecification const &ms,
>                                         MachineSpaceCoordinate const &coord);
> ```





_Suggestion:_
```objc
bool is_valid_machine_space_coordinate(MachineSpecification const &ms,
                                        MachineSpaceCoordinate const &coord);
```
___
*[`lib/pcg/include/pcg/machine_view.struct.toml` line 29 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OML2v2JuyCgW9epxu:-O8OML2v2JuyCgW9epxv:bmaztcv) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/machine_view.struct.toml#L29)):*
> ```TOML
> [[fields]]
> name = "projection"
> type = "std::vector<::FlexFlow::MachineSpecificationDimension>"
> ```

Why are these separate `vectors` rather than a single `vector`?
___
*[`lib/pcg/include/pcg/machine_view_dim_idx_t.h` line 9 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OMRIw9-7M4Ip-V9G6:-O8OMRIw9-7M4Ip-V9G7:bn517vs) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/machine_view_dim_idx_t.h#L9)):*
> ```objc
> namespace FlexFlow {
> 
> std::vector<machine_view_dim_idx_t>
> ```

Why a `vector` here?
___
*[`lib/pcg/include/pcg/task_space_operator.h` line 12 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OMamj3qoRbFop9Hh4:-O8OMamj3qoRbFop9Hh5:bplqtmu) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/task_space_operator.h#L12)):*
> ```objc
> 
> std::unordered_set<TaskSpaceCoordinate>
>     get_fragment_coordinates(TaskSpaceOperator const &task);
> ```

Why not just `get_task_space_coordinates`?
___
*[`lib/pcg/include/pcg/task_space_operator.h` line 15 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ON49x1p69WKsx9TEa:-O8ON49yB0-2n_zvfrvM:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/task_space_operator.h#L15)):*
> ```objc
> 
> TaskSpaceCoordinate
>     get_maximum_fragment_coordinate(TaskSpaceOperator const &task);
> ```





_Suggestion:_
```objc
   get_task_space_maximum_coordinate(TaskSpaceOperator const &task);
```
___
*[`lib/pcg/include/pcg/task_space_operator.h` line 18 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OMtK8-wLnKRTA5Xdo:-O8OMtK92OPC1q8VFQui:b-qbgtvu) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/task_space_operator.h#L18)):*
> ```objc
> 
> size_t num_dims(TaskSpaceOperator const &task);
> size_t num_fragments(TaskSpaceOperator const &task);
> ```

Clearer and doesn't require new terminology (i.e., "fragment")--not that I mind new terminology when necessary, just don't think it's necessary here



_Suggestion:_
```objc
size_t num_tasks(TaskSpaceOperator const &task);
```
___
*[`lib/pcg/src/pcg/delete.c` line 0 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ONVVR4y6yXHjn-A7G:-O8ONVVR4y6yXHjn-A7H:b5ys57j) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/src/pcg/delete.c#L0)):*
What's going on here?
___
*[`lib/pcg/src/pcg/machine_specification.cc` line 43 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ONgLV2PkWmtWA2HNJ:-O8ONgLV2PkWmtWA2HNK:b-g5pwal) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/src/pcg/machine_specification.cc#L43)):*
> ```cpp
> device_id_t get_device_id(MachineSpecification const &ms,
>                           MachineSpaceCoordinate const &coord) {
>   assert(is_valid_machine_space_coordinates(ms, coord));
> ```

Might be better to throw an exception so that the out-of-bounds case can be tested? We can't really test that an `assert` is fired



_Code quote:_
```cpp
  assert(is_valid_machine_space_coordinates(ms, coord));
```
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 35 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OTiOZ98CZSZtDJZdg:-O8OTiOZ98CZSZtDJZdh:b4vj1px) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/test/src/pcg/machine_view.cc#L35)):*
> ```cpp
> 
>       MachineSpecification ms = MachineSpecification{
>           1, 6, 6, 0, 0}; // Single node with 6 GPUs (0,1,2,3,4,5)
> ```

Add argument name comments?



_Code quote:_
```cpp
      MachineSpecification ms = MachineSpecification{
          1, 6, 6, 0, 0}; // Single node with 6 GPUs (0,1,2,3,4,5)
```
___
*[`lib/utils/include/utils/containers/get_all_permutations.h` line 105 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Nzy1Z3QXJLKdmyqMo:-O8Nzy1Z3QXJLKdmyqMp:bbzec1c) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/utils/include/utils/containers/get_all_permutations.h#L105)):*
> ```objc
> 
> template <typename T>
> struct permutations_with_repetition_container {
> ```

I'd move this to a separate `get_all_permutations_with_repetitions.h` file unless there's a strong reason it should be here



_Co [...]

2024-10-05 01:26 UTC, Marsella8 reviewed
> Reviewed 1 of 21 files at r9.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 73 of 96 files reviewed, 30 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/include/compiler/allowed_machine_views.h` line 15 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OO7WD4bwVsE76qJap:-O8OqR080i1_0vRYD1Z8:b-pyuv2f) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/compiler/include/compiler/allowed_machine_views.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

These two overloads seem nontrivially different(?), so giving them different (and clearer) names might help
</blockquote></details>

second one was redundant.
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 67 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6OFa7r6jiQyu-oVCKg:-O8PAsiA7hdg7iBbXpyg:b-fvdzxz) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/src/compiler/allowed_machine_views.cc#L67)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can any of this get pulled out into separate functions that make logical sense by themselves? Each statement is okay to read but the sheer number of statements is a bit intense and doesn't provide a lot of walking the reader through. If it really is this complicated that's fine (there are places where stuff just fundamentally needs a bunch of code that can't get decomposed), but I'd like to be convinced of that :slightly_smiling_face:
</blockquote></details>

I've tried to split it up a bit more, but it's probably not enough. Not super sure how to express the `candidate_strides` computation more cleanly otherwise.
___
*[`lib/local-execution/test/src/test_local_cost_estimator.cc` line 11 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Nxy5D8fgbrrYdAKeR:-O8OrxS00F-Viim0bBFQ:b-wloidr) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/local-execution/test/src/test_local_cost_estimator.cc#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What's going on here?
</blockquote></details>

the interface for `MachineView` has changed so there is not really an equivalent for `make_1d_machine_view` anymore.
It would have to be something like a `OperatorTaskSpace` which encodes the number of points (so degree of the only dimension) and then a `MachineView` which tells us the stride and the StartCoordinate within the MachineSpecification space.
___
*[`lib/op-attrs/src/op-attrs/parallel_tensor_dim_idx_t.cc` line 10 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6OA9Z28iVkJKyf8WRD:-O8Ot_qRC7tGagH6q3yZ:b-tuv8x8) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/op-attrs/src/op-attrs/parallel_tensor_dim_idx_t.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't know how widely `parallel_tensor_dim_idx_t` will be used, but it's such an obvious thing to have conceptually that I think it makes sense to integrate into `parallel_tensor_shape.h`, etc.
</blockquote></details>

Done. note that since we don't have the bijective mapping stuff anymore, `parallel_tensor_dim_idx` is not needed anymore, but I've moved it to 'parallel_tensor_shape.cc` for future use.
___
*[`lib/pcg/include/pcg/machine_specification.h` line 19 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OLuNv2riNtFtrgZpU:-O8OvLkiEqS5NVP3HpD6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/machine_specification.h#L19)):*
> ```objc
> 
> bool is_valid_machine_space_coordinates(MachineSpecification const &ms,
>                                         MachineSpaceCoordinate const &coord);
> ```

Done.
___
*[`lib/pcg/include/pcg/machine_view.struct.toml` line 29 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OML2v2JuyCgW9epxu:-O8P-DF18XnVg9ATrX-z:b-n5kore) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/machine_view.struct.toml#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why are these separate `vectors` rather than a single `vector`?
</blockquote></details>

we can have them as a single vector of pairs (or some custom other data type) but i think it would make it a bit more clunky to iterate over either vector. I can change it if you think it's preferrable.
___
*[`lib/pcg/include/pcg/machine_view_dim_idx_t.h` line 9 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OMRIw9-7M4Ip-V9G6:-O8Ovxcu3Vp4IhkvkgvS:b-5i0pow) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/machine_view_dim_idx_t.h#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why a `vector` here?
</blockquote></details>

old residue from the previous interface, now it's deleted
___
*[`lib/pcg/include/pcg/task_space_operator.h` line 12 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OMamj3qoRbFop9Hh4:-O8P0KhJ1UN_GORhAbf-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/task_space_operator.h#L12)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not just `get_task_space_coordinates`?
</blockquote></details>

Done.
___
*[`lib/pcg/include/pcg/task_space_operator.h` line 15 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ON49x1p69WKsx9TEa:-O8P0VxY3rWOo0tUhMNK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/task_space_operator.h#L15)):*
> ```objc
> 
> TaskSpaceCoordinate
>     get_maximum_fragment_coordinate(TaskSpaceOperator const &task);
> ```

Done.
___
*[`lib/pcg/include/pcg/task_space_operator.h` line 18 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OMtK8-wLnKRTA5Xdo:-O8P0cWUAV0SZ8ZQ11-n:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/task_space_operator.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Clearer and doesn't require new terminology (i.e., "fragment")--not that I mind new terminology when necessary, just don't think it's necessary here
</blockquote></details>

Done.
___
*[`lib/pcg/src/pcg/delete.c` line  at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ONVVR4y6yXHjn-A7G:-O8OwE5ECl_c_pncGOcB:b-k6nu07) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/src/pcg/delete.c#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What's going on here?
</blockquote></details>

sorry old file where I dumped some stuff, now deleted
___
*[`lib/pcg/src/pcg/machine_specification.cc` line 43 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ONgLV2PkWmtWA2HNJ:-O8P4iGs3OtNDHTXYvls:b-u57dvh) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/src/pcg/machine_specification.cc#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be better to throw an exception so that the out-of-bounds case can be tested? We can't really test that an `assert` is fired
</blockquote></details>

Done + added some tests
___
*[`lib/pcg/src/pcg/machine_view.cc` line 47 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6OCmP-0PfaOX4Y_8Bz:-O8PEch12Nkg4LyHAdKI:b-ar08y0) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3 [...]

2024-10-05 04:30 UTC, lockshaw requested changes
> Reviewed 9 of 21 files at r9, 34 of 36 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 99 of 101 files reviewed, 38 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 18 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PnBhBDhapnJGKFbCp:-O8PnBhBDhapnJGKFbCq:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L18)):*
> ```cpp
>     SUBCASE("1 degree of parallelism") {
> 
>       MachineSpecification ms = MachineSpecification{1, 5, 5, 0, 0};
> ```





_Suggestion:_
```cpp
      MachineSpecification ms = MachineSpecification{
        /*num_nodes=*/1, 
        /*num_cpus_per_node=*/5, 
        /*num_gpus_per_node=*/5, 
        /*inter_node_bandwidth=*/0, 
        /*intra_node_bandwidth=*/0,
      };
```
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 24 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PsIet-AA7dFtw_alS:-O8PsIet-AA7dFtw_alT:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L24)):*
> ```cpp
>           MachineView{{{stride_t{1}}},
>                       {{MachineSpecificationDimension::INTRA_NODE}},
>                       MachineSpaceCoordinate{0, 0, DeviceType::GPU}},
> ```





_Suggestion:_
```cpp
                      MachineSpaceCoordinate{
                        /*node=idx=*/0, 
                        /*device_idx=*/0, 
                        DeviceType::GPU,
                      }},
```
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 45 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PsfQF1j9Jn8Hd-PyM:-O8PsfQF1j9Jn8Hd-PyN:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L45)):*
> ```cpp
>     SUBCASE("2 degrees of parallelism") {
> 
>       MachineSpecification ms = MachineSpecification{3, 3, 3, 0, 0};
> ```





_Suggestion:_
```cpp
      MachineSpecification ms = MachineSpecification{
        /*num_nodes=*/3, 
        /*num_cpus_per_node=*/3, 
        /*num_gpus_per_node=*/3, 
        /*inter_node_bandwidth=*/0, 
        /*intra_node_bandwidth=*/0,
      };
```
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 48 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PswgO1ixV_WG1hU1s:-O8PswgO1ixV_WG1hU1t:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L48)):*
> ```cpp
>       OperatorTaskSpace task = OperatorTaskSpace{{2, 3}};
> 
>       auto make_2d_views = [&](int start_x,
> ```





_Suggestion:_
```cpp
      auto make_2d_view
```
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 49 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Pt2By--71bCVPqkX2:-O8Pt2By--71bCVPqkX3:b9mx2xl) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L49)):*
> ```cpp
> 
>       auto make_2d_views = [&](int start_x,
>                                int start_y,
> ```

Aren't these in machine space? What does `y` mean in a machine space?



_Code quote:_
```cpp
                               int start_y,
```
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 63 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PtAzS859LPTLE3niY:-O8PtAzS859LPTLE3niZ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L63)):*
> ```cpp
>       auto inter = MachineSpecificationDimension::INTER_NODE;
>       std::unordered_set<MachineView> correct = {
>           make_2d_views(0, 0, /*stride1*/ 1, /*stride2*/ 1, inter, intra),
> ```





_Suggestion:_
```cpp
          make_2d_views(0, 0, /*stride1=*/1, /*stride2=*/1, inter, intra),
```
___
*[`lib/local-execution/test/src/test_local_cost_estimator.cc` line 11 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Nxy5D8fgbrrYdAKeR:-O8PvpPtCPpH78E6nPdJ:b-ptfn92) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/local-execution/test/src/test_local_cost_estimator.cc#L11)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

the interface for `MachineView` has changed so there is not really an equivalent for `make_1d_machine_view` anymore.
It would have to be something like a `OperatorTaskSpace` which encodes the number of points (so degree of the only dimension) and then a `MachineView` which tells us the stride and the StartCoordinate within the MachineSpecification space.
</blockquote></details>

Got it, so we likely need to (at some point) add a primitive in `op-attrs` that lets us take an `UnmappedCostEstimateKey` and return the `OperatorTaskSpace` for the operator?
___
*[`lib/pcg/include/pcg/machine_view.struct.toml` line 29 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OML2v2JuyCgW9epxu:-O8PjktcEhvwvDHltOLV:b-idjjq) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/machine_view.struct.toml#L29)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

we can have them as a single vector of pairs (or some custom other data type) but i think it would make it a bit more clunky to iterate over either vector. I can change it if you think it's preferrable.
</blockquote></details>

I'd go with one vector due to the "make invalid states unrepresentable" reasoning (one vector prevents the two from having different lengths). I'd add a custom well-named (maybe `MachineDimensionStride`? or `StridedMachineDimension`? or even something as basic as `MachineDimensionWithStride`? Feel free to use something else if you can come up with something, I'm not exactly in love with any of the above names) `.struct.toml` datatype to represent the combination of the two
___
*[`lib/pcg/test/src/pcg/machine_specification.cc` line 11 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PkasGCmL9WXqnfNXE:-O8PkasGCmL9WXqnfNXF:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_specification.cc#L11)):*
> ```cpp
>   TEST_CASE("MachineSpecification") {
> 
>     MachineSpecification ms = MachineSpecification{4, 16, 8, 100.0f, 200.0f};
> ```





_Suggestion:_
```cpp
    MachineSpecification ms = MachineSpecification{
      /*num_nodes=*/4, 
      /*num_cpus_per_node=*/16, 
      /*num_gpus_per_node=*/8, 
      /*inter_node_bandwidth=*/100.0f, 
      /*intra_node_bandwidth=*/200.0f,
    };
```
___
*[`lib/pcg/test/src/pcg/machine_specification.cc` line 29 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PkJXM0Q-uphFwhMAB:-O8PkJXM0Q-uphFwhMAC:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_specification.cc#L29)):*
> ```cpp
>       SUBCASE("valid MachineSpaceCoordinate") {
>         MachineSpaceCoordinate coord =
>             MachineSpaceCoordinate{2, 12, DeviceType::CPU};
> ```





_Suggestion:_
```cpp
           MachineSpaceCoordinate{
             /*node_idx=*/2, 
             /*device_idx=*/12, 
             DeviceType::CPU,
           };
```
___
*[`lib/pcg/test/src/pcg/machine_specification.cc` line 35 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Pl62tDMj2NvMPD0Ew:-O8Pl62tDMj2NvMPD0Ex:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_specification.cc#L35)):*
> ```cpp
>         CHECK(correct == result);
>    [...]

2024-10-05 22:58 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 99 of 101 files reviewed, 38 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 18 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PnBhBDhapnJGKFbCp:-O8TRnG0AM8PbHzdBTir:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L18)):*
> ```cpp
>     SUBCASE("1 degree of parallelism") {
> 
>       MachineSpecification ms = MachineSpecification{1, 5, 5, 0, 0};
> ```

Done.
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 24 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PsIet-AA7dFtw_alS:-O8TRmmd96D87H4p8I89:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L24)):*
> ```cpp
>           MachineView{{{stride_t{1}}},
>                       {{MachineSpecificationDimension::INTRA_NODE}},
>                       MachineSpaceCoordinate{0, 0, DeviceType::GPU}},
> ```

Done.
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 45 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PsfQF1j9Jn8Hd-PyM:-O8TRlJj7Y6CNyZK9txJ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L45)):*
> ```cpp
>     SUBCASE("2 degrees of parallelism") {
> 
>       MachineSpecification ms = MachineSpecification{3, 3, 3, 0, 0};
> ```

Done.
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 48 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PswgO1ixV_WG1hU1s:-O8TRkjE2dEhDGvgL2pK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L48)):*
> ```cpp
>       OperatorTaskSpace task = OperatorTaskSpace{{2, 3}};
> 
>       auto make_2d_views = [&](int start_x,
> ```

Done.
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 49 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Pt2By--71bCVPqkX2:-O8TRsCI0Gz1-vBzFLmY:b-tplbw7) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Aren't these in machine space? What does `y` mean in a machine space?
</blockquote></details>

Machine space is the 2D space described by machine specification. (!= Task Space, which is N-dimensional, with N dimension of the parallel tensor). So we have a vector of strides, a vector of dimensions to which to map each dimension of the task, and then a 2D coordinate (start_x, start_y) which is the node and device indices.
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 63 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PtAzS859LPTLE3niY:-O8TRiO8A1YxyxY_mP5o:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L63)):*
> ```cpp
>       auto inter = MachineSpecificationDimension::INTER_NODE;
>       std::unordered_set<MachineView> correct = {
>           make_2d_views(0, 0, /*stride1*/ 1, /*stride2*/ 1, inter, intra),
> ```

Done.
___
*[`lib/local-execution/test/src/test_local_cost_estimator.cc` line 11 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Nxy5D8fgbrrYdAKeR:-O8TSVkXBzTtCI7E2OYg:b-33pmjq) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/local-execution/test/src/test_local_cost_estimator.cc#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Got it, so we likely need to (at some point) add a primitive in `op-attrs` that lets us take an `UnmappedCostEstimateKey` and return the `OperatorTaskSpace` for the operator?
</blockquote></details>

yes pretty much (we don't really need `OperatorTaskSpace` as long as we have a datatype from which we can get a vector of the parallel degrees, but obviously OperatorTaskSpace makes things more clean)
___
*[`lib/pcg/test/src/pcg/machine_specification.cc` line 11 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PkasGCmL9WXqnfNXE:-O8ToOWLBHOUbYznwcA-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_specification.cc#L11)):*
> ```cpp
>   TEST_CASE("MachineSpecification") {
> 
>     MachineSpecification ms = MachineSpecification{4, 16, 8, 100.0f, 200.0f};
> ```

Done.
___
*[`lib/pcg/test/src/pcg/machine_specification.cc` line 29 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PkJXM0Q-uphFwhMAB:-O8ToOxj1GcZlVlmTZcG:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_specification.cc#L29)):*
> ```cpp
>       SUBCASE("valid MachineSpaceCoordinate") {
>         MachineSpaceCoordinate coord =
>             MachineSpaceCoordinate{2, 12, DeviceType::CPU};
> ```

Done.
___
*[`lib/pcg/test/src/pcg/machine_specification.cc` line 35 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Pl62tDMj2NvMPD0Ew:-O8TTV_iBUbMhsuaoz0C:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_specification.cc#L35)):*
> ```cpp
>         CHECK(correct == result);
>       }
>       SUBCASE("invalid MachineSpaceCoordinate") {
> ```

Done.
___
*[`lib/pcg/test/src/pcg/machine_specification.cc` line 37 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Pl0av5shxbiocg3Cs:-O8TU1rn4ifvGfoULSpj:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_specification.cc#L37)):*
> ```cpp
>       SUBCASE("invalid MachineSpaceCoordinate") {
>         MachineSpaceCoordinate coord =
>             MachineSpaceCoordinate{2, 18, DeviceType::CPU};
> ```

Done.
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 38 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PlDjL-LAt4_bG1g0E:-O8TVDX_8EXzXyDqy81d:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_view.cc#L38)):*
> ```cpp
>                                                      /*num_gpus_per_node*/ 6,
>                                                      0,
>                                                      0};
> ```

Done.
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 40 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PuByZ6JGhqLQ8nf6G:-O8TadkF-jIfOU60waLU:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_view.cc#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Didn't we get rid of "fragment"?
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 49 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PuEi35MmPnokwAWlK:-O8Ta7G0ERXTrIP9F7b9:b-2ozzre) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_view.cc#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Come up with better case names. It appears you have three subcases here for the 2d thing, so I'm assuming you're checking the start point and then checking the stepping in each of the two dimensions? 

Actually looks like not as there's only one dim, so I'm not sure why `Fragment 2` is here at all. Try to think about your subcase names as explaining to me why they're they're, not just what they are  [...]

2024-10-05 23:28 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 87 of 102 files reviewed, 38 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/pcg/include/pcg/machine_view.struct.toml` line 29 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8OML2v2JuyCgW9epxu:-O8U-qTl3UxoTiISxDQC:bb7f2mf) ([raw file](https://github.com/flexflow/FlexFlow/blob/21ca265c7a9409f181d33b19e55b033a56cf9f4c/lib/pcg/include/pcg/machine_view.struct.toml#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'd go with one vector due to the "make invalid states unrepresentable" reasoning (one vector prevents the two from having different lengths). I'd add a custom well-named (maybe `MachineDimensionStride`? or `StridedMachineDimension`? or even something as basic as `MachineDimensionWithStride`? Feel free to use something else if you can come up with something, I'm not exactly in love with any of the above names) `.struct.toml` datatype to represent the combination of the two
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-10-08 05:08 UTC, lockshaw requested changes
> Reviewed 13 of 15 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 100 of 102 files reviewed, 7 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 45 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PsfQF1j9Jn8Hd-PyM:-O8eUHzr9x36WJ2Mx7e3:b-hhl4uy) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L45)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't appear to have changed?
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 49 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Pt2By--71bCVPqkX2:-O8eUOWz7XtUrPMvTarF:bnryu6m) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L49)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Machine space is the 2D space described by machine specification. (!= Task Space, which is N-dimensional, with N dimension of the parallel tensor). So we have a vector of strides, a vector of dimensions to which to map each dimension of the task, and then a 2D coordinate (start_x, start_y) which is the node and device indices.
</blockquote></details>

Then why not just call it `start_node_idx` and `start_device_idx`?
___
*[`lib/pcg/test/src/pcg/machine_specification.cc` line 35 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Pl62tDMj2NvMPD0Ew:-O8eUmG0CufJuk00fe4R:bhq98uf) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_specification.cc#L35)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you're missing "out of bounds" in the new name?
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 49 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PuEi35MmPnokwAWlK:-O8eVn9J9dAk7xGF7fr3:b-raf7kz) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_view.cc#L49)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

made a docstring for each case that explains it pretty extensively.
</blockquote></details>

My concern was more that the names weren't really justifying why that point was included for testing, but as it appears that all of the possible points are tested exhaustively I guess this is fine
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 245 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8eW7AWDsBL5vibM3Jx:-O8eW7AWDsBL5vibM3Jy:bs32bil) ([raw file](https://github.com/flexflow/FlexFlow/blob/c1e1c8c9d286058330605b09d821f310cda9a2e7/lib/pcg/test/src/pcg/machine_view.cc#L245)):*
> ```cpp
> 
>         /**
>          * The tasks will thus be distributed like this:
> ```

`proj format` appears to have butchered your nice diagram--there should be a clang-format comment you can insert to disable clang-format for these lines
___
*[`lib/pcg/test/src/pcg/operator_task_space.cc` line 9 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PqbPE7VjNgsDEukpM:-O8eWbyVCCBoDgL67B05:bbdu8dl) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/operator_task_space.cc#L9)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

Returns a single empty coordinate (vacuously makes sense?). Not sure what a zero dimensional TaskSpaceOperator would represent, whether something with no parallelism or a straight up wrong data-type (so something with no parallelism would be a TaskSpaceOperator with 1 or more ones. Let me know what you think is best.
</blockquote></details>

Yeah this is fine, I was mostly just curious and it's a bit nice to have edgecases like this documented


<!-- Sent from Reviewable.io -->

2024-10-09 01:15 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 100 of 102 files reviewed, 7 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 45 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8PsfQF1j9Jn8Hd-PyM:-O8iofPl9YIoVK3oJSX2:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L45)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Doesn't appear to have changed?
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/allowed_machine_views.cc` line 49 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Pt2By--71bCVPqkX2:-O8iopGFEJLVJFpI00CC:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/compiler/test/src/allowed_machine_views.cc#L49)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Then why not just call it `start_node_idx` and `start_device_idx`?
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/pcg/machine_specification.cc` line 35 at r10](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8Pl62tDMj2NvMPD0Ew:-O8ioxim8V-nGneyXwKF:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/52b7a26d07472efe2627b4bebf1baec56b205b5e/lib/pcg/test/src/pcg/machine_specification.cc#L35)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think you're missing "out of bounds" in the new name?
</blockquote></details>

Done.
___
*[`lib/pcg/test/src/pcg/machine_view.cc` line 245 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8eW7AWDsBL5vibM3Jx:-O8io9096Zqyu4onHIFp:b-7ql1td) ([raw file](https://github.com/flexflow/FlexFlow/blob/c1e1c8c9d286058330605b09d821f310cda9a2e7/lib/pcg/test/src/pcg/machine_view.cc#L245)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`proj format` appears to have butchered your nice diagram--there should be a clang-format comment you can insert to disable clang-format for these lines
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2024-10-09 01:43 UTC, lockshaw requested changes
> Reviewed 1 of 15 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: 101 of 102 files reviewed, 9 unresolved discussions (waiting on @Marsella8 and @wmdi)

___
*[`lib/pcg/include/pcg/machine_view_dimension.struct.toml` line 20 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8itkxRD_8Oe7D64gJp:-O8itkxRD_8Oe7D64gJq:b-az4wu3) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/include/pcg/machine_view_dimension.struct.toml#L20)):*
> ```TOML
> [[fields]]
> name = "stride"
> type = "::FlexFlow::stride_t"
> ```

Any particular reason to keep this as a `stride_t` rather than just dropping it to an `int`? Not a big issue, just curious
___
*[`lib/pcg/src/pcg/machine_view.cc` line 33 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ispp-1SxugsOjWM4-:-O8ispp-1SxugsOjWM40:b45h) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L33)):*
> ```cpp
> 
> static std::vector<int>
>     get_projection_indices(MachineView const &mv,
> ```





_Suggestion:_
```cpp
    get_projection_indices_for_dimension(MachineView const &mv,
```
___
*[`lib/pcg/src/pcg/machine_view.cc` line 39 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8irE2--K2TRRA8Fwsi:-O8irE2--K2TRRA8Fwsj:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L39)):*
> ```cpp
>   std::vector<MachineSpecificationDimension> projections = get_projections(mv);
>   for (size_t i = 0; i < projections.size(); ++i) {
>     if (projections[i] == dimension) {
> ```





_Suggestion:_
```cpp
projections.at(i)
```
___
*[`lib/pcg/src/pcg/machine_view.cc` line 44 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8is7ZVB29gdjubJAF6:-O8is7ZW2SJfUegrB3Pk:b45h) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L44)):*
> ```cpp
>   }
>   return projection_indices;
> }
> ```





_Suggestion:_
```cpp
  std::vector<int> projection_indices
    = filter(count(projections.size()),
             [&](int idx) {
               return projections.at(idx) == dimension;
             });

  return projection_indices;
}
```
___
*[`lib/pcg/src/pcg/machine_view.cc` line 46 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iv7-W7UEm-skGIP_q:-O8iv7-W7UEm-skGIP_r:b-l1x8b8) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L46)):*
> ```cpp
> }
> 
> static int compute_index(int start_idx,
> ```

Try to aim for clearer function names even if they're static, especially if they take this number of parameters (in fact, arguably the sheer number of shared parameters imply that this should probably just be a lambda in `get_machine_space_coordinate` as it doesn't really seem to stand alone
___
*[`lib/pcg/src/pcg/machine_view.cc` line 62 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ivJU600e3KXcMZWEd:-O8ivJU600e3KXcMZWEe:b8mcch3) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L62)):*
> ```cpp
>     sizes.push_back(dim_size);
>     coord_points.push_back(coord.raw_coord[i]);
>     strides.push_back(mv_strides[i].unwrapped);
> ```

Code-style wise probably cleaner to generate `sizes`, `coord_points`, and `strides` as three separate `transform` expressions rather than one big combined loop



_Code quote:_
```cpp
  for (int i : projection_indices) {
    int dim_size = task.degrees[i] * mv_strides[i].unwrapped;
    sizes.push_back(dim_size);
    coord_points.push_back(coord.raw_coord[i]);
    strides.push_back(mv_strides[i].unwrapped);
```
___
*[`lib/pcg/src/pcg/machine_view.cc` line 78 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iunDkAe2S1Sg7RkUl:-O8iunDkAe2S1Sg7RkUm:b-3lcb8) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L78)):*
> ```cpp
>                                  MachineView const &mv,
>                                  TaskSpaceCoordinate const &coord,
>                                  MachineSpecification const &ms) {
> ```

What about splitting this into a function that takes a `MachineView` and generates a `DeduplicatedMachineView` (which has all of the strides multiplied so you can't produce redundant points), and then a corresponding function that takes a `DeduplicatedMachineView` which then can do a much simpler computation to find the `MachineSpaceCoordinate`. Thoughts?

Overall one of the best way you can make code more readable is to introduce (sane and conceptually clear) intermediate types, and then break a complicated function that does `A -> D` into `A -> B -> C -> D`



_Code quote:_
```cpp
std::optional<MachineSpaceCoordinate>
    get_machine_space_coordinate(OperatorTaskSpace const &task,
                                 MachineView const &mv,
                                 TaskSpaceCoordinate const &coord,
                                 MachineSpecification const &ms) {
```
___
*[`lib/pcg/src/pcg/machine_view.cc` line 96 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iqnwEAK6X1m9b41Xi:-O8iqnwL3i9HldeLD0Ks:b-vgb1gs) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L96)):*
> ```cpp
>   return ms_coord;
> }
> std::unordered_set<MachineSpaceCoordinate>
> ```

Is it possible that this should be an `std::unordered_multiset`, or is `MachineView` defined such as to make this impossible?
___
*[`lib/pcg/src/pcg/machine_view.cc` line 103 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iwRwf0q16hXdwMJPV:-O8iwRwf0q16hXdwMJPW:b-nj3r2r) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L103)):*
> ```cpp
>   return transform(
>       get_task_space_coordinates(task), [&](TaskSpaceCoordinate const &c) {
>         return get_machine_space_coordinate(task, mv, c, ms).value();
> ```

Try not to abbreviate these variables too much or the code starts to become rather hard to skim as I keep having to chase down definitions unnecessarily



_Suggestion:_
```cpp
       return get_machine_space_coordinate(task, machine_view, coord, machine_spec).value();
```


<!-- Sent from Reviewable.io -->

2024-10-09 01:56 UTC, lockshaw requested changes
> Reviewed 1 of 15 files at r11.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: all files reviewed, 12 unresolved discussions (waiting on @Marsella8)

___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 67 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6OFa7r6jiQyu-oVCKg:-O8ixwb_5RZd1xviACS5:b-dqx1n2) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/src/compiler/allowed_machine_views.cc#L67)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

I've tried to split it up a bit more, but it's probably not enough. Not super sure how to express the `candidate_strides` computation more cleanly otherwise.
</blockquote></details>

No worries, the key thing is that the high-level flow is clear. As long as you name `get_candidate_strides` clearly so I know what it does I can just ignore the details of it and still get a good idea of how the overall code works. Breaking things into separate lambdas, naming things clearly, having solid intermediate types, and having a clear logical flow (generate candidate values, generate an overapproximation of the space, then filter) like you did here is great and much more important than low-level style.
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 27 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iwq0uAK_GF5wPv7xP:-O8iwq0uAK_GF5wPv7xQ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L27)):*
> ```cpp
>                            OperatorTaskSpace const &task,
>                            MachineSpecification const &ms) {
>   std::optional<MachineSpaceCoordinate> maximum_device_coords =
> ```





_Suggestion:_
```cpp
  std::optional<MachineSpaceCoordinate> maximum_device_coord 
```
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 36 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iyzhM0hqKZ2Y-wfT0:-O8iyzhM0hqKZ2Y-wfT1:b-8pw300) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L36)):*
> ```cpp
>  * The returned set includes all valid machine views, and might contain
>  invalid ones. This function should never be used externally (see
>  * `get_allowed_partial_machine_view_mappings` instead). There is no
> ```

Is this the right name?



_Code quote:_
```cpp
`get_allowed_partial_machine_view_mappings
```
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 40 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iyuws-OOtal7au8ZT:-O8iyuws-OOtal7au8ZU:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L40)):*
> ```cpp
>  its possible for all
>  * `MachineView`s to be invalid)
>  */
> ```





_Suggestion:_
```cpp
/* Generates a set of candidate `MachineView`s
 * The returned set includes all valid machine views, and might contain
 * invalid ones. This function should not be used externally (see
 * `get_allowed_partial_machine_view_mappings` instead). There is no
 * guarantee that a non-empty returned set contains a valid machine view (i.e.
 * it's possible for all the returned `MachineView`s to be invalid)
 */
```
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 61 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ixLe5ExnuKSIjbfEv:-O8ixLe5ExnuKSIjbfEw:b-p67ko4) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L61)):*
> ```cpp
>     std::vector<stride_t> single_stride_range =
>         transform(range(1, max_stride_upper_bound + 1),
>                   [](int stride) { return stride_t(stride); });
> ```

for consistency



_Suggestion:_
```cpp
                  [](int stride) { return stride_t{stride}; });
```
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 75 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ixWUe05ciBu6kAIsj:-O8ixWUf29hoxqGszQcM:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L75)):*
> ```cpp
>     std::unordered_set<MachineSpaceCoordinate> result;
>     for (int i : range(ms.num_nodes)) {
>       for (int j : range(get_num_devices_per_node(ms, device_type))) {
> ```





_Suggestion:_
```cpp
    for (int node_idx : range(ms.num_nodes)) {
      for (int device_idx : range(get_num_devices_per_node(ms, device_type))) {
```
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 99 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iyaAH0i_07YT2nTU5:-O8iyaAH0i_07YT2nTU6:b3nryhk) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L99)):*
> ```cpp
>          candidate_starts(machine_spec, device_type)) {
>       for (std::vector<MachineSpecificationDimension> const &proj :
>            candidate_projections(task)) {
> ```

FYI the whole projection vs machine-spec-dim is naming-wise a bit inconsistent and weird. Not a big issue as at least neither term is overloaded to also mean something else (you just have two words for one concept), but it can be a bit confusing at times



_Code quote:_
```cpp
      for (std::vector<MachineSpecificationDimension> const &proj :
           candidate_projections(task)) {
```
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 103 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ixiJt-izhc0UvYl-d:-O8ixiJt-izhc0UvYl-e:bz2ygyu) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L103)):*
> ```cpp
>             transform(zip(strides.raw_strides, proj), [&](auto const &p) {
>               return MachineViewDimension{p.first, p.second};
>             });
> ```

I would add a function to `MachineView` for constructing a `MachineView` from a start and separate lists of `strides` and `projections` and then use it here to simplify this code a bit



_Code quote:_
```cpp
        std::vector<MachineViewDimension> dimensions =
            transform(zip(strides.raw_strides, proj), [&](auto const &p) {
              return MachineViewDimension{p.first, p.second};
            });
```


<!-- Sent from Reviewable.io -->

2024-10-09 05:19 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: all files reviewed, 12 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 67 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O6OFa7r6jiQyu-oVCKg:-O8jUB01EQCKF1JKZlBR:b-v4j9iv) ([raw file](https://github.com/flexflow/FlexFlow/blob/40ab5ef7af7ebe3c052850c1f62f3373125e2aa7/lib/compiler/src/compiler/allowed_machine_views.cc#L67)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

No worries, the key thing is that the high-level flow is clear. As long as you name `get_candidate_strides` clearly so I know what it does I can just ignore the details of it and still get a good idea of how the overall code works. Breaking things into separate lambdas, naming things clearly, having solid intermediate types, and having a clear logical flow (generate candidate values, generate an overapproximation of the space, then filter) like you did here is great and much more important than low-level style.
</blockquote></details>

great tip, will keep it in mind in the future
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 27 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iwq0uAK_GF5wPv7xP:-O8jB8ng8ZWz1Xrgowf-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L27)):*
> ```cpp
>                            OperatorTaskSpace const &task,
>                            MachineSpecification const &ms) {
>   std::optional<MachineSpaceCoordinate> maximum_device_coords =
> ```

Done.
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 36 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iyzhM0hqKZ2Y-wfT0:-O8jCFVPB3JEIbLr5GeF:b-oss53h) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L36)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is this the right name?
</blockquote></details>

changed to the correct one 
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 40 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iyuws-OOtal7au8ZT:-O8jCXka8fND_HbgUuBo:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L40)):*
> ```cpp
>  its possible for all
>  * `MachineView`s to be invalid)
>  */
> ```

Done.
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 75 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ixWUe05ciBu6kAIsj:-O8jCkpb20ov4geh0SXt:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L75)):*
> ```cpp
>     std::unordered_set<MachineSpaceCoordinate> result;
>     for (int i : range(ms.num_nodes)) {
>       for (int j : range(get_num_devices_per_node(ms, device_type))) {
> ```

Done.
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 99 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iyaAH0i_07YT2nTU5:-O8jWWcz4bWOlts9k5N5:b2x61v6) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L99)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

FYI the whole projection vs machine-spec-dim is naming-wise a bit inconsistent and weird. Not a big issue as at least neither term is overloaded to also mean something else (you just have two words for one concept), but it can be a bit confusing at times
</blockquote></details>

agreed, replaced projection since it's not only unclear but a bit of a misnomer, since the operation we are doing is not really projection as much as it is flattening an N-dim space into a 2D one.
___
*[`lib/compiler/src/compiler/allowed_machine_views.cc` line 103 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ixiJt-izhc0UvYl-d:-O8jZ740-_QqiYW9aQt8:bb7f2mf) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/compiler/src/compiler/allowed_machine_views.cc#L103)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I would add a function to `MachineView` for constructing a `MachineView` from a start and separate lists of `strides` and `projections` and then use it here to simplify this code a bit
</blockquote></details>

done
___
*[`lib/pcg/include/pcg/machine_view_dimension.struct.toml` line 20 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8itkxRD_8Oe7D64gJp:-O8jCzeg2bDw0oAZLRYd:b-dy2jc3) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/include/pcg/machine_view_dimension.struct.toml#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Any particular reason to keep this as a `stride_t` rather than just dropping it to an `int`? Not a big issue, just curious
</blockquote></details>

no strong reason / preference, I don't mind it since it makes things a bit more explicit / clear. I can change it if needed
___
*[`lib/pcg/src/pcg/machine_view.cc` line 33 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ispp-1SxugsOjWM4-:-O8jDahK3joI9I94O9zD:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L33)):*
> ```cpp
> 
> static std::vector<int>
>     get_projection_indices(MachineView const &mv,
> ```

Done.
___
*[`lib/pcg/src/pcg/machine_view.cc` line 39 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8irE2--K2TRRA8Fwsi:-O8jDl694sISlrngrAjm:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L39)):*
> ```cpp
>   std::vector<MachineSpecificationDimension> projections = get_projections(mv);
>   for (size_t i = 0; i < projections.size(); ++i) {
>     if (projections[i] == dimension) {
> ```

Done.
___
*[`lib/pcg/src/pcg/machine_view.cc` line 44 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8is7ZVB29gdjubJAF6:-O8jE9u05AYDcECpO696:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L44)):*
> ```cpp
>   }
>   return projection_indices;
> }
> ```

Done.
___
*[`lib/pcg/src/pcg/machine_view.cc` line 46 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iv7-W7UEm-skGIP_q:-O8jZANSCoisf6jU67sp:b9873ga) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Try to aim for clearer function names even if they're static, especially if they take this number of parameters (in fact, arguably the sheer number of shared parameters imply that this should probably just be a lambda in `get_machine_space_coordinate` as it doesn't really seem to stand alone
</blockquote></details>

yeah, put into a lambda, much clearer now
___
*[`lib/pcg/src/pcg/machine_view.cc` line 62 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8ivJU600e3KXcMZWEd:-O8jHkKNDGHb8ceryEIP:bb7f2mf) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L62)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Code-style wise probably cleaner to generate `sizes`, `coord_points`, and `strides` as three separate `transform` expressions rather than one big combined loop
</blockquote></details>

done
___
*[`lib/pcg/src/pcg/machi [...]

2024-10-09 18:33 UTC, lockshaw approved these changes
> Reviewed 7 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marsella8)

___
*[`lib/pcg/include/pcg/start_invariant_machine_view.h` line 39 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8mXqfjEY_u_lvty4cE:-O8mXqfjEY_u_lvty4cF:b6aonxa) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1cd5a2a53fc8240f20b31e1af52b31b1e6a66f4/lib/pcg/include/pcg/start_invariant_machine_view.h#L39)):*
> ```objc
>                                  MachineSpecification const &ms);
> 
> std::unordered_set<MachineSpaceCoordinate>
> ```

Seems a bit odd to return a `MachineSpaceCoordinate` here rather than some other type like `MachineSpaceOffset` or something to represent the fact that `StartInvariantMachineView` doesn't actually have a `start`
___
*[`lib/pcg/src/pcg/machine_view.cc` line 78 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iunDkAe2S1Sg7RkUl:-O8mSogt75hzOB2IPxEo:bmcrvbg) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L78)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

not sure I fully agree, what would `DeduplicatedMachineView` represent exactly (the partial strides /degrees for each dimension)? I think the current logic is decently clear, at least at the top level. Cleaned up a bit, let me know if this is better
</blockquote></details>

My understanding of how `TaskSpaceCoordinate` -> `MachineSpaceCoordinate` works is that for the most part it's a pretty simple calculation: given a machine view, you have `machine_space_coord_x = task_space_coord_a * stride_a + start_x`. The complexity comes in when you start to have multiple task space dimensions projected to the same machine space dimension, so you end up with, e.g., `machine_space_coord_x = task_space_coord_a * stride_a + task_space_coord_b * stride_b + start_x`, and then you have an issue where you can have two non-equal pairs `(task_space_coord_a, task_space_coord_b)` and `(task_space_coord_a', task_space_coord_b')` such that `task_space_coord_a * stride_a + task_space_coord_b * stride_b == task_space_coord_a' * stride_a + task_space_coord_b' * stride_b`, leading to multiple `TaskSpaceCoordinate`s mapping to the same device. Correct me if I'm wrong, but the way we fix this is by introducing an order within the task space dimensions that map to a single machine space dimension (e.g., `[a, b]` here), and then we change the computation to `task_space_coord_a * stride_a * (task_space_size_b * stride_b) + task_space_coord_b * stride_b + start_x`, which makes the mapping one-to-one. As the logic for computing this is more complex, one way to simplify things would be to argue that `stride_a * task_space_size_b * stride_b` simply functions as a "normalized"/"deduplicated" stride `stride_a'`, and then you could divide the computation into `MachineView` -> `NormalizedMachineView`, and then use the simpler computation for transforming a `TaskSpaceCoordinate` into a MachineSpaceCoordinate` through a `NormalizedMachineView` 

The current code is reasonably nice so this isn't critical, just throwing it out there as a potential improvement as I don't think you'll be able to get the existing code much nicer via only style changes


<!-- Sent from Reviewable.io -->

2024-10-09 22:39 UTC, Marsella8 reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marsella8)

___
*[`lib/pcg/include/pcg/start_invariant_machine_view.h` line 39 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8mXqfjEY_u_lvty4cE:-O8nP5n69_6PZoZULMw3:b-yk35ac) ([raw file](https://github.com/flexflow/FlexFlow/blob/e1cd5a2a53fc8240f20b31e1af52b31b1e6a66f4/lib/pcg/include/pcg/start_invariant_machine_view.h#L39)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Seems a bit odd to return a `MachineSpaceCoordinate` here rather than some other type like `MachineSpaceOffset` or something to represent the fact that `StartInvariantMachineView` doesn't actually have a `start`
</blockquote></details>

yeah agree, added new dtgen type.
___
*[`lib/pcg/src/pcg/machine_view.cc` line 78 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1458#-O8iunDkAe2S1Sg7RkUl:-O8nPTgnBT7q3ZtoB5qp:b-t1da1y) ([raw file](https://github.com/flexflow/FlexFlow/blob/5cc2a2f1fcf7610b9366ee3652d4806ed090f326/lib/pcg/src/pcg/machine_view.cc#L78)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

My understanding of how `TaskSpaceCoordinate` -> `MachineSpaceCoordinate` works is that for the most part it's a pretty simple calculation: given a machine view, you have `machine_space_coord_x = task_space_coord_a * stride_a + start_x`. The complexity comes in when you start to have multiple task space dimensions projected to the same machine space dimension, so you end up with, e.g., `machine_space_coord_x = task_space_coord_a * stride_a + task_space_coord_b * stride_b + start_x`, and then you have an issue where you can have two non-equal pairs `(task_space_coord_a, task_space_coord_b)` and `(task_space_coord_a', task_space_coord_b')` such that `task_space_coord_a * stride_a + task_space_coord_b * stride_b == task_space_coord_a' * stride_a + task_space_coord_b' * stride_b`, leading to multiple `TaskSpaceCoordinate`s mapping to the same device. Correct me if I'm wrong, but the way we fix this is by introducing an order within the task space dimensions that map to a single machine space dimension (e.g., `[a, b]` here), and then we change the computation to `task_space_coord_a * stride_a * (task_space_size_b * stride_b) + task_space_coord_b * stride_b + start_x`, which makes the mapping one-to-one. As the logic for computing this is more complex, one way to simplify things would be to argue that `stride_a * task_space_size_b * stride_b` simply functions as a "normalized"/"deduplicated" stride `stride_a'`, and then you could divide the computation into `MachineView` -> `NormalizedMachineView`, and then use the simpler computation for transforming a `TaskSpaceCoordinate` into a MachineSpaceCoordinate` through a `NormalizedMachineView` 

The current code is reasonably nice so this isn't critical, just throwing it out there as a potential improvement as I don't think you'll be able to get the existing code much nicer via only style changes
</blockquote></details>

aah ok got it know thanks! I think I'll leave it like this for now, but will take this into consideration when going over that CPU kernel tests PR you tagged me in to see if it makes sense to have a centralized set of functions for working with these indices transformation.


<!-- Sent from Reviewable.io -->

2024-10-09 23:11 UTC, lockshaw approved these changes
> Reviewed 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1458)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marsella8)



<!-- Sent from Reviewable.io -->

2024-10-09 23:15 UTC, lockshaw approved these changes

2024-10-09 23:53 UTC, merged