Unity device mapping algorithm
flexflow/FlexFlow pull request #1459
Opened 2024-08-07 20:06 UTC by wmdi

**Description of changes:**
This PR recovers the device mapping algorithm (the DP-based algorithm) used in Unity.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-08-08 04:47 UTC, lockshaw requested changes
Can you add `compiler-tests` to CI and `proj`? 

Also, overall this code could use a bit of simplifying and readability-improving. For a lot of the cases where you're unwrapping types consider just defining equivalent functions for those types, which would help simplify things. Overall, more small functions with better names would probably help over the current large functions which can be a bit hard to actually read through

> Reviewed 7 of 15 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-:-O3kIiq1-7nM6JDgrGTw:bxysv1x)* status: all files reviewed, 14 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/graph_optimize_result.struct.toml` line 7 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3k5bZo5jVZE9FwTm8m:-O3k5bZo5jVZE9FwTm8n:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/include/compiler/graph_optimize_result.struct.toml#L7)):*
> ```TOML
> includes = [ 
>   "compiler/machine_mapping.h"
> ]
> ```





_Suggestion:_
```TOML
includes = [
  "compiler/machine_mapping.dtg.h",
  "pcg/parallel_computation_graph/parallel_computation_graph.dtg.h",
]
```
___
*[`lib/compiler/include/compiler/graph_optimize_state.h` line 13 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kHocw1woA6l3fcwFD:-O3kHocw1woA6l3fcwFE:b-u7hdr6) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/include/compiler/graph_optimize_state.h#L13)):*
> ```objc
>   float runtime;
> 
>   bool operator==(GraphOptimizeState const &other) const;
> ```

`GraphOptimizeState::operator==` should probably have tests
___
*[`lib/compiler/include/compiler/unity_algorithm.h` line 13 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kHyTY95y_6jYLnhCz:-O3kHyTY95y_6jYLnhD-:bp5g3n7) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/include/compiler/unity_algorithm.h#L13)):*
> ```objc
> namespace FlexFlow {
> 
> struct OptimizerConfig {
> ```

Move over to `dtgen` so it's printable, equality-checkable, hashable, etc.?
___
*[`lib/compiler/src/graph_optimize_state.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kIAym5Yc4ECMISkBW:-O3kIAym5Yc4ECMISkBX:b3v9kpr) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/graph_optimize_state.cc#L6)):*
> ```cpp
> 
> bool GraphOptimizeState::operator==(GraphOptimizeState const &other) const {
>   auto layers1 = topological_ordering(graph_optimize_result.pcg);
> ```

I'm not sure `topological_ordering` is the best thing to rely on here. This seems like a graph-level comparison function, so it might be better to figure out what the semantics are and then it can get added to `graph` so you only have to use it here?
___
*[`lib/compiler/src/graph_optimize_state.cc` line 30 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kI3_U9c85se-5vD6J:-O3kI3_U9c85se-5vD6K:b3qqre7) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/graph_optimize_state.cc#L30)):*
> ```cpp
>   return !(*this == other);
> }
> ```

Where is `operator<`? I think it was declared?
___
*[`lib/compiler/src/machine_mapping.cc` line 159 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3k7EbFEVCOejcvjQ2i:-O3k7EbFEVCOejcvjQ2j:b-dqba4v) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L159)):*
> ```cpp
>         cached_subgraph_costs(cached_subgraph_costs) {}
> 
>   ParallelComputationGraph pcg;
> ```

Why move the PCG from `OptimalCostFunctor` to `MachineMappingSearcher`?
___
*[`lib/compiler/src/machine_mapping.cc` line 166 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kEpuIBJE4dSnV3Atp:-O3kEpuJBRP4-GOYOSRa:b421dna) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L166)):*
> ```cpp
>   OptimalCostCache &cached_subgraph_costs;
> 
>   struct OptimalCostFunctor {
> ```

Why do we have this separate `OptimalCostFunctor`? 
___
*[`lib/compiler/src/machine_mapping.cc` line 219 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kGaSh7CZG-NOvXfCn:-O3kGaSh7CZG-NOvXfCo:b-g5lta) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L219)):*
> ```cpp
> 
>     std::unordered_set<DataflowOutput> split_outputs;
>     for (auto const &[value, _] :
> ```

Might be simpler with `transform`? Also the `assert` isn't really necessary, `get` will already throw if you perform an invalid access
___
*[`lib/compiler/src/machine_mapping.cc` line 287 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kFbh_9r-qzuRM36sm:-O3kFbh_9r-qzuRM36sn:b-4ec72h) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L287)):*
> ```cpp
>           optimal_result,
>           OptimalCostResult::parallel_combine(
>               std::visit(OptimalCostFunctor(
> ```

Why not just pull out a separate function that does `std::visit(OptimalCostFunctor(...))` rather than repeat it each time?
___
*[`lib/compiler/src/machine_mapping.cc` line 320 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kFSpPDCXtyhVbVHun:-O3kFSpPDCXtyhVbVHuo:b-wgmuzl) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L320)):*
> ```cpp
>            enumerate_machine_views({node}, resource)) {
>         MachineMapping mv_map{{{node, node_machine_views.at(node)}}};
>         std::unordered_map<OpenDataflowValue, MachineView> machine_views =
> ```

Might be cleaner using `merge_maps` and `generate_map`?
___
*[`lib/compiler/src/machine_mapping.cc` line 334 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kEwux25i_ZYhuJIBH:-O3kEwux25i_ZYhuJIBI:b-yzcmlm) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L334)):*
> ```cpp
> 
>   std::vector<std::unordered_map<Node, MachineView>>
>       enumerate_machine_views(std::unordered_set<Node> const &nodes,
> ```

Not entirely clear what these do? Can you rename them to something a bit more descriptive?
___
*[`lib/compiler/test/src/test_optimal_cost.cc` line 9 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kH5p53XHUvP-ThaLH:-O3kH5p53XHUvP-ThaLI:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/test/src/test_optimal_cost.cc#L9)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("optimal_cost_0") {
> ```





_Suggestion:_
```cpp
  TEST_CASE("optimal_cost does not crash on minimal inputs") {
```
___
*[`lib/substitutions/include/substitutions/sub_parallel_computation_graph.h` line 25 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kHHkvDFx4r9_OySAF:-O3kHHkvDFx4r9_OySAG:bgg20s3) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/substitutions/include/substitutions/sub_parallel_computation_graph.h#L25)):*
> ```objc
> 
> SubParallelComputationGraph
>     sub_pcg_from_partial_pcg(ParallelComputationGraph const &,
> ```

Is this just `get_subgraph` for `PCGs`?
___
*[`lib/substitutions/src/substitutions/sub_parallel_computation_graph.cc` line 61 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kHbko4Uh_vL2aNZn2:-O3kHbko4Uh_vL2aNZn3:b-uewm6p) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/substitutions/src/substitutions/sub_parallel_computation_graph.cc#L61)):*
> ```cpp
>                              std::unordered_set<Node [...]

2024-08-18 04:39 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: all files reviewed, 14 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/graph_optimize_result.struct.toml` line 7 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3k5bZo5jVZE9FwTm8m:-O4WF4fOD6hUtP-oRFwM:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/include/compiler/graph_optimize_result.struct.toml#L7)):*
> ```TOML
> includes = [ 
>   "compiler/machine_mapping.h"
> ]
> ```

Done.
___
*[`lib/compiler/include/compiler/graph_optimize_state.h` line 13 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kHocw1woA6l3fcwFD:-O4Xrgud1inYQCZlltqQ:bs7wumx) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/include/compiler/graph_optimize_state.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`GraphOptimizeState::operator==` should probably have tests
</blockquote></details>

Done. 
___
*[`lib/compiler/include/compiler/unity_algorithm.h` line 13 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kHyTY95y_6jYLnhCz:-O4YCnTY6t_LV8yi6ULx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/include/compiler/unity_algorithm.h#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move over to `dtgen` so it's printable, equality-checkable, hashable, etc.?
</blockquote></details>

Done.
___
*[`lib/compiler/src/graph_optimize_state.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kIAym5Yc4ECMISkBW:-O4YCqbO924Xe1RoGK3d:b-g7cjqr) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/graph_optimize_state.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm not sure `topological_ordering` is the best thing to rely on here. This seems like a graph-level comparison function, so it might be better to figure out what the semantics are and then it can get added to `graph` so you only have to use it here?
</blockquote></details>

I think I require homomorphism assuming inputs are ordered.
___
*[`lib/compiler/src/machine_mapping.cc` line 159 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3k7EbFEVCOejcvjQ2i:-O4YDCJK8QXGpJq9XNOF:b-uy4kfq) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L159)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why move the PCG from `OptimalCostFunctor` to `MachineMappingSearcher`?
</blockquote></details>

This is to avoid transferring variables that are not changed during DP, i.e., they are 'constants' to the DP, instead of states.
___
*[`lib/compiler/src/machine_mapping.cc` line 166 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kEpuIBJE4dSnV3Atp:-O4YDX8UEzGI6ZeXdDdD:b-v2fbt1) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L166)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why do we have this separate `OptimalCostFunctor`?
</blockquote></details>

To separate DP states with DP constants (environments).
___
*[`lib/compiler/src/machine_mapping.cc` line 219 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kGaSh7CZG-NOvXfCn:-O4YDbVdCMaXoovOxyVA:bgmfhlp) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L219)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be simpler with `transform`? Also the `assert` isn't really necessary, `get` will already throw if you perform an invalid access
</blockquote></details>

I do not find methods to get the set of left/right values of a `bidict`
___
*[`lib/compiler/src/machine_mapping.cc` line 287 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kFbh_9r-qzuRM36sm:-O4YFK4KECu4kPu49yho:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L287)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not just pull out a separate function that does `std::visit(OptimalCostFunctor(...))` rather than repeat it each time?
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 320 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kFSpPDCXtyhVbVHun:-O4YFkW_1XlraMQ1PNiT:b-ribo86) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L320)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be cleaner using `merge_maps` and `generate_map`?
</blockquote></details>

We do not have the utils required for `bidict`
___
*[`lib/compiler/src/machine_mapping.cc` line 334 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kEwux25i_ZYhuJIBH:-O4YGQJ01jEz0IntJhDA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L334)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not entirely clear what these do? Can you rename them to something a bit more descriptive?
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/test_optimal_cost.cc` line 9 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kH5p53XHUvP-ThaLH:-O4YGYi-5fq5QGcRbABK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/test/src/test_optimal_cost.cc#L9)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("optimal_cost_0") {
> ```

Done.
___
*[`lib/substitutions/include/substitutions/sub_parallel_computation_graph.h` line 25 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kHHkvDFx4r9_OySAF:-O4YGjCR3vwNZtctaM6v:b2nhswy) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/substitutions/include/substitutions/sub_parallel_computation_graph.h#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is this just `get_subgraph` for `PCGs`?
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2024-08-22 02:20 UTC, lockshaw requested changes
> Reviewed 7 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: 15 of 17 files reviewed, 9 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/optimal_cost_state.struct.toml` line 20 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4rDPYg8DFHrOegAL_e:-O4rDPYg8DFHrOegAL_f:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/678e9909b089c30e40d096978b3cf7fbf96b755f/lib/compiler/include/compiler/optimal_cost_state.struct.toml#L20)):*
> ```TOML
>   "utils/hash/unordered_map.h",
>   "utils/fmt/unordered_map.h", 
> ]
> ```





_Suggestion:_
```TOML
includes = [
  "utils/graph/serial_parallel/serial_parallel_decomposition.dtg.h",
  "pcg/machine_specification.dtg.h",
  "pcg/machine_view.dtg.h",
  "utils/graph/open_dataflow_graph/open_dataflow_edge.dtg.h",
  "utils/graph/open_dataflow_graph/open_dataflow_value.dtg.h",
]

src_includes = [
  "utils/hash/unordered_map.h",
  "utils/fmt/unordered_map.h",
]
```
___
*[`lib/compiler/src/graph_optimize_state.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kIAym5Yc4ECMISkBW:-O4rrIpQE-41E_gKVmgG:b-khzhqx) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/graph_optimize_state.cc#L6)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I think I require homomorphism assuming inputs are ordered.
</blockquote></details>

Using a hack like this for now is fine, but eventually it would be good to move over to a more principled algorithm implemented in `utils/graph` that doesn't make correctness tradeoffs and more explicitly uses the properties of `DataflowGraph` that you're relying on for efficiency. Until that's implemented let's add a comment in the code that clarifies that this is a hack and links to an issue with the plan for moving this over to something more correct
___
*[`lib/compiler/src/machine_mapping.cc` line 159 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3k7EbFEVCOejcvjQ2i:-O4rrg4g00qGsY6NnVOm:bs2ds3p) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L159)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

This is to avoid transferring variables that are not changed during DP, i.e., they are 'constants' to the DP, instead of states.
</blockquote></details>

As discussed in the Wednesday meeting, it should be possible to remove `OptimalCostFunctor`, especially as we're now on C++17 and can use `overload`

There seem to be two potential designs (either (1) making `optimal_cost` a method on `MachineMappingSearcher`, or (2) making `MachineMappingSearcher` just a wrapper for the global state (probably renamed to something like `DPContext`) and passing that around between top-level functions as a mutable reference, i.e., essentially doing the passing of `this` manually)
___
*[`lib/compiler/src/machine_mapping.cc` line 219 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kGaSh7CZG-NOvXfCn:-O4rsDbrCgYySguNpT7q:b-re1j7q) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L219)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I do not find methods to get the set of left/right values of a `bidict`
</blockquote></details>

See `keys` in `utils/containers/keys.h`
___
*[`lib/compiler/src/machine_mapping.cc` line 320 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kFSpPDCXtyhVbVHun:-O4rsNvI9nSqvu-QT7vu:b1qmima) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L320)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

We do not have the utils required for `bidict`
</blockquote></details>

Not exactly sure the details of simplifying this, but making it more clear what this is doing would be nice (maybe using functions from `utils/containers` or pulling out some pieces into separate named lambdas)
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 8 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4rD7KhDFmzp8dXMk4i:-O4rD7KhDFmzp8dXMk4j:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/678e9909b089c30e40d096978b3cf7fbf96b755f/lib/compiler/test/src/test_graph_optimize_state.cc#L8)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("graph_optimize_state:equality") {
> ```





_Suggestion:_
```cpp
  TEST_CASE("GraphOptimizeState::operator==") {
```


<!-- Sent from Reviewable.io -->

2024-08-22 21:30 UTC, lockshaw requested changes
> Reviewed 2 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: all files reviewed, 13 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/src/graph_optimize_state.cc` line 57 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4vzkuQCtTzxmIsR26c:-O4vzkuQCtTzxmIsR26d:b-hcwhx3) ([raw file](https://github.com/flexflow/FlexFlow/blob/678e9909b089c30e40d096978b3cf7fbf96b755f/lib/compiler/src/graph_optimize_state.cc#L57)):*
> ```cpp
> namespace std {
> 
> size_t hash<::FlexFlow::GraphOptimizeState>::operator()(
> ```

See https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kIAym5Yc4ECMISkBW. Eventually it might be good to use a proper graph hash like https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.graph_hashing.weisfeiler_lehman_graph_hash.html#networkx.algorithms.graph_hashing.weisfeiler_lehman_graph_hash
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 44 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sFtnyABZ_-JhKG7s6:-O4sFtnz5AESGtjVMoBQ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/678e9909b089c30e40d096978b3cf7fbf96b755f/lib/compiler/test/src/test_graph_optimize_state.cc#L44)):*
> ```cpp
>                                                   "dense1");
> 
>     ParallelComputationGraph pcg = builder.pcg;
> ```





_Suggestion:_
```cpp
    ParallelComputationGraph pcg1 = [&] {
      ParallelComputationGraphBuilder builder;
      
      
      ParallelTensorShape input_shape =
        ParallelTensorShape{ParallelTensorDims{
                                FFOrdered<ShardParallelDim>{
                                    ShardParallelDim{32, 2},
                                    ShardParallelDim{16, 1},
                                },
                                ReplicaParallelDimSet{
                                    SumDegree{1},
                                    DiscardCopyDegree{1},
                                },
                            },
                            DataType::FLOAT};

      parallel_tensor_guid_t input0 =
        builder.create_input_tensor(input_shape);
      parallel_tensor_guid_t dense0 = builder.dense(input0,
                                                  8);

      parallel_tensor_guid_t dense1 = builder.dense(dense0,
                                                  4);
      return builder.pcg
    }();
```
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 67 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sGimW4CLwttff0w_W:-O4sGimW4CLwttff0w_X:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/678e9909b089c30e40d096978b3cf7fbf96b755f/lib/compiler/test/src/test_graph_optimize_state.cc#L67)):*
> ```cpp
>                                                    "dense0");
> 
>     ParallelComputationGraph pcg_ = builder.pcg;
> ```





_Suggestion:_
```cpp
    ParallelComputationGraph pcg2 = [&] {
      ParallelComputationGraphBuilder builder;  
      
      parallel_tensor_guid_t input0 =
        builder.create_input_tensor(input_shape);
      parallel_tensor_guid_t dense0 = builder.dense(input0,
                                                   8);
                                                   
      return builder.pcg;                          
    }();
```
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 69 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sHMtc8Kbk8P9VG_3u:-O4sHMtc8Kbk8P9VG_3v:b-kvj0r) ([raw file](https://github.com/flexflow/FlexFlow/blob/678e9909b089c30e40d096978b3cf7fbf96b755f/lib/compiler/test/src/test_graph_optimize_state.cc#L69)):*
> ```cpp
>     ParallelComputationGraph pcg_ = builder.pcg;
> 
>     CHECK(GraphOptimizeState(GraphOptimizeResult(pcg, empty_machine_mapping), 0) !=
> ```

This doesn't really sufficiently test `GraphOptimizeState::operator==`--from this I'm not sure (1) what role the machine mappings and the cost play in equality, and (2) whether any graphs compare equal at all, or whether all of them just return not equal. A few more test/sub-cases are needed
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 70 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sH6qyDC85wLwD47V-:-O4sH6qz90QKvUJ0n3f0:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/678e9909b089c30e40d096978b3cf7fbf96b755f/lib/compiler/test/src/test_graph_optimize_state.cc#L70)):*
> ```cpp
> 
>     CHECK(GraphOptimizeState(GraphOptimizeResult(pcg, empty_machine_mapping), 0) !=
>           GraphOptimizeState(GraphOptimizeResult(pcg_, empty_machine_mapping), 0));
> ```





_Suggestion:_
```cpp
    GraphOptimizeState state1 = GraphOptimizeState{
      GraphOptimizeResult{pcg, empty_machine_mapping},
      0,  
    };
    
    GraphOptimzieState state2 = GraphOptimizeState{
      GraphOptimizeResult{pcg, empty_machine_mapping},
      0,
    };
    
    CHECK(state1 != state2);
```
___
*[`lib/substitutions/include/substitutions/sub_parallel_computation_graph.h` line 25 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kHHkvDFx4r9_OySAF:-O4sFWds3SSLK2U0fjAe:b-m06nhy) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/substitutions/include/substitutions/sub_parallel_computation_graph.h#L25)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

In that case let's rename it to `get_pcg_subgraph`


<!-- Sent from Reviewable.io -->

2024-08-29 00:56 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: 4 of 41 files reviewed, 13 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/src/graph_optimize_state.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kIAym5Yc4ECMISkBW:-O5K89UC4jiWos1niFHt:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/graph_optimize_state.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Using a hack like this for now is fine, but eventually it would be good to move over to a more principled algorithm implemented in `utils/graph` that doesn't make correctness tradeoffs and more explicitly uses the properties of `DataflowGraph` that you're relying on for efficiency. Until that's implemented let's add a comment in the code that clarifies that this is a hack and links to an issue with the plan for moving this over to something more correct
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 159 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3k7EbFEVCOejcvjQ2i:-O5Kf3ml1nuOZNmqa0Lj:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L159)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

As discussed in the Wednesday meeting, it should be possible to remove `OptimalCostFunctor`, especially as we're now on C++17 and can use `overload`

There seem to be two potential designs (either (1) making `optimal_cost` a method on `MachineMappingSearcher`, or (2) making `MachineMappingSearcher` just a wrapper for the global state (probably renamed to something like `DPContext`) and passing that around between top-level functions as a mutable reference, i.e., essentially doing the passing of `this` manually)
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 219 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kGaSh7CZG-NOvXfCn:-O5KgFweEz2x2TITyYWS:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L219)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

See `keys` in `utils/containers/keys.h`
</blockquote></details>

Done.
___
*[`lib/compiler/src/machine_mapping.cc` line 320 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kFSpPDCXtyhVbVHun:-O5KivWxArJS03y4-D8e:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/compiler/src/machine_mapping.cc#L320)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not exactly sure the details of simplifying this, but making it more clear what this is doing would be nice (maybe using functions from `utils/containers` or pulling out some pieces into separate named lambdas)
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 8 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4rD7KhDFmzp8dXMk4i:-O5Kj02I9zIfCx8g86nX:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ee2429c2b17202e5a352a20b8d4c46a8176e46aa/lib/compiler/test/src/test_graph_optimize_state.cc#L8)):*
> ```cpp
> 
> TEST_SUITE(FF_TEST_SUITE) {
>   TEST_CASE("graph_optimize_state:equality") {
> ```

Done.
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 44 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sFtnyABZ_-JhKG7s6:-O5POtP95R2ldn6OfK7i:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ee2429c2b17202e5a352a20b8d4c46a8176e46aa/lib/compiler/test/src/test_graph_optimize_state.cc#L44)):*
> ```cpp
>                                                   "dense1");
> 
>     ParallelComputationGraph pcg = builder.pcg;
> ```

Done.
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 67 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sGimW4CLwttff0w_W:-O5PGA2D5TGDprYgman0:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ee2429c2b17202e5a352a20b8d4c46a8176e46aa/lib/compiler/test/src/test_graph_optimize_state.cc#L67)):*
> ```cpp
>                                                    "dense0");
> 
>     ParallelComputationGraph pcg_ = builder.pcg;
> ```

Done.
___
*[`lib/substitutions/include/substitutions/sub_parallel_computation_graph.h` line 25 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kHHkvDFx4r9_OySAF:-O5KjDPq6vzEyoaUsN15:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/substitutions/include/substitutions/sub_parallel_computation_graph.h#L25)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In that case let's rename it to `get_pcg_subgraph`
</blockquote></details>

Done.
___
*[`lib/compiler/include/compiler/optimal_cost_state.struct.toml` line 20 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4rDPYg8DFHrOegAL_e:-O5K7YLc03w3W12RIlVq:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ee2429c2b17202e5a352a20b8d4c46a8176e46aa/lib/compiler/include/compiler/optimal_cost_state.struct.toml#L20)):*
> ```TOML
>   "utils/hash/unordered_map.h",
>   "utils/fmt/unordered_map.h", 
> ]
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-02 18:49 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: 4 of 41 files reviewed, 13 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/src/graph_optimize_state.cc` line 57 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4vzkuQCtTzxmIsR26c:-O5o27ztDUqYyTtzBxp5:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ee2429c2b17202e5a352a20b8d4c46a8176e46aa/lib/compiler/src/graph_optimize_state.cc#L57)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

See https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kIAym5Yc4ECMISkBW. Eventually it might be good to use a proper graph hash like https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.graph_hashing.weisfeiler_lehman_graph_hash.html#networkx.algorithms.graph_hashing.weisfeiler_lehman_graph_hash
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 69 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sHMtc8Kbk8P9VG_3u:-O5o29SG7id7zuOZSVqK:b-zhvmc) ([raw file](https://github.com/flexflow/FlexFlow/blob/ee2429c2b17202e5a352a20b8d4c46a8176e46aa/lib/compiler/test/src/test_graph_optimize_state.cc#L69)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This doesn't really sufficiently test `GraphOptimizeState::operator==`--from this I'm not sure (1) what role the machine mappings and the cost play in equality, and (2) whether any graphs compare equal at all, or whether all of them just return not equal. A few more test/sub-cases are needed
</blockquote></details>

This will be fixed in another PR.
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 70 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sH6qyDC85wLwD47V-:-O5o2ET90F46ppiC9UJJ:b-zhvmc) ([raw file](https://github.com/flexflow/FlexFlow/blob/ee2429c2b17202e5a352a20b8d4c46a8176e46aa/lib/compiler/test/src/test_graph_optimize_state.cc#L70)):*
> ```cpp
> 
>     CHECK(GraphOptimizeState(GraphOptimizeResult(pcg, empty_machine_mapping), 0) !=
>           GraphOptimizeState(GraphOptimizeResult(pcg_, empty_machine_mapping), 0));
> ```

This will be fixed in another PR.
___
*[`lib/substitutions/src/substitutions/sub_parallel_computation_graph.cc` line 61 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O3kHbko4Uh_vL2aNZn2:-O5o3YEI4wmZROwr09QL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c71b773c136606cbb80d830f7f99eacbf1ec7f87/lib/substitutions/src/substitutions/sub_parallel_computation_graph.cc#L61)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably better to just add `get_subgraph` for `LabelledOpenDataflowGraph` and then use it here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-03 01:22 UTC, lockshaw requested changes
> Reviewed 27 of 37 files at r4, 6 of 7 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: 38 of 41 files reviewed, 31 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h` line 6 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5oPtxS30uhS0yiJihP:-O5oPtxS30uhS0yiJihQ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h#L6)):*
> ```objc
> #include "machine_mapping.h"
> #include "machine_mapping_cache.h"
> #include "machine_mapping_context.dtg.h"
> ```





_Suggestion:_
```objc
#include "compiler/machine_mapping/machine_mapping.h"
#include "compiler/machine_mapping/machine_mapping_cache.h"
#include "compiler/machine_mapping/machine_mapping_context.dtg.h"
```
___
*[`lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h` line 16 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pICXjCNSEeOm-COWW:-O5pICXkDA1K-_8ziDRB:b-28fx4d) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h#L16)):*
> ```objc
>     ParallelComputationGraph const &pcg,
>     std::function<std::unordered_set<MachineView>(
>         ParallelLayerAttrs const &, MachineSpecification const &)> const
> ```

This isn't going to allow access to the input and output tensor shapes of the operator, which are probably necessary?



_Code quote:_
```objc
        ParallelLayerAttrs const &, M
```
___
*[`lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h` line 23 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSD3s6yo8z81yxIaV:-O5pSD3s6yo8z81yxIaW:b-kgfmph) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h#L23)):*
> ```objc
> 
> MachineMappingResult
>     get_optimal_machine_mapping_internal(MachineMappingContext &context,
> ```

What is this overload for? Why does it not take a `SerialParallelDecomposition`?
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping.h` line 4 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pET25562u-SF2kReh:-O5pET25562u-SF2kRei:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/machine_mapping.h#L4)):*
> ```objc
> #define _FLEXFLOW_COMPILER_MACHINE_MAPPING_H
> 
> #include "machine_mapping.dtg.h"
> ```





_Suggestion:_
```objc
#include "compiler/machine_mapping/machine_mapping.dtg.h"
```
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping.h` line 8 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pEMG09N_RLmysLksI:-O5pEMG09N_RLmysLksJ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/machine_mapping.h#L8)):*
> ```objc
> namespace FlexFlow {
> 
> MachineMapping combine(MachineMapping const &, MachineMapping const &);
> ```





_Suggestion:_
```objc
MachineMapping combine_disjoint_mappings(MachineMapping const &, MachineMapping const &);
```
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_cache.h` line 10 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSLpJB-z4NkSnxlsc:-O5pSLpJB-z4NkSnxlsd:b2k2q57) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/machine_mapping_cache.h#L10)):*
> ```objc
> namespace FlexFlow {
> 
> class MachineMappingCache {
> ```

Does it make sense to have a separate class/object for this, or this not just the `std::unordered_map` API?
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml` line 7 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5UIn7E19T0Z0_YYZKm:-O5UIn7E19T0Z0_YYZKn:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/150ca5e1a2bd6d16e2c6b61034f64d8b11f5fefe/lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml#L7)):*
> ```TOML
> 
> includes = [
>   "machine_mapping.dtg.h",
> ```





_Suggestion:_
```TOML
  "compiler/machine_mapping/machine_mapping.dtg.h",
```
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml` line 29 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSW-0DdNHPGa16HB-:-O5pSW-0DdNHPGa16HB0:b-jyidlz) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml#L29)):*
> ```TOML
> [[fields]]
> name = "cached_subgraph_results"
> type = "::FlexFlow::MachineMappingCache"
> ```

What about moving `MachineMappingCache` out of this class so `MachineMappingContext` can be passed as `const &` and `MachineMappingCache` alone gets passed as mutable `&`?
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_result.h` line 14 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSkGHES5VbcZLw9Tk:-O5pSkGHES5VbcZLw9Tl:bsixksi) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/machine_mapping_result.h#L14)):*
> ```objc
> MachineMappingResult get_infinity_machine_mapping_result();
> 
> void minimize_runtime(MachineMappingResult &m1, MachineMappingResult const &m2);
> ```

Why this vs just calling `min` or something? 



_Code quote:_
```objc
void minimize_runtime(MachineMappingResult &m1, MachineMappingResult const &m2);
```
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_result.struct.toml` line 9 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5UIt1p7LcmJoYwXIFL:-O5UIt1p7LcmJoYwXIFM:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/150ca5e1a2bd6d16e2c6b61034f64d8b11f5fefe/lib/compiler/include/compiler/machine_mapping/machine_mapping_result.struct.toml#L9)):*
> ```TOML
> 
> includes = [
>   "machine_mapping.dtg.h",
> ```





_Suggestion:_
```TOML
  "compiler/machine_mapping/machine_mapping.dtg.h",
```
___
*[`lib/compiler/src/unity_algorithm.cc` line 39 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pIqwICFcIIJFoMxSp:-O5pIqwICFcIIJFoMxSq:b-3xd9kx) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/src/unity_algorithm.cc#L39)):*
> ```cpp
> 
>   MachineMappingCache cached_subgraph_costs;
>   DeduplicatedPriorityQueue<GraphOptimizeState> candidates;
> ```

Would it be cleaner here to, rather than having a custom `GraphOptimizeState` type whose hash and `operator==` ignore the runtime cost, instead have this be a `DeduplicatedPriorityQueue<SomeWrapperAroundAPCG, CustomComparator>` where the `CustomComparator` is something like below, where `MyCustomType` is analagous to `SomeWrapperAroundAPCG`, and I suppose instead of a `std::unordered_map<MyCustomType, float>` you'd have a `MachineMappingCache`



_Code snippet:_
```cpp
#include <map>
#include <queue>
#include <unordered_map>
#include <stdlib.h>
#include <iostream>

int guid_ctr = 0; 

struct MyCustomType {
  MyCustomType()
    : guid(guid_ctr++) {}

  bool operator==(MyCustomType const &other) const {
    return this->guid == other.guid;
  }

  bool operator!=(MyCustomType const &other) const {
    return this->guid != other.guid;
  }

  int guid;
};

namespace std {

template <>
struct hash<MyCustomType> {
  size_t operator()(MyCustomType const &x) const {
    return x.guid;
  }
};

}

float get_cost(MyCustomType const &) {
  return rand();
}

int main() {
  std::unordered_map<MyCustomType, float> costs;

  a [...]

2024-09-04 20:30 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: 38 of 41 files reviewed, 31 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml` line 29 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSW-0DdNHPGa16HB-:-O5yQ-U60XeHkAgY7zCs:b1ghblw) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What about moving `MachineMappingCache` out of this class so `MachineMappingContext` can be passed as `const &` and `MachineMappingCache` alone gets passed as mutable `&`?
</blockquote></details>

I think `MachineMappingCache` should be part of the context, and it is fine to have a mutable context.
___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 81 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pNAF36hyj_zxtkskS:-O5yiYmVDjkS_dTP9nYO:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L81)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to a separate `allowed_machine_mappings` file, this file is already getting rather complicated/large
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 20:41 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: 38 of 41 files reviewed, 31 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 206 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pH1-55TKrbct-3-gB:-O5yixHq4Us8A28whS1e:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L206)):*
> ```cpp
>                       get_open_dataflow_values(subgraph_res2.graph));
> 
>     for (auto const &[split_value, split_input] :
> ```

Done.
___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 283 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pO_SH2UUwwCg_J8ij:-O5yjPcICfQfg0YR5o_6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L283)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Simplify
</blockquote></details>

Done.
___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 302 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pOqY-BEpFKY3poKiG:-O5ykFDdBewnFi__s5wN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L302)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Simplify, probably separate into two expressions
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/test_get_optimal_machine_mapping.cc` line 100 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pPd916U5IUNumzOkq:-O5ykilfDJLtshvv36Sw:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/test/src/compiler/machine_mapping/test_get_optimal_machine_mapping.cc#L100)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

These should be in the `SUBCASE`s as they're not shared between them
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/compiler/machine_mapping/test_get_optimal_machine_mapping.cc` line 146 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pPPPk6Tktgg0OjoIp:-O5ykj7NAKvw7l0su86G:b-3mbv3d) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/test/src/compiler/machine_mapping/test_get_optimal_machine_mapping.cc#L146)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Rather than running it, getting a cost, and then just hardcoding that into the file, I'd focus on generating testcases (such as restricting the allowed machine views to only a few, controlling the cost function, etc.) where you can actually set analytically derived values
</blockquote></details>

In terms of actual cost, I mean the cost model we have for a pcg. Even for analytical results, we need a precise cost model.
___
*[`lib/compiler/test/src/compiler/machine_mapping/test_get_optimal_machine_mapping.cc` line 171 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pRo0C3fZgMSx2T8Tg:-O5yl4u54-yt--PDjgIq:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/test/src/compiler/machine_mapping/test_get_optimal_machine_mapping.cc#L171)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You'd want separate testcases for this too that actually check the graph manipulation, not just `get_optimal_machine_mapping`-level tests
</blockquote></details>

Done.
___
*[`lib/substitutions/include/substitutions/sub_parallel_computation_graph.h` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pRP5SEkof0vIXHf5b:-O5ylBSz5gzReP1dFoSc:bb76mu4) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/substitutions/include/substitutions/sub_parallel_computation_graph.h#L25)):*
> ```objc
> 
> SubParallelComputationGraph get_pcg_subgraph(ParallelComputationGraph const &,
>                                              std::unordered_set<Node> const &);
> ```

Why?


<!-- Sent from Reviewable.io -->

2024-09-06 22:14 UTC, lockshaw requested changes
> Reviewed 1 of 37 files at r4, 7 of 17 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: 33 of 43 files reviewed, 24 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h` line 12 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O68IRMF8J0s3GLGhsLZ:-O68IRMF8J0s3GLGhsL_:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h#L12)):*
> ```objc
>     allowed_machine_mappings(MachineMappingContext const &context,
>                              std::unordered_set<Node> const &nodes,
>                              MachineSpecification const &resource);
> ```





_Suggestion:_
```objc
std::vector<std::unordered_map<parallel_layer_guid_t, MachineView>>
    allowed_machine_mappings(MachineMappingContext const &context,
                             std::unordered_set<parallel_layer_guid_t> const &nodes,
                             MachineSpecification const &resource);
```
___
*[`lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h` line 16 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O68I9pIEX7J8P3L-ZBZ:-O68I9pJ-s1WfMrOZZBT:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h#L16)):*
> ```objc
> std::vector<std::unordered_map<DataflowOutput, MachineView>>
>     allowed_machine_mappings(MachineMappingContext const &context,
>                              std::unordered_set<DataflowOutput> const &values,
> ```





_Suggestion:_
```objc
                            std::unordered_set<parallel_tensor_guid_t> const &values,
```
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 70 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sH6qyDC85wLwD47V-:-O68KmUvD96ws9TqomoJ:b-sjqiaa) ([raw file](https://github.com/flexflow/FlexFlow/blob/ee2429c2b17202e5a352a20b8d4c46a8176e46aa/lib/compiler/test/src/test_graph_optimize_state.cc#L70)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

This will be fixed in another PR.
</blockquote></details>

Isn't this a trivial fix?
___
*[`lib/compiler/test/src/compiler/machine_mapping/test_get_optimal_machine_mapping.cc` line 146 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pPPPk6Tktgg0OjoIp:-O68JDtw56RCgXYjqkYA:b-uttvp1) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/test/src/compiler/machine_mapping/test_get_optimal_machine_mapping.cc#L146)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

In terms of actual cost, I mean the cost model we have for a pcg. Even for analytical results, we need a precise cost model.
</blockquote></details>

In a way yes, but you control the cost model: you can add a custom implementation of `CostEstimator` that returns whatever numbers you think would be useful for testing. We absolutely do want to (at some point) test the whole compiler+costestimator+machineviews+everything stack, but even if all of that was present we would also want to have tests that just that compiler is correct in isolation, which is what most of these tests should be--provide an arbitrary tiny set of allowed machine views (say, two of them), create a tiny PCG (with, say, 2 operators in parallel), and write a `CostEstimator` subclass that gives you back some chosen constants (1 for each of the possible node-machineview assignments). Then solve for what the resulting value of `get_optimal_machine_mappings` *should* be, run the function, and check that the returned value is the same as what you solved analytically. 

At this point there shouldn't be anything stopping you from testing pretty much the whole Unity DP in isolation, and once everything is merged we'll add a couple end-to-end tests just to make sure there weren't any unexpected issues at the boundaries between components
___
*[`lib/compiler/test/src/compiler/machine_mapping/test_get_optimal_machine_mapping.cc` line 12 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O68KUGs6703BX-VA5G8:-O68KUGs6703BX-VA5G9:bjtxymv) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/test/src/compiler/machine_mapping/test_get_optimal_machine_mapping.cc#L12)):*
> ```cpp
>     auto allowed_machine_views1 = [&](ParallelLayerAttrs const &,
>                                       MachineSpecification const &) {
>       // TODO(@Mengdi Wu): Replace it with actual allowed machine views when
> ```

Ideally don't do this--these tests are supposed to confirm that `get_optimal_machine_mapping` is correct, not that `get_allowed_machine_views` is correct. If you call `get_allowed_machine_views` in this test and the test fails, you don't know whether it is because `get_optimal_machine_mapping` is wrong or if it s because `get_allowed_machine_views` is wrong
___
*[`lib/compiler/test/src/compiler/machine_mapping/test_machine_mapping.cc` line  at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pQr11Cs6E1T7cGBKC:-O68IVjp0y5ZslWMY1Tb:beporia) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/test/src/compiler/machine_mapping/test_machine_mapping.cc#L)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

What does this mean?
</blockquote></details>

Rename from `test_machine_mapping.cc` to `machine_mapping.cc`--the current convention is to not have the `test_` prefix, as they're already under the `test` directory
___
*[`lib/compiler/test/src/compiler/machine_mapping/test_machine_mapping.cc` line 25 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O68IpKn39if0j6SuErS:-O68IpKn39if0j6SuErT:b2esztd) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/test/src/compiler/machine_mapping/test_machine_mapping.cc#L25)):*
> ```cpp
>         combine_disjoint_mappings(machine_mapping_0, machine_mapping_1);
>     CHECK(result == correct);
>   }
> ```

Add a `SUBCASE` to test the failure case



_Suggestion:_
```cpp
  TEST_CASE("combine_disjoint_mappings(MachineMapping, MachineMappping)") {
    MachineView machine_view_0 = make_1d_machine_view(gpu_id_t(0), gpu_id_t(1));
    MachineView machine_view_1 = make_1d_machine_view(gpu_id_t(0), gpu_id_t(2));
    
    SUBCASE("input machine mappings are disjoint") {
      MachineMapping machine_mapping_0 = MachineMapping({
          {Node(0), machine_view_0},
      });
      MachineMapping machine_mapping_1 = MachineMapping({
          {Node(1), machine_view_1},
      });
      MachineMapping correct = MachineMapping({
          {Node(0), machine_view_0},
          {Node(1), machine_view_1},
      });
      MachineMapping result =
          combine_disjoint_mappings(machine_mapping_0, machine_mapping_1);
      CHECK(result == correct);
    }
    
    SUBCASE("input machine mappings are not disjoint") {
      ...
    }
  }
```
___
*[`lib/substitutions/include/substitutions/sub_parallel_computation_graph.h` line 25 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pRP5SEkof0vIXHf5b:-O62ajL26X3ykhJEIte_:bir9pp0) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/substitutions/include/substitutions/sub_parallel_computation_graph.h#L25)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

`parallel_layer_guid_t` is a wrapper for `Node` that we use for representing `Node`s in a `ParallelComputationGraph`. It primarily improves readability and helps prevent accidentally passing the wrong node to things


<!-- Sent from Reviewable.io - [...]

2024-09-07 02:04 UTC, lockshaw requested changes
> Reviewed 10 of 17 files at r7.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: all files reviewed, 28 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h` line 10 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O698VUD59Y87RDRRgWf:-O698VUD59Y87RDRRgWg:b-ss04zn) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h#L10)):*
> ```objc
> 
> std::vector<std::unordered_map<Node, MachineView>>
>     allowed_machine_mappings(MachineMappingContext const &context,
> ```

The type signatures of these methods are a bit odd? At least it's not 100% clear for me what they're doing based on the names and input types, especially since there are two overloads? Can you either clarify the names a bit and/or add doxygen docstrings giving a brief description of what they do?
___
*[`lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h` line 23 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSD3s6yo8z81yxIaV:-O69CTgXCahdMraqaT9C:b-8jlz76) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h#L23)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

This is to further split the logics into multiple pieces. `get_optimal_machine_mapping` wraps global variables as `MachineMappingContext` and calls this function, and this function performs sp decomposition (and solves the un-sp-izable issue in a later version) and calls other overloads.
</blockquote></details>

I think it's probably better to think of the SP decomposition as coming from outside of the optimal machine mapping algorithm, as with Pietro's stuff it at least seems more like creating an SP-ization of a given PCG is a separate step than just part of optimal machine mapping algorithm, but this isn't a bit deal and can always get refactored later. That said, it seems a bit odd to have this function, which conceptually seems to do entirely different things from the other `get_optimal_machine_mapping_internal` overloads, have the same name as them, so if you do prefer to use this structure it should at least be renamed to something clearer--ideally I should be able to make a pretty accurate educated guess of what a function does from its name and arguments, and I don't think that's the case here.  
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml` line 29 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSW-0DdNHPGa16HB-:-O698qr76W_TQuUARD09:b17dro3) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml#L29)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I think `MachineMappingCache` should be part of the context, and it is fine to have a mutable context.
</blockquote></details>

Is there a significant downside to moving it out? It would make the code a bit more readable as it would make it more obvious what gets mutated and what doesn't
___
*[`lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc` line 9 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O699DMS0w21AbegYQA5:-O699DMS0w21AbegYQA6:baw38jz) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc#L9)):*
> ```cpp
> namespace FlexFlow {
> 
> std::vector<std::unordered_map<Node, MachineView>>
> ```

Might be cleaner to define a `machine_mapping.struct.toml` wrapper type around `std::unordered_map<parallel_layer_guid_t, MachineView>` so this turns into the more readable `std::vector<MachineMapping>`? Also why is this a `std::vector` and not a `std::unordered_set`/`std::set`? Should there be duplicates or does order matter?
___
*[`lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc` line 14 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O6995K6BumY5Mxk5m-Z:-O6995K6BumY5Mxk5m-_:bsrt6zg) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc#L14)):*
> ```cpp
>                              MachineSpecification const &resource) {
>   if (nodes.empty()) {
>     return {{}};
> ```

Why not an empty vector as a return value? Does an empty machine mapping really have a meaning?
___
*[`lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc` line 29 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O699vFc0X1p-KcCXGeA:-O699vFc0X1p-KcCXGeB:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc#L29)):*
> ```cpp
>     }
>   }
>   return enumeration;
> ```





_Suggestion:_
```cpp
  Node curr_node = get_first(nodes);
  std::unordered_set<Node> other_nodes = set_minus(nodes, {node});
  
  std::vector<std::unordered_map<Node, MachineView>> other_node_mappings_from_recursion =
      allowed_machine_mappings(context, other_nodes, resource);
      
  std::unordered_set<MachineView> allowed_machine_views_for_curr_node =
      context.allowed_machine_views(context.pcg.raw_graph.at(node), resource);
      
  std::vector<std::unordered_map<Node, MachineView>> result;
  for (MachineView const &for_curr_node : allowed_machine_views_for_curr_node) {
    for (std::unordered_map<Node, MachineView> const &for_other_nodes :
         other_node_mappings_from_recursion) {
           
      MachineMapping merged = merge_disjoint_machine_mappings(
        MachineView{{
          {curr_node, for_cudd_node},
        }},
        for_other_nodes,
      });
      
      enumeration.push_back(merged);
    }
  }
  return result;
```
___
*[`lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc` line 39 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O69BEKj9kSqOT1eCgGy:-O69BEKj9kSqOT1eCgGz:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc#L39)):*
> ```cpp
>   for (DataflowOutput const &v : values) {
>     nodes.insert(v.node);
>   }
> ```





_Suggestion:_
```cpp
  std::unordered_set<Node> nodes transform(values, [](DataflowOutput const &v) { return v.node; });
```
___
*[`lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc` line 47 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O69AygoBtNMW9q45Tn-:-O69AygpA81fYYL3VQB7:b8zgz33) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc#L47)):*
> ```cpp
>   for (std::unordered_map<Node, MachineView> _node_enumeration :
>        node_enumeration) {
>     std::unordered_map<DataflowOutput, MachineView> _emumeration;
> ```

Don't use leading underscore, if you need to distinguish it from `enumeration` it's probably better to come up with a clearer name as `enumeration` is a bit unclear (what is being enumerated? does this have to do with `enumerate` from `utils/containers/enumerate.h`?)



_Code quote:_
```cpp
_emumeration;
```
___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 257 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O692X-e75DLTugQhqWQ:-O692X-fBQX_wNFICup3:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L257)):*
> ```cpp
>       std::unorde [...]

2024-09-12 00:24 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: all files reviewed, 28 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h` line 12 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O68IRMF8J0s3GLGhsLZ:-O6XQGWh7sEzswMgtj38:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h#L12)):*
> ```objc
>     allowed_machine_mappings(MachineMappingContext const &context,
>                              std::unordered_set<Node> const &nodes,
>                              MachineSpecification const &resource);
> ```

Done.
___
*[`lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h` line 16 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O68I9pIEX7J8P3L-ZBZ:-O6XU0-V7khF_Wqc2Y1F:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h#L16)):*
> ```objc
> std::vector<std::unordered_map<DataflowOutput, MachineView>>
>     allowed_machine_mappings(MachineMappingContext const &context,
>                              std::unordered_set<DataflowOutput> const &values,
> ```

Done.
___
*[`lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h` line 23 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSD3s6yo8z81yxIaV:-O6XdQsh6MeLNnroOABi:bn5udpv) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h#L23)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think it's probably better to think of the SP decomposition as coming from outside of the optimal machine mapping algorithm, as with Pietro's stuff it at least seems more like creating an SP-ization of a given PCG is a separate step than just part of optimal machine mapping algorithm, but this isn't a bit deal and can always get refactored later. That said, it seems a bit odd to have this function, which conceptually seems to do entirely different things from the other `get_optimal_machine_mapping_internal` overloads, have the same name as them, so if you do prefer to use this structure it should at least be renamed to something clearer--ideally I should be able to make a pretty accurate educated guess of what a function does from its name and arguments, and I don't think that's the case here.
</blockquote></details>

I see. But I don't think it is a problem to have this signature. First, it is only used internally, so it has little effect on other parts. And it actually make the internal implementation more convenient. Second, it actually has the similar functionality as other functions that have the same name but just different format of the inputs. We should name functions according to their functionality instead of the detailed implementation.
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml` line 29 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSW-0DdNHPGa16HB-:-O6XUWnq0KQGSBlEdbPX:b-9axwem) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is there a significant downside to moving it out? It would make the code a bit more readable as it would make it more obvious what gets mutated and what doesn't
</blockquote></details>

I feel like we should put global variables in `MachineMappingContext` as possible and only explicitly pass the variables that belong to DP states. I think it is more clear this way.
___
*[`lib/compiler/src/unity_algorithm.cc` line 39 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pIqwICFcIIJFoMxSp:-O6XVDUAD046e_eUXrQC:b7dqmwr) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/src/unity_algorithm.cc#L39)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Would it be cleaner here to, rather than having a custom `GraphOptimizeState` type whose hash and `operator==` ignore the runtime cost, instead have this be a `DeduplicatedPriorityQueue<SomeWrapperAroundAPCG, CustomComparator>` where the `CustomComparator` is something like below, where `MyCustomType` is analagous to `SomeWrapperAroundAPCG`, and I suppose instead of a `std::unordered_map<MyCustomType, float>` you'd have a `MachineMappingCache`
</blockquote></details>

Sounds a good idea and we will leave all the MCMC search part to another PR.
___
*[`lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc` line 9 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O699DMS0w21AbegYQA5:-O6XbjEjBcb-SvdAnd9F:b-ub2zv1) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc#L9)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Might be cleaner to define a `machine_mapping.struct.toml` wrapper type around `std::unordered_map<parallel_layer_guid_t, MachineView>` so this turns into the more readable `std::vector<MachineMapping>`? Also why is this a `std::vector` and not a `std::unordered_set`/`std::set`? Should there be duplicates or does order matter?
</blockquote></details>

It is a vector because no deduplication is required here.
___
*[`lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc` line 14 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O6995K6BumY5Mxk5m-Z:-O6XcFJX1w5KgsS47SJi:bkj864d) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not an empty vector as a return value? Does an empty machine mapping really have a meaning?
</blockquote></details>

It means the only machine mapping for an empty set of input nodes.
___
*[`lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc` line 29 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O699vFc0X1p-KcCXGeA:-O6XcZ039THtNAdWcjri:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc#L29)):*
> ```cpp
>     }
>   }
>   return enumeration;
> ```

Done.
___
*[`lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc` line 39 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O69BEKj9kSqOT1eCgGy:-O6Xcg9H19VUeCpoBfR1:bfq4fh8) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc#L39)):*
> ```cpp
>   for (DataflowOutput const &v : values) {
>     nodes.insert(v.node);
>   }
> ```

I don't think we should use transform since it is not a one-to-one mapping but a many-to-one mapping. We should not expect transform to handle many-to-one mapping not matter whether it actually does.
___
*[`lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc` line 47 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O69AygoBtNMW9q45Tn-:-O6Xd3wN2Bv3EqaPRR6w:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/src/compiler/machine_mapping/allowed_machine_mappings.cc#L47)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Don't use leadin [...]

2024-09-12 00:56 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: 24 of 45 files reviewed, 28 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h` line 10 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O698VUD59Y87RDRRgWf:-O6YhwSFCNU0K36WuKgc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/include/compiler/machine_mapping/allowed_machine_mappings.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The type signatures of these methods are a bit odd? At least it's not 100% clear for me what they're doing based on the names and input types, especially since there are two overloads? Can you either clarify the names a bit and/or add doxygen docstrings giving a brief description of what they do?
</blockquote></details>

Done.
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 69 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sHMtc8Kbk8P9VG_3u:-O6YhzwuDdL000BoIflQ:bd6gfr9) ([raw file](https://github.com/flexflow/FlexFlow/blob/ee2429c2b17202e5a352a20b8d4c46a8176e46aa/lib/compiler/test/src/test_graph_optimize_state.cc#L69)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

In that case can you create an issue for that and link it here?
</blockquote></details>

I think we will have another PR to handle the entire MCMC search part, which will clearly include the tests files.
___
*[`lib/compiler/test/src/test_graph_optimize_state.cc` line 70 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O4sH6qyDC85wLwD47V-:-O6YiMy57jh1ba5wHpZO:b-ldfurw) ([raw file](https://github.com/flexflow/FlexFlow/blob/ee2429c2b17202e5a352a20b8d4c46a8176e46aa/lib/compiler/test/src/test_graph_optimize_state.cc#L70)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Isn't this a trivial fix?
</blockquote></details>

I think we will have another PR to handle the entire MCMC search part, which will clearly include the tests files. Also it is very likely we will modify `GraphOptimizeReulst` (as you have suggested), so I prefer to put off all the MCMC tests after that.


<!-- Sent from Reviewable.io -->

2024-09-12 18:37 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: 24 of 45 files reviewed, 28 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/test/src/compiler/machine_mapping/test_machine_mapping_cache.cc` line 58 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O694LDi4I_FCg07MZB_:-O6bUT1Y3sjb7k8ktB1e:b-r9129b) ([raw file](https://github.com/flexflow/FlexFlow/blob/8eff2b91039b5b014bf01f8062ec194aa8ed586a/lib/compiler/test/src/compiler/machine_mapping/test_machine_mapping_cache.cc#L58)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer curly-brace initialization for consistency with the rest of the FF codebase
</blockquote></details>

Why? Since we are moving towards dtgen style code, we should use direct initialization, right? Also, it is safer than curly-brace initialization.


<!-- Sent from Reviewable.io -->

2024-09-12 19:35 UTC, lockshaw requested changes
> Reviewed 21 of 21 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: all files reviewed, 32 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/machine_mapping/get_allowed_machine_views_list.h` line 11 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O6bP382EutmH9GATdg3:-O6bP382EutmH9GATdg4:b193mfm) ([raw file](https://github.com/flexflow/FlexFlow/blob/89ed108f4dad59f9fb9e45b25adb64e4de855280/lib/compiler/include/compiler/machine_mapping/get_allowed_machine_views_list.h#L11)):*
> ```objc
> 
> std::vector<std::unordered_map<parallel_layer_guid_t, MachineView>>
>     get_allowed_machine_views_list(
> ```

Isn't this just a `std::vector<MachineMapping>`? If so, why not make that change to the type signature and change the function name to `get_allowed_machine_mappings` (or `get_allowed_machine_mappings_for_layers`)?



_Code quote:_
```objc
std::vector<std::unordered_map<parallel_layer_guid_t, MachineView>>
    get_allowed_machine_views_list(
```
___
*[`lib/compiler/include/compiler/machine_mapping/get_allowed_machine_views_list.h` line 17 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O6bOYukAW5Z1E_m17P_:-O6bOYukAW5Z1E_m17Pa:bvo3t6j) ([raw file](https://github.com/flexflow/FlexFlow/blob/89ed108f4dad59f9fb9e45b25adb64e4de855280/lib/compiler/include/compiler/machine_mapping/get_allowed_machine_views_list.h#L17)):*
> ```objc
> 
> std::vector<std::unordered_map<parallel_tensor_guid_t, MachineView>>
>     get_allowed_src_machine_views_list(
> ```

I'm not sure I totally get the semantics of this function. Is it intended to be used to get the machine views of the tensors crossing a split? In that case maybe the return type should be different? This operation just doesn't currently seem to make that much sense to me by itself, though maybe I just need a better explanation of what this is intended to do.



_Code quote:_
```objc
    get_allowed_src_machine_views_list
```
___
*[`lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h` line 23 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSD3s6yo8z81yxIaV:-O6bi3Q_B1m3EWGSfvMP:br8sn39) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/get_optimal_machine_mapping.h#L23)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I see. But I don't think it is a problem to have this signature. First, it is only used internally, so it has little effect on other parts. And it actually make the internal implementation more convenient. Second, it actually has the similar functionality as other functions that have the same name but just different format of the inputs. We should name functions according to their functionality instead of the detailed implementation.
</blockquote></details>

Fair enough, let's keep this for now and reevaluate if it still makes sense once approximate SP stuff is actually in place
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml` line 29 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSW-0DdNHPGa16HB-:-O6biP4kC4WigFixBZkg:b73jap1) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml#L29)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I feel like we should put global variables in `MachineMappingContext` as possible and only explicitly pass the variables that belong to DP states. I think it is more clear this way.
</blockquote></details>

I agree up to the point of grouping mutable and non-mutable global variables into the same type as then the mutation properties become unclear (how do I know that your function isn't also mutating the `pcg`?), especially since only one of the members ever mutable. This is one case where I have a strong preference that we split `MachineMappingCache` out so that the function signatures remain clear about what is safe from mutation
___
*[`lib/compiler/src/unity_algorithm.cc` line 39 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pIqwICFcIIJFoMxSp:-O6bNUsFChxlvj1N_pnu:b-3lo5v) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/src/unity_algorithm.cc#L39)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Sounds a good idea and we will leave all the MCMC search part to another PR.
</blockquote></details>

Sounds good, tracked in https://github.com/flexflow/FlexFlow/issues/1501
___
*[`lib/compiler/src/compiler/machine_mapping/get_allowed_machine_views_list.cc` line 44 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O6bRIxRA8dEVIpx521v:-O6bRIxRA8dEVIpx521w:bu8fkiy) ([raw file](https://github.com/flexflow/FlexFlow/blob/89ed108f4dad59f9fb9e45b25adb64e4de855280/lib/compiler/src/compiler/machine_mapping/get_allowed_machine_views_list.cc#L44)):*
> ```cpp
>     }
>   }
>   return result;
> ```

Might be more readable as something like this? We'd need to add a `transform_tuples` function or something like it that takes in a container of `std::tuple<A, B, ...>` and a lambda matching `std::function<T(A const &, B const &, ...)>` and combines the destructuring and `transform` operations, but I'm sure I or @Marsella8 would be happy to add this to `containers` as I can think of quite a few places where it would be useful. Not a high priority and the current code is fine as is, just something I was thinking of



_Suggestion:_
```cpp
  return transform_tuples(as_vector(get_all_permutations(allowed_machine_view_for_curr_layer, other_machine_view_from_recursion)),
                          [](MachineView const &for_curr_node, MachineMapping const &for_other_layers) {
                             return add_view_for_layer_to_mapping(for_other_layers, curr_node, for_curr_node);
                          });
```
___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 63 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O6bV6E0Ea2u2tXpHrR2:-O6bV6E0Ea2u2tXpHrR3:b-pk3xp9) ([raw file](https://github.com/flexflow/FlexFlow/blob/89ed108f4dad59f9fb9e45b25adb64e4de855280/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L63)):*
> ```cpp
>         &machine_views) {
>   // TODO: Replace it with the actual implementation.
>   auto get_input_shapes = [&](parallel_layer_guid_t) {
> ```

Migrate to using #1493 once it's merged 
___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 73 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O6bVKJJ1u70QJts-IaY:-O6bVKJJ1u70QJts-IaZ:b7sbvja) ([raw file](https://github.com/flexflow/FlexFlow/blob/89ed108f4dad59f9fb9e45b25adb64e4de855280/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L73)):*
> ```cpp
>   };
> 
>   assert(contains_key(machine_views, get_layer_outputs(pcg, layer)[0]));
> ```

FYI `at` already does this check so the separate `assert` isn't really necessary
___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 83 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O6bW2yz8kvi-bs5cymN:-O6bW2yz8kvi-bs5cymO:b-eui3zk) ([raw file](https://github.com/flexflow/FlexFlow/blob/89ed108f4dad59f9fb9e45b25adb64e4de855280/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L83)):*
> ```cpp
>                               layer_machine_view);
>   float communication_cost = 0;
>   for (parallel_tensor_guid_t const &input : get_layer_inputs(pcg, layer)) {
> ```

iirc the old Unity implementation took into account the outgoing tensor communication costs rather than the incoming tensor communication costs. As incoming/outgoing is not symmetric in `DataflowGraph` (a tenso [...]

2024-09-13 08:05 UTC, Marsella8 approved these changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: all files reviewed, 33 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/graph_optimize_state.h` line 1 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O6eE74X8z2Cg9YxwgrB:-O6eE74X8z2Cg9YxwgrC:bkdbi21) ([raw file](https://github.com/flexflow/FlexFlow/blob/89ed108f4dad59f9fb9e45b25adb64e4de855280/lib/compiler/include/compiler/graph_optimize_state.h#L1)):*
> ```objc
> #ifndef _FLEXFLOW_COMPILER_MCMC_STATE_H
> ```

Why not dtgen?
___
*[`lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc` line 140 at r8](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O6eG1YS25LbS8UPf5-5:-O6eG1YS25LbS8UPf5-6:b9o7ese) ([raw file](https://github.com/flexflow/FlexFlow/blob/89ed108f4dad59f9fb9e45b25adb64e4de855280/lib/compiler/src/compiler/machine_mapping/get_optimal_machine_mapping.cc#L140)):*
> ```cpp
> 
>   MachineMappingResult result = decompn.visit<MachineMappingResult>(
>       overload{[&](SerialSplit const &serial) {
> ```

i think this can be subbed by `decompn.visit<MachineMappingResult>([](auto const &x) { return get_optimal_machine_mapping_internal(x); });)`

Alternatively, probably cleaner to add another overload to `get_optimal_machine_mapping_internal` which delegates the call to the other overloads.


<!-- Sent from Reviewable.io -->

2024-10-03 04:06 UTC, Marsella8 reviewed
> Reviewed 1 of 3 files at r9, 106 of 150 files at r10, 117 of 145 files at r11, 51 of 60 files at r12, 23 of 23 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: all files reviewed, 52 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/include/compiler/machine_mapping/include_unconstrained.struct.toml` line 2 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O84Z2yN0sYtnQUo9nns:-O84Z2yN0sYtnQUo9nnt:blenc7g) ([raw file](https://github.com/flexflow/FlexFlow/blob/b0475b4c97ee3e3f2bc31bfdb8d8cffa71d70522/lib/compiler/include/compiler/machine_mapping/include_unconstrained.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "IncludeUnconstrained"
> ```

maybe enum instead? (just an idea)
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_result.h` line 9 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8Eir7a2PgwyLyPAMBp:-O8Eir7a2PgwyLyPAMBq:b7ydtq7) ([raw file](https://github.com/flexflow/FlexFlow/blob/85fd5b4fde364da21d150a55ecc4256ea75505ea/lib/compiler/include/compiler/machine_mapping/machine_mapping_result.h#L9)):*
> ```objc
> namespace FlexFlow {
> 
> [[nodiscard]] MachineMappingResult infeasible_machine_mapping_result();
> ```

any strong reason for `[[nodiscard]]`?
___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_problem_tree/mm_problem_tree_parallel_split_label.struct.toml` line 2 at r11](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O84__Je1Xu35iR4-Hdm:-O84__JfCZfZyjb8oK6t:beybgge) ([raw file](https://github.com/flexflow/FlexFlow/blob/b0475b4c97ee3e3f2bc31bfdb8d8cffa71d70522/lib/compiler/include/compiler/machine_mapping/machine_mapping_problem_tree/mm_problem_tree_parallel_split_label.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "MMProblemTreeParallelSplitLabel"
> ```

why is it empty?
___
*[`lib/compiler/src/compiler/machine_mapping/get_machine_resource_splits.cc` line 27 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8ElM3K0271KUx2klm8:-O8ElM3K0271KUx2klm9:bcxxg20) ([raw file](https://github.com/flexflow/FlexFlow/blob/85fd5b4fde364da21d150a55ecc4256ea75505ea/lib/compiler/src/compiler/machine_mapping/get_machine_resource_splits.cc#L27)):*
> ```cpp
>     result.insert(std::make_pair(sub_resource2, sub_resource1));
>   }
> ```

note that we are only partitioning across GPUs here.

Currently, I consider how `MachineSpecification` fuses GPU and CPU nodes to be a bit awkard (e.g. it doesn't even have a separate intra and inter node bandwitdh per parameters), I think it should instead have as attributes num_nodes, num_devices_per_node, device_type, inter_node_bandwidth, and intra_node_bandwidth, since this way we can ignore the CPU stuff a lot more and only use it when needed.

Also with the `i*=2` in this part of the code feels a bit arbitrary?
___
*[`lib/compiler/src/compiler/machine_mapping/get_tensor_set_movement_across_split.cc` line 4 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8Ennrh1TEAnoANmHCQ:-O8Ennrh1TEAnoANmHCR:bxoby85) ([raw file](https://github.com/flexflow/FlexFlow/blob/597e13c0e81b233ef44a1af1bd6ad87ebdeee9f0/lib/compiler/src/compiler/machine_mapping/get_tensor_set_movement_across_split.cc#L4)):*
> ```cpp
> #include "compiler/machine_mapping/abstracted_tensor_set_movement/abstracted_tensor_set_movement.h"
> #include "compiler/machine_mapping/abstracted_tensor_set_movement/get_abstracted_tensor_set_movement_across_split.h"
> #include "compiler/machine_mapping/transitive_reduced_pcg.h"
> ```

some of this imports seem superfluous
___
*[`lib/compiler/src/compiler/machine_mapping/machine_mapping_result.cc` line 26 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8Eqg9MC4ssotLfvhT2:-O8Eqg9MC4ssotLfvhT3:b-rov08n) ([raw file](https://github.com/flexflow/FlexFlow/blob/597e13c0e81b233ef44a1af1bd6ad87ebdeee9f0/lib/compiler/src/compiler/machine_mapping/machine_mapping_result.cc#L26)):*
> ```cpp
> 
>   for (MachineMappingResult const &candidate : candidates) {
>     result = minimize_runtime(result, candidate);
> ```

optionally `foldl`, but it's honestly pretty clear as it is
___
*[`lib/compiler/src/compiler/machine_mapping/machine_mapping_result.cc` line 51 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8ErI0O-27yF70JFe0_:-O8ErI0O-27yF70JFe0a:bcu1ttw) ([raw file](https://github.com/flexflow/FlexFlow/blob/597e13c0e81b233ef44a1af1bd6ad87ebdeee9f0/lib/compiler/src/compiler/machine_mapping/machine_mapping_result.cc#L51)):*
> ```cpp
> 
>   ParallelLayerGuidObliviousMachineMapping mapping = [&] {
>     if (parallel_split_transformation.has_value()
> ```

I think this should be `if (parallel_split_transformation.has_value())` then evaluate whether it should be `LthenR` or `RthenL`, here if the split_transformation has no value it calls it with `LthenR`
___
*[`lib/compiler/src/compiler/machine_mapping/machine_mapping_result.cc` line 97 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8EsLQREI_Pi1cnnN24:-O8EsLQREI_Pi1cnnN25:bj62s8s) ([raw file](https://github.com/flexflow/FlexFlow/blob/597e13c0e81b233ef44a1af1bd6ad87ebdeee9f0/lib/compiler/src/compiler/machine_mapping/machine_mapping_result.cc#L97)):*
> ```cpp
> MachineMappingResult minimize_runtime(MachineMappingResult const &maybe_m1,
>                                       MachineMappingResult const &maybe_m2) {
>   FeasibleMachineMappingResult m1 = ({
> ```

This pattern to get the feasible results seems to appear fairly often here, maybe pacakge it into a separate function?
___
*[`lib/compiler/src/compiler/machine_mapping/machine_mapping_result.cc` line 111 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8EsC5MDbEbbpB5eZ9Z:-O8EsC5MDbEbbpB5eZ9_:bm2gfmf) ([raw file](https://github.com/flexflow/FlexFlow/blob/597e13c0e81b233ef44a1af1bd6ad87ebdeee9f0/lib/compiler/src/compiler/machine_mapping/machine_mapping_result.cc#L111)):*
> ```cpp
>   });
> 
>   if (m2.runtime < m1.runtime) {
> ```

ternary optionally
___
*[`lib/compiler/test/src/compiler/machine_mapping/machine_mapping_problem_tree/get_machine_mapping_problem_tree.cc` line 63 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8F-X4rAvoUc8pkkNKo:-O8F-X4rAvoUc8pkkNKp:b-l6mwxj) ([raw file](https://github.com/flexflow/FlexFlow/blob/597e13c0e81b233ef44a1af1bd6ad87ebdeee9f0/lib/compiler/test/src/compiler/machine_mapping/machine_mapping_problem_tree/get_machine_mapping_problem_tree.cc#L63)):*
> ```cpp
>       UnmappedOpCostEstimateKey input_key = make_input_key(input_shape);
> 
>       PCGBinarySPDecomposition sp_decomposition = \
> ```

remove



_Code quote:_
```cpp
\
```
___
*[`lib/local-execution/src/ops/element_binary.h` line 1 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8F-xXX516v3iA6zGqN:-O8F-xXX516v3iA6zGqO:bfu011c) ([raw file](https://github.com/flexflow/FlexFlow/blob/597e13c0e81b233ef44a1af1bd6ad87ebdeee9f0/lib/local-execution/src/ops/element_binary.h#L1)):*
> ```objc
> #ifndef _FLEXFLOW_ELEMENT_BINARY_H
> ```

change for all `src/ops/` to also include the path? not a big deal



_Code quote:_
```objc
_FLEXFLOW_ELEMENT_BINARY_H
```
___
*[`lib/local-execution/src/ops/layer_norm.h` line 1 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8F0Eel5xUmwr-Gc2rR:-O8F0EemCZlZL4tWdE5L:bqpcfof) ([raw file](https://github.com/flexflow/FlexFlow/blob/597e13c0e81b233ef44a1af1bd6ad87ebdeee9f0/lib/local-execution/src/ops/layer_norm.h#L1)):*
> ```objc
> #ifndef _FLEXFLOW_RUNTIME_SRC_OPS_LAYER_NORM_H
> ```

LOCAL_EXECUTION



_Code quote:_
```objc
RUNTIME
```
___
*[`lib/utils/include/utils/full_binary_tree/find_paths_to_leaf.h` line 16 at r13](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O8F42TJA67sBvyCEMOj:-O8F42TJA67sBvyCEMOk:b1ryjlf) ([raw file](https://github.com/flexflow/FlexFlow/blob/597e13c0e81b233ef44a1af1bd6ad87ebdeee9f0/lib/utils/include/utils/full_binary_tree/find_paths_to_leaf.h#L16)):*
> ```objc
> 
> template <typename ParentLabel,  [...]

2024-10-04 20:34 UTC, wmdi reviewed
> Reviewed 2 of 15 files at r1, 1 of 9 files at r3, 9 of 37 files at r4, 1 of 17 files at r7, 4 of 21 files at r8, 1 of 3 files at r9, 103 of 150 files at r10, 84 of 145 files at r11, 40 of 60 files at r12, 18 of 23 files at r13, 83 of 83 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1459)* status: all files reviewed, 52 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml` line 29 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O5pSW-0DdNHPGa16HB-:-O8Nkgve4aBT0AvzbRis:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/e628c72a07792363d7a25cccd2f93f67291d7e08/lib/compiler/include/compiler/machine_mapping/machine_mapping_context.struct.toml#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I agree up to the point of grouping mutable and non-mutable global variables into the same type as then the mutation properties become unclear (how do I know that your function isn't also mutating the `pcg`?), especially since only one of the members ever mutable. This is one case where I have a strong preference that we split `MachineMappingCache` out so that the function signatures remain clear about what is safe from mutation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-05 18:35 UTC, lockshaw approved these changes

2024-10-08 04:28 UTC, lockshaw approved these changes

2024-10-08 04:46 UTC, merged