Add Candle Uno PCG
flexflow/FlexFlow pull request #1479
Opened 2024-08-29 00:59 UTC by hsdfzhsdfz

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-09-02 19:26 UTC, lockshaw requested changes
Waiting on @hsdfzhsdfz to update this PR to match the style of #1453 

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-:-O5oBqgA8haYlSSiQTiM:bcx530e)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @reyna-abhyankar and @wmdi)



<!-- Sent from Reviewable.io -->

2024-09-06 16:17 UTC, reyna-abhyankar requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 12 unresolved discussions (waiting on @hsdfzhsdfz and @wmdi)

___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 25 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O673FLA-JC-mzU2O7WG:-O673FLA-JC-mzU2O7WH:bhtckls) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L25)):*
> ```TOML
>   "utils/hash/map.h",
> ]
> ```

I'm seeing dropout value as a parameter for building the model: https://github.com/ECP-CANDLE/Benchmarks/blob/f6a3da8818308c9edcd9fedbcf831dd5968efcdd/Pilot1/Uno/uno_baseline_keras2.py#L125

should be a config
___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 43 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O671krSE7XHlv_Czdsm:-O671krSE7XHlv_Czdsn:b-e4cty3) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L43)):*
> ```TOML
> 
> [[fields]]
> name = "input_features"
> ```

can you make these names more descriptive? why is input features a mapping from string to string? (and why not `unordered_map`)
___
*[`lib/models/src/models/candle_uno.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O671HLMETsd3whY4b4w:-O671HLMETsd3whY4b4x:b-fz4j8i) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L6)):*
> ```cpp
> 
> CandleUnoConfig get_default_candle_uno_config() {
>   CandleUnoConfig config(
> ```

Bracket initialization preferred



_Suggestion:_
```cpp
CandleUnoConfig config{...};
```
___
*[`lib/models/src/models/candle_uno.cc` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O670zr88D29Z4Qx0ep0:-O670HCl1IMhB97CcHPR:b-fz4j8i) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L11)):*
> ```cpp
>       /*dense_feature_layers=*/std::vector<int>(8, 4192),
>       /*feature_shapes=*/std::map<std::string, int>(),
>       /*input_features=*/std::map<std::string, std::string>());
> ```

Bracket initialization preferred



_Suggestion:_
```cpp
      /*feature_shapes=*/std::map<std::string, int>{},
      /*input_features=*/std::map<std::string, std::string>{});
```
___
*[`lib/models/src/models/candle_uno.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6719nTAxKH2Igx9NzV:-O6719nTAxKH2Igx9NzW:b6mbeqc) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L24)):*
> ```cpp
>   config.input_features["drug1.fingerprints"] = "drug.fingerprints";
>   config.input_features["drug2.descriptors"] = "drug.descriptors";
>   config.input_features["drug2.fingerprints"] = "drug.fingerprints";
> ```

Why not just initialize the maps first and then pass them to the config?  
___
*[`lib/models/src/models/candle_uno.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674F12ECD-hpLFgiwu:-O674F12ECD-hpLFgiwv:b-ikbyfg) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L24)):*
> ```cpp
>   config.input_features["drug1.fingerprints"] = "drug.fingerprints";
>   config.input_features["drug2.descriptors"] = "drug.descriptors";
>   config.input_features["drug2.fingerprints"] = "drug.fingerprints";
> ```

Can all the raw strings get converted into an enum? That also allows the map type to be more specific. 
___
*[`lib/models/src/models/candle_uno.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6763ZR9OsTVcSYCmrD:-O6763ZR9OsTVcSYCmrE:bd14fky) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L24)):*
> ```cpp
>   config.input_features["drug1.fingerprints"] = "drug.fingerprints";
>   config.input_features["drug2.descriptors"] = "drug.descriptors";
>   config.input_features["drug2.fingerprints"] = "drug.fingerprints";
> ```

Does the string to string mapping ever change from one config to the next? If not, we can just set that outside of the config.
___
*[`lib/models/src/models/candle_uno.cc` line 34 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O673RA5CO4bwmeqmTEx:-O673RA5CO4bwmeqmTEy:b-wbgdi4) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L34)):*
> ```cpp
>   tensor_guid_t t = input;
>   for (auto const dense_dim : config.dense_feature_layers) {
>     t = cgb.dense(t, dense_dim, Activation::RELU, /*use_bias=*/false);
> ```

See the dropout and residual code: https://github.com/ECP-CANDLE/Benchmarks/blob/f6a3da8818308c9edcd9fedbcf831dd5968efcdd/Pilot1/Uno/uno_baseline_keras2.py#L118
___
*[`lib/models/src/models/candle_uno.cc` line 34 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O676ZRZ0bvAs5Th4a4R:-O676ZRZ0bvAs5Th4a4S:bglz3e4) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L34)):*
> ```cpp
>   tensor_guid_t t = input;
>   for (auto const dense_dim : config.dense_feature_layers) {
>     t = cgb.dense(t, dense_dim, Activation::RELU, /*use_bias=*/false);
> ```

Also, you can actual pass in `InitializerAttrs` for computation graph builder. It looks like they use glorot normal
https://github.com/ECP-CANDLE/Benchmarks/blob/f6a3da8818308c9edcd9fedbcf831dd5968efcdd/Pilot1/Uno/uno_baseline_keras2.py#L167

https://github.com/flexflow/FlexFlow/tree/repo-refactor/lib/pcg/include/pcg/initializers. If glorot normal doesn't exist yet, you can just add a `.toml` file for it
___
*[`lib/models/src/models/candle_uno.cc` line 56 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674dkcCu0L0AzTNEZP:-O674dkcCu0L0AzTNEZQ:b-glgviu) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L56)):*
> ```cpp
>     if (type.find(".") != std::string::npos) {
>       std::string base_type = type.substr(0, type.find("."));
>       if (base_type == "cell" || base_type == "drug") {
> ```

Enums would simplify this string parsing stuff greatly. 



_Code quote:_
```cpp
    if (type.find(".") != std::string::npos) {
      std::string base_type = type.substr(0, type.find("."));
      if (base_type == "cell" || base_type == "drug") {
```
___
*[`lib/models/src/models/candle_uno.cc` line 85 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6768iU-SPP6cNwdA3I:-O6768iU-SPP6cNwdA3J:b4uk7g2) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L85)):*
> ```cpp
>       cgb.concat(encoded_inputs.size(), encoded_inputs, /*axis=*/-1);
>   for (auto const dense_layer_dim : config.dense_layers) {
>     output = cgb.dense(
> ```

See https://github.com/ECP-CANDLE/Benchmarks/blob/f6a3da8818308c9edcd9fedbcf831dd5968efcdd/Pilot1/Uno/uno_baseline_keras2.py#L220

Dropout here too
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 716 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674rH80RUHIkGUmCvs:-O674rH80RUHIkGUmCvt:biuffro) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/pcg/src/pcg/computation_graph_builder.cc#L716)):*
> ```cpp
>     int axis,
>     std::optional<std::string> const &maybe_name) {
>   // NOT_IMPLEMENTED
> ```

can this get implemented?


<!-- Sent from Reviewable.io -->

2024-09-06 16:36 UTC, lockshaw requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 18 unresolved discussions (waiting on @hsdfzhsdfz, @lockshaw, and @wmdi)

___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 40 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67AT4u59fb5YVtXpHL:-O67AT4u59fb5YVtXpHM:bx4htio) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L40)):*
> ```TOML
> [[fields]]
> name = "feature_shapes"
> type = "std::map<std::string, int>"
> ```

Should probably be `feature_num_channels` or something like that? `feature_shapes` makes it sound like it should map to `TensorShape`
___
*[`lib/models/src/models/candle_uno.cc` line 43 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67Amzk8czS2J8pDW2I:-O67Amzk8czS2J8pDW2J:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L43)):*
> ```cpp
>   ComputationGraphBuilder cgb;
> 
>   auto create_input_tensor = [&](FFOrdered<size_t> dims) -> tensor_guid_t {
> ```





_Suggestion:_
```cpp
  auto create_input_tensor = [&](FFOrdered<size_t> const &dims) -> tensor_guid_t {
```
___
*[`lib/models/src/models/candle_uno.cc` line 66 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67A0kNA4CibkPNeqk0:-O67A0kNA4CibkPNeqk1:b-p9vjp0) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L66)):*
> ```cpp
> 
>   for (auto const &input_feature : config.input_features) {
>     auto const &feature_name = input_feature.second;
> ```

Prefer explicit typenames over `auto` unless the full name is super long
___
*[`lib/models/src/models/candle_uno.cc` line 67 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67A5ue5zu7bbWu_skB:-O67A5ue5zu7bbWu_skC:btzlndi) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L67)):*
> ```cpp
>   for (auto const &input_feature : config.input_features) {
>     auto const &feature_name = input_feature.second;
>     assert(config.feature_shapes.find(feature_name) !=
> ```

`contains_key` from `utils/containers/contains_key.h`

Also, `at` already checks this, so the `assert` is arguably superfluous
___
*[`lib/models/src/models/candle_uno.cc` line 74 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67BDLn9I-qRDtcZFAb:-O67BDLn9I-qRDtcZFAc:bkjezv0) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L74)):*
> ```cpp
>     all_inputs.push_back(input);
> 
>     if (input_models.find(feature_name) != input_models.end()) {
> ```

`contains` from `utils/containers/contains.h`
___
*[`lib/models/src/models/candle_uno.cc` line 84 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67B6A2AVZ3Cmx5hdLd:-O67B6A2AVZ3Cmx5hdLe:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L84)):*
> ```cpp
>   tensor_guid_t output =
>       cgb.concat(encoded_inputs.size(), encoded_inputs, /*axis=*/-1);
>   for (auto const dense_layer_dim : config.dense_layers) {
> ```





_Suggestion:_
```cpp
  for (auto const &dense_layer_dim : config.dense_layers) {
```
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 716 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674rH80RUHIkGUmCvs:-O679s2cArkEqr9iABS2:b-l0i8l0) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/pcg/src/pcg/computation_graph_builder.cc#L716)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

can this get implemented?
</blockquote></details>

This is on me @reyna-abhyankar, currently working on it :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2024-09-06 16:44 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 22 unresolved discussions (waiting on @hsdfzhsdfz and @wmdi)

___
*[`lib/models/include/models/candle_uno.h` line 0 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67D6xk2kbtrls1kuKs:-O67D6xk2kbtrls1kuKt:b-7fvwsh) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno.h#L0)):*
Move to `lib/models/include/models/candle_uno/candle_uno.h`
___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 0 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67D2mJ0QWPLcQ_Dtts:-O67D2mJ0QWPLcQ_Dttt:b-pn0f1b) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L0)):*
Move to `lib/models/include/models/candle_uno/candle_uno_config.struct.toml`
___
*[`lib/models/src/models/candle_uno.cc` line 0 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67D-296qGw3hSx9DVm:-O67D-296qGw3hSx9DVn:b-ovsizn) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L0)):*
Move to `lib/models/src/models/candle_uno/candle_uno.cc`
___
*[`lib/models/test/src/models/candle_uno.cc` line 0 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67DD20BBTF2_8djh1w:-O67DD20BBTF2_8djh1x:b-mj559u) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/test/src/models/candle_uno.cc#L0)):*
Move to `lib/models/test/src/models/candle_uno/candle_uno.cc`


<!-- Sent from Reviewable.io -->

2024-09-06 20:11 UTC, lockshaw requested changes
> Reviewed 31 of 31 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 23 unresolved discussions (waiting on @hsdfzhsdfz, @reyna-abhyankar, and @wmdi)

___
*[`lib/models/src/models/candle_uno.cc` line 83 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67xWma7vx4RcoAOhR5:-O67xWma7vx4RcoAOhR6:b-8rrzsi) ([raw file](https://github.com/flexflow/FlexFlow/blob/5d7acf66c7b675b8e3d0b950a852476149c8da08/lib/models/src/models/candle_uno.cc#L83)):*
> ```cpp
> 
>   tensor_guid_t output =
>       cgb.concat(encoded_inputs, /*axis=*/-1);
> ```

Currently you can't pass negative indices. It's on the list of things to add, but for now this should be converted to a non-negative index
___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 716 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674rH80RUHIkGUmCvs:-O67xRg5BcTRq5Zn6gm3:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/pcg/src/pcg/computation_graph_builder.cc#L716)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This is on me @reyna-abhyankar, currently working on it :slightly_smiling_face:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-11 12:07 UTC, hsdfzhsdfz reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 23 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/models/include/models/candle_uno.h` line  at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67D6xk2kbtrls1kuKs:-O6VvBz-3Q5MaDEAdVux:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno.h#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `lib/models/include/models/candle_uno/candle_uno.h`
</blockquote></details>

Done.
___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 40 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67AT4u59fb5YVtXpHL:-O6Vw0cf4v6m7pEX9m3B:bw4pqma) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should probably be `feature_num_channels` or something like that? `feature_shapes` makes it sound like it should map to `TensorShape`
</blockquote></details>

I guess that's to align with the original model. So prefer not to change it.
___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 43 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O671krSE7XHlv_Czdsm:-O6Vw5xM9KhRa8tMPR-L:b-8wzofx) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L43)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

can you make these names more descriptive? why is input features a mapping from string to string? (and why not `unordered_map`)
</blockquote></details>

The name is to match with original implementation. We can check with Zhihao that whether using std::map is to maintain an order of the keys. won't change for now
___
*[`lib/models/include/models/candle_uno_config.struct.toml` line  at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67D2mJ0QWPLcQ_Dtts:-O6VvCKP0dqorod3toN7:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `lib/models/include/models/candle_uno/candle_uno_config.struct.toml`
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O671HLMETsd3whY4b4w:-O6VwQ0W96hJYZMpWTDm:b-w5tfo5) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L6)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Bracket initialization preferred
</blockquote></details>

Value initialization is the same as `()` here. They are the same.
___
*[`lib/models/src/models/candle_uno.cc` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O670zr88D29Z4Qx0ep0:-O6VwWgm-3iNeeB-252v:bn8lf8a) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L11)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Bracket initialization preferred
</blockquote></details>

Not needed actually. By default, C++ will do value initialization for user-defined classes (such as std::map).
___
*[`lib/models/src/models/candle_uno.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6719nTAxKH2Igx9NzV:-O6VweGe9dEF73e2RHw2:b-affb3g) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L24)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Why not just initialize the maps first and then pass them to the config?
</blockquote></details>

It's a bit messy to include so many things in the constructor list. Plus, people may want to add more key-value pairs in the future. So I thought doing this is easier to understand and extend.
___
*[`lib/models/src/models/candle_uno.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674F12ECD-hpLFgiwu:-O6VwstX01-u0HaHzIGJ:b772vj7) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L24)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Can all the raw strings get converted into an enum? That also allows the map type to be more specific.
</blockquote></details>

That doesn't make sense - as we don't know how many are there in the dataset.
___
*[`lib/models/src/models/candle_uno.cc` line 24 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6763ZR9OsTVcSYCmrD:-O6VwzPa8p4AUOxyYFVN:bokb687) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L24)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Does the string to string mapping ever change from one config to the next? If not, we can just set that outside of the config.
</blockquote></details>

I think they depend on the dataset - maybe that's why they are part of the "configs" in the original implementation as well.
___
*[`lib/models/src/models/candle_uno.cc` line 43 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67Amzk8czS2J8pDW2I:-O6VxDgd38PbNcMIybuW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L43)):*
> ```cpp
>   ComputationGraphBuilder cgb;
> 
>   auto create_input_tensor = [&](FFOrdered<size_t> dims) -> tensor_guid_t {
> ```

Done.
___
*[`lib/models/src/models/candle_uno.cc` line 56 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674dkcCu0L0AzTNEZP:-O6VxVl09li8dLbGssgn:b-7kq4qq) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L56)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Enums would simplify this string parsing stuff greatly.
</blockquote></details>

As mentioned above, enum may not support alternative dataset well.
___
*[`lib/models/src/models/candle_uno.cc` line 66 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67A0kNA4CibkPNeqk0:-O6Vy2t89ocku_ATJC9R:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L66)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer explicit typenames over `auto` unless the full name is super long
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno.cc` line 67 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67A5ue5zu7bbWu_skB:-O6Vxhak0gMAteVsgMB0:bgqxphz) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L67)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`contains_key` from `utils/containers/contains_key.h`

Also, `at` already checks this, so the `assert` is arguably superfluous
</blockquote></details>

I'll just remove it. Assert is optimized out in the optimization mode. This was just to match with the original C++ version.
___
*[`lib/models/src/models/candle_uno.cc` line 84 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67B6A2AVZ3Cmx5hdLd: [...]

2024-09-11 12:19 UTC, hsdfzhsdfz reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 23 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 25 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O673FLA-JC-mzU2O7WG:-O6VzDqq74U2QhYn_Zvj:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L25)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

I'm seeing dropout value as a parameter for building the model: https://github.com/ECP-CANDLE/Benchmarks/blob/f6a3da8818308c9edcd9fedbcf831dd5968efcdd/Pilot1/Uno/uno_baseline_keras2.py#L125

should be a config
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O671HLMETsd3whY4b4w:-O6W06mS5bVJSmFH366U:b8r86sg) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L6)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Value initialization is the same as `()` here. They are the same.
</blockquote></details>

Oh, actually here `()` is preferred, because we want to explicitly call its constructor. It will cause confusion if the class has an initializer_list constructor. It's similar to we need to be careful to construct std::vector.
___
*[`lib/models/src/models/candle_uno.cc` line 11 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O670zr88D29Z4Qx0ep0:-O6W0Qgj4iIjsT7DEeUz:bo9rfrx) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L11)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Not needed actually. By default, C++ will do value initialization for user-defined classes (such as std::map).
</blockquote></details>

But I changed it anyway.
___
*[`lib/models/src/models/candle_uno.cc` line 34 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O673RA5CO4bwmeqmTEx:-O6VztbU7s7rLtooyqb2:bebrt1w) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L34)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

See the dropout and residual code: https://github.com/ECP-CANDLE/Benchmarks/blob/f6a3da8818308c9edcd9fedbcf831dd5968efcdd/Pilot1/Uno/uno_baseline_keras2.py#L118
</blockquote></details>

Will do
___
*[`lib/models/src/models/candle_uno.cc` line 34 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O676ZRZ0bvAs5Th4a4R:-O6W-7o1Awno73tOdjzg:bmc1lp8) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L34)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Also, you can actual pass in `InitializerAttrs` for computation graph builder. It looks like they use glorot normal
https://github.com/ECP-CANDLE/Benchmarks/blob/f6a3da8818308c9edcd9fedbcf831dd5968efcdd/Pilot1/Uno/uno_baseline_keras2.py#L167

https://github.com/flexflow/FlexFlow/tree/repo-refactor/lib/pcg/include/pcg/initializers. If glorot normal doesn't exist yet, you can just add a `.toml` file for it
</blockquote></details>

Will do. I saw there is a glorot toml file there. Do we need to actually implement it in order to use here? Or it's just fine to use without actual implementation?
___
*[`lib/models/src/models/candle_uno.cc` line 74 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67BDLn9I-qRDtcZFAb:-O6W0-T2-ZzZ4vJ40LNO:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L74)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`contains` from `utils/containers/contains.h`
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno.cc` line 85 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6768iU-SPP6cNwdA3I:-O6W-M729t0fvIg4ffgu:bebrt1w) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L85)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

See https://github.com/ECP-CANDLE/Benchmarks/blob/f6a3da8818308c9edcd9fedbcf831dd5968efcdd/Pilot1/Uno/uno_baseline_keras2.py#L220

Dropout here too
</blockquote></details>

Will do


<!-- Sent from Reviewable.io -->

2024-09-11 12:22 UTC, hsdfzhsdfz reviewed
There were quite a few formatting change after I ran the formatter. Not sure if that was because a previous change was not formatted properly?

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-:-O6W19Si0bn81fOtqsEK:b-gj62dg)* status: 17 of 34 files reviewed, 23 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)



<!-- Sent from Reviewable.io -->

2024-09-12 19:45 UTC, lockshaw commented
*[`lib/models/src/models/candle_uno.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O671HLMETsd3whY4b4w:-O6bkSQAB2kza5TRJsNU:b-6ctt9u) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L6)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Oh, actually here `()` is preferred, because we want to explicitly call its constructor. It will cause confusion if the class has an initializer_list constructor. It's similar to we need to be careful to construct std::vector.
</blockquote></details>

@hsdfzhsdfz here's a discussion of this convention: https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O694LDi4I_FCg07MZB_. I agree that there's not a clear winner between the two, but for the most part FlexFlow has settled on using `{}` initialization in cases where the two are equivalent (partially for the reasons outlined in the discussion and partly for history reasons, i.e., `visitable`). I'm open to a discussion of if we want to change/remove this convention going forward, but let's do that in parallel with this PR and not as part of it :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2024-09-13 01:29 UTC, lockshaw commented
*[`lib/models/src/models/candle_uno.cc` line 34 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O676ZRZ0bvAs5Th4a4R:-O6cFsrD2yObVKsDB9sM:b-k0hea0) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L34)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Will do. I saw there is a glorot toml file there. Do we need to actually implement it in order to use here? Or it's just fine to use without actual implementation?
</blockquote></details>

`ComputationGraphBuilder::dense` has a `std::optional<InitializerAttrs>` arguments for each weight, so you'd just have to pass in a `InitializerAttrs{GlorotUniformAttrs{...}}` for that argument


<!-- Sent from Reviewable.io -->

2024-09-13 16:46 UTC, lockshaw requested changes
I probably just forgot to run the formatter after I added support for `Concat`

> Reviewed 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-:-O6gG4kgD0k6nkRatXM5:b-vnx3ek)* status: all files reviewed, 15 unresolved discussions (waiting on @hsdfzhsdfz, @reyna-abhyankar, and @wmdi)

___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 40 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67AT4u59fb5YVtXpHL:-O6gGP_GAAL4C2f54USj:b7agjtr) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L40)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

I guess that's to align with the original model. So prefer not to change it.
</blockquote></details>

Fair enough. It would be nice though to have a doxygen docstring explaining the meaning of these fields w.r.t. the constructed computation graph. It's not trivial to add docs for `dtgen` types right now, so maybe best to add this to the docstring for `get_candle_uno_computation_graph`?
___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 43 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O671krSE7XHlv_Czdsm:-O6gGilH87JoTWz_6-1m:b-6hsjyd) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L43)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

The name is to match with original implementation. We can check with Zhihao that whether using std::map is to maintain an order of the keys. won't change for now
</blockquote></details>

See https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67AT4u59fb5YVtXpHL for a potential way to still match the old implementation but make things a bit more readable
___
*[`lib/models/src/models/candle_uno/candle_uno.cc` line 34 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6gFFjJ3kEZknQkNeJg:-O6gFFjJ3kEZknQkNeJh:bx5t2r1) ([raw file](https://github.com/flexflow/FlexFlow/blob/b31f4792a28efe9c78b73eb500786941e775ddf9/lib/models/src/models/candle_uno/candle_uno.cc#L34)):*
> ```cpp
>                                               tensor_guid_t const &input) {
>   tensor_guid_t t = input;
>   for (auto const dense_dim : config.dense_feature_layers) {
> ```

Prefer explicit type name over `auto`



_Code quote:_
```cpp
auto const dense_dim
```
___
*[`lib/models/src/models/candle_uno/candle_uno.cc` line 82 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6gFU_CE2mc3UOYkHAe:-O6gFU_CE2mc3UOYkHAf:bx5t2r1) ([raw file](https://github.com/flexflow/FlexFlow/blob/b31f4792a28efe9c78b73eb500786941e775ddf9/lib/models/src/models/candle_uno/candle_uno.cc#L82)):*
> ```cpp
> 
>   tensor_guid_t output = cgb.concat(encoded_inputs, /*axis=*/1);
>   for (auto const &dense_layer_dim : config.dense_layers) {
> ```

Prefer explicit type name over `auto`


<!-- Sent from Reviewable.io -->

2024-09-15 15:46 UTC, hsdfzhsdfz reviewed
Got it, thx

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-:-O6qCRj4CdGjbcdBCE_-:b-tbjvkk)* status: 30 of 34 files reviewed, 15 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 40 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67AT4u59fb5YVtXpHL:-O6q7E4X57HhYi5v6oFJ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Fair enough. It would be nice though to have a doxygen docstring explaining the meaning of these fields w.r.t. the constructed computation graph. It's not trivial to add docs for `dtgen` types right now, so maybe best to add this to the docstring for `get_candle_uno_computation_graph`?
</blockquote></details>

Done.
___
*[`lib/models/include/models/candle_uno_config.struct.toml` line 43 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O671krSE7XHlv_Czdsm:-O6q97s13udAWtOJ4IYr:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/include/models/candle_uno_config.struct.toml#L43)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

See https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O67AT4u59fb5YVtXpHL for a potential way to still match the old implementation but make things a bit more readable
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O671HLMETsd3whY4b4w:-O6q7g4635_sHEPvK2d6:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

@hsdfzhsdfz here's a discussion of this convention: https://reviewable.io/reviews/flexflow/FlexFlow/1459#-O694LDi4I_FCg07MZB_. I agree that there's not a clear winner between the two, but for the most part FlexFlow has settled on using `{}` initialization in cases where the two are equivalent (partially for the reasons outlined in the discussion and partly for history reasons, i.e., `visitable`). I'm open to a discussion of if we want to change/remove this convention going forward, but let's do that in parallel with this PR and not as part of it :slightly_smiling_face:
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno.cc` line 34 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O673RA5CO4bwmeqmTEx:-O6qCdhWAEuWWyoBHLCW:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L34)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno.cc` line 34 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O676ZRZ0bvAs5Th4a4R:-O6qFXgd3jU2g_p-TCjB:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L34)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`ComputationGraphBuilder::dense` has a `std::optional<InitializerAttrs>` arguments for each weight, so you'd just have to pass in a `InitializerAttrs{GlorotUniformAttrs{...}}` for that argument
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno.cc` line 85 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6768iU-SPP6cNwdA3I:-O6qCvD-BeuwxrYGLzhT:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L85)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno/candle_uno.cc` line 34 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6gFFjJ3kEZknQkNeJg:-O6q7zHG76DmexBBqCGy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b31f4792a28efe9c78b73eb500786941e775ddf9/lib/models/src/models/candle_uno/candle_uno.cc#L34)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer explicit type name over `auto`
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno/candle_uno.cc` line 82 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O6gFU_CE2mc3UOYkHAe:-O6qCh6K9NUtaYC4yw2n:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/b31f4792a28efe9c78b73eb500786941e775ddf9/lib/models/src/models/candle_uno/candle_uno.cc#L82)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer explicit type name over `auto`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-15 15:47 UTC, hsdfzhsdfz reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: 30 of 34 files reviewed, 15 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/pcg/src/pcg/computation_graph_builder.cc` line 716 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674rH80RUHIkGUmCvs:-O6qMaKN5qbRaUWJknH9:b-zcjvte) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/pcg/src/pcg/computation_graph_builder.cc#L716)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks


<!-- Sent from Reviewable.io -->

2024-09-16 00:09 UTC, reyna-abhyankar requested changes
> Reviewed 1 of 17 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 5 unresolved discussions (waiting on @hsdfzhsdfz, @lockshaw, and @wmdi)

___
*[`lib/models/src/models/candle_uno.cc` line 34 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O676ZRZ0bvAs5Th4a4R:-O6s9IRd92rdqzmm4oGK:b89ww87) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L34)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`GlorotUniform` and `GlorotNormal` should be different right? 
___
*[`lib/models/src/models/candle_uno.cc` line 56 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674dkcCu0L0AzTNEZP:-O6s6OI_BGMOlr8lXasL:bhcii4l) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L56)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

As mentioned above, enum may not support alternative dataset well.
</blockquote></details>

As per wednesday 9/11 meeting, this is fine, but maybe just add some comments that explain the string parsing. 


<!-- Sent from Reviewable.io -->

2024-09-21 14:19 UTC, hsdfzhsdfz reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 5 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/models/src/models/candle_uno.cc` line 34 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O676ZRZ0bvAs5Th4a4R:-O7JtEZWAha6iLw9YDnO:bi9wy22) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L34)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

`GlorotUniform` and `GlorotNormal` should be different right?
</blockquote></details>

Oh right, good catch! Added glorot normal toml file. Thank you @reyna-abhyankar !
___
*[`lib/models/src/models/candle_uno.cc` line 56 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674dkcCu0L0AzTNEZP:-O7Jv_a37Hb9jvDzAJHF:b-oesf5o) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L56)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

As per wednesday 9/11 meeting, this is fine, but maybe just add some comments that explain the string parsing.
</blockquote></details>

Yes, added comments.


<!-- Sent from Reviewable.io -->

2024-09-21 17:48 UTC, lockshaw requested changes
> Reviewed 3 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 5 unresolved discussions (waiting on @hsdfzhsdfz, @reyna-abhyankar, and @wmdi)

___
*[`lib/models/include/models/candle_uno/candle_uno.h` line 18 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O7KfaCh1QmHmqm06UJh:-O7KfaCh1QmHmqm06UJi:b16iaxs) ([raw file](https://github.com/flexflow/FlexFlow/blob/feb8847b0c0eaa6c3ea665868e430973dee1b36f/lib/models/include/models/candle_uno/candle_uno.h#L18)):*
> ```objc
> 
> /**
>  * @brief Get the default configs of Candle Uno model.
> ```

Where is this config from? A link to where you got the values from would be really nice to have in the docstring
___
*[`lib/models/include/models/candle_uno/candle_uno.h` line 28 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O7KfoPYDR-PeORxKdPo:-O7KfoPYDR-PeORxKdPp:b-vark9i) ([raw file](https://github.com/flexflow/FlexFlow/blob/feb8847b0c0eaa6c3ea665868e430973dee1b36f/lib/models/include/models/candle_uno/candle_uno.h#L28)):*
> ```objc
>  * of channels for the feature.
>  * @note CandleUnoConfig.input_features is a map from specific data identifier
>  * in the dataset to the feature name used in this model.
> ```

iirc @note highlights the text with a bright yellow background or symbol or something, which is probably overkill here



_Suggestion:_
```objc
 * @details CandleUnoConfig.feature_shapes is a map from feature name to the number
 * of channels for the feature, and CandleUnoConfig.input_features is a map from specific data identifier
 * in the dataset to the feature name used in this model.
```
___
*[`lib/models/src/models/candle_uno.cc` line 56 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674dkcCu0L0AzTNEZP:-O7KgHTj8surMpocwGb3:bk2ms2c) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L56)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Yes, added comments.
</blockquote></details>

Thanks, the links to the reference implementation are super helpful--feel free to add more of those in any places where it would be helpful
___
*[`lib/models/src/models/candle_uno/candle_uno.cc` line 114 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O7KgVFr18KEZkLvnffc:-O7KgVFr18KEZkLvnffd:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/feb8847b0c0eaa6c3ea665868e430973dee1b36f/lib/models/src/models/candle_uno/candle_uno.cc#L114)):*
> ```cpp
>   }
>   output = cgb.dense(output,
>                      1,
> ```





_Suggestion:_
```cpp
                     /*outDim=*/1,
```


<!-- Sent from Reviewable.io -->

2024-09-21 18:17 UTC, hsdfzhsdfz reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 5 unresolved discussions (waiting on @lockshaw, @note, @reyna-abhyankar, and @wmdi)

___
*[`lib/models/include/models/candle_uno/candle_uno.h` line 18 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O7KfaCh1QmHmqm06UJh:-O7KmQPG5tyL_kk96bE6:bmvnf8w) ([raw file](https://github.com/flexflow/FlexFlow/blob/feb8847b0c0eaa6c3ea665868e430973dee1b36f/lib/models/include/models/candle_uno/candle_uno.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Where is this config from? A link to where you got the values from would be really nice to have in the docstring
</blockquote></details>

These are inherited from the previous FF implementation. I believe the numbers came from the dataset used by the original model: https://github.com/ECP-CANDLE/Benchmarks/tree/f6a3da8818308c9edcd9fedbcf831dd5968efcdd/Pilot1/Uno

```
Input features shapes:
  dose1: (1,)
  dose2: (1,)
  cell.rnaseq: (942,)
  drug1.descriptors: (5270,)
  drug1.fingerprints: (2048,)
  drug2.descriptors: (5270,)
  drug2.fingerprints: (2048,)
```
___
*[`lib/models/include/models/candle_uno/candle_uno.h` line 28 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O7KfoPYDR-PeORxKdPo:-O7KnIqs1_1eSSiTLnrx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/feb8847b0c0eaa6c3ea665868e430973dee1b36f/lib/models/include/models/candle_uno/candle_uno.h#L28)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

iirc @note highlights the text with a bright yellow background or symbol or something, which is probably overkill here
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno.cc` line 56 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O674dkcCu0L0AzTNEZP:-O7KljYP1kao3UIUrQvw:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/363a83231a96d4f34e7acb6f13ec4ede71868c47/lib/models/src/models/candle_uno.cc#L56)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Thanks, the links to the reference implementation are super helpful--feel free to add more of those in any places where it would be helpful
</blockquote></details>

Done.
___
*[`lib/models/src/models/candle_uno/candle_uno.cc` line 114 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O7KgVFr18KEZkLvnffc:-O7KleHA4ybB3rMBmIDC:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/feb8847b0c0eaa6c3ea665868e430973dee1b36f/lib/models/src/models/candle_uno/candle_uno.cc#L114)):*
> ```cpp
>   }
>   output = cgb.dense(output,
>                      1,
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-09-21 21:25 UTC, lockshaw requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 3 unresolved discussions (waiting on @hsdfzhsdfz, @reyna-abhyankar, and @wmdi)

___
*[`lib/models/include/models/candle_uno/candle_uno.h` line 18 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O7KfaCh1QmHmqm06UJh:-O7LTFhm38jbNBlVk-7W:b-q617cf) ([raw file](https://github.com/flexflow/FlexFlow/blob/feb8847b0c0eaa6c3ea665868e430973dee1b36f/lib/models/include/models/candle_uno/candle_uno.h#L18)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

These are inherited from the previous FF implementation. I believe the numbers came from the dataset used by the original model: https://github.com/ECP-CANDLE/Benchmarks/tree/f6a3da8818308c9edcd9fedbcf831dd5968efcdd/Pilot1/Uno

```
Input features shapes:
  dose1: (1,)
  dose2: (1,)
  cell.rnaseq: (942,)
  drug1.descriptors: (5270,)
  drug1.fingerprints: (2048,)
  drug2.descriptors: (5270,)
  drug2.fingerprints: (2048,)
```
</blockquote></details>

Great, can you add that link to the docstring?


<!-- Sent from Reviewable.io -->

2024-09-22 01:38 UTC, hsdfzhsdfz reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: all files reviewed, 3 unresolved discussions (waiting on @lockshaw, @reyna-abhyankar, and @wmdi)

___
*[`lib/models/include/models/candle_uno/candle_uno.h` line 18 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-O7KfaCh1QmHmqm06UJh:-O7MMkZT9ifabFj1Q19y:br0kh83) ([raw file](https://github.com/flexflow/FlexFlow/blob/feb8847b0c0eaa6c3ea665868e430973dee1b36f/lib/models/include/models/candle_uno/candle_uno.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Great, can you add that link to the docstring?
</blockquote></details>

Okay, added


<!-- Sent from Reviewable.io -->

2024-09-22 14:31 UTC, reyna-abhyankar approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479#-:-O7P8DlF-8l6KuLbDp99:bnfp4nl)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @lockshaw and @wmdi)



<!-- Sent from Reviewable.io -->

2024-09-23 16:32 UTC, lockshaw submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2024-09-23 18:47 UTC, lockshaw submitted a review, later dismissed
> Reviewed 29 of 29 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2024-09-23 19:25 UTC, lockshaw approved these changes
> Reviewed 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1479)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wmdi)



<!-- Sent from Reviewable.io -->

2024-09-23 19:39 UTC, merged