Add BERT model PCG
flexflow/FlexFlow pull request #1488
Opened 2024-09-05 00:47 UTC by hsdfzhsdfz

**Description of changes:**

This PR adds the PCG of BERT.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-09-06 16:33 UTC, reyna-abhyankar requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 3 unresolved discussions (waiting on @hsdfzhsdfz and @lockshaw)

___
*[`lib/models/include/models/bert_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O6790vxBSMhb__GVG4B:-O6790vxBSMhb__GVG4C:bsf4b5d) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "BertConfig"
> ```

Did you look at https://github.com/google-research/bert/blob/eedf5716ce1268e56f0a50264a88cafad334ac61/modeling.py#L31?

It seems like there are a couple of missing configs, such as activation function, attention dropout
___
*[`lib/models/include/models/bert_config.struct.toml` line 18 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O6784tV4v5P3T3TzFYK:-O6784tWAgxD8OFsZIyP:b-etlvnt) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L18)):*
> ```TOML
> 
> [[fields]]
> name = "num_features"
> ```

Is this the same as `hidden_size`? If so, can you rename it to be consistent with the terminology used by the paper.
___
*[`lib/models/src/models/bert.cc` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O678axi-yBb0EoMuH_R:-O678axi-yBb0EoMuH_S:bs2x25l) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/src/models/bert.cc#L13)):*
> ```cpp
>                     /*dim_feedforward=*/3072,
>                     /*dropout=*/0.1,
>                     /*layer_norm_eps=*/1e-12,
> ```

Where did you find this value?


<!-- Sent from Reviewable.io -->

2024-09-06 16:42 UTC, lockshaw requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 8 unresolved discussions (waiting on @hsdfzhsdfz)

___
*[`lib/models/include/models/bert.h` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67BtrdCSNqff-Ykp4i:-O67Btre0o4GpSiC6Uzm:b-mkkoxp) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert.h#L0)):*
Move to `models/bert/bert.h` (going forward all models should have their own subdirectory of `models` which should also contain the `.struct.toml` file for their config struct if applicable 
___
*[`lib/models/include/models/bert.h` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67Bhi53X77VEp7eAS6:-O67Bhi53X77VEp7eAS7:b1zyc1c) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert.h#L21)):*
> ```objc
> 
> /**
>  * @brief Get the base config of the BERT model.
> ```

Which default config is this? If this is from a paper, having a link to the paper (ideally with a page number/figure number where it is stated) would be good
___
*[`lib/models/include/models/bert.h` line 27 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67CCl_2PwqheQ5_vfS:-O67CCl_2PwqheQ5_vfT:b6127xd) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert.h#L27)):*
> ```objc
> /**
>  * @brief Get the BERT computation graph.
>  *
> ```

You mentioned some subtleties between different variants of BERT at the last meeting? Those and the corresponding choices made should be explicitly called out in this docstring
___
*[`lib/models/src/models/bert.cc` line 34 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67CYESBtZoM0Jr-Od6:-O67CYESBtZoM0Jr-Od7:bz36fkh) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/src/models/bert.cc#L34)):*
> ```cpp
>                                         BertConfig const &config,
>                                         tensor_guid_t const &input) {
>   std::vector<int> layer_norm_axis{2}; // Normalize the last dim
> ```

What does this comment refer to?
___
*[`lib/models/src/models/bert.cc` line 34 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67CZam1tYYdVJzwwv2:-O67CZam1tYYdVJzwwv3:btafb9t) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/src/models/bert.cc#L34)):*
> ```cpp
>                                         BertConfig const &config,
>                                         tensor_guid_t const &input) {
>   std::vector<int> layer_norm_axis{2}; // Normalize the last dim
> ```

If you are intending to create a `vector` with a single element (the number 2), `std::vector<int> layer_norm_axis = {2};` would be a bit clearer


<!-- Sent from Reviewable.io -->

2024-09-06 16:47 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 11 unresolved discussions (waiting on @hsdfzhsdfz)

___
*[`lib/models/include/models/bert_config.struct.toml` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67DmHe2uZ463DgjdhZ:-O67DmHe2uZ463Dgjdh_:b-wi8htr) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L0)):*
Move to `lib/models/include/models/bert/bert_config.struct.toml`
___
*[`lib/models/src/models/bert.cc` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67Dxkn6QHswWvV4fFr:-O67Dxkn6QHswWvV4fFs:b-udfy2r) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/src/models/bert.cc#L0)):*
Move to `lib/models/src/models/bert/bert.cc`
___
*[`lib/models/test/src/models/bert.cc` line 0 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67DsD5-gMHVtqBXOwZ:-O67DsD5-gMHVtqBXOw_:b-eypv9u) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/test/src/models/bert.cc#L0)):*
Move to `lib/models/test/src/models/bert/bert.cc`


<!-- Sent from Reviewable.io -->

2024-09-15 15:55 UTC, hsdfzhsdfz reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/models/include/models/bert.h` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67Bhi53X77VEp7eAS6:-O6qKEgH-eRjol1OeXQE:b-z2x6nj) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert.h#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Which default config is this? If this is from a paper, having a link to the paper (ideally with a page number/figure number where it is stated) would be good
</blockquote></details>

These are the default configs of hugging face here: https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig
___
*[`lib/models/include/models/bert.h` line 27 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67CCl_2PwqheQ5_vfS:-O6qKfXuBRtaUtUeXI4Y:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert.h#L27)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

You mentioned some subtleties between different variants of BERT at the last meeting? Those and the corresponding choices made should be explicitly called out in this docstring
</blockquote></details>

Done.
___
*[`lib/models/include/models/bert.h` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67BtrdCSNqff-Ykp4i:-O6qKBjp5VDhqdObsY7a:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert.h#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `models/bert/bert.h` (going forward all models should have their own subdirectory of `models` which should also contain the `.struct.toml` file for their config struct if applicable
</blockquote></details>

Done.
___
*[`lib/models/include/models/bert_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O6790vxBSMhb__GVG4B:-O6qNGvVA850BxJzZDhh:b-hx85g4) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L2)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Did you look at https://github.com/google-research/bert/blob/eedf5716ce1268e56f0a50264a88cafad334ac61/modeling.py#L31?

It seems like there are a couple of missing configs, such as activation function, attention dropout
</blockquote></details>

Hmm, not really... I referred more to the Hugging Face version at https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig. And I left only one dropout config and one default activation.

Do we want to have the ability to alter the dropout / activation for this example? If so, I can add them.

cc. @lockshaw 
___
*[`lib/models/include/models/bert_config.struct.toml` line 18 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O6784tV4v5P3T3TzFYK:-O6qO5ni3LmmUq6-C2sH:b-9bgjmt) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L18)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Is this the same as `hidden_size`? If so, can you rename it to be consistent with the terminology used by the paper.
</blockquote></details>

Yes, makes sense. I have renamed it. Thx
___
*[`lib/models/include/models/bert_config.struct.toml` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67DmHe2uZ463DgjdhZ:-O6qL8mM5L9fN0en9pq0:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `lib/models/include/models/bert/bert_config.struct.toml`
</blockquote></details>

Done.
___
*[`lib/models/src/models/bert.cc` line 13 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O678axi-yBb0EoMuH_R:-O6qLExZ02Cy3iXeAB1C:b-z2x6nj) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/src/models/bert.cc#L13)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Where did you find this value?
</blockquote></details>

These are the default configs of hugging face here: https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig
___
*[`lib/models/src/models/bert.cc` line 34 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67CYESBtZoM0Jr-Od6:-O6qLHrSC6GYVqf3qXeH:buftnve) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/src/models/bert.cc#L34)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What does this comment refer to?
</blockquote></details>

This is to indicate why the normalize axis is 2 - that's because it's the last dim of input tensor.
___
*[`lib/models/src/models/bert.cc` line 34 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67CZam1tYYdVJzwwv2:-O6qLV1q6tKRyKAYyh_7:b-3y89gx) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/src/models/bert.cc#L34)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If you are intending to create a `vector` with a single element (the number 2), `std::vector<int> layer_norm_axis = {2};` would be a bit clearer
</blockquote></details>

Ok, changed this.
___
*[`lib/models/src/models/bert.cc` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67Dxkn6QHswWvV4fFr:-O6qL9yQ5FB-6yHj_SEx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/src/models/bert.cc#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `lib/models/src/models/bert/bert.cc`
</blockquote></details>

Done.
___
*[`lib/models/test/src/models/bert.cc` line  at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67DsD5-gMHVtqBXOwZ:-O6qLfeV8APmQ6VILI7K:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/test/src/models/bert.cc#L)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `lib/models/test/src/models/bert/bert.cc`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-16 00:21 UTC, reyna-abhyankar requested changes
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 9 unresolved discussions (waiting on @lockshaw)

___
*[`lib/models/include/models/bert_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O6790vxBSMhb__GVG4B:-O6sBPKg-h_s4XJVMP_o:bhvmrzt) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L2)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Hmm, not really... I referred more to the Hugging Face version at https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig. And I left only one dropout config and one default activation.

Do we want to have the ability to alter the dropout / activation for this example? If so, I can add them.

cc. @lockshaw
</blockquote></details>

The hugging face config still has those parameters.


<!-- Sent from Reviewable.io -->

2024-09-19 01:30 UTC, reyna-abhyankar requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 9 unresolved discussions (waiting on @lockshaw)

___
*[`lib/models/include/models/bert_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O6790vxBSMhb__GVG4B:-O76sz9UAJrpe96N01_4:beh6h7k) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L2)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

The hugging face config still has those parameters.
</blockquote></details>

As per 9/18 meeting, let's add the following:
-   **hidden\_act** (`str` or `Callable`, _optional_, defaults to `"gelu"`) — The non-linear activation function (function or string) in the encoder and pooler. If string, `"gelu"`, `"relu"`, `"silu"` and `"gelu_new"` are supported.
-   [](https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig.hidden_dropout_prob)**hidden\_dropout\_prob** (`float`, _optional_, defaults to 0.1) — The dropout probability for all fully connected layers in the embeddings, encoder, and pooler.
-   [](https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig.attention_probs_dropout_prob)**attention\_probs\_dropout\_prob** (`float`, _optional_, defaults to 0.1) — The dropout ratio for the attention probabilities.
-   [](https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig.initializer_range)**initializer\_range** (`float`, _optional_, defaults to 0.02) — The standard deviation of the truncated\_normal\_initializer for initializing all weight matrices.
-   [](https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig.position_embedding_type)**position\_embedding\_type** (`str`, _optional_, defaults to `"absolute"`) — Type of position embedding. Choose one of `"absolute"`, `"relative_key"`, `"relative_key_query"`. For positional embeddings use `"absolute"`. For more information on `"relative_key"`, please refer to [Self-Attention with Relative Position Representations (Shaw et al.)](https://arxiv.org/abs/1803.02155). For more information on `"relative_key_query"`, please refer to _Method 4_ in [Improve Transformer Models with Better Relative Position Embeddings (Huang et al.)](https://arxiv.org/abs/2009.13658).
-   [](https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig.classifier_dropout)**classifier\_dropout** (`float`, _optional_) — The dropout ratio for the classification head.

For `position_embedding_type`, we can support just the default and throw an error if there's any other selection.


<!-- Sent from Reviewable.io -->

2024-09-21 15:36 UTC, hsdfzhsdfz reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 9 unresolved discussions (waiting on @lockshaw)

___
*[`lib/models/include/models/bert_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O6790vxBSMhb__GVG4B:-O7K288xA7sve1f2gi-J:b5ejw6d) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L2)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

As per 9/18 meeting, let's add the following:
-   **hidden\_act** (`str` or `Callable`, _optional_, defaults to `"gelu"`) — The non-linear activation function (function or string) in the encoder and pooler. If string, `"gelu"`, `"relu"`, `"silu"` and `"gelu_new"` are supported.
-   [](https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig.hidden_dropout_prob)**hidden\_dropout\_prob** (`float`, _optional_, defaults to 0.1) — The dropout probability for all fully connected layers in the embeddings, encoder, and pooler.
-   [](https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig.attention_probs_dropout_prob)**attention\_probs\_dropout\_prob** (`float`, _optional_, defaults to 0.1) — The dropout ratio for the attention probabilities.
-   [](https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig.initializer_range)**initializer\_range** (`float`, _optional_, defaults to 0.02) — The standard deviation of the truncated\_normal\_initializer for initializing all weight matrices.
-   [](https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig.position_embedding_type)**position\_embedding\_type** (`str`, _optional_, defaults to `"absolute"`) — Type of position embedding. Choose one of `"absolute"`, `"relative_key"`, `"relative_key_query"`. For positional embeddings use `"absolute"`. For more information on `"relative_key"`, please refer to [Self-Attention with Relative Position Representations (Shaw et al.)](https://arxiv.org/abs/1803.02155). For more information on `"relative_key_query"`, please refer to _Method 4_ in [Improve Transformer Models with Better Relative Position Embeddings (Huang et al.)](https://arxiv.org/abs/2009.13658).
-   [](https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig.classifier_dropout)**classifier\_dropout** (`float`, _optional_) — The dropout ratio for the classification head.

For `position_embedding_type`, we can support just the default and throw an error if there's any other selection.
</blockquote></details>

Okay, have added the additional parameters.


<!-- Sent from Reviewable.io -->

2024-09-21 17:15 UTC, lockshaw requested changes
> Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 10 unresolved discussions (waiting on @hsdfzhsdfz and @reyna-abhyankar)

___
*[`lib/pcg/include/pcg/initializers/truncated_norm_initializer_attrs.struct.toml` line 2 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KWqTH63c6z2ZlgTD4:-O7KWqTH63c6z2ZlgTD5:b-c55el7) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/pcg/include/pcg/initializers/truncated_norm_initializer_attrs.struct.toml#L2)):*
> ```TOML
> namespace = "FlexFlow"
> name = "TruncatedNormInitializerAttrs"
> ```

The pytorch name is `trunc_normal_`, and `Norm` is a bit overloaded (yes I know we use `Norm` for normal sometimes, this should probably get fixed eventually)



_Suggestion:_
```TOML
name = "TruncatedNormalInitializerAttrs"
```
___
*[`lib/pcg/include/pcg/initializers/truncated_norm_initializer_attrs.struct.toml` line 11 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KXSYl5ryNMW0S4w7N:-O7KXSYl5ryNMW0S4w7O:b-4y97ax) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/pcg/include/pcg/initializers/truncated_norm_initializer_attrs.struct.toml#L11)):*
> ```TOML
>   "fmt",
> ]
> ```

Where are the truncation attrs (i.e., `a` and `b` in https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.trunc_normal_)?
___
*[`lib/models/include/models/bert.h` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67Bhi53X77VEp7eAS6:-O7KYboA7XCFtSQPemAc:b-481jq4) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert.h#L21)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

These are the default configs of hugging face here: https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/bert#transformers.BertConfig
</blockquote></details>

Can you add that link to the doxygen docstring?
___
*[`lib/models/include/models/bert/bert.h` line 28 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KYjOr1j6_D85QD8Rj:-O7KYjOr1j6_D85QD8Rk:b-koijhw) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/include/models/bert/bert.h#L28)):*
> ```objc
>  * @brief Get the BERT computation graph.
>  *
>  * @note This is a naive encoder-only model for pre-training.
> ```

Is "naive" the right word here, or would something like "standard" or "plain" or "pure" be more accurate?



_Code quote:_
```objc
 * @note This is a naive encoder-only model for pre-training.
```
___
*[`lib/models/include/models/bert/bert.h` line 31 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KYtcoDeWkXLXCJV4q:-O7KYtcoDeWkXLXCJV4r:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/include/models/bert/bert.h#L31)):*
> ```objc
>  *
>  * @param BertConfig The config of BERT model.
>  * @return ComputationGraph The PCG of a BERT model.
> ```





_Suggestion:_
```objc
 * @return ComputationGraph The computation graph of a BERT model
```
___
*[`lib/models/include/models/bert/bert_config.struct.toml` line 35 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KWCHvAjCF8MCGqozV:-O7KWCHvAjCF8MCGqozW:bpp4pei) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/include/models/bert/bert_config.struct.toml#L35)):*
> ```TOML
> [[fields]]
> name = "hidden_act"
> type = "std::string"
> ```

Probably would be better as a `::FlexFlow::Activation`
___
*[`lib/models/src/models/bert/bert.cc` line 21 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KZwdq0mw4c47R4jSv:-O7KZwdr7csBy_JanCI_:brubqa0) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L21)):*
> ```cpp
>                     /*sequence_length=*/512,
>                     /*batch_size=*/64);
> }
> ```

For consistency, not a big deal



_Suggestion:_
```cpp
BertConfig get_default_bert_config() {
  return BertConfig{/*vocab_size=*/30522,
                    /*hidden_size=*/768,
                    /*num_encoder_layers=*/12,
                    /*num_heads=*/12,
                    /*dim_feedforward=*/3072,
                    /*hidden_act=*/"GELU",
                    /*hidden_dropout_prob=*/0.1,
                    /*attention_probs_dropout_prob=*/0.1,
                    /*initializer_range=*/0.02,
                    /*layer_norm_eps=*/1e-12,
                    /*classifier_dropout=*/0.1,
                    /*sequence_length=*/512,
                    /*batch_size=*/64};
}
```
___
*[`lib/models/src/models/bert/bert.cc` line 35 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KWV310FsMSNQpzwbR:-O7KWV310FsMSNQpzwbS:b-vpym65) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L35)):*
> ```cpp
>                 /*use_bias=*/true,
>                 /*data_type=*/DataType::FLOAT,
>                 /*kernel_initializer=*/kernel_initializer);
> ```

`bias_initializer` should be a zero initializer I think based on https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense
___
*[`lib/models/src/models/bert/bert.cc` line 54 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KXs_M-KDZ2VqhXPRc:-O7KXs_M-KDZ2VqhXPRd:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L54)):*
> ```cpp
>                               Activation const &activation,
>                               InitializerAttrs const &kernel_initializer) {
>   std::vector<int> layer_norm_axis = {2}; // Normalize the last dim
> ```





_Suggestion:_
```cpp
  assert (num_dims(cgb.get_shape(input)) == 3);
  std::vector<int> layer_norm_axis = {2}; // Apply layernorm across the last dim
```
___
*[`lib/models/src/models/bert/bert.cc` line 135 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7K_9GV9X1O3INGzCgP:-O7K_9GV9X1O3INGzCgQ:bldyzrp) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L135)):*
> ```cpp
>   tensor_guid_t input = cgb.create_tensor(input_shape, CreateGrad::YES);
> 
>   tensor_guid_t encoder_output =
> ```

Ideally add some checks on the shapes of these output tensors (i.e., `encoder_output` and `out_prob`)--improves readability and acts as a nice sanity check


<!-- Sent from Reviewable.io -->

2024-09-21 19:15 UTC, hsdfzhsdfz reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 10 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/pcg/include/pcg/initializers/truncated_norm_initializer_attrs.struct.toml` line 2 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KWqTH63c6z2ZlgTD4:-O7KqRJ48Sy2ovPd6j_8:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/pcg/include/pcg/initializers/truncated_norm_initializer_attrs.struct.toml#L2)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The pytorch name is `trunc_normal_`, and `Norm` is a bit overloaded (yes I know we use `Norm` for normal sometimes, this should probably get fixed eventually)
</blockquote></details>

Done.
___
*[`lib/pcg/include/pcg/initializers/truncated_norm_initializer_attrs.struct.toml` line 11 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KXSYl5ryNMW0S4w7N:-O7Ksksl4VS66wZyl6et:bek5wf3) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/pcg/include/pcg/initializers/truncated_norm_initializer_attrs.struct.toml#L11)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Where are the truncation attrs (i.e., `a` and `b` in https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.trunc_normal_)?
</blockquote></details>

Hmm, for this, I was referring more to the tensorflow version where it had the following spec:

```
The values are drawn from a normal distribution with specified mean and standard deviation, discarding and re-drawing any samples that are more than two standard deviations from the mean.
```

https://www.tensorflow.org/api_docs/python/tf/random/truncated_normal

But I agree having a and b makes more sense. I have added them and made them the same default as TF definition.
___
*[`lib/models/include/models/bert.h` line 21 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O67Bhi53X77VEp7eAS6:-O7KpQCF5S4lGlfCoF7S:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert.h#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you add that link to the doxygen docstring?
</blockquote></details>

Done.
___
*[`lib/models/include/models/bert/bert.h` line 28 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KYjOr1j6_D85QD8Rj:-O7KpWYX0Bdbn-jWoYPr:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/include/models/bert/bert.h#L28)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is "naive" the right word here, or would something like "standard" or "plain" or "pure" be more accurate?
</blockquote></details>

Done.
___
*[`lib/models/include/models/bert/bert.h` line 31 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KYtcoDeWkXLXCJV4q:-O7KpZod4lFBv1odaWoy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/include/models/bert/bert.h#L31)):*
> ```objc
>  *
>  * @param BertConfig The config of BERT model.
>  * @return ComputationGraph The PCG of a BERT model.
> ```

Done.
___
*[`lib/models/include/models/bert/bert_config.struct.toml` line 35 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KWCHvAjCF8MCGqozV:-O7Kppos0V-IRzwN1zBI:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/include/models/bert/bert_config.struct.toml#L35)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Probably would be better as a `::FlexFlow::Activation`
</blockquote></details>

Done.
___
*[`lib/models/src/models/bert/bert.cc` line 21 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KZwdq0mw4c47R4jSv:-O7KpuZX1TkyncF3PGT5:bb6un1j) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

For consistency, not a big deal
</blockquote></details>

Done
___
*[`lib/models/src/models/bert/bert.cc` line 35 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KWV310FsMSNQpzwbR:-O7L-Xck6A8rDbtyZIxG:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L35)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`bias_initializer` should be a zero initializer I think based on https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense
</blockquote></details>

Done.
___
*[`lib/models/src/models/bert/bert.cc` line 54 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7KXs_M-KDZ2VqhXPRc:-O7Kq5XV1y9s2FRQm3Dc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L54)):*
> ```cpp
>                               Activation const &activation,
>                               InitializerAttrs const &kernel_initializer) {
>   std::vector<int> layer_norm_axis = {2}; // Normalize the last dim
> ```

Done.
___
*[`lib/models/src/models/bert/bert.cc` line 135 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7K_9GV9X1O3INGzCgP:-O7L-bF25311VbVKgzUL:bb71kmx) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L135)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Ideally add some checks on the shapes of these output tensors (i.e., `encoder_output` and `out_prob`)--improves readability and acts as a nice sanity check
</blockquote></details>

Okay


<!-- Sent from Reviewable.io -->

2024-09-21 21:29 UTC, lockshaw requested changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 2 unresolved discussions (waiting on @hsdfzhsdfz and @reyna-abhyankar)

___
*[`lib/models/src/models/bert/bert.cc` line 135 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7K_9GV9X1O3INGzCgP:-O7LTy-z246aHdHW8gQa:b-7ct44z) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L135)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Okay
</blockquote></details>

Not seeing any change for this?


<!-- Sent from Reviewable.io -->

2024-09-22 02:02 UTC, hsdfzhsdfz reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 2 unresolved discussions (waiting on @lockshaw and @reyna-abhyankar)

___
*[`lib/models/src/models/bert/bert.cc` line 135 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7K_9GV9X1O3INGzCgP:-O7M8E0O2Z1IsrLBY-4P:b-knojs6) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L135)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not seeing any change for this?
</blockquote></details>

Added some basic checks.

Btw, when we do `proj build/test`, does it compile in debug mode or optimized mode?


<!-- Sent from Reviewable.io -->

2024-09-22 14:43 UTC, reyna-abhyankar submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @hsdfzhsdfz and @lockshaw)

___
*[`lib/models/include/models/bert_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O6790vxBSMhb__GVG4B:-O7P9clw7ySafiNXr0uU:bgfmv76) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L2)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Okay, have added the additional parameters.
</blockquote></details>

Also add `position_embedding_type` and then throw an error if they specify anything other than "absolute" in the config.


<!-- Sent from Reviewable.io -->

2024-09-23 19:43 UTC, lockshaw approved these changes
> Reviewed 1 of 1 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/models/include/models/bert_config.struct.toml` line 2 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O6790vxBSMhb__GVG4B:-O7VOkWI9rGwxLrk-St4:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/03785df3690a3ec8bc098eb34a3f52d3160453a6/lib/models/include/models/bert_config.struct.toml#L2)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Also add `position_embedding_type` and then throw an error if they specify anything other than "absolute" in the config.
</blockquote></details>

Done.
___
*[`lib/models/src/models/bert/bert.cc` line 135 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/1488#-O7K_9GV9X1O3INGzCgP:-O7UxmIx1Vccvqzktc9f:bwx9cd) ([raw file](https://github.com/flexflow/FlexFlow/blob/ac182613fb5f0b0cdfbabf0578bed71ac0861bda/lib/models/src/models/bert/bert.cc#L135)):*
<details><summary><i>Previously, hsdfzhsdfz wrote…</i></summary><blockquote>

Added some basic checks.

Btw, when we do `proj build/test`, does it compile in debug mode or optimized mode?
</blockquote></details>

debug mode: https://github.com/lockshaw/proj/blob/c650b0e52337652ea7190131988c0370e0ee7f25/proj/config_file.py#L83-L95


<!-- Sent from Reviewable.io -->

2024-09-23 19:55 UTC, lockshaw approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1488)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2024-09-23 20:12 UTC, merged