inception v3 initial implementation
flexflow/FlexFlow pull request #1495
Opened 2024-09-10 23:43 UTC by Marsella8

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

2024-09-11 00:20 UTC, lockshaw commented
@reyna-abhyankar Can you take care of the "implementation vs paper" checks for this PR? I'll work on getting the additional operators implemented





<!-- Sent from Reviewable.io -->

2024-09-11 03:04 UTC, lockshaw requested changes
> Reviewed 5 of 7 files at r1, 34 of 39 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1495)* status: all files reviewed, 6 unresolved discussions (waiting on @Marsella8 and @reyna-abhyankar)

___
*[`lib/models/include/models/inceptionv3.h` line 5 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6TX3AfDr9CGHpecU1I:-O6TX3AfDr9CGHpecU1J:br98bto) ([raw file](https://github.com/flexflow/FlexFlow/blob/ede66f7faa9fc014db1c3ab29dfa4935ab2e7108/lib/models/include/models/inceptionv3.h#L5)):*
> ```objc
> 
> #include "models/inceptionv3_config.dtg.h"
> #include "pcg/computation_graph.h"
> ```

Nothing in the `.h` needs the functions declared in `computation_graph.h`



_Suggestion:_
```objc
#include "pcg/computation_graph.dtg.h"
```
___
*[`lib/models/include/models/inceptionv3.h` line 6 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6TWxvsCrEXK6lsnYt6:-O6TWxvsCrEXK6lsnYt7:b-cn2hvh) ([raw file](https://github.com/flexflow/FlexFlow/blob/ede66f7faa9fc014db1c3ab29dfa4935ab2e7108/lib/models/include/models/inceptionv3.h#L6)):*
> ```objc
> #include "models/inceptionv3_config.dtg.h"
> #include "pcg/computation_graph.h"
> #include "pcg/computation_graph_builder.h"
> ```

Move to `.cc`, nothing in the `.h` mentions `ComputationGraphBuilder`
___
*[`lib/models/include/models/inceptionv3_config.struct.toml` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6TXm_QBsqtQ2-M7VhU:-O6TXm_R-YrlfJd5DzjN:b-b1v6al) ([raw file](https://github.com/flexflow/FlexFlow/blob/ede66f7faa9fc014db1c3ab29dfa4935ab2e7108/lib/models/include/models/inceptionv3_config.struct.toml#L15)):*
> ```TOML
> [[fields]]
> name = "input_height"
> type = "size_t"
> ```

Prefer `int`s for all of these
___
*[`lib/models/src/models/inceptionv3.cc` line 35 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6TY8qI9TABCehmqmTb:-O6TY8qI9TABCehmqmTc:b-15eawq) ([raw file](https://github.com/flexflow/FlexFlow/blob/ede66f7faa9fc014db1c3ab29dfa4935ab2e7108/lib/models/src/models/inceptionv3.cc#L35)):*
> ```cpp
>                                   std::nullopt,
>                                   1,
>                                   use_bias);
> ```

Argument name comments might be nice for some of these (like "1" and "std::nullopt")



_Code quote:_
```cpp
                                  std::nullopt,
                                  1,
                                  use_bias);
```
___
*[`lib/models/src/models/inceptionv3.cc` line 130 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6TwKANDfMybSaPD_w4:-O6TwKANDfMybSaPD_w5:b-90ghaq) ([raw file](https://github.com/flexflow/FlexFlow/blob/ede66f7faa9fc014db1c3ab29dfa4935ab2e7108/lib/models/src/models/inceptionv3.cc#L130)):*
> ```cpp
>   branch3x3dbl = cgb.concat(2, {branch3x3dbl_1, branch3x3dbl_2}, 3);
> 
>   tensor_guid_t branch_pool = cgb.pool2d(input, 3, 3, 1, 1, 1, 1, PoolOp::AVG);
> ```

Honestly might not be the worst idea to add argument comments for all of these raw number parameters for readability. Right now even if I had the order memorized there are so many that it's visually difficult to pick out which is which
___
*[`lib/models/test/src/models/inception_v3/inception_v3.cc` line 15 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6U0_JL055bnivSq4a8:-O6U0_JL055bnivSq4a9:b-kjl1wp) ([raw file](https://github.com/flexflow/FlexFlow/blob/d724185dce337a6603ce9758228588bf8d96806a/lib/models/test/src/models/inception_v3/inception_v3.cc#L15)):*
> ```cpp
>     SUBCASE("num layers") {
>       // int result_num_layers = get_layers(result).size();
>       int correct_num_layers = -1;
> ```

Checks should be added before merge


<!-- Sent from Reviewable.io -->

2024-09-11 05:47 UTC, reyna-abhyankar requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1495)* status: all files reviewed, 8 unresolved discussions (waiting on @Marsella8)

___
*[`lib/models/src/models/inception_v3/inception_v3.cc` line 154 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6U_Rwc6i_NPDZEf7oN:-O6U_Rwc6i_NPDZEf7oO:bfvy0jg) ([raw file](https://github.com/flexflow/FlexFlow/blob/cc16481bac4ced5f7bc4dd6bdbda536bfdea1e6b/lib/models/src/models/inception_v3/inception_v3.cc#L154)):*
> ```cpp
>                                   tensor_guid_t const &input,
>                                   size_t num_classes) {
>   tensor_guid_t x = cgb.pool2d(input, 8, 8, 1, 1, 0, 0, PoolOp::AVG);
> ```

So technically the module is adaptive avg pool, which I think means it reduces any input to the specified output size. The point of this is to deal with variable size inputs, which only happens if the `inception_aux = true`. I think you can probably just handle this manually (i.e. `if (aux_logits) { ...__size A__...} else { ...__size B__...}`)
___
*[`lib/models/src/models/inception_v3/inception_v3.cc` line 175 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6UZuJy1_mleM5gXVRK:-O6UZuJy1_mleM5gXVRL:buup3sq) ([raw file](https://github.com/flexflow/FlexFlow/blob/cc16481bac4ced5f7bc4dd6bdbda536bfdea1e6b/lib/models/src/models/inception_v3/inception_v3.cc#L175)):*
> ```cpp
>   x = create_inception_module_c(cgb, x, 160);
>   x = create_inception_module_c(cgb, x, 192);
> ```

Missing `inception_aux`:  can add `aux_logits` in the config as such
https://github.com/pytorch/vision/blob/00e7fa164bfdfd302f0b471c18ce2fd6bd1a50bc/torchvision/models/inception.py#L78

https://pytorch.org/vision/0.8/_modules/torchvision/models/inception.html - is the code for the module


<!-- Sent from Reviewable.io -->

2024-09-17 17:30 UTC, lockshaw reviewed
> Reviewed 12 of 22 files at r4, 27 of 38 files at r6, 14 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1495)* status: all files reviewed, 2 unresolved discussions (waiting on @reyna-abhyankar)

___
*[`lib/models/include/models/inceptionv3.h` line 5 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6TX3AfDr9CGHpecU1I:-O6yE0Tq3IK3rr_5DSAr:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ede66f7faa9fc014db1c3ab29dfa4935ab2e7108/lib/models/include/models/inceptionv3.h#L5)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Nothing in the `.h` needs the functions declared in `computation_graph.h`
</blockquote></details>

Done.
___
*[`lib/models/include/models/inceptionv3.h` line 6 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6TWxvsCrEXK6lsnYt6:-O6yE19DD7ryj1lqA2r_:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ede66f7faa9fc014db1c3ab29dfa4935ab2e7108/lib/models/include/models/inceptionv3.h#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `.cc`, nothing in the `.h` mentions `ComputationGraphBuilder`
</blockquote></details>

Done.
___
*[`lib/models/include/models/inceptionv3_config.struct.toml` line 15 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6TXm_QBsqtQ2-M7VhU:-O6yE2fJDmaORzfMKCqB:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ede66f7faa9fc014db1c3ab29dfa4935ab2e7108/lib/models/include/models/inceptionv3_config.struct.toml#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Prefer `int`s for all of these
</blockquote></details>

Done.
___
*[`lib/models/src/models/inceptionv3.cc` line 35 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6TY8qI9TABCehmqmTb:-O701BvQ2ibVK8A6b-qy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ede66f7faa9fc014db1c3ab29dfa4935ab2e7108/lib/models/src/models/inceptionv3.cc#L35)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Argument name comments might be nice for some of these (like "1" and "std::nullopt")
</blockquote></details>

Done.
___
*[`lib/models/src/models/inceptionv3.cc` line 130 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6TwKANDfMybSaPD_w4:-O6yE8DFE1Fd5TnGsbS-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ede66f7faa9fc014db1c3ab29dfa4935ab2e7108/lib/models/src/models/inceptionv3.cc#L130)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Honestly might not be the worst idea to add argument comments for all of these raw number parameters for readability. Right now even if I had the order memorized there are so many that it's visually difficult to pick out which is which
</blockquote></details>

Done.
___
*[`lib/models/src/models/inception_v3/inception_v3.cc` line 154 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6U_Rwc6i_NPDZEf7oN:-O6yEA6yAXEEf2bXpRX7:b1sivam) ([raw file](https://github.com/flexflow/FlexFlow/blob/cc16481bac4ced5f7bc4dd6bdbda536bfdea1e6b/lib/models/src/models/inception_v3/inception_v3.cc#L154)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

So technically the module is adaptive avg pool, which I think means it reduces any input to the specified output size. The point of this is to deal with variable size inputs, which only happens if the `inception_aux = true`. I think you can probably just handle this manually (i.e. `if (aux_logits) { ...__size A__...} else { ...__size B__...}`)
</blockquote></details>

Added (partial) adaptive avg pool support
___
*[`lib/models/src/models/inception_v3/inception_v3.cc` line 175 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6UZuJy1_mleM5gXVRK:-O6yEGmB6w7OYjB8cqnj:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/cc16481bac4ced5f7bc4dd6bdbda536bfdea1e6b/lib/models/src/models/inception_v3/inception_v3.cc#L175)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Missing `inception_aux`:  can add `aux_logits` in the config as such
https://github.com/pytorch/vision/blob/00e7fa164bfdfd302f0b471c18ce2fd6bd1a50bc/torchvision/models/inception.py#L78

https://pytorch.org/vision/0.8/_modules/torchvision/models/inception.html - is the code for the module
</blockquote></details>

Done.
___
*[`lib/models/test/src/models/inception_v3/inception_v3.cc` line 15 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O6U0_JL055bnivSq4a8:-O6yDxk250rkvSq5rKsy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/d724185dce337a6603ce9758228588bf8d96806a/lib/models/test/src/models/inception_v3/inception_v3.cc#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Checks should be added before merge
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-17 17:40 UTC, lockshaw reviewed
> Reviewed 23 of 23 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1495)* status: all files reviewed, 2 unresolved discussions (waiting on @reyna-abhyankar)



<!-- Sent from Reviewable.io -->

2024-09-17 17:51 UTC, reyna-abhyankar requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1495)* status: all files reviewed, 1 unresolved discussion (waiting on @Marsella8)

___
*[`lib/op-attrs/src/op-attrs/ops/pool_2d.cc` line 41 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O705Ad2AypXkZ7C9Jos:-O705Ad2AypXkZ7C9Jot:b-ffwgc8) ([raw file](https://github.com/flexflow/FlexFlow/blob/51fa6a23f5f12acdb5606d110c1ec62c0d54d2a2/lib/op-attrs/src/op-attrs/ops/pool_2d.cc#L41)):*
> ```cpp
> 
>   int stride_h = kernel_h;
>   int stride_w = kernel_w;
> ```

On the stack overflow post, I'm seeing the following formula:
```python
stride = ind // outd
kernel_size = ind - (outd-1)*stride
padding = 0
```


<!-- Sent from Reviewable.io -->

2024-09-17 17:55 UTC, lockshaw reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1495)* status: all files reviewed, 1 unresolved discussion (waiting on @reyna-abhyankar)

___
*[`lib/op-attrs/src/op-attrs/ops/pool_2d.cc` line 41 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O705Ad2AypXkZ7C9Jos:-O706TMoAn8m4bJGbNUW:bbt2tc5) ([raw file](https://github.com/flexflow/FlexFlow/blob/51fa6a23f5f12acdb5606d110c1ec62c0d54d2a2/lib/op-attrs/src/op-attrs/ops/pool_2d.cc#L41)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

On the stack overflow post, I'm seeing the following formula:
```python
stride = ind // outd
kernel_size = ind - (outd-1)*stride
padding = 0
```
</blockquote></details>

`ind - (outd - 1)*stride` = `ind - (outd - 1) * (ind / outd)` = `ind - ind + (ind  /outd)` = `ind / outd` = `stride`


<!-- Sent from Reviewable.io -->

2024-09-17 18:09 UTC, reyna-abhyankar submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-:-O70AEKT9AOnyv2QH2DE:bnfp4nl)* status: 68 of 69 files reviewed, all discussions resolved (waiting on @lockshaw)

___
*[`lib/op-attrs/src/op-attrs/ops/pool_2d.cc` line 41 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O705Ad2AypXkZ7C9Jos:-O70AB_Q6dFLk5fUqXE6:bwuva5w) ([raw file](https://github.com/flexflow/FlexFlow/blob/51fa6a23f5f12acdb5606d110c1ec62c0d54d2a2/lib/op-attrs/src/op-attrs/ops/pool_2d.cc#L41)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`ind - (outd - 1)*stride` = `ind - (outd - 1) * (ind / outd)` = `ind - ind + (ind  /outd)` = `ind / outd` = `stride`
</blockquote></details>

Nice. 


<!-- Sent from Reviewable.io -->

2024-09-17 18:10 UTC, lockshaw approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/1495)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marsella8)

___
*[`lib/op-attrs/src/op-attrs/ops/pool_2d.cc` line 41 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/1495#-O705Ad2AypXkZ7C9Jos:-O70A8u41q8YEG-FHl4_:b-reomdq) ([raw file](https://github.com/flexflow/FlexFlow/blob/51fa6a23f5f12acdb5606d110c1ec62c0d54d2a2/lib/op-attrs/src/op-attrs/ops/pool_2d.cc#L41)):*
<details><summary><i>Previously, reyna-abhyankar (Reyna Abhyankar) wrote…</i></summary><blockquote>

Nice.
</blockquote></details>

Added a comment documenting this.


<!-- Sent from Reviewable.io -->

2024-09-17 18:37 UTC, lockshaw approved these changes

2024-09-17 18:50 UTC, merged