Add sine and cosine operators
flexflow/FlexFlow pull request #466
Opened 2022-11-10 20:31 UTC by soumyac1999

Fixes #462.

Discussion items (@lockshaw):
1. Where and do we expose these ops in the Keras frontend?
2. Are there C++ and/or Python tests which need to be added corresponding to these new operations?

2022-11-11 03:40 UTC, lockshaw commented
>     1. Where and do we expose these ops in the Keras frontend?

How are they being invoked in the current keras notebook you have?

>     2. Are there C++ and/or Python tests which need to be added corresponding to these new operations?

Unfortunately at the moment I don't think so. Feel free to add some if you want (we definitely want to move towards having more tests, but I don't think there's currently a systematic approach--see #429)

2022-11-11 03:41 UTC, lockshaw commented
For now you could probably just access the core FF interface directly and we can discuss how to surface it later

2022-11-11 03:44 UTC, lockshaw requested changes

2022-11-11 03:44 UTC, lockshaw commented on python/flexflow/core/flexflow_cffi.py
> +    """Sine function.
```suggestion
    """Elementwise sine function.
```

2022-11-11 03:44 UTC, lockshaw commented on python/flexflow/core/flexflow_cffi.py
> +    """Cosine function.
```suggestion
    """Elementwise cosine function.
```

2022-11-11 03:44 UTC, lockshaw commented on src/ops/element_unary.cu
> +      }
You need `break` statements here

2022-11-11 03:44 UTC, lockshaw commented on src/ops/element_unary.cpp
> +      case OP_SIN: {
You need `break` statements here--C++ case by default falls through

2022-12-22 06:49 UTC, soumyac1999 commented on src/ops/element_unary.cpp
> +        out[i] = (T)sin((float)in[i]);
```suggestion
        out[i] = (T)sin((float)in[i]);
        break;
```

2022-12-22 06:49 UTC, soumyac1999 commented on src/ops/element_unary.cpp
> +        out[i] = (T)cos((float)in[i]);
```suggestion
        out[i] = (T)cos((float)in[i]);
        break;
```

2022-12-22 06:49 UTC, soumyac1999 commented on src/ops/element_unary.cu
> +        out[i] = (T)sin((float)in[i]);
```suggestion
        out[i] = (T)sin((float)in[i]);
        break;
```

2022-12-22 06:50 UTC, soumyac1999 commented on src/ops/element_unary.cu
> +        out[i] = (T)cos((float)in[i]);
```suggestion
        out[i] = (T)cos((float)in[i]);
        break;
```

2022-12-24 22:45 UTC, lockshaw approved these changes

2022-12-24 22:45 UTC, merged