Fixed implicit closure in sorting comparator
flexflow/FlexFlow pull request #827
Opened 2023-07-03 14:48 UTC by stelleg

**Description of changes:**
Existing code requires implicit closure over f, which appears to be invalid C++ and fails with g++. 

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

2023-07-06 02:23 UTC, lockshaw commented
So this was the fix I had--it seems cleaner, so I'd probably lean toward this unless you have an objection: 
```
 template <typename T, typename F>
 void inplace_sorted_by(std::vector<T> &v, F const &f) {
-  struct {
-    bool operator()(T const &lhs, T const &rhs) { return f(lhs, rhs); }
-  } custom_comparator;
+  auto custom_comparator = [&](T const &lhs, T const &rhs) -> bool {
+    return f(lhs, rhs);
+  };
   
   std::sort(v.begin(), v.end(), custom_comparator);
```
It's not much code though, so I don't have particularly strong opinions.

2023-07-06 15:14 UTC, stelleg commented
Yep, I prefer yours as well.

2023-07-06 23:54 UTC, lockshaw commented
Great, can you update this PR to have that change and then I'll approve?

2023-07-10 12:18 UTC, lockshaw requested changes
see above

2023-07-10 12:19 UTC, lockshaw commented
Nevermind, fixed in #850

2023-07-10 12:19 UTC, closed without merging