Build Docker images on multiple cuda versions in parallel
flexflow/FlexFlow pull request #859
Opened 2023-07-13 20:42 UTC by DerrickYLJ

**Description of changes:**
Parallelize the process of building docker images with multiple different cuda versions as base images and modify the build.sh, pulish.sh, and workflow to distinguish the tag of cuda or hip_rocm as FF_BACK_END.

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

2023-07-14 16:13 UTC, goliaro requested changes

2023-07-14 16:13 UTC, goliaro commented on docker/run.sh
> +if [[ "$cuda_version" != @(11.1.1|11.2.2|11.3.1|11.5.2|11.6.2|11.7.1|11.8.0) ]]; then
could we also autodetect the cuda version in the `run.sh`? And could you add a message telling the user which cuda version the script is building for ? E.g. "Building FlexFlow docker image for CUDA 11.8"

2023-07-14 16:13 UTC, goliaro commented on docker/build.sh
> +cuda_version=${cuda_version:-11.1.1}
can we make the `cuda_version` environment variable take CUDA versions with only one decimal, like the previous cuda_version argument? then, we can add the default subversion digit in the script

2023-07-14 16:13 UTC, goliaro commented on docker/build.sh
> -if [[ "$cuda_version" == @(11.1|11.3|11.7) ]]; then
I think we can bring back this block

2023-07-17 19:09 UTC, goliaro commented on docker/run.sh
> +if [[ "${FF_GPU_BACKEND}" == "hip_rocm" ]]; then
I think here, to reduce the code duplication, we could use the `if [[ "${FF_GPU_BACKEND}" == "hip_rocm" ]]; then ... else ... fi` statement only to modify the `cuda_version` variable. For rocm, we can make it an empty string, whereas for CUDA, we can set it as `cuda_version="-${cuda_version}"` (we add the hyphen). Then, we can run the docker machines "flexflow-environment-${FF_GPU_BACKEND}${cuda_version}:latest", "flexflow-${FF_GPU_BACKEND}${cuda_version}:latest", etc... in all cases. Note how I have removed the hyphen between `${FF_GPU_BACKEND}` and `${cuda_version}`

2023-07-17 19:38 UTC, DerrickYLJ commented
Most changes have been completed except for the "autodetect cuda_version in run.sh". I added back the `--cuda_version` optional flag so that users are able to input any cuda versions they want to build, and as before, if there is no input, it will autodetect the cuda version installed on the current machine and run with that if available.

2023-07-18 15:11 UTC, goliaro requested changes

2023-07-18 15:11 UTC, goliaro commented on docker/README.md
> +After having either built or downloaded a Docker container by following the instructions above, you can run it with the following command (the `--image_name flexflow` argument of the run script can b
can we update the readme to reflect the new way of passing the CUDA version, and image name?

2023-07-18 15:11 UTC, goliaro commented on docker/README.md
> +FF_GPU_BACKEND=<YOUR_GPU_BACKEND> ./docker/run.sh --image_name flexflow --cuda_version 11.1
same here

2023-07-18 15:11 UTC, goliaro commented on docker/build.sh
> -  cuda_version=$(command -v nvcc >/dev/null 2>&1 && nvcc --version | grep "release" | awk '{print $NF}')
I think we should bring back this block to perform autodetection

2023-07-18 15:11 UTC, goliaro commented on docker/build.sh
> +if [[ "${FF_GPU_BACKEND}" == "hip_rocm" ]]; then
here, to reduce code duplication, we can use the `if [[ "${FF_GPU_BACKEND}" == "hip_rocm" ]];` to set the cuda_version to variable to the empty string, and then use the same docker build command for both hip_rocm and CUDA

2023-07-18 15:11 UTC, goliaro commented on docker/build.sh
> +  docker build --build-arg "N_BUILD_CORES=${n_build_cores}" --build-arg "FF_GPU_BACKEND=${FF_GPU_BACKEND}" --build-arg "BUILD_CONFIGS=${BUILD_CONFIGS}" -t "flexflow-${FF_GPU_BACKEND}" -f docker/flexf
same here. After having set the cuda_version to the empty string above when building for hip_rocm, here we can remove this if statement and use a single docker build command for both

2023-07-18 15:11 UTC, goliaro commented on docker/flexflow/Dockerfile
> +FROM flexflow-environment-$FF_GPU_BACKEND$cuda_version:latest
perfect!

2023-07-18 15:11 UTC, goliaro commented on docker/publish.sh
> -if [[ $cuda_version == "empty" ]]; then
we should bring back this block for automatic detection

2023-07-18 15:11 UTC, goliaro commented on docker/run.sh
> +    eval docker run -it "$gpu_arg" "--shm-size=${SHM_SIZE}" "flexflow-environment-${FF_GPU_BACKEND}${cuda_version}:latest"
great! that's exactly what I had in mind here

2023-07-18 21:26 UTC, goliaro approved these changes
I just made some small additional fixes / reorderings. LGTM!

2023-07-18 21:26 UTC, merged