add unit tests for compiler
flexflow/FlexFlow pull request #870
Opened 2023-07-19 16:59 UTC by wmdi

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/870)

2023-07-25 21:11 UTC, lockshaw requested changes
Can we merge the base of this and then merge this? Because `repo-refactor` doesn't have some of the changes from my fork this diff shows all of them at once. It would be nice to do this as two separate PRs (one for the changes from my fork with a base of repo-refactor and one for the changes from your fork with a base of my fork so the diffs work out)

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870#-:-NaDsdm6Afjucfmderu8:b-sq7kak)* status: 0 of 40 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-27 05:35 UTC, lockshaw requested changes
> Reviewed 7 of 12 files at r2, 33 of 33 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: all files reviewed, 16 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/src/machine_mapping.cc` line 204 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKphyK0V6yxPTQr7Xp:-NaKphyK0V6yxPTQr7Xq:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/src/machine_mapping.cc#L204)):*
> ```cpp
>                                      cached_subgraph_costs),
>                          post_decompn)),
>                MachineMappingRuntimeCmp{});
> ```





_Suggestion:_
```cpp
      minimize_runtime(optimal_result,
               MachineMapping::sequential_combine(
                   visit(OptimalCost(pre_graph,
                                     cost_estimator,
                                     resource,
                                     source_machine_view,
                                     pre_sink_mv,
                                     allowed_machine_views,
                                     cached_subgraph_costs),
                         pre_decompn),
                   visit(OptimalCost(post_graph,
                                     cost_estimator,
                                     resource,
                                     post_source_mv,
                                     sink_machine_view,
                                     allowed_machine_views,
                                     cached_subgraph_costs),
                         post_decompn)));
```
___
*[`lib/compiler/test/test_generator.h` line 21 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKkrYHBVlb4A798g3q:-NaKkrYHBVlb4A798g3r:b-u0afum) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L21)):*
> ```objc
>   static Gen<MachineView> arbitrary() {
>     return gen::apply(make_1d_machine_view,
>                       gen::construct<gpu_id_t>(gen::nonZero<int>()),
> ```

Why not add an arbitrary instance for `gpu_id_t`? (or even `strong_typedef` in general)
___
*[`lib/compiler/test/test_generator.h` line 41 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKlLt14bXgb3zXE3VU:-NaKlLt14bXgb3zXE3VV:b-90rtz3) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L41)):*
> ```objc
> struct Arbitrary<ComputationGraph> {
>   static Gen<ComputationGraph> arbitrary() {
>     return gen::apply(
> ```

If would be really nice to clean up this code a bit -- it's currently really hard to read/understand (and some of this may be complexity we can't avoid, but I think there's still some simplifying to be done). At the very least it should be possible to pull some of it out into functions
___
*[`lib/compiler/test/test_generator.h` line 47 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKlcTp807UlhySvMhj:-NaKlcTp807UlhySvMhk:b-aobqrt) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L47)):*
> ```objc
>            std::vector<int> const &compn_type) {
>           auto g =
>               ::create<UnorderedOutputLabelledMultiDiGraph<Layer, Tensor>>();
> ```

Why is there nothing to the left of`::create`?
___
*[`lib/compiler/test/test_generator.h` line 78 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKl8P63Npu6mjskqcL:-NaKl8P63Npu6mjskqcM:btbhm94) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L78)):*
> ```objc
>             RC_ASSERT(source0 != source1 && sink0 != sink1);
> 
>             if (source0 == sink0 || t == 0) {
> ```

Would probably be a good idea to add parallel and serial composition as actual functions in the codebase as they're pretty core functionality
___
*[`lib/compiler/test/test_generator.h` line 117 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKkexC3miK_a1NmFb_:-NaKkexC3miK_a1NmFba:bsfcsg) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L117)):*
> ```objc
> 
> template <>
> struct Arbitrary<ParallelComputationGraph> {
> ```

Why do `ParallelComputationGraph` and `ComputationGraph` have separate `Arbitrary` instances?
___
*[`lib/compiler/test/test_generator.h` line 170 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKpvB72tAcnBjDC6Dz:-NaKpvB72tAcnBjDC6E-:b4p0vx2) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L170)):*
> ```objc
>             } else {
>               // parallel composition
>               g.add_edge(MultiDiOutput{source0, NodePort(0)},
> ```

Should be constructed by `add_node_port`



_Code quote:_
```objc
NodePort(0)
```
___
*[`lib/compiler/test/test_machine_mapping.cc` line 10 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKmHF3Ejylc8dfdMpR:-NaKmHF3Ejylc8dfdMpS:b-oyz2lg) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_machine_mapping.cc#L10)):*
> ```cpp
>     MachineMapping comb = MachineMapping::sequential_combine(mp0, mp1);
> 
>     RC_ASSERT(comb.runtime == mp0.runtime + mp1.runtime);
> ```

We should pull `runtime` out of `MachineMapping` for the sake of immutability
___
*[`lib/compiler/test/test_machine_mapping.cc` line 21 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKnRpw9PHi9rpJvzxu:-NaKnRpw9PHi9rpJvzxv:b6ky8g) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_machine_mapping.cc#L21)):*
> ```cpp
> TEST_CASE("MachineMapping::parallel_combine") {
>   rc::check([](MachineMapping const &mp0, MachineMapping const &mp1) {
>     RC_PRE(are_disjoint(keys(mp0), keys(mp1)));
> ```

Should this be `keys(mp0.machine_views)`, or is there a `keys(...)` instance for `MachineMapping` somewhere I missed. Also might be nice to just add a `are_disjoint(MachineMapping const &, MachineMapping const &)` or `nodes_are_disjoint(MachineMapping const &, MachineMapping const &)`
___
*[`lib/compiler/test/test_machine_mapping.cc` line 30 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKnEwh6909gwjF__6m:-NaKnEwh6909gwjF__6n:bah00oi) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_machine_mapping.cc#L30)):*
> ```cpp
>     for (auto p : mp0.machine_views) {
>       RC_ASSERT(p.second == comb.machine_views.at(p.first));
>     }
> ```

Also, might be nice to just define an `is_submap` in `containers.h`



_Suggestion:_
```cpp
    RC_ASSERT(restrict_keys(comb.machine_views, keys(mp0)) == mp0);
```
___
*[`lib/compiler/test/test_machine_mapping.cc` line 34 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKnmNWAW-p8Z-5mpZN:-NaKnmNWAW-p8Z-5mpZO:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_machine_mapping.cc#L34)):*
> ```cpp
> }
> 
> TEST_CASE("MachieMapping::infinity") {
> ```





_Suggestion:_
```cpp
MachineMapping
```
___
*[`lib/compiler/test/test_optimal_cost.cc` line 5 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKovlk815FjzkVXa0y:-NaKovlk815FjzkVXa0z:b-tw3o3) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_optimal_cost.cc#L5)):*
> ```cpp
> 
> TEST_CASE("optimal_cost") {
>   rc::check([](ParallelComputationGraph const &g) {
> ```

Can you add a quick explanation of what these tests are checking? It's a little nontrivial to decode them currently
___
*[`lib/compiler/test/test_optimal_cost.cc` line 13 at r4](https://reviewabl [...]

2023-08-02 16:14 UTC, wmdi reviewed
I suggest we merge https://github.com/flexflow/FlexFlow/pull/842 before merging this pr, because there are some dependencies in graphs.

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870#-:-Nar08AR93m9NZGxFa6L:b5px9bn)* status: all files reviewed, 16 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/src/machine_mapping.cc` line 204 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKphyK0V6yxPTQr7Xp:-NaqnaIf5pZYpoMNr44k:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/src/machine_mapping.cc#L204)):*
> ```cpp
>                                      cached_subgraph_costs),
>                          post_decompn)),
>                MachineMappingRuntimeCmp{});
> ```

Done.
___
*[`lib/compiler/test/test_generator.h` line 21 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKkrYHBVlb4A798g3q:-NaqngjLB9PhYHkiOxuP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why not add an arbitrary instance for `gpu_id_t`? (or even `strong_typedef` in general)
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_generator.h` line 41 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKlLt14bXgb3zXE3VU:-Naqni6M9yE_uDi0T4Ml:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L41)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If would be really nice to clean up this code a bit -- it's currently really hard to read/understand (and some of this may be complexity we can't avoid, but I think there's still some simplifying to be done). At the very least it should be possible to pull some of it out into functions
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_generator.h` line 47 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKlcTp807UlhySvMhj:-NaqnjP75fQhWaFZgCkM:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L47)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is there nothing to the left of`::create`?
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_generator.h` line 78 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKl8P63Npu6mjskqcL:-NaqnrVb-FWMZmUxJJkr:b-tphiki) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L78)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Would probably be a good idea to add parallel and serial composition as actual functions in the codebase as they're pretty core functionality
</blockquote></details>

I agree. But we should have a consistent definition of parallel and serial composition first, i.e., 1)different appearance of parallel and serial composition should have the same meaning, and 2) serial-parallel composition and serial-parallel decomposition should be the inverse of each other.

There might be two (or even more) different ways to define it: (I only describe serial composition here, as parallel composition should be similar.)

1. For two graphs 'g_1' and 'g_2', a serial composition means we merge the sink node of 'g_1' and the source node of 'g_2' as a single node. This definition assumes all the graphs are perfect two-terminal series–parallel graphs.
2. For two graphs 'g_1' and 'g_2', a serial composition means we add edges between the sink nodes of 'g_1' and the source nodes of 'g_2'. This definition allows we have multiple source/sink nodes (perhaps with additional conventions of how to add edges).

The first one is the definition in graph theory, while the second one is the inverse of the sp decomposition we have now in the codebase.
___
*[`lib/compiler/test/test_generator.h` line 117 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKkexC3miK_a1NmFb_:-Naqs4ojApcg8Zx_DHgG:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L117)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why do `ParallelComputationGraph` and `ComputationGraph` have separate `Arbitrary` instances?
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_generator.h` line 170 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKpvB72tAcnBjDC6Dz:-Naqs61N6DI0IS9c31GX:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L170)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should be constructed by `add_node_port`
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_machine_mapping.cc` line 10 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKmHF3Ejylc8dfdMpR:-NaqsDY_AzbdorbO6nop:bhma5lo) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_machine_mapping.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

We should pull `runtime` out of `MachineMapping` for the sake of immutability
</blockquote></details>

I don't quite get it. Could you explain more? 
___
*[`lib/compiler/test/test_machine_mapping.cc` line 21 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKnRpw9PHi9rpJvzxu:-NaquZgV52EuRRrAJcuL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_machine_mapping.cc#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should this be `keys(mp0.machine_views)`, or is there a `keys(...)` instance for `MachineMapping` somewhere I missed. Also might be nice to just add a `are_disjoint(MachineMapping const &, MachineMapping const &)` or `nodes_are_disjoint(MachineMapping const &, MachineMapping const &)`
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_machine_mapping.cc` line 30 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKnEwh6909gwjF__6m:-NaquYDJ2DvwfzDy6232:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_machine_mapping.cc#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Also, might be nice to just define an `is_submap` in `containers.h`
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_machine_mapping.cc` line 34 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKnmNWAW-p8Z-5mpZN:-NaqucaR3KuKuyPB9KBr:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_machine_mapping.cc#L34)):*
> ```cpp
> }
> 
> TEST_CASE("MachieMapping::infinity") {
> ```

Done.
___
*[`lib/compiler/test/test_optimal_cost.cc` line 13 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKoFg70RMENTxMCLss:-NaqxAiZ8LsQ2KILQseS:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_optimal_cost.cc#L13)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Add strong_typedefs for the args of MachineSpecification--it's quite unclear what these numbers mean currently
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_unity_algorithm.cc` line 23 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKpBfWADwSYHBhVcmb:-Naqx_FM9leNp_osEAag:b-896fix) ([raw file](https://github.com/flexflow/FlexF [...]

2023-08-02 16:24 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: 29 of 45 files reviewed, 16 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/test/test_optimal_cost.cc` line 18 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKoRDZ5fjJ_B5Emac8:-Nar2hXo0WPG4dPA4uch:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_optimal_cost.cc#L18)):*
> ```cpp
>     for (auto node : get_nodes(g)) {
>       RC_ASSERT(contains_key(machine_mapping.machine_views, node));
>     }
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-08-02 16:25 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: 29 of 45 files reviewed, 16 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/graph/cow_ptr_t.h` line 14 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKpNcg3V4DxniL5VoZ:-Nar3RivETdsyBA_YK6N:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/utils/include/utils/graph/cow_ptr_t.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

And create an issue, assign it to me, and link it in the comment after the TODO
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-02 16:51 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: 29 of 45 files reviewed, 16 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/test/test_generator.h` line 78 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKl8P63Npu6mjskqcL:-Nar3yid92-kc-krSo0C:b-qp4xfr) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L78)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I agree. But we should have a consistent definition of parallel and serial composition first, i.e., 1)different appearance of parallel and serial composition should have the same meaning, and 2) serial-parallel composition and serial-parallel decomposition should be the inverse of each other.

There might be two (or even more) different ways to define it: (I only describe serial composition here, as parallel composition should be similar.)

1. For two graphs 'g_1' and 'g_2', a serial composition means we merge the sink node of 'g_1' and the source node of 'g_2' as a single node. This definition assumes all the graphs are perfect two-terminal series–parallel graphs.
2. For two graphs 'g_1' and 'g_2', a serial composition means we add edges between the sink nodes of 'g_1' and the source nodes of 'g_2'. This definition allows we have multiple source/sink nodes (perhaps with additional conventions of how to add edges).

The first one is the definition in graph theory, while the second one is the inverse of the sp decomposition we have now in the codebase.
</blockquote></details>

It seems that we cannot use the definition in graph theory, because it duplicates some nodes in decomposition, which is not good for our algorithm.

If we use the second definition, we have to solve the 'additional conventions': According to the current sp decomposition we have, a parallel composition means we put g_1 and g_2 in parallel. As a result, we will have a graph with more than 1 source/sink nodes. Then how do we serially compose the following two graphs?
```
g_1: n0 -> n1
      n2 -> n3
g_2: n4 -> n5
      n6 -> n7
```
In decomposition, we never encounter this case, because we will have a parallel decomposition before. However, in composition, we have to deal with it because we are building the graph in a bottom-up way.

Another way is to use definition 1 for serial and parallel composition to build a perfect two-terminal series–parallel graph, and use definition 2 for decomposition for the convenience of our algorithm.

Any thoughts?


<!-- Sent from Reviewable.io -->

2023-08-03 11:27 UTC, lockshaw requested changes
> Reviewed 15 of 16 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: all files reviewed, 13 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/test/test_generator.h` line 41 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKlLt14bXgb3zXE3VU:-Nav7r_0BK3lMc2q8jju:b-wqww06) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L41)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Well done, the new code is already much easier to understand :slightly_smiling_face: 
___
*[`lib/compiler/test/test_generator.h` line 78 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKl8P63Npu6mjskqcL:-Nav4ZyX2eeTYclU2RTQ:brv7w8x) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L78)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

It seems that we cannot use the definition in graph theory, because it duplicates some nodes in decomposition, which is not good for our algorithm.

If we use the second definition, we have to solve the 'additional conventions': According to the current sp decomposition we have, a parallel composition means we put g_1 and g_2 in parallel. As a result, we will have a graph with more than 1 source/sink nodes. Then how do we serially compose the following two graphs?
```
g_1: n0 -> n1
      n2 -> n3
g_2: n4 -> n5
      n6 -> n7
```
In decomposition, we never encounter this case, because we will have a parallel decomposition before. However, in composition, we have to deal with it because we are building the graph in a bottom-up way.

Another way is to use definition 1 for serial and parallel composition to build a perfect two-terminal series–parallel graph, and use definition 2 for decomposition for the convenience of our algorithm.

Any thoughts?
</blockquote></details>

I would use definition 2, with the serial composition of the graphs you gave being 
```
digraph G {
  n0 -> n1;
  n2 -> n3;
  n1 -> n4;
  n1 -> n6;
  n3 -> n4;
  n3 -> n6;
  n4 -> n5;
  n6 -> n7;
}
```
(i.e., add all-to-all edges between all sink nodes of `g_1` and all source nodes of `g_2`--I think this is the only way you can get the guarantees that everything in `g_1` will execute before anything in `g_2` can execute) 
___
*[`lib/compiler/test/test_generator.h` line 10 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav59cTCNh_Ukv2NDzf:-Nav59cU881KL4r_u_K0:b-bvb7e3) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L10)):*
> ```objc
> using namespace FlexFlow;
> 
> enum class CompnType { SERIAL, PARALLEL };
> ```

What does `Compn` stand for? Composition? If so I'd just write that out as `Compn` is a little ambiguous
___
*[`lib/compiler/test/test_generator.h` line 31 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav5jFxDb29_g0m3_1n:-Nav5jFxDb29_g0m3_1o:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L31)):*
> ```objc
>   Generates a series-parallel graph according to the composition sequence
>   described by `composition`. A series-parallel graph can be generated as
>   follows: 1) Initially, we have E (E is the length of `composition`+1)
> ```





_Suggestion:_
```objc
E is `composition.size()+1`
```
___
*[`lib/compiler/test/test_generator.h` line 32 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav5u40EUGPytIQ7fze:-Nav5u40EUGPytIQ7fzf:bo30yo3) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L32)):*
> ```objc
>   described by `composition`. A series-parallel graph can be generated as
>   follows: 1) Initially, we have E (E is the length of `composition`+1)
>   components, each containing a single edge; 2) In iteration `i`, we compose two
> ```

It feels like it would be easier to have each of the starting graphs just be a single node and have composition be adding edges, not merging nodes. What do you think? I also wonder if this would make it easy to do SP graph generation via recursion rather than the current method (i.e., `generate_sp_graph(int num_compositions) = compose(randomComposition(), generate_sp_graph(randomNumLessThan(num_compositions)), generate_sp_graph(<remaining num_compositions>)`)



_Code quote:_
```objc
each containing a single edge
```
___
*[`lib/compiler/test/test_generator.h` line 47 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav6BczAdO2spR8qmGW:-Nav6BczAdO2spR8qmGX:bl23hen) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L47)):*
> ```objc
>       dstIdx; // src and dst node ports for each edge (I assume it is sufficient
>               // to make different edges have different NodePort. Correct me if
>               // I am wrong. @lockshaw)
> ```

Yes, that works
___
*[`lib/compiler/test/test_generator.h` line 48 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav7-9h-r0QNACduKR-:-Nav7-9h-r0QNACduKR0:b-ij6439) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L48)):*
> ```objc
>               // to make different edges have different NodePort. Correct me if
>               // I am wrong. @lockshaw)
>   AdjacencyMultiDiGraph g(0, 0, {});
> ```

`MultiDiGraph g = MultiDiGraph::create<AdjacencyMultiDiGraph>();`
___
*[`lib/compiler/test/test_generator.h` line 93 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav8B3A4fpu2_G4ag50:-Nav8B3A4fpu2_G4ag51:b-tdlbh9) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L93)):*
> ```objc
>     generate_test_labelled_sp_graph() {
>   NOT_IMPLEMENTED();
>   // Is there a way to construct a labelled graph from a MultiDiGraph and the
> ```

I don't think so right now, but it should be relatively easy to add a view that takes a `MultiDiGraph` and a `std::function<NodeLabel(Node const &)>` and a `std::function<OutputLabel(Output const &)>` and implements `IOutputLabelledMultiDiGraph`
___
*[`lib/compiler/test/test_generator.h` line 104 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav8l-D9kN3Mfg4q2-F:-Nav8l-D9kN3Mfg4q2-G:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L104)):*
> ```objc
> 
> template <typename Tag, typename T>
> struct Arbtrary<Tag> {
> ```





_Suggestion:_
```objc
Arbitrary
```
___
*[`lib/compiler/test/test_generator.h` line 113 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav8etaDXNmKG0NxtKB:-Nav8etaDXNmKG0NxtKC:b5nd76t) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L113)):*
> ```objc
> 
> template <>
> struct Arbitrary<Node> {
> ```

Why does this exist in addition to the generic `Arbitrary` instance for `strong_typedef`?
___
*[`lib/compiler/test/test_machine_mapping.cc` line 10 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKmHF3Ejylc8dfdMpR:-Nav3QaL-uhfsEOj1TGp:b-2csc74) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_machine_mapping.cc#L10)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

I don't quite get it. Could you explain more? 
</blockquote></details>

Conceptually I view the cost of a `MachineMapping` as separate from the views it holds. For example, if I just want to construct a `MachineMapping` in some other part of the c [...]

2023-08-09 22:53 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: all files reviewed, 12 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/test/test_generator.h` line 78 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKl8P63Npu6mjskqcL:-NavvIWmAlF8iIha7vbU:bpv1hyu) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_generator.h#L78)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I would use definition 2, with the serial composition of the graphs you gave being 
```
digraph G {
  n0 -> n1;
  n2 -> n3;
  n1 -> n4;
  n1 -> n6;
  n3 -> n4;
  n3 -> n6;
  n4 -> n5;
  n6 -> n7;
}
```
(i.e., add all-to-all edges between all sink nodes of `g_1` and all source nodes of `g_2`--I think this is the only way you can get the guarantees that everything in `g_1` will execute before anything in `g_2` can execute) 
</blockquote></details>

Good idea. In this way our definitions of composition and decomposition would be consistent.
___
*[`lib/compiler/test/test_generator.h` line 10 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav59cTCNh_Ukv2NDzf:-Navt-_z4pZROTdKuUBH:b-6txtuo) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What does `Compn` stand for? Composition? If so I'd just write that out as `Compn` is a little ambiguous
</blockquote></details>

It stands for composition. I think I overused 'compn'.
___
*[`lib/compiler/test/test_generator.h` line 31 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav5jFxDb29_g0m3_1n:-NavwxJJEsPZtiaSXyzj:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L31)):*
> ```objc
>   Generates a series-parallel graph according to the composition sequence
>   described by `composition`. A series-parallel graph can be generated as
>   follows: 1) Initially, we have E (E is the length of `composition`+1)
> ```

Done.
___
*[`lib/compiler/test/test_generator.h` line 32 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav5u40EUGPytIQ7fze:-Navu0296_764F4c7hZW:bt959g7) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

It feels like it would be easier to have each of the starting graphs just be a single node and have composition be adding edges, not merging nodes. What do you think? I also wonder if this would make it easy to do SP graph generation via recursion rather than the current method (i.e., `generate_sp_graph(int num_compositions) = compose(randomComposition(), generate_sp_graph(randomNumLessThan(num_compositions)), generate_sp_graph(<remaining num_compositions>)`)
</blockquote></details>

Starting with edges and merging nodes align with the graph theory definition (definition 1 in our discussion). But since we decide to use definition 2, it will be good to start with a single node.
___
*[`lib/compiler/test/test_generator.h` line 48 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav7-9h-r0QNACduKR-:-NbRSAow30LVoi2Eb8Ii:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L48)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`MultiDiGraph g = MultiDiGraph::create<AdjacencyMultiDiGraph>();`
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_generator.h` line 104 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav8l-D9kN3Mfg4q2-F:-NbRSKPb-_N3Cj5YOZxj:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L104)):*
> ```objc
> 
> template <typename Tag, typename T>
> struct Arbtrary<Tag> {
> ```

Done.
___
*[`lib/compiler/test/test_generator.h` line 113 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav8etaDXNmKG0NxtKB:-NbRSLkD83NesFVsf6MK:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L113)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why does this exist in addition to the generic `Arbitrary` instance for `strong_typedef`?
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_optimal_cost.cc` line 5 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKovlk815FjzkVXa0y:-NbRUH3nA8dOKv15L0i7:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_optimal_cost.cc#L5)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you add a quick explanation of what these tests are checking? It's a little nontrivial to decode them currently
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-10 01:15 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: 43 of 45 files reviewed, 12 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/test_types.h` line 84 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaskROl5dJ_e4iEWBoI:-NbS-v808Cmu7wmld_bk:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/utils/include/utils/test_types.h#L84)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Commented out code here should be removed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-11 01:19 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: 42 of 45 files reviewed, 12 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/test/test_generator.h` line 93 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav8B3A4fpu2_G4ag50:-NbX270WCbvNeEGxbJ28:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L93)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think so right now, but it should be relatively easy to add a view that takes a `MultiDiGraph` and a `std::function<NodeLabel(Node const &)>` and a `std::function<OutputLabel(Output const &)>` and implements `IOutputLabelledMultiDiGraph`
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_machine_mapping.cc` line 4 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nask2yKCxN3OFEWA4La:-NbX2BgL60LCSUOBUW1u:b-ic0xwh) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_machine_mapping.cc#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This seems general enough to justify moving out of tests and into the standard codebase
</blockquote></details>

For now I keep the new codes as local as possible for convenience. After you review the serial parallel composition codes I will move all the general codes into proper position together.


<!-- Sent from Reviewable.io -->

2023-08-11 02:52 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: 41 of 45 files reviewed, 12 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/test/test_generator.h` line 93 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav8B3A4fpu2_G4ag50:-NbXVYBF0QNJBZ34BB2C:b-95od14) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L93)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And where are the serialization methods, which are to serialize a graph view into a graph?
___
*[`lib/compiler/test/test_machine_mapping.cc` line 10 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NaKmHF3Ejylc8dfdMpR:-NbXV0J7EboR7bkW7SPG:b78b471) ([raw file](https://github.com/flexflow/FlexFlow/blob/908a66ca4d3d276713735ad3edbcc0d719a0dfba/lib/compiler/test/test_machine_mapping.cc#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Conceptually I view the cost of a `MachineMapping` as separate from the views it holds. For example, if I just want to construct a `MachineMapping` in some other part of the code, or as part of a test, etc., what value would I assign `runtime`? I was thinking that it might be nice to make `MachineMapping` just be a `std::unordered_map<Node, MachineView>`, and have a separate component that calculates and caches `runtime_cost(MachineView const &)`. Would that work with the current design?
</blockquote></details>

Actually, the current `MachineMapping` should be viewed as the type for dp result, which is the cost with the corresponding strategy(machine mapping). I have separated MachineMapping from the dp result.


<!-- Sent from Reviewable.io -->

2023-08-14 14:17 UTC, wmdi reviewed
> Reviewed 2 of 12 files at r2, 24 of 33 files at r3, 11 of 16 files at r5, 1 of 1 files at r8, 3 of 6 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: all files reviewed, 12 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2023-08-14 14:42 UTC, wmdi reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: 40 of 46 files reviewed, 12 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/test/test_machine_mapping.cc` line 4 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nask2yKCxN3OFEWA4La:-NboUqqv7F-WpTB1-_KL:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_machine_mapping.cc#L4)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

For now I keep the new codes as local as possible for convenience. After you review the serial parallel composition codes I will move all the general codes into proper position together.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-17 08:43 UTC, lockshaw requested changes
> Reviewed 11 of 11 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: all files reviewed, 8 unresolved discussions (waiting on @lockshaw and @wmdi)

___
*[`lib/compiler/test/test_generator.h` line 93 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav8B3A4fpu2_G4ag50:-Nc1WWa_AQ-pU4rlIRSU:b-xosy3t) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L93)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

And where are the serialization methods, which are to serialize a graph view into a graph?
</blockquote></details>

`materialize_*` (https://github.com/flexflow/FlexFlow/blob/405ddf44f1214e0bba6ac3f41914749e49977bbe/lib/utils/include/utils/graph/views.h#L322-L347)
___
*[`lib/compiler/test/test_generator.h` line 120 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NbSXqsJ52zUrYfEpZ6i:-NbSXqsKCXKBrzcx5cdm:b4bshhy) ([raw file](https://github.com/flexflow/FlexFlow/blob/edb1c588cab76ffe31147523c4676f77d1332702/lib/compiler/test/test_generator.h#L120)):*
> ```objc
> 
> template <>
> struct Arbitrary<variant<Serial, Node>> {
> ```

Does there not exist automatic `Arbitrary` instances for `variant`? If not this should be added
___
*[`lib/compiler/test/test_generator.h` line 138 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NbSY8I41_NpOd_GmZSS:-NbSY8I41_NpOd_GmZST:b3pook0) ([raw file](https://github.com/flexflow/FlexFlow/blob/edb1c588cab76ffe31147523c4676f77d1332702/lib/compiler/test/test_generator.h#L138)):*
> ```objc
> 
> template <>
> struct Arbitrary<Serial> {
> ```

Aren't `Serial` and `Parallel` visitable? Doesn't visitable automatically define an arbitrary instance?
___
*[`lib/utils/src/graph/serialparallel.cc` line 221 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nc1Xoj230Y5wWIgYbgF:-Nc1Xoj230Y5wWIgYbgG:b20ev43) ([raw file](https://github.com/flexflow/FlexFlow/blob/60b6f59e5e357d23ba38325403eaa57d590e0aa0/lib/utils/src/graph/serialparallel.cc#L221)):*
> ```cpp
> }
> 
> std::unordered_map<Node, Node> parallel_extend(MultiDiGraph &g,
> ```

Can you add an issue to refactor these once global-nodes is merged? (and link it in the code). Feel free to assign the issue to me and add it to the project board
___
*[`lib/utils/src/graph/serialparallel.cc` line 267 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nc1dNzXDEX8NF0LQHCD:-Nc1dNzXDEX8NF0LQHCE:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/60b6f59e5e357d23ba38325403eaa57d590e0aa0/lib/utils/src/graph/serialparallel.cc#L267)):*
> ```cpp
> }
> 
> struct MultiDiGraphFromSPDecomposition {
> ```





_Suggestion:_
```cpp
struct MultiDiGraphFromSPDecompositionFunctor {
```
___
*[`lib/utils/src/graph/serialparallel.cc` line 291 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nc1dS9X6HAog4E7WmNG:-Nc1dS9X6HAog4E7WmNH:b-gpx7ek) ([raw file](https://github.com/flexflow/FlexFlow/blob/60b6f59e5e357d23ba38325403eaa57d590e0aa0/lib/utils/src/graph/serialparallel.cc#L291)):*
> ```cpp
> MultiDiGraph multidigraph_from_sp_decomposition(Serial const &serial) {
>   MultiDiGraph g = MultiDiGraph::create<AdjacencyMultiDiGraph>();
>   for (auto child : serial.children) {
> ```

Ideally write out the type here rather than use `auto` unless the type name is really long (also, `const &`)
___
*[`lib/utils/src/graph/serialparallel.cc` line 299 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nc1dY8S0JHmMA-mvV32:-Nc1dY8S0JHmMA-mvV33:b-gpx7ek) ([raw file](https://github.com/flexflow/FlexFlow/blob/60b6f59e5e357d23ba38325403eaa57d590e0aa0/lib/utils/src/graph/serialparallel.cc#L299)):*
> ```cpp
> MultiDiGraph multidigraph_from_sp_decomposition(Parallel const &parallel) {
>   MultiDiGraph g = MultiDiGraph::create<AdjacencyMultiDiGraph>();
>   for (auto child : parallel.children) {
> ```

Ideally write out the type here rather than use `auto` unless the type name is really long (also, `const &`)


<!-- Sent from Reviewable.io -->

2023-08-17 08:46 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: all files reviewed, 8 unresolved discussions (waiting on @wmdi)

___
*[`lib/compiler/test/test_generator.h` line 32 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav5u40EUGPytIQ7fze:-Nc1ez4ABQ65AYn0oDHL:b-7lfnsq) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L32)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Starting with edges and merging nodes align with the graph theory definition (definition 1 in our discussion). But since we decide to use definition 2, it will be good to start with a single node.
</blockquote></details>

Sounds good. Do you want to implement this in this PR or do a follow-up PR?


<!-- Sent from Reviewable.io -->

2023-08-18 01:30 UTC, wmdi reviewed
> Reviewed 11 of 11 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: all files reviewed, 8 unresolved discussions (waiting on @lockshaw)

___
*[`lib/compiler/test/test_generator.h` line 32 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav5u40EUGPytIQ7fze:-Nc4NwPwAMvfOSJ7qMCe:b-hhv4y6) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L32)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Sounds good. Do you want to implement this in this PR or do a follow-up PR?
</blockquote></details>

I think it is done in this PR, by constructing graphs from sp decomposition (without using global nodes).
___
*[`lib/compiler/test/test_generator.h` line 93 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nav8B3A4fpu2_G4ag50:-Nc5DCZR4ts3S9cU5v_W:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/4c7e56eee94e813ccc9afc7e3bc4b919728aeb53/lib/compiler/test/test_generator.h#L93)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`materialize_*` (https://github.com/flexflow/FlexFlow/blob/405ddf44f1214e0bba6ac3f41914749e49977bbe/lib/utils/include/utils/graph/views.h#L322-L347)
</blockquote></details>

Done.
___
*[`lib/compiler/test/test_generator.h` line 120 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NbSXqsJ52zUrYfEpZ6i:-Nc5DErD9mYD4-i0EPLM:b-l7tesz) ([raw file](https://github.com/flexflow/FlexFlow/blob/edb1c588cab76ffe31147523c4676f77d1332702/lib/compiler/test/test_generator.h#L120)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Does there not exist automatic `Arbitrary` instances for `variant`? If not this should be added
</blockquote></details>

No. And we can easily imagine that there isn't a clear way to define an `Arbitrary` instance for `variant`.
___
*[`lib/compiler/test/test_generator.h` line 138 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NbSY8I41_NpOd_GmZSS:-Nc5Db62CEzGBCd3xr0Z:b-20w329) ([raw file](https://github.com/flexflow/FlexFlow/blob/edb1c588cab76ffe31147523c4676f77d1332702/lib/compiler/test/test_generator.h#L138)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Aren't `Serial` and `Parallel` visitable? Doesn't visitable automatically define an arbitrary instance?
</blockquote></details>

Not for now. I tried to make it but had trouble with the macro stuffs. I will open an issue  for this.
___
*[`lib/utils/src/graph/serialparallel.cc` line 221 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nc1Xoj230Y5wWIgYbgF:-Nc5F2eD2tARAHUHgcUM:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/60b6f59e5e357d23ba38325403eaa57d590e0aa0/lib/utils/src/graph/serialparallel.cc#L221)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you add an issue to refactor these once global-nodes is merged? (and link it in the code). Feel free to assign the issue to me and add it to the project board
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/serialparallel.cc` line 267 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nc1dNzXDEX8NF0LQHCD:-Nc5FZam-HRSRG_mfq-c:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/60b6f59e5e357d23ba38325403eaa57d590e0aa0/lib/utils/src/graph/serialparallel.cc#L267)):*
> ```cpp
> }
> 
> struct MultiDiGraphFromSPDecomposition {
> ```

Done.
___
*[`lib/utils/src/graph/serialparallel.cc` line 291 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nc1dS9X6HAog4E7WmNG:-Nc5Fq9g0pf-2iQkq9UN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/60b6f59e5e357d23ba38325403eaa57d590e0aa0/lib/utils/src/graph/serialparallel.cc#L291)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Ideally write out the type here rather than use `auto` unless the type name is really long (also, `const &`)
</blockquote></details>

Done.
___
*[`lib/utils/src/graph/serialparallel.cc` line 299 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nc1dY8S0JHmMA-mvV32:-Nc5FrPi6hQctwnTkhPh:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/60b6f59e5e357d23ba38325403eaa57d590e0aa0/lib/utils/src/graph/serialparallel.cc#L299)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Ideally write out the type here rather than use `auto` unless the type name is really long (also, `const &`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-18 01:31 UTC, wmdi reviewed
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: all files reviewed, 8 unresolved discussions (waiting on @lockshaw)



<!-- Sent from Reviewable.io -->

2023-08-18 06:55 UTC, lockshaw approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/870)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wmdi)

___
*[`lib/compiler/test/test_generator.h` line 120 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NbSXqsJ52zUrYfEpZ6i:-Nc6PrxJ9fi8OxPFAE3x:b-lwxfi9) ([raw file](https://github.com/flexflow/FlexFlow/blob/edb1c588cab76ffe31147523c4676f77d1332702/lib/compiler/test/test_generator.h#L120)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

No. And we can easily imagine that there isn't a clear way to define an `Arbitrary` instance for `variant`.
</blockquote></details>

I'll work on adding one. https://github.com/flexflow/FlexFlow/issues/981
___
*[`lib/compiler/test/test_generator.h` line 138 at r7](https://reviewable.io/reviews/flexflow/FlexFlow/870#-NbSY8I41_NpOd_GmZSS:-Nc6OsLn4KUba0o5QFQR:bqcrhm0) ([raw file](https://github.com/flexflow/FlexFlow/blob/edb1c588cab76ffe31147523c4676f77d1332702/lib/compiler/test/test_generator.h#L138)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Not for now. I tried to make it but had trouble with the macro stuffs. I will open an issue  for this.
</blockquote></details>

https://github.com/flexflow/FlexFlow/issues/976
___
*[`lib/utils/src/graph/serialparallel.cc` line 221 at r12](https://reviewable.io/reviews/flexflow/FlexFlow/870#-Nc1Xoj230Y5wWIgYbgF:-Nc6QCR60ndJn5jYQC0D:bqcrhm0) ([raw file](https://github.com/flexflow/FlexFlow/blob/60b6f59e5e357d23ba38325403eaa57d590e0aa0/lib/utils/src/graph/serialparallel.cc#L221)):*
<details><summary><i>Previously, wmdi (Mengdi Wu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

https://github.com/flexflow/FlexFlow/issues/976


<!-- Sent from Reviewable.io -->

2023-08-18 06:57 UTC, merged