Fix/formatter
flexflow/FlexFlow pull request #886
Opened 2023-07-24 17:02 UTC by KateUnger

**Description of changes:**

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

2023-07-25 00:38 UTC, lockshaw requested changes
> Reviewed 9 of 23 files at r1, 1 of 4 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: all files reviewed, 19 unresolved discussions (waiting on @KateUnger)

___
*[`lib/runtime/src/optimizer.h` line 21 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9LclB3O9HMZt-o5Q5:-Na9LclB3O9HMZt-o5Q6:b-edbvir) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/optimizer.h#L21)):*
> ```objc
> #include "kernels/per_device_op_state.h"
> #include "legion.h"
> #include "parallel_computation_graph.h"
> ```

Why was this added?
___
*[`lib/runtime/src/serialization.h` line 150 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9LpSf8YsUhYvtsmhk:-Na9LpSf8YsUhYvtsmhl:b-qbkzyi) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/serialization.h#L150)):*
> ```objc
> template <typename T, typename Enable = void>
> struct Serialization {
>   void serialize(Legion::Serializer &sez, T const &) const;
> ```

Why were these names added?
___
*[`lib/runtime/src/ops/aggregate_spec.cc` line 267 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9MuD36WgADTVyBlZd:-Na9MuD4B8HN0K8uAxGQ:b-uvcvax) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/aggregate_spec.cc#L267)):*
> ```cpp
>   auto const &attrs = acc.get_argument<AggregateSpecAttrs>(ATTRS);
>   auto per_device_state =
>       acc.get_device_specific_argument<AggregateSpecPerDeviceState>(
> ```

Task implementations should not be aware of how their arguments were passed (i.e., device-specific or not). Whether or not an argument was passed as device-specific or not should be handled by `TaskArgumentAccessor` 



_Suggestion:_
```cpp
   acc.get_argument<AggregateSpecPerDeviceState>(
```
___
*[`lib/runtime/src/ops/attention.h` line 4 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9NaEeEAp_3DLskUKw:-Na9NaEeEAp_3DLskUKx:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.h#L4)):*
> ```objc
> #define _FLEXFLOW_ATTENTION_H
> 
> #include "../task_spec/op_task_signature.h"
> ```





_Suggestion:_
```objc
#include "runtime/task_spec/op_task_signature.h"
```
___
*[`lib/runtime/src/ops/attention.h` line 26 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9NkYvCZRRtNDVCnKm:-Na9NkYvCZRRtNDVCnKn:b5zok5j) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.h#L26)):*
> ```objc
>                                     Context ctx,
>                                     Runtime *runtime);
> static MHAPerDeviceState *init_task_impl(TaskArgumentAccessor const &acc);
> ```

The return type should be `DeviceSpecificArg<MHAPerDeviceState>` here I think 
___
*[`lib/runtime/src/ops/attention.cc` line 19 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9O6jLDZzEQUvtxr1W:-Na9O6jLDZzEQUvtxr1X:b-u9wb17) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L19)):*
> ```cpp
> #include "kernels/attention_kernels.h"
> #include "kernels/profiling.h"
> #include "model.h"
> ```

Why was this include added?
___
*[`lib/runtime/src/ops/attention.cc` line 161 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9OFDQ1ldERjnW_zTf:-Na9OFDQ1ldERjnW_zTg:bm099ba) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L161)):*
> ```cpp
> }
> 
> // Tensor FFModel::multihead_attention(const Tensor query,
> ```

Should be moved into the corresponding `op-attrs` `.cc` file
___
*[`lib/runtime/src/ops/attention.cc` line 530 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9OiC_3XXOnuTt0vLr:-Na9OiC_3XXOnuTt0vLs:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L530)):*
> ```cpp
>   TaskArgumentAccessor acc(task, regions, ctx, runtime);
> 
>   auto query = acc.get_tensor<FlexFlow::Permissions::RO>(QUERY);
> ```





_Suggestion:_
```cpp
Permissions::RO
```
___
*[`lib/runtime/src/ops/attention.cc` line 627 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9RN954RYk4XjU_UCh:-Na9RN954RYk4XjU_UCi:bcup8kh) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L627)):*
> ```cpp
> // }
> 
> static void backward_task(Task const *task,
> ```

Split into `backward_task` and `backward_task_impl`
___
*[`lib/runtime/src/ops/attention.cc` line 627 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9RUpW9l2cW87zS0IC:-Na9RUpW9l2cW87zS0ID:b-y43a8w) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L627)):*
> ```cpp
> // }
> 
> static void backward_task(Task const *task,
> ```

`impl` should return an `optional<float>` (the return value of `profile`)
___
*[`lib/runtime/src/ops/attention.cc` line 710 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9RmPx6oABjNDfenfC:-Na9RmPx6oABjNDfenfD:bjw3gx2) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L710)):*
> ```cpp
> template <>
> void register_task<ATTENTION_BWD_TASK_ID>() {
>   OpTaskSignature bwd(OpTaskType::BWD);
> ```

Move over to `infer_bwd_signature`
___
*[`lib/runtime/src/ops/attention.cc` line 718 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9RuaKEzdFEsQFINSk:-Na9RuaKEzdFEsQFINSl:bpmj9wi) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L718)):*
> ```cpp
>   bwd.add_weight_slot(WEIGHTS);
> 
>   OpTensorSlotSpec key_gradient = OpTensorSlotSpec(
> ```

I don't think there's any need to explicitly declare gradient slots anymore
___
*[`lib/runtime/src/task_spec/arg_ref.h` line 59 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9SKA32nsanqqIP_Kc:-Na9SKA4E_-t95k557cE:bj8lnei) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/arg_ref.h#L59)):*
> ```objc
>   ArgTypeRuntimeTag type_tag;
>   LABEL_TYPE ref_type;
>   optional<size_t> device_idx = nullopt;
> ```

`ArgRefSpec` should not include `device_idx`--this is entirely a runtime thing managed through `DeviceSpecificArg`
___
*[`lib/runtime/src/task_spec/op_task_signature.h` line 75 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9SWL6EL8QGBFfNH6o:-Na9SWL6EL8QGBFfNH6p:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/op_task_signature.h#L75)):*
> ```objc
>   template <typename T>
>   void add_unchecked_arg_slot(slot_id name) {
>     NOT_IMPLEMENTED()
> ```





_Suggestion:_
```objc
 NOT_IMPLEMENTED();
```
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 61 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9SkcDC-nKrmpdsd-a:-Na9SkcDC-nKrmpdsd-b:b-essvj3) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/task_argument_accessor.h#L61)):*
> ```objc
> };
> 
> static_assert(
> ```

Remove the static asserts
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 103 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9SxgM1NTxJ56UNmIJ:-Na9SxgM1NTxJ56UNmIK:bbk2uzr) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/task_argument_accessor.h#L103)):*
> ```objc
> 
>   PerDeviceFFHandle get_per_device_ffhandle() const {
>     return *((PerDeviceFFHandle [...]

2023-07-25 00:46 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: all files reviewed, 19 unresolved discussions (waiting on @lockshaw)

___
*[`lib/runtime/src/serialization.h` line 150 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9LpSf8YsUhYvtsmhk:-Na9VZcXAUiNVFJsxRdg:bjb76of) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/serialization.h#L150)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why were these names added?
</blockquote></details>

Readability


<!-- Sent from Reviewable.io -->

2023-07-25 00:48 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: all files reviewed, 19 unresolved discussions (waiting on @KateUnger)

___
*[`lib/runtime/src/serialization.h` line 150 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9LpSf8YsUhYvtsmhk:-Na9Vums2Tym5hEJcQdo:b-hqlxwm) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/serialization.h#L150)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Readability
</blockquote></details>

Okay, but these names add nothing over their types (like, what does `sez` add in addition to knowing it's a `Serializer`?)


<!-- Sent from Reviewable.io -->

2023-07-25 21:44 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: all files reviewed, 19 unresolved discussions (waiting on @lockshaw)

___
*[`lib/runtime/src/ops/aggregate_spec.cc` line 267 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9MuD36WgADTVyBlZd:-NaD0Yd15QXpAYn964EK:b-2l1zpb) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/aggregate_spec.cc#L267)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Task implementations should not be aware of how their arguments were passed (i.e., device-specific or not). Whether or not an argument was passed as device-specific or not should be handled by `TaskArgumentAccessor` 
</blockquote></details>

get_argument doesn't work anymore and I don't think there is a good way to get the argument unless its handled by TaskArgumentAccessor
___
*[`lib/runtime/src/ops/attention.h` line 4 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9NaEeEAp_3DLskUKw:-NaD0juc88skEx5FfV5P:bq0ncok) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.h#L4)):*
> ```objc
> #define _FLEXFLOW_ATTENTION_H
> 
> #include "../task_spec/op_task_signature.h"
> ```

sounds good
___
*[`lib/runtime/src/ops/attention.h` line 26 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9NkYvCZRRtNDVCnKm:-NaD1ldm9hcOzvYPLAfj:b86b05k) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.h#L26)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

The return type should be `DeviceSpecificArg<MHAPerDeviceState>` here I think 
</blockquote></details>

It was PerDeviceOpState, previously. Why would it be an Argument?
___
*[`lib/runtime/src/ops/attention.cc` line 19 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9O6jLDZzEQUvtxr1W:-NaE-gg45Pj05W0pA5c9:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was this include added?
</blockquote></details>

Done.
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 61 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9SkcDC-nKrmpdsd-a:-NaD4X-t-M1oDnWqUaIq:b-8l3fwy) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/task_argument_accessor.h#L61)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Remove the static asserts
</blockquote></details>

Why should I remove them?
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 131 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9T1jAA9OSFlmmcD82:-NaD4x3I15wNxtfhk-vo:bdxvzz8) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/task_argument_accessor.h#L131)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Delete, task impls should not know if args are device-specific or not
</blockquote></details>


Leaving it for now, until we decide on an alternative
___
*[`lib/utils/include/utils/containers.h` line 536 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9TEuu2q9pYPTM_Jeg:-NaD56bq4tet_EGwXPR3:b-72lirj) ([raw file](https://github.com/flexflow/FlexFlow/blob/1cb41b1d28961ef71b1a618dd02ddf84e87bb5e3/lib/utils/include/utils/containers.h#L536)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should not be removed, `unordered_set` doesn't have the right iterator type to support `std::remove_if` (should probably guard `inplace_filter` based on the iterator type)
</blockquote></details>

Adding back


<!-- Sent from Reviewable.io -->

2023-07-26 06:10 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: all files reviewed, 19 unresolved discussions (waiting on @KateUnger and @lockshaw)

___
*[`lib/runtime/src/ops/aggregate_spec.cc` line 267 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9MuD36WgADTVyBlZd:-NaFkyou-nCxQOgts2PW:b-1pk5at) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/aggregate_spec.cc#L267)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

get_argument doesn't work anymore and I don't think there is a good way to get the argument unless its handled by TaskArgumentAccessor
</blockquote></details>

Why doesn't `get_argument` work here?
___
*[`lib/runtime/src/ops/attention.h` line 26 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9NkYvCZRRtNDVCnKm:-NaFlCS_94GK76yCmCQY:bqdakn6) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.h#L26)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

It was PerDeviceOpState, previously. Why would it be an Argument?
</blockquote></details>

`DeviceSpecificArg` should probably be renamed--it's not really argument-specific, it just adds serializability for non-serializable types (and MHAPerDeviceState is not serializable)
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 61 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9SkcDC-nKrmpdsd-a:-NaFkOsE6t5GhQ1vBLly:b-xozv1s) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/task_argument_accessor.h#L61)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Why should I remove them?
</blockquote></details>

Because iirc they were just there for debugging. Those are fine static asserts to have, but they should be somewhere else (and probably through macros so they have more useful error messages)
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 131 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9T1jAA9OSFlmmcD82:-NaFkeFS-Znohm61-Wf-:bwv5cmz) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/task_argument_accessor.h#L131)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Leaving it for now, until we decide on an alternative
</blockquote></details>

I mean, the alternative is just to use `get_argument`, which I think should be correct


<!-- Sent from Reviewable.io -->

2023-07-26 06:17 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: all files reviewed, 19 unresolved discussions (waiting on @KateUnger and @lockshaw)

___
*[`lib/runtime/src/ops/attention.h` line 4 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9NaEeEAp_3DLskUKw:-NaFoGSw3ALMPd-7r1vq:b-ri8jtd) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.h#L4)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

sounds good
</blockquote></details>

If you address comments but don't actually push your fix yet, change your disposition to "Working" so I can mark it as read from my side without resolving the discussion entirely.
___
*[`lib/runtime/src/ops/attention.cc` line 19 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9O6jLDZzEQUvtxr1W:-NaFpmLZBLoNyGjffgCi:b-ri8jtd) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L19)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If you address comments but don't actually push your fix yet, change your disposition to "Working" so I can mark it as read from my side without resolving the discussion entirely.
___
*[`lib/utils/include/utils/containers.h` line 536 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9TEuu2q9pYPTM_Jeg:-NaFnZzKCoheILG0Tqxv:b-ri8jtd) ([raw file](https://github.com/flexflow/FlexFlow/blob/1cb41b1d28961ef71b1a618dd02ddf84e87bb5e3/lib/utils/include/utils/containers.h#L536)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Adding back
</blockquote></details>

If you address comments but don't actually push your fix yet, change your disposition to "Working" so I can mark it as read from my side without resolving the discussion entirely.


<!-- Sent from Reviewable.io -->

2023-07-27 05:26 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: 14 of 27 files reviewed, 19 unresolved discussions (waiting on @KateUnger and @lockshaw)

___
*[`lib/runtime/src/optimizer.h` line 21 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9LclB3O9HMZt-o5Q5:-NaIDcPO6qIqZ3GTJrTt:b9b8jbu) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/optimizer.h#L21)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why was this added?
</blockquote></details>

Deleting it and replacing the include with `task_spec/task_invocation.h` to declare `TaskInvocation` and `parallel_tensor_guid_t`
___
*[`lib/runtime/src/ops/aggregate_spec.cc` line 267 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9MuD36WgADTVyBlZd:-NaIPZJMAXmIXxw052fy:b-j7p64e) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/aggregate_spec.cc#L267)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why doesn't `get_argument` work here?
</blockquote></details>

I thought we were removing get_argument. I'll add it back
___
*[`lib/runtime/src/ops/attention.h` line 4 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9NaEeEAp_3DLskUKw:-NaIQCYJE4SFPDn3wLZd:boy9sbf) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.h#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If you address comments but don't actually push your fix yet, change your disposition to "Working" so I can mark it as read from my side without resolving the discussion entirely.
</blockquote></details>

I might be misunderstanding something, but that path doesn't work . I'll keep it with `..` for now. What I tried: 



_Code snippet:_
```objc
runtime/task_spec/op_task_signature.h: No such file or directory
    4 | #include "runtime/task_spec/op_task_signature.h"
```
___
*[`lib/runtime/src/ops/attention.h` line 26 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9NkYvCZRRtNDVCnKm:-NaJ16sw4a9LZTjpxz9G:b-og2dd6) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.h#L26)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`DeviceSpecificArg` should probably be renamed--it's not really argument-specific, it just adds serializability for non-serializable types (and MHAPerDeviceState is not serializable)
</blockquote></details>

Sounds good, added a constructor to be implemented later for DeviceSpecificArg<MHAPerDeviceState>
___
*[`lib/runtime/src/ops/attention.cc` line 19 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9O6jLDZzEQUvtxr1W:-NaJJCjn6dUaMJurFcXx:b-or1tbl) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L19)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

If you address comments but don't actually push your fix yet, change your disposition to "Working" so I can mark it as read from my side without resolving the discussion entirely.
</blockquote></details>

Removed, as well as other includes already in attention.h
___
*[`lib/runtime/src/ops/attention.cc` line 161 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9OFDQ1ldERjnW_zTf:-NaJJk-E9RnrUGJgsS4x:b-sw2fgv) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L161)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Should be moved into the corresponding `op-attrs` `.cc` file
</blockquote></details>

Sorry, I forgot to do that
___
*[`lib/runtime/src/ops/attention.cc` line 530 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9OiC_3XXOnuTt0vLr:-NaKlpwS1IhcI_obIz3t:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L530)):*
> ```cpp
>   TaskArgumentAccessor acc(task, regions, ctx, runtime);
> 
>   auto query = acc.get_tensor<FlexFlow::Permissions::RO>(QUERY);
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 627 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9RN954RYk4XjU_UCh:-NaKlx-gA2YpT5lgvb1x:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L627)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Split into `backward_task` and `backward_task_impl`
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 627 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9RUpW9l2cW87zS0IC:-NaKltt1-L0a4ua8-qb4:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L627)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`impl` should return an `optional<float>` (the return value of `profile`)
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 710 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9RmPx6oABjNDfenfC:-NaKmO2QBRuPts_ZezBt:b44bhb7) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L710)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move over to `infer_bwd_signature`
</blockquote></details>

I think that is for the backward() function (above). I think this should be what it is
___
*[`lib/runtime/src/ops/attention.cc` line 718 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9RuaKEzdFEsQFINSk:-NaJQYLVB0FDDyfHYfSc:brd0oc0) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L718)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think there's any need to explicitly declare gradient slots anymore
</blockquote></details>

Think I fixed this correctly, but please double check!
___
*[`lib/runtime/src/task_spec/arg_ref.h` line 59 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9SKA32nsanqqIP_Kc:-NaJTxLf3HToD1rxOQ52:bktzgl0) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/arg_ref.h#L59)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`ArgRefSpec` should not include `device_idx`--this is entirely a runtime thing managed through `DeviceSpecificArg`
</blockquote></details>

Removed it, I dont think I needed it for when I when I called it
___
*[`lib/runtime/src/task_spec/op_task_signature.h` line 75 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9SWL6EL8QGBFfNH6o:-NaKmmfa9hvWjyduU9La:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/op_task_signature.h#L75)):*
> ```objc
>   template <typename T>
>   void add_unchecked_arg_slot(slot_id name) {
>     NOT_IMPLEMENTED()
> ```

Done.
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 61 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9SkcDC-nKrmpdsd-a:-NaKmpmi4YG0Vw-TES4h:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/task_spec/task_argument_accessor.h#L61)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Because iirc they were just there for debugging. Those are fine static asserts to have, but they should be somewhere e [...]

2023-07-27 05:51 UTC, lockshaw requested changes
> Reviewed 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: all files reviewed, 10 unresolved discussions (waiting on @KateUnger)

___
*[`lib/runtime/src/ops/attention.h` line 15 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKqvN96LrNdyQzyOzf:-NaKqvN96LrNdyQzyOzg:bedi0wz) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/ops/attention.h#L15)):*
> ```objc
> using Legion::PhysicalRegion;
> using Legion::Runtime;
> using Legion::Task;
> ```

Not in the `.h`--this adds `Legion::Context`, etc. to the `FlexFlow` namespace for any file that transitively includes `attention.h`. This is acceptable in `.cc` files but not in `.h`



_Code quote:_
```objc
using Legion::Context;
using Legion::PhysicalRegion;
using Legion::Runtime;
using Legion::Task;
```
___
*[`lib/runtime/src/ops/attention.h` line 46 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKrCtME8CoQo75x0AG:-NaKrCtME8CoQo75x0AH:bbl5g6h) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/ops/attention.h#L46)):*
> ```objc
>                           Context ctx,
>                           Runtime *runtime);
> static optional<float> backward_task_impl(TaskArgumentAccessor const &acc);
> ```

These have static linkage
___
*[`lib/runtime/src/ops/attention.cc` line 710 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9RmPx6oABjNDfenfC:-NaKsDbtEwWO1S00IKf3:b-muqqfx) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L710)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

I think that is for the backward() function (above). I think this should be what it is
</blockquote></details>

I think there's `infer_bwd_signature` *and* `infer_bwd_binding`--correct me if I'm wrong
___
*[`lib/runtime/src/ops/attention.cc` line 79 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKrTjP1X8cG3USiap6:-NaKrTjP1X8cG3USiap7:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/ops/attention.cc#L79)):*
> ```cpp
>   OpTaskBinding b = infer_bwd_binding(forward(attrs).binding);
> 
>   return {BATCHMATMUL_BWD_TASK_ID, b};
> ```





_Suggestion:_
```cpp
return {ATTENTION_BWD_TASK_ID, b};
```
___
*[`lib/runtime/src/ops/attention.cc` line 154 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKrpue0C6xQXC4g-69:-NaKrpue0C6xQXC4g-6A:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/ops/attention.cc#L154)):*
> ```cpp
> }
> 
> static DeviceSpecificArg<MHAPerDeviceState> *
> ```


___
*[`lib/runtime/src/ops/attention.cc` line 163 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKrsLR3TpLchDZxGcD:-NaKrsLR3TpLchDZxGcE:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/ops/attention.cc#L163)):*
> ```cpp
> }
> 
> static DeviceSpecificArg<MHAPerDeviceState> *
> ```


___
*[`lib/runtime/src/task_spec/device_specific_arg.h` line 12 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKsw-D5hdqcGMVA1Lg:-NaKsw-D5hdqcGMVA1Lh:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/task_spec/device_specific_arg.h#L12)):*
> ```objc
> template <typename T>
> struct DeviceSpecificArg {
> ```





_Code snippet:_
```objc
DeviceSpecificArg() = delete;
```
___
*[`lib/runtime/src/task_spec/device_specific_arg.h` line 15 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKsWl3EIWLWirVCLT5:-NaKsWl3EIWLWirVCLT6:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/task_spec/device_specific_arg.h#L15)):*
> ```objc
>   DeviceSpecificArg(T *) {
>     NOT_IMPLEMENTED();
>   }
> ```





_Suggestion:_
```objc
  template <typename ...Args>
  static DeviceSpecificArg<T> create(size_t device_idx, Args &&... args) {
    NOT_IMPLEMENTED();
  }
```
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 100 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKtEhv51tbBpUSq-Kj:-NaKtEhv51tbBpUSq-Kk:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/task_spec/task_argument_accessor.h#L100)):*
> ```objc
>     // void *start_ptr = &((std::uint8_t *)this->task->args)[arg_fmt.start];
>     // Legion::Deserializer dez(start_ptr, arg_fmt.start);
> ```





_Code snippet:_
```objc
NOT_IMPLEMENTED();
```
___
*[`lib/utils/include/utils/sequence.h` line 7 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9TOs00NfkSJB25fzG:-NaKtXC68dPL36fU3F6b:b-48f295) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/utils/include/utils/sequence.h#L7)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think this diff got pushed--I'm still seeing that include


<!-- Sent from Reviewable.io -->

2023-07-27 23:10 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: 22 of 27 files reviewed, 10 unresolved discussions (waiting on @lockshaw)

___
*[`lib/runtime/src/ops/attention.h` line 15 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKqvN96LrNdyQzyOzf:-NaNUZ61-JblETfqLSv0:bb6un1j) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/ops/attention.h#L15)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Not in the `.h`--this adds `Legion::Context`, etc. to the `FlexFlow` namespace for any file that transitively includes `attention.h`. This is acceptable in `.cc` files but not in `.h`
</blockquote></details>

Done
___
*[`lib/runtime/src/ops/attention.h` line 46 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKrCtME8CoQo75x0AG:-NaNbAsq9UfDlFwgzYXU:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/ops/attention.h#L46)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

These have static linkage
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 710 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9RmPx6oABjNDfenfC:-NaNeu202m6u6Cdf664e:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/runtime/src/ops/attention.cc#L710)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think there's `infer_bwd_signature` *and* `infer_bwd_binding`--correct me if I'm wrong
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 79 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKrTjP1X8cG3USiap6:-NaNc9FH77gsXkuZI7th:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/ops/attention.cc#L79)):*
> ```cpp
>   OpTaskBinding b = infer_bwd_binding(forward(attrs).binding);
> 
>   return {BATCHMATMUL_BWD_TASK_ID, b};
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 154 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKrpue0C6xQXC4g-69:-NaNe4n61rO6mlfdTema:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/ops/attention.cc#L154)):*
> ```cpp
> }
> 
> static DeviceSpecificArg<MHAPerDeviceState> *
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 163 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKrsLR3TpLchDZxGcD:-NaNe5UK4z81FdVr0Ryg:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/ops/attention.cc#L163)):*
> ```cpp
> }
> 
> static DeviceSpecificArg<MHAPerDeviceState> *
> ```

Done.
___
*[`lib/runtime/src/task_spec/device_specific_arg.h` line 12 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKsw-D5hdqcGMVA1Lg:-NaOau-8E1Wh7mPIsGJ-:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/task_spec/device_specific_arg.h#L12)):*
> ```objc
> template <typename T>
> struct DeviceSpecificArg {
> ```

Done.
___
*[`lib/runtime/src/task_spec/device_specific_arg.h` line 15 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKsWl3EIWLWirVCLT5:-NaOawKZ-ZuPGLUXL2Nd:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/task_spec/device_specific_arg.h#L15)):*
> ```objc
>   DeviceSpecificArg(T *) {
>     NOT_IMPLEMENTED();
>   }
> ```

Done.
___
*[`lib/runtime/src/task_spec/task_argument_accessor.h` line 100 at r4](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaKtEhv51tbBpUSq-Kj:-NaNRHeUClXz5RK8cs0f:b-upvaie) ([raw file](https://github.com/flexflow/FlexFlow/blob/663024ae1051ded8d85dcd85706ddeb626d4a962/lib/runtime/src/task_spec/task_argument_accessor.h#L100)):*
> ```objc
>     // void *start_ptr = &((std::uint8_t *)this->task->args)[arg_fmt.start];
>     // Legion::Deserializer dez(start_ptr, arg_fmt.start);
> ```

I think you missed the NOT_IMPLEMENTED() call I already had there, correct me if I'm wrong!
___
*[`lib/utils/include/utils/sequence.h` line 7 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Na9TOs00NfkSJB25fzG:-NaNRtZA-KsDHfaa_8ht:bvp0wxw) ([raw file](https://github.com/flexflow/FlexFlow/blob/3c3c6b2d29a0fdc4806c8101848a5a27ae89a71d/lib/utils/include/utils/sequence.h#L7)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think this diff got pushed--I'm still seeing that include
</blockquote></details>

Yeah I missed the file, thank you


<!-- Sent from Reviewable.io -->

2023-07-28 03:48 UTC, lockshaw requested changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: all files reviewed, 15 unresolved discussions (waiting on @KateUnger)

___
*[`lib/runtime/src/ops/attention.h` line 4 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPXf411B0Y5xkZwljt:-NaPXf411B0Y5xkZwlju:bwqyw0k) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.h#L4)):*
> ```objc
> #define _FLEXFLOW_ATTENTION_H
> 
> #include "../task_spec/op_task_signature.h"
> ```

Change to `op_task_invocation.h`
___
*[`lib/runtime/src/ops/attention.h` line 5 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPXY2D8MGg_QCZTLyY:-NaPXY2D8MGg_QCZTLyZ:ble6w3p) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.h#L5)):*
> ```objc
> 
> #include "../task_spec/op_task_signature.h"
> #include "kernels/attention_kernels.h"
> ```

Move to `.cc` file
___
*[`lib/runtime/src/ops/attention.h` line 6 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPXa1V-x-le4Metrhr:-NaPXa1V-x-le4Metrhs:ble6w3p) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.h#L6)):*
> ```objc
> #include "../task_spec/op_task_signature.h"
> #include "kernels/attention_kernels.h"
> #include "legion.h"
> ```

Move to `.cc` file
___
*[`lib/runtime/src/ops/attention.h` line 117 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPXSOg8u-RpQorOMdF:-NaPXSOg8u-RpQorOMdG:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.h#L117)):*
> ```objc
> /* template <> OpTaskSignature get_signature<ATTENTION_INIT_TASK_ID>(); */
> /* template <> OpTaskSignature get_signature<ATTENTION_FWD_TASK_ID>(); */
> /* template <> OpTaskSignature get_signature<ATTENTION_BWD_TASK_ID>(); */
> ```


___
*[`lib/runtime/src/ops/attention.cc` line 146 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPYC3H0lIFRZYtqV5Z:-NaPYC3H0lIFRZYtqV5_:b-uy6e2k) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L146)):*
> ```cpp
>                                           get_float_ptr(weights),
>                                           get_float_ptr(weights_grad),
>                                           get_float_ptr(output_grad))
> ```

This should be calling `fwd_task_impl` and `bwd_task_impl`--see `aggregate.h`



_Code quote:_
```cpp
  float forward_time = profiling_wrapper(forward_kernel,
                                         settings,
                                         per_device_state,
                                         get_float_ptr(query),
                                         get_float_ptr(key),
                                         get_float_ptr(value),
                                         get_float_ptr(weights),
                                         get_float_ptr(output))
                           .value();

  float backward_time = profiling_wrapper(backward_kernel,
                                          settings,
                                          per_device_state,
                                          get_float_ptr(query),
                                          get_float_ptr(query_grad),
                                          get_float_ptr(key),
                                          get_float_ptr(key_grad),
                                          get_float_ptr(value),
                                          get_float_ptr(value_grad),
                                          get_float_ptr(weights),
                                          get_float_ptr(weights_grad),
                                          get_float_ptr(output_grad))
```
___
*[`lib/runtime/src/ops/attention.cc` line 166 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPYZoa7V-_rlv0Uvcd:-NaPYZoa7V-_rlv0Uvce:bh6kk1z) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L166)):*
> ```cpp
>   int vProjSize = acc.get_argument<int>(VPROJSIZE);
>   int oProjSize = acc.get_argument<int>(OPROJSIZE);
>   Allocator allocator = acc.get_allocator();
> ```

None of these are passed in the binding in `init(MultiHeadAttentionAttrs const &)`, so this will crash at runtime.

They're also not all included in the signature for `init` in `register_task<ATTENTION_INIT_TASK_ID>`. 

It would be good to start setting up basic unit tests that check the `OpTaskInvocation`s against the `OpTaskSignature`s for each task (not in this PR, but this should be next priority before refactoring more ops--no point refactoring them if they will likely end up wrong due to not having any testing--this will also provide additional motivation for us to get stuff building)



_Code quote:_
```cpp
  bool profiling = acc.get_argument<bool>(PROFILING);
  int kvSeqLength = acc.get_argument<int>(KVSEQLENGTH);
  int qSize = acc.get_argument<int>(QSIZE);
  int kSize = acc.get_argument<int>(KSIZE);
  int vSize = acc.get_argument<int>(VSIZE);
  int qProjSize = acc.get_argument<int>(QPROJSIZE);
  int kProjSize = acc.get_argument<int>(KPROJSIZE);
  int vProjSize = acc.get_argument<int>(VPROJSIZE);
  int oProjSize = acc.get_argument<int>(OPROJSIZE);
  Allocator allocator = acc.get_allocator();
```
___
*[`lib/runtime/src/ops/attention.cc` line 190 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPZjqP7FjlZUu-LpLR:-NaPZjqP7FjlZUu-LpLS:b-yyppho) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L190)):*
> ```cpp
>   assert(num_samples == output.shape[legion_dim_t(2)]);
>   assert(qoSeqLength == output.shape[legion_dim_t(1)]);
>   assert(oProjSize(attrs) == output.shape[legion_dim_t(0)]);
> ```

Interesting that this function doesn't actually care about the values in `query`, `key`, `value`, `weight`, and `output`, but just their shapes. If this ends up being a common behavior we should add the ability to pass in `input_tensor_shape(0)` as an `OpArgRef` in `OpTaskInvocation`



_Code quote:_
```cpp
  int qoSeqLength = query.shape[legion_dim_t(1)];

  int num_samples = query.shape[legion_dim_t(2)];
  assert(qoSeqLength == query.shape[legion_dim_t(1)]);
  assert(qSize == query.shape[legion_dim_t(0)]);
  assert(num_samples == key.shape[legion_dim_t(2)]);
  assert(kvSeqLength == key.shape[legion_dim_t(1)]);
  assert(kSize == key.shape[legion_dim_t(0)]);
  assert(num_samples == value.shape[legion_dim_t(2)]);
  assert(kvSeqLength == value.shape[legion_dim_t(1)]);
  assert(vSize == value.shape[legion_dim_t(0)]);
  int num_heads = weight.shape[legion_dim_t(1)];
  assert(num_samples == output.shape[legion_dim_t(2)]);
  assert(qoSeqLength == output.shape[legion_dim_t(1)]);
  assert(oProjSize(attrs) == output.shape[legion_dim_t(0)]);
```
___
*[`lib/runtime/src/ops/attention.cc` line 214 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaP_14K0gcAIzcidtP8:-NaP_14K0gcAIzcidtP9:b-3c0kpx) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L214)):*
> ```cpp
> }
> 
> static DeviceSpecificArg<MHAPerDeviceState>
> ```

Can you create an issue to rename this to `DeviceSpecific`?



_Code quote:_
```cpp
DeviceSpecificArg
```
___
*[`lib/runtime/src/ops/attention.cc` line 262 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaP_igV2MXoKFSTB-vP:-NaP_igV2MXoKFSTB-vQ:b-1ku5tz) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L262)):*
> ```cpp
>   auto query_grad = acc.get_tensor_grad<Permissions::RW>(QUERY);
>   auto key_grad = acc.get_tensor_grad<Permissions::RW>(KEY);
>   auto  [...]

2023-08-17 23:19 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: 22 of 32 files reviewed, 15 unresolved discussions (waiting on @KateUnger and @lockshaw)

___
*[`lib/runtime/src/ops/attention.h` line 4 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPXf411B0Y5xkZwljt:-NahFMRN2WeEiuuEDwdp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.h#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Change to `op_task_invocation.h`
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.h` line 5 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPXY2D8MGg_QCZTLyY:-NahFMhC6AnIiPhks08Y:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.h#L5)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `.cc` file
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.h` line 6 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPXa1V-x-le4Metrhr:-NahFNFD0eebBtlEimhP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.h#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `.cc` file
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.h` line 117 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPXSOg8u-RpQorOMdF:-NahN7cE1AlKGf3in5Cn:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.h#L117)):*
> ```objc
> /* template <> OpTaskSignature get_signature<ATTENTION_INIT_TASK_ID>(); */
> /* template <> OpTaskSignature get_signature<ATTENTION_FWD_TASK_ID>(); */
> /* template <> OpTaskSignature get_signature<ATTENTION_BWD_TASK_ID>(); */
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 146 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPYC3H0lIFRZYtqV5Z:-NbuIALFDseOlsEA8caR:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L146)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This should be calling `fwd_task_impl` and `bwd_task_impl`--see `aggregate.h`
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 166 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPYZoa7V-_rlv0Uvcd:-NbuU33w2k0K7IlkvNvM:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L166)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

None of these are passed in the binding in `init(MultiHeadAttentionAttrs const &)`, so this will crash at runtime.

They're also not all included in the signature for `init` in `register_task<ATTENTION_INIT_TASK_ID>`. 

It would be good to start setting up basic unit tests that check the `OpTaskInvocation`s against the `OpTaskSignature`s for each task (not in this PR, but this should be next priority before refactoring more ops--no point refactoring them if they will likely end up wrong due to not having any testing--this will also provide additional motivation for us to get stuff building)
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 190 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPZjqP7FjlZUu-LpLR:-NbuJt67CF7P3f6gkuu7:brs4yme) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L190)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Interesting that this function doesn't actually care about the values in `query`, `key`, `value`, `weight`, and `output`, but just their shapes. If this ends up being a common behavior we should add the ability to pass in `input_tensor_shape(0)` as an `OpArgRef` in `OpTaskInvocation`
</blockquote></details>

Will keep that in mind
___
*[`lib/runtime/src/ops/attention.cc` line 214 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaP_14K0gcAIzcidtP8:-Nah4Zhu3VMpzEH3fV8I:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L214)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can you create an issue to rename this to `DeviceSpecific`?
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 262 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaP_igV2MXoKFSTB-vP:-NbuUBLf8KNWSIlpZELq:bo21h4g) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L262)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What happens if these aren't passed to this task as they are untrainable?
</blockquote></details>

Added as issue
___
*[`lib/runtime/src/ops/attention.cc` line 263 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaP_SPa2Wv-kEWpGtaJ:-NbuKVrZEqwOhJvjzX1k:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L263)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Put the argument accessors together for clarity
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 301 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPa4rZB_y4i0820T9-:-NbuoVon-Lw5MHvYQG-v:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L301)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

All three of these signatures don't match the tasks or the bindings
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 305 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaP_rrGBMq81p3xpE2h:-NbuKqUb3LOxWxhGrv65:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L305)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think this is necessary anymore--was replaced by `ProfilingSettings`
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 340 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPWtgn9obea08Q2_iE:-Nah9GNT6GMjYrd7Ck-k:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L340)):*
> ```cpp
> void register_task<ATTENTION_BWD_TASK_ID>() {
>   OpTaskSignature bwd =
>       infer_bwd_signature(get_op_signature(AGG_SPEC_FWD_TASK_ID));
> ```

Done.
___
*[`lib/runtime/src/task_spec/device_specific_arg.h` line 10 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPaako5R2vyvT8-Kfv:-NahARJBC8l4qrrxbRmZ:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/task_spec/device_specific_arg.h#L10)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

How do we make sure that `ptr` actually gets deallocated eventually (don't fix this this PR, but add an issue or just think about it as we'll need to solve this in the future)
</blockquote></details>

Done.
___
*[`lib/runtime/src/task_spec/device_specific_arg.h` line 19 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaPaMQZBuhrZXKsqNCj:-Nc4msmj8bl0nwbnxJiA:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/ [...]

2023-08-17 23:19 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: 22 of 32 files reviewed, 15 unresolved discussions (waiting on @KateUnger and @lockshaw)

___
*[`lib/runtime/src/ops/attention.cc` line 262 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaP_igV2MXoKFSTB-vP:-Nc4myAj4YBTbfY5pBFi:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L262)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Added as issue
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-18 07:34 UTC, lockshaw requested changes
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: all files reviewed, 29 unresolved discussions (waiting on @KateUnger)

___
*[`lib/kernels/include/kernels/attention_kernels.h` line 44 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6RDMbBF3yjXArdmGn:-Nc6RDMcAjZNTZMx6vzX:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/kernels/include/kernels/attention_kernels.h#L44)):*
> ```objc
>                                    hiWinIdx,
>                                    reserveSpace,
>                                    allocator);
> ```





_Suggestion:_
```objc
FF_VISITABLE_STRUCT_NO_EQ(MHAPerDeviceState,
                                   handle,
                                   weightSize,
                                   reserveSpaceSize,
                                   attnDesc,
                                   qDesc,
                                   kDesc,
                                   vDesc,
                                   oDesc,
                                   devQoSeqArray,
                                   devKvSeqArray,
                                   loWinIdx,
                                   hiWinIdx,
                                   reserveSpace,
                                   allocator);
```
___
*[`lib/runtime/src/ops/attention.h` line 4 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6RMTs4_2RUjACeyhs:-Nc6RMTs4_2RUjACeyht:b-3h7lgi) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.h#L4)):*
> ```objc
> #define _FLEXFLOW_ATTENTION_H
> 
> #include "../task_spec/op_task_invocation.h"
> ```

I think this should work since `runtime/src` is in the include path



_Suggestion:_
```objc
#include "task_spec/op_task_invocation.h"
```
___
*[`lib/runtime/src/ops/attention.cc` line 214 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaP_14K0gcAIzcidtP8:-Nc6TKh4BC1PYnDIhI9O:bqcrhfx) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L214)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

https://github.com/flexflow/FlexFlow/issues/904
___
*[`lib/runtime/src/ops/attention.cc` line 262 at r5](https://reviewable.io/reviews/flexflow/FlexFlow/886#-NaP_igV2MXoKFSTB-vP:-Nc6T1N71xI-gkxTQi6Y:bqcrhl6) ([raw file](https://github.com/flexflow/FlexFlow/blob/ba9cbf307c032667c2a2ef7cd4675c15067e2444/lib/runtime/src/ops/attention.cc#L262)):*
<details><summary><i>Previously, KateUnger (Kate Unger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

https://github.com/flexflow/FlexFlow/issues/967
___
*[`lib/runtime/src/ops/attention.cc` line 56 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6SKeoEyfHnYKAwlfd:-Nc6SKeoEyfHnYKAwlfe:bporrxb) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L56)):*
> ```cpp
>   b.bind(VALUE, input_tensor(2));
>   b.bind(WEIGHTS, weight_tensor(0));
>   b.bind(OUTPUT, output_tensor(0));
> ```

Binding the tensors shouldn't be necessary anymore as `init_task_impl` only uses their shapes, so we can just `bind_arg` their shapes
___
*[`lib/runtime/src/ops/attention.cc` line 62 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6VoPd6mqbKIWD1eJY:-Nc6VoPd6mqbKIWD1eJZ:b-9gwju2) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L62)):*
> ```cpp
> 
>   // get 3 parallel tensor shapes to construct MultiHeadAttentionInputs (in
>   // init_task_impl)
> ```

I don't think this really adds much over the code
___
*[`lib/runtime/src/ops/attention.cc` line 63 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6Rcoi3knYM_4KcEhf:-Nc6Rcoi3knYM_4KcEhg:b-2wnnb0) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L63)):*
> ```cpp
>   // get 3 parallel tensor shapes to construct MultiHeadAttentionInputs (in
>   // init_task_impl)
>   b.bind_arg(QUERY_PARALLEL_TENSOR_SHAPE, parallel_tensor_shape(0));
> ```

Just like with `input_tensor(0)` vs `weight_tensor(0)` we should probably specify that we're referring to an input rather than a weight or output tensor



_Suggestion:_
```cpp
  b.bind_arg(QUERY_PARALLEL_TENSOR_SHAPE, input_parallal_tensor_shape(0));
```
___
*[`lib/runtime/src/ops/attention.cc` line 100 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6S0C0373yO0s-OvV_:-Nc6S0C0373yO0s-OvVa:bgcpcw5) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L100)):*
> ```cpp
>   auto const &attrs = acc.get_argument<MultiHeadAttentionAttrs>(ATTRS);
> 
>   // get ParallelTensorShapes from acc
> ```

This comment doesn't add anything over the code
___
*[`lib/runtime/src/ops/attention.cc` line 108 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6S4kr5zwOO--YVCQN:-Nc6S4kr5zwOO--YVCQO:bgcpcw5) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L108)):*
> ```cpp
>       acc.get_argument<ParallelTensorShape>(VALUE_PARALLEL_TENSOR_SHAPE);
> 
>   // create MultiHeadAttentionInputs from ParallelTensorShapes
> ```

This comment doesn't add anything over the code
___
*[`lib/runtime/src/ops/attention.cc` line 120 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6W-w6CALus5xMiVp-:-Nc6W-w6CALus5xMiVp0:b9nydal) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L120)):*
> ```cpp
>   int vSize = get_vSize(inputs);
> 
>   int qProjSize = acc.get_argument<int>(QPROJSIZE);
> ```

Would be nice if all argument accesses occurred at the top of the function
___
*[`lib/runtime/src/ops/attention.cc` line 211 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6SvXG-gClEAopqH4w:-Nc6SvXHBbg5QydaiunC:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L211)):*
> ```cpp
> 
> static optional<float> backward_task_impl(TaskArgumentAccessor const &acc) {
>   // tensors
> ```


___
*[`lib/runtime/src/ops/attention.cc` line 217 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6StZSCN3tLTijDREA:-Nc6StZSCN3tLTijDREB:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L217)):*
> ```cpp
>   auto weight = acc.get_tensor<Permissions::RO>(WEIGHTS);
> 
>   // tensor gradients
> ```


___
*[`lib/runtime/src/ops/attention.cc` line 224 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6Srv94joY922Bkk68:-Nc6Srv94joY922Bkk69:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L224)):*
> ```cpp
>   auto value_grad = acc.get_tensor_grad<Permissions::RW>(VALUE);
> 
>   // arguments
> ```


___
*[`lib/runtime/src/ops/attention.cc` line 283 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6WFTwExdjnFoMGr-N:-Nc6WFTwExdjnFoMGr-O:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L283)):*
> ```cpp
>   init_binding.bind(VALUE, value_shape);
>   init_binding.bind(WEIGHTS, weight_shape);
>   init_binding.bind(OUTPUT, output_shape);
> ```


___
*[`lib/runtime/src/ops/attention.cc` line 299 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6WK4y5DGj_zH6IsXg:-Nc6WK4y5DGj_zH6IsXh:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dc [...]

2023-08-19 21:27 UTC, KateUnger reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/886)* status: 29 of 31 files reviewed, 29 unresolved discussions (waiting on @lockshaw)

___
*[`lib/kernels/include/kernels/attention_kernels.h` line 44 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6RDMbBF3yjXArdmGn:-Nc8zX8M-TvoI1x4zkqT:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/kernels/include/kernels/attention_kernels.h#L44)):*
> ```objc
>                                    hiWinIdx,
>                                    reserveSpace,
>                                    allocator);
> ```

Done.
___
*[`lib/runtime/src/ops/attention.h` line 4 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6RMTs4_2RUjACeyhs:-Nc92O3lBVmIBk-FpaDE:b-igmpgd) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.h#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I think this should work since `runtime/src` is in the include path
</blockquote></details>

Sorry didn't catch this when pushing
___
*[`lib/runtime/src/ops/attention.cc` line 56 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6SKeoEyfHnYKAwlfd:-Nc9LG0zDpNoR9pdrO_m:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L56)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Binding the tensors shouldn't be necessary anymore as `init_task_impl` only uses their shapes, so we can just `bind_arg` their shapes
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 62 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6VoPd6mqbKIWD1eJY:-Nc9LO0x6YdL86sVPEUO:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L62)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I don't think this really adds much over the code
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 63 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6Rcoi3knYM_4KcEhf:-Nc9Pnsv9TClnJFNVD5d:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L63)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Just like with `input_tensor(0)` vs `weight_tensor(0)` we should probably specify that we're referring to an input rather than a weight or output tensor
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 100 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6S0C0373yO0s-OvV_:-Nc9QF8T6v6NHEE1R-ZD:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L100)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This comment doesn't add anything over the code
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 108 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6S4kr5zwOO--YVCQN:-Nc9QFdMDFh-WjoCc1uw:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L108)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This comment doesn't add anything over the code
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 120 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6W-w6CALus5xMiVp-:-Nc9fotn3gQxImfuRugs:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L120)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Would be nice if all argument accesses occurred at the top of the function
</blockquote></details>

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 211 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6SvXG-gClEAopqH4w:-Nc9gZRo6zZp-2Y7wzpM:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L211)):*
> ```cpp
> 
> static optional<float> backward_task_impl(TaskArgumentAccessor const &acc) {
>   // tensors
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 217 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6StZSCN3tLTijDREA:-Nc9gZx77nLCZBJlWcAy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L217)):*
> ```cpp
>   auto weight = acc.get_tensor<Permissions::RO>(WEIGHTS);
> 
>   // tensor gradients
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 224 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6Srv94joY922Bkk68:-Nc9yJ9kCbvSjI7XC0bc:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L224)):*
> ```cpp
>   auto value_grad = acc.get_tensor_grad<Permissions::RW>(VALUE);
> 
>   // arguments
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 283 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6WFTwExdjnFoMGr-N:-Nc9ht-Z-Gw4rD0A2B83:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L283)):*
> ```cpp
>   init_binding.bind(VALUE, value_shape);
>   init_binding.bind(WEIGHTS, weight_shape);
>   init_binding.bind(OUTPUT, output_shape);
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 299 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6WK4y5DGj_zH6IsXg:-Nc9hnrbA8u46J767JZp:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L299)):*
> ```cpp
>   init_binding.bind(VALUE, value_shape);
>   init_binding.bind(WEIGHTS, weight_shape);
>   init_binding.bind(OUTPUT, output_shape);
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 308 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6Sli7CCm19UvAWDzv:-Nc9iGG1C7ngJDaCwGGM:b-onqlpy) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L308)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What happens to the per device state that `init_task_impl` returns?
</blockquote></details>

Oh I'll bind that to fwd and bwd
___
*[`lib/runtime/src/ops/attention.cc` line 321 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6U1Zo2iVcZtFow7mT:-Nc9nItG6CccLtTstGku:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L321)):*
> ```cpp
>   init.add_arg_slot<int>(QUERY_PARALLEL_TENSOR_SHAPE);
>   init.add_arg_slot<int>(KEY_PARALLEL_TENSOR_SHAPE);
>   init.add_arg_slot<int>(VALUE_PARALLEL_TENSOR_SHAPE);
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 332 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6UjTw3-JFjFw9gojK:-Nc9nrJH8nXh3AKRvUta:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/runtime/src/ops/attention.cc#L332)):*
> ```cpp
>   init.add_input_slot(VALUE);
>   init.add_weight_slot(WEIGHTS);
>   init.add_output_slot(OUTPUT);
> ```

Done.
___
*[`lib/runtime/src/ops/attention.cc` line 350 at r6](https://reviewable.io/reviews/flexflow/FlexFlow/886#-Nc6V8GKDEB7txVsgDGN:-Nc9vQC36br2gjij_jxP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/c46173a9db2959dcd62a7c0c397c3d3f8e3b062d/lib/ [...]

2023-08-21 15:58 UTC, merged