add command line parsing and print for #issue942
flexflow/FlexFlow pull request #991
Opened 2023-08-19 09:16 UTC by lambda7xx

**Description of changes:**
- [x] add command line parsing and print for FFConfig
- [x] add parser test

**Related Issues:**

Linked Issues:
- Issue # [942](https://github.com/flexflow/FlexFlow/issues/942)

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/963)

2023-08-29 15:53 UTC, lockshaw requested changes
Can you add an issue to also allow this to pull from a config file (e.g., yaml or json) and link it here?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/991#-:-Nd0zooY4LyfPAgZxY2w:bk90gl7)* status: all files reviewed, 16 unresolved discussions (waiting on @lambda7xx)

___
*[`lib/utils/include/utils/parse.h` line 4 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNt9uR6cN0c9NxL7n9:-NcNt9uR6cN0c9NxL7nA:bi2bxsk) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L4)):*
> ```objc
> #define _FLEXFLOW_UTILS_INCLUDE_UTILS_PARSE_H
> 
> #include "runtime/config.h"
> ```

`utils` cannot depend on `runtime`
___
*[`lib/utils/include/utils/parse.h` line 12 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNtZTt4a73VnlrcUOO:-NcNtZTt4a73VnlrcUOP:b45h) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L12)):*
> ```objc
> namespace FlexFlow {
> 
> using VariantType = variant<int, bool, float, std::string>;
> ```





_Suggestion:_
```objc
using AllowedArgTypes = variant<int, bool, float, std::string>;
```
___
*[`lib/utils/include/utils/parse.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0za1YBXE4WrwGW9Lx:-Nd0za1YBXE4WrwGW9Ly:b31uhqf) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L14)):*
> ```objc
> using VariantType = variant<int, bool, float, std::string>;
> 
> class ArgsParser {
> ```

There should be a separate `ArgsSpec` or something which is a `visitable` object that contains a specification of the args that we can pass up to Python to plug into `argparse`
___
*[`lib/utils/include/utils/parse.h` line 18 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0ygDwD5uMySA27-iV:-Nd0ygDwD5uMySA27-iW:b-o45t9b) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L18)):*
> ```objc
>   std::unordered_map<std::string, std::string> mArgs;
>   std::unordered_map<std::string, VariantType> mDefaultValues;
>   std::unordered_map<std::string, std::string> mDescriptions;
> ```

Potentially unify into a single `unordered_map` where the values are structs? As long as they should always have the same keyset this would help prevent bugs



_Code quote:_
```objc
  std::unordered_map<std::string, std::string> mArgs;
  std::unordered_map<std::string, VariantType> mDefaultValues;
  std::unordered_map<std::string, std::string> mDescriptions;
```
___
*[`lib/utils/include/utils/parse.h` line 20 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNtly79wMqlZOCFEmF:-NcNtly79wMqlZOCFEmG:b83q3sc) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L20)):*
> ```objc
>   std::unordered_map<std::string, std::string> mDescriptions;
> 
>   std::string parseKey(std::string const &arg) const {
> ```

Convert to function (as there is no dependency on the class)
___
*[`lib/utils/include/utils/parse.h` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0ya7Q2yDZDnbZqMqB:-Nd0ya7Q2yDZDnbZqMqC:bmsohz) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L24)):*
> ```objc
>       return arg.substr(2);
>     } else {
>       return arg;
> ```

Why is the `--` here optional?
___
*[`lib/utils/include/utils/parse.h` line 30 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNtgqT57K1rqa9pTRa:-NcNtgqT57K1rqa9pTRb:ble6w3p) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L30)):*
> ```objc
> public:
>   ArgsParser() = default;
>   void parse_args(int argc, char **argv) {
> ```

Move to `.cc` file
___
*[`lib/utils/include/utils/parse.h` line 47 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0yrXR86Rc9d0WPLGY:-Nd0yrXR86Rc9d0WPLGZ:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L47)):*
> ```objc
>                     VariantType const &value,
>                     std::string const &description) {
>     mDefaultValues[parseKey(key)] = std::move(value);
> ```





_Suggestion:_
```objc
    mDefaultValues[parseKey(key)] = value;
```
___
*[`lib/utils/include/utils/parse.h` line 54 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0yGtC0dgJe9q3GgcN:-Nd0yGtC0dgJe9q3GgcO:bctwuy7) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L54)):*
> ```objc
>   T get(std::string const &key) const {
>     auto it = mArgs.find(key);
>     if (it != mArgs.end()) {
> ```

`contains` from `containers.h`?
___
*[`lib/utils/include/utils/parse.h` line 67 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0yx1o0QwJKsdNF5kx:-Nd0yx1o0QwJKsdNF5ky:b7s4xo2) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L67)):*
> ```objc
>   void showDescriptions() const {
>     for (auto const &kv : mDescriptions) {
>       std::cout << kv.first << ": " << kv.second << std::endl;
> ```

Also, this should probably use `fmt` or at the last use `ostream`'s alignment options



_Suggestion:_
```objc
      std::cerr << kv.first << ": " << kv.second << std::endl;
```
___
*[`lib/utils/include/utils/parse.h` line 74 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0z6rKByzQ67Xd8_hz:-Nd0z6rKByzQ67Xd8_i-:b-qi4sks) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L74)):*
> ```objc
>   T convert(std::string const &s) const;
> 
>   friend std::ostream &operator<<(std::ostream &out, ArgsParser const &args);
> ```

Use `fmt` for now
___
*[`lib/utils/include/utils/parse.h` line 89 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0zEn_4dQryxBXiVdl:-Nd0zEn_4dQryxBXiVdm:bm1q1wn) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L89)):*
> ```objc
> template <>
> bool ArgsParser::convert<bool>(std::string const &s) const {
>   return s == "true" || s == "1";
> ```

Is `ArgsParser` currently case-sensitive for these values?



_Suggestion:_
```objc
  return s == "true" || s == "1" || s == "yes";
```
___
*[`lib/utils/include/utils/parse.h` line 116 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNuuZQCkDgNgb1UzUD:-NcNuuZQCkDgNgb1UzUE:b-352vkc) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L116)):*
> ```objc
>     ArgsParser::get_from_variant<std::string>(VariantType const &v) const {
>   return mpark::get<std::string>(v);
> }
> ```

What is the purpose of these? It seems like they can all just be replaced by calling `get` directly?

At the very least they can be unified as suggested below



_Suggestion:_
```objc
template <typename T>
T ArgsParser::get_from_variant<T>(VariantType const &v) const {
  return mpark::get<int>(v);
}
```
___
*[`lib/utils/include/utils/parse.h` line 123 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0xUc-7bUZt5QSfgx1:-Nd0xUc-7bUZt5QSfgx2:b-giawbj) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L123)):*
> ```objc
> }
> 
> void FFConfig::parse_args(char **argv, int argc) {
> ```

This should go into `runtime`. `utils/parse` should just be a command-line parsing library with no explicit link to flexflow, and then `runtime` can use `utils/parse` for any flexflow-specific command line argument parsing
___
*[`lib/utils/include/ [...]

2023-08-29 23:43 UTC, lambda7xx commented
OK





<!-- Sent from Reviewable.io -->

2023-09-04 02:56 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 4 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNt9uR6cN0c9NxL7n9:-NdT6_2r2JxZNj2Rwal1:bcjx7rj) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L4)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`utils` cannot depend on `runtime`
</blockquote></details>

implement this in config.cc 


<!-- Sent from Reviewable.io -->

2023-09-04 02:58 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0ya7Q2yDZDnbZqMqB:-NdT7-MN-wJve4zpMoYI:b-eot4ky) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is the `--` here optional?
</blockquote></details>

for example, I pass "--size", it parse it and get 'size'


<!-- Sent from Reviewable.io -->

2023-09-05 09:41 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 116 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNuuZQCkDgNgb1UzUD:-NdZgKrK6YQIfDRw-ZzZ:b-t00046) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L116)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

What is the purpose of these? It seems like they can all just be replaced by calling `get` directly?

At the very least they can be unified as suggested below
</blockquote></details>

You mean ?



_Code snippet (i):_
```objc
template <typename T>
  T ArgsParser::get_from_variant(AllowedArgTypes const &v) const {
    return mpark::get<T>(v);
  }
```



_Code snippet (ii):_
```objc
I fix it.
```


<!-- Sent from Reviewable.io -->

2023-09-05 09:59 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 74 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0z6rKByzQ67Xd8_hz:-NdZlkG99qya8uTfWPlF:b-k68vaj) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L74)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Use `fmt` for now
</blockquote></details>

these commit are far behind the latest, maybe I should set a separate PR to use fmt after this PR is merged.


<!-- Sent from Reviewable.io -->

2023-09-05 10:01 UTC, lambda7xx reviewed
I reply in other channel.

> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/991#-:-NdV7VXG2Y2yW8GjJDMJ:b-39v20s)* status: 1 of 4 files reviewed, 16 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/parse.h` line 12 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNtZTt4a73VnlrcUOO:-NdT6h4-1mjScMVC2-Zy:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L12)):*
> ```objc
> namespace FlexFlow {
> 
> using VariantType = variant<int, bool, float, std::string>;
> ```

Done.
___
*[`lib/utils/include/utils/parse.h` line 20 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNtly79wMqlZOCFEmF:-NdT6yoM8pR8-BwHdmOY:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L20)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Convert to function (as there is no dependency on the class)
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/parse.h` line 30 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNtgqT57K1rqa9pTRa:-NdT8-Fe2x7RWE1mAY68:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L30)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Move to `.cc` file
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/parse.h` line 47 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0yrXR86Rc9d0WPLGY:-NdT8-py9nMHSod_VOGN:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L47)):*
> ```objc
>                     VariantType const &value,
>                     std::string const &description) {
>     mDefaultValues[parseKey(key)] = std::move(value);
> ```

Done.
___
*[`lib/utils/include/utils/parse.h` line 54 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0yGtC0dgJe9q3GgcN:-NdT8Ok8-WXumIAVtKzx:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L54)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

`contains` from `containers.h`?
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/parse.h` line 67 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0yx1o0QwJKsdNF5kx:-NdT8QkB6PT-ZXSwjVN1:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L67)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Also, this should probably use `fmt` or at the last use `ostream`'s alignment options
</blockquote></details>

Done.
___
*[`lib/utils/include/utils/parse.h` line 89 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0zEn_4dQryxBXiVdl:-NdT8Wgq-QC3er7OSrJz:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L89)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Is `ArgsParser` currently case-sensitive for these values?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-08 18:12 UTC, lockshaw requested changes
Can you add a link to the new issue here?

> Reviewed 3 of 3 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/991#-:-Ndpwx_P6Sftn1i_m0zh:bpa479i)* status: 2 of 5 files reviewed, 15 unresolved discussions (waiting on @lambda7xx)

___
*[`lib/runtime/src/config.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Ndpxpft40IhPnfLQxXM:-Ndpxpft40IhPnfLQxXN:brgi8mz) ([raw file](https://github.com/flexflow/FlexFlow/blob/901db09d3682390baad5af7b015faa679daeedd5/lib/runtime/src/config.cc#L6)):*
> ```cpp
> namespace FlexFlow {
> 
> // void FFConfig::parse_args(char **argv, int argc) {
> ```

Why is this all commented out?
___
*[`lib/utils/include/utils/parse.h` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0ya7Q2yDZDnbZqMqB:-NdpukaS6xz80tR6BOBr:bk0mqqm) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L24)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

for example, I pass "--size", it parse it and get 'size'
</blockquote></details>

Yes, but `parseKey("size")` also equals `"size"`, so wouldn't `./flexflow size 10` and `./flexflow --size 10` be treated identically (when one is clearly wrong)?
___
*[`lib/utils/include/utils/parse.h` line 54 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0yGtC0dgJe9q3GgcN:-NdpzdojDlfCw1y9Izvr:b-d1uzhr) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L54)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did this code disappear? I'm not seeing it
___
*[`lib/utils/include/utils/parse.h` line 74 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0z6rKByzQ67Xd8_hz:-NdpwT8J-6qZekCZi-nv:b2fje2t) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L74)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

these commit are far behind the latest, maybe I should set a separate PR to use fmt after this PR is merged.
</blockquote></details>

I'm okay with that--can you create an issue and link it here?
___
*[`lib/utils/include/utils/parse.h` line 89 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0zEn_4dQryxBXiVdl:-NdpwmHaDo5vVZFalB_m:b-74tkp0) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L89)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the case sensitivity handled, and I don't see test cases for this
___
*[`lib/utils/include/utils/parse.h` line 116 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNuuZQCkDgNgb1UzUD:-NdpwLB76-BhD1W744ew:b-5im063) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L116)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

You mean ?
</blockquote></details>

Or just get rid of the method entirely and just call `get` directly
___
*[`lib/utils/include/utils/parse.h` line 193 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NcNu21f5jFxQLU7Ohjq:-Ndpvzl39V6bTQ2f6z8z:bbwztv4) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L193)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

we still need pass the type. the below is my implementation.
</blockquote></details>

The key is to make `ArgRef` (also, rename to `CmdlineArgRef` for clarity) actually a `template <typename T> struct ArgRef;` so that you can get the type back again when you parse--that should fix the type inference problem
___
*[`lib/utils/include/utils/parse.h` line 23 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NdpyGQ56eGLxnE6A64T:-NdpyGQ56eGLxnE6A64U:bawibh5) ([raw file](https://github.com/flexflow/FlexFlow/blob/901db09d3682390baad5af7b015faa679daeedd5/lib/utils/include/utils/parse.h#L23)):*
> ```objc
> class ArgsParser {
> private:
>   std::unordered_map<std::string, std::string> mArgs;
> ```

Why not just use a single map?
___
*[`lib/utils/include/utils/parse.h` line 29 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Ndpy39z7NJa7wzwkoD0:-Ndpy39z7NJa7wzwkoD1:bc0qcta) ([raw file](https://github.com/flexflow/FlexFlow/blob/901db09d3682390baad5af7b015faa679daeedd5/lib/utils/include/utils/parse.h#L29)):*
> ```objc
> public:
>   ArgsParser() = default;
>   void parse_args(int argc, char **argv);
> ```

Where did the implementation of this go?
___
*[`lib/utils/src/parse.cc` line 41 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NdpvfUOE1rO09Y0WUxE:-NdpvfUOE1rO09Y0WUxF:b2dnicm) ([raw file](https://github.com/flexflow/FlexFlow/blob/8f04a1a91704eed7f65b2b8e76ab935918a63d1d/lib/utils/src/parse.cc#L41)):*
> ```cpp
>       std::cerr  << kv.first << ": " << kv.second << std::endl;
>     }
>   }
> ```

(also, formatting)



_Suggestion:_
```cpp
void ArgsParser::showDescriptions() const {
    std::cerr << *this << std::endl;
  }
```
___
*[`lib/utils/src/parse.cc` line 47 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NdpvQ7l00J4WF1FXPV2:-NdpvQ7l00J4WF1FXPV3:undefined) ([raw file](https://github.com/flexflow/FlexFlow/blob/8f04a1a91704eed7f65b2b8e76ab935918a63d1d/lib/utils/src/parse.cc#L47)):*
> ```cpp
>   args.showDescriptions();
>   return out;
> }
> ```





_Suggestion:_
```cpp
std::string format_as(ArgsParser const &args) {
  ... 
}
```


<!-- Sent from Reviewable.io -->

2023-09-26 13:55 UTC, lambda7xx commented
*[`lib/runtime/src/config.cc` line 6 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Ndpxpft40IhPnfLQxXM:-NfGlU-zDnqgw2YnzIaR:b-pwg4wv) ([raw file](https://github.com/flexflow/FlexFlow/blob/901db09d3682390baad5af7b015faa679daeedd5/lib/runtime/src/config.cc#L6)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why is this all commented out?
</blockquote></details>

it seems I remove the commented


<!-- Sent from Reviewable.io -->

2023-09-26 13:57 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 18 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0ygDwD5uMySA27-iV:-NfGli32ADCRyBSgkx4z:b-ym2p6v) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L18)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Potentially unify into a single `unordered_map` where the values are structs? As long as they should always have the same keyset this would help prevent bugs
</blockquote></details>

I think three is ok. one is for help, one is for default and other one is for args.


<!-- Sent from Reviewable.io -->

2023-09-26 13:59 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 14 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0za1YBXE4WrwGW9Lx:-NfGlv2nEAXTRo1cIDAC:bguccrr) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L14)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

There should be a separate `ArgsSpec` or something which is a `visitable` object that contains a specification of the args that we can pass up to Python to plug into `argparse`
</blockquote></details>

i am a little confused about your words.

you mean we should use FF like. `FF_STRUCT_VISITABLE` for `ArgsSpec`


<!-- Sent from Reviewable.io -->

2023-09-26 14:02 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 29 at r2](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Ndpy39z7NJa7wzwkoD0:-NfGmtt2AWy1NbfkAp6v:b-ah96bk) ([raw file](https://github.com/flexflow/FlexFlow/blob/901db09d3682390baad5af7b015faa679daeedd5/lib/utils/include/utils/parse.h#L29)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Where did the implementation of this go?
</blockquote></details>

it's for `help`. when user parse help, we just print all argument.


<!-- Sent from Reviewable.io -->

2023-09-26 14:03 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 54 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0yGtC0dgJe9q3GgcN:-NfGn6ne6WUc5Hv4jnPa:b-508pp5) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L54)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Did this code disappear? I'm not seeing it
</blockquote></details>

I will push. in my code, I use `contains` from. `containers.h`


<!-- Sent from Reviewable.io -->

2023-09-26 14:03 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 74 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0z6rKByzQ67Xd8_hz:-NfGnJr42nWa1xHxaoQJ:b2ni9ah) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L74)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I'm okay with that--can you create an issue and link it here?
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2023-09-26 14:08 UTC, lambda7xx reviewed
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/991)* status: 2 of 5 files reviewed, 15 unresolved discussions (waiting on @lockshaw)

___
*[`lib/utils/include/utils/parse.h` line 123 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0xUc-7bUZt5QSfgx1:-NfGoK5y9Q7XrOL8fMNP:b-896fix) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L123)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

This should go into `runtime`. `utils/parse` should just be a command-line parsing library with no explicit link to flexflow, and then `runtime` can use `utils/parse` for any flexflow-specific command line argument parsing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-26 15:17 UTC, lambda7xx commented
*[`lib/utils/src/parse.cc` line 47 at r3](https://reviewable.io/reviews/flexflow/FlexFlow/991#-NdpvQ7l00J4WF1FXPV2:-NfH3AW32igGggukGPDy:b-bl7qf2) ([raw file](https://github.com/flexflow/FlexFlow/blob/8f04a1a91704eed7f65b2b8e76ab935918a63d1d/lib/utils/src/parse.cc#L47)):*
> ```cpp
>   args.showDescriptions();
>   return out;
> }
> ```

i set a new issue for it


<!-- Sent from Reviewable.io -->

2023-09-28 15:12 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0ya7Q2yDZDnbZqMqB:-NfRLCQX5P_mOSc1JgMb:bti558a) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L24)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

I know: it should only support `--size`, not `size` -- supporting both is incorrect
</blockquote></details>

so, if we pass the `size`, it will be error and throw an exceptions?


<!-- Sent from Reviewable.io -->

2023-10-01 02:46 UTC, lockshaw requested changes
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/991)* status: 0 of 5 files reviewed, 15 unresolved discussions (waiting on @lambda7xx and @wmdi)

___
*[`lib/utils/include/utils/parse.h` line 24 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0ya7Q2yDZDnbZqMqB:-Nfd74dK8jsfFJK38_uu:b-grr5n) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L24)):*
<details><summary><i>Previously, lambda7xx (Lambda(Xiaoxiang) Shi ) wrote…</i></summary><blockquote>

so, if we pass the `size`, it will be error and throw an exceptions?
</blockquote></details>

Yes (ideally if used interactively it would print an error message, but just throwing an exception is fine for now)


<!-- Sent from Reviewable.io -->

2024-01-19 09:27 UTC, lockshaw reviewed
I'm still seeing lots of open comments--can you go through and mark the ones you think you've resolved as "Done" and try to resolve any that aren't currently fixed?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/991#-:-NoW1sc22yeHzrsIEJw6:b7fkxfm)* status: 0 of 5 files reviewed, 15 unresolved discussions (waiting on @lambda7xx and @wmdi)



<!-- Sent from Reviewable.io -->

2024-02-10 12:46 UTC, lambda7xx commented
*[`lib/utils/include/utils/parse.h` line 74 at r1](https://reviewable.io/reviews/flexflow/FlexFlow/991#-Nd0z6rKByzQ67Xd8_hz:-NqI293zBc_rJVESlLML:b-h5hhsk) ([raw file](https://github.com/flexflow/FlexFlow/blob/ca7f9a197f25bd105b5aa9184cf640c88d4bc9de/lib/utils/include/utils/parse.h#L74)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Please link the issue here
</blockquote></details>

Done. [Implement command line parsing and help printing · Issue #942 · flexflow/FlexFlow (github.com)](https://github.com/flexflow/FlexFlow/issues/942)


<!-- Sent from Reviewable.io -->

2024-09-08 06:34 UTC, lockshaw commented
Superseded by #1490

2024-09-08 06:34 UTC, closed without merging